### ISSUE TITLE
Notification-related traceback when logging in

### ISSUE THREAD

**Issue by riovan** [tgalal/yowsup#1000]
When logging in, for example with
python yowsup-cli demos -y --config d:\user.conf
I get this:

Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
Auth: Logged in!
[connected]:Traceback (most recent call last):
  File "yowsup-cli", line 327, in <module>
    if not parser.process():
  File "yowsup-cli", line 231, in process
    self.startCmdline()
  File "yowsup-cli", line 259, in startCmdline
    stack.start()
  File "D:\repositories\yowsup\yowsup\demos\cli\stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "D:\repositories\yowsup\yowsup\stacks\yowstack.py", line 183, in loop
    asyncore.loop(*args, **kwargs)
  File "C:\Python27\Lib\asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "C:\Python27\Lib\asyncore.py", line 156, in poll
    read(obj)
  File "C:\Python27\Lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Python27\Lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\Lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "D:\repositories\yowsup\yowsup\layers\network\layer.py", line 84, in hand
le_read
    self.receive(data)
  File "D:\repositories\yowsup\yowsup\layers\network\layer.py", line 91, in rece
ive
    self.toUpper(data)
  File "D:\repositories\yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\repositories\yowsup\yowsup\layers\stanzaregulator\layer.py", line 28,
 in receive
    self.processReceived()
  File "D:\repositories\yowsup\yowsup\layers\stanzaregulator\layer.py", line 48,
 in processReceived
    self.toUpper(oneMessageData)
  File "D:\repositories\yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\repositories\yowsup\yowsup\layers\auth\layer_crypt.py", line 63, in r
eceive
    self.toUpper(payload)
  File "D:\repositories\yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\repositories\yowsup\yowsup\layers\coder\layer.py", line 35, in receiv
e
    self.toUpper(node)
  File "D:\repositories\yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\repositories\yowsup\yowsup\layers\logger\layer.py", line 14, in recei
ve
    self.toUpper(data)
  File "D:\repositories\yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\repositories\yowsup\yowsup\layers\__init__.py", line 169, in receive
    s.receive(data)
  File "D:\repositories\yowsup\yowsup\layers\__init__.py", line 105, in receive
    recv(node)
  File "D:\repositories\yowsup\yowsup\layers\protocol_notifications\layer.py", l
ine 41, in recvNotification
    self.raiseErrorForNode(node)
  File "D:\repositories\yowsup\yowsup\layers\__init__.py", line 121, in raiseErr
orForNode
    raise ValueError("Unimplemented notification type %s " % node)
ValueError: Unimplemented notification type <notification type="encrypt" offline
="2" from="s.whatsapp.net" id="3971826177" t="1439016107">
<count value="0">
</count>
</notification>

I'm using the yowsup-cli script, on windows. Before a few days ago yowsup worked fine.

**Comment by francesconuma** [comment]
Type /help for available commands

[offline]:L
[offline]:/L
Auth: Logged in!
[connected]:Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.3.185', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 327, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 259, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/demos/cli/stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/stacks/yowstack.py", line 167, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/network/layer.py", line 73, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/network/layer.py", line 80, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 160, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 101, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/protocol_notifications/layer.py", line 41, in recvNotification
    self.raiseErrorForNode(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 117, in raiseErrorForNode
    raise ValueError("Unimplemented notification type %s " % node)
ValueError: Unimplemented notification type <notification type="encrypt" offline="1" from="s.whatsapp.net" id="2137347882" t="1441215094">
<count value="0">
</count>
</notification>



Similari on rasp bian

**Comment by tgalal** [comment]
need to have axolotl layer in stack
