### ISSUE TITLE
Python3: Generating axolotl key fails ? 

### ISSUE THREAD

**Issue by ThomasRgbg** [tgalal/yowsup#1002]
I just ported my scripts to python3 (3.2), but now the key generation fails. Starting the sam script with Python 2.7 works. 

```

12:32:11 DEBUG:yowsup.layers.logger.layer:receive:rx:
<success status="active" kind="free" creation="1421686494" expiration="1453222494" props="4" t="1439721130">
©ÆeÁ▒:jÞ}Pwi$
HEX3:b'a9c665c18813183a6ade1f7d5093877769240508'
</success>

12:32:11 DEBUG:yowsup.layers.protocol_iq.layer:onEvent:starting ping thread.
12:32:11 INFO:yowsup.layers.axolotl.layer:onEvent:Axolotl layer is generating keys
Traceback (most recent call last):
  File "/usr/local/bin/wa_user.py", line 114, in <module>
    stack.loop(timeout=2, count=1) # Let the taskloop run one time for 2 seconds 
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/stacks/yowstack.py", line 175, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.2/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.2/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python3.2/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.2/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.2/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/network/layer.py", line 73, in handle_read
    self.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/network/layer.py", line 80, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/axolotl/layer.py", line 112, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/__init__.py", line 160, in receive
    s.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/__init__.py", line 101, in receive
    recv(node)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/auth/layer_authentication.py", line 59, in handleSuccess
    self.broadcastEvent(successEvent)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/__init__.py", line 168, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/__init__.py", line 72, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/axolotl/layer.py", line 82, in onEvent
    self.sendKeys()
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/axolotl/layer.py", line 280, in sendKeys
    preKeysDict[self.adjustId(preKey.getId())] = self.adjustArray(keyPair.getPublicKey().serialize()[1:])
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.3.185-py3.2.egg/yowsup/layers/axolotl/layer.py", line 352, in adjustId
    return binascii.unhexlify(_id)
TypeError: 'str' does not support the buffer interface
```

**Comment by ThomasRgbg** [comment]
Duplicate of #971 . The needed bugfix is also mentioned there.
