### ISSUE TITLE
AttributeError with ImageDownloadableMediaMessageProtocolEntity

### ISSUE THREAD

**Issue by janboll** [tgalal/yowsup#1009]
Hi,

i recently encountered a mysterious behaviour with while using the MediaUploader.  On the first try of uploading an image i receive an Exception (AttributeError), on the second try sending the message succeedes.
If you review the subsequent debug output, you will see that the image must have been already uploaded in the first try. Therefore i assume the error must be somehow related to yowsup.

I will try to further investigate this issue, but any help or advice would be appreciated.

## First try
```
2015-08-20 09:56:13,380 - INFO: Sending WhatsApp Message to WhatsApp-Sender-ID: XXXXX@s.whatsapp.net
2015-08-20 09:56:13,381 - DEBUG: sending media Upload Request for receipt XXXXX@s.whatsapp.net and media c:\Users\lokal\PycharmProjects\WhatsApp\image_archive\testbild.png
2015-08-20 09:56:13,381 - DEBUG: tx:
<iq to="s.whatsapp.net" xmlns="w:m" type="set" id="2">
<media type="image" hash="jU98DMx41aqCLH+r33MpceynGL4UNJ5wdcc4ZY73RvA=" size="6992">
</media>
</iq>

2015-08-20 09:56:14,980 - DEBUG: rx:
<iq type="result" from="s.whatsapp.net" id="2">
<media url="https://mmi611.whatsapp.net/u/YVJNRZowxb-bqLH5U7UeQrE2gjoABR25fEnCKg/AunpLv_quz4c3ZLkvhdLzOqbGztzcLUcf56D6gHgnCL2" ip="184.173.204.54">
</media>
</iq>

2015-08-20 09:56:17,243 - ERROR: Error occured at transfer 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "C:\python\virtual_envs\whatsapp\lib\site-packages\yowsup\layers\protocol_media\mediauploader.py", line 137, in run
    self.successCallback(sourcePath, self.jid, result["url"])
  File "C:\Users\lokal\PycharmProjects\WhatsApp\WhatsAppLayer.py", line 141, in onUploadSuccess
    self.doSendImage(filePath, url, jid)
  File "C:\Users\lokal\PycharmProjects\WhatsApp\WhatsAppLayer.py", line 122, in doSendImage
    entity = ImageDownloadableMediaMessageProtocolEntity.fromFilePath(filePath, url, ip, to, caption=caption.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'
2015-08-20 09:56:17,243 - ERROR: WhatsAppLayer: Upload file c:\Users\lokal\PycharmProjects\WhatsApp\image_archive\testbild.png to https://mmi611.whatsapp.net/u/YVJNRZowxb-bqLH5U7UeQrE2gjoABR25fEnCKg/AunpLv_quz4c3ZLkvhdLzOqbGztzcLUcf56D6gHgnCL2 for XXXXX@s.whatsapp.net failed!
```

## Second try
```
2015-08-20 09:58:43,358 - INFO: Sending WhatsApp Message to WhatsApp-Sender-ID: XXXXX@s.whatsapp.net
2015-08-20 09:58:43,358 - DEBUG: sending media Upload Request for receipt XXXXX@s.whatsapp.net and media c:\Users\lokal\PycharmProjects\WhatsApp\image_archive\testbild.png
2015-08-20 09:58:43,358 - DEBUG: tx:
<iq to="s.whatsapp.net" xmlns="w:m" type="set" id="1">
<media type="image" hash="jU98DMx41aqCLH+r33MpceynGL4UNJ5wdcc4ZY73RvA=" size="6992">
</media>
</iq>

2015-08-20 09:58:43,453 - DEBUG: rx:
<iq type="result" from="s.whatsapp.net" id="1">
<duplicate mimetype="image/png" filehash="jU98DMx41aqCLH+r33MpceynGL4UNJ5wdcc4ZY73RvA=" url="https://mmi611.whatsapp.net/d/AunpLv_quz4c3ZLkvhdLzOqbGztzcLUcf56D6gHgnCL2.png" height="648" width="1152" type="image" size="6992">
</duplicate>
</iq>

2015-08-20 09:58:43,631 - DEBUG: tx:
<message to="XXXXX@s.whatsapp.net" type="media" id="1440057523-2">
[ENCODED DATA]
</message>
```

**Comment by janboll** [comment]
this was my mistake :-(

**Comment by charanjit-singh** [comment]
Hello Jan-Hendrik Boll 

Can you please tell how to download Media Content ??

Thanks in Advance.
