### ISSUE TITLE
Yowsup just closes after sending a message

### ISSUE THREAD

**Issue by carlosdiaz** [tgalal/yowsup#1022]
After updating to the latest release and trying to send a message the process just closes:

```console
/message send 52XXX Hi
[connected]:
Sent: 14YYY-X
[connected]:
Traceback (most recent call last):
  File "yowsup-cli", line 327, in <module>
    if not parser.process():
  File "yowsup-cli", line 231, in process
    self.startCmdline()
  File "yowsup-cli", line 259, in startCmdline
    stack.start()
  File "/yowsup/yowsup/demos/cli/stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/yowsup/yowsup/stacks/yowstack.py", line 167, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 444, in handle_read_event
    self.handle_read()
  File "/yowsup/yowsup/layers/network/layer.py", line 73, in handle_read
    self.receive(data)
  File "/yowsup/yowsup/layers/network/layer.py", line 80, in receive
    self.toUpper(data)
  File "/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/yowsup/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/yowsup/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/yowsup/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/yowsup/yowsup/layers/__init__.py", line 160, in receive
    s.receive(data)
  File "/yowsup/yowsup/layers/__init__.py", line 101, in receive
    recv(node)
  File "/yowsup/yowsup/layers/protocol_notifications/layer.py", line 41, in recvNotification
    self.raiseErrorForNode(node)
  File "/yowsup/yowsup/layers/__init__.py", line 117, in raiseErrorForNode
    raise ValueError("Unimplemented notification type %s " % node)
ValueError: Unimplemented notification type <notification type="encrypt" from="s.whatsapp.net" id="27852XXX" t="14408XXX">
<count value="0">
</count>
</notification>
```

**Comment by carlosdiaz** [comment]
My bad, I realized that using moxie library solves this.

```console
python yowsup-cli demos --moxie --y -c
```
Closing issue.
