### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getData' at Logging in

### ISSUE THREAD

**Issue by oriolrd** [tgalal/yowsup#1031]
Hi,
After doing the registration I sent a "Hello" message to my phone number, and when I replied it from my phone I received this error message. From that moment, every time I try to log in it crashes showing this message:

```
[offline]:/L
Auth: Logged in!
[connected]:Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.3.185', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 327, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 259, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/demos/cli/stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/stacks/yowstack.py", line 167, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/network/layer.py", line 73, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/network/layer.py", line 80, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 160, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 101, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'
```

Any solution? Thank you!

**Comment by gonzalosr** [comment]
Hi, you should enable the axolotl layer.

If using yowsup-cli add --moxie switch to enable it.

**Comment by Dl0tt** [comment]
updating yowsup will fix it

-------- Original Message --------

**Comment by oriolrd** [comment]
I finally solved it using moxie. After running 
```
yowsup-cli demos -m --yowsup --config config
```
I could send and receive messages. Thank you!!!

**Comment by neeraj3011** [comment]
i am getting same error after updating yowsup also

**Comment by oriolrd** [comment]
I updated Yowsup yesterday and after that I had to stop writing the `-m` command, it's just the opposite

**Comment by neeraj3011** [comment]
i also did the same but still receiving the same error

**Comment by neeraj3011** [comment]
One more error i recieve every time 

File "/root/virtenvs/yutility/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/root/virtenvs/yutility/local/lib/python2.7/site-packages/yowsup/layers/auth/layer_authentication.py", line 89, in handleStreamError
    raise AuthError("Unhandled stream:error node:\n%s" % node)
yowsup.layers.auth.autherror.AuthError: Unhandled stream:error node:

**Comment by idigevian** [comment]
I am getting the same error and have created the following ticket: https://github.com/tgalal/yowsup/issues/1103

One observation i have is, if you create a group, this problem of -> "'NoneType' object has no attribute 'getData'" doesn't come up.

Any help is much appreciated!
