### ISSUE TITLE
yowsup registration

### ISSUE THREAD

**Issue by brekler** [tgalal/yowsup#1040]
Hello, im trying to register my number with yowsup and im having this error... any ideas ?

yowsup-cli registration -r sms -c /etc/zabbix/zap.conf
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4', 'yowsup-cli')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/yowsup2-2.4-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>

  File "/usr/lib/python2.7/site-packages/yowsup2-2.4-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 158, in process

  File "/usr/lib/python2.7/site-packages/yowsup2-2.4-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 176, in handleRequestCode

  File "build/bdist.linux-x86_64/egg/yowsup/registration/coderequest.py", line 46, in send
  File "build/bdist.linux-x86_64/egg/yowsup/common/http/warequest.py", line 73, in send
  File "build/bdist.linux-x86_64/egg/yowsup/common/http/warequest.py", line 111, in sendGetRequest
  File "build/bdist.linux-x86_64/egg/yowsup/common/http/warequest.py", line 167, in sendRequest
  File "/usr/lib64/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 113] No route to host

**Comment by ale-rinaldi** [comment]
It really seems like your PC is unable to reach the Whatsapp server. Are you sure you aren't behind a firewall that blocks Whatsapp usage?

**Comment by brekler** [comment]
yes... this server has all access on the network

**Comment by brekler** [comment]
just tested with my phone giving all privileges on my network like my server... whatsapp worked fine

**Comment by ale-rinaldi** [comment]
This happened to me one time 'cause I set a wrong subnet mask on my connection. If I remember correctly, Whatsapp server is 173.192.222.170 and it's really near to the 172.0.0.0/8 class used on internal networks. Please try to ping 173.192.222.170 (or c2.whatsapp.net) and see how it works.

**Comment by brekler** [comment]
Dude! you were right!
Our firewall had a block against whatsapp, i asked the FW dude to fix that and it worked! thanks

**Comment by ivanbaldo** [comment]
Please close this issue @brekler , thanks!
