### ISSUE TITLE
Error running Command Line interface demo

### ISSUE THREAD

**Issue by msanchezt** [tgalal/yowsup#1042]
Trying to run Command Line interface demo, I get this error:

root@RaspberryPI:/home/pi/yowsup# ./yowsup-cli demos -y
Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 227, in process
    self.startCmdline()
  File "./yowsup-cli", line 249, in startCmdline
    from yowsup.demos import cli
  File "/home/pi/yowsup/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/home/pi/yowsup/yowsup/demos/cli/stack.py", line 2, in <module>
    from .layer import YowsupCliLayer
  File "/home/pi/yowsup/yowsup/demos/cli/layer.py", line 1, in <module>
    from .cli import Cli, clicmd
  File "/home/pi/yowsup/yowsup/demos/cli/cli.py", line 9, in <module>
    import pyreadline as readline
  File "/usr/local/lib/python2.7/dist-packages/pyreadline/__init__.py", line 9, in <module>
    import unicode_helper, logger, clipboard, lineeditor, modes, console
  File "/usr/local/lib/python2.7/dist-packages/pyreadline/modes/__init__.py", line 2, in <module>
    import emacs,notemacs,vi
  File "/usr/local/lib/python2.7/dist-packages/pyreadline/modes/emacs.py", line 15, in <module>
    import basemode
  File "/usr/local/lib/python2.7/dist-packages/pyreadline/modes/basemode.py", line 12, in <module>
    from   pyreadline.keysyms.common import make_KeyPress_from_keydescr
  File "/usr/local/lib/python2.7/dist-packages/pyreadline/keysyms/__init__.py", line 20, in <module>
    raise ImportError(u"Could not import keysym for local pythonversion", x)
ImportError: (u'Could not import keysym for local pythonversion', ImportError('cannot import name windll',))
root@RaspberryPI:/home/pi/yowsup#

**Comment by tgalal** [comment]
google those errors please as they're not yowsup related.
