### ISSUE TITLE
DecodeError: Truncated message

### ISSUE THREAD

**Issue by Marcello87** [tgalal/yowsup#1050]
Fresh installation on new server don't work.
--moxie don't work: demos: error: unrecognized arguments: --moxie

I also try a few python versions 2.6, 2.7, 3.4.3, always same error, what could i do?

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
  File "/opt/install/yowsup-master/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/opt/install/yowsup-master/yowsup-cli", line 231, in process
    self.startSendClient()
  File "/opt/install/yowsup-master/yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/opt/install/yowsup-master/yowsup/demos/sendclient/stack.py", line 54, in start
    self.stack.loop()
  File "/opt/install/yowsup-master/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/opt/install/yowsup-master/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/opt/install/yowsup-master/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/opt/install/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/opt/install/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/opt/install/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/opt/install/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/opt/install/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/opt/install/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/opt/install/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/opt/install/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/opt/install/yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/opt/install/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/opt/install/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/opt/install/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/opt/install/yowsup-master/yowsup/layers/axolotl/layer.py", line 126, in receive
    self.toUpper(protocolTreeNode)
  File "/opt/install/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/opt/install/yowsup-master/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/opt/install/yowsup-master/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/opt/install/yowsup-master/yowsup/layers/auth/layer_authentication.py", line 71, in handleSuccess
    self.toUpper(nodeEntity)
  File "/opt/install/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/opt/install/yowsup-master/yowsup/layers/interface/interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "/opt/install/yowsup-master/yowsup/demos/sendclient/layer.py", line 35, in onSuccess
    self.toLower(messageEntity)
  File "/opt/install/yowsup-master/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/opt/install/yowsup-master/yowsup/layers/__init__.py", line 173, in send
    s.send(data)
  File "/opt/install/yowsup-master/yowsup/layers/__init__.py", line 111, in send
    send(entity)
  File "/opt/install/yowsup-master/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/opt/install/yowsup-master/yowsup/layers/__init__.py", line 115, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/opt/install/yowsup-master/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/opt/install/yowsup-master/yowsup/layers/axolotl/layer.py", line 107, in send
    self.handlePlaintextNode(node)
  File "/opt/install/yowsup-master/yowsup/layers/axolotl/layer.py", line 190, in handlePlaintextNode
    ciphertext = sessionCipher.encrypt(plaintext)
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessioncipher.py", line 38, in encrypt
    sessionRecord   = self.sessionStore.loadSession(self.recipientId, self.deviceId)
  File "/opt/install/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 47, in loadSession
    return self.sessionStore.loadSession(recepientId, deviceId)
  File "/opt/install/yowsup-master/yowsup/layers/axolotl/store/sqlite/litesessionstore.py", line 20, in loadSession
    return SessionRecord(serialized=result[0])
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/state/sessionrecord.py", line 16, in __init__
    record.ParseFromString(serialized)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0_alpha_1-py2.7.egg/google/protobuf/message.py", line 186, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0_alpha_1-py2.7.egg/google/protobuf/internal/python_message.py", line 859, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0_alpha_1-py2.7.egg/google/protobuf/internal/python_message.py", line 892, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0_alpha_1-py2.7.egg/google/protobuf/internal/decoder.py", line 652, in DecodeField
    raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

Thanks a lot!

**Comment by Marcello87** [comment]
I've done a fresh install, now it works without errors!
Close
