### ISSUE TITLE
cannot import name symbol_database

### ISSUE THREAD

**Issue by hsimosa** [tgalal/yowsup#1053]
After installing YOWSUP 2.4 following your instructions and configuring yowsup-cli.config after receiving registration correctly I tried to run demos example:
hector@hector:~/yowsup$ yowsup-cli demos --config yowsup-cli.config --send 58XXXXXXXXXX "Hello world"
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4', 'yowsup-cli')
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 735, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 1659, in run_script
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 279, in startSendClient
  File "build/bdist.linux-x86_64/egg/yowsup/demos/sendclient/stack.py", line 24, in **init**
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/**init**.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/util/keyhelper.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/identitykeypair.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/state/storageprotos.py", line 9, in <module>
ImportError: cannot import name symbol_database

Previous suggestions lead me to:
checking for protobuf version:

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
Type "copyright", "credits" or "license" for more information.
IPython 1.2.1 -- An enhanced Interactive Python.

In [1]: from google import protobuf
In [2]: print(protobuf.**version**)
3.0.0-alpha-1

Installed protobuf from: https://github.com/google/protobuf/
Similar procedures for: python-axolotl-curve25519 from: http://github.com/tgalal/python-axolotl
Follow procedure from: https://github.com/tgalal/yowsup/issues/523
All depencies installed correctly.

Still same error message. What I'm missing?
Your help is appreciated.
##

**Comment by DomineCabra** [comment]
I've hit the same problem on a fresh install of yowsup on Linux (Mint); after downloading the latest from git.

Requesting SMS and registering a phone number works fine, but trying to run the echo demo or the send message one throws this error.

Any ideas?

**Comment by eskorbutin** [comment]
I've hit the same error after downloading the latest from source and installing on a brand new Linux virtual machine (Mint on hyper-v).

Requesting SMS and registering the number with the resulting SMS seems to work just fine, but running the send demo or the echo one throws this error.

Any ideas?
