### ISSUE TITLE
EXCEPTION:    self.getLayerInterface(YowAuthenticationProtocolLayer).setCredentials(username, password) TypeError: setCredentials() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by naghizadeh** [tgalal/yowsup#1061]
Yowsup Cli client
==================
Type /help for available commands

[offline]:/login PHON  HASH
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/tmp/yowsup/yowsup/demos/cli/cli.py", line 154, in startInputThread
    wait = self.execCmd(cmd)
  File "/tmp/yowsup/yowsup/demos/cli/cli.py", line 138, in execCmd
    return self.doExecCmd(lambda :targetFn(*args))
  File "/tmp/yowsup/yowsup/demos/cli/cli.py", line 141, in doExecCmd
    return fn()
  File "/tmp/yowsup/yowsup/demos/cli/cli.py", line 138, in <lambda>
    return self.doExecCmd(lambda :targetFn(*args))
  File "/tmp/yowsup/yowsup/demos/cli/layer.py", line 425, in login
    self.setCredentials(username, b64password)
  File "/tmp/yowsup/yowsup/demos/cli/layer.py", line 82, in setCredentials
    self.getLayerInterface(YowAuthenticationProtocolLayer).setCredentials(username, password)
TypeError: setCredentials() takes exactly 2 arguments (3 given)

**Comment by naghizadeh** [comment]
--- a/yowsup/demos/cli/layer.py
+++ b/yowsup/demos/cli/layer.py
@@ -79,7 +79,8 @@ class YowsupCliLayer(Cli, YowInterfaceLayer):
         return "%s@s.whatsapp.net" % number
 
     def setCredentials(self, username, password):
-        self.getLayerInterface(YowAuthenticationProtocolLayer).setCredentials(username, password)
+        credent=(username,password)
+        self.getLayerInterface(YowAuthenticationProtocolLayer).setCredentials(credent)

**Comment by yniv** [comment]
I'm having this problem too. any solution?

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "server.py", line 41, in whatsAppClientThread
    WhatsAppClient(soc).start()
  File "/home/bumptestlin/server/whatsapp_client.py", line 53, in start
    stack.loop()
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 126, in receive
    self.toUpper(protocolTreeNode)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_authentication.py", line 71, in handleSuccess
    self.toUpper(nodeEntity)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/interface/interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "/home/bumptestlin/server/bumpyard_layer.py", line 136, in onSuccess
    self.setCredentials(self.credentials[0],self.credentials[1]);
  File "/home/bumptestlin/server/bumpyard_layer.py", line 87, in setCredentials
    self.getLayerInterface(YowAuthenticationProtocolLayer).setCredentials(username, password)
TypeError: setCredentials() takes exactly 2 arguments (3 given)
