### ISSUE TITLE
Error send msg using demo

### ISSUE THREAD

**Issue by rlljorge** [tgalal/yowsup#1062]
[root@server-zbx-node01 yowsup]# ./yowsup-cli demos -c config -s 5511XXXXXXX teste -d
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e16.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
stream:features
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
/stream:features

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="5511955502582" mechanism="WAUTH-2">
▒▒}▒▒▒}▒߾▒▒(Aq▒3▒X}▒ڽ ▒zi▒▒▒▒▒UO1WE▒d'▒(.▒
HEX:c2fab27dc2f7ce7dafdfbe8bde284171d333c61c587da1dabd20cd7a69989da890b21f554f315745d46427d2282e82
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
stream:features
/stream:features

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1442935471" expiration="1474471471" props="4" t="1442936920">
▒▒f▒▒`*▒j▒▒?tl▒O▒
HEX:0705a4936684c9602af86a80a73f746c17dd4fc0
</success>

Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 231, in process
    self.startSendClient()
  File "./yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/u01/yowsup/yowsup/demos/sendclient/stack.py", line 54, in start
    self.stack.loop()
  File "/u01/yowsup/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib64/python2.6/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.6/asyncore.py", line 151, in poll
    read(obj)
  File "/usr/lib64/python2.6/asyncore.py", line 82, in read
    obj.handle_error()
  File "/usr/lib64/python2.6/asyncore.py", line 78, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.6/asyncore.py", line 428, in handle_read_event
    self.handle_read()
  File "/u01/yowsup/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/u01/yowsup/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/u01/yowsup/yowsup/layers/**init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/u01/yowsup/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/u01/yowsup/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/u01/yowsup/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/u01/yowsup/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/u01/yowsup/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/u01/yowsup/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/u01/yowsup/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/u01/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/u01/yowsup/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/u01/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/u01/yowsup/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/u01/yowsup/yowsup/layers/axolotl/layer.py", line 126, in receive
    self.toUpper(protocolTreeNode)
  File "/u01/yowsup/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/u01/yowsup/yowsup/layers/__init**.py", line 169, in receive
    s.receive(data)
  File "/u01/yowsup/yowsup/layers/**init**.py", line 105, in receive
    recv(node)
  File "/u01/yowsup/yowsup/layers/auth/layer_authentication.py", line 71, in handleSuccess
    self.toUpper(nodeEntity)
  File "/u01/yowsup/yowsup/layers/**init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/u01/yowsup/yowsup/layers/interface/interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "/u01/yowsup/yowsup/demos/sendclient/layer.py", line 35, in onSuccess
    self.toLower(messageEntity)
  File "/u01/yowsup/yowsup/layers/__init**.py", line 63, in toLower
    self.**lower.send(data)
  File "/u01/yowsup/yowsup/layers/__init**.py", line 173, in send
    s.send(data)
  File "/u01/yowsup/yowsup/layers/**init**.py", line 111, in send
    send(entity)
  File "/u01/yowsup/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/u01/yowsup/yowsup/layers/**init**.py", line 115, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/u01/yowsup/yowsup/layers/**init**.py", line 63, in toLower
    self.**lower.send(data)
  File "/u01/yowsup/yowsup/layers/axolotl/layer.py", line 107, in send
    self.handlePlaintextNode(node)
  File "/u01/yowsup/yowsup/layers/axolotl/layer.py", line 190, in handlePlaintextNode
    ciphertext = sessionCipher.encrypt(plaintext)
  File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/sessioncipher.py", line 38, in encrypt
    sessionRecord   = self.sessionStore.loadSession(self.recipientId, self.deviceId)
  File "/u01/yowsup/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 47, in loadSession
    return self.sessionStore.loadSession(recepientId, deviceId)
  File "/u01/yowsup/yowsup/layers/axolotl/store/sqlite/litesessionstore.py", line 20, in loadSession
    return SessionRecord(serialized=result[0])
  File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/state/sessionrecord.py", line 16, in __init**
    record.ParseFromString(serialized)
  File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/message.py", line 186, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/internal/python_message.py", line 859, in MergeFromString
PuTTY    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/internal/python_message.py", line 892, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/internal/decoder.py", line 652, in DecodeField
    raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
##

**Comment by rlljorge** [comment]
I added the option -M (--unmoxie) and I can send message with success !
What package i need install to send encrypted messages ?

**Comment by WildSix** [comment]
Hi, so how can i disable encryption in code? i am using newest yowsup with python 3.4.2 on raspberry pi 3, and sample code worked on python 2, but i need to switch to python 3. sample code starts but when when it want send a message i get this error, when sending message through cli shows up the same error, with -M parameter it sends message without error

**Comment by jlguardi** [comment]
Be careful sending messages without encryption. WA could ban you due to it is an unexpected working flow.
See #1590 for python3 and protobuf

**Comment by WildSix** [comment]
thank You for this tip, i dont care it will be wih encryption or not, i need it working on python3 ;) thanks you for pointing this issue, i am going there to look for solution.
