### ISSUE TITLE
Not able to send message from command line interface

### ISSUE THREAD

**Issue by naveen1988** [tgalal/yowsup#1064]
I have installed yowsup in my linux server, I have registered my number using "python yowsup-cli registration --requestcode sms --phone 91xxxxxxxxxx --cc 91 --mcc 404 --mnc 45" command and i got a reply with password. I updated config file with new password. But still i am unable to send message using command line interface "yowsup-cli demos --config config.txt --send 91xxxxxxxxxx "Hello world"".
I am getting the following output

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
File "yowsup-cli", line 323, in 
if not parser.process():
File "yowsup-cli", line 231, in process
self.startSendClient()
File "yowsup-cli", line 280, in startSendClient
stack.start()
File "/yowsup-2.4/yowsup/demos/sendclient/stack.py", line 54, in start
self.stack.loop()
File "/yowsup-2.4/yowsup/stacks/yowstack.py", line 195, in loop
asyncore.loop(args, *kwargs)
File "/usr/lib/python2.6/asyncore.py", line 210, in loop
poll_fun(timeout, map)
File "/usr/lib/python2.6/asyncore.py", line 151, in poll
read(obj)
File "/usr/lib/python2.6/asyncore.py", line 82, in read
obj.handle_error()
File "/usr/lib/python2.6/asyncore.py", line 78, in read
obj.handle_read_event()
File "/usr/lib/python2.6/asyncore.py", line 428, in handle_read_event
self.handle_read()
File "/yowsup-2.4/yowsup/layers/network/layer.py", line 86, in handle_read
self.receive(data)
File "/yowsup-2.4/yowsup/layers/network/layer.py", line 94, in receive
self.toUpper(data)
File "/yowsup-2.4/yowsup/layers/init.py", line 59, in toUpper
self.upper.receive(data)
File "/yowsup-2.4/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
self.processReceived()
File "/yowsup-2.4/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
self.processReceived()
File "/yowsup-2.4/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
self.processReceived()
File "/yowsup-2.4/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
self.toUpper(oneMessageData)
File "/yowsup-2.4/yowsup/layers/__init.py", line 59, in toUpper
self.upper.receive(data)
File "/yowsup-2.4/yowsup/layers/auth/layer_crypt.py", line 63, in receive
self.toUpper(payload)
File "/yowsup-2.4/yowsup/layers/__init.py", line 59, in toUpper
self.upper.receive(data)
File "/yowsup-2.4/yowsup/layers/coder/layer.py", line 35, in receive
self.toUpper(node)
File "/yowsup-2.4/yowsup/layers/__init.py", line 59, in toUpper
self.upper.receive(data)
File "/yowsup-2.4/yowsup/layers/logger/layer.py", line 14, in receive
self.toUpper(data)
File "/yowsup-2.4/yowsup/layers/__init.py", line 59, in toUpper
self.upper.receive(data)
File "/yowsup-2.4/yowsup/layers/axolotl/layer.py", line 126, in receive
self.toUpper(protocolTreeNode)
File "/yowsup-2.4/yowsup/layers/__init.py", line 59, in toUpper
self.upper.receive(data)
File "/yowsup-2.4/yowsup/layers/__init.py", line 169, in receive
s.receive(data)
File "/yowsup-2.4/yowsup/layers/init.py", line 105, in receive
recv(node)
File "/yowsup-2.4/yowsup/layers/auth/layer_authentication.py", line 71, in handleSuccess
self.toUpper(nodeEntity)
File "/yowsup-2.4/yowsup/layers/init.py", line 59, in toUpper
self.upper.receive(data)
File "/yowsup-2.4/yowsup/layers/interface/interface.py", line 98, in receive
self.callbacksentityType
File "/yowsup-2.4/yowsup/demos/sendclient/layer.py", line 35, in onSuccess
self.toLower(messageEntity)
File "/yowsup-2.4/yowsup/layers/__init.py", line 63, in toLower
self.lower.send(data)
File "/yowsup-2.4/yowsup/layers/__init.py", line 173, in send
s.send(data)
File "/yowsup-2.4/yowsup/layers/init.py", line 111, in send
send(entity)
File "/yowsup-2.4/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
self.entityToLower(entity)
File "/yowsup-2.4/yowsup/layers/init.py", line 115, in entityToLower
self.toLower(entity.toProtocolTreeNode())
File "/yowsup-2.4/yowsup/layers/init.py", line 63, in toLower
self.lower.send(data)
File "/yowsup-2.4/yowsup/layers/axolotl/layer.py", line 107, in send
self.handlePlaintextNode(node)
File "/yowsup-2.4/yowsup/layers/axolotl/layer.py", line 190, in handlePlaintextNode
ciphertext = sessionCipher.encrypt(plaintext)
File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/sessioncipher.py", line 38, in encrypt
sessionRecord = self.sessionStore.loadSession(self.recipientId, self.deviceId)
File "/yowsup-2.4/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 47, in loadSession
return self.sessionStore.loadSession(recepientId, deviceId)
File "/yowsup-2.4/yowsup/layers/axolotl/store/sqlite/litesessionstore.py", line 20, in loadSession
return SessionRecord(serialized=result[0])
File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/state/sessionrecord.py", line 16, in __init
record.ParseFromString(serialized)
File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/message.py", line 186, in ParseFromString
self.MergeFromString(serialized)
File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/internal/python_message.py", line 859, in MergeFromString
if self._InternalParse(serialized, 0, length) != length:
File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/internal/python_message.py", line 892, in InternalParse
pos = field_decoder(buffer, new_pos, end, self, field_dict)
File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/internal/decoder.py", line 652, in DecodeField
raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

Please anyone help me how to fix it. Thanks in advance
##

**Comment by naveen1988** [comment]
Even i am getting this error when i try to login 

Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4', 'yowsup-cli')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 227, in process
    self.startCmdline()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 255, in startCmdline
    stack.start()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/demos/cli/stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.6/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.6/asyncore.py", line 151, in poll
    read(obj)
  File "/usr/lib/python2.6/asyncore.py", line 82, in read
    obj.handle_error()
  File "/usr/lib/python2.6/asyncore.py", line 78, in read
    obj.handle_read_event()
  File "/usr/lib/python2.6/asyncore.py", line 425, in handle_read_event
    self.handle_connect_event()
  File "/usr/lib/python2.6/asyncore.py", line 431, in handle_connect_event
    self.handle_connect()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/network/layer.py", line 68, in handle_connect
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/__init__.py", line 72, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/__init__.py", line 72, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/__init__.py", line 66, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/coder/layer.py", line 26, in onEvent
    self.write(streamStartBytes.pop(0))
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/coder/layer.py", line 41, in write
    self.toLower(bytearray([i]))
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/auth/layer_crypt.py", line 46, in send
    self.toLower(bytearray(data))
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/stanzaregulator/layer.py", line 23, in send
    self.toLower(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/network/layer.py", line 91, in send
    self.initiate_send()
  File "/usr/lib/python2.6/asyncore.py", line 516, in initiate_send
    num_sent = dispatcher.send(self, self.out_buffer[:512])
  File "/usr/lib/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
socket.error: [Errno 32] Broken pipe

**Comment by anmol26s** [comment]
I have similar problem 

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 227, in process
    self.startCmdline()
  File "/usr/local/bin/yowsup-cli", line 254, in startCmdline
    stack = cli.YowsupCliStack(credentials, not self.args["unmoxie"])
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/stack.py", line 13, in __init__
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 51, in pushDefaultLayers
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 73, in getDefaultLayers
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/util/keyhelper.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/identitykeypair.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/state/storageprotos.py", line 9, in <module>
ImportError: cannot import name symbol_database

**Comment by naveen1988** [comment]
I am not able to send message from command line interface. I have installed updated version of yowsup. Below is the following error i am getting.


WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 231, in process
    self.startSendClient()
  File "yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/yowsup-master/yowsup/demos/sendclient/stack.py", line 54, in start
    self.stack.loop()
  File "/yowsup-master/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.6/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.6/asyncore.py", line 151, in poll
    read(obj)
  File "/usr/lib/python2.6/asyncore.py", line 82, in read
    obj.handle_error()
  File "/usr/lib/python2.6/asyncore.py", line 78, in read
    obj.handle_read_event()
  File "/usr/lib/python2.6/asyncore.py", line 428, in handle_read_event
    self.handle_read()
  File "/yowsup-master/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/yowsup-master/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/yowsup-master/yowsup/layers/axolotl/layer.py", line 115, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/yowsup-master/yowsup/layers/__init__.py", line 136, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/yowsup-master/yowsup/layers/axolotl/layer.py", line 175, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "/yowsup-master/yowsup/layers/axolotl/layer.py", line 354, in onGetKeysResult
    sessionBuilder.processPreKeyBundle(preKeyBundle)
  File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/sessionbuilder.py", line 167, in processPreKeyBundle
    parameters.create())
  File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/ratchet/ratchetingsession.py", line 58, in initializeSessionAsAlice
    parameters.getOurIdentityKey().getPrivateKey()))
  File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/ecc/curve.py", line 59, in calculateAgreement
    return _curve.calculateAgreement(privateKey.getPrivateKey(), publicKey.getPublicKey())
ValueError: input must be 32-byte string

**Comment by Simonwcm** [comment]
i also have problem after update. please let me know how to do fix it?

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
  File "/var/www/html/script/yowsup-master/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/var/www/html/script/yowsup-master/yowsup-cli", line 231, in process
    self.startSendClient()
  File "/var/www/html/script/yowsup-master/yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/var/www/html/script/yowsup-master/yowsup/demos/sendclient/stack.py", line 54, in start
    self.stack.loop()
  File "/var/www/html/script/yowsup-master/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/local/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/local/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/local/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/var/www/html/script/yowsup-master/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/var/www/html/script/yowsup-master/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/var/www/html/script/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/var/www/html/script/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/var/www/html/script/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/var/www/html/script/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/var/www/html/script/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/var/www/html/script/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/var/www/html/script/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/var/www/html/script/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/var/www/html/script/yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/var/www/html/script/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/var/www/html/script/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/var/www/html/script/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/var/www/html/script/yowsup-master/yowsup/layers/axolotl/layer.py", line 126, in receive
    self.toUpper(protocolTreeNode)
  File "/var/www/html/script/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/var/www/html/script/yowsup-master/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/var/www/html/script/yowsup-master/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/var/www/html/script/yowsup-master/yowsup/layers/auth/layer_authentication.py", line 71, in handleSuccess
    self.toUpper(nodeEntity)
  File "/var/www/html/script/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/var/www/html/script/yowsup-master/yowsup/layers/interface/interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "/var/www/html/script/yowsup-master/yowsup/demos/sendclient/layer.py", line 35, in onSuccess
    self.toLower(messageEntity)
  File "/var/www/html/script/yowsup-master/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/var/www/html/script/yowsup-master/yowsup/layers/__init__.py", line 173, in send
    s.send(data)
  File "/var/www/html/script/yowsup-master/yowsup/layers/__init__.py", line 111, in send
    send(entity)
  File "/var/www/html/script/yowsup-master/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/var/www/html/script/yowsup-master/yowsup/layers/__init__.py", line 115, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/var/www/html/script/yowsup-master/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/var/www/html/script/yowsup-master/yowsup/layers/axolotl/layer.py", line 107, in send
    self.handlePlaintextNode(node)
  File "/var/www/html/script/yowsup-master/yowsup/layers/axolotl/layer.py", line 190, in handlePlaintextNode
    ciphertext = sessionCipher.encrypt(plaintext)
  File "/usr/local/lib/python2.7/site-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessioncipher.py", line 38, in encrypt
  File "/var/www/html/script/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 47, in loadSession
    return self.sessionStore.loadSession(recepientId, deviceId)
  File "/var/www/html/script/yowsup-master/yowsup/layers/axolotl/store/sqlite/litesessionstore.py", line 20, in loadSession
    return SessionRecord(serialized=result[0])
  File "/usr/local/lib/python2.7/site-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/state/sessionrecord.py", line 16, in __init__
  File "build/bdist.linux-x86_64/egg/google/protobuf/message.py", line 186, in ParseFromString
  File "build/bdist.linux-x86_64/egg/google/protobuf/internal/python_message.py", line 859, in MergeFromString
  File "build/bdist.linux-x86_64/egg/google/protobuf/internal/python_message.py", line 892, in InternalParse
  File "build/bdist.linux-x86_64/egg/google/protobuf/internal/decoder.py", line 652, in DecodeField
google.protobuf.message.DecodeError: Truncated message.
