### ISSUE TITLE
i really need help, what can i do?

### ISSUE THREAD

**Issue by Loxurkrift** [tgalal/yowsup#1071]
No handlers could be found for logger "yowsup.stacks.yowstack"
Traceback (most recent call last):
  File "run.py", line 36, in <module>
    stack.loop() #this is the program mainloop
  File "/home/pi/yowsup/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/pi/yowsup/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/home/pi/yowsup/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/home/pi/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/pi/yowsup/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/pi/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/pi/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/pi/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/home/pi/yowsup/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/home/pi/yowsup/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/home/pi/yowsup/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'

**Comment by xkmato** [comment]
You have to add `YowAxolotlLayer` above the coder layer

**Comment by Loxurkrift** [comment]
doesn't work 
I want to use yowsup to light a LED, but still failed.
how can I do it?
sorry for bad English

**Comment by xkmato** [comment]
#1069 See if that works got you.
