### ISSUE TITLE
Cannot send messages to certain contacts

### ISSUE THREAD

**Issue by josiasmat** [tgalal/yowsup#1091]
Using Python 2.6.6, yowsup 2.4.2 and yowsup-cli 2.0.13.
I can send messages to some contacts, but to others no. Error output:

Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 231, in process
    self.startSendClient()
  File "/usr/bin/yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/usr/lib/python2.6/site-packages/yowsup/demos/sendclient/stack.py", line 54, in start
    self.stack.loop()
  File "/usr/lib/python2.6/site-packages/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib64/python2.6/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.6/asyncore.py", line 151, in poll
    read(obj)
  File "/usr/lib64/python2.6/asyncore.py", line 82, in read
    obj.handle_error()
  File "/usr/lib64/python2.6/asyncore.py", line 78, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.6/asyncore.py", line 428, in handle_read_event
    self.handle_read()
  File "/usr/lib/python2.6/site-packages/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/**init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/lib/python2.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/usr/lib/python2.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/usr/lib/python2.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/axolotl/layer.py", line 126, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/__init**.py", line 169, in receive
    s.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/**init**.py", line 105, in receive
    recv(node)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/auth/layer_authentication.py", line 71, in handleSuccess
    self.toUpper(nodeEntity)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/**init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/interface/interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "/usr/lib/python2.6/site-packages/yowsup/demos/sendclient/layer.py", line 35, in onSuccess
    self.toLower(messageEntity)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/__init**.py", line 63, in toLower
    self.**lower.send(data)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/__init**.py", line 173, in send
    s.send(data)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/**init**.py", line 111, in send
    send(entity)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/**init**.py", line 115, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/usr/lib/python2.6/site-packages/yowsup/layers/**init**.py", line 63, in toLower
    self.**lower.send(data)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/axolotl/layer.py", line 107, in send
    self.handlePlaintextNode(node)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/axolotl/layer.py", line 190, in handlePlaintextNode
    ciphertext = sessionCipher.encrypt(plaintext)
  File "/usr/lib/python2.6/site-packages/axolotl/sessioncipher.py", line 38, in encrypt
    sessionRecord   = self.sessionStore.loadSession(self.recipientId, self.deviceId)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 47, in loadSession
    return self.sessionStore.loadSession(recepientId, deviceId)
  File "/usr/lib/python2.6/site-packages/yowsup/layers/axolotl/store/sqlite/litesessionstore.py", line 20, in loadSession
    return SessionRecord(serialized=result[0])
  File "/usr/lib/python2.6/site-packages/axolotl/state/sessionrecord.py", line 16, in __init**
    record.ParseFromString(serialized)
  File "/usr/lib/python2.6/site-packages/google/protobuf/message.py", line 186, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/lib/python2.6/site-packages/google/protobuf/internal/python_message.py", line 859, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/lib/python2.6/site-packages/google/protobuf/internal/python_message.py", line 892, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/lib/python2.6/site-packages/google/protobuf/internal/decoder.py", line 652, in DecodeField
    raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
##

**Comment by jlguardi** [comment]
@josiasmat try to remove axolot.db and try again. I've experienced this issue with mixed encription version for some recipients.

**Comment by Rustem** [comment]
Also look through the issues. I've seen that somebody recreates the keys instead of raising exception

**Comment by josiasmat** [comment]
Solved the issue. Added --unmoxie to the command line. Thanks.

**Comment by arlsr** [comment]
@josiasmat Same issue and your solution worked, thanks.

--unmoxie disables end to end encryption, I imagine it's necessary when sending to non-Android clients based on https://github.com/tgalal/yowsup/wiki/End-to-End-encryption
