### ISSUE TITLE
'NoneType' object has no attribute 'index'

### ISSUE THREAD

**Issue by Rockerrox** [tgalal/yowsup#1106]
I tried to execute run.py and got this:

DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e1.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
stream:features
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
/stream:features

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive= +str(val)+  user= +str(val)+  mechanism= +str(val)+ >
▒f▒b▒y-▒J
W▒▒ẃE:▒} ▒▒>▒f▒▒▒T]f▒▒▒▒
HEX:fa66d962da792dfe4a0e070a5fc4013c76451e3aaf7d2010afb03efe66ede4cb545d1066baa79da40d57b5da77cd81
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
stream:features
/stream:features

DEBUG:yowsup.layers.logger.layer:rx:
<success status= +str(val)+  kind= +str(val)+  creation= +str(val)+  expiration= +str(val)+  props= +str(val)+  t= +str(val)+ >
▒`GGz[▒Ո'▒0<_RU'▒▒
HEX:eb604719477a5be9d5882795303c5f525527d6d7
</success>

DEBUG:yowsup.layers.logger.layer:rx:
<ib from= +str(val)+ >
<dirty timestamp= +str(val)+  type= +str(val)+ >
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt offline= +str(val)+  from= +str(val)+  id= +str(val)+  t= +str(val)+ >
</receipt>

DEBUG:yowsup.layers.logger.layer:tx:
<ack to= +str(val)+  participant= +str(val)+  type= +str(val)+  id= +str(val)+  class= +str(val)+ >
</ack>

Traceback (most recent call last):
  File "run.py", line 34, in <module>
    stack.loop()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/**init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/axolotl/layer.py", line 126, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/__init**.py", line 169, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/**init**.py", line 105, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/protocol_receipts/layer.py", line 17, in recvReceiptNode
    self.toUpper(IncomingReceiptProtocolEntity.fromProtocolTreeNode(node))
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/**init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/interface/interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "/home/pi/w/layer.py", line 27, in onReceipt
    self.toLower(ack)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/__init**.py", line 63, in toLower
    self.**lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/__init**.py", line 173, in send
    s.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/**init**.py", line 111, in send
    send(entity)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/protocol_acks/layer.py", line 14, in sendAckEntity
    self.entityToLower(entity)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/**init**.py", line 115, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/**init**.py", line 63, in toLower
    self.**lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/axolotl/layer.py", line 109, in send
    self.toLower(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/__init**.py", line 63, in toLower
    self.**lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/logger/layer.py", line 9, in send
    self.toLower(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/__init**.py", line 63, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/coder/layer.py", line 30, in send
    self.write(self.writer.protocolTreeNodeToBytes(data))
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/coder/encoder.py", line 26, in protocolTreeNodeToBytes
    self.writeInternal(node, outBytes)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/coder/encoder.py", line 38, in writeInternal
    self.writeAttributes(node.attributes, data);
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/coder/encoder.py", line 53, in writeAttributes
    self.writeString(value, data);
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/yowsup/layers/coder/encoder.py", line 114, in writeString
    atIndex = tag.index(at)
AttributeError: 'NoneType' object has no attribute 'index'

In encoder.py, the problem seems to be writeString, where it says       at 
Index = tag.index(at)

https://github.com/tgalal/yowsup/blob/master/yowsup/layers/coder/encoder.py

Does anyone have any idea what the problem could be?  Thank you.
##

**Comment by Mafioso** [comment]
Could you provide a snippet you try to launch please @Rockerrox
