### ISSUE TITLE
Error at login - Notification error type=account notify=server

### ISSUE THREAD

**Issue by bernardojedi** [tgalal/yowsup#1110]
I keep getting this error every time i use /L and haven't found anyone with a similar problem. How can i workaround this?

Auth: Logged in!
[connected]:Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    **import**('pkg_resources').run_script('yowsup2==2.4', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 227, in process

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 255, in startCmdline

  File "build/bdist.linux-armv6l/egg/yowsup/demos/cli/stack.py", line 25, in start
  File "build/bdist.linux-armv6l/egg/yowsup/stacks/yowstack.py", line 187, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-armv6l/egg/yowsup/layers/network/layer.py", line 86, in handle_read
  File "build/bdist.linux-armv6l/egg/yowsup/layers/network/layer.py", line 94, in receive
  File "build/bdist.linux-armv6l/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-armv6l/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-armv6l/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-armv6l/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-armv6l/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-armv6l/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-armv6l/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-armv6l/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-armv6l/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-armv6l/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-armv6l/egg/yowsup/layers/axolotl/layer.py", line 126, in receive
  File "build/bdist.linux-armv6l/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-armv6l/egg/yowsup/layers/**init**.py", line 169, in receive
  File "build/bdist.linux-armv6l/egg/yowsup/layers/**init**.py", line 105, in receive
  File "build/bdist.linux-armv6l/egg/yowsup/layers/protocol_notifications/layer.py", line 41, in recvNotification
  File "build/bdist.linux-armv6l/egg/yowsup/layers/**init**.py", line 121, in raiseErrorForNode
ValueError: Unimplemented notification type <notification from="s.whatsapp.net" notify="Server" offline="3" type="account" id="3102097840" t="1446059346">
<redeem sku="missing" delta="1">
<account status="active" kind="paid" creation="1408790961" expiration="1446145746">
</account>
</redeem>
</notification>
##

**Comment by bernardojedi** [comment]
ValueError: Unimplemented notification type <notification from="s.whatsapp.net" notify="Server" offline="3" type="account" id="3102097840" t="1446059346">
<redeem sku="missing" delta="1">
<account status="active" kind="paid" creation="1408790961" expiration="1446145746">
</account>
</redeem>
</notification>

**Comment by jlguardi** [comment]
Please, add -d flag to command line and post logs.
