### ISSUE TITLE
recieved error AttributeError: 'NoneType' object has no attribute 'getData'

### ISSUE THREAD

**Issue by dordhn** [tgalal/yowsup#1115]
the send option works great but the echo client faild to recieved the message. i used -M option as well but still no luck.i also downloaded the develop version. but still no luck

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 229, in process
    self.startEcho()
  File "./yowsup-cli", line 265, in startEcho
    stack.start()
  File "/home/pc/yowsup-master/getmsg/yowsup/demos/echoclient/stack.py", line 49, in start
    self.stack.loop()
  File "/home/pc/yowsup-master/getmsg/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/**init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/__init**.py", line 169, in receive
    s.receive(data)
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/**init**.py", line 105, in receive
    recv(node)
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/home/pc/yowsup-master/getmsg/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'

any idea?
##

**Comment by jlguardi** [comment]
Usually this message is raised if an encrypted message is received but axolot layer is not enabled. So, don't use -M option an try again. Also add -d flag to get full log and post it, please.

**Comment by sendytiaprayoga** [comment]
I try this:

yowsup-cli demos -d -c /home/whatsapp/yowsup-2.4.48/config -e

and i have error:

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 724, in run_script
  File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 1657, in run_script
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>
PuTTYPuTTYPuTTYPuTTY
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 229, in process

  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 265, in startEcho

  File "build/bdist.linux-i686/egg/yowsup/demos/echoclient/stack.py", line 48, in start
  File "build/bdist.linux-i686/egg/yowsup/stacks/yowstack.py", line 195, in loop
  File "/usr/lib/python2.7/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 151, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 79, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 435, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-i686/egg/yowsup/layers/network/layer.py", line 86, in handle_read
  File "build/bdist.linux-i686/egg/yowsup/layers/network/layer.py", line 94, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/layer.py", line 117, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/layer.py", line 139, in onMessage
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/layer.py", line 222, in handleEncMessage
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/layer.py", line 259, in handlePreKeyWhisperMessage
  File "/usr/local/lib/python2.7/site-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessioncipher.py", line 91, in decryptPkmsg
  File "/usr/local/lib/python2.7/site-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessionbuilder.py", line 43, in process
  File "/usr/local/lib/python2.7/site-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessionbuilder.py", line 104, in processV3
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 65, in loadSignedPreKey
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/store/sqlite/litesignedprekeystore.py", line 24, in loadSignedPreKey
  File "/usr/local/lib/python2.7/site-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/state/signedprekeyrecord.py", line 8, in __init__
  File "build/bdist.linux-i686/egg/google/protobuf/message.py", line 186, in ParseFromString
  File "build/bdist.linux-i686/egg/google/protobuf/internal/python_message.py", line 867, in MergeFromString
google.protobuf.message.DecodeError: unpack requires a string argument of length 8
