### ISSUE TITLE
Syntax error when --send

### ISSUE THREAD

**Issue by pvleite** [tgalal/yowsup#1118]
(yowsup-env)root@server:~/yowsup-master# ./yowsup-cli demos --config yowsup.cnf --send 5512XXXXXX "Hello world"
Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 231, in process
    self.startSendClient()
  File "./yowsup-cli", line 279, in startSendClient
    not self.args["unmoxie"])
  File "/root/yowsup-master/yowsup/demos/sendclient/stack.py", line 24, in __init__
    from yowsup.layers.axolotl                     import YowAxolotlLayer
  File "/root/yowsup-master/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/root/yowsup-master/yowsup/layers/axolotl/layer.py", line 3, in <module>
    from axolotl.util.keyhelper import KeyHelper
  File "/root/yowsup-env/lib/python3.4/site-packages/axolotl/util/keyhelper.py", line 3, in <module>
    from ..identitykeypair import IdentityKeyPair
  File "/root/yowsup-env/lib/python3.4/site-packages/axolotl/identitykeypair.py", line 1, in <module>
    from .state.storageprotos import IdentityKeyPairStructure
  File "/root/yowsup-env/lib/python3.4/site-packages/axolotl/state/storageprotos.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/root/yowsup-env/lib/python3.4/site-packages/google/protobuf/reflection.py", line 68, in <module>
    from google.protobuf.internal import python_message
  File "/root/yowsup-env/lib/python3.4/site-packages/google/protobuf/internal/python_message.py", line 848
    except struct.error, e:
                       ^
SyntaxError: invalid syntax

**Comment by mrxfhd** [comment]
this is a bug in the protobuf package , update to protobuf 3.0.0a3 , pip install protobuf==3.0.0a3 , that fixed the problem for me

**Comment by MrMontesa** [comment]
Just stumbled upon this issue which helped me to resolve the error I received.
Thanks you!
