### ISSUE TITLE
Getting  AttributeError: 'BYYowsupLayer' object has no attribute '_YowLayer__stack'

### ISSUE THREAD

**Issue by yniv** [tgalal/yowsup#1119]
Hi, I'm getting this error when creating the stack.
I followed the CLI example almost entirely. here is the Traceback:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "server.py", line 41, in whatsAppClientThread
    WhatsAppClient(soc).start()
  File "/home/bumptestlin/server/whatsapp_client.py", line 48, in start
    stack = YowStack(layers)
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 135, in __init__
    self._construct()
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 206, in _construct
    inst = s()
  File "/home/bumptestlin/server/bumpyard_layer.py", line 45, in __init__
    self.credentials = self.getProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 88, in getProp
    return self.getStack().getProp(key, default)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 45, in getStack
    return self.__stack
AttributeError: 'BYYowsupLayer' object has no attribute '_YowLayer__stack'
```
The code i use:
```
            layers = (
                         BYYowsupLayer,
                         (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer,                    
                          YowReceiptProtocolLayer,
                          YowAckProtocolLayer),
                         YowAxolotlLayer
                     ) + YOWSUP_CORE_LAYERS

            # setup Yowsup stack
            stack = YowStack(layers)
            stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, (command[1], command[2]))  # setting credentials
            stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])  # whatsapp server address
            stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
            stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())  # info about us as WhatsApp client
            stack.setProp("Client", self)  # set client for layer use

            # sending the connect signal
            stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))

            # start main loop
            stack.loop()
```
help someone?

**Comment by jlguardi** [comment]
BYYowsupLayer extends yowsupLayer?

**Comment by yniv** [comment]
Yes it is. i solved this problem thx!

now when i'm calling setCredentials i'm getting this:
```
File "/home/bumptestlin/server/bumpyard_layer.py", line 87, in setCredentials
    self.getLayerInterface(YowAuthenticationProtocolLayer).setCredentials(username, password)
TypeError: setCredentials() takes exactly 2 arguments (3 given)
```

**Comment by jlguardi** [comment]
Probably you missed self parameter in the function declaration.
