### ISSUE TITLE
Non ASCII still broken with Python 3.3

### ISSUE THREAD

**Issue by DerFlob** [tgalal/yowsup#112]
Sending non-ASCII characters is still broken for me, with Python 3.3. I used the example CmdClient, to send a message to myself. On receiving the client crashes with this stack trace:

```
[flob@FlobsHS src]$ python3 yowsup-cli -c ~/.yowsup/auth -ai 123456789
Connecting to c2.whatsapp.net
Authed 123456789
Starting Interactive chat with 123456789
Enter Message or command: (/lastseen, /unavailable, /available)
abcö
123456789 [13-04-2013 19:21]:abcö
Enter Message or command: (/lastseen, /unavailable, /available)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.3/threading.py", line 639, in _bootstrap_inner
    self.run()
  File "/home/flob/bin/yowsup/src/Yowsup/connectionmanager.py", line 877, in run
    self.parseMessage(node)
  File "/home/flob/bin/yowsup/src/Yowsup/connectionmanager.py", line 1409, in parseMessage
    msgData = msgData if sys.version_info < (3, 0) else msgData.encode('latin-1').decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 3: invalid start byte
```

If I use Python 2.7, it doesn't crash, but only shows a placeholder symbol for the ö. I also tried sending this message to my brother, who uses the official client and he too receives only placeholder symbols for the non-ASCII character.
So there seems to be a problem on the sending-side of the library.
##

**Comment by jorgehortelano** [comment]
I can confirm this issue with current code of github at (2016-03-25). Using python3 causes this issue.

**Comment by jlguardi** [comment]
@jorgehortelano which code are you using? tgalal/master?

**Comment by jorgehortelano** [comment]
I have just done a 'git clone https://github.com/tgalal/yowsup.git'.
With python2.7 no problem, but with python3 I see this issue.

**Comment by pabloruan0710** [comment]
somebody resolved???
