### ISSUE TITLE
Not able to install yowsup in rhel

### ISSUE THREAD

**Issue by naveen1988** [tgalal/yowsup#1120]
I am not able to send message from command line interface. I have installed updated version of yowsup. Below is the following error i am getting.

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
File "yowsup-cli", line 323, in 
if not parser.process():
File "yowsup-cli", line 231, in process
self.startSendClient()
File "yowsup-cli", line 280, in startSendClient
stack.start()
File "/yowsup-master/yowsup/demos/sendclient/stack.py", line 54, in start
self.stack.loop()
File "/yowsup-master/yowsup/stacks/yowstack.py", line 195, in loop
asyncore.loop(args, *kwargs)
File "/usr/lib/python2.6/asyncore.py", line 210, in loop
poll_fun(timeout, map)
File "/usr/lib/python2.6/asyncore.py", line 151, in poll
read(obj)
File "/usr/lib/python2.6/asyncore.py", line 82, in read
obj.handle_error()
File "/usr/lib/python2.6/asyncore.py", line 78, in read
obj.handle_read_event()
File "/usr/lib/python2.6/asyncore.py", line 428, in handle_read_event
self.handle_read()
File "/yowsup-master/yowsup/layers/network/layer.py", line 86, in handle_read
self.receive(data)
File "/yowsup-master/yowsup/layers/network/layer.py", line 94, in receive
self.toUpper(data)
File "/yowsup-master/yowsup/layers/init.py", line 59, in toUpper
self.upper.receive(data)
File "/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
self.processReceived()
File "/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
self.toUpper(oneMessageData)
File "/yowsup-master/yowsup/layers/__init.py", line 59, in toUpper
self.upper.receive(data)
File "/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 63, in receive
self.toUpper(payload)
File "/yowsup-master/yowsup/layers/__init.py", line 59, in toUpper
self.upper.receive(data)
File "/yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
self.toUpper(node)
File "/yowsup-master/yowsup/layers/__init.py", line 59, in toUpper
self.upper.receive(data)
File "/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
self.toUpper(data)
File "/yowsup-master/yowsup/layers/__init.py", line 59, in toUpper
self.upper.receive(data)
File "/yowsup-master/yowsup/layers/axolotl/layer.py", line 115, in receive
if not self.processIqRegistry(protocolTreeNode):
File "/yowsup-master/yowsup/layers/__init.py", line 136, in processIqRegistry
successClbk(protocolTreeNode, originalIq)
File "/yowsup-master/yowsup/layers/axolotl/layer.py", line 175, in 
self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
File "/yowsup-master/yowsup/layers/axolotl/layer.py", line 354, in onGetKeysResult
sessionBuilder.processPreKeyBundle(preKeyBundle)
File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/sessionbuilder.py", line 167, in processPreKeyBundle
parameters.create())
File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/ratchet/ratchetingsession.py", line 58, in initializeSessionAsAlice
parameters.getOurIdentityKey().getPrivateKey()))
File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/ecc/curve.py", line 59, in calculateAgreement
return _curve.calculateAgreement(privateKey.getPrivateKey(), publicKey.getPublicKey())
ValueError: input must be 32-byte string

**Comment by t0rr3sp3dr0** [comment]
I had this same problem a few months ago. The axolotl package doesn't work properly on Python 2.6, you will need to update Python to version 2.7 at least. And how WhatsApp almost obligate you to use encrypted communications with the server, it's not possible to use yowsup in Python 2.6 any more. If you try to disable moxie, how you did, you will keep receiving encrypted messages and yowsup will not be able to process them, causing your error. Just update to Python 2.7.

**Comment by janboll** [comment]
if you run rhel6 i recommend creating a virtual environment and then compiling python 2.7 into that environment. this will prevent any damages to the rest of the system (a few redhat components base on python).
