### ISSUE TITLE
input must be 32-byte string

### ISSUE THREAD

**Issue by lance1001** [tgalal/yowsup#1124]
I installed the yowsup2 in a Linux Centos and the login is OK, but when I try to send a message I receive the message ValueError: input must be 32-byte string

I'm using this command:
yowsup-cli demos -c config -s 99999999999 MESSAGE -d

And the debug print is:
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tupl
e is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer -
 Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e5.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
stream:features
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
/stream:features

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="5511991092602" mechanism="WAUTH-2">
♥w&Q─Vp╩ ¶√fc =-╧oδ▌ÉD∙♥╓↓▼¡ ╝£τ♦╗┤p▀2ùuσF╨!ÅK
HEX:03772651c45670ca2014fb6663203d2dcf6febdd9044f903d6191fadffbc9ce704bbb470df32
9775e546d0218f4b18
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
stream:features
/stream:features

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1422360490" expiration="145389649
0" props="4" t="1446730433">
╦ºª§ª(ƒ╦┬■§}]OPΣ«ƒ
HEX:cba7a615a6289fcbc2fe15137d5d4f50e4ae7f9f
</success>

DEBUG:yowsup.layers.logger.layer:tx:
<iq to="s.whatsapp.net" xmlns="encrypt" type="get" id="2">
<key>
<user jid="5511984437337@s.whatsapp.net">
</user>
</key>
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1446730434" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="s.whatsapp.net" id="2">
<list>
<user jid="5511984437337@s.whatsapp.net">
<registration>
.Σ
HEX:00002ee4
</registration>
<type>

HEX:05
</type>
<identity>
╒╝/δÑj↔8Aë·∩ç°µ[S╔▓▀ÿΣçûÉΘÑKe8
HEX:d5bc2feba56a1d384189faef87f87fe65b53c9b2df98e4879690e9a50f4b6538
</identity>
<skey>
<id>

HEX:000005
</id>
<value>
kÿσ▬
    u^»âòΓCè¡*¼Ü∟╠ò┼Ñ]ª§v
HEX:6b98e5160b00755eaf8395e2437f078a0ead2aac9a1cc408cc95c5a55da61576
</value>
<signature>
²≤D aó3nöm┘>╔U[ ╥ÅJ╧τ►möò:♥%\òv▬╨│¿|!P═Y♦0↔>╨gÆ╚╕ñì[(▲╫íç,╗╧}╠ü
HEX:0efdf3442061a2336e946dd93ec9555bffd28f4acfe7106d94953a03255c957616d0b3a87c21
50cd5904301d3ed06792c8b8a48d5b281ed7a1872cbbcf7dcc81
</signature>
</skey>
<key>
<id>
w
HEX:000077
</id>
<value>
e╪`═/╪O╫û≈☺╟/┬┬╦₧hzém≈
                      ╬╧╔ƒΣ☻
HEX:65d860cd182fd8134fd796f701c72fc2c21acb9e687a826df70bcecfc99fe402
</value>
</key>
</user>
</list>
</iq>

Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4', 'yowsup-cli')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_scr
ipt
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_sc
ript
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/EGG-INFO/scripts/
yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/EGG-INFO/scripts/
yowsup-cli", line 231, in process
    self.startSendClient()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/EGG-INFO/scripts/
yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/demos/send
client/stack.py", line 54, in start
    self.stack.loop()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/stacks/yow
stack.py", line 195, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib64/python2.6/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.6/asyncore.py", line 151, in poll
    read(obj)
  File "/usr/lib64/python2.6/asyncore.py", line 82, in read
    obj.handle_error()
  File "/usr/lib64/python2.6/asyncore.py", line 78, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.6/asyncore.py", line 428, in handle_read_event
    self.handle_read()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/net
work/layer.py", line 86, in handle_read
    self.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/net
work/layer.py", line 94, in receive
    self.toUpper(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/**i
nit**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/sta
nzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/sta
nzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/__i
nit**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/aut
h/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/__i
nit**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/cod
er/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/__i
nit**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/log
ger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/__i
nit**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/axo
lotl/layer.py", line 115, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/__i
nit**.py", line 136, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/axo
lotl/layer.py", line 175, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPen
dingMessages), self.onGetKeysError)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/yowsup/layers/axo
lotl/layer.py", line 354, in onGetKeysResult
    sessionBuilder.processPreKeyBundle(preKeyBundle)
  File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/
sessionbuilder.py", line 167, in processPreKeyBundle
    parameters.create())
  File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/ratchet/ratchetingsession.py", line 58, in initializeSessionAsAlice
    parameters.getOurIdentityKey().getPrivateKey()))
  File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/ecc/curve.py", line 59, in calculateAgreement
    return _curve.calculateAgreement(privateKey.getPrivateKey(), publicKey.getPublicKey())
ValueError: input must be 32-byte string

What is wrong???

Thanks in advance.
##

**Comment by forkmancze** [comment]
I have the same problem after upgrade to 2.4 on centos 6.5 with python 2.7

**Comment by t0rr3sp3dr0** [comment]
@lance1001 try to Python 2.7

**Comment by forkmancze** [comment]
The same with python 3.3.2 but it depends on phone number. For example 420603385860 is OK and message is sent but 420777273747 ends with
**ValueError: input must be 32-byte string.**
Any idea?

**Comment by forkmancze** [comment]
I found that disable encryption parameter of *yowsup-cli* **-M** resolves the problem
