### ISSUE TITLE
CLI: Traceback (most recent call last):

### ISSUE THREAD

**Issue by gfngr** [tgalal/yowsup#1137]
Hey guys,
does anybody know why i get this message in the CLI?
Normaly I got this right after I tried to send an audio file, now i also get it after some time just being online.

[connected]:Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/yowsup-cli", line 4, in <module>
    **import**('pkg_resources').run_script('yowsup2==2.4', 'yowsup-cli')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/**init**.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1649, in run_script
    exec(script_code, namespace, namespace)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yowsup2-2.4-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yowsup2-2.4-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 227, in process

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yowsup2-2.4-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 255, in startCmdline

  File "build/bdist.macosx-10.6-intel/egg/yowsup/demos/cli/stack.py", line 25, in start
  File "build/bdist.macosx-10.6-intel/egg/yowsup/stacks/yowstack.py", line 187, in loop
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
select.error: (9, 'Bad file descriptor')
##

**Comment by CreatorSky** [comment]
Modify /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py and set the default of use_poll from False to True:

Line 207:

`def loop(timeout=30.0, use_poll=False, map=None, count=None):`

to

`def loop(timeout=30.0, use_poll=True, map=None, count=None):`

and that solved my issue .
Best of luck.

**Comment by pabloruan0710** [comment]
somebody fix?

**Comment by thinesh3859** [comment]
[connected]:
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.7', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/stacks/yowstack.py", line 189, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/protocol_notifications/layer.py", line 41, in recvNotification
    self.raiseErrorForNode(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 146, in raiseErrorForNode
    raise ValueError("Unimplemented notification type %s " % node)
ValueError: Unimplemented notification type <notification participant="919442361227@s.whatsapp.net" notify="Anbu Travels" from="location@broadcast" offline="3" type="location" id="01" t="1531636046">
<enc type="pkmsg" v="2">
���!�A��
           ڲ�W͓��r��2	|d��]���$h!�!���<�B���.+ա>�J�	q� 
                                                                   "�3
!��
&�����W��ª�e�l�B�e.���kg"��iA���$�Uu��9�?δ��g�lHS���e�Rc)+��Ab���B�X��i�����GI�Gc�<�����+h_�/�jv��|G�Ж	5�D��cUY�s;����j�H�Q��aZ$'(��ނ0
HEX:3308bccdcb02122105eb41deec0c20dab2c157cd9313a9b4728a1285321a097c64bcf25de786e424681a2105802197e4140e05b63c16189e42f6f30ef62e2bd5a13e15b54a920971ea200b1122c301330a2105cff90a2686bb131cb689cb57b1fcc2aac21a659e6caa42c5652ec7d211f86b6710011800229001bb6941def0c324cd5575b51015fb0339cf3fceb49dd667d26c4853aff59065f208c4526313292b9e8c4162fbae17fb4291850fcb6a01fd1ddf45811fe3c3f88d8f07e542acb176ed6bca63afb38f0d58b8a769109792a58ea647498b4763b83cabfd01e3e2812b685fa32fba6a76a9c57c4799d0960935ba1c44051ab687635559ac733bf3f5188ff5136a07f448c60f518ac17f615a242728fea8de82073001
</enc>
</notification>

Same error occurred for me also, some one guide me please
