### ISSUE TITLE
yowsup-cli demos -e -c /etc/zapzap.cfg AttributeError: 'NoneType' object has no attribute 'getData'

### ISSUE THREAD

**Issue by blaksoft** [tgalal/yowsup#1149]
on command: 
yowsup-cli demos -e -c /etc/zapzap.cfg -M get error:
  File "/usr/bin/yowsup-cli", line 4, in <module>
    **import**('pkg_resources').run_script('yowsup2==2.4', 'yowsup-cli')
  File "/usr/lib/python2.6/site-packages/pkg_resources/**init**.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources/**init**.py", line 1674, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>

  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 229, in process

  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 265, in startEcho

  File "build/bdist.linux-x86_64/egg/yowsup/demos/echoclient/stack.py", line 48, in start
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 195, in loop
  File "/usr/lib64/python2.6/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.6/asyncore.py", line 151, in poll
    read(obj)
  File "/usr/lib64/python2.6/asyncore.py", line 82, in read
    obj.handle_error()
  File "/usr/lib64/python2.6/asyncore.py", line 78, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.6/asyncore.py", line 428, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 86, in handle_read
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 94, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 169, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 105, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
AttributeError: 'NoneType' object has no attribute 'getData'
##

**Comment by jlguardi** [comment]
Try to remove -M flag.

**Comment by blaksoft** [comment]
without -M flag

run command: 
yowsup-cli demos -e -c /etc/zapzap.cfg get a error:

Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 229, in process
    self.startEcho()
  File "./yowsup-cli", line 265, in startEcho
    stack.start()
  File "/root/whats/yowsup-develop/yowsup/demos/echoclient/stack.py", line 48, in start
    self.stack.loop()
  File "/root/whats/yowsup-develop/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python2.6/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.6/asyncore.py", line 151, in poll
    read(obj)
  File "/usr/lib64/python2.6/asyncore.py", line 82, in read
    obj.handle_error()
  File "/usr/lib64/python2.6/asyncore.py", line 78, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.6/asyncore.py", line 428, in handle_read_event
    self.handle_read()
  File "/root/whats/yowsup-develop/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/root/whats/yowsup-develop/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/root/whats/yowsup-develop/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/whats/yowsup-develop/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/root/whats/yowsup-develop/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/root/whats/yowsup-develop/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/whats/yowsup-develop/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/root/whats/yowsup-develop/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/whats/yowsup-develop/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/root/whats/yowsup-develop/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/whats/yowsup-develop/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/root/whats/yowsup-develop/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/whats/yowsup-develop/yowsup/layers/axolotl/layer.py", line 117, in receive
    self.onMessage(protocolTreeNode)
  File "/root/whats/yowsup-develop/yowsup/layers/axolotl/layer.py", line 139, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/root/whats/yowsup-develop/yowsup/layers/axolotl/layer.py", line 222, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/root/whats/yowsup-develop/yowsup/layers/axolotl/layer.py", line 258, in handlePreKeyWhisperMessage
    plaintext = sessionCipher.decryptPkmsg(preKeyWhisperMessage)
  File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/sessioncipher.py", line 90, in decryptPkmsg
    sessionRecord = self.sessionStore.loadSession(self.recipientId, self.deviceId)
  File "/root/whats/yowsup-develop/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 47, in loadSession
    return self.sessionStore.loadSession(recepientId, deviceId)
  File "/root/whats/yowsup-develop/yowsup/layers/axolotl/store/sqlite/litesessionstore.py", line 20, in loadSession
    return SessionRecord(serialized=result[0])
  File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/state/sessionrecord.py", line 16, in __init__
    record.ParseFromString(serialized)
  File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/message.py", line 186, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/internal/python_message.py", line 859, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/internal/python_message.py", line 892, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/internal/decoder.py", line 652, in DecodeField
    raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
