### ISSUE TITLE
Can't send VideoDownloadableMediaMessageProtocolEntity

### ISSUE THREAD

**Issue by msshapira** [tgalal/yowsup#1158]
While trying to forward a video message. Throws the following exception. I have a fix and will submit a PR in a short while:

  File "C:\Python34\lib\asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "C:\Python34\lib\asyncore.py", line 153, in poll
    read(obj)
  File "C:\Python34\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Python34\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python34\lib\asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\network\layer.py", line 86, in handle_read
    self.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\network\layer.py", line 94, in receive
    self.toUpper(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\stanzaregulator\layer.py", line 28, in receive
    self.processReceived()
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\stanzaregulator\layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\auth\layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\axolotl\layer.py", line 117, in receive
    self.onMessage(protocolTreeNode)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\axolotl\layer.py", line 141, in onMessage
    self.toUpper(protocolTreeNode)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 169, in receive
    s.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 105, in receive
    recv(node)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\protocol_media\layer.py", line 48, in recvMessageStanza
    self.toUpper(entity)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\interface\interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "D:/projects/orefreports/python\OrefReports\OrefLayer.py", line 169, in onMessage
    self.ForwardMessage(group, messageProtocolEntity)
  File "D:/projects/orefreports/python\OrefReports\OrefLayer.py", line 230, in ForwardMessage
    self.toLower(outVideo)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 173, in send
    s.send(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 111, in send
    send(entity)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\protocol_media\layer.py", line 35, in sendMessageEntity
    self.entityToLower(entity)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 115, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\axolotl\layer.py", line 109, in send
    self.toLower(node)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\logger\layer.py", line 8, in send
    logger.debug("tx:\n%s" % ldata)
  File "D:\projects\orefreports\python/yowsup\yowsup\structs\protocoltreenode.py", line 81, in __str__
    return self.toString()
  File "D:\projects\orefreports\python/yowsup\yowsup\structs\protocoltreenode.py", line 73, in toString
    out += c.toString()
  File "D:\projects\orefreports\python/yowsup\yowsup\structs\protocoltreenode.py", line 53, in toString
    out+= " "+key+'="'+val+'"'
TypeError: Can't convert 'NoneType' object to str implicitly
ERROR:OrefReports.stack:Other Error
Traceback (most recent call last):
  File "D:/projects/orefreports/python\OrefReports\stack.py", line 65, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "D:\projects\orefreports\python/yowsup\yowsup\stacks\yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "C:\Python34\lib\asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "C:\Python34\lib\asyncore.py", line 153, in poll
    read(obj)
  File "C:\Python34\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Python34\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python34\lib\asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\network\layer.py", line 86, in handle_read
    self.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\network\layer.py", line 94, in receive
    self.toUpper(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\stanzaregulator\layer.py", line 28, in receive
    self.processReceived()
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\stanzaregulator\layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\auth\layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\axolotl\layer.py", line 117, in receive
    self.onMessage(protocolTreeNode)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\axolotl\layer.py", line 141, in onMessage
    self.toUpper(protocolTreeNode)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 169, in receive
    s.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 105, in receive
    recv(node)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\protocol_media\layer.py", line 48, in recvMessageStanza
    self.toUpper(entity)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\interface\interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "D:/projects/orefreports/python\OrefReports\OrefLayer.py", line 169, in onMessage
    self.ForwardMessage(group, messageProtocolEntity)
  File "D:/projects/orefreports/python\OrefReports\OrefLayer.py", line 230, in ForwardMessage
    self.toLower(outVideo)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 173, in send
    s.send(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 111, in send
    send(entity)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\protocol_media\layer.py", line 35, in sendMessageEntity
    self.entityToLower(entity)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 115, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\axolotl\layer.py", line 109, in send
    self.toLower(node)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "D:\projects\orefreports\python/yowsup\yowsup\layers\logger\layer.py", line 8, in send
    logger.debug("tx:\n%s" % ldata)
  File "D:\projects\orefreports\python/yowsup\yowsup\structs\protocoltreenode.py", line 81, in __str__
    return self.toString()
  File "D:\projects\orefreports\python/yowsup\yowsup\structs\protocoltreenode.py", line 73, in toString
    out += c.toString()
  File "D:\projects\orefreports\python/yowsup\yowsup\structs\protocoltreenode.py", line 53, in toString
    out+= " "+key+'="'+val+'"'
TypeError: Can't convert 'NoneType' object to str implicitly

**Comment by t0rr3sp3dr0** [comment]
Solved in my fork #1129

**Comment by msshapira** [comment]
I also pushed a PR (#1159) yesterday... so really, only one should be
merged i guess.

**Comment by msshapira** [comment]
seems like whatsapp server now sends the "seconds" and the "vbirtrate" fields populated - so now this exception will not reproduce when forwarding messages. The PR is still relevant - the code should be protected against null fields, but i'm closing the bug
