### ISSUE TITLE
Yowsup Failed to respond when try to register

### ISSUE THREAD

**Issue by sbogeman** [tgalal/yowsup#1174]
Hi,

When try to register, we got error failed to respond.
Can someone kindly enlighten ?

We're using yowsup version :
yowsup-cli v2.0.13
Using yowsup v2.4

OS : Window7

Able to ping to whatsapp server : 
E:\work\whatsaap\yowsup-master\yowsup-master>ping v.whatsapp.net

Pinging v.whatsapp.net [184.173.136.86] with 32 bytes of data:
Reply from 184.173.136.86: bytes=32 time=252ms TTL=45

E:\work\whatsaap\yowsup-master\yowsup-master>ping c2.whatsapp.net

Pinging c2.whatsapp.net [173.192.222.169] with 32 bytes of data:
Reply from 173.192.222.169: bytes=32 time=257ms TTL=46

The issue is  we got error :
socket.error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Below is the full command 
E:\work\whatsaap\yowsup-master\yowsup-master>python yowsup-cli registration --requestcode sms --phone 6289908058535 --cc 62 --mcc 510 --mnc 89 -d
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.13.5 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=62&in=89908058535&lc=GB&lg=en&sim_mcc=510&sim_mnc=089&method=sms&token=3b0e43720f8832eeb7140040ffaf6dd0&id=%99b%5C%C9%DAU%EDc%1F%A4%CC9dfg%40%0E%1E%83%E4
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=62&in=89908058535&lc=GB&lg=en&sim_mcc=510&sim_mnc=089&method=sms&token=3b0e43720f8832eeb7140040ffaf6dd0&id=%99b%5C%C9%DAU%EDc
%1F%A4%CC9dfg%40%0E%1E%83%E4
Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 158, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup-cli", line 176, in handleRequestCode
    result = codeReq.send()
  File "E:\work\whatsaap\yowsup-master\yowsup-master\yowsup\registration\coderequest.py", line 46, in send
    res = super(WACodeRequest, self).send(parser)
  File "E:\work\whatsaap\yowsup-master\yowsup-master\yowsup\common\http\warequest.py", line 73, in send
    return self.sendGetRequest(parser)
  File "E:\work\whatsaap\yowsup-master\yowsup-master\yowsup\common\http\warequest.py", line 111, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET")
  File "E:\work\whatsaap\yowsup-master\yowsup-master\yowsup\common\http\warequest.py", line 167, in sendRequest
    conn.request(reqType, path, params, headers);
  File "C:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 897, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 859, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "C:\Python27\lib\httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python27\lib\socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has fa
iled to respond

**Comment by sbogeman** [comment]
This is because of firewall, since after change the network connection, it's success
