### ISSUE TITLE
Unable to send messages - ImportError: cannot import name symbol_database

### ISSUE THREAD

**Issue by doinkusboinkus** [tgalal/yowsup#1206]
Command:
yowsup-cli demos -c yowsup-cli.config -s xxxxxxxxxxx "testing yowsup"

Returns:
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 279, in startSendClient
    
  File "build/bdist.linux-i686/egg/yowsup/demos/sendclient/stack.py", line 24, in __init__
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/layer.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/util/keyhelper.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/identitykeypair.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/state/storageprotos.py", line 9, in <module>
ImportError: cannot import name symbol_database

Command:
python yowsup-cli demos -c yowsup-cli.config -s xxxxxxxxxxx "testing yowsup"

Returns:
Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 231, in process
    self.startSendClient()
  File "yowsup-cli", line 279, in startSendClient
    not self.args["unmoxie"])
  File "/home/jliew/Downloads/yowsup-master/yowsup/demos/sendclient/stack.py", line 24, in __init__
    from yowsup.layers.axolotl                     import YowAxolotlLayer
  File "/home/jliew/Downloads/yowsup-master/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/home/jliew/Downloads/yowsup-master/yowsup/layers/axolotl/layer.py", line 3, in <module>
    from axolotl.util.keyhelper import KeyHelper
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/util/keyhelper.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/identitykeypair.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/state/storageprotos.py", line 9, in <module>
ImportError: cannot import name symbol_database

I have no problems requesting for sms code and registering. 

Thank you in advance for your help!

**Comment by doinkusboinkus** [comment]
I did a sudo apt-get remove python-protobuf as recommended by rfelten and it worked!

**Comment by jairoccjunior** [comment]
@doinkusboinkus sudo pip install --upgrade protobuf
