### ISSUE TITLE
Error while send mesage

### ISSUE THREAD

**Issue by sjkeerthi** [tgalal/yowsup#1215]
I have installed the yowsup in CentOS 6.7 
after the successful installation while I trying to send a sms
# yowsup-cli demos -c yowsup-cli.conf -s xxxxxxxx "test"

Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4.48-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4.48-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process
    self.startSendClient()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4.48-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 279, in startSendClient
    not self.args["unmoxie"])
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4.48-py2.6.egg/yowsup/demos/sendclient/stack.py", line 24, in **init**
    from yowsup.layers.axolotl                     import YowAxolotlLayer
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4.48-py2.6.egg/yowsup/layers/axolotl/**init**.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4.48-py2.6.egg/yowsup/layers/axolotl/layer.py", line 15, in <module>
    from axolotl.sessioncipher import SessionCipher
  File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/sessioncipher.py", line 3, in <module>
    from Crypto.Util import Counter
ImportError: cannot import name Counter

Kindly let me know is this because of any library issue
##

**Comment by sjkeerthi** [comment]
yowsup-cli demos --send xxxxxxx "Test" --config yowsup-cli.conf 
/usr/lib/python2.6/site-packages/yowsup2-2.4.48-py2.6.egg/yowsup/demos/sendclient/stack.py:56: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  print("Authentication Error: %s" % e.message)
Authentication Error: not-authorized
