### ISSUE TITLE
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type

### ISSUE THREAD

**Issue by yniv** [tgalal/yowsup#1219]
I started to get these messages from time to time. This crushes my server.
Any ideas whats that?

```
Traceback (most recent call last):
  File "/home/bumptestlin/server/server.py", line 76, in <module>
    asyncore.loop()
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 117, in receive
    self.onMessage(protocolTreeNode)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 139, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 224, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 274, in handleWhisperMessage
    plaintext = sessionCipher.decryptMsg(whisperMessage)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/axolotl/sessioncipher.py", line 77, in decryptMsg
    sessionRecord = self.sessionStore.loadSession(self.recipientId, self.deviceId)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 47, in loadSession
    return self.sessionStore.loadSession(recepientId, deviceId)
  File "/home/bumptestlin/server/venv-yowsapp/local/lib/python2.7/site-packages/yowsup/layers/axolotl/store/sqlite/litesessionstore.py", line 16, in loadSession
    c.execute(q, (recipientId, deviceId))
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
```
##

**Comment by 1upon0** [comment]
same here. Tried restarting. Worked once after 2-3 restarts, but then got:
 
   No handlers could be found for logger "axolotl.sessionbuilder"

this now happens consistently (with many restarts with 2-3 sec delay). 
Appears if somehow I could reset the sqlite session information, restarting might help
