### ISSUE TITLE
yowsup does not work with group-messages since 2 days!

### ISSUE THREAD

**Issue by capsload** [tgalal/yowsup#1220]
hello,

i got a problem (without changing/updating anything!)

when i send a message to a number, it works:

======

./yowsup-cli demos --config bot.conf -s 49151xxx "HELLO"
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
INFO:yowsup.demos.sendclient.layer:Message sent

======

when i try to send this message to a GROUP, it DOESNT work anymore:

======
./yowsup-cli demos --config bot.conf -s 49151xxx-141xxx "NIKO DRUNK BEER NO"
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 231, in process
    self.startSendClient()
  File "./yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/x/yowsup/yowsup/demos/sendclient/stack.py", line 54, in start
    self.stack.loop()
  File "/x/yowsup/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 444, in handle_read_event
    self.handle_read()
  File "/x/yowsup/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/x/yowsup/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/x/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/x/yowsup/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/x/yowsup/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/x/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/x/yowsup/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/x/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/x/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/x/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/x/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/x/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/x/yowsup/yowsup/layers/axolotl/layer.py", line 115, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/x/yowsup/yowsup/layers/__init__.py", line 136, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/x/yowsup/yowsup/layers/axolotl/layer.py", line 175, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "/x/yowsup/yowsup/layers/axolotl/layer.py", line 339, in onGetKeysResult
    entity = ResultGetKeysIqProtocolEntity.fromProtocolTreeNode(resultNode)
  File "/x/yowsup/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 87, in fromProtocolTreeNode
    preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
AttributeError: 'NoneType' object has no attribute 'getChild'
======

what could cause this? :(

**Comment by capsload** [comment]
@mgp25 @CODeRUS @tgalal you guys know what WhatsApp has changed again?

**Comment by mgp25** [comment]
@capsload Yes, new protocol, check Chat API commits

**Comment by msshapira** [comment]
wow.
Reviewing https://github.com/WHAnonymous/Chat-API/commit/9b4a2e6b4235890db0a15b09725a8b4090c8a772 - it looks major. @tgalal - are you planning a commit in the near future? If not, i'll try to port this and prepare a PR...

**Comment by capsload** [comment]
im thinking about that too @msshapira 
i coded my "beer counter" game with php and yowsup, theres a lot of code.
later, i saw Chat-API's features, i use that in addition for other features like changing group name/image, but the main script uses yowsup.

i begin to see chat-api's "auto-update-feature" is working really great, didnt updated any codes in the files since i installed it >6-8 months ago, while yowsup needs to be changed a little bit if whatsapp is changing some things (like this groupmessage thing here).

yowsup needs to be updated while chat-api still works -> does @mgp25 / @CODeRUS  can "update" Chat-API through their servers for us? at least they can do it with whatsapp_scratch :D

so my question is, do i have to update chat-api like yowsup ? i think not, because the guys above can update chat-api through their update script build into their script.

**Comment by kingherold** [comment]
Hi, 
I'm using yowsup to send messages into a group which is created by me with mobile phone. Sending into this group was not working anymore since the ticket from capsload.
Now I have created a new group with mobile and yowsup was invited to this group. It is working good again to send into this new group. 
All people left the old group and have been invited into the new group. 
A lot of trouble, but for me it is running again.

**Comment by tgalal** [comment]
WIP in wa16 branch

**Comment by e0xify** [comment]
that means? :dash: when will it be fixxed

**Comment by tgalal** [comment]
when it's no more WIP in wa16 branch

**Comment by carlosfelipe29** [comment]
Hi, @kingherold .  
Could you explain me, or What I have to modify, or add or link the group from Yowsup?, I have been trying to do that using the yowstack() functions without suceeded. 
I want to do the same thing, that is sending a msg or image to a group. 
thanks you.  (sorry for my english)

**Comment by mikkolindfors** [comment]
Any update on this one. This happened to me last night. Everything worked fine for few weeks and suddenly this same error on sending group messages.

**Comment by kumarshivam675** [comment]
This happened to me today. Everything was working fine for a month. Now I am able to send private messages but not group messages. Any Update?

**Comment by jlguardi** [comment]
Partially avoided but not fixed in #1364 and #1361.

**Comment by mikkolindfors** [comment]
Try adding -M to command, it worked for me

**Comment by theSha1chemist** [comment]
Yeah this happened to my bot in group messages only - since 2 days ago

**Comment by kumarshivam675** [comment]
@jlguardi - It worked.. Thanks

**Comment by tgalal** [comment]
Error gone in latest update, real fix through full encrypted groups supported is WIP
