### ISSUE TITLE
AttributeError: 'ProtocolTreeNode' object has no attribute 'getTag' - even with all layers in place and proper order!

### ISSUE THREAD

**Issue by jodersus** [tgalal/yowsup#1222]
Hi,
I am trying to send an image; I literally copied the code from yowsup-cli, but I keep getting this error.
I have read #595 and other issues reference from there, and ammended my stack build (not much change from my original setup).
```
      layers = (
            WsapLayer,
            YowParallelLayer([
              YowAuthenticationProtocolLayer, 
              YowMessagesProtocolLayer, 
              YowReceiptProtocolLayer, 
              YowAckProtocolLayer, 
              YowMediaProtocolLayer, 
              YowIqProtocolLayer,
              YowPresenceProtocolLayer,
              YowChatstateProtocolLayer,
              YowContactsIqProtocolLayer,
              YowGroupsProtocolLayer,
              YowIbProtocolLayer,
              YowPrivacyProtocolLayer,
              YowProfilesProtocolLayer,
              YowCallsProtocolLayer]),
            YowAxolotlLayer) +\
            (YowLoggerLayer,
            YowCoderLayer,
            YowCryptLayer,
            YowStanzaRegulator,
            YowNetworkLayer
        )
      self.stack = YowStack(layers)
      self.stack.setCredentials(credentials)
```

And this is the error message I get. 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/data/wsap/echo/wsap_layer.py", line 90, in onMessage
    self.image_send(jid = messageProtocolEntity.getFrom(), path = emo[1], caption = emo[2])
  File "/data/wsap/echo/wsap_layer.py", line 192, in image_send
    self._sendIq(entity, successFn, errorFn)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 126, in _sendIq
    self.toLower(iqEntity.toProtocolTreeNode())
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 173, in send
    s.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 108, in send
    if entity.getTag() in self.handleMap:
AttributeError: 'ProtocolTreeNode' object has no attribute 'getTag'
```

Help, please?
A

**Comment by jodersus** [comment]
Caught the error, sorry, I was inhering from YowProtocolLayer instead of YowInterfaceLayer.
Now it works (though I have another problem with the iq upload, which I will post in a separte issue ticket)
