### ISSUE TITLE
Echo Client not working anymore

### ISSUE THREAD

**Issue by iAeneas** [tgalal/yowsup#1225]
Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 229, in process
    self.startEcho()
  File "./yowsup-cli", line 265, in startEcho
    stack.start()
  File "/home/john/myYowsup/yowsup-master/yowsup/demos/echoclient/stack.py", line 48, in start
    self.stack.loop()
  File "/home/john/myYowsup/yowsup-master/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/**init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/__init**.py", line 169, in receive
    s.receive(data)
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/**init**.py", line 105, in receive
    recv(node)
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'

Any suggestions?
##

**Comment by jlmadurga** [comment]
Are you using axolotl layer? I think this error is raised when you are receiving encrypted message but encryption is no enabled in yowsup

**Comment by iAeneas** [comment]
Couple of days ago worked: ./yowsup-cli demos -c conf -M -e.
Now it doesn't.
Btw, how can i stop using axoltl layer? I thought -M disabled the encryption.

**Comment by jlmadurga** [comment]
Test it enabling encryption removing -M option, it should work. I had the same issue.

**Comment by iAeneas** [comment]
I have tried without -M:

Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 229, in process
    self.startEcho()
  File "./yowsup-cli", line 264, in startEcho
    stack = echoclient.YowsupEchoStack(credentials, not self.args["unmoxie"])
  File "/home/john/myYowsup/yowsup-master/yowsup/demos/echoclient/stack.py", line 20, in __init__
    from yowsup.layers.axolotl                     import YowAxolotlLayer
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/axolotl/layer.py", line 2, in <module>
    from .protocolentities import SetKeysIqProtocolEntity
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/axolotl/protocolentities/__init__.py", line 3, in <module>
    from .iq_keys_get_result import ResultGetKeysIqProtocolEntity
  File "/home/john/myYowsup/yowsup-master/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 4, in <module>
    from axolotl.identitykey import IdentityKey
  File "/usr/local/lib/python2.7/dist-packages/axolotl/identitykey.py", line 1, in <module>
    from .ecc.curve import Curve
  File "/usr/local/lib/python2.7/dist-packages/axolotl/ecc/curve.py", line 1, in <module>
    import axolotl_curve25519 as _curve
ImportError: No module named axolotl_curve25519

**Comment by jlmadurga** [comment]
You need to have `python-axolotl` installed and all its dependencies.
`deps = ["protobuf>=2.6,<3.0.0-alpha-2", "pycrypto", "python-axolotl-curve25519"]`

**Comment by iAeneas** [comment]
I think i got everything:

Installed /usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg
Processing dependencies for yowsup2==2.4.48
Searching for Pillow==2.3.0
Best match: Pillow 2.3.0
Pillow 2.3.0 is already the active version in easy-install.pth

Using /usr/lib/python2.7/dist-packages
Searching for python-axolotl==0.1.7
Best match: python-axolotl 0.1.7
Adding python-axolotl 0.1.7 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for argparse==1.2.1
Best match: argparse 1.2.1
argparse 1.2.1 is already the active version in easy-install.pth

Using /usr/lib/python2.7
Searching for python-dateutil==2.4.2
Best match: python-dateutil 2.4.2
Adding python-dateutil 2.4.2 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for python-axolotl-curve25519==0.1
Best match: python-axolotl-curve25519 0.1
Processing python_axolotl_curve25519-0.1-py2.7-linux-x86_64.egg
python-axolotl-curve25519 0.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/python_axolotl_curve25519-0.1-py2.7-linux-x86_64.egg
Searching for pycrypto==2.6.1
Best match: pycrypto 2.6.1
pycrypto 2.6.1 is already the active version in easy-install.pth

Using /usr/lib/python2.7/dist-packages
Searching for protobuf==3.0.0-alpha-1
Best match: protobuf 3.0.0-alpha-1
Removing protobuf 2.5.0 from easy-install.pth file
Adding protobuf 3.0.0-alpha-1 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for six==1.5.2
Best match: six 1.5.2
Adding six 1.5.2 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for setuptools==3.3
Best match: setuptools 3.3
setuptools 3.3 is already the active version in easy-install.pth
Installing easy_install script to /usr/local/bin
Installing easy_install-2.7 script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for yowsup2==2.4.48


But still not working!
Thx tho for your help!

**Comment by paul218** [comment]
some body can resolve these problem ???

**Comment by paul218** [comment]
i can resolve this problem .. you should use the layers axelotl  in your run.py ..and it is all ... echolayer runs again 

    def recv_message():
        
            from yowsup.layers.axolotl                     import YowAxolotlLayer
            layers = (
                EchoLayer,
                YowParallelLayer([YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer, YowMediaProtocolLayer, YowIqProtocolLayer, YowCallsProtocolLayer]),
                YowAxolotlLayer,
                YowLoggerLayer,
                YowCoderLayer,
                YowCryptLayer,
                YowStanzaRegulator,
                YowNetworkLayer
            )

        self.stack = YowStack(layers)

**Comment by iAeneas** [comment]
I can not find any file named "run.py" and there is no function named "recv_message".The closest thing is "recvMessageStanza" in "layers/protocol_messages/layers.py.
Could you be more explicit.
Thank you.

**Comment by jlmadurga** [comment]
What he is saying is analogue not to use -M option in Cli. The problem you have with `No module named axolotl_curve25519` is related with not correct installation of libraries

**Comment by iAeneas** [comment]
As I stated earlier it doesn't work without -M either.

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 229, in process
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 264, in startEcho
    
  File "build/bdist.linux-x86_64/egg/yowsup/demos/echoclient/stack.py", line 20, in __init__
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/axolotl/util/keyhelper.py", line 3, in <module>
    from ..identitykeypair import IdentityKeyPair
  File "/usr/local/lib/python2.7/dist-packages/axolotl/identitykeypair.py", line 1, in <module>
    from .state.storageprotos import IdentityKeyPairStructure
  File "/usr/local/lib/python2.7/dist-packages/axolotl/state/storageprotos.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database

Other sugestions?

**Comment by paul218** [comment]
ahh sorry ,I create a new script, based on yowsup-cli, but if you can see the script yowsup-cli here impor of yowsup/yowsup/demos/echoclient/ the script 	echoclient in these folder there is a stack.py and it contain the next 

from yowsup.stacks import YowStack
from .layer import EchoLayer
from yowsup.layers import YowLayerEvent
from yowsup.layers.auth                        import YowCryptLayer, YowAuthenticationProtocolLayer, AuthError
from yowsup.layers.coder                       import YowCoderLayer
from yowsup.layers.network                     import YowNetworkLayer
from yowsup.layers.protocol_messages           import YowMessagesProtocolLayer
from yowsup.layers.protocol_media              import YowMediaProtocolLayer
from yowsup.layers.stanzaregulator             import YowStanzaRegulator
from yowsup.layers.protocol_receipts           import YowReceiptProtocolLayer
from yowsup.layers.protocol_acks               import YowAckProtocolLayer
from yowsup.layers.logger                      import YowLoggerLayer
from yowsup.layers.protocol_iq                 import YowIqProtocolLayer
from yowsup.layers.protocol_calls              import YowCallsProtocolLayer
from yowsup.layers                             import YowParallelLayer

class YowsupEchoStack(object):
    def __init__(self, credentials, encryptionEnabled = False):
        if encryptionEnabled:
            from yowsup.layers.axolotl                     import YowAxolotlLayer
            layers = (
                EchoLayer,
                YowParallelLayer([YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer, YowMediaProtocolLayer, YowIqProtocolLayer, YowCallsProtocolLayer]),
                YowAxolotlLayer,
                YowLoggerLayer,
                YowCoderLayer,
                YowCryptLayer,
                YowStanzaRegulator,
                YowNetworkLayer
            )
        else:
            layers = (
                EchoLayer,
                YowParallelLayer([YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer, YowMediaProtocolLayer, YowIqProtocolLayer, YowCallsProtocolLayer]),
                YowLoggerLayer,
                YowCoderLayer,
                YowCryptLayer,
                YowStanzaRegulator,
                YowNetworkLayer
            )

        self.stack = YowStack(layers)
        self.stack.setCredentials(credentials)

    def start(self):
        self.stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))
        try:
            self.stack.loop()
        except AuthError as e:
            print("Authentication Error: %s" % e.message)


you can see the next statement , and this solves the error ..

  if encryptionEnabled:
            from yowsup.layers.axolotl                     import YowAxolotlLayer
layers = (
                EchoLayer,
                YowParallelLayer([YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer, YowMediaProtocolLayer, YowIqProtocolLayer, YowCallsProtocolLayer]),
                YowAxolotlLayer,
                YowLoggerLayer,
                YowCoderLayer,
                YowCryptLayer,
                YowStanzaRegulator,
                YowNetworkLayer
            )

.i can suggest  install the lasted version of yowsup  and run yowsup-cli:

Create a file to save your credentials

sudo nano /home/pi/yowsup/config
with this content

## Actual config starts below ##
  cc=593 #if not specified it will be autodetected,593 number of your country
  phone=593xxxxxxxxxx
  password=xxxxxxxxxxxxxxx=
Ok, we're ready for the test, Yowsup has a demo application in /home/pi/yowsup/yowsup/demos

Navigate to yowsup folder

cd /home/pi/yowsup
Start yowsup-cli demos with the command

yowsup-cli demos --yowsup --config config
enter the login with /L 

here you see that started to download something .. then  you can send and recieve messages

**Comment by iAeneas** [comment]
I do not think i understand the first part. Indeed I've got those lines in stack.py but the you state
"you can see the next statement , and this solves the error ..

if encryptionEnabled:
from yowsup.layers.axolotl import YowAxolotlLayer
layers = (
EchoLayer,
YowParallelLayer([YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer, YowMediaProtocolLayer, YowIqProtocolLayer, YowCallsProtocolLayer]),
YowAxolotlLayer,
YowLoggerLayer,
YowCoderLayer,
YowCryptLayer,
YowStanzaRegulator,
YowNetworkLayer
)"

What am I supposed to? Eliminate the rest of the file after the if is ending? I ask this because the "if" in the file and the "if" you posted are the same.

P.S. I installed your mentions and the conf file is alright but still not working.

**Comment by paul218** [comment]
sorry the problem return ...i cant recieve messages ... 
when try to sent show this:
No handlers could be found for logger "yowsup.layers.axolotl.layer"
closing
....
now i dont know to do

**Comment by ashishradadia** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in startSendClient
    not self.args["unmoxie"])
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/demos/sendclient/stack.py", line 26, in __init__
    self.stack.setCredentials(credentials)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/stacks/yowstack.py", line 156, in setCredentials
    self.getLayerInterface(YowAuthenticationProtocolLayer).setCredentials(*credentials)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/auth/layer_interface_authentication.py", line 5, in setCredentials
    self._layer.setCredentials((phone, password))
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/auth/layer_authentication.py", line 46, in setCredentials
    self._credentials = self.__getCredentials(credentials)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/auth/layer_authentication.py", line 41, in __getCredentials
    password = base64.b64decode(pb64)
  File "/usr/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

i get this error
