### ISSUE TITLE
What is the difference between jid, contact and number in yowsup-cli

### ISSUE THREAD

**Issue by jerryames** [tgalal/yowsup#1226]
Some of them need a number like
/message       send  number  content 
I figure this out, just put the phone number there

What is jid then?
/contact       picture  jid
I never figure out what should I put in jid

And contacts

/statuses      get            contacts
That is the feature I am waiting for months, but, cannot figure out how to use it.
I put phone number to replaces contacts, the whole yowsup just stopped and give out tons of error messages.

 What should I put in the <contacts> in /statuses

Thank you!
##

**Comment by jerryames** [comment]
The error message when use /statuses get phonenumber

[connected]:Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/local/lib/python3.4/dist-packages/setuptools-11.1-py3.4.egg/pkg_resources/__init__.py", line 696, in run_script
  File "/usr/local/lib/python3.4/dist-packages/setuptools-11.1-py3.4.egg/pkg_resources/__init__.py", line 1621, in run_script
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/EGG-INFO/scripts/yowsup-cli", line 227, in process
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/EGG-INFO/scripts/yowsup-cli", line 255, in startCmdline
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/demos/cli/stack.py", line 25, in start
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/stacks/yowstack.py", line 187, in loop
  File "/usr/lib/python3.4/asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.4/asyncore.py", line 153, in poll
    read(obj)
  File "/usr/lib/python3.4/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.4/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.4/asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/network/layer.py", line 86, in handle_read
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/network/layer.py", line 94, in receive
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/axolotl/layer.py", line 126, in receive
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__init__.py", line 169, in receive
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__init__.py", line 105, in receive
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/protocol_contacts/layer.py", line 32, in recvIq
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/interface/interface.py", line 98, in receive
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/demos/cli/layer.py", line 472, in onIq
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/protocol_contacts/protocolentities/iq_statuses_result.py", line 31, in __str__
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by moyamo** [comment]
Use python 2 (maybe that's a bug). jid is 'contact@s.whatsapp.net'

**Comment by Miguel1422** [comment]
As you are in python3 , you need to use items() instead of iteritems(), iteritems() was removed in python3, so you can't use this method anymore. So you can go to yowsup/layers/protocol_contacts/protocolentities/iq_statuses_result.py and in line 31 change it that works for me

**Comment by jerryames** [comment]
Yes, I am using python3 and Yes, change from iteritems to items solve the problem! :)

Thank you, Miguel1422 & moyamo!
