### ISSUE TITLE
Sample Application not running 

### ISSUE THREAD

**Issue by iorch** [tgalal/yowsup#1240]
I tried to run the example in the Wiki. I have just copied the code, and started the script with `python run.py` as indicated in the wiki, however, I never received the "Logged in" notification, but seems to be running. When I send a a message, the app crashes with this message:
````
Traceback (most recent call last):
  File "run.py", line 32, in <module>
    stack.loop() #this is the program mainloop
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/stacks/yowstack.py", line 195, in loop
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/asyncore.py", line 150, in poll
    read(obj)
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/asyncore.py", line 87, in read
    obj.handle_error()
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/network/layer.py", line 86, in handle_read
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/network/layer.py", line 94, in receive
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    if messageProtocolEntity.getMediaType() == "image":
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/coder/layer.py", line 35, in receive
    print("Echoing vcard (%s, %s) to %s" % (messageProtocolEntity.getName(), messageProtocolEntity.getCardData(), messageProtocolEntity.getFrom(False)))
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toLower(messageProtocolEntity.ack())
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 169, in receive
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/__init__.py", line 105, in receive
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    self.toLower(entity.ack())
  File "/home/jorge/.pyenv/versions/3.5.1/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
AttributeError: 'NoneType' object has no attribute 'getData'
```

**Comment by iorch** [comment]
Solved in https://github.com/tgalal/yowsup/issues/690
