### ISSUE TITLE
error : 'NoneType' object has no attribute 'getChild'

### ISSUE THREAD

**Issue by deounix** [tgalal/yowsup#1266]
SolVed!!

in "yowsup/layers/axolotl/protocolentities/iq_keys_get_result"

Edited to :

            try: preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
            except: preKeyId = None; pass
            try: preKeyPublic = DjbECPublicKey(ResultGetKeysIqProtocolEntity.encStr(preKeyNode.getChild("value").getData()))
            except: preKeyPublic = None; pass

but now how can I build this to include it in Python?

I'm trying "python setup.py install" but these plugins didn't move to python lib

**Comment by deounix** [comment]
Also when I'm trying to run my account with echoclient from demos and when I'm trying to send msg show to me this error :

Traceback (most recent call last):
  File "./yowsup-cli", line 326, in <module>
    if not parser.process():
  File "./yowsup-cli", line 229, in process
    self.startEcho()
  File "./yowsup-cli", line 265, in startEcho
    stack.start()
  File "/root/yowsup-master/yowsup/demos/echoclient/stack.py", line 48, in start
    self.stack.loop()
  File "/root/yowsup-master/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/local/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/local/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/local/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/root/yowsup-master/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/root/yowsup-master/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/root/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/root/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/root/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/root/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/root/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/root/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup-master/yowsup/layers/axolotl/layer.py", line 115, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/root/yowsup-master/yowsup/layers/__init__.py", line 136, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/root/yowsup-master/yowsup/layers/axolotl/layer.py", line 175, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "/root/yowsup-master/yowsup/layers/axolotl/layer.py", line 339, in onGetKeysResult
    entity = ResultGetKeysIqProtocolEntity.fromProtocolTreeNode(resultNode)
  File "/root/yowsup-master/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 87, in fromProtocolTreeNode
    preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
AttributeError: 'NoneType' object has no attribute 'getChild'

What is the problem ?

**Comment by deounix** [comment]
I fix it, 


in "yowsup/layers/axolotl/protocolentities/iq_keys_get_result"

Edited to :

            try: preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
            except: preKeyId = None; pass
            try: preKeyPublic = DjbECPublicKey(ResultGetKeysIqProtocolEntity.encStr(preKeyNode.getChild("value").getData()))
            except: preKeyPublic = None; pass

but now how can I build this to include it in Python?

I'm trying "python setup.py install" but these plugins didn't move to python lib

**Comment by Lucky-Kumar** [comment]
Thanks a lot for this peice of code. You are really awesome :D
