### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed: prekeys.prekey_id

### ISSUE THREAD

**Issue by ganesansays** [tgalal/yowsup#1277]
I am getting the following error in CLI, but not in my own program. But my program stops doing anything after logging in. This happens for a while (Say 30 mins) and the application starts getting the older messages. This happens only if the application gets out of the main loop and tries to login again. Is there a way to keep the main loop running without logging off and logging back again? (stack.loop())?

From: Number-1453819990@g.us
Type: w:gp2
Participant: Number@s.whatsapp.net

[connected]:
Storing prekeys 100%
Notification: Notification
From: Number-1453436436@g.us
Type: picture

[connected]:
Iq:ring prekeys 100%
ID: 23
Type: result
from: number@s.whatsapp.net

(.......) Removed for brevity 

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 227, in process
    self.startCmdline()
  File "/usr/local/bin/yowsup-cli", line 255, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/demos/cli/stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/**init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 115, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 136, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 312, in <lambda>
    onResult = lambda _, __: self.persistKeys(registrationId, identityKeyPair, preKeys, signedPreKey, fresh)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 325, in persistKeys
    self.store.storePreKey(preKey.getId(), preKey)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 38, in storePreKey
    self.preKeyStore.storePreKey(preKeyId, preKeyRecord)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/store/sqlite/liteprekeystore.py", line 36, in storePreKey
    cursor.execute(q, (preKeyId, preKeyRecord.serialize()))
sqlite3.IntegrityError: UNIQUE constraint failed: prekeys.prekey_id
##

**Comment by tgalal** [comment]
dba50de
