### ISSUE TITLE
send a message via CLI

### ISSUE THREAD

**Issue by albertjordan** [tgalal/yowsup#1284]
I'm trying to send a test message using the command line interface.  I've tried two variations and both fail.  Any hints or help will be appreciated.

first variation is to use the -l option as below.  I complains that I am providing one extra argument and not sure what I can cut (i need credentials, the target phone number, and the message)
```
$ yowsup-cli demos -l:1650823XXX:JvcBT4Vt2DGT345oXXXXXXXXXXX -s 16502694442 "hello"  
Traceback (most recent call last):
  File "/Users/Albert/anaconda/bin/yowsup-cli", line 4, in <module>
    **import**('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/Users/Albert/anaconda/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/**init**.py", line 735, in run_script
  File "/Users/Albert/anaconda/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/**init**.py", line 1659, in run_script
  File "/Users/Albert/anaconda/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>

  File "/Users/Albert/anaconda/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process

  File "/Users/Albert/anaconda/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 279, in startSendClient

  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/demos/sendclient/stack.py", line 49, in **init**
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/stacks/yowstack.py", line 155, in setCredentials
TypeError: setCredentials() takes exactly 3 arguments (4 given)

I also try the option where I submit a configuration file per below, and get an error message as well

yowsup-cli demos -s 1650269xxxx "hello" -c /Users/Albert/Development/Python/yowsup-master/config2.txt
INFO:yowsup.layers.axolotl.layer:Axolotl layer is generating keys
Traceback (most recent call last):
  File "/Users/Albert/anaconda/bin/yowsup-cli", line 4, in <module>
    **import**('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/Users/Albert/anaconda/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/**init**.py", line 735, in run_script
  File "/Users/Albert/anaconda/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/**init**.py", line 1659, in run_script
  File "/Users/Albert/anaconda/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>

  File "/Users/Albert/anaconda/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process

  File "/Users/Albert/anaconda/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 280, in startSendClient

  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/demos/sendclient/stack.py", line 54, in start
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/stacks/yowstack.py", line 195, in loop
  File "/Users/Albert/anaconda/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/Users/Albert/anaconda/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/Users/Albert/anaconda/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/Users/Albert/anaconda/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/Users/Albert/anaconda/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/network/layer.py", line 86, in handle_read
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/network/layer.py", line 94, in receive
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/axolotl/layer.py", line 115, in receive
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/**init**.py", line 136, in processIqRegistry
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/axolotl/layer.py", line 175, in <lambda>
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/axolotl/layer.py", line 354, in onGetKeysResult
  File "/Users/Albert/anaconda/lib/python2.7/site-packages/axolotl/sessionbuilder.py", line 157, in processPreKeyBundle
    .setOurIdentityKey(self.identityKeyStore.getIdentityKeyPair())\
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 17, in getIdentityKeyPair
  File "build/bdist.macosx-10.5-x86_64/egg/yowsup/layers/axolotl/store/sqlite/liteidentitykeystore.py", line 31, in getIdentityKeyPair
TypeError: 'NoneType' object is not utterable
```

**Comment by jlguardi** [comment]
1st Remove : after -l
2nd start cli app an login in interactive mode to generate axolotl keys.

**Comment by aldoleyva** [comment]
In this moment yowsup is working properly ?
I think Whatsapp Inc is making changes that are affecting to Yowsup an Chat API.
