### ISSUE TITLE
yowsup not connecting any more, cant request new code or sth.

### ISSUE THREAD

**Issue by e0xify** [tgalal/yowsup#1285]
Hello guys,

yesterday my yowsup seems not working properly anymore, so i restarted my bot.
since then i was not able to start it again, after login i get instantly / disconnected.

by requesting a new sms code to check if sth is blocked i get.

`root@h2476922:/home/ts3# yowsup-cli registration --requestcode sms --phone 49xxxxxx --cc 49 --mcc 123 --mnc 456                                                                                                
Traceback (most recent call last):                                                                                                                                                                                 
  File "/usr/local/bin/yowsup-cli", line 323, in <module>                                                                                                                                                          
    if not parser.process():                                                                                                                                                                                       
  File "/usr/local/bin/yowsup-cli", line 158, in process                                                                                                                                                           
    self.handleRequestCode(self.args["requestcode"], config)                                                                                                                                                       
  File "/usr/local/bin/yowsup-cli", line 176, in handleRequestCode                                                                                                                                                 
    result = codeReq.send()                                                                                                                                                                                        
  File "/usr/local/lib/python2.7/dist-packages/yowsup/registration/coderequest.py", line 39, in send                                                                                                               
    result = request.send()                                                                                                                                                                                        
  File "/usr/local/lib/python2.7/dist-packages/yowsup/registration/existsrequest.py", line 26, in send                                                                                                             
    res = super(WAExistsRequest, self).send(parser)                                                                                                                                                                
  File "/usr/local/lib/python2.7/dist-packages/yowsup/common/http/warequest.py", line 73, in send                                                                                                                  
    return self.sendGetRequest(parser)                                                                                                                                                                             
  File "/usr/local/lib/python2.7/dist-packages/yowsup/common/http/warequest.py", line 111, in sendGetRequest                                                                                                       
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET")                                                                                                                                
  File "/usr/local/lib/python2.7/dist-packages/yowsup/common/http/warequest.py", line 167, in sendRequest                                                                                                          
    conn.request(reqType, path, params, headers);                                                                                                                                                                  
  File "/usr/lib/python2.7/httplib.py", line 979, in request                                                                                                                                                       
    self._send_request(method, url, body, headers)                                                                                                                                                                 
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request                                                                                                                                                
    self.endheaders(body)                                                                                                                                                                                          
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders                                                                                                                                                    
    self._send_output(message_body)                                                                                                                                                                                
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output                                                                                                                                                  
    self.send(msg)                                                                                                                                                                                                 
  File "/usr/lib/python2.7/httplib.py", line 797, in send                                                                                                                                                          
    self.connect()                                                                                                                                                                                                 
  File "/usr/lib/python2.7/httplib.py", line 1178, in connect                                                                                                                                                      
    self.timeout, self.source_address)                                                                                                                                                                             
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection                                                                                                                                              
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):                                                                                                                                                            
socket.gaierror: [Errno -2] Name or service not known               `

**Comment by e0xify** [comment]
local dns resolve issue.
