### ISSUE TITLE
Question about setting Presence name on sending without the yowsup commandline

### ISSUE THREAD

**Issue by alx090** [tgalal/yowsup#1298]
Hello,
i tried to do this:https://github.com/tgalal/yowsup/issues/702
my command was:  sudo yowsup-cli demos -c config.example -s 4917xxxxxxxxx Hi
The name which have to be shown on the reciving device is just the registration number.
`Traceback (most recent call last):
  File "/home/pi/yowsup-master/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/home/pi/yowsup-master/yowsup-cli", line 231, in process
    self.startSendClient()
  File "/home/pi/yowsup-master/yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/home/pi/yowsup-master/yowsup/demos/sendclient/stack.py", line 53, in start
    self.stack.loop()
  File "/home/pi/yowsup-master/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/pi/yowsup-master/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/home/pi/yowsup-master/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/home/pi/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/pi/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/home/pi/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/home/pi/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/pi/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/pi/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/pi/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/pi/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup-master/yowsup/layers/axolotl/layer.py", line 126, in receive
    self.toUpper(protocolTreeNode)
  File "/home/pi/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup-master/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/home/pi/yowsup-master/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/home/pi/yowsup-master/yowsup/layers/auth/layer_authentication.py", line 71, in handleSuccess
    self.toUpper(nodeEntity)
  File "/home/pi/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup-master/yowsup/layers/interface/interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "/home/pi/yowsup-master/yowsup/demos/sendclient/layer.py", line 24, in onSuccess
    entity = PresenceProtocolEntity(name = "my name")
NameError: global name 'PresenceProtocolEntity' is not defined
`
I hope you can help me. Thanks

**Comment by jlguardi** [comment]
As sed in the thread that you commented: "Have you imported YowPresenceProtocolLayer?"

**Comment by alx090** [comment]
I did, here is my stack.py(in sendclient folder):http://pastebin.com/RWHFZndt
here is my layer.py (in sendclient folder):http://pastebin.com/8NrNTZiX

**Comment by shedokan** [comment]
The problem is that you need to use YowPresenceProtocolLayer and not PresenceProtocolLayer as your exception mentioned, cheers :)
