### ISSUE TITLE
Exception: No such prekeyRecord!   File "/opt/transwhat/transwhat.py", line 95, in <module>

### ISSUE THREAD

**Issue by thundergreen** [tgalal/yowsup#1303]
2016-02-11 00:14:58,803 ERROR transwhat: Traceback (most recent call last):
  File "/opt/transwhat/transwhat.py", line 95, in <module>
    asyncore.loop(timeout=1.0, count=10, use_poll = True)
  File "/usr/lib/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
  File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 117, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 139, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 222, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 259, in handlePreKeyWhisperMessage
    plaintext = sessionCipher.decryptPkmsg(preKeyWhisperMessage)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessioncipher.py", line 91, in decryptPkmsg
    unsignedPreKeyId = self.sessionBuilder.process(sessionRecord, ciphertext)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 43, in process
    unsignedPreKeyId = self.processV3(sessionRecord, message)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 113, in processV3
    parameters.setOurOneTimePreKey(self.preKeyStore.loadPreKey(message.getPreKeyId()).getKeyPair())
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 32, in loadPreKey
    return self.preKeyStore.loadPreKey(preKeyId)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/store/sqlite/liteprekeystore.py", line 20, in loadPreKey
    raise Exception("No such prekeyRecord!")
Exception: No such prekeyRecord!

2016-02-11 00:14:58,820 ERROR transwhat: Traceback (most recent call last):
  File "/opt/transwhat/transwhat.py", line 95, in <module>
    asyncore.loop(timeout=1.0, count=10, use_poll = True)
  File "/usr/lib/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
  File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 117, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 139, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 222, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 259, in handlePreKeyWhisperMessage
    plaintext = sessionCipher.decryptPkmsg(preKeyWhisperMessage)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessioncipher.py", line 91, in decryptPkmsg
    unsignedPreKeyId = self.sessionBuilder.process(sessionRecord, ciphertext)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 43, in process
    unsignedPreKeyId = self.processV3(sessionRecord, message)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 113, in processV3
    parameters.setOurOneTimePreKey(self.preKeyStore.loadPreKey(message.getPreKeyId()).getKeyPair())
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 32, in loadPreKey
    return self.preKeyStore.loadPreKey(preKeyId)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/store/sqlite/liteprekeystore.py", line 20, in loadPreKey
    raise Exception("No such prekeyRecord!")
Exception: No such prekeyRecord!

**Comment by thundergreen** [comment]
After deletion of axolotl.DB error disappeared
