### ISSUE TITLE
Unhandled stream error

### ISSUE THREAD

**Issue by thundergreen** [tgalal/yowsup#1307]
2016-02-13 11:00:16,528 ERROR transwhat: Traceback (most recent call last):
  File "/opt/transwhat/transwhat.py", line 95, in <module>
    asyncore.loop(timeout=1.0, count=10, use_poll = True)
  File "/usr/lib/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
  File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-armv7l/egg/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/**init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "build/bdist.linux-armv7l/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer.py", line 126, in receive
    self.toUpper(protocolTreeNode)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init**.py", line 59, in toUpper
    self.**upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init**.py", line 169, in receive
    s.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/**init**.py", line 105, in receive
    recv(node)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/auth/layer_authentication.py", line 89, in handleStreamError
    raise AuthError("Unhandled stream:error node:\n%s" % node)
AuthError: Unhandled stream:error node:
stream:error
<xml-not-well-formed>
</xml-not-well-formed>
/stream:error

2016-02-13 11:00:16,564 DEBUG yowsup.layers.network.layer: Disconnected, reason: Connection Closed
##

**Comment by nlsdfnbch** [comment]
Same here.

`Traceback (most recent call last):
  File "stack.py", line 89, in <module>
    stack.loop() #this is the program mainloop
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/stacks/yows                                                            tack.py", line 195, in loop
  File "/usr/lib/python3.4/asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.4/asyncore.py", line 153, in poll
    read(obj)
  File "/usr/lib/python3.4/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.4/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.4/asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/netw                                                            ork/layer.py", line 86, in handle_read
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/netw                                                            ork/layer.py", line 94, in receive
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__in                                                            it__.py", line 59, in toUpper
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/stan                                                            zaregulator/layer.py", line 28, in receive

  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/stan                                                            zaregulator/layer.py", line 48, in processReceived
    def onMediaMessage(self, messageProtocolEntity):
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__in                                                            it__.py", line 59, in toUpper
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/auth                                                            /layer_crypt.py", line 63, in receive
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__in                                                            it__.py", line 59, in toUpper
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/code                                                            r/layer.py", line 35, in receive
    self.toLower(entity.ack())
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__in                                                            it__.py", line 59, in toUpper
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/logg                                                            er/layer.py", line 14, in receive
    media = '/mnt/arcanum/argos/data/bropocalypse/media'
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__in                                                            it__.py", line 59, in toUpper
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/axol                                                            otl/layer.py", line 126, in receive
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__in                                                            it__.py", line 59, in toUpper
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__in                                                            it__.py", line 169, in receive
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/__in                                                            it__.py", line 105, in receive
  File "/usr/local/lib/python3.4/dist-packages/yowsup2-2.4.48-py3.4.egg/yowsup/layers/auth                                                            /layer_authentication.py", line 89, in handleStreamError
yowsup.layers.auth.autherror.AuthError: Unhandled stream:error node:
<stream:error>
<ping id="1455369386">
</ping>
</stream:error>
`

**Comment by deounix** [comment]
same error happened to me .


```
<stream:error>
<xml-not-well-formed>
</xml-not-well-formed>
</stream:error>
Traceback (most recent call last):
  File "src/server.py", line 38, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/local/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python2.7/asyncore.py", line 201, in poll2
    readwrite(obj, flags)
  File "/usr/local/lib/python2.7/asyncore.py", line 123, in readwrite
    obj.handle_error()
  File "/usr/local/lib/python2.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
  File "/usr/local/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 126, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/auth/layer_authentication.py", line 89, in handleStreamError
    raise AuthError("Unhandled stream:error node:\n%s" % node)
AuthError: Unhandled stream:error node:
<stream:error>
<xml-not-well-formed>
</xml-not-well-formed>
</stream:error>
```

**Comment by Marcovus** [comment]
see: #873
