### ISSUE TITLE
Not able to register mobile number

### ISSUE THREAD

**Issue by naveen1988** [tgalal/yowsup#1322]
i am getting the following error when ever i try to register mobile number in ubuntu...Please could anyone help me how to resolve this..

Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 158, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup-cli", line 176, in handleRequestCode
    result = codeReq.send()
  File "/home/patil/Desktop/yowsup-master/yowsup/registration/coderequest.py", line 46, in send
    res = super(WACodeRequest, self).send(parser)
  File "/home/patil/Desktop/yowsup-master/yowsup/common/http/warequest.py", line 73, in send
    return self.sendGetRequest(parser)
  File "/home/patil/Desktop/yowsup-master/yowsup/common/http/warequest.py", line 111, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET")
  File "/home/patil/Desktop/yowsup-master/yowsup/common/http/warequest.py", line 167, in sendRequest
    conn.request(reqType, path, params, headers);
  File "/usr/lib/python2.7/httplib.py", line 966, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1000, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 962, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 822, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 784, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1165, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

**Comment by abdhan** [comment]
Try this https://github.com/tgalal/yowsup/issues/1285
