### ISSUE TITLE
Not able to send image using yowsup-cli demos command line client

### ISSUE THREAD

**Issue by abhiroock** [tgalal/yowsup#1339]
I tried to send image using command line client like this 
"yowsup-cli demos -c config.txt -i \usr\src\imag1.jpg image"  for uploading image to whatsapp server.But i am getting error like below.

[root@IMS_Dev yowsup-master]# yowsup-cli demos --debug -c config.txt -i /usr/src/imag1.jpg image
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Media Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
Traceback (most recent call last):
 File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
 File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 724, in run_script

 File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 1657, in run_script

 File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 347, in <module>

 File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 239, in process

 File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 303, in startSendImgClient

 File "build/bdist.linux-i686/egg/yowsup/demos/sendclient/stack.py", line 54, in start
 File "build/bdist.linux-i686/egg/yowsup/stacks/yowstack.py", line 177, in broadcastEvent
 File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 76, in broadcastEvent

 File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 187, in onEvent

 File "build/bdist.linux-i686/egg/yowsup/layers/protocol_media/layer.py", line 25, in onEvent
TypeError: getArg() takes exactly 2 arguments (3 given)

**Comment by jlguardi** [comment]
@abhiroock You aren't using HEAD code because yowsup/layers/protocol_media/layer.py", line 25 is commented out on HEAD.

Update to master and try again.

**Comment by abhiroock** [comment]
@jlguardi Thanks a lot

**Comment by abhiroock** [comment]
@jlguardi  i tired to send image by using this command format like this got an error 

[root@IMS_Dev yowsup-master]# yowsup-cli demos --debug -c config.txt -i  \usr\src\imag1.jpg image
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Media Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e14.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="919591995560" mechanism="WAUTH-2">
▒!▒z▒▒▒/▒[ ▒i▒▒ ▒▒t5▒▒뭮▒▒▒'"▒_+▒▒i#▒
HEX:00e721e87a1301ddedf02fd45b20d369abee20b0fd1f7435a0f2b31eebadaef3fccb2722ed1f5f2bb095692302d0
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1454392056" expiration="4444444444" props="4" t="1457352269">
▒▒u▒S▒_]h]T▒▒▒▒(}▒▒
HEX:a7f575f253ba065f5d685d548b8f9786287dacc5
</success>

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 724, in run_script

  File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 1657, in run_script

  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 347, in <module>

  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 239, in process

  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 303, in startSendImgClient

  File "build/bdist.linux-i686/egg/yowsup/demos/sendclient/stack.py", line 56, in start
  File "build/bdist.linux-i686/egg/yowsup/stacks/yowstack.py", line 195, in loop
  File "/usr/local/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/local/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/local/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-i686/egg/yowsup/layers/network/layer.py", line 86, in handle_read
  File "build/bdist.linux-i686/egg/yowsup/layers/network/layer.py", line 94, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-i686/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
  File "build/bdist.linux-i686/egg/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
  File "build/bdist.linux-i686/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-i686/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-i686/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-i686/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 169, in receive

  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 105, in receive

  File "build/bdist.linux-i686/egg/yowsup/layers/auth/layer_authentication.py", line 71, in handleSuccess
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-i686/egg/yowsup/layers/interface/interface.py", line 98, in receive
  File "build/bdist.linux-i686/egg/yowsup/demos/sendclient/layer.py", line 26, in onSuccess
ValueError: need more than 1 value to unpack

**Comment by jlguardi** [comment]
@abhiroock 

Where are you getting from the code? Download latest version from the web (or tag 2.4.48). With the latest version, I get:

```
./yowsup-cli demos --debug -c config.txt -i /usr/src/imag1.jpg image
usage: demos [-h] [-v] [-d] [--help-config] [-l phone:b64password | -c CONFIG]
             [-M] [-y] [-e] [-s phone message] [-S contacts]
demos: error: unrecognized arguments: -i /usr/src/imag1.jpg image
```

See also #1144 and #555

**Comment by abhiroock** [comment]
@jlguardi I need to implement sending image same way as sending message from command line client for project.This is the requirment for me so i tried above way to send image by creating -i or --image.

**Comment by jlguardi** [comment]
@abhiroock  but bug seems to be due this option. Attach sample code.

Anyway, look at yowsup-cli + 278 where is passed arguments to sendclient. Check if you have correctly set key and if you have correctly defined your new param. i.e:
```
sendOpts.add_argument('-i', '--image', action="store", help = "Send image to specified phone number, "
                                                                     "wait for server receipt and exit",
                              metavar=("phone", "image_path"), nargs = 2)
```

**Comment by abhiroock** [comment]
@jlguardi  Thanks a lot

**Comment by ShopriteDevelopment** [comment]
Hi, I am new to Python, as I normally work in Java. Inside  yowsup/demos/cli.cli.py  I want to use methods from  yowsup/demos/cli/layer.py    such as message_broadcast, image_send. 

I have thought that if I use
from yowsup.demos.cli     import * I would be able to access the functions.

x = YowsupCliLayer()

then I can use 
x.image_send(number, path, caption)

Then I can direct the command line to the code to call x.image_send by adding the method name into the command line call to ./yowsup-cli 

Please could someone let me know if this is the right pathway to take for extending yowsup-cli

**Comment by abhiroock** [comment]
@ShopriteDevelopment click on #555 you will get an idea how to use in command lineclient

**Comment by ShopriteDevelopment** [comment]
@abhiroock Thank you for the help. It is greatly appreciated.
