### ISSUE TITLE
Issue running yowsup

### ISSUE THREAD

**Issue by mabbashm110** [tgalal/yowsup#1346]
Could you pls tell me how to fix this, dont know python very well... 

Error message
Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 158, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup-cli", line 167, in handleRequestCode
    from yowsup.registration import WACodeRequest
  File "C:\yowsup\yowsup\registration\__init__.py", line 1, in <module>
    from .coderequest import WACodeRequest
  File "C:\yowsup\yowsup\registration\coderequest.py", line 4, in <module>
    from yowsup.common.tools import StorageTools, WATools
  File "C:\yowsup\yowsup\common\tools.py", line 2, in <module>
    from dateutil import tz
  File "C:\Python34\lib\site-packages\python_dateutil-2.5.0-py3.4.egg\dateutil\t
z\__init__.py", line 1, in <module>
  File "C:\Python34\lib\site-packages\python_dateutil-2.5.0-py3.4.egg\dateutil\t
z\tz.py", line 16, in <module>
ImportError: No module named 'six'

**Comment by jlguardi** [comment]
This is a problem with your installation of python but not about yowsup.

You need to install six module for python. Some google results
  http://stackoverflow.com/questions/21990581/how-to-install-the-six-module-in-python2-7 
  https://pip.pypa.io/en/latest/quickstart/

In summary:
```
pip install six
```

**Comment by mabbashm110** [comment]
I am using Windows, how do i do it?

One other thing,Yowsup has the channel registration error "old version" fixed?

**Comment by jlguardi** [comment]
Old version is repoted in #1335 and fixed (read it). 

About pip and python, googling you will get: http://stackoverflow.com/questions/4750806/how-do-i-install-pip-on-windows

**Comment by mabbashm110** [comment]
Thanks fixed
