### ISSUE TITLE
Error in Yowsup

### ISSUE THREAD

**Issue by mabbashm110** [tgalal/yowsup#1351]
It worked for 2 sims after that it started giving me this error

Does it need an IP change or something? What went wrong?

Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 158, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup-cli", line 167, in handleRequestCode
    from yowsup.registration import WACodeRequest
  File "C:\yow\yowsup\registration\__init__.py", line 1, in <module>
    from .coderequest import WACodeRequest
  File "C:\yow\yowsup\registration\coderequest.py", line 4, in <module>
    from yowsup.common.tools import StorageTools, WATools
  File "C:\yow\yowsup\common\tools.py", line 2, in <module>
    from dateutil import tz
ImportError: No module named dateutil

**Comment by jlguardi** [comment]
The bug is related with your python installation. Missing dateutil module.

**Comment by mabbashm110** [comment]
Thanks sorted using this command line
pip install python-dateutil
