### ISSUE TITLE
I am unable to send anything

### ISSUE THREAD

**Issue by JuanLombana** [tgalal/yowsup#1354]
Hi, firts thanks in advance for your help.

I am trying to send a message with yowsup-cli, i have tried ALL parameters, but always recibe the following exception:

python yowsup-cli demos -c config.txt -y --debug
Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 227, in process
    self.startCmdline()
  File "yowsup-cli", line 254, in startCmdline
    stack = cli.YowsupCliStack(credentials, not self.args["unmoxie"])
  File "D:\SourceCodeGitHub\yowsup\yowsup\demos\cli\stack.py", line 13, in __init__
    .pushDefaultLayers(encryptionEnabled)\
  File "D:\SourceCodeGitHub\yowsup\yowsup\stacks\yowstack.py", line 51, in pushDefaultLayers
    defaultLayers = YowStackBuilder.getDefaultLayers(axolotl)
  File "D:\SourceCodeGitHub\yowsup\yowsup\stacks\yowstack.py", line 73, in getDefaultLayers
    from yowsup.layers.axolotl import YowAxolotlLayer
  File "D:\SourceCodeGitHub\yowsup\yowsup\layers\axolotl\__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "D:\SourceCodeGitHub\yowsup\yowsup\layers\axolotl\layer.py", line 3, in <module>
    from axolotl.util.keyhelper import KeyHelper
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\python_axolotl-0.1.7-py3.5.egg\axolotl\util\keyhelper.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\python_axolotl-0.1.7-py3.5.egg\axolotl\identitykeypair.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\python_axolotl-0.1.7-py3.5.egg\axolotl\state\storageprotos.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\protobuf-2.6.1-py3.5.egg\google\protobuf\reflection.py", line 68, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1136, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1093, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 530, in spec_from_file_location
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\protobuf-2.6.1-py3.5.egg\google\protobuf\internal\python_message.py", line 848
    except struct.error, e:
                       ^
SyntaxError: invalid syntax

What am i doing wrong?

**Comment by jlguardi** [comment]
Seems an error with protobuf and your python verison. Try with python 2.6+.

I've found this:
https://github.com/google/protobuf/issues/882
http://stackoverflow.com/questions/29389754/how-do-we-use-python-generated-protobuf-codes-in-to-python-code
