### ISSUE TITLE
Cannot send to Group (it start just in a couple hour ago)

### ISSUE THREAD

**Issue by nurdan** [tgalal/yowsup#1359]
My yowsup failed to send message to a group, it start just in a couple hour ago.

$yowsup-cli demos -c conf.txt -s 628179XXXX-1392347XXX@g.us test

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 696, in run_script

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1621, in run_script

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 280, in startSendClient

  File "build/bdist.linux-x86_64/egg/yowsup/demos/sendclient/stack.py", line 54, in start
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 195, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 86, in handle_read
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 94, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 115, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 136, in processIqRegistry

  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 175, in <lambda>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 339, in onGetKeysResult
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 87, in fromProtocolTreeNode
AttributeError: 'NoneType' object has no attribute 'getChild'

**Comment by jlguardi** [comment]
@nurdan Change env to S40 to disable group encryption which is not supported by the API yet.

Replace CURRENT_ENV = AndroidYowsupEnv() byCURRENT_ENV = S40YowsupEnv() in yowsup/env/__init__.py

**Comment by nurdan** [comment]
It is already set on my yowsup/env/_init_.py  but still on problem :

from .env_android import AndroidYowsupEnv
from .env_s40 import S40YowsupEnv

CURRENT_ENV = S40YowsupEnv()

**Comment by cfenollosa** [comment]
Same here. Just downloaded @jlguardi fork with the fixed `__init__.py` but the code still crashes when trying to send to a group

```
Traceback (most recent call last):
  File "run/stack.py", line 25, in <module>
    stack.loop()
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 195, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 86, in handle_read
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 94, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper

  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 115, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 136, in processIqRegistry

  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 175, in <lambda>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 339, in onGetKeysResult
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 87, in fromProtocolTreeNode
AttributeError: 'NoneType' object has no attribute 'getChild'
```

**Comment by cfenollosa** [comment]
I discovered that when the stack is created with `axolotl=False`, the code can send messages to groups, but not to individuals. If `axolotl=True` it is the other way around: it can send private messages but not to groups.

Can anybody think of a temporal workaround to this? I'm not keen on yowsup's internals

**Comment by WilliamSouza** [comment]
I have the same problem.

**Comment by nauramutiara** [comment]
same problem. private message too.

**Comment by xiraina** [comment]
Same problem.  Group messages not working.

**Comment by jroman** [comment]
Same problem here with the version of Dic 14.

**Comment by jegue** [comment]
same problem. private message too.

**Comment by jlguardi** [comment]
Have any one tried to register again (with the new Id) with #1335 but used S40 env after that?

**Comment by alafanechere** [comment]
I encounter the seame issue. I re-register with the Android env as stated previously by @jlguardi in issue #1335. Registration works fine. But the problem remains :
````
File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 87, in fromProtocolTreeNode
    preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
AttributeError: 'NoneType' object has no attribute 'getChild'
```

**Comment by yairh** [comment]
As cfenollosa commented:
Removing Axolotl (either with `axolotl=False `or removing the `YowAxolotlLayer `layer) does work for sending group messages, but not private messages :(

**Comment by dr1ka** [comment]
Same problem. Group messages not working. =(

**Comment by WilliamSouza** [comment]
> 
As cfenollosa commented:
Removing Axolotl (either with axolotl=Falseor removing the YowAxolotlLayerlayer) does work for sending group messages, but not private messages :(

> 
Where do I change this ?

**Comment by alafanechere** [comment]
@WilliamSouza indeed you can 'fix it'  by commenting `yowstack.py` on `getDefaultLayer`:
```
def getDefaultLayers(axolotl = False, groups = True, media = True, privacy = True, profiles = True):
        coreLayers = YowStackBuilder.getCoreLayers()
        protocolLayers = YowStackBuilder.getProtocolLayers(groups = groups, media=media, privacy=privacy, profiles=profiles)

        allLayers = coreLayers
        #if axolotl:
            #from yowsup.layers.axolotl import YowAxolotlLayer
            #allLayers += (YowAxolotlLayer,)

        allLayers += (YowParallelLayer(protocolLayers),)

        return allLayers 
```

But this disables private messages...

**Comment by deounix** [comment]
@alafanechere What is the name of file should I edit it? I can't send msg via YowSup to group. Did u face this problem too ? or u fix it ? thnx.

**Comment by alafanechere** [comment]
This is not a proper fix but allow group sending. I edited `yowstack.py`. Please read my last answer

**Comment by dr1ka** [comment]
@alafanechere did not work. error persists =(

**Comment by jhonnyvey** [comment]
@alafanechere Tried too and this not work :(

**Comment by zorzevey** [comment]
Same problem here. Tried these but not working.

**Comment by neck-olodum** [comment]
Same here! Pls help! =/

**Comment by pablosouza10** [comment]
I comment the 3 lines below in the file yowstack.py, but not work to send to group,
 anything else?

             #if axolotl:
            #from yowsup.layers.axolotl import YowAxolotlLayer
            #allLayers += (YowAxolotlLayer,)

**Comment by CARLOSCAROSA** [comment]
Hourly you can use the -M option in the message send command , disabling encryption.

**Comment by pablosouza10** [comment]
@CARLOSCAROSA, Tks -M works!!! :+1:

**Comment by jhonnyvey** [comment]
@CARLOSCAROSA Works fine! Tks! :+1:

**Comment by WilliamSouza** [comment]
-M Works!!!!! Tks!

**Comment by LandRover** [comment]
Yup, -M does the trick!

**Comment by neck-olodum** [comment]
TKS @CARLOSCAROSA :raised_hands:

**Comment by jlguardi** [comment]
I've made a PR #1361 to disable group messages encryption (due to it's not supported yet) but encryption is enabled by default in echo/send client.

With this PR we have groups/private messages working again.

**Comment by nurdan** [comment]
Thank you so much @CARLOSCAROSA, @jlguardi n all..  
May Allah Ta'ala the almighty give you better reward.

**Comment by adirevelo** [comment]
Works for me tks  @CARLOSCAROSA

**Comment by betojsp** [comment]
-M work, thank @CARLOSCAROSA
