### ISSUE TITLE
messages to groups

### ISSUE THREAD

**Issue by ghost** [tgalal/yowsup#1373]
Hello,

When I send messages to a particular phone I have no problems, but when trying to group the following error is reported:
```
homer@monit:~# yowsup-cli demos -c /homer/.yowsup/.config -s 573xxxxxxxxx-14xxxxxxxx "test `date +'%T'`"
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    **import**('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 726, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 1491, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 280, in startSendClient

  File "build/bdist.linux-x86_64/egg/yowsup/demos/sendclient/stack.py", line 54, in start
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 195, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 86, in handle_read
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 94, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 115, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/**init**.py", line 136, in processIqRegistry
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 175, in <lambda>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 339, in onGetKeysResult
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 87, in fromProtocolTreeNode
AttributeError: 'NoneType' object has no attribute 'getChild'
```

**Comment by jlguardi** [comment]
Fixed in #1361 and #1364.

**Comment by betojsp** [comment]
thanks @jlguardi

**Comment by betojsp** [comment]
#1359 -M

**Comment by tgalal** [comment]
4dc99cfc5d396b83b4777a37ea50526e4595830c
