### ISSUE TITLE
Run ./yowsup-cli registration 

### ISSUE THREAD

**Issue by levalves** [tgalal/yowsup#1375]
Hello,

I am installing yowsup version bellow, well... this with problem, can you help?

yowsup-cli v2.0.13
Using yowsup v2.4.48

[root@zabbix-server yowsup-master]# ./yowsup-cli registration --requestcode sms --config yowsup-cli.config --debug
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.13.21 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=55&in=19981749059&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&method=sms&token=d5b9687da2400f899b95f1cf31bbffab&id=%D6%01y%8C%88%95%C4%9B%9C%1B%FE%3D%CC%C5jB%99L%08%FA
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=55&in=19981749059&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&method=sms&token=d5b9687da2400f899b95f1cf31bbffab&id=%D6%01y%8C%88%95%C4%9B%9C%1B%FE%3D%CC%C5jB%99L%08%FA
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

**Comment by jlguardi** [comment]
Read #1335

**Comment by levalves** [comment]
I read #1335, so show error bellow

[root@zabbix-server yowsup-master]# ./yowsup-cli demos -c yowsup-cli.config -s 5519992056304 "TEST"

INFO:yowsup.layers.axolotl.layer:Axolotl layer is generating keys
Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 231, in process
    self.startSendClient()
  File "./yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/zabbix/plugins/yowsup-master/yowsup/demos/sendclient/stack.py", line 54, in start
    self.stack.loop()
  File "/zabbix/plugins/yowsup-master/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib64/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib64/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/zabbix/plugins/yowsup-master/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/zabbix/plugins/yowsup-master/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/zabbix/plugins/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/zabbix/plugins/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/zabbix/plugins/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/zabbix/plugins/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/zabbix/plugins/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/zabbix/plugins/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/zabbix/plugins/yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/zabbix/plugins/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/zabbix/plugins/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/zabbix/plugins/yowsup-master/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/zabbix/plugins/yowsup-master/yowsup/layers/axolotl/layer.py", line 115, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/zabbix/plugins/yowsup-master/yowsup/layers/__init__.py", line 136, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/zabbix/plugins/yowsup-master/yowsup/layers/axolotl/layer.py", line 175, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "/zabbix/plugins/yowsup-master/yowsup/layers/axolotl/layer.py", line 354, in onGetKeysResult
    sessionBuilder.processPreKeyBundle(preKeyBundle)
  File "/usr/lib/python2.7/site-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessionbuilder.py", line 157, in processPreKeyBundle
  File "/zabbix/plugins/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 17, in getIdentityKeyPair
    return self.identityKeyStore.getIdentityKeyPair()
  File "/zabbix/plugins/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteidentitykeystore.py", line 31, in getIdentityKeyPair
    publicKey, privateKey = result
TypeError: 'NoneType' object is not iterable

**Comment by levalves** [comment]
Hello,
I using option "-M", It was sucessfully.

./yowsup-cli demos -c yowsup-cli.config **-M** -s 5519XXXXXXXXX "TEST"
INFO:yowsup.demos.sendclient.layer:Message sent

Yowsdown

**Comment by arminth** [comment]
Well, that just switches off end-to-end encryption...

**Comment by jlguardi** [comment]
Run first yowsup-cli demos -y just for generate and upload your crypto keys. Then you can run send or echo client.
