### ISSUE TITLE
Problem with yowsup-cli registration 

### ISSUE THREAD

**Issue by bryanmora** [tgalal/yowsup#1379]
Hello, 
I have this problem in the registration 

pi@raspberrypi:~/yowsup $ python yowsup-cli registration --requestcode sms --phone XXXXXXXXXXX --cc X
Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 158, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup-cli", line 174, in handleRequestCode
    method
  File "/home/pi/yowsup/yowsup/registration/coderequest.py", line 44, in **init**
    self.addParam("token", CURRENT_ENV.getToken(p_in))
  File "/home/pi/yowsup/yowsup/env/env_android.py", line 45, in getToken
    keyDecoded = bytearray(base64.b64decode(self.**class**._KEY))
  File "/usr/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

Thanks for help.

**Comment by gullyy** [comment]
I am also getting the same issue.Just to add- using a password which was already generated(by some other tool) without yowsup.

**Comment by jostidetosti** [comment]
I had the same problem, i solved it by changing my password in /home/pi/yowsup/config to something with only numbers and letters. My old password had a exclamation mark.

**Comment by paulrsilva** [comment]
same here
