### ISSUE TITLE
solucion de error de old-version

### ISSUE THREAD

**Issue by danf22** [tgalal/yowsup#1403]
El Problema fue que la actualizacion que hizo whatsapp para el _TOKEN_STRING y _VERSION   fue denegada y toca hacer una nueva con un update de la version y queda asi.

1) descargue la ultima version de yowsup
2) haga el cambio en el script en  env/env_s40.py:
_VERSION = "2.13.39"
_OS_NAME= "S40"
_OS_VERSION = "14.26"
_DEVICE_NAME = "Nokia302"
_TOKEN_STRING = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk{phone}"
_AXOLOTL = True
3) re instale la aplicacion con el comando python setup.py install  y listo.

**Comment by EiderDiaz** [comment]
hice las modificaciones pero ahora me muestra otro error " bad token" espero y me puedas ayudar @danf22 :+1: 
![12887268_10209571930603458_1107122510_o](https://cloud.githubusercontent.com/assets/17805140/14037209/d28ad240-f206-11e5-9dcc-40f8dbfc1473.jpg)

**Comment by alvelig** [comment]
@EiderDiaz cat env/env_s40.py

**Comment by danf22** [comment]
para poder hacer un registro toca hacer estos pasos

1-
cd /tmp
2
wget https://github.com/jlguardi/yowsup/archive/Android_2.12.440.zip
3
unzip Android_2.12.440.zip
3
cd yowsup-Android_2.12.440
4
./yowsup-cli registration --requestcode sms --phone 57xxxxxxxx --cc 57 --mcc 732 --mnc=123 -----"este caso para colombia Movistar"
5
"se recivira este mensaje"
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"incorrect","sms_length":6,"voice_length":6,"sms_wait":0,"voice_wait":0}

INFO:yowsup.common.http.warequest:{"status":"sent","length":6,"method":"sms","retry_after":46805,"sms_wait":46805,"voice_wait":64}

status: sent
retry_after: 46805
length: 6
method: sms
5
y ya se podra hacer el registro del numero.

![captura](https://cloud.githubusercontent.com/assets/13857489/14039812/827eeeb2-f22e-11e5-8e4e-7b75e1388f18.PNG)

**Comment by jlguardi** [comment]
Now we are using https://github.com/jlguardi/yowsup/archive/master.zip instead which includes all other fixes developed last days.

@danf22 Vamos, que está mucho más actualizado que el branch que proponías.

**Comment by yniv** [comment]
@jlguardi but does your repo support image dectryption???

**Comment by gitFabio** [comment]
@danf22 this worked for me.

thanks

**Comment by EiderDiaz** [comment]
@jlguardi yoswup-master works it  finaly woooooooooooooooooooorks 
love you broooo :heart: :heart:

**Comment by sowerkoku** [comment]
some solution for echo?

**Comment by jlguardi** [comment]
Please close this issue.
Echo is fixed in my master (probably but images/documents)

**Comment by thundergreen** [comment]
Please guys ..instead of posting 100000 times the same questions please
read the Wiki

Thorsten Fröhlich
Am 28.03.2016 21:19 schrieb "sowerkoku" <notifications@github.com>:

**Comment by sowerkoku** [comment]
@jlguardi 
I'm sorry, but I echo-client throws me error.
I'm using your master and the axolotl updated

`tc@pctc:~/jlguardi/yowsup$ ./yowsup-cli demos -c tc.config -e
Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 229, in process
    self.startEcho()
  File "./yowsup-cli", line 265, in startEcho
    stack.start()
  File "/home/tc/jlguardi/yowsup/yowsup/demos/echoclient/stack.py", line 21, in start
    self.stack.loop()
  File "/home/tc/jlguardi/yowsup/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/tc/jlguardi/yowsup/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/home/tc/jlguardi/yowsup/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/home/tc/jlguardi/yowsup/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/tc/jlguardi/yowsup/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/tc/jlguardi/yowsup/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/tc/jlguardi/yowsup/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/tc/jlguardi/yowsup/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/tc/jlguardi/yowsup/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/tc/jlguardi/yowsup/yowsup/layers/coder/layer.py", line 33, in receive
    node = self.reader.getProtocolTreeNode(data)
  File "/home/tc/jlguardi/yowsup/yowsup/layers/coder/decoder.py", line 16, in getProtocolTreeNode
    return self.nextTreeInternal(data)
  File "/home/tc/jlguardi/yowsup/yowsup/layers/coder/decoder.py", line 251, in nextTreeInternal
    nodeChildren = self.readList(read2, data)
  File "/home/tc/jlguardi/yowsup/yowsup/layers/coder/decoder.py", line 275, in readList
    listx.append(self.nextTreeInternal(data))
  File "/home/tc/jlguardi/yowsup/yowsup/layers/coder/decoder.py", line 267, in nextTreeInternal
    nodeData = "".join(map(chr, nodeData))
TypeError: an integer is required
`

**Comment by martifg** [comment]
muchas gracias amigo
