### ISSUE TITLE
ERROR:yowsup.layers.axolotl.layer

### ISSUE THREAD

**Issue by oscardb22** [tgalal/yowsup#1405]
ERROR:yowsup.layers.axolotl.layer:No session for: 57XXXXXXXXXX, 1
ERROR:yowsup.layers.axolotl.layer:No valid sessionsBad Mac!

yowsup can not receive messages sent to you, and this error appears.

**Comment by oscardb22** [comment]
ERROR:yowsup.layers.axolotl.layer:No such signedprekeyrecord!

above all this, I happened three days ago, and use the latest version of the library yowsup, including the use of Develop.

**Comment by bdbais** [comment]
remove ../.yowsup/57XXXXXXXXXX/axolotl.db  they keys / mac are stored there.

**Comment by oscardb22** [comment]
@bdbais  I already did, continue the same message.

**Comment by ronromer** [comment]
try sending any message test to 57XXXXXXXXXX .. also run a debug

**Comment by jlguardi** [comment]
Post debug logs

**Comment by sowerkoku** [comment]
`Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 231, in process
    self.startSendClient()
  File "./yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/home/tc/yowsup2/yowsup/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/home/tc/yowsup2/yowsup/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/tc/yowsup2/yowsup/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/tc/yowsup2/yowsup/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/layer.py", line 116, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 136, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/layer.py", line 176, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/layer.py", line 364, in onGetKeysResult
    sessionBuilder.processPreKeyBundle(preKeyBundle)
  File "build/bdist.linux-i686/egg/axolotl/sessionbuilder.py", line 166, in processPreKeyBundle
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 17, in getIdentityKeyPair
    return self.identityKeyStore.getIdentityKeyPair()
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/store/sqlite/liteidentitykeystore.py", line 31, in getIdentityKeyPair
    publicKey, privateKey = result
`

**Comment by sowerkoku** [comment]
INFO:yowsup.layers.axolotl.layer:Axolotl layer is generating keys
Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 231, in process
    self.startSendClient()
  File "./yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/home/tc/yowsup2/yowsup/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/home/tc/yowsup2/yowsup/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/tc/yowsup2/yowsup/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/tc/yowsup2/yowsup/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/layer.py", line 116, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 136, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/layer.py", line 176, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/layer.py", line 364, in onGetKeysResult
    sessionBuilder.processPreKeyBundle(preKeyBundle)
  File "build/bdist.linux-i686/egg/axolotl/sessionbuilder.py", line 166, in processPreKeyBundle
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 17, in getIdentityKeyPair
    return self.identityKeyStore.getIdentityKeyPair()
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/store/sqlite/liteidentitykeystore.py", line 31, in getIdentityKeyPair
    publicKey, privateKey = result
TypeError: 'NoneType' object is not iterable

**Comment by sowerkoku** [comment]
`INFO:yowsup.layers.axolotl.layer:Axolotl layer is generating keys
Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 231, in process
    self.startSendClient()
  File "./yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/home/tc/yowsup2/yowsup/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/home/tc/yowsup2/yowsup/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/tc/yowsup2/yowsup/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/tc/yowsup2/yowsup/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/layer.py", line 116, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/home/tc/yowsup2/yowsup/yowsup/layers/__init__.py", line 136, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/layer.py", line 176, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/layer.py", line 364, in onGetKeysResult
    sessionBuilder.processPreKeyBundle(preKeyBundle)
  File "build/bdist.linux-i686/egg/axolotl/sessionbuilder.py", line 166, in processPreKeyBundle
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 17, in getIdentityKeyPair
    return self.identityKeyStore.getIdentityKeyPair()
  File "/home/tc/yowsup2/yowsup/yowsup/layers/axolotl/store/sqlite/liteidentitykeystore.py", line 31, in getIdentityKeyPair
    publicKey, privateKey = result
TypeError: 'NoneType' object is not iterable
`

**Comment by gbarba** [comment]
this issue is duplicated ( #1130 ), please concentrate all scenarios and conversations in a single issue

**Comment by tgalal** [comment]
This is [not a problem](https://github.com/tgalal/yowsup/issues/1436#issuecomment-214690516)
