### ISSUE TITLE
Message encoding issues

### ISSUE THREAD

**Issue by rokha** [tgalal/yowsup#1407]
Because of issue #1400 as it appeared suddenly my running system broke. After that I tried to register a new test number and got stuck here. After a daylong search and fixes, one of the problem seems to be coming from two versions of messages being supported right now. One of them recieves body and other recieves enc in the message xml (message_text.py inside fromProtocolTreeNode).

However inside the message_encrypted.py in the same function, it is getting stuck in trying to decode to string. If the data is sent directly then it breaks at assert in setEncProps (in the same file). This happens because it recieves encoding type as `skmsg` .

Issue #1401 also has a comment by cfenollosa stating 

> What's weird is that I have other bots running from other numbers and they still work (group and private, text and images). My theory is that since the protocol change, old axolotl.db (i.e. generated before the change) still work, who knows until when, but newly generated files have this non-ack issue and thus the clients don't work.

So I am trying to figure out if this is the right direction or a rabbit hole. Any help is greatly appreciated.

 The trigger to this was the stacktrace below:

```
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 227, in process

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 255, in startCmdline

  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/stack.py", line 25, in start
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 187, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 86, in handle_read
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 94, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 117, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 139, in onMessage
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 224, in handleEncMessage
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 270, in handleWhisperMessage
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/protocolentities/message_encrypted.py", line 53, in fromProtocolTreeNode
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/protocolentities/message_encrypted.py", line 24, in setEncProps

AssertionError: msg
```

**Comment by payamazadi** [comment]
i'm not sure how you're getting to this code. what version of the software are you using?
@jlguardi 's master is a pretty sexy and clean branch of the original, and his encrypted-media branch fixes a lot of media.

if you look at axolotl's layer, you'll see a handleEncMessage function. there, because the type of the enc subchild is msg, it gets sent to the handleWhisperMessage, then bad things happen.

what needs to happen instead is to treat that function differently - which is what we are doing in the encrypted-media branch. 

is this helpful? if your issue is with receiving images, there is an active discussion on #1400

**Comment by payamazadi** [comment]
but basically the encrypted portion of the message needs to be decrypted. the result of the decryption is basically a bunch of binary. encoded in the binary is metadata. the metadata has a link to an encrypted file, which must be downloaded and decrypted. to decrypt it, you need to parse out a bunch of that metadata. we do this using protobuf.

**Comment by Gab0** [comment]
It tried to assert encType of encrypted message between "msg" and "pkmsg", failed because the type was "skmsg"... wtf is this? A new encryption type whatsapp is starting to use?

**Comment by payamazadi** [comment]
where is the assert you're talking about? is it in the tests, or in the code?
there is no type of skmsg. there is only msg and pkmsg 

```
def handleEncMessage(self, node):
        try:
            if node.getChild("enc")["v"] == "2" and node["from"] not in self.v2Jids:
                self.v2Jids.append(node["from"])

            if node.getChild("enc")["type"] == "pkmsg":
                self.handlePreKeyWhisperMessage(node)
            elif node.getChild("enc")["type"] == "msg" and node.getChild("enc")["mediatype"] == "image":
                self.handleWhisperMessage2(node)
```

**Comment by Gab0** [comment]
Actually it is a new encryption type, our community was aware no skmsg implementations were made. #898

**Comment by rokha** [comment]
@payamazadi the code is in layers/axolotl/protocolentities/message_encrypted.py

```
def setEncProps(self, encType, encVersion, encData):
        assert encType in "pkmsg", "msg"
        self.encType = encType
        self.encVersion = int(encVersion)
        self.encData = encData
```

I started with the media messages but then started to see these `skmsg` so I thought it might be important to mention. 

@Gab0  thanks for pointing out the `skmsg` handlers. I'll incorporate them and keep everyone posted here.

**Comment by rokha** [comment]
While trying to implement wa16 branch (although it is not approved by @tgalal) I have not been able to receive messages. 

So in an attempt to repair it, I just copied the changes relevant to skmsg handling on that branch to the working yowsup layer. This is where it got interesting. On running the bundled echo client, an android message gets replied with gibberish but iPhone(6s running OS update 9.3) gets a properly decrypted reply. Moreover, in this process bunch of notifications got accumulated. So still working to fix that first.

Still trying to figure out what is going wrong.

**Comment by jlguardi** [comment]
@rokha where are you uploading your code? I'm focused now in media (incoming is fixed but images outgoing crashes) but I think that skmsg if the current hotpoint.
Are you using python-axolotl with group support (is a brach)? I tried two weeks ago but always failed the decryption. Probably now after deeper study, I could get something. 
So, if you have some improvements, I'll start from them.

**Comment by rokha** [comment]
@jlguardi I haven't uploaded any code yet as it is not working in any way... however what I did was apply commits from here: https://github.com/tgalal/yowsup/pull/1341/commits

At first I worked with commits from d075c4b to fc76eff and the above mentioned iphone issue was happening.
Then I applied all commits from f79dbab to 6819949. It didn't work as I never got a reply while running echo client.

**Comment by jlguardi** [comment]
@rokha dont use echo client to skip forward function. Is better to send a simple text message and check xml content.

**Comment by rokha** [comment]
@jlguardi I generally use echo client for a quick response and clearing the message queue (if some mistake is made in my code). Even after reinstalling the library it is not working. 

I also tried another method where I merged tgalal's wa16 branch with your master branch of yowsup fork. I was not able to receive the messages again. Now I have a queue of messages which have not been acknowledged.

so I have three questions for you:

1. What do you mean by skip forward function, I am confused there.
2. At which points should I place print statements to find if decoding is working or not.(my hunch is that since message is not decoded correctly, no response action is taken)
3. How can I clear the queue of messages and their acks.

Thanks for all your help.

**Comment by Gab0** [comment]
@rokha Can you create a branch with this code you are working on?

**Comment by jlguardi** [comment]
@rokha echo client does something like: entity.forward(...). This function was implemented before encryption. I'm not sure about this function. So, use a simple text message but don't forward. 
2. Use logger.debug at axolotl layer before de toUpper the node should be like a unencrypted message but with an "enc" child
3. Catch exceptions in axolotl/layer.py and do something like: toLower(incomming.ack()). I don't have access now to the code but in this file you have an example when old index came.

**Comment by sowerkoku** [comment]
some solution for echo?

**Comment by rigid** [comment]
:+1:  i'm experiencing the same crash.
