### ISSUE TITLE
Getting Error while sending message

### ISSUE THREAD

**Issue by neeraj360** [tgalal/yowsup#1411]
Traceback (most recent call last):
  File "run.py", line 53, in <module>
    whatsapp_reciever(1)
  File "run.py", line 50, in whatsapp_reciever
    stack.loop() #this is the program mainloop
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 117, in receive
    self.onMessage(protocolTreeNode)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 139, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 224, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 281, in handleWhisperMessage
    self.toUpper(node)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
    self.toUpper(entity) 
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/interface/interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "/home/neeraj/yutility/layer.py", line 118, in onMessage
    self.toLower(outgoingMessageProtocolEntity)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 173, in send
    s.send(data)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 111, in send
    send(entity)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 115, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 107, in send
    self.handlePlaintextNode(node)
  File "/home/neeraj/.virtualenvs/yow/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 185, in handlePlaintextNode
    padded.extend(plaintext)
TypeError: an integer or string of size 1 is required

**Comment by jlguardi** [comment]
Are you sending an empty string?

**Comment by neeraj360** [comment]
Nopes,

On Sunday, 27 March 2016, jlguardi <notifications@github.com> wrote:

> Are you sending an empty string?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tgalal/yowsup/issues/1411#issuecomment-202095221>
>


-- 



*Regards *

*Neeraj Goel*
+91 7838872866

**Comment by drmaposa** [comment]
@jlguardi

I got the same error, it started happening when i was trying to send emoji unicode

`TypeError: an integer or string of size 1 is required`

Below is the output

`Traceback (most recent call last):
  File "run.py", line 32, in <module>
    stack.loop() #this is the program mainloop
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/axolotl/layer.py", line 118, in receive
    self.onMessage(protocolTreeNode)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/axolotl/layer.py", line 140, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/axolotl/layer.py", line 225, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/axolotl/layer.py", line 282, in handleWhisperMessage
    self.toUpper(node)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
    self.toUpper(entity)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/interface/interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/layerbot.py", line 37, in onMessage
    self.message_send(messageProtocolEntity.getFrom(), emoji.emojize('Python is :thumbs_up_sign:')+'xxx'+messageProtocolEntity.getBody())
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/layerbot.py", line 44, in message_send
    self.toLower(outgoingMessage)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/__init__.py", line 173, in send
    s.send(data)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/__init__.py", line 111, in send
    send(entity)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/__init__.py", line 115, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/axolotl/layer.py", line 108, in send
    self.handlePlaintextNode(node)
  File "/home/bot263/apps/yowsup/whatsapp/yowsup/yowsup/layers/axolotl/layer.py", line 186, in handlePlaintextNode
    padded.extend(plaintext)
TypeError: an integer or string of size 1 is required`

Any help?

**Comment by michjans** [comment]
I had the same problem a couple of days ago. The problem was that I was passing an object of type unicode into the TextMessageProtocolEntity instead of a str.
The solution I implemented was:
```
if type(message) is unicode:
  #convert unicode to str
  message = message.encode('utf-8')
entity = TextMessageProtocolEntity(message, phone)
self.toLower(entity)
```

**Comment by drmaposa** [comment]
@michjans 
Thanks it really worked. You are such a star 

:+1:

**Comment by thundergreen** [comment]
Can we please add this to the master branch?

Thorsten Fröhlich
Am 30.03.2016 18:17 schrieb "drmaposa" <notifications@github.com>:

**Comment by thundergreen** [comment]
Where exactly  did u add this code?

Thorsten Fröhlich
Am 30.03.2016 14:56 schrieb "michjans" <notifications@github.com>:

**Comment by drmaposa** [comment]
@thundergreen

`def message_send(self, number, content):
         outgoingMessage = TextMessageProtocolEntity(content.encode('utf-8'), to=self.normalizeJid(number))`

**Comment by thundergreen** [comment]
Thanks but in which file? Layer.py?

Thorsten Fröhlich
Am 30.03.2016 19:12 schrieb "drmaposa" <notifications@github.com>:

**Comment by michjans** [comment]
@thundergreen 
I did not fix this in yowsup, but in my custom layer which is on top of the stack. I use this layer to send and receive messages. It has a sendMessage method, similar like @drmaposa mentioned above.

It used to be no problem to send messages of unicode type instead of str, but since the yowsup version of the @tgalal master branch stopped working, I had to implement this fix (or workaround).
I don't know the internals of yowsup well enough to say where this should be fixed permanently

**Comment by thundergreen** [comment]
Thanks for your  reply bit as I'm more or less a newbie in python I would
just need where to out this part of to ...which file ;)

Thorsten Fröhlich
Am 31.03.2016 09:46 schrieb "michjans" <notifications@github.com>:

**Comment by drmaposa** [comment]
@thundergreen

Go to Yowsup Demos

`/yowsup/demos/echoclient/layer.py`

find a function that send messages. 

These demos should be your starting point

**Comment by thundergreen** [comment]
Thanks guys will check this

Thorsten Fröhlich
Am 31.03.2016 12:54 schrieb "drmaposa" <notifications@github.com>:

**Comment by sphaero** [comment]
Can this be closed?

**Comment by neeraj360** [comment]
yes




*Regards *

*Neeraj Goel*
+91 7838872866
