### ISSUE TITLE
error while running yowsup demo

### ISSUE THREAD

**Issue by jbhv12** [tgalal/yowsup#1412]
i get the following error message. please help.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 279, in startSendClient
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/demos/sendclient/stack.py", line 24, in __init__
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/yowsup2-2.4.48-py3.5.egg/yowsup/layers/axolotl/layer.py", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/axolotl/util/keyhelper.py", line 3, in <module>
    from ..identitykeypair import IdentityKeyPair
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/axolotl/identitykeypair.py", line 1, in <module>
    from .state.storageprotos import IdentityKeyPairStructure
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/axolotl/state/storageprotos.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/protobuf/reflection.py", line 68, in <module>
    from google.protobuf.internal import python_message
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 848
    except struct.error, e:
                       ^

**Comment by smartm13** [comment]
What was the command called in CLI?

**Comment by jbhv12** [comment]
@smartm13  Jays-MacBook-Pro:~ jbhv12$ yowsup-cli demos -s 91xxxxxxxxxx syulkjhgfdsx -c config

**Comment by jlguardi** [comment]
Try it with older pyhon version.

**Comment by Jotese** [comment]
Hi, 

I'm learning python and my opinion maybe is wrong because i do not have too much experience. I tried to teto the demo code from repository (run.py & layer.py) and i received similar error. I think this error is due protobuf library is python 2 and you have python3.5 interpreter.
Check what protobuff version have you installed. I updated protobuf to 3.0.0b2 (beta version) by pip and i think that i solved issue:
python3.4 -m pip install protobuf==3.0.0b2

After update library i doesnt get protobuf error. I get invalid padding error now and i can't solve it. I hope i could solve it...

**Comment by jbhv12** [comment]
@jlguardi @Jotese
 yes it helped.

**Comment by customdeve** [comment]
Hi i am using this script and its running fine for me but some time its getting stuck somewhere its showing me some errors frequently and the script gets closed automatically
a) In valid frame Number came after sync .
b) Sometimes its saying MySQL server gone away.

Any help will be appreciated.
