### ISSUE TITLE
Upload Image Error - Broken Pipe.

### ISSUE THREAD

**Issue by daemonserj** [tgalal/yowsup#1419]
Hello!
Uploading did as in latest cli app. Now I use @jlguardi master branch so there is no authorization problems. But "Broken pipe" error is still here , this error was in @tgalal  version too.

This is log:

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="s.whatsapp.net" id="12">
<duplicate mimetype="image/gif" filehash="LCdxkCkM/QHNPU883DUPG4DIzTvzvR4r3qOOAxbVWAk=" url="https://mmi656.whatsapp.net/d/As3b4EGRi0SY_7DB6xkF2z8g-r3kqb--MsqzLt-dlfKH.gif" height="460" width="650" type="image" size="563245">
</duplicate>
</iq>

INFO:proxylayer:Starting upload picture /picture_ny/201.gif to URL : https://mmi656.whatsapp.net/d/As3b4EGRi0SY_7DB6xkF2z8g-r3kqb--MsqzLt-dlfKH.gif

INFO:proxylayer:PROGRESS: 1
INFO:proxylayer:PROGRESS: 2
INFO:proxylayer:PROGRESS: 3
INFO:proxylayer:PROGRESS: 4
INFO:proxylayer:PROGRESS: 5
INFO:proxylayer:PROGRESS: 6
INFO:proxylayer:PROGRESS: 7
INFO:proxylayer:PROGRESS: 8
INFO:proxylayer:PROGRESS: 9
INFO:proxylayer:PROGRESS: 10
INFO:proxylayer:PROGRESS: 11
INFO:proxylayer:PROGRESS: 12
INFO:proxylayer:PROGRESS: 13
INFO:proxylayer:PROGRESS: 14
INFO:proxylayer:PROGRESS: 15
INFO:proxylayer:PROGRESS: 16

ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/protocol_media/mediauploader.py", line 98, in run
    ssl_sock.write(stream[:buf])
  File "/usr/lib/python2.7/ssl.py", line 172, in write
    return self._sslobj.write(data)
error: [Errno 32] Broken pipe

DEBUG:yowsup.layers.logger.layer:rx:
<stream:error>
<ack id="1459227793-25">
</ack>
</stream:error>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

**Comment by daemonserj** [comment]
it seems because of image upload successfuly but notification about it not sent (by error in my app). secondary upload of the same image failed with "broken pipe"
