### ISSUE TITLE
 Authentication Error: not-authorized

### ISSUE THREAD

**Issue by josep112** [tgalal/yowsup#1424]
Hello I managed to make the record, but I can not send message
/usr/src/yowsup-master/yowsup-cli demos -c /usr/src/yowsup-master/config -s "55XXXXXXXXXX" "TESTE"
Authentication Error: not-authorized

**Comment by maykel535** [comment]
Same problem... I apply this patch for register:

https://github.com/tgalal/yowsup/pull/1336/files

Debug:

Yowsup Cli client                                                                                                                                                                              
==================                                                                                                                                                                             
Type /help for available commands                                                                                                                                                              
                                                                                                                                                                                               
[offline]:/L                                                                                                                                                                                   
general: Login Failed, reason: not-authorized                                                                                                                                                  
Auth Error, reason not-authorized  



EBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer                                                                                                                                         
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer                                                                                                                                
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer                                                                                                                                           
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e13.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user=""34666777888"" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
▒�ZfΐA(l�Nq    �

HEX:18a15a66ce9041286cee8e95a04e7109c104090c
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
�X��#��s����=��
               e�㜘s�0z�*�9Z�2�W�L��Dխ
HEX:8c589c9123eeb573d3fe815008a33dc0178c0e0c65f5e39c9873bb30067a9f2a92395acd32a9570fb04cac8944d5ad
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized

Any ideas for this issue??

**Comment by relima** [comment]
@maykel535 same issue here.

**Comment by josep112** [comment]
We will only have one solution with the updating of yowsup?

**Comment by jlguardi** [comment]
Tired to answer this issue. Search for previous answers.
In summary: YES, update with jlguardi/master (is most advanced version by now) and close this issue.

**Comment by maykel535** [comment]
I have the latest version:

https://github.com/tgalal/yowsup

What do you mean with jilguardi/master? Where is the URL?

**Comment by eduardobento** [comment]
https://github.com/jlguardi/yowsup

**Comment by maykel535** [comment]
I downloaded and installed and still have the same problem ... The password is ok because register again....

**Comment by maykel535** [comment]
Full uninstall yowsup and reinstall yowsup with repo jlguardi/yowsup

Install ok but i get received this error:

root@mysql-test2:/home/maykel/yowsup-axolot# ./yowsup-cli demos --yowsup --config yowsup.config -d
Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 227, in process
    self.startCmdline()
  File "./yowsup-cli", line 249, in startCmdline
    from yowsup.demos import cli
  File "/home/maykel/yowsup-axolot/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/home/maykel/yowsup-axolot/yowsup/demos/cli/stack.py", line 2, in <module>
    from .layer import YowsupCliLayer
  File "/home/maykel/yowsup-axolot/yowsup/demos/cli/layer.py", line 2, in <module>
    from yowsup.layers.interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/home/maykel/yowsup-axolot/yowsup/layers/interface/__init__.py", line 1, in <module>
    from .interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/home/maykel/yowsup-axolot/yowsup/layers/interface/interface.py", line 7, in <module>
    from yowsup.layers.axolotl.layer import YowAxolotlLayer
  File "/home/maykel/yowsup-axolot/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/home/maykel/yowsup-axolot/yowsup/layers/axolotl/layer.py", line 27, in <module>
    from axolotl.axolotladdress import AxolotlAddress
ImportError: No module named axolotladdress


I install, uninstall, reinstall this module for python:

pip install python-axolotl

But I get same error...

**Comment by rump1992** [comment]
Use axolotl from tgalal

**Comment by maykel535** [comment]
https://github.com/tgalal/python-axolotl-curve25519

python setup install     -- installed

root@mysql-test2:/home/maykel/yowsup-axolot# ./yowsup-cli demos --yowsup --config yowsup.config -d
Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 227, in process
    self.startCmdline()
  File "./yowsup-cli", line 249, in startCmdline
    from yowsup.demos import cli
  File "/home/maykel/yowsup-axolot/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/home/maykel/yowsup-axolot/yowsup/demos/cli/stack.py", line 2, in <module>
    from .layer import YowsupCliLayer
  File "/home/maykel/yowsup-axolot/yowsup/demos/cli/layer.py", line 2, in <module>
    from yowsup.layers.interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/home/maykel/yowsup-axolot/yowsup/layers/interface/__init__.py", line 1, in <module>
    from .interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/home/maykel/yowsup-axolot/yowsup/layers/interface/interface.py", line 7, in <module>
    from yowsup.layers.axolotl.layer import YowAxolotlLayer
  File "/home/maykel/yowsup-axolot/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/home/maykel/yowsup-axolot/yowsup/layers/axolotl/layer.py", line 27, in <module>
    from axolotl.axolotladdress import AxolotlAddress
ImportError: No module named axolotladdress

**Comment by jlguardi** [comment]
Search for "No module named axolotladdress" in closed issues of jlguardi/yowsup
In sum, you need to install tgalal/python-axolotl branch develop

**Comment by olucurious** [comment]
@jlguardi thanks, it's working, I've been dealing with the same issue with the dude above for about a week, thanks for all the good works on the project.

**Comment by josep112** [comment]
I made all procedures the jlguardi but still get this error which may be missing?
/usr/src/yowsup-master/yowsup-cli demos -c /usr/src/yowsup-master/config -s "55XXXXXXXXX" "ok"
INFO:yowsup.layers.axolotl.layer:Axolotl layer is generating keys
Traceback (most recent call last):
  File "/usr/src/yowsup-master/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/usr/src/yowsup-master/yowsup-cli", line 231, in process
    self.startSendClient()
  File "/usr/src/yowsup-master/yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/usr/src/yowsup-master/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/usr/src/yowsup-master/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/src/yowsup-master/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/src/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/layer.py", line 130, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 155, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/layer.py", line 188, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/layer.py", line 628, in onGetKeysResult
    sessionBuilder.processPreKeyBundle(preKeyBundle)
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.34-py2.7.egg/axolotl/sessionbuilder.py", line 166, in processPreKeyBundle
    .setOurIdentityKey(self.identityKeyStore.getIdentityKeyPair())\
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 19, in getIdentityKeyPair
    return self.identityKeyStore.getIdentityKeyPair()
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteidentitykeystore.py", line 31, in getIdentityKeyPair
    publicKey, privateKey = result
TypeError: 'NoneType' object is not iterable

**Comment by josep112** [comment]
Thanks for the reply I've done it but still the same error

**Comment by jlguardi** [comment]
Remove axolotl.db and restart the app.

**Comment by josep112** [comment]
Hello  jlguardi 
I've done it too and continues with the same error, I am sending this command is correct?
/usr/src/yowsup-master/yowsup-cli demos -c /usr/src/yowsup-master/config -s "55XXXXXXXXX" "OK"

**Comment by tgalal** [comment]
Updating to latest  version should fix the auth problem
