### ISSUE TITLE
issues with @jlguardi's branch

### ISSUE THREAD

**Issue by abloch** [tgalal/yowsup#1426]
Hi All!

I used @jlguardi 's master branch with the below pip packages installed

```
argparse==1.2.1
protobuf==3.0.0a3
pycrypto==2.6.1
python-axolotl-curve25519==0.1
python-dateutil==2.5.2
requests==2.9.1
six==1.10.0
wsgiref==0.1.2
```
and got this error:
```
Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 227, in process
    self.startCmdline()
  File "./yowsup-cli", line 249, in startCmdline
    from yowsup.demos import cli
  File "/home/ffil/projects/yys/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/home/ffil/projects/yys/yowsup/demos/cli/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/home/ffil/projects/yys/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/home/ffil/projects/yys/yowsup/stacks/yowstack.py", line 10, in <module>
    from yowsup.layers.protocol_media              import YowMediaProtocolLayer
  File "/home/ffil/projects/yys/yowsup/layers/protocol_media/__init__.py", line 1, in <module>
    from .layer import YowMediaProtocolLayer 
  File "/home/ffil/projects/yys/yowsup/layers/protocol_media/layer.py", line 2, in <module>
    from .protocolentities import DocumentDownloadableMediaMessageProtocolEntity
  File "/home/ffil/projects/yys/yowsup/layers/protocol_media/protocolentities/__init__.py", line 2, in <module>
    from .message_media_downloadable import DownloadableMediaMessageProtocolEntity
  File "/home/ffil/projects/yys/yowsup/layers/protocol_media/protocolentities/message_media_downloadable.py", line 10, in <module>
    from axolotl.kdf.hkdfv3 import HKDFv3
```
**ImportError: No module named axolotl.kdf.hkdfv3**

**Comment by jlguardi** [comment]
Read ‎https://github.com/jlguardi/yowsup/issues/12

De: Akiva
Enviado: miércoles, 30 de marzo de 2016 15:56
Para: tgalal/yowsup
Responder a: tgalal/yowsup
CC: jlguardi
Asunto: [tgalal/yowsup] issues with @jlguardi's branch (#1426)


Hi All!

I used @jlguardi 's master branch with the below pip packages installed

```
argparse==1.2.1
protobuf==3.0.0a3
pycrypto==2.6.1
python-axolotl-curve25519==0.1
python-dateutil==2.5.2
requests==2.9.1
six==1.10.0
wsgiref==0.1.2
```
and got this error:
```
Traceback (most recent call last):
  File "./yowsup-cli", line 323, in <module>
    if not parser.process():
  File "./yowsup-cli", line 227, in process
    self.startCmdline()
  File "./yowsup-cli", line 249, in startCmdline
    from yowsup.demos import cli
  File "/home/ffil/projects/yys/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/home/ffil/projects/yys/yowsup/demos/cli/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/home/ffil/projects/yys/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/home/ffil/projects/yys/yowsup/stacks/yowstack.py", line 10, in <module>
    from yowsup.layers.protocol_media              import YowMediaProtocolLayer
  File "/home/ffil/projects/yys/yowsup/layers/protocol_media/__init__.py", line 1, in <module>
    from .layer import YowMediaProtocolLayer
  File "/home/ffil/projects/yys/yowsup/layers/protocol_media/layer.py", line 2, in <module>
    from .protocolentities import DocumentDownloadableMediaMessageProtocolEntity
  File "/home/ffil/projects/yys/yowsup/layers/protocol_media/protocolentities/__init__.py", line 2, in <module>
    from .message_media_downloadable import DownloadableMediaMessageProtocolEntity
  File "/home/ffil/projects/yys/yowsup/layers/protocol_media/protocolentities/message_media_downloadable.py", line 10, in <module>
    from axolotl.kdf.hkdfv3 import HKDFv3
```
**ImportError: No module named axolotl.kdf.hkdfv3**

---
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/tgalal/yowsup/issues/1426

**Comment by abloch** [comment]
@jlguardi, thanks for your kind and quick reply.

the issue you linked suggests removing _python-axolotl_ which is not in my installed packages
```
Cannot uninstall requirement python-axolotl, not installed
```

**Comment by abloch** [comment]
oh, sorry, my bad.
I had this package installed out of pip

closing

**Comment by jlguardi** [comment]
Of course, and then install develop branch!!!

De: Akiva
Enviado: miércoles, 30 de marzo de 2016 16:07
Para: tgalal/yowsup
Responder a: tgalal/yowsup
CC: jlguardi
Asunto: Re: [tgalal/yowsup] issues with @jlguardi's branch (#1426)


@jlguardi, thanks for your kind and quick reply.

the issue you linked suggests removing _python-axolotl_ which is not in my installed packages
```
Cannot uninstall requirement python-axolotl, not installed
```


---
