### ISSUE TITLE
enc type="skmsg" v="2"

### ISSUE THREAD

**Issue by ronromer** [tgalal/yowsup#1428]
Hi there,
Any solution for this issue? I tried so many thing without luck

ERROR:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 29661 
DEBUG:yowsup.layers.logger.layer:tx:

HEX:3308a494f0031221052d60685fa92cd9650f51d920f1d7bcec830512d6fb96b0450c7bebdb4b86d1121a2105c60df4cd7b89895046f306546da10b231840d82e2252a01a4fab82e0c5cd991d22b301330a2105d3db0490b847dd9cce0a972c350e50232e64e39cefafe21de467dc5159b7a233100018002280016f0fab8c95b30d08c9a56295c5515b0879abbe9eee5c5bdafef41b863c80792da8c8fc4a1d935c0188a36b673164fc07967348aa89d7c9a71e4fcb0cef44a8bdfb6ff8ff9a2521398c1a769126898f614b63939de004eb344a02478a346fec24271f3de47a011a610c62174438b9c16e37bdc55750e603d5fe340c089c2045ba7499fa78c588dc7d28daa0d68f0330dde701
</enc>
<enc type="skmsg" v="2">
��;Y�J�5���Ԣ��OqE�0F�҄

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 726, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1491, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 227, in process
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 255, in startCmdline
    
  File "build/bdist.linux-i686/egg/yowsup/demos/cli/stack.py", line 25, in start
  File "build/bdist.linux-i686/egg/yowsup/stacks/yowstack.py", line 187, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-i686/egg/yowsup/layers/network/layer.py", line 86, in handle_read
  File "build/bdist.linux-i686/egg/yowsup/layers/network/layer.py", line 94, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/layer.py", line 117, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/layer.py", line 139, in onMessage
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/layer.py", line 224, in handleEncMessage
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/layer.py", line 270, in handleWhisperMessage
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/protocolentities/message_encrypted.py", line 53, in fromProtocolTreeNode
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/protocolentities/message_encrypted.py", line 24, in setEncProps
AssertionError: msg

**Comment by jlguardi** [comment]
Fixed in https://github.com/jlguardi/yowsup/ master branch

**Comment by ronromer** [comment]
hi @jlguardi 
after install the new master now I have other error 

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 726, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1484, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 227, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 249, in startCmdline
    from yowsup.demos import cli
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/demos/cli/stack.py", line 2, in <module>
    from .layer import YowsupCliLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/demos/cli/layer.py", line 2, in <module>
    from yowsup.layers.interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/interface/__init__.py", line 1, in <module>
    from .interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/interface/interface.py", line 7, in <module>
    from yowsup.layers.axolotl.layer import YowAxolotlLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 27, in <module>
    from axolotl.axolotladdress import AxolotlAddress
ImportError: No module named axolotladdress

**Comment by jlguardi** [comment]
@ronromer Read close issues in my repo.

**Comment by ronromer** [comment]
thanks @jlguardi solved reading close issues :)

Now i have a new one, looking information ..

Exception: Unsupported/unrecognized mimetype: audio/mp4 

do I need to open a new issue?

Regards,
Rony

**Comment by jlguardi** [comment]
@ronromer yes, open a new issue but check before that you are using head master and post logs.
