### ISSUE TITLE
Exception: Unsupported/unrecognized mimetype: audio/mp4 using demo client

### ISSUE THREAD

**Issue by ronromer** [tgalal/yowsup#1433]
Hi there,
I received this error after received a audio message in a group for demo client and I'm unable to start again demos -y

DEBUG:yowsup.layers.logger.layer:rx:
<media mimetype="audio/mp4" filehash="Y/wRcqV2KnwJ0ZtkWrIgiB4MFM/WyASbNHmgEZAri/o=" encoding="raw" url="https://mme6.whatsapp.net/d/0wTUR6zvkMc9a29YO9pJsVb6Ynw/AotlCzayzxWb3YCC18jxlki_-qTN_QoBgTCBz94GLeL_.m4a" abitrate="32" seconds="210" asampfmt="flt" file="AotlCzayzxWb3YCC18jxlki_-qTN_QoBgTCBz94GLeL_.m4a" duration="211" asampfreq="22050" acodec="aac" type="audio" size="863140">
</media>
</message>

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 726, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1484, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 227, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 255, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/demos/cli/stack.py", line 27, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 132, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/axolotl/layer.py", line 156, in onMessage
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 188, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 124, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/protocol_media/layer.py", line 47, in recvMessageStanza
    self.toUpper(entity)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/interface/interface.py", line 78, in receive
    self.entity_callbacks[entityType](entity)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/demos/cli/layer.py", line 517, in onMessage
    messageOut = self.getMediaMessageBody(message)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/demos/cli/layer.py", line 543, in getMediaMessageBody
    return self.getDownloadableMediaMessageBody(message)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/demos/cli/layer.py", line 548, in getDownloadableMediaMessageBody
    filename = "%s/%s%s"%(tempfile.gettempdir(),message.getId(),message.getExtension())
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/layers/protocol_media/protocolentities/message_media_downloadable.py", line 75, in getExtension
    return MimeTools.getExtension(self.mimeType)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/yowsup/common/tools.py", line 198, in getExtension
    raise Exception("Unsupported/unrecognized mimetype: "+mimetype);
Exception: Unsupported/unrecognized mimetype: audio/mp4

any idea?

Regards,

**Comment by jlguardi** [comment]
It is supposed that yowsup looks for file extension based in mimetype. For that, it uses system defined mimetypes (I've experienced problems with some kind of audio not defined in my system) and since today in tgalal/master and some days ago in jlguardi/master, looks in a file of the project with all supported mimetypes. 
I see that audio/mp4 is defined in this file so, if you are running updated code, you should no have this issue. Please, update your code, try again and feedback us.

**Comment by thundergreen** [comment]
Just got an issue with sending pic. In fact  I use httpupload and there's
only a link send . my pics won't be sent at all and randomly I receive pics
and sometimes

https://mmi285.whatsapp.net/d/923n03Spi2DT9Z8YBjDcdVb9ghs/AjvQ1el4WazFHnrY_6EAHwJlLwrupVszSivQ1st0tROF.enc

Thorsten Fröhlich
Am 31.03.2016 21:57 schrieb "jlguardi" <notifications@github.com>:

**Comment by ronromer** [comment]
hi @jlguardi yes using the last code https://github.com/jlguardi/yowsup/ 
I download it minutes ago.

**Comment by ronromer** [comment]
Hi team,
Not sure if this workaround is the best, but work for me

edit /usr/lib/python2.7/mimetypes.py
include the line: '.mp4'    : 'audio/mp4',
reinstall phyton

after that yowsup cli worked, but with a new error now with acc/audio
i repeted it with
'.aac'    : 'audio/aac',

And now yowsup demos -y is working ... is it was just luck?

Regards,
Rony
