### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getChild'

### ISSUE THREAD

**Issue by michjans** [tgalal/yowsup#1434]
I have been searching through the issues, but didn't find a similar stack trace, so I'm creating a new one. 
I've had this problem before, but didn't report it earlier, because a lot of changes have been made in the last couple of days, so I was hoping this problem would be fixed, too.

I just installed the latest yowsup version v2.4.98 from the master branch, including the latest version of python-axolotl v0.1.34

My server starts fine and I am able to send, receive, broadcast messages, without a problem, but at some point, just after broadcasting a message, the server crashes with the following stacktrace:

```
Traceback (most recent call last):
  File "mywhatsapp.py", line 127, in <module>
    stack.loop() #this is the program mainloop
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/axolotl/layer.py", line 122, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/__init__.py", line 155, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/axolotl/layer.py", line 182, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/axolotl/layer.py", line 357, in onGetKeysResult
    entity = ResultGetKeysIqProtocolEntity.fromProtocolTreeNode(resultNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.98-py2.7.egg/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 88, in fromProtocolTreeNode
    preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
AttributeError: 'NoneType' object has no attribute 'getChild'
```

These are the last messages that I see coming in in the log file, just before the crash:
```
2016-03-31 16:59:37,912 DEBUG layer.py:13: rx:
<ack type="read" from="xxxxxxxxxxx@s.whatsapp.net" class="receipt" id="A625E052D36F8C0C0ACA01C92E0EFB">
</ack>

2016-03-31 16:59:38,432 DEBUG layer.py:13: rx:
<iq type="result" from="s.whatsapp.net" id="66">
<list>
<user jid="xxxxxxxxxxxxx@broadcast">
<registration>
g<95>$3
HEX:67952433
</registration>
<type>
^E
HEX:05
</type>
<identity>
<BE>~^^F<<EA>^DZI<94>P<F8><8A><F8><<D3><C9><C4><F6>uwv<D7>jGs<BE><CE><D2><C3><95>>
HEX:be7e1e463cea045a499450f88af83cd3c9c4f6757776d76a4773beced2c3953e
</identity>
<skey>
<id>
<CE><89>M
HEX:ce894d
</id>
<value>
#<DE>Z<DE>Y^Z`<DA>^CY<9B>^Yr<E6><FD><D6>&_AQ<BD><FB>u<D0><AC>*ajW<C0>x^D
HEX:23de5ade591a60da03599b1972e6fdd6265f4151bdfb75d0ac2a616a57c07804
</value>
<signature>
<CC>I^^<E5><AF>A<ED>4^F<BD><,<D1>t<B3><C1>^VXZ{<B0>$V<F1><A9>;<E9><A7><A6><84>}[<CD>'<E6>q<9B><F9>N7C&q<D2><9A><CA><AF><B5>^]u^V^T<B2><D3><C8>R<81>^]X<FC>
<D4>^G<85>
HEX:cc491ee5af41ed3406bd3c2cd174b3c116585a7bb02456f1a93be9a7a6847d5bcd27e6719bf94e37432671d29acaafb51d751614b2d3c852811d58fc0ad40785
</signature>
</skey>
</user>
</list>
</iq>

2016-03-31 16:59:39,623 DEBUG layer.py:54: ping queue size: 1
2016-03-31 16:59:39,625 DEBUG layer.py:8: tx:
<iq xmlns="w:p" type="get" id="67">
</iq>

2016-03-31 17:00:29,687 DEBUG layer.py:54: ping queue size: 2
2016-03-31 17:00:29,689 DEBUG layer.py:70: stopping ping thread
2016-03-31 17:00:29,692 DEBUG layer.py:74: Disconnected, reason: Ping Timeout
```

This is my yowsup stack:
```
receiverLayer = MyReceiverLayer()
layers = (
            receiverLayer,
            YowParallelLayer([YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer, YowIqProtocolLayer, YowProfilesProtocolLayer]),
            YowAxolotlLayer
        ) + YOWSUP_CORE_LAYERS

stack = YowStack(layers)
stack.setCredentials(CREDENTIALS)         #setting credentials
stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))   #sending the connect signal
stack.loop() #this is the program mainloop
```

Could this be a bug, or is there a possibility I'm doing something wrong in my code?

**Comment by rigid** [comment]
i have the same problem :+1:

**Comment by michjans** [comment]
I forgot to mention that my code is manually patched with tgalal/yowsup/pull/1390 because without that patch the incoming messages contain garbage.

(so the line numbers in the stack trace from my first message should match the code from tgalal/yowsup master branch v2.4.102 with tgalal/yowsup/pull/1390 merged into it)

**Comment by rigid** [comment]
i don't have that patch applied (and incoming messages are still garbled)

**Comment by michjans** [comment]
I have installed yowsup from the @jlguardi yowsup/master branch this morning, without any patches and started my server with that version. It has been running for 4 hours now, without crashing and everything seems to be working as expected.
I think that this issue (and the garbled message issue) has been fixed in the @jlguardi repo, but not been merged back by @tgalal yet.

**Comment by rigid** [comment]
i just upgraded python-axolotl and now the issue seems to be gone. But there's a different crash now. I'll open a new issue for it, from my point - this issue can be closed.

**Comment by michjans** [comment]
Because this issue is already fixed on the  @jlguardi yowsup/master branch, I'm closing the issue
