### ISSUE TITLE
NameError: global name 'YowsupEnv' is not defined

### ISSUE THREAD

**Issue by jroman** [tgalal/yowsup#1435]
Hi,
just git-pulled and, on starting demo, I see this uncatched exception:

  ```
File "./yowsup/env/env.py", line 10, in __init__
    YowsupEnv.registerEnv(cls)
NameError: global name 'YowsupEnv' is not defined
```

Is it just me?

Cheers!

**Comment by sisoftrg** [comment]
Have the same problem on Python 2.7.3 (from Debian 7):

```py
Traceback (most recent call last):
  File "/home/skype/whatsapper.py", line 10, in <module>
    from yowsup.layers.interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/interface/__init__.py", line 1, in <module>
    from .interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/interface/interface.py", line 2, in <module>
    from yowsup.layers.protocol_iq.protocolentities import IqProtocolEntity
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_iq/__init__.py", line 1, in <module>
    from .layer import YowIqProtocolLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_iq/layer.py", line 6, in <module>
    from yowsup.layers.network import YowNetworkLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/__init__.py", line 1, in <module>
    from .layer import YowNetworkLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 2, in <module>
    from yowsup.common.http.httpproxy import HttpProxy
  File "/usr/local/lib/python2.7/dist-packages/yowsup/common/http/__init__.py", line 2, in <module>
    from .warequest import WARequest
  File "/usr/local/lib/python2.7/dist-packages/yowsup/common/http/warequest.py", line 4, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup/env/env.py", line 13, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 353, in with_metaclass
    return meta("NewBase", (base,), {})
  File "/usr/local/lib/python2.7/dist-packages/yowsup/env/env.py", line 10, in __init__
    YowsupEnv.registerEnv(cls)
NameError: global name 'YowsupEnv' is not defined
``

**Comment by jroman** [comment]
Circular reference in class declaration?

**Comment by Lijo050** [comment]
Just upgrade yowsup2 by `sudo pip install yowsup2 --upgrade`

**Comment by tgalal** [comment]
upgrade as @Lijo050 described and confirm please

**Comment by jroman** [comment]
Any simple explanation for this? Any python conflict?

I am running on the git downloaded code, no pip install, and would like to happily continue like that.

Thanks!

**Comment by nicshackle** [comment]
Similair problem. I've updated as mentioned above. CLI works, but I can't run my own yowsup script. See below traceback (ubuntu 14.04):

`thingking@Hercules:~/dev$ sudo python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from layer import EchoLayer
  File "/home/thingking/dev/layer.py", line 1, in <module>
    from yowsup.layers.interface                           import YowInterfaceLayer, ProtocolEntityCallback
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/layers/interface/__init__.py", line 1, in <module>
    from .interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/layers/interface/interface.py", line 2, in <module>
    from yowsup.layers.protocol_iq.protocolentities import IqProtocolEntity
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/layers/protocol_iq/__init__.py", line 1, in <module>
    from .layer import YowIqProtocolLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/layers/protocol_iq/layer.py", line 6, in <module>
    from yowsup.layers.network import YowNetworkLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/layers/network/__init__.py", line 1, in <module>
    from .layer import YowNetworkLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/layers/network/layer.py", line 2, in <module>
    from yowsup.common.http.httpproxy import HttpProxy
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/common/http/__init__.py", line 2, in <module>
    from .warequest import WARequest
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/common/http/warequest.py", line 4, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/env/env.py", line 13, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/env/env.py", line 10, in __init__
    YowsupEnv.registerEnv(cls)
NameError: global name 'YowsupEnv' is not defined`

**Comment by jroman** [comment]
I am not really sure, I played a lot,... but I think this solved the issue:

`sudo pip install six --upgrade`

Anyway, no messages are received after the git pull :(

**Comment by beereshg** [comment]
Even after upgrading "six" package, the issue persists

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup/env/env.py", line 13, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/lib/python2.7/dist-packages/yowsup/env/env.py", line 10, in __init__
    YowsupEnv.registerEnv(cls)
NameError: global name 'YowsupEnv' is not defined

**Comment by ayeteng** [comment]
I got the same issue. Just pull from pip.
Still persist with upgrading six package.

NUC:~ teng$ yowsup-cli
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/Library/Python/2.7/site-packages/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/Library/Python/2.7/site-packages/yowsup/env/env.py", line 13, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py", line 566, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Library/Python/2.7/site-packages/yowsup/env/env.py", line 10, in __init__
    YowsupEnv.registerEnv(cls)
NameError: global name 'YowsupEnv' is not defined

**Comment by andresakata** [comment]
I got the same issue.

**Comment by nicshackle** [comment]
Also solved using Python 3.5, thanks @andresakata 

Would be curious as to a solution for python 2.7.

**Comment by tgalal** [comment]
yowsup at the moment would use the globally installed package, even if you are running it from a local check out. So either update your global yowsup installation, or use a virtualenv, at least until this behaviour changes in yowsup

**Comment by maykel535** [comment]
With python 2.7 in ubuntu 14.04 LTS:

# python2.7 yowsup-cli demos --yowsup --config /usr/local/nagios/yowsup/yowsup.config -d

Traceback (most recent call last):
  File "yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/local/nagios/yowsup/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/usr/local/nagios/yowsup/yowsup/env/env.py", line 13, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/nagios/yowsup/yowsup/env/env.py", line 10, in __init__
    YowsupEnv.registerEnv(cls)
NameError: global name 'YowsupEnv' is not defined

With python 3.4:

# python3.4 yowsup-cli demos --yowsup --config /usr/local/nagios/yowsup/yowsup.config -d
Traceback (most recent call last):
  File "yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/local/nagios/yowsup/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/usr/local/nagios/yowsup/yowsup/env/env.py", line 3, in <module>
    from six import with_metaclass
ImportError: No module named 'six'


I have updated module six python:

apt-get install python3-six

And now:

# python3.4 yowsup-cli demos --yowsup --config yowsup-cli.config -d
Traceback (most recent call last):
  File "yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/home/maykel/yowsup-master/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/home/maykel/yowsup-master/yowsup/env/env.py", line 13, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python3/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/home/maykel/yowsup-master/yowsup/env/env.py", line 10, in __init__
    YowsupEnv.registerEnv(cls)
NameError: name 'YowsupEnv' is not defined


To do the whole installation with Python 3? You need python 3.5 exclusively to work ...
I took more than two weeks without being able to run yowsup between one thing and another ...

Thanks for all.

**Comment by maykel535** [comment]
With python 3.5 the problem persist:

user@server# python3.5 yowsup-cli demos --yowsup --config yowsup-cli.config -d
Traceback (most recent call last):
  File "yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/home/maykel/yowsup-master/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/home/maykel/yowsup-master/yowsup/env/env.py", line 13, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python3/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/home/maykel/yowsup-master/yowsup/env/env.py", line 10, in __init__
    YowsupEnv.registerEnv(cls)
NameError: name 'YowsupEnv' is not defined

**Comment by shacharlovett** [comment]
Same problem here. Upgraded to python 3.5, reinstalled everything.

**Comment by tgalal** [comment]
@shacharlovett no you didn't. Here is my comment again for reference

> yowsup at the moment would use the globally installed package, even if you are running it from a local check out. So either update your global yowsup installation, or use a virtualenv, at least until this behaviour changes in yowsup
