### ISSUE TITLE
No module named yowsup error

### ISSUE THREAD

**Issue by kadnan** [tgalal/yowsup#1443]
I am keep getting this error despite of it's already installed. Check below:

```
MacBook:examples User$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from whatsapp import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/whatsapp.py", line 5, in <module>
    from yowsup import env
ImportError: No module named yowsup
>>> quit()
MacBook:examples User$ sudo pip install yowsup
Password:
The directory '/Users/User/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/User/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): yowsup in /Library/Python/2.7/site-packages
```

**Comment by janboll** [comment]
You have to install yowsup2

**Comment by kadnan** [comment]
Already installed mate; check below:

Same error. 

PS: Do I have to restart my system?

```
Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0.b2 in /Library/Python/2.7/site-packages (from python-axolotl>=0.1.7->yowsup2)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf>=3.0.0.b2->python-axolotl>=0.1.7->yowsup2)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9 in /Library/Python/2.7/site-packages (from protobuf>=3.0.0.b2->python-axolotl>=0.1.7->yowsup2)
MacBook:php-protobuf adnan$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yowsup
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named yowsup
```

**Comment by kadnan** [comment]
@tgalal can you please help?

**Comment by kadnan** [comment]
Turned out that installation via `pip` had issues. I installed via `easy_install` then it worked
