### ISSUE TITLE
Error within yowsup-cli echo

### ISSUE THREAD

**Issue by copymaster** [tgalal/yowsup#1445]
Hello,

after some messing around during the last days I decided to start with a fresh working version of yowsup. So I cloned the Sourcecode from GitHub and installed with no errors.
But after starting the echo app to test things out i got the following error
(Note, that the Message I sent was only "Test" without the newlines. At a sooner try I got something like Echoing "Test~~~~~~~"...)

I Would love to receive some help where to look for the error

pi@raspberrypi ~ $ yowsup-cli demos -e -c yowsup.config 
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Echoing Test

```
         to 49XXXXXXXXXX
```

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4.102', 'yowsup-cli')
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1236, in run_script
    exec(compile(open(script_filename).read(), script_filename, 'exec'), namespace, namespace)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/EGG-INFO/scripts/yowsup-cli", line 270, in process
    self.startEcho()
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/EGG-INFO/scripts/yowsup-cli", line 308, in startEcho
    stack.start()
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/demos/echoclient/stack.py", line 21, in start
    self.stack.loop()
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib/python3.2/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.2/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python3.2/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.2/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.2/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/**init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/axolotl/layer.py", line 124, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/axolotl/layer.py", line 146, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/axolotl/layer.py", line 231, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/axolotl/layer.py", line 288, in handleWhisperMessage
    self.toUpper(node)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/__init**.py", line 188, in receive
    s.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/**init**.py", line 124, in receive
    recv(node)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
    self.toUpper(entity) 
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/**init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/interface/interface.py", line 100, in receive
    self.entity_callbacks[entityType](entity)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/demos/echoclient/layer.py", line 13, in onMessage
    self.toLower(messageProtocolEntity.forward(messageProtocolEntity.getFrom()))
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/__init**.py", line 79, in toLower
    self.**lower.send(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/__init**.py", line 192, in send
    s.send(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/**init**.py", line 130, in send
    send(entity)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/**init**.py", line 134, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/**init**.py", line 79, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/axolotl/layer.py", line 114, in send
    self.handlePlaintextNode(node)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.4.102-py3.2.egg/yowsup/layers/axolotl/layer.py", line 192, in handlePlaintextNode
    padded.extend(plaintext)
TypeError: an integer is required

**Comment by andresakata** [comment]
I got exactly same issue.

**Comment by copymaster** [comment]
I got rid of the newlines/unwanted characters by using 
[this file from jlguardi](https://github.com/jlguardi/yowsup/blob/956626e77fc4aa777da65f57978a27b0518a8410/yowsup/layers/axolotl/layer.py)
but the
**TypeError: an integer is required **
stays the same.

Any Ideas?

**Comment by just10minutes** [comment]
Even I am getting similar error, is there a fix in place by any chance?

**Comment by sphaero** [comment]
You are using python3 and at line 192 plaintext is getting appended to the bytearray.
```
padded.extend(plaintext)
```
This works in Python2 however in python3 plaintext is a string and strings in python3 are not bytes automatically. You'd need to specify the encoding. For example using utf-8 encoding
 ```
padded.extend(plaintext.encode('utf-8'))
```
However I don't know what encoding is the right one. I'd expect utf-8 though. 
This would work for python as well!

**Comment by sphaero** [comment]
Btw, this method is refactored in the @jlguardi master branch: https://github.com/jlguardi/yowsup/blob/master/yowsup/layers/axolotl/layer.py#L183

**Comment by sphaero** [comment]
Ow and in the develop branch it has also been refactored...
https://github.com/tgalal/yowsup/commit/8cb3a84dc100ad7d688650d3db9e7ebafaddc3a7

Guess we need to wait untill these changes are pushed to master
