### ISSUE TITLE
Error sending encrypted Messages on Raspian Jessie

### ISSUE THREAD

**Issue by arminth** [tgalal/yowsup#1447]
Dear all,

I have installed most recent Version (April1st 2016) on Raspberry Pi 2 running Jessie.

First I ran into an issue that six-library supplied by raspian is stuck on 1.8.
Could solve this with a pip install six --upgrade.
I was able to get registration code and could register.

With sending the first "Hello World" I get the following errrormessages

`
INFO:yowsup.layers.axolotl.layer:Axolotl layer is generating keys
Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 272, in process
    self.startSendClient()
  File "yowsup-cli", line 324, in startSendClient
    stack.start()
  File "/root/yowsup/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/root/yowsup/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/root/yowsup/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/root/yowsup/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/root/yowsup/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/root/yowsup/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/root/yowsup/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/root/yowsup/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/root/yowsup/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/root/yowsup/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup/yowsup/layers/axolotl/layer.py", line 122, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/root/yowsup/yowsup/layers/__init__.py", line 155, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/root/yowsup/yowsup/layers/axolotl/layer.py", line 182, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "/root/yowsup/yowsup/layers/axolotl/layer.py", line 361, in onGetKeysResult
    sessionBuilder.processPreKeyBundle(preKeyBundle)
  File "build/bdist.linux-x86_64/egg/axolotl/sessionbuilder.py", line 166, in processPreKeyBundle
  File "/root/yowsup/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 17, in getIdentityKeyPair
    return self.identityKeyStore.getIdentityKeyPair()
  File "/root/yowsup/yowsup/layers/axolotl/store/sqlite/liteidentitykeystore.py", line 31, in getIdentityKeyPair
    publicKey, privateKey = result
TypeError: 'NoneType' object is not iterable
`

I tried a pip install python-axolotl --upgrade but this didnt change anything.

If you switch off encryption with the -M switch, message is sent correctly.

Any ideas?
Cheers
Armin

**Comment by abloch** [comment]
I had the same problem. I think the -s command is not maintained. sending messages with the -y cli stilll works though

**Comment by Packus** [comment]
It works again after login/logoff with -y key.

**Comment by fabsh** [comment]
Nope. The interactive -y interface doesn't send encrypted messages either. My phone tells me the connection isn't encrypted.

**Comment by jlguardi** [comment]
Encrypted messages are sent just after incoming encrypted message.

**Comment by fabsh** [comment]
First received message from my phone gives me ERROR:yowsup.layers.axolotl.layer:No valid sessionsBad Mac!

No encrypted messages are sent from either end after that.

**Comment by LeoSdls** [comment]
Hello friends, anyone knows that when receiving messages on whatsapp my raspberry, erroneously receive the message, for example: sending "hello" from a mobile to my raspberry and receive "helloooooooooooooooooooooooooooo" or incomplete message. By submitting no problem, I have only this error when receiving the message, I get incomplete so to speak. Sorry for my English

**Comment by LeoSdls** [comment]
Hello friends, anyone knows that when receiving messages on whatsapp my raspberry, erroneously receive the message, for example: sending "hello" from a mobile to my raspberry and receive "helloooooooooooooooooooooooooooo" or incomplete message. By submitting no problem, I have only this error when receiving the message, I get incomplete so to speak. Sorry for my English
