### ISSUE TITLE
Yowsup v2.4.102 YowsupEnv' is not defined

### ISSUE THREAD

**Issue by maykel535** [tgalal/yowsup#1453]
Hi, before anything thanks for this yowsup update. I update the yowsup and all ok but when I running the command:

./yowsup-cli demos --yowsup --config yowsup.config -d

I get this error:

Traceback (most recent call last):
  File "./yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/local/nagios/yowsup/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/usr/local/nagios/yowsup/yowsup/env/env.py", line 13, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/nagios/yowsup/yowsup/env/env.py", line 10, in __init__
    YowsupEnv.registerEnv(cls)
NameError: global name 'YowsupEnv' is not defined

I have edit the YowsupEnv en these code?

**Comment by tgalal** [comment]
See my comment in #1435

**Comment by for2ne** [comment]
.

**Comment by Hisoka87** [comment]
hi! I have the same error!
Traceback (most recent call last):
  File "./yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/home/santi/yowsup/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/home/santi/yowsup/yowsup/env/env.py", line 13, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/home/santi/yowsup/yowsup/env/env.py", line 10, in __init__
    YowsupEnv.registerEnv(cls)
NameError: global name 'YowsupEnv' is not defined
