### ISSUE TITLE
YowAxolotlLayer' object has no attribute '_store'

### ISSUE THREAD

**Issue by fnlopes** [tgalal/yowsup#1460]
Hi,
When i call this command "./yowsup-cli demos -s XXXXXXX "Teste" -c whatsapp.config i have this error:

Traceback (most recent call last):
  File "./yowsup-cli", line 368, in <module>
    if not parser.process():
  File "./yowsup-cli", line 272, in process
    self.startSendClient()
  File "./yowsup-cli", line 323, in startSendClient
    not self.args["unmoxie"])
  File "/usr/lib/nagios/plugins/whatsapp/yowsup-master/yowsup/demos/sendclient/stack.py", line 21, in __init__
    .push(SendLayer)\
  File "/usr/lib/nagios/plugins/whatsapp/yowsup-master/yowsup/stacks/yowstack.py", line 64, in build
    return YowStack(self.layers, reversed = False, props = self._props)
  File "/usr/lib/nagios/plugins/whatsapp/yowsup-master/yowsup/stacks/yowstack.py", line 135, in __init__
    self._construct()
  File "/usr/lib/nagios/plugins/whatsapp/yowsup-master/yowsup/stacks/yowstack.py", line 206, in _construct
    inst = s()
  File "/usr/lib/nagios/plugins/whatsapp/yowsup-master/yowsup/layers/axolotl/layer.py", line 43, in __init__
    super(YowAxolotlLayer, self).__init__()
  File "/usr/lib/nagios/plugins/whatsapp/yowsup-master/yowsup/layers/__init__.py", line 115, in __init__
    super(YowProtocolLayer, self).__init__()
  File "/usr/lib/nagios/plugins/whatsapp/yowsup-master/yowsup/layers/__init__.py", line 47, in __init__
    members = inspect.getmembers(self, predicate=inspect.ismethod)
  File "/usr/lib64/python2.6/inspect.py", line 252, in getmembers
    value = getattr(object, key)
  File "/usr/lib/nagios/plugins/whatsapp/yowsup-master/yowsup/layers/axolotl/layer.py", line 55, in store
    if self._store is None:
AttributeError: 'YowAxolotlLayer' object has no attribute '_store'

Obs.: When i put the option -M, send the message, but i can't stay online by command line, gets another error.

  entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/usr/lib/nagios/plugins/whatsapp/yowsup-master/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'

Somebody can help me.

**Comment by robertol** [comment]
Same error with python 2.6 and 2.7.

**Comment by fabsh** [comment]
I get this too: https://gist.github.com/fabsh/09aeaf479d3a47431178404c98b1052b

The echo client crashes when it tries to store PreKeys on the server. AFAICT yowsup can't currently send encrypted messages.

**Comment by jlguardi** [comment]
Run cli in interactive mode first and login (/L). So keys will be uploaded an send client will start working.
