### ISSUE TITLE
Problem with receiving image messages 'NoneType' object has no attribute 'getAttributeValue'

### ISSUE THREAD

**Issue by DonkeyHot** [tgalal/yowsup#1469]
I have hupdated yowsup2 version v2.4.102 and I got a problem with receiving image messages.

**AttributeError: 'NoneType' object has no attribute 'getAttributeValue'**
```
Exception in thread Thread-68:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\user1\workspace\wamqd\wamqd\whats_app_stack.py", line 95, in start
    self.yowsupStack.loop()
  File "C:\Python27\lib\site-packages\yowsup\stacks\yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "C:\Python27\lib\asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "C:\Python27\lib\asyncore.py", line 156, in poll
    read(obj)
  File "C:\Python27\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\site-packages\yowsup\layers\network\layer.py", line 88, in handle_read
    self.receive(data)
  File "C:\Python27\lib\site-packages\yowsup\layers\network\layer.py", line 96, in receive
    self.toUpper(data)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\lib\site-packages\yowsup\layers\stanzaregulator\layer.py", line 29, in receive
    self.processReceived()
  File "C:\Python27\lib\site-packages\yowsup\layers\stanzaregulator\layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\lib\site-packages\yowsup\layers\auth\layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\lib\site-packages\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\lib\site-packages\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\lib\site-packages\yowsup\layers\axolotl\layer.py", line 124, in receive
    self.onMessage(protocolTreeNode)
  File "C:\Python27\lib\site-packages\yowsup\layers\axolotl\layer.py", line 146, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "C:\Python27\lib\site-packages\yowsup\layers\axolotl\layer.py", line 231, in handleEncMessage
    self.handleWhisperMessage(node)
  File "C:\Python27\lib\site-packages\yowsup\layers\axolotl\layer.py", line 288, in handleWhisperMessage
    self.toUpper(node)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 188, in receive
    s.receive(data)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 124, in receive
    recv(node)
  File "C:\Python27\lib\site-packages\yowsup\layers\protocol_media\layer.py", line 40, in recvMessageStanza
    if mediaNode.getAttributeValue("type") == "image":
AttributeError: 'NoneType' object has no attribute 'getAttributeValue'
```

**Comment by umonteiro** [comment]
Same error with me, it have to do with the recent changes of whatsapp crypt p2p ?

**Comment by jlguardi** [comment]
Print node at axolotl/layer.py level and one line before the exception. And post it, pls.

**Comment by DonkeyHot** [comment]
code 
```
    def recvMessageStanza(self, node):
        if node.getAttributeValue("type") == "media":
            mediaNode = node.getChild("media")
            print mediaNode;
            if mediaNode.getAttributeValue("type") == "image":
                entity = ImageDownloadableMediaMessageProtocolEntity.fromProtocolTreeNode(node)
```
outputs
```
None
```
and throws the Exception

**Comment by jlguardi** [comment]
Are you using my latest master (https://github.com/jlguardi/yowsup/master)? Otherwise, encrypted media isn't supported.

**Comment by thundergreen** [comment]
@jlguardi your Master branch supports encrypted media?

Thorsten Fröhlich
Am 07.04.2016 20:09 schrieb "jlguardi" <notifications@github.com>:

**Comment by jlguardi** [comment]
Yes, read my wiki.

**Comment by DonkeyHot** [comment]
Ok, thanks!
