### ISSUE TITLE
ImportError: No module named six

### ISSUE THREAD

**Issue by DanielV88** [tgalal/yowsup#1470]
I updated since the yowsup-cli wasn't working any more (registration failed, after some weeks).
Now I try to use yowsup-cli again, but receiving the following errors:

[root@******* yowsup]# yowsup-cli demos
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4.102', 'yowsup-cli')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4.102-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4.102-py2.6.egg/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4.102-py2.6.egg/yowsup/env/env.py", line 3, in <module>
    from six import with_metaclass
ImportError: No module named six

Does anyone know what to do about this?

**Comment by freelo** [comment]
how about `pip install six`?
