### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by josep112** [tgalal/yowsup#1478]
I've done everything that has been done in other posts, but even with the new version of yowsup receive the error message if you use the -M works but after 3 shipping the chip is blocked

/usr/src/yowsup-master/yowsup-cli demos -c /usr/src/yowsup-master/config -s "55XXXXXXXXX" "Message ok" 
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.layers.axolotl.layer:Axolotl layer is generating keys
Traceback (most recent call last):
  File "/usr/src/yowsup-master/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/src/yowsup-master/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/src/yowsup-master/yowsup-cli", line 324, in startSendClient
    stack.start()
  File "/usr/src/yowsup-master/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/usr/src/yowsup-master/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/src/yowsup-master/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/src/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/layer.py", line 122, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/src/yowsup-master/yowsup/layers/__init__.py", line 155, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/layer.py", line 182, in <lambda>
    self._sendIq(entity, lambda a, b: self.onGetKeysResult(a, b, self.processPendingMessages), self.onGetKeysError)
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/layer.py", line 361, in onGetKeysResult
    sessionBuilder.processPreKeyBundle(preKeyBundle)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 166, in processPreKeyBundle
    .setOurIdentityKey(self.identityKeyStore.getIdentityKeyPair())\
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 17, in getIdentityKeyPair
    return self.identityKeyStore.getIdentityKeyPair()
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteidentitykeystore.py", line 31, in getIdentityKeyPair
    publicKey, privateKey = result
TypeError: 'NoneType' object is not iterable

**Comment by jlguardi** [comment]
Start "yowsup-cli demos -y -d -c config" first to generate keys. Then try again and post logs.

**Comment by josep112** [comment]
/usr/src/yowsup-master# yowsup-cli demos -y -d -c config
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:

**Comment by jlguardi** [comment]
@josep112 what about login???

**Comment by josep112** [comment]
I do not know, right after the command drops this screen

./yowsup-cli demos -y -d -c config 
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:

**Comment by freelo** [comment]
`Type /help for available commands`

**Comment by freelo** [comment]
I think `/L` will log you in.

**Comment by josep112** [comment]
Thank you, after giving / A ./yowsup he created and is now sending, case solved!

**Comment by josep112** [comment]
sorry I meant " /L "
