### ISSUE TITLE
Group bot issues: crashes on bot adding / group participants changes

### ISSUE THREAD

**Issue by sattva1** [tgalal/yowsup#1483]
Hi,

I'm writing a bot partially based on https://github.com/joaoricardo000/whatsapp-bot-seed and using yowsup wa16 PR by jlguardi. However i've got a number of issues that i'm unable to figure out. Here's the relevant (and slightly simplified) code i'm running:

```python

class YowsupEchoStack(object):

    def __init__(self, credentials):
        self.credentials = credentials
        stack_builder = YowStackBuilder().pushDefaultLayers(axolotl=True)
        stack_builder.push(YowParallelLayer([RouteLayer, NotificationsLayer]))
        self.stack = stack_builder.build()
        self.stack.setCredentials(credentials)

    def start(self):
        self.stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))
        self.stack.loop(timeout=0.5, discrete=0.5)


class RouteLayer(YowInterfaceLayer):

    def __init__(self):
        super(RouteLayer, self).__init__()

        # Views definition.
        self.views = ROUTES[:]

    def route(self, message):
        text = message.getBody()

        if text.startswith(PREFIX):
            command, _, payload = text[1:].partition(' ')
        else:
            return

        for route, callback in self.views:
            if route == command:
                threading.Thread(target=self.handle_callback,
                                 args=(callback, message, payload)).start()
                break

    def handle_callback(self, callback, message, payload):
        try:
            data = callback(message, payload.encode('utf-8'))
            if data:
                self.toLower(data)  # if callback returns a message entity, sends it.
        except Exception:
            logging.exception("Error routing message: %s\n%s" % (message.getBody(), message))

    @ProtocolEntityCallback("message")
    def on_message(self, message):
        self.toLower(message.ack())  # Auto ack
        self.toLower(message.ack(True))  # Auto ack (double blue check symbol)

        # Routing only text type messages, for now ignoring other types. (media, audio, location...)
        if message.getType() == 'text':
            self.route(message)

    @ProtocolEntityCallback("receipt")
    def on_receipt(self, entity):
        self.toLower(entity.ack())


# For the sake of example, here is one of callback functions for actual bot commands.
def echo(message, payload):
    return TextMessageProtocolEntity("Echo: %s" % payload, to=message.getFrom())
```

The first issue i'm facing happens whenever a bot is initially added to any group. Once it's added, the first message posted to that group triggers the following exception:

```
Traceback (most recent call last):
  File "server.py", line 56, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "<...>/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib64/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib64/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "<...>/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "<...>/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "<...>/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "<...>/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "<...>/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "<...>/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "<...>/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "<...>/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "<...>/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "<...>/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "<...>/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "<...>/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "<...>/yowsup/layers/axolotl/layer.py", line 132, in receive
    self.onMessage(protocolTreeNode)
  File "<...>/yowsup/layers/axolotl/layer.py", line 154, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "<...>/yowsup/layers/axolotl/layer.py", line 228, in handleEncMessage
    self.handleWhisperMessage(node)
  File "<...>/yowsup/layers/axolotl/layer.py", line 289, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "<...>/yowsup/layers/axolotl/layer.py", line 347, in parseAndHandleMessageProto
    raise ValueError("Unhandled")
ValueError: Unhandled
```

After that the bot can be safely restarted, and it remains running fine, but that first message remains unhandled. I should note that sending private messages to the bot doesn't lead to any such issues.

The second and more serious issue happens when the group participants list has changed (i.e. a user was added / has joined or leaved the group): the bot silently ceases to ack and process any subsequent messages. Restarting the bot doesn't help in this situation. What's weird is if i add additional log prints into the RouteLayer.on_message() method like this:

```python
    @ProtocolEntityCallback("message")
    def on_message(self, message):
        logging.info('XXX got message')
        self.toLower(message.ack())  # Auto ack
        logging.info('XXX send ack')
        self.toLower(message.ack(True))  # Auto ack (double blue check symbol)
        logging.info('XXX send ack2')

        # Routing only text type messages, for now ignoring other types. (media, audio, location...)
        if message.getType() == 'text':
            logging.info('XXX routing message')
            self.route(message)
```

then i'm still getting them all printed for every message posted to the group despite messages remain unacked in the WA interface, and the bot fails to respond to the group as well (like if some underlying layer doesn't propagates the acks/responses back to the group):

```
_router.py_     [INFO][2016-04-09 14:36:22,024] XXX got message
_router.py_     [INFO][2016-04-09 14:36:22,026] XXX send ack
_router.py_     [INFO][2016-04-09 14:36:22,028] XXX send ack2
_router.py_     [INFO][2016-04-09 14:36:22,028] XXX routing message
_router.py_     [INFO][2016-04-09 14:40:22,857] XXX got message
_router.py_     [INFO][2016-04-09 14:40:22,860] XXX send ack
_router.py_     [INFO][2016-04-09 14:40:22,861] XXX send ack2
_router.py_     [INFO][2016-04-09 14:40:22,862] XXX routing message
```

Would be grateful for any help in debugging these issues or if anyone can point out what i'm doing wrong.

**Comment by jlguardi** [comment]
Try to reproduce the issue with jlguardi master and using yowsup-cli. So we were sure if the cause is in yowsup or in your layer.

**Comment by sattva1** [comment]
Okay, the first issue is easily reproduced (a bot added to a group, a message posted, crash):

```
[connected]:
Notification: Notification
From: [USER]-1460193849@g.us
Type: w:gp2
Participant: [USER]@s.whatsapp.net
Creator: [USER]@s.whatsapp.net
Create type: new
Creation timestamp: 1460193849
Subject: Bot 3
Subject owner: [USER]@s.whatsapp.net
Subject timestamp: 1460193849
Participants: {'[BOT]@s.whatsapp.net': None, '[USER]@s.whatsapp.net': 'admin'}

[connected]:
sender_key_distribution_message {
  groupId: "[USER]-1460193849@g.us"
  axolotl_sender_key_distribution_message: "3\010\214\216\353\214\004\020\000\032 Q\001\016)\264P\255\372\r\242[tL\350\227\266\021\000\231\250c\005\244\326uCr\020\264P\335\366\"!\005\260\215\303\010?\261\201\315\256l\305~\246\332\013U\246y\377\246T\211\001G\333d\210\274l\362\344k"
}

Traceback (most recent call last):
  File "yowsup-cli", line 324, in <module>
    if not parser.process():
  File "yowsup-cli", line 228, in process
    self.startCmdline()
  File "yowsup-cli", line 256, in startCmdline
    stack.start()
  File "<...>/yowsup/demos/cli/stack.py", line 27, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "<...>/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib64/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib64/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "<...>/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "<...>/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "<...>/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "<...>/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "<...>/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "<...>/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "<...>/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "<...>/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "<...>/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "<...>/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "<...>/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "<...>/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "<...>/yowsup/layers/axolotl/layer.py", line 136, in receive
    self.onMessage(protocolTreeNode)
  File "<...>/yowsup/layers/axolotl/layer.py", line 158, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "<...>/yowsup/layers/axolotl/layer.py", line 232, in handleEncMessage
    self.handleWhisperMessage(node)
  File "<...>/yowsup/layers/axolotl/layer.py", line 316, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "<...>/yowsup/layers/axolotl/layer.py", line 374, in parseAndHandleMessageProto
    raise ValueError("Unhandled")
ValueError: Unhandled
```

**Comment by sattva1** [comment]
And the second issue as well:
1. Message "Test" is posted and acked.
2. A new participant joins the group.
3. Message "Test 2" is posted and not acked.
4. Message "Test 3" is posted and not acked.
5. A participant is kicked from the group.
6. Message "Test 4" is sent.
7. CLI crashes with the same exception as in issue above.

```
[connected]:[[USER]/[USER]-1460193849@g.us(09-04-2016 15:30)]:[FFE223A2623EDC1BC4F1812B30777B] Test
Message FFE223A2623EDC1BC4F1812B30777B: Sent delivered receipt and Read
[connected]:

[connected]:
Notification: Notification
From: [USER]-1460193849@g.us
Type: w:gp2
Participant: [USER]@s.whatsapp.net
Participants: [PARTICIPANT]@s.whatsapp.net

[connected]:
Iq:
ID: 2
Type: result
from: [BOT]@s.whatsapp.net


[[USER]/[USER]-1460193849@g.us(09-04-2016 15:31)]:[E08FDD941BD3DADE8951B361FA5D77] Test 2
Message E08FDD941BD3DADE8951B361FA5D77: Sent delivered receipt and Read
[connected]:

[[USER]/[USER]-1460193849@g.us(09-04-2016 15:31)]:[82AF7693F9E944CBCEAC7A52BED8AC] Test 3
Message 82AF7693F9E944CBCEAC7A52BED8AC: Sent delivered receipt and Read
[connected]:
Iq:
ID: 3
Type: result
from: [BOT]@s.whatsapp.net

Iq:
ID: 4
Type: result
from: [BOT]@s.whatsapp.net

Iq:
ID: 5
Type: result
from: [BOT]@s.whatsapp.net


Notification: Notification
From: [USER]-1460193849@g.us
Type: w:gp2
Participant: [USER]@s.whatsapp.net

[connected]:
sender_key_distribution_message {
  groupId: "[USER]-1460193849@g.us"
  axolotl_sender_key_distribution_message: "3\010\227\262\311\354\003\020\000\032 \201 \217|L\025\213nP\225\345\226\031T\013\331\232\233\023\264n\266M2\214\266\255\332B*\351\235\"!\005\330GzA\321\253\202\271\025\253>\225\016\201m\005V\205Nr1\323\231\341x\271\001I\"b`>"
}
```

**Comment by jlguardi** [comment]
First issue fixed in  6f7d0c6 (tgalal wa16 didn't have the error)
Second issue related with https://github.com/jlguardi/yowsup/issues/62 and https://github.com/jlguardi/yowsup/issues/64

**Comment by sattva1** [comment]
Thanks for the pointers. However the commit regarding the first issue is only a partial fix: although there is no "Unhandled" exception from the axolotl layer anymore, the first message sent to a group after adding a bot remains unreceived, it misses the bot entirely. Here's the output from the CLI on the following steps:
1. Bot added to the group.
2. Message "Foo" is posted to the group (neither received nor logged nor acked).
3. Message "Test" is posted to the group (received and acked).

```
[connected]:Notification: Notification
From: [USER]-1460271505@g.us
Type: w:gp2
Participant: [USER]@s.whatsapp.net
Creator: [USER]@s.whatsapp.net
Create type: new
Creation timestamp: 1460271505
Subject: Bot 3
Subject owner: [USER]@s.whatsapp.net
Subject timestamp: 1460271505
Participants: {'[BOT]@s.whatsapp.net': None, '[USER]@s.whatsapp.net': 'admin'}

[connected]:
Iq:
ID: 2
Type: result
from: [BOT]@s.whatsapp.net


[[USER]/[USER]-1460271505@g.us(10-04-2016 12:58)]:[CED1279AEBCE0CF4A8E0EAD39EE122] Test
Message CED1279AEBCE0CF4A8E0EAD39EE122: Sent delivered receipt and Read
[connected]:
```

**Comment by jlguardi** [comment]
I've oppened #62 and #64 for this porpose.

**Comment by jlguardi** [comment]
Related with a76bd12.

**Comment by sattva1** [comment]
Thank you, seems to be a step in the right direction. I've experienced some desyncing issue on one occasion but am unable to reproduce it yet.

**Comment by sattva1** [comment]
Ok, the latter problems seem to be triggered by a bug in my consumer code, so i'm closing the issue.
