### ISSUE TITLE
echo demo appears to be broken with Python 3.5, yowsup 2.4.102

### ISSUE THREAD

**Issue by voltagex** [tgalal/yowsup#1484]
Crashes when sent a message.
```
(env-whatsapp) [voltagex@ea890b2a-eefd-11e5-a1ef-0cc47a6bbf34 ~]$ yowsup-cli demos -e -c .yowsuprc
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "/usr/home/voltagex/env-whatsapp/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/home/voltagex/env-whatsapp/bin/yowsup-cli", line 270, in process
    self.startEcho()
  File "/usr/home/voltagex/env-whatsapp/bin/yowsup-cli", line 308, in startEcho
    stack.start()
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/demos/echoclient/stack.py", line 21, in start
    self.stack.loop()
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/local/lib/python3.5/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python3.5/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/local/lib/python3.5/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/local/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/axolotl/layer.py", line 124, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/axolotl/layer.py", line 146, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/axolotl/layer.py", line 231, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/yowsup/layers/axolotl/layer.py", line 281, in handleWhisperMessage
    plaintext = sessionCipher.decryptMsg(whisperMessage)
  File "/usr/home/voltagex/env-whatsapp/lib/python3.5/site-packages/axolotl/sessioncipher.py", line 88, in decryptMsg
    return plaintext.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 6: invalid start byte

```

**Comment by andresakata** [comment]
Getting same error.

**Comment by McBacker** [comment]
Apply this "fix":

https://github.com/tgalal/yowsup/issues/1356

Working OK for text messages and Python 2.7.

**Comment by voltagex** [comment]
Duplicate of #1490, although it was created after this there's more discussion there.
