### ISSUE TITLE
Need to regenerate axolotl key when peers phone changes

### ISSUE THREAD

**Issue by mode2k** [tgalal/yowsup#1506]
Hi,

i always have to delete me axolotl.db and generate new keys with 
yowsup-cli demos -y -d -c yourconfig.conf
/L
when a peer changes his phone (hardware change - got a new phone)

With the old key no messages arrive at the peer. While sending with yowsup there is no errormessage.

Can you explain why?

Best regards

mode

**Comment by Gab0** [comment]
Confirmed. There should be a mechanism to remove the old  key for a contact if he sends some messages with a different key. The new key should be added automatically after. Can you show a log of this happening?

**Comment by jlguardi** [comment]
There is a PROP_IDENTITY_AUTOTRUST at axolotl/layer.py to do it.

**Comment by Gab0** [comment]
With autotrust we would have to mannualy set the contacts to autotrust, its good but not a long term solution, the official whatsapp client do it automatically... I don't have a clue on how to implement it xD

**Comment by mode2k** [comment]
Ok, 
i can not provide a log, because the old axolotl.db is deleted. Sorry.
Is there a possibility to delete only the key for this contact?

**Comment by tgalal** [comment]
As @jlguardi wrote, set PROP_IDENTITY_AUTOTRUST to True and you're good.

**Comment by mode2k** [comment]
I am good after the client with the new hardware writes a new message to me. AFTER this i can send messages to him again. BEFORE this my messages will not arrive him, cause i am still using the old key?

**Comment by fjrmaulana** [comment]
help me sir..

yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "d:\yowsup\yowsup\demos\sendclient\stack.py", line 31, in start
    self.stack.loop()
  File "d:\yowsup\yowsup\stacks\yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 150, in poll
    read(obj)
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 423, in hand
ent
    self.handle_read()
  File "d:\yowsup\yowsup\layers\network\layer.py", line 102, in handle_read
    self.receive(data)
  File "d:\yowsup\yowsup\layers\network\layer.py", line 110, in receive
    self.toUpper(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\stanzaregulator\layer.py", line 29, in receive
    self.processReceived()
  File "d:\yowsup\yowsup\layers\stanzaregulator\layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\auth\layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\axolotl\layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 194, in receive
    s.receive(data)
  File "d:\yowsup\yowsup\layers\axolotl\layer_receive.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 194, in receive
    s.receive(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 130, in receive
    recv(node)
  File "d:\yowsup\yowsup\layers\auth\layer_authentication.py", line 81, in handleFailure
    raise AuthError(nodeEntity.getReason())
yowsup.layers.auth.autherror.AuthError: not-authorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 272, in process
    self.startSendClient()
  File "yowsup-cli", line 324, in startSendClient
    stack.start()
  File "d:\yowsup\yowsup\demos\sendclient\stack.py", line 33, in start
    print("Authentication Error: %s" % e.message)
AttributeError: 'AuthError' object has no attribute 'message'

d:\yowsup>
