### ISSUE TITLE
does not work send messages

### ISSUE THREAD

**Issue by egorovalexey27** [tgalal/yowsup#1509]
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4.102', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in startSendClient
    not self.args["unmoxie"])
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/demos/sendclient/stack.py", line 20, in __init__
    .pushDefaultLayers(encryptionEnabled)\
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/stacks/yowstack.py", line 51, in pushDefaultLayers
    defaultLayers = YowStackBuilder.getDefaultLayers(axolotl)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/stacks/yowstack.py", line 73, in getDefaultLayers
    from yowsup.layers.axolotl import YowAxolotlLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.102-py2.7.egg/yowsup/layers/axolotl/layer.py", line 3, in <module>
    from axolotl.util.keyhelper import KeyHelper
  File "/usr/local/lib/python2.7/dist-packages/axolotl/util/keyhelper.py", line 10, in <module>
    from ..identitykeypair import IdentityKeyPair
  File "/usr/local/lib/python2.7/dist-packages/axolotl/identitykeypair.py", line 3, in <module>
    from .state.storageprotos import IdentityKeyPairStructure
  File "/usr/local/lib/python2.7/dist-packages/axolotl/state/storageprotos.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name symbol_database

**Comment by jlguardi** [comment]
Read https://github.com/jlguardi/yowsup/issues/57
