### ISSUE TITLE
No sender key

### ISSUE THREAD

**Issue by Gab0** [tgalal/yowsup#1522]
With a new database file, receiving messages from groups I was already in, how do I get those sender keys? The yowsup-cli appears to have a command to do this (/keys get [jid]), but this returns failure either using a group jid or person jid.

 Solution is to exit and reenter the groups? (I tried) Or just leave the client online for sufficient time to get the skeys? Thanks..

**Comment by sowerkoku** [comment]
@tgalal 

It gives me problems when I run: /keys set.

`
[connected]:/keys set
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/tcontrol/yowsup/yowsup/demos/cli/cli.py", line 154, in startInputThread
    wait = self.execCmd(cmd)
  File "/home/tcontrol/yowsup/yowsup/demos/cli/cli.py", line 138, in execCmd
    return self.doExecCmd(lambda :targetFn(*args))
  File "/home/tcontrol/yowsup/yowsup/demos/cli/cli.py", line 141, in doExecCmd
    return fn()
  File "/home/tcontrol/yowsup/yowsup/demos/cli/cli.py", line 138, in <lambda>
    return self.doExecCmd(lambda :targetFn(*args))
  File "/home/tcontrol/yowsup/yowsup/demos/cli/layer.py", line 348, in keys_set
    with AxolotlOptionalModule(failMessage = self.__class__.FAIL_OPT_AXOLOTL) as axoOptMod:
  File "/home/tcontrol/yowsup/yowsup/common/optionalmodules.py", line 44, in __init__
    require=require)
TypeError: __init__() got an unexpected keyword argument 'failmessage'`

**Comment by Gab0** [comment]
Digging into it, when you are put on a new group, along with the first message you receive from a participant, you get a ``TYPE_MSG`` containg the sender keys. This is sent to protobuf who raises error on reading it, so no keys are decoded.

**Comment by tgalal** [comment]
@Gab0 is this in wa16 branch ?

**Comment by Gab0** [comment]
yes, on wa16.. the command is fixed now, thanks.
