### ISSUE TITLE
Error on Yowsup-cli echo client

### ISSUE THREAD

**Issue by navinpai** [tgalal/yowsup#1527]
I'm trying to run the yowsup-cli echo client with the latest code, and I get the following error.

```
./yowsup-cli demos --config ~/yowsup-cli.config -e
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


ERROR:yowsup.layers.axolotl.layer:No such signedprekeyrecord! 44143 
Traceback (most recent call last):
  File "./yowsup-cli", line 368, in <module>
    if not parser.process():
  File "./yowsup-cli", line 270, in process
    self.startEcho()
  File "./yowsup-cli", line 308, in startEcho
    stack.start()
  File "/home/navin/downloads/yowsup/demos/echoclient/stack.py", line 21, in start
    self.stack.loop()
  File "/home/navin/downloads/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/navin/downloads/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/home/navin/downloads/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/home/navin/downloads/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/navin/downloads/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/navin/downloads/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/navin/downloads/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/navin/downloads/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/navin/downloads/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/navin/downloads/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/navin/downloads/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/navin/downloads/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/navin/downloads/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/navin/downloads/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/navin/downloads/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/navin/downloads/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/navin/downloads/yowsup/layers/axolotl/layer.py", line 124, in receive
    self.onMessage(protocolTreeNode)
  File "/home/navin/downloads/yowsup/layers/axolotl/layer.py", line 146, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/navin/downloads/yowsup/layers/axolotl/layer.py", line 231, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/home/navin/downloads/yowsup/layers/axolotl/layer.py", line 277, in handleWhisperMessage
    encMessageProtocolEntity = EncryptedMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/home/navin/downloads/yowsup/layers/axolotl/protocolentities/message_encrypted.py", line 53, in fromProtocolTreeNode
    encNode.data.encode('latin-1') if sys.version_info >= (3,0) else encNode.data)
  File "/home/navin/downloads/yowsup/layers/axolotl/protocolentities/message_encrypted.py", line 24, in setEncProps
    assert encType in "pkmsg", "msg"
AssertionError: msg
```

I'm running this on python 2.7.3. The send message demo command however seems to work without any issue. Any idea why this is happening?

**Comment by navinpai** [comment]
Ok, so came across #898 , which seems to point to the same issue, and saw the comment mentioning this was being worked on in wa16 branch. Used the code from that branch and it seems to work just perfect. Closing this issue as this will be out in the next release anyway. :+1:
