### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getAttributeValue' (mediaNode)

### ISSUE THREAD

**Issue by ganesansays** [tgalal/yowsup#1529]
I am able to successfully login but not able to read messages. Appreciate any help.

[connected]:Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/usr/local/bin/yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/demos/cli/stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/**init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 124, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 146, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 229, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer.py", line 274, in handlePreKeyWhisperMessage
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init**.py", line 188, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/**init**.py", line 124, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_media/layer.py", line 40, in recvMessageStanza
    if mediaNode.getAttributeValue("type") == "image":
AttributeError: 'NoneType' object has no attribute 'getAttributeValue'

**Comment by jlguardi** [comment]
Encrypted media isn't supported in tgalal/master. Try wa16 branch or my master.

**Comment by ganesansays** [comment]
@jlguardi, thanks for the options. I tried you master. I am encountering a different effort. I am creating and issue in your fork.

**Comment by ganesansays** [comment]
@jlguardi , in wa16 branch I am getting the following issue. 

[offline]:/L
Auth: Logged in!
[connected]:Traceback (most recent call last):
  File "./yowsup-cli", line 368, in <module>
    if not parser.process():
  File "./yowsup-cli", line 268, in process
    self.startCmdline()
  File "./yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/home/ubuntu/yowsup/yowsup/demos/cli/stack.py", line 27, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/home/ubuntu/yowsup/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/ubuntu/yowsup/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/ubuntu/yowsup/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/ubuntu/yowsup/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/ubuntu/yowsup/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/ubuntu/yowsup/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/ubuntu/yowsup/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/ubuntu/yowsup/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/home/ubuntu/yowsup/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/__init__.py", line 188, in receive
    s.receive(data)
  File "/home/ubuntu/yowsup/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "/home/ubuntu/yowsup/yowsup/layers/axolotl/layer_receive.py", line 73, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/ubuntu/yowsup/yowsup/layers/axolotl/layer_receive.py", line 86, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/home/ubuntu/yowsup/yowsup/layers/axolotl/layer_receive.py", line 129, in handlePreKeyWhisperMessage
    plaintext = sessionCipher.decryptPkmsg(preKeyWhisperMessage)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessioncipher.py", line 96, in decryptPkmsg
    unsignedPreKeyId = self.sessionBuilder.process(sessionRecord, ciphertext)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 50, in process
    unsignedPreKeyId = self.processV3(sessionRecord, message)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 121, in processV3
    parameters.setOurOneTimePreKey(self.preKeyStore.loadPreKey(message.getPreKeyId()).getKeyPair())
  File "/home/ubuntu/yowsup/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 34, in loadPreKey
    return self.preKeyStore.loadPreKey(preKeyId)
  File "/home/ubuntu/yowsup/yowsup/layers/axolotl/store/sqlite/liteprekeystore.py", line 20, in loadPreKey
    raise Exception("No such prekeyRecord!")
Exception: No such prekeyRecord!

**Comment by tgalal** [comment]
5ac5c3c
