### ISSUE TITLE
How to use yowsup2 send image

### ISSUE THREAD

**Issue by moriweiji** [tgalal/yowsup#1538]
How to use yowsup2 send image like "./yowsup-cli demos -c 1.config -s phone message" ,but not Start the Yowsup command line client.

**Comment by sowerkoku** [comment]
@moriweiji 
tried with:
`echo -e "/L\n/image send phone $HOME/image.jpg" | ./yowsup-cli demos -c 1.config -y &`

then you kill the process: `kill %1`

**Comment by moriweiji** [comment]
@sowerkoku
Thank you! why I need kill the process:kill %1?

**Comment by sowerkoku** [comment]
@moriweiji 

with the option "-y" the cli option is activated and the "&" leaves the background process. then you need to kill this process after the message is sent.
kill the process:
"kill %1" or "kill -9 pid"

**Comment by moriweiji** [comment]
@sowerkoku
thank，I know how to kill the process.

**Comment by moriweiji** [comment]
@sowerkoku
I have a few of pictures want send to my friend.Now I will write a python program,but output=os.popen('echo -e "/L\n/image send phone $HOME/image.jpg" | ./yowsup-cli demos -c 1.config -y &' can't  run in python. Can you help me?

**Comment by sowerkoku** [comment]
@moriweiji 
to execute a command in python:
`import commands, time`
`output = commands.getoutput('echo -e "/L\n/image send phone $HOME/image.jpg" | ./yowsup-cli demos -c 1.config -y &')`
`time.sleep(6)`
`commands.getoutput('kill %1')`

**Comment by moriweiji** [comment]
@sowerkoku
system return "sh: 2: Syntax error: ";" unexpected" what's wrong

**Comment by sowerkoku** [comment]
@moriweiji
I remember now that "commands.getoutput" captures what returns the command and "os.system" executes the command

**Comment by moriweiji** [comment]
I have tested it. but fail it

**Comment by sowerkoku** [comment]
@moriweiji 

you only need to send a picture? or you need other things?
we can create a specific layer for that.

**Comment by moriweiji** [comment]
@sowerkoku
yes,send a picture and send a txt

**Comment by lolibo** [comment]
@moriweiji 
Have you already found a solution for your problem ?
I have the same problem ..
I would appreciate an answer.

**Comment by sowerkoku** [comment]
@tgalal @moriweiji @lolibo 

unfortunately not supported by this version of yowsup (image, sound, video, vcard).

**Comment by rhernandez-itemsoft** [comment]
Can you help me?
I use this command on bash script  and i get this error:


### [offline]:Auth: Logged in!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/demos/cli/cli.py", line 153, in startInputThread
    cmd = self._queuedCmds.pop(0) if len(self._queuedCmds) else input(self.getPrompt()).strip()
EOFError: EOF when reading a line

[connected]:[connected]:[connected]:general: Disconnected: Requested

**Comment by rodrigoorrego** [comment]
@rhernandez-itemsoft i tried the same thing and had the same error...

someone else figured it out...?

thanks in advance! :)

**Comment by vteccomm** [comment]
hi i am newbie here 
i have successfully installed and configure yowsup 2.0. Can send and receive message but unable to send images and audio.
please help me ( possibly step by step ) how and where to use the code  mentioned earlier.

output=os.popen('echo -e "/L\n/image send phone $HOME/image.jpg" | ./yowsup-cli demos -c 1.config 

thanks

**Comment by jakibaki** [comment]
If you're using python anyways just use the yowsup api like you're supposed to (see the wiki and if that's understandably too confusing look at how other projects do it ([this](https://github.com/rmed/wat-bridge) is a nice understandable example for how to handle incoming messages and send new ones (you can check the yowsup-cli source code for how you would normally send an image).

However sending images is currently broken in yowsup so it won't work at all for now. [People are getting close to a solution though](https://github.com/tgalal/yowsup/issues/2149) so hopefully you'll be able to send images again in the near future.
