### ISSUE TITLE
OSX: global name 'YowsupEnv' is not defined : with latest install 

### ISSUE THREAD

**Issue by thisisdos1984** [tgalal/yowsup#1539]
I am getting this error even with latest master branch. 
I have updated local installation with,

sudo python setup.py install

Any suggestions ? 
--

**Comment by rafaelsilverioit** [comment]
@thisisdos1984 please, show the output, if possible, with the debug option <b>-d</b>.

**Comment by thisisdos1984** [comment]
$ sudo yowsup-cli -d
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4.102', 'yowsup-cli')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1350, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Python/2.7/site-packages/yowsup2-2.4.102-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/Library/Python/2.7/site-packages/yowsup2-2.4.102-py2.7.egg/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/Library/Python/2.7/site-packages/yowsup2-2.4.102-py2.7.egg/yowsup/env/env.py", line 13, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py", line 566, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Library/Python/2.7/site-packages/yowsup2-2.4.102-py2.7.egg/yowsup/env/env.py", line 10, in __init__
    YowsupEnv.registerEnv(cls)
NameError: global name 'YowsupEnv' is not defined
$

**Comment by rafaelsilverioit** [comment]
Hey, in order to start, you need to generate a password and then run:

$ ./yowsup-cli demos -d -l phone:password (other options)

This is the output I've asked.

**Comment by thisisdos1984** [comment]
but i m not even able to run yowsup-cli

**Comment by yniwly43** [comment]
First of all don't run it as sudo.
Second, run it with ./yowsup-cli, not yowsup-cli

**Comment by thisisdos1984** [comment]
I tried both, I am getting same error. If you think this is environment issue, then please let me know how to cleanup. Thanks in advance. 


$ ./yowsup-cli 
Traceback (most recent call last):
  File "./yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/Users/user/Downloads/yowsup_git/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/Users/user/Downloads/yowsup_git/yowsup/env/env.py", line 13, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py", line 566, in with_metaclass
    return meta("NewBase", bases, {})
  File "/Users/user/Downloads/yowsup_git/yowsup/env/env.py", line 10, in __init__
    YowsupEnv.registerEnv(cls)
NameError: global name 'YowsupEnv' is not defined
$

**Comment by tgalal** [comment]
Use the issues search box
