### ISSUE TITLE
Error reading a messages with emojis

### ISSUE THREAD

**Issue by drmaposa** [tgalal/yowsup#1541]
I recently installed Yowsup from **https://github.com/jlguardi/yowsup** 

When I run `yowsup-cli demos -y -l  MOBILE:PASSWORD`

I get the error below.

Im thinking the script is failing to parse the Emoji characters from another person who sent the smiley face. The previous versions were working fine

`
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
Auth: Logged in!
[connected]:Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_scr                                                      ipt
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_sc                                                      ript
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO                                                      /scripts/yowsup-cli", line 324, in <module>

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO                                                      /scripts/yowsup-cli", line 228, in process

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO                                                      /scripts/yowsup-cli", line 256, in startCmdline

  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/stack.py", line 27, in sta                                                      rt
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 187, in lo                                                      op
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 102,                                                       in handle_read
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 110,                                                       in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toU                                                      pper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", li                                                      ne 29, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", li                                                      ne 49, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toU                                                      pper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 65                                                      , in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toU                                                      pper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in                                                       receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toU                                                      pper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in                                                       receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toU                                                      pper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 136,                                                       in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 160,                                                       in onMessage
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toU                                                      pper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 188, in re                                                      ceive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 124, in re                                                      ceive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_messages/layer.py",                                                       line 21, in recvMessageStanza
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 75, in toU                                                      pper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/interface/interface.py", line                                                       78, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/layer.py", line 529, in on                                                      Message
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 0: ordinal                                                       not in range(128)
`

**Comment by drmaposa** [comment]
If you change Line No. 523 from 

`MESSAGE=messageOut.encode('latin-1').decode() if sys.version_info >= (3, 0) else messageOut,`

to

`MESSAGE=messageOut,`

the error message is gone

How do we fix the issue?

**Comment by jlguardi** [comment]
@drmaposa this change shouldn't affect you if using python2.7 as you made. Moreover, I made a fix some days ago in my master to fi this issue. Update an try again. If issue persists, reopen it, please.
