### ISSUE TITLE
Python-Six and DateUtil error

### ISSUE THREAD

**Issue by christiankrug** [tgalal/yowsup#1544]
Hello, I'm running intro problems when issuing the following command on my raspberry pi:
`sudo yowsup-cli demos --yowsup --config config`
When everything is installed normally I get the following python-six error:

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    **import**('pkg_resources').run_script('yowsup2==2.4.103', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (six 1.8.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9'))

Once I uninstall python-six I get the following error:

[Traceback](most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    **import**('pkg_resources').run_script('yowsup2==2.4.103', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: python-dateutil

This does apparently happen because it removes python-dateutil when I remove python-six.

**Comment by nightcore125** [comment]
Install six with:
pip install six
