### ISSUE TITLE
yowsup-cli: contact sync causes exception

### ISSUE THREAD

**Issue by yniwly43** [tgalal/yowsup#1555]
Tried using yowsup-cli to figure out why the blocking happens.
So, I connected, did a /contacts sync with 60 contacts. I got an exception, below:

```
yowsup-cli  v2.0.15
yowsup      v2016.4.26.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

..
..

rx: <success status="active" kind="free" creation="1461729818" expiration="4444444444" props="5" t="1461794533">

Yowsup Cli client
==================
Type /help for available commands

[connected]:/contacts sync 963442044164,963405610710,963446887998,963409039597,963443010186,963444828874,963428722089,963405819488,963406007403,963424222916,963448882100,963423423864,963444514614,963444775652,963445772747,963407484014,972
526662445,963405064130,963408870055,963424335758,963447787801,963445743214,963426998224,963447456588,963424260654,963428888556,963444918079,963428888531,963403048779,963444260246,963425816442,963406692768,963422511543,963403103010,9634445
44805,963407755752,963447552742,963444550228,963444814551,963405985890,963433360577,963445700236,963443082881,963443027000,963448198567,963443380028,963426201361,963409019633,963428888907,963442293660,963406673226,963405250034,96342453459
1,963446486887,963404968342,963406971951,963448120710,963406410077,963444470671
tx: <iq xmlns="urn:xmpp:whatsapp:sync" type="get" id="2">
<sync index="0" last="true" mode="full" context="interactive" sid="131062717430000000">
<user>
963442044164
HEX:393633343432303434313634
</user>
<user>
963405610710
HEX:393633343035363130373130
</user>
<user>
963446887998
HEX:393633343436383837393938
</user>
<user>
963409039597
HEX:393633343039303339353937
</user>
<user>
963443010186
HEX:393633343433303130313836
</user>
<user>
963444828874
HEX:393633343434383238383734
</user>
<user>
963428722089
HEX:393633343238373232303839
</user>
<user>
963405819488
HEX:393633343035383139343838
</user>
<user>
963406007403
HEX:393633343036303037343033
</user>
<user>
963424222916
HEX:393633343234323232393136
</user>
<user>
963448882100
HEX:393633343438383832313030
</user>
<user>
963423423864
HEX:393633343233343233383634
</user>
<user>
963444514614
HEX:393633343434353134363134
</user>
<user>
963444775652
HEX:393633343434373735363532
</user>
<user>
963445772747
HEX:393633343435373732373437
</user>
<user>
963407484014
HEX:393633343037343834303134
</user>
<user>
963426662445
HEX:393633343236363632343435
</user>
<user>
963405064130
HEX:393633343035303634313330
</user>
<user>
963408870055
HEX:393633343038383730303535
</user>
<user>
963424335758
HEX:393633343234333335373538
</user>
<user>
963447787801
HEX:393633343437373837383031
</user>
<user>
963445743214
HEX:393633343435373433323134
</user>
<user>
963426998224
HEX:393633343236393938323234
</user>
<user>
963447456588
HEX:393633343437343536353838
</user>
<user>
963424260654
HEX:393633343234323630363534
</user>
<user>
963428888556
HEX:393633343238383838353536
</user>
<user>
963444918079
HEX:393633343434393138303739
</user>
<user>
963428888531
HEX:393633343238383838353331
</user>
<user>
963403048779
HEX:393633343033303438373739
</user>
<user>
963444260246
HEX:393633343434323630323436
</user>
<user>
963425816442
HEX:393633343235383136343432
</user>
<user>
963406692768
HEX:393633343036363932373638
</user>
<user>
963422511543
HEX:393633343232353131353433
</user>
<user>
963403103010
HEX:393633343033313033303130
</user>
<user>
963444544805
HEX:393633343434353434383035
</user>
<user>
963407755752
HEX:393633343037373535373532
</user>
<user>
963447552742
HEX:393633343437353532373432
</user>
<user>
963444550228
HEX:393633343434353530323238
</user>
<user>
963444814551
HEX:393633343434383134353531
</user>
<user>
963405985890
HEX:393633343035393835383930
</user>
<user>
963433360577
HEX:393633343333333630353737
</user>
<user>
963445700236
HEX:393633343435373030323336
</user>
<user>
963443082881
HEX:393633343433303832383831
</user>
<user>
963443027000
HEX:393633343433303237303030
</user>
<user>
963448198567
HEX:393633343438313938353637
</user>
<user>
963443380028
HEX:393633343433333830303238
</user>
<user>
963426201361
HEX:393633343236323031333631
</user>
<user>
963409019633
HEX:393633343039303139363333
</user>
<user>
963428888907
HEX:393633343238383838393037
</user>
<user>
963442293660
HEX:393633343432323933363630
</user>
<user>
963406673226
HEX:393633343036363733323236
</user>
<user>
963405250034
HEX:393633343035323530303334
</user>
<user>
963424534591
HEX:393633343234353334353931
</user>
<user>
963446486887
HEX:393633343436343836383837
</user>
<user>
963404968342
HEX:393633343034393638333432
</user>
<user>
963406971951
HEX:393633343036393731393531
</user>
<user>
963448120710
HEX:393633343438313230373130
</user>
<user>
963406410077
HEX:393633343036343130303737
</user>
<user>
963444470671
HEX:393633343434343730363731
</user>
</sync>
</iq>

Exception: invalid list size in readListSize: token 120
Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/yniwly43/yowsup/yowsup/layers/network/layer.py", line 176, in handle_read
    self.receive(data)
  File "/home/yniwly43/yowsup/yowsup/layers/network/layer.py", line 200, in receive
    self.toUpper(data)
  File "/home/yniwly43/yowsup/yowsup/layers/__init__.py", line 68, in toUpper
    self.__upper.receive(data)
  File "/home/yniwly43/yowsup/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/yniwly43/yowsup/yowsup/layers/stanzaregulator/layer.py", line 53, in processReceived
    self.toUpper(oneMessageData)
  File "/home/yniwly43/yowsup/yowsup/layers/__init__.py", line 68, in toUpper
    self.__upper.receive(data)
  File "/home/yniwly43/yowsup/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/yniwly43/yowsup/yowsup/layers/__init__.py", line 68, in toUpper
    self.__upper.receive(data)
  File "/home/yniwly43/yowsup/yowsup/layers/coder/layer.py", line 33, in receive
    node = self.reader.getProtocolTreeNode(data)
  File "/home/yniwly43/yowsup/yowsup/layers/coder/decoder.py", line 16, in getProtocolTreeNode
    return self.nextTreeInternal(data)
  File "/home/yniwly43/yowsup/yowsup/layers/coder/decoder.py", line 229, in nextTreeInternal
    size = self.readListSize(self.readInt8(data), data)
  File "/home/yniwly43/yowsup/yowsup/layers/coder/decoder.py", line 167, in readListSize
    raise Exception("invalid list size in readListSize: token " + str(token))

```

**Comment by yniwly43** [comment]
This seems to be related to a protocol change... token 120 is not an option, only 248 (list with 255 or less items) or 249 (list with 65535 or less items).

**Comment by josemonino** [comment]
@yniwly43 From where did you get those numbers? What's the meaning of "token 120"?

**Comment by rigid** [comment]
The numbers come from whatsapp. They are processed in https://github.com/tgalal/yowsup/blob/master/yowsup/layers/coder/decoder.py#L84 and 120 is not supported atm.
