### ISSUE TITLE
error when receiving an image with 2.4.102 and 2.4.103 version

### ISSUE THREAD

**Issue by josben** [tgalal/yowsup#1565]
===================== ERROR IMAGES =====================
Traceback (most recent call last):
  File "/home/ben/Project/environments/fabrica-env/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.103', 'yowsup-cli')
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home/ben/Project/environments/fabrica-env/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/home/ben/Project/environments/fabrica-env/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/home/ben/Project/environments/fabrica-env/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/demos/cli/stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/network/layer.py", line 88, in handle_read
    self.receive(data)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/network/layer.py", line 96, in receive
    self.toUpper(data)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/axolotl/layer.py", line 124, in receive
    self.onMessage(protocolTreeNode)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/axolotl/layer.py", line 146, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/axolotl/layer.py", line 231, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/axolotl/layer.py", line 288, in handleWhisperMessage
    self.toUpper(node)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/__init__.py", line 75, in toUpper
    self.__upper.receive(data)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/__init__.py", line 188, in receive
    s.receive(data)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/__init__.py", line 124, in receive
    recv(node)
  File "/home/ben/Project/environments/fabrica-env/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/yowsup/layers/protocol_media/layer.py", line 40, in recvMessageStanza
    if mediaNode.getAttributeValue("type") == "image":
AttributeError: 'NoneType' object has no attribute 'getAttributeValue'
================================= END IMAGE ERROR ===================
with .102 and 103 version is the same error with images

There is sometimes the error with messages received

the message is: que tal?
but received: Message: ue tal���������������������������������������������������������������������������������������������������������������������������������������������������������������������

the message is: Hola
received: Message: Hola++++++++++++++++++++++++++++++++++++++++++

Thanks.

**Comment by jlguardi** [comment]
Related with padding. Use develop branch or my master.
