### ISSUE TITLE
yowsup-cli can't used

### ISSUE THREAD

**Issue by moriweiji** [tgalal/yowsup#1569]
C:\yowsup>python yowsup-cli demos -c 1.config -y
Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 268, in process
    self.startCmdline()
  File "yowsup-cli", line 290, in startCmdline
    from yowsup.demos import cli
  File "C:\yowsup\yowsup\demos\cli\__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "C:\yowsup\yowsup\demos\cli\stack.py", line 2, in <module>
    from .layer import YowsupCliLayer
  File "C:\yowsup\yowsup\demos\cli\layer.py", line 1, in <module>
    from .cli import Cli, clicmd
  File "C:\yowsup\yowsup\demos\cli\cli.py", line 9, in <module>
    import pyreadline as readline
ImportError: No module named pyreadline

Please help me !!thanks!

**Comment by moriweiji** [comment]
it was ok
