### ISSUE TITLE
[tgalal/develop] ACK for receipt causes delayed stream error when sending message

### ISSUE THREAD

**Issue by Vinpasso** [tgalal/yowsup#1576]
Good afternoon,

First of all let me thank all the contributors of this project for their excellent work. I am running a bridge for several instant messengers for 1.5 years now and Yowsup has always worked consistently, never once have I been blocked for using third-party applications.

Now however, it looks like I have hit a problem that I cannot solve by myself. I have tested this on two different numbers and I have waited a couple of days for an issue/fix to arise on GitHub, however there is no issue directly related to this one as far as I can tell.

This issue occurs on the current tgalal/develop.

This problem seems to be caused by a certain type of message, which I could not yet determine, that does not appear to be in the axolotl database (Axolotl layer does not have the message, bubbling it upwards) causing the message receipt to get acknowledged incorrectly by a higher layer. However, the actual stream error only occurs after 5-10 minutes.

At first I thought that this could be related to messages sent/received before encryption was rolled out, however after registering a new number this same phenomenon appears. While it is still possible to send messages in this condition, it is impossible to receive any more messages until these have been properly acknowledged. I believe this issue is related only to outgoing messages, since this issue only appears when handling receipts. I cannot determine whether this error occurs on all outgoing messages or randomly, however all sent messages solely contain text. Note that all of the messages dealt with are group messages in groups where all clients use encryption. Both android clients and iPhone clients are present in the group, this particular case seems to originate from a fully updated android mobile, and it has previously occurred on a second yowsup installation from another slightly outdated android mobile.

As far as I can tell the actual exception is not related to the case, it appears in the attempt to formulate an error message.

The debug log has been attached below. If necessary, I can also attach my Layer.py, a slightly modified version of the cli from 1 year ago that base64 encodes messages on the output to deal with Charset issues that has been updated over time to reflect changes on master.

Note that Auto-Reconnect has been deliberately disabled to avoid restart-loops which are likely to get the number blocked.

Any hints as to fixing this issue or pointing me in the right direction are much appreciated.

Sincerely,
Vinpasso

```
DEBUG:yowsup.env.env:registered env android => <class 'yowsup.env.env_android.AndroidYowsupEnv'>
DEBUG:yowsup.env.env:registered env s40 => <class 'yowsup.env.env_s40.S40YowsupEnv'>
DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f55fdba8358>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f5600f73048>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer -
Profiles
Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
DEBUG:yowsup.layers.network.layer:Connecting to e12.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="NUMBER" mechanism="WAUTH-2">
OMMITTED Authentication
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<success expiration="4444444444" t="1462641592" status="active" kind="free" props="5" creation="1462463693">
0k\xf4\x9d\xcaI|dr\xe3
                      (\xb0\xc7;@\x95\x83\x9bN
HEX3:b'306bf49dca497c6472e30b28b0c73b4095839b4e'
</success>

DEBUG:yowsup.layers.protocol_iq.layer:starting ping thread.
Auth: Logged in!
DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1462641592" type="groups">
</dirty>
</ib>

[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<receipt participant="Number_Ommitted" from="Number_Ommitted" t="1462465941" id="1462465940-1" offline="3">
</receipt>

DEBUG:yowsup.layers.axolotl.layer_send:Axolotl layer does not have the message, bubbling it upwards
DEBUG:yowsup.layers.logger.layer:tx:
<ack id="1462465940-1" to="Number_Ommitted" class="receipt">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt participant="Number_Ommitted" from="Number_Ommitted" t="1462465942" id="1462465940-1" offline="3">
</receipt>

DEBUG:yowsup.layers.axolotl.layer_send:Axolotl layer does not have the message, bubbling it upwards
DEBUG:yowsup.layers.logger.layer:tx:
<ack id="1462465940-1" to="Number_Ommitted" class="receipt">
</ack>
DEBUG:yowsup.layers.logger.layer:rx:
<receipt participant="Number_Ommitted" from="Number_Ommitted" t="1462465942" id="1462465940-1" offline="3">
</receipt>

DEBUG:yowsup.layers.axolotl.layer_send:Axolotl layer does not have the message, bubbling it upwards
DEBUG:yowsup.layers.logger.layer:tx:
<ack id="1462465940-1" to="Number_Ommitted" class="receipt">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt participant="Number_Ommitted" from="Number_Ommitted" t="1462465942" id="1462465940-1" offline="3">
</receipt>

DEBUG:yowsup.layers.axolotl.layer_send:Axolotl layer does not have the message, bubbling it upwards
DEBUG:yowsup.layers.logger.layer:tx:
<ack id="1462465940-1" to="Number_Ommitted" class="receipt">
</ack>

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq id="1" xmlns="w:p" type="get">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq from="Number_Ommitted" t="1462641642" id="1" type="result">
</iq>

Iq:
ID: 1
Type: result
from: Number_Ommitted

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq id="2" xmlns="w:p" type="get">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq from="Number_Ommitted" t="1462641692" id="2" type="result">
</iq>

Iq:
ID: 2
Type: result
from: Number_Ommitted

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq id="3" xmlns="w:p" type="get">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq from="Number_Ommitted" t="1462641742" id="3" type="result">
</iq>

Iq:
ID: 3
Type: result
from: Number_Ommitted

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq id="4" xmlns="w:p" type="get">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq from="Number_Ommitted" t="1462641792" id="4" type="result">
</iq>

Iq:
ID: 4
Type: result
from: Number_Ommitted

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq id="5" xmlns="w:p" type="get">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq from="Number_Ommitted" t="1462641842" id="5" type="result">
</iq>

Iq:
ID: 5
Type: result
from: Number_Ommitted

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq id="6" xmlns="w:p" type="get">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq from="Number_Ommitted" t="1462641892" id="6" type="result">
</iq>

Iq:
ID: 6
Type: result
from: Number_Ommitted

DEBUG:yowsup.layers.logger.layer:rx:
<stream:error>
<ack id="1462465940-1">
</ack>
</stream:error>

--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/logging/__init__.py", line 978, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.4/logging/__init__.py", line 565, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.4/logging/__init__.py", line 326, in getMessage
    msg = str(self.msg)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/auth/protocolentities/stream_error.py", line 46, in __str__
    out += self.getErrorData()
TypeError: Can't convert 'dict' object to str implicitly
Call stack:
  File "run.py", line 20, in <module>
    BridgeMPPArgParser()
  File "run.py", line 14, in __init__
    stack.start()
  File "/home/vinpasso/BridgeMPP/yowsup-python/yowsupclient/stack.py", line 31, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/local/lib/python3.4/asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python3.4/asyncore.py", line 153, in poll
    read(obj)
  File "/usr/local/lib/python3.4/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/lib/python3.4/asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/__init__.py", line 125, in receive
    recv(node)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/auth/layer_authentication.py", line 94, in handleStreamError
    self.toUpper(nodeEntity)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/usr/local/lib/python3.4/site-packages/yowsup2-2.4.103-py3.4.egg/yowsup/layers/interface/interface.py", line 86, in onStreamError
    logger.error(streamErrorEntity)
Message: <yowsup.layers.auth.protocolentities.stream_error.StreamErrorProtocolEntity object at 0x7f55fd493d68>
Arguments: ()
WARNING:yowsup.layers.interface.interface:No reconnecting because property org.openwhatsapp.yowsup.prop.interface.reconnect_on_stream_error is not set
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
DEBUG:yowsup.layers.protocol_iq.layer:stopping ping thread
general: Disconnected: Connection Closed
```

**Comment by Vinpasso** [comment]
I have experimented some more around this issues, including running it in different environments.

As I wanted to check if this was a mess up on the existing installation, I created a new setup in a virtual machine, completely untouched debian install, with the necessary build-essential and python-dev. However, after cloning and installing the same issue still appears on both numbers.

Next I tried switching over to @jlguardi master, as it seems to include more commits than the devel branch. However the same problem still persists.

I may try re-registering next, however I suspect that this issue will just return the next time I send messages to the encrypted group.

Thanks for any help,
Vinpasso

**Comment by jlguardi** [comment]
@Vinpasso are you sure about your installation? Obviously your acts are incorrect for groups but it is fixed in develop branch and also my master. 
Check https://github.com/tgalal/yowsup/blob/a59ac410c057e8042c528e9f73e9f3eaada6e79e/yowsup/layers/protocol_receipts/protocolentities/receipt_incoming.py where participant is missing in ack but in this file in develop branch the participant is present. Also my master. 
So check again your installation and report if required.

**Comment by Vinpasso** [comment]
Thanks for the hint, it appears an old version of the cli layer was causing issues, not sure why git was not overwriting it. 

Thanks for the help,
Vinpasso
