### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte in field: com.whatsapp.proto.UrlMessage.jpeg_thumbnail

### ISSUE THREAD

**Issue by bzero** [tgalal/yowsup#1591]
_server.py_	[ERROR][2016-05-12 22:13:54,772] Unexpected Exception: 
Traceback (most recent call last):
  File "bot.py", line 38, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "build/bdist.linux-armv7l/egg/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-armv7l/egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "build/bdist.linux-armv7l/egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 86, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 129, in handlePreKeyWhisperMessage
    self.parseAndHandleMessageProto(pkMessageProtocolEntity, plaintext[:-padding])
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 171, in parseAndHandleMessageProto
    m.ParseFromString(serializedData)
  File "/home/bob01/venv/lib/python2.7/site-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/home/bob01/venv/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1091, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/home/bob01/venv/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1127, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/home/bob01/venv/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 633, in DecodeField
    if value._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/home/bob01/venv/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1127, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/home/bob01/venv/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 502, in DecodeField
    field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])
  File "/home/bob01/venv/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 469, in _ConvertToUnicode
    return local_unicode(byte_str, 'utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte in field: com.whatsapp.proto.UrlMessage.jpeg_thumbnail

**Comment by jlguardi** [comment]
@bzero this is a bug layers/protocol_messages/proto/wa.proto jpeg_thumbnail should be bytes instead of string. You need to regenerate wa_pb2.py o edit it manually.
You can also use the wa_pb2.py in my master which h some other fixes.

**Comment by bzero** [comment]
worked for me

**Comment by msshapira** [comment]
ran into the same issues. Regenerated wa_pb2.py using bytes instead of string. Now URL messages are not even passed to yowsup....
@bzero how did you overcome this?

**Comment by jlguardi** [comment]
Try to import this code from my master. I've no time for that now but I've fixed this issue some time ago.
