### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)

### ISSUE THREAD

**Issue by bzero** [tgalal/yowsup#1592]
Traceback (most recent call last):
  File "/home/bob01/venv/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.103', 'yowsup-cli')
  File "/home/bob01/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/bob01/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/home/bob01/venv/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>

  File "/home/bob01/venv/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 268, in process

  File "/home/bob01/venv/local/lib/python2.7/site-packages/yowsup2-2.4.103-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 297, in startCmdline

  File "build/bdist.linux-armv7l/egg/yowsup/demos/cli/stack.py", line 26, in start
  File "build/bdist.linux-armv7l/egg/yowsup/stacks/yowstack.py", line 188, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-armv7l/egg/yowsup/layers/network/layer.py", line 102, in handle_read
  File "build/bdist.linux-armv7l/egg/yowsup/layers/network/layer.py", line 110, in receive
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
  File "build/bdist.linux-armv7l/egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
  File "build/bdist.linux-armv7l/egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
  File "build/bdist.linux-armv7l/egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
  File "build/bdist.linux-armv7l/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
  File "build/bdist.linux-armv7l/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 189, in receive
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 86, in handleEncMessage
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 129, in handlePreKeyWhisperMessage
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 188, in parseAndHandleMessageProto
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 217, in handleConversationMessage
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 189, in receive
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 125, in receive
  File "build/bdist.linux-armv7l/egg/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
  File "build/bdist.linux-armv7l/egg/yowsup/layers/interface/interface.py", line 80, in receive
  File "build/bdist.linux-armv7l/egg/yowsup/demos/cli/layer.py", line 512, in onMessage
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)

**Comment by Udirley** [comment]
Hello
I had this same problem and resolved added these lines down in the file layer.py

reload(sys)  
sys.setdefaultencoding('utf8')

Like this:

import sys
reload(sys)  
sys.setdefaultencoding('utf8')

Maybe this helps you.

**Comment by jlguardi** [comment]
@bzero change line 34 of yowsup/demos/cli/layer.py from:
'''
MESSAGE_FORMAT          = "[{FROM}({TIME})]:[{MESSAGE_ID}]\t {MESSAGE}"
'''
To:
'''
MESSAGE_FORMAT          = u"[{FROM}({TIME})]:[{MESSAGE_ID}]\t {MESSAGE}"
'''

**Comment by bzero** [comment]
utf8 solved, thanks guys
