### ISSUE TITLE
ValueError: Unhandled ( audio received on group )

### ISSUE THREAD

**Issue by bzero** [tgalal/yowsup#1595]
_bot.py_        [ERROR][2016-05-13 22:18:40,073] Unexpected Exception: Unhandled
Traceback (most recent call last):
  File "bot.py", line 38, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "build/bdist.linux-armv7l/egg/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-armv7l/egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "build/bdist.linux-armv7l/egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper(receive)data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)  (data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper(node)ve(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)  (data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper(data)ve(data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protoco(data)ode)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper(receive(data)   )
  File "build/bdist.linux-armv7l/egg/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)     (data)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMe(data)protocolTreeNode)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEnc(essage(protocolT)eeNode)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 90, in handleEncMessage
    self.handleSenderKeyM(ssage(node)     )
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 159, in handleSenderKeyMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext)
  File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer_receive.py", line 204, in parseAndHandleMessageProto
    raise ValueError("Unhandled")
ValueError: Unhandled

**Comment by jlguardi** [comment]
Audio messages and Location messages aren't still supported by tgalal/yowsup/develop. You can import this code from jlguardi/yowsup/master which implements audio and location messages.

**Comment by bzero** [comment]
perfect ! gonna merge it here, thanks for the prompt reply

**Comment by mp3il** [comment]
Any way just to let the yowsup to ignore audio messages instead of throwing exception and ending the stack loop?

**Comment by mzalazar** [comment]
For ignoring audio files:
/yowsup/layers/axolotl/layer_receive.py  (line 202 in my file):
        if not handled:
            print(m)
        #    raise ValueError("Unhandled")   <--- comment this one!

But with this workaround, audio messages doesn't seems to be marked as read, but it's no an issue for me.
