### ISSUE TITLE
Exception: No such prekeyRecord!

### ISSUE THREAD

**Issue by xhan0o** [tgalal/yowsup#1607]
[connected]:Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.103', 'yowsup-cli')
  File "/home/shan0o/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/shan0o/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.103-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.103-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 268, in process
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.103-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 297, in startCmdline
    
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/stack.py", line 26, in start
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 188, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 102, in handle_read
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 110, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 76, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 76, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 76, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 76, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 76, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 76, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 189, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer_receive.py", line 86, in handleEncMessage
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer_receive.py", line 125, in handlePreKeyWhisperMessage
  File "/home/shan0o/.local/lib/python2.7/site-packages/axolotl/sessioncipher.py", line 101, in decryptPkmsg
    unsignedPreKeyId = self.sessionBuilder.process(sessionRecord, ciphertext)
  File "/home/shan0o/.local/lib/python2.7/site-packages/axolotl/sessionbuilder.py", line 50, in process
    unsignedPreKeyId = self.processV3(sessionRecord, message)
  File "/home/shan0o/.local/lib/python2.7/site-packages/axolotl/sessionbuilder.py", line 121, in processV3
    parameters.setOurOneTimePreKey(self.preKeyStore.loadPreKey(message.getPreKeyId()).getKeyPair())
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 34, in loadPreKey
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/store/sqlite/liteprekeystore.py", line 21, in loadPreKey

Using code of develop branch(2 weeks older).

**Comment by jlguardi** [comment]
Send a message to recipient or regenerate your keys and discard current incoming message.
