### ISSUE TITLE
Can't import YowAxolotlLayer

### ISSUE THREAD

**Issue by kuhlsv** [tgalal/yowsup#1611]
Some people gets a ImportError because they use the Sample-Application scripts from the Wiki.
To avoid this problem change following:

```

from layer import EchoLayer

from yowsup.layers                             import YowParallelLayer
from yowsup.layers.auth                        import YowCryptLayer, YowAuthenticationProtocolLayer
from yowsup.layers.coder                       import YowCoderLayer
from yowsup.layers.network                     import YowNetworkLayer
from yowsup.layers.protocol_messages           import YowMessagesProtocolLayer
from yowsup.layers.stanzaregulator             import YowStanzaRegulator
from yowsup.layers.protocol_receipts           import YowReceiptProtocolLayer
from yowsup.layers.protocol_acks               import YowAckProtocolLayer
from yowsup.stacks import YowStack
from yowsup.common import YowConstants
from yowsup.layers import YowLayerEvent
from yowsup.layers.axolotl                     import YowAxolotlLayer
from yowsup.env                                import YowsupEnv


CREDENTIALS = ("phone", "password")  # replace with your phone and password

if __name__ == "__main__":
    layers = (
        EchoLayer,
        YowParallelLayer([YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer]),
        YowAxolotlLayer,
        YowCoderLayer,
        YowCryptLayer,
        YowStanzaRegulator,
        YowNetworkLayer
    )

    stack = YowStack(layers)
    stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, CREDENTIALS)  # setting credentials
    stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])  # whatsapp server address
    stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
    stack.setProp(YowCoderLayer.PROP_RESOURCE, YowsupEnv.getCurrent().getResource())  # info about us as WhatsApp client

    stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))  # sending the connect signal

    stack.loop()  # this is the main program loop

```

to this

```
from yowsup.stacks import  YowStackBuilder
from layer import EchoLayer
from yowsup.layers.auth import AuthError
from yowsup.layers import YowLayerEvent
from yowsup.layers.network import YowNetworkLayer
from yowsup.env                                import YowsupEnv

credentials = ("phone", "password") # replace with your phone and password
#CREDENTIALS = DemosArgParser._getCredentials()

if __name__==  "__main__":
    stackBuilder = YowStackBuilder()

    stack = stackBuilder\
        .pushDefaultLayers(True)\
        .push(EchoLayer)\
        .build()

    stack.setCredentials(credentials)
    stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))   #sending the connect signal
    stack.loop() #this is the program mainloop
```

This would solve it. Pls update Wiki!

**Comment by schoerg** [comment]
You could edit it yourself I think, or create a PR.

**Comment by matiasinsaurralde** [comment]
I was getting this error, thanks!

**Comment by jonathancma** [comment]
Edited the wiki to point here

**Comment by pdv63** [comment]
I also receive the error message after starting:

 File "/home/pi/yowsup/wareceive.py", line 18, in <module>
    from yowsup.layers.axolotl                     import YowAxolotlLayer
ImportError: cannot import name YowAxolotlLayer

Any news how to fix?

**Comment by jlguardi** [comment]
Why are you trying to use yowAxolotlLayer directly?

‎Anyway, this layer doesn't exist. See https://github.com/tgalal/yowsup/blob/master/yowsup/layers/axolotl/__init__.py

**Comment by xSiraxXx** [comment]
I use kuhlsv's run.py but can you also paste your layer.py? Mine just gives me errors (syntax error: print entity.ack() )

**Comment by coollorenzo** [comment]
with @kuhlsv code i get `Traceback (most recent call last):
  File "run.py", line 19, in <module>
    stack.setCredentials(credentials)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/stacks/yowstack.py", line 156, in setCredentials
    self.getLayerInterface(YowAuthenticationProtocolLayer).setCredentials(*credentials)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/auth/layer_interface_authentication.py", line 5, in setCredentials
    self._layer.setCredentials((phone, password))
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/auth/layer_authentication.py", line 46, in setCredentials
    self._credentials = self.__getCredentials(credentials)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/auth/layer_authentication.py", line 41, in __getCredentials
    password = base64.b64decode(pb64)
  File "/usr/lib/python3.5/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
`

**Comment by othreecodes** [comment]
Give this man a beer

**Comment by fjrmaulana** [comment]
sir how a bouth this.. where im wrong?

d:\yowsup>python yowsup-cli demos -c C:\Users\FAJAR\.yowsup\62896242xxxxx\config -s 6289999xxxxx "Hola"
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "d:\yowsup\yowsup\demos\sendclient\stack.py", line 31, in start
    self.stack.loop()
  File "d:\yowsup\yowsup\stacks\yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 150, in poll
    read(obj)
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 423, in handle_read_ev
ent
    self.handle_read()
  File "d:\yowsup\yowsup\layers\network\layer.py", line 102, in handle_read
    self.receive(data)
  File "d:\yowsup\yowsup\layers\network\layer.py", line 110, in receive
    self.toUpper(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\stanzaregulator\layer.py", line 29, in receive
    self.processReceived()
  File "d:\yowsup\yowsup\layers\stanzaregulator\layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\auth\layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\axolotl\layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 194, in receive
    s.receive(data)
  File "d:\yowsup\yowsup\layers\axolotl\layer_receive.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 194, in receive
    s.receive(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 130, in receive
    recv(node)
  File "d:\yowsup\yowsup\layers\auth\layer_authentication.py", line 81, in handleFailure
    raise AuthError(nodeEntity.getReason())
yowsup.layers.auth.autherror.AuthError: not-authorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 272, in process
    self.startSendClient()
  File "yowsup-cli", line 324, in startSendClient
    stack.start()
  File "d:\yowsup\yowsup\demos\sendclient\stack.py", line 33, in start
    print("Authentication Error: %s" % e.message)
AttributeError: 'AuthError' object has no attribute 'message'
