### ISSUE TITLE
axolotl.sessioncipher error

### ISSUE THREAD

**Issue by matiasinsaurralde** [tgalal/yowsup#1625]
Any clue?

```
WARNING:axolotl.sessionbuilder:We've already setup a session for this V3 message, letting bundled message fall through...
WARNING:axolotl.sessioncipher:'utf-8' codec can't decode byte 0x9c in position 28: invalid start byte
```

At this point, I've tried regenerating keys, installing Yowsup from `master`, with no luck!
This error too:

```
DUMP:

abc
['\n', '\x03', 'a', 'b', 'c']
[10, 3, 97, 98, 99]
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1080, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1102, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/protobuf/internal/decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 270, in process
    self.startEcho()
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 308, in startEcho
    stack.start()
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/demos/echoclient/stack.py", line 21, in start
    self.stack.loop()
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/axolotl/layer_receive.py", line 88, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/axolotl/layer_receive.py", line 144, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "/usr/local/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/axolotl/layer_receive.py", line 171, in parseAndHandleMessageProto
    m.ParseFromString(serializedData)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1086, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
```

**Comment by parag** [comment]
Same as #1613 .  Facing similar issues.

**Comment by tgalal** [comment]
by https://github.com/tgalal/python-axolotl/pull/13
