### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0

### ISSUE THREAD

**Issue by relima** [tgalal/yowsup#1627]
Message 9B0B2AEF5CC9A9C7C8D2786CF7C222: Sent delivered receipt and Read
[connected]:
DUMP:
p
5511999XXXXXX-1XXXX39491@g.usO▒ĺ▒▒ '▒m~ST▒▒<▒0▒▒▒▒V▒'▒11ps▒▒C"!▒<▒x▒Q% |▒2▒i▒▒y^du(_2▒
xhttp://m.folha.uol.com.br/poder/2015/05/1632911-projetos-do-stf-criam-auxilios-do-berco-ao-caixao-para-magistrados.shtmlxhttp://m.folha.uol.com.br/poder/2015/05/1632911-projetos-do-stf-criam-auxilios-do-berco-ao-caixao-para-magistrados.shtml2kProjeto do STF cria auxílios do berço ao caixão para magistrados - 24/05/2015 - Poder - Folha de S.Paulo▒▒▒▒▒▒JFIF▒▒C
%-(0%()(▒▒C

(((((((((((((((((((((((((((((((((((((((((((((((((((▒rr"▒▒

▒▒▒}!1AQa"q2▒▒#B▒▒R▒▒$3br▒
%&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒

▒▒▒w!1AQaq"2B▒▒▒▒       #3R▒br▒
$4▒%▒&'()_56789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
?▒"▒w▒▒▒^=z
▒u^=z
▒u^=z
▒u^=z
▒u^=z
▒uP@▒N5▒U~hj)▒b▒▒@▒▒F▒_▒F▒X▒F▒▒>▒]▒[}.▒▒▒▒▒_}&▒▒▒▒▒_}&▒▒▒▒▒_}▒▒▒m▒▒▒<QP▒p(▒
e▒c^#▒I▒~$▒i▒▒w▒▒▒▒▒-Z▒GD▒c▒J▒▒+▒I▒^▒_▒^^▒~▒O▒%▒>|B▒t▒Ŀ▒
▒▒▒"[8]IUR      8▒WK▒>x▒[▒|-▒K▒fk▒3Px$▒▒Q▒▒▒▒▒▒▒▒Q▒▒7▒ma,▒y▒▒▒z▒۰▒▒c▒▒ٝ&▒▒▒m▒w▒▒▒͉Vlx▒▒▒▒4▒▒?-u˫▒▒▒w▒V▒G]Z"$y▒▒▒が▒J▒▒u▒7▒▒<▒▒e▒▒Q▒fk▒_p[▒@$
▒▒|W)▒/[-▒▒->T=▒▒▒▒}▒▒A^=▒xK▒\▒ւ▒^▒9▒nS▒4▒Z▒▒mA▒G▒to[▒_▒D-l▒▒?t▒▒r▒ף▒j▒\▒Pm:▒▒C▒)▒-▒#?)\▒▒ぞ▒G▒?▒▒▒l▒▒▒▒2?▒▒hʇ▒▒▒w▒h▒$:▒▒▒▒?3▒▒6c▒▒▒▒▒▒▒#▒v▒k▒^▒▒▒I▒▒▒YA.>e▒z▒▒▒p▒▒▒Y▒1▒k▒▒s▒   d▒▒{▒|U▒tT▒m4▒F▒▒B
▒Γ▒kݼ▒(▒_▒▒w▒▒▒9▒CM▒8▒▒U▒A▒P▒▒▒|▒▒I▒▒▒▒uOa:]▒▒I▒Pr<ȑ]▒▒ ▒▒▒`▒z▒M▒▒▒*▒
                                                                     x▒▒惪H▒▒▒Rb▒O▒▒2▒▒k▒▒@▒▒Q▒▒(▒"▒?&▒C▒l▒=▒?▒&▒▒*J▒R▒▒^▒G▒▒ ▒4▒-9,`▒nE▒׻]▒c)]▒x1▒'▒ G3▒▒w▒>
k67Vւ▒▒▒x#▒x▒▒M▒3▒▒▒j▒>K?x>▒b▒I▒W▒
DJ▒▒▒]O▒ox▒▒Z蚞▒▒Ka%▒▒▒q_▒▒ʁ▒/o▒▒Gqֻ_▒f▒▒~▒▒o▒Ƴ▒▒&*▒w▒#▒$P3▒▒▒▒eS▒rN▒▒▒▒▒▒▒huO▒fH▒▒b▒ռ▒P▒kվ▒>:▒s▒▒h▒▒▒▒▒▒▒▒P▒%V >▒▒ds֤▒W▒▒E▒M▒<]=▒Ʒ<▒I▒9%▒▒▒ܐ▒d▒{y▒▒۾>Dަ▒▒-}[▒▒Zdp▒▒▒▒▒[▒  ▒%l▒▒C▒_=▒B▒e▒?▒▒▒8▒t▒dC▒
H▒▒▒1▒~▒x▒G▒▒<_▒R▒M▒l▒4k▒t▒▒▒>a▒▒9▒Q▒d▒▒▒▒E▒~җ6w:E>▒▒▒▒7▒yV▒▒+{▒▒ŏ▒▒>▒s▒▒▒▒▒▒z▒Ǘ▒▒▒y▒Z▒O▒▒5_▒?▒▒J▒▒▒▒▒'▒▒▒v▒▒▒▒O▒▒▒7▒▒t▒ҭl!▒▒G&I▒gw
                                                   ▒v▒▒)\g<▒Ps▒▒P▒M▒7▒_N▒Ek▒   ؓ▒▒R▒▒W▒kVz▒▒)▒▒▒▒▒>▒&▒▒v▒vfg▒▒Yǯ▒B▒▒▒▒▒^▒▒tد>▒,▒▒▒▒|▒A,έ▒▒^k▒▒]A<-e▒mR▒-▒̺zރ▒▒v▒6▒▒@O▒"k▒n▒▒▒2ɖ▒▒n▒S▒\m|~*▒▒▒}▒▒k▒_▒▒▒▒z▒V▒eŹG▒▒▒▒o▒▒ӵ}▒▒2▒▒▒{QU▒▒T"▒M▒X▒&▒􀳾▒▒W}#▒d`▒T▒▒▒g▒-▒▒6▒O▒▒|▒▒c▒~▒6▒▒▒▒m▒▒g{wo0▒qu▒▒▒▒▒▒>▒▒.▒▒u[▒i|▒pFPz{▒nՌ+sI▒▒▒+)▒
▒j^▒+i۽▒▒>j8.c▒!$LpG▒▒▒▒▒▒ٽť▒Kdt▒2▒▒▒s}(kh▒#▒▒#▒▒&▒簯V▒▒▒▒+/▒▒▒>J▒j▒b▒pwk▒▒mv▒▒w▒▒▒▒j▒▒if`/▒ݮV.▒0▒I▒Ȫ▒▒w▒▒▒&▒z▒w▒▒r▒3▒▒▒▒9▒▒5▒▒▒b▒[▒=▒▒f:Ht@m▒,T▒▒I9▒▒G▒▒▒▒X▒
Z▒▒▒▒▒▒C{▒dxaF▒▒:▒▒y>գ▒▒,▒=U▒K▒▒/,▒(▒▒▒▒(▒"▒~M▒6        ▒} '▒K▒▒n▒▒@▒▒▒▒nnny▒F▒^A▒▒▒▒j~▒k▒l-▒▒
ID▒B▒▒▒ڍԡ▒(▒i_▒$▒\▒Z~/▒▒▒+▒▒t_6০}▒z<▒▒▒▒'۴▒▒#▒▒▒▒uh▒I+'▒▒▒A▒f▒▒▒br▒
F▒▒u▒f▒&▒J▒▒rO▒\▒▒▒{0▒5▒▒0Mk3Es ▒b▒5`▒I▒▒▒mԛ▒-▒n▒▒▒▒@▒O▒wR▒w{Ѻ▒&.▒j▒:▒▒
▒▒#▒#▒ou_T▒8▒\▒▒z▒▒▒h▒▒
ɰnsEt▒R_▒Y▒▒ͦ\4▒F▒J▒PH▒QE<▒▒@▒▒
▒(▒▒▒▒)Ҋ(01HP▒zR9▒▒P<Q▒▒▒P▒x▒▒▒/▒▒▒28▒*JAEP3▒▒
['\x12', 'p', '\n', '\x1d', '5', '5', '1', '1', '9', '9', '9', '2', '2', '9', '5', '8', '4', '-', '1', '4', '4', '2', '4', '3', '9', '4', '9', '1', '@', 'g', '.', 'u', 's', '\x12', 'O', '3', '\x08', '\x85', '\xc4', '\xba', '\xf0', '\x02', '\x10', '\xd2', '\x04', '\x1a', ' ', "'", '\x8a', 'm', '~', 'S', 'T', '\x8c', '\xc0', '<', '\x1b', '[', ':', '\xd0', '\xf1', '\xa5', '0', '\xbf', '\xb8', '\xac', '\xe9', 'V', '\xd3', "'", '\xdf', '1', '1', 'p', '\x13', 's', '\xcb', '\xf9', 'C', '"', '!', '\x05', '\x93', '<', '\xf9', 'x', '\xa8', '\x07', 'Q', '%', ' ', '|', '\xed', '\x14', '2', '\xfb', 'i', '\x80', '\x13', '\xf3', 'y', '^', '\x1d', 'b', '\x9b', '\xd6', '\xe8', '\xb0', 'j', '\r', 'd', 'u', '(', '_', '2', '\x98', '\x1a', '\n', 'x', 'h', 't', 't', 'p', ':', '/', '/', 'm', '.', 'f', 'o', 'l', 'h', 'a', '.', 'u', 'o', 'l', '.', 'c', 'o', 'm', '.', 'b', 'r', '/', 'p', 'o', 'd', 'e', 'r', '/', '2', '0', '1', '5', '/', '0', '5', '/', '1', '6', '3', '2', '9', '1', '1', '-', 'p', 'r', 'o', 'j', 'e', 't', 'o', 's', '-', 'd', 'o', '-', 's', 't', 'f', '-', 'c', 'r', 'i', 'a', 'm', '-', 'a', 'u', 'x', 'i', 'l', 'i', 'o', 's', '-', 'd', 'o', '-', 'b', 'e', 'r', 'c', 'o', '-', 'a', 'o', '-', 'c', 'a', 'i', 'x', 'a', 'o', '-', 'p', 'a', 'r', 'a', '-', 'm', 'a', 'g', 'i', 's', 't', 'r', 'a', 'd', 'o', 's', '.', 's', 'h', 't', 'm', 'l', '\x12', 'x', 'h', 't', 't', 'p', ':', '/', '/', 'm', '.', 'f', 'o', 'l', 'h', 'a', '.', 'u', 'o', 'l', '.', 'c', ...,  218, 50, 56, 245, 174, 162, 138, 42, 74, 65, 69, 20, 80, 51, 255, 217]
Traceback (most recent call last):
  File "./yowsup-cli", line 368, in <module>
    if not parser.process():
  File "./yowsup-cli", line 268, in process
    self.startCmdline()
  File "./yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/home/mestre/yowsup-2.5.0/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/home/mestre/yowsup-2.5.0/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/**init**.py", line 76, in toUpper
    self.**upper.receive(data)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/__init**.py", line 76, in toUpper
    self.**upper.receive(data)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/__init**.py", line 76, in toUpper
    self.**upper.receive(data)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/__init**.py", line 76, in toUpper
    self.**upper.receive(data)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/__init**.py", line 76, in toUpper
    self.**upper.receive(data)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/__init**.py", line 76, in toUpper
    self.**upper.receive(data)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/__init**.py", line 189, in receive
    s.receive(data)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/axolotl/layer_receive.py", line 88, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/axolotl/layer_receive.py", line 144, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "/home/mestre/yowsup-2.5.0/yowsup/layers/axolotl/layer_receive.py", line 171, in parseAndHandleMessageProto
    m.ParseFromString(serializedData)
  File "/home/mestre/.local/lib/python2.7/site-packages/google/protobuf/message.py", line 186, in ParseFromString
    self.MergeFromString(serialized)
  File "/home/mestre/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 859, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/home/mestre/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 892, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/home/mestre/.local/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 654, in DecodeField
    if value._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/home/mestre/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 892, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/home/mestre/.local/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 520, in DecodeField
    field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])
  File "/home/mestre/.local/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 487, in _ConvertToUnicode
    return local_unicode(byte_str, 'utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte in field: com.whatsapp.proto.UrlMessage.jpeg_thumbnail

**Comment by tgalal** [comment]
0acd440
