### ISSUE TITLE
[Offline message]through yowsup-cli 

### ISSUE THREAD

**Issue by sree0410** [tgalal/yowsup#1635]
Hi , 

i have registered my number through yowsup-cli with -E option at the end by reading through few other issues figured out -E option to be added while registering

i majorly doubt this option 

now wen i try to login with the login and credential obtained ,how do i change the password what i had obtained ? my password would be something like "SFExj4JUUHVHe9ec2yLBTJVlJtc=" do i have to further convert or anything , i am not using any config file i just use 

 ./yowsup-cli demos -y -l <login_num>:SFExj4JUUHVHe9ec2yLBTJVlJtc=

when i try regiserting again with the passcode i get a different password .so i wanted to know how can i set passwrd how can i validate the passwrd what i have set is correct

i get this error message 

general: Disconnected: Connection Closed

so could you please let me know what is the problem ?
i am using python version 2.6.5 , i have installed all the packages needed 

please help me .

**Comment by sree0410** [comment]
i get this debug traces


DEBUG:yowsup.layers.network.layer:Connecting to e1.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="919886372816" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
general: Disconnected: Connection Closed

when i give an option -M -E s40 to yowsup-cli 
Network layer connected is here ::Connecting to e1.whatsapp.net:443

when i give an option -E android to yowsup-cli
Nework layer is connected to :e13.whatsapp.net:443




when i give /seq option i get the following 
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="jabber:iq:privacy" type="get" id="1">
<query>
<list name="default">
</list>
</query>
</iq>

DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="urn:xmpp:whatsapp:push" type="get" id="2">
<config>
</config>
</iq>

DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w" type="get" id="3">
<props>
</props>
</iq>

DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="urn:xmpp:whatsapp:account" type="get" id="4">
<crypto action="create">
<google>
▒\▒
Q▒▒x▒TWp▒▒`▒H1,▒6▒▒▒KI▒4
HEX:fe5cf90c511fb899781bbed754577098e460d048312c8b36c11c91ca4b49ca34
</google>
</crypto>
</iq>




some one please help me , i am not understanding the traces,isthere any layer missing 

do i have to encode the password 
by doing this login pw=base64.b64decode(bytes(PASSWORD.encode('utf-8')))

**Comment by fjrmaulana** [comment]
how abouth this..?
d:\yowsup>python yowsup-cli demos -c C:\Users\FAJAR\.yowsup\62896242xxxxx\config -s 6289999xxxxx "Hola"
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "d:\yowsup\yowsup\demos\sendclient\stack.py", line 31, in start
    self.stack.loop()
  File "d:\yowsup\yowsup\stacks\yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 150, in poll
    read(obj)
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Users\FAJAR\AppData\Local\Programs\Python\Python35-32\lib\asyncore.py", line 423, in handle_read_ev
ent
    self.handle_read()
  File "d:\yowsup\yowsup\layers\network\layer.py", line 102, in handle_read
    self.receive(data)
  File "d:\yowsup\yowsup\layers\network\layer.py", line 110, in receive
    self.toUpper(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\stanzaregulator\layer.py", line 29, in receive
    self.processReceived()
  File "d:\yowsup\yowsup\layers\stanzaregulator\layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\auth\layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\axolotl\layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 194, in receive
    s.receive(data)
  File "d:\yowsup\yowsup\layers\axolotl\layer_receive.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "d:\yowsup\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 194, in receive
    s.receive(data)
  File "d:\yowsup\yowsup\layers\__init__.py", line 130, in receive
    recv(node)
  File "d:\yowsup\yowsup\layers\auth\layer_authentication.py", line 81, in handleFailure
    raise AuthError(nodeEntity.getReason())
yowsup.layers.auth.autherror.AuthError: not-authorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 272, in process
    self.startSendClient()
  File "yowsup-cli", line 324, in startSendClient
    stack.start()
  File "d:\yowsup\yowsup\demos\sendclient\stack.py", line 33, in start
    print("Authentication Error: %s" % e.message)
AttributeError: 'AuthError' object has no attribute 'message'
