### ISSUE TITLE
socket.error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by sree0410** [tgalal/yowsup#1637]
DEBUG:yowsup.layers.network.layer:Connecting to e12.whatsapp.net:443
Traceback (most recent call last):
  File "./yowsup-cli", line 368, in <module>
    if not parser.process():
  File "./yowsup-cli", line 268, in process
    self.startCmdline()
  File "./yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/home/rpy/yowsup-master/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/home/rpy/yowsup-master/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.6/asyncore.py", line 202, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.6/asyncore.py", line 143, in poll
    read(obj)
  File "/usr/lib/python2.6/asyncore.py", line 80, in read
    obj.handle_error()
  File "/usr/lib/python2.6/asyncore.py", line 76, in read
    obj.handle_read_event()
  File "/usr/lib/python2.6/asyncore.py", line 413, in handle_read_event
    self.handle_connect_event()
  File "/usr/lib/python2.6/asyncore.py", line 420, in handle_connect_event
    self.handle_connect()
  File "/home/rpy/yowsup-master/yowsup/layers/network/layer.py", line 82, in handle_connect
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/home/rpy/yowsup-master/yowsup/layers/__init__.py", line 89, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/rpy/yowsup-master/yowsup/layers/__init__.py", line 89, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/rpy/yowsup-master/yowsup/layers/__init__.py", line 83, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/home/rpy/yowsup-master/yowsup/layers/__init__.py", line 104, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/home/rpy/yowsup-master/yowsup/layers/coder/layer.py", line 26, in onConnected
    self.write(streamStartBytes.pop(0))
  File "/home/rpy/yowsup-master/yowsup/layers/coder/layer.py", line 41, in write
    self.toLower(bytearray([i]))
  File "/home/rpy/yowsup-master/yowsup/layers/__init__.py", line 80, in toLower
    self.__lower.send(data)
  File "/home/rpy/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 48, in send
    self.toLower(bytearray(data))
  File "/home/rpy/yowsup-master/yowsup/layers/__init__.py", line 80, in toLower
    self.__lower.send(data)
  File "/home/rpy/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 24, in send
    self.toLower(data)
  File "/home/rpy/yowsup-master/yowsup/layers/__init__.py", line 80, in toLower
    self.__lower.send(data)
  File "/home/rpy/yowsup-master/yowsup/layers/network/layer.py", line 107, in send
    self.initiate_send()
  File "/usr/lib/python2.6/asyncore.py", line 504, in initiate_send
    num_sent = dispatcher.send(self, self.out_buffer[:512])
  File "/usr/lib/python2.6/asyncore.py", line 352, in send
    result = self.socket.send(data)
socket.error: [Errno 32] Broken pipe

what does socket error mean ?what is missing here 
the command i used is 

./yowsup-cli demos -y -l <loginNum>:cVg1dWdBb1hhTHRJOVNGSStnVENQa2tZWmZnPQ== -d -e

this passoword is base64.b64encode(bytes(PW.encode('utf-8'))) where PW is the obtained pw during registration

am i missing any layer 
is it the right way to login 
please help

**Comment by jlguardi** [comment]
You should use:
```
-l phone:pass
```

Where pass I directly th one obtained while registering. 

Also, don't use -e without arguments (s40 or android)
