### ISSUE TITLE
Unexpected Exception Looping 

### ISSUE THREAD

**Issue by haxxorsid** [tgalal/yowsup#1644]
```
_server.py_ [INFO][2016-06-12 23:08:03,507] ##################################################
_server.py_ [INFO][2016-06-12 23:08:03,507]     Server started. Phone number: 919004094663
_server.py_ [INFO][2016-06-12 23:08:03,507] ##################################################
_server.py_ [ERROR][2016-06-12 23:08:03,507] Unexpected Exception: 
Traceback (most recent call last):
  File "src/server.py", line 38, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
error: (9, 'Bad file descriptor')
_server.py_ [INFO][2016-06-12 23:08:03,508] Restarting..
_server.py_ [INFO][2016-06-12 23:08:03,507] ##################################################
_server.py_ [INFO][2016-06-12 23:08:03,507]     Server started. Phone number: 919004094663
_server.py_ [INFO][2016-06-12 23:08:03,507] ##################################################
_server.py_ [ERROR][2016-06-12 23:08:03,507] Unexpected Exception: 
Traceback (most recent call last):
  File "src/server.py", line 38, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
error: (9, 'Bad file descriptor')
```

When I start server.py, after few minutes server.py restarts and continues to loop around by restarting till I don't stop server.py. It happens most of the times (frequently).

**Comment by sowerkoku** [comment]
@tgalal 
I have problems with the "echoclient"

```
yowsup-cli v2.0.15
Using yowsup v2.5.0
```


`./yowsup-cli demos -c bot.config -e `

error:

```
DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w:p" type="get" id="478">
</iq>


DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="xxxxxxxxx@s.whatsapp.net" id="478" t="1465968304">
</iq>

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w:p" type="get" id="479">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="xxxxxxxxx@s.whatsapp.net" id="479" t="1465968354">
</iq>

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w:p" type="get" id="480">
</iq>

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 2
DEBUG:yowsup.layers.protocol_iq.layer:stopping ping thread
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Ping Timeout
```
