### ISSUE TITLE
Error to send image using yowsup-cli - AttributeError: 'NoneType' object has no attribute 'getTag'

### ISSUE THREAD

**Issue by marcoarildo** [tgalal/yowsup#1666]
Hi, 

I am using  **python3 yowsup-cli demos -c config2 -x 5511999999999 brasil.jpeg**, but i got this error. 
Before i changed the **/yowsup/demos/mediaclient/stack.py**

self.stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())
to 
self.stack.setProp(YowCoderLayer.PROP_RESOURCE, YowsupEnv.getCurrent().getResource())

-- file body
import sys

from yowsup.stacks import YowStack, YOWSUP_CORE_LAYERS, YOWSUP_PROTOCOL_LAYERS_FULL
from yowsup.layers import YowLayerEvent
from yowsup.layers.auth import YowAuthenticationProtocolLayer, AuthError
from yowsup.layers.coder import YowCoderLayer
from yowsup.layers.network import YowNetworkLayer
from yowsup.common import YowConstants
from yowsup.env import YowsupEnv

from .layer import SendMediaLayer

class SendMediaStack(object):

```
def __init__(self, credentials, messages):
    layers = (SendMediaLayer,) + (YOWSUP_PROTOCOL_LAYERS_FULL,) + YOWSUP_CORE_LAYERS

    self.stack = YowStack(layers)
    self.stack.setProp(SendMediaLayer.PROP_MESSAGES, messages)
    self.stack.setProp(YowAuthenticationProtocolLayer.PROP_PASSIVE, True)
    self.stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, credentials)
    self.stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])
    self.stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
    #self.stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())
    self.stack.setProp(YowCoderLayer.PROP_RESOURCE, YowsupEnv.getCurrent().getResource())

def start(self):
    self.stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))
    try:
        self.stack.loop()
    except AuthError as e:
        print("Authentication Error: %s" % e.message)_
```

Now when I try execute **python3 yowsup-cli demos -c config2 -x 5511999999999 brasil.jpeg**
I have this error:

File "/u01/yowsup-marco/yowsup/demos/mediaclient/layer.py", line 30, in onSuccess
    self.main()
  File "/u01/yowsup-marco/yowsup/demos/mediaclient/layer.py", line 119, in main
    self._sendIq(entity, successFn, errorFn)
  File "/u01/yowsup-marco/yowsup/layers/interface/interface.py", line 41, in _sendIq
    assert iqEntity.getTag() == "iq", "Expected *IqProtocolEntity in _sendIq, got %s" % iqEntity.getTag()
AttributeError: 'NoneType' object has no attribute 'getTag'

Someone havy a idea ?

Hugs

**Comment by jlguardi** [comment]
Add debug log (-d) adn try also with python 2.7.

**Comment by marcoarildo** [comment]
@jlguardi Hi. tks for help me.

I did like you said me, but I have received the same error:

python3 yowsup-cli demos -d -c config2 -x 5511999999999 brasil.jpeg

-- result -- 
DEBUG:yowsup.env.env:registered env android => <class 'yowsup.env.env_android.AndroidYowsupEnv'>
DEBUG:yowsup.env.env:registered env s40 => <class 'yowsup.env.env_s40.S40YowsupEnv'>
DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer - call Layer - Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e1.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth user="5511985980503" mechanism="WAUTH-2" passive="true">
Ã¤ÂÃÃ
XHÃÃÂÃ¥Â£Qc]Â°3Â°ÂÃ¢K|Â¤Ã4)@cÃ·Ã
Ã¹ÃÃi_ÃÃ¹ÂÃ¬Ã ÃJ1ÂÃ«q||+ÃÃRÂÃ´9Ã$ÂÃ´Â´
HEX3:b'e4018ada071cc55848d9da80e5a351631d1c5db033b095e24b007ca4cc34294063f7c5f9c9db1e68695fc3f999ece006d14a3194eb717c217f7c2bc2d45299f439d0240795f4b4'
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<success expiration="4444444444" creation="1461785471" t="1467143123" props="5" status="active" kind="free">
Az.ÃºovÃuÃ¾Ã
            Â¨iÂ¯sÂ¿bÂ¢PÃÂ¸
HEX3:b'417a2efa6f76d175fec4a869af73bf62a250c9b8'
</success>

DEBUG:yowsup.layers.protocol_iq.layer:starting ping thread.
DEBUG:yowsup.demos.mediaclient.layer:Media not recognized
DEBUG:yowsup.layers.protocol_iq.layer:stopping ping thread
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Requested
DEBUG:yowsup.demos.mediaclient.layer:Send None in brasil.jpeg to 5511999999999@s.whatsapp.net
Traceback (most recent call last):
  File "yowsup-cli", line 330, in <module>
    if not parser.process():
  File "yowsup-cli", line 235, in process
    self.startMediaClient()
  File "yowsup-cli", line 300, in startMediaClient
    stack.start()
  File "/u01/yowsup-marco/yowsup/demos/mediaclient/stack.py", line 40, in start
    self.stack.loop()
  File "/u01/yowsup-marco/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/local/lib/python3.3/asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python3.3/asyncore.py", line 153, in poll
    read(obj)
  File "/usr/local/lib/python3.3/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/local/lib/python3.3/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/lib/python3.3/asyncore.py", line 441, in handle_read_event
    self.handle_read()
  File "/u01/yowsup-marco/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/u01/yowsup-marco/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/u01/yowsup-marco/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/u01/yowsup-marco/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/u01/yowsup-marco/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/u01/yowsup-marco/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/u01/yowsup-marco/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/u01/yowsup-marco/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/u01/yowsup-marco/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/u01/yowsup-marco/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/u01/yowsup-marco/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/u01/yowsup-marco/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/u01/yowsup-marco/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/u01/yowsup-marco/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/u01/yowsup-marco/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/u01/yowsup-marco/yowsup/layers/__init__.py", line 125, in receive
    recv(node)
  File "/u01/yowsup-marco/yowsup/layers/auth/layer_authentication.py", line 75, in handleSuccess
    self.toUpper(nodeEntity)
  File "/u01/yowsup-marco/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/u01/yowsup-marco/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/u01/yowsup-marco/yowsup/demos/mediaclient/layer.py", line 30, in onSuccess
    self.main()
  File "/u01/yowsup-marco/yowsup/demos/mediaclient/layer.py", line 119, in main
    self._sendIq(entity, successFn, errorFn)
  File "/u01/yowsup-marco/yowsup/layers/interface/interface.py", line 41, in _sendIq
    assert iqEntity.getTag() == "iq", "Expected *IqProtocolEntity in _sendIq, got %s" % iqEntity.getTag()
AttributeError: 'NoneType' object has no attribute 'getTag'

Do you have same example to open the conect com Whatsapp and star to send image ?

I have to finish the project but i have problem to send image only, and I have to send a 3000 msg between text and image.

Tks again.

**Comment by marcoarildo** [comment]
@jlguardi 

Sucess !!!

So, I removed all files and started again.
I did download python 2.7 again
I did download yowsup-master again
After this i got a lot of problem, but i see #555 again and did download those 7 files carrefully.

And by last we have problem with pillow and filemagic and then we installed again to version 2.7

We have problem with from_file() so i did this on /yowsup/common/tools.py

    @classmethod
    def fromMimeType(cls, path):
        return "image"
        """
        mimeType = magic.from_file(path, mime=True)

        if mimeType in MediaDiscover.MIME_TYPE_IMAGE:
            return "image"
        elif mimeType in MediaDiscover.MIME_TYPE_VIDEO:
            return "video"
        elif mimeType in MediaDiscover.MIME_TYPE_AUDIO:
            return "audio"

        return None
        """

I don´t know if exist another option to from_file() to python 2.7.

Tks again for help me @jlguardi !!!
