### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getAttributeValue'

### ISSUE THREAD

**Issue by anaganisk** [tgalal/yowsup#1669]
I'm getting this error on Python 2.7 when I receive 'media' type message @tgalal 

`C:\Python27\python.exe C:/Users/saiki/Desktop/yowsup/run.py
No handlers could be found for logger "yowsup.layers.axolotl.layer"
text
Traceback (most recent call last):
  File "C:/Users/saiki/Desktop/yowsup/run.py", line 33, in <module>
    stack.loop()
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\stacks\yowstack.py", line 195, in loop
    asyncore.loop(_args, *_kwargs)
  File "C:\Python27\lib\asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "C:\Python27\lib\asyncore.py", line 156, in poll
    read(obj)
  File "C:\Python27\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers\network\layer.py", line 88, in handle_read
    self.receive(data)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers\network\layer.py", line 96, in receive
    self.toUpper(data)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers__init__.py", line 75, in toUpper
    self.**upper.receive(data)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers\stanzaregulator\layer.py", line 29, in receive
    self.processReceived()
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers\stanzaregulator\layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers\auth\layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers\axolotl\layer.py", line 124, in receive
    self.onMessage(protocolTreeNode)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers\axolotl\layer.py", line 146, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers\axolotl\layer.py", line 231, in handleEncMessage
    self.handleWhisperMessage(node)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers\axolotl\layer.py", line 288, in handleWhisperMessage
    self.toUpper(node)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers__init**.py", line 75, in toUpper
    self.**upper.receive(data)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers__init**.py", line 188, in receive
    s.receive(data)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers__init__.py", line 124, in receive
    recv(node)
  File "C:\Python27\lib\site-packages\yowsup2-2.4.103-py2.7.egg\yowsup\layers\protocol_media\layer.py", line 40, in recvMessageStanza
    if mediaNode.getAttributeValue("type") == "image":
AttributeError: 'NoneType' object has no attribute 'getAttributeValue'

Process finished with exit code 1`

**Comment by rami-dabain** [comment]
Change that line to:
    if mediaNode == null:
        return
    if mediaNode.getAttributeValue("type") == "image":
