### ISSUE TITLE
NameError: global name 'YowsupEnv' is not defined

### ISSUE THREAD

**Issue by b4zz4** [tgalal/yowsup#1672]
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup/env/env.py", line 15, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/lib/python2.7/dist-packages/yowsup/env/env.py", line 12, in __init__
    YowsupEnv.registerEnv(cls)
NameError: global name 'YowsupEnv' is not defined

**Comment by carlosen14** [comment]
How did you solve it?

**Comment by jlguardi** [comment]
@CarlosV reinstall current master of yowsup or the latest release.
'''
sudo python setup.py install
'''

**Comment by carlosen14** [comment]
solved. I first installed using `python3`, and for the execution i was using `python` only (Python2.X), my bad..
