### ISSUE TITLE
Cant send Videos.. May wrong ffvideo Version?

### ISSUE THREAD

**Issue by TheJens90** [tgalal/yowsup#1673]
Hey guys. If i'll send a video, i get this error:

`_media_sender.py_       [INFO][2016-07-02 17:54:14,816] [Upload progress]3a23afcfef08bfae95f19691df221e25.mp4 => 49************@s.whatsapp.net, 100%
_optionalmodules.py_    [ERROR][2016-07-02 17:54:14,832] ffvideo import failed
_mediauploader.py_      [ERROR][2016-07-02 17:54:14,832] Error occured at transfer type object 'DownloadableMediaMessageProtocolEntity' has no attribute 'fromFilePath'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_media/mediauploader.py", line 138, in run
    self.successCallback(sourcePath, self.jid, result["url"])
  File "/home/whatsapp/src/utils/media_sender.py", line 91, in <lambda>
    caption)
  File "/home/whatsapp/src/utils/media_sender.py", line 105, in _do_send_file
    entity = VideoDownloadableMediaMessageProtocolEntity.fromFilePath(file_path, url, self.MEDIA_TYPE, ip, to)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_video.py", line 134, in fromFilePath
    entity = DownloadableMediaMessageProtocolEntity.fromFilePath(path, url, DownloadableMediaMessageProtocolEntity.MEDIA_TYPE_VIDEO, ip, to, mimeType, preview)
AttributeError: type object 'DownloadableMediaMessageProtocolEntity' has no attribute 'fromFilePath'
`

I used `pip install ffvideo` but still get this Message.

**Comment by jlguardi** [comment]
Now, DownloadableMadia use fromBuilder() functions instead. So we need to adapt https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_video.py to something like https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_image.py

**Comment by Dargmuesli** [comment]
If I'm not wrong @tanquetav did so in pull request #1564. But this one is open since 2 May...

**Comment by joelunmsm2003** [comment]
please help :) 

ERROR:yowsup.common.optionalmodules:ffvideo import failedpp.net, 1% 
ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer type object 'DownloadableMediaMessageProtocolEntity' has no attribute 'fromFilePath'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/mediauploader.py", line 138, in run
    self.successCallback(sourcePath, self.jid, result["url"])
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/demos/cli/layer.py", line 558, in <lambda>
    successFn = lambda filePath, jid, url: self.doSendMedia(mediaType, filePath, url, jid, resultRequestUploadIqProtocolEntity.getIp(), caption)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/demos/cli/layer.py", line 544, in doSendMedia
    entity = VideoDownloadableMediaMessageProtocolEntity.fromFilePath(filePath, url, ip, to, caption = caption)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_video.py", line 134, in fromFilePath
    entity = DownloadableMediaMessageProtocolEntity.fromFilePath(path, url, DownloadableMediaMessageProtocolEntity.MEDIA_TYPE_VIDEO, ip, to, mimeType, preview)
AttributeError: type object 'DownloadableMediaMessageProtocolEntity' has no attribute 'fromFilePath'
ERROR:yowsup.demos.cli.layer:Upload file /home/andy/Escritorio/video.mp4 to https://mmi499.whatsapp.net/u/4FB-M6k1g9d4XDSQDpFiI1XDrOYABUSIpMxcMw/Ag5XlASJaESK6EE5FLKI8Hfi5vhMlgkduwWQUzqUkGOx for 51xxxxxxxxx@s.whatsapp.net failed!

**Comment by Dargmuesli** [comment]
Please read "[BottomNews: Errors](https://github.com/Dargmuesli/bottomnews#errors)" and look at the changed code.

**Comment by joelunmsm2003** [comment]
this worked , thanx !!
