### ISSUE TITLE
Adding yowsup-cli to sudoers

### ISSUE THREAD

**Issue by bredmich** [tgalal/yowsup#1685]
Hi there,

i´m trying to add the yowsup-cli to sudoers as i want to execute it from another application.
This application can´t enter a password for the sudo command.

I tried to add yowsup-cli to sudoers:
pi ALL=(ALL) NOPASSWD: /usr/local/bin/yowsup-cli

When i try to execute i get the following error:
```
pi@HER-MB-OpenHab:/ $ yowsup-cli demos -s XXX "Test" -c config.yowsup
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2888, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 758, in subscribe
    callback(dist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2888, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2425, in activate
    for pkg in self._get_metadata('namespace_packages.txt'):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2415, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1413, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1405, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1514, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0b3-py2.7.egg/EGG-INFO/namespace_packages.txt'
```

Cheers
Michael

**Comment by sowerkoku** [comment]
drwxr-sr-x  2 root staff protobuf
--------^---------------^-------------- 
possibly this is your problem

**Comment by bredmich** [comment]
Where do i find this "protobuf" ?

**Comment by sowerkoku** [comment]
/usr/local/lib/python2.7/dist-packages/

**Comment by bredmich** [comment]
I got the problem.
I added the user permission to sudoers but tried to call yowsup-cli without sudo ...
```
yowsup-cli demos -s XXX "Test" -c config.yowsup
```
should be
```
sudo yowsup-cli demos -s XXX "Test" -c config.yowsup
```

Cheers
Michael

**Comment by sowerkoku** [comment]
sudo is not necessary to occupy

**Comment by bredmich** [comment]
But it's working with sudo :-)

**Comment by arthahir** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.2', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/yowsup/env/env.py", line 15, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python2.7/abc.py", line 87, in __new__
    cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
root@BBLPT0825:~/yowsup-2.5.2# 


got the same problem and tried to resolve with above solution still not working.can u pls help on this
