### ISSUE TITLE
Send Video Error

### ISSUE THREAD

**Issue by GabrielHenriqueGz** [tgalal/yowsup#1688]
ERROR:yowsup.common.optionalmodules:ffvideo import failed
ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer type object 'DownloadableMediaMessageProtocolEntity' has no attribute 'fromFilePath'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/mediauploader.py", line 138, in run
    self.successCallback(sourcePath, self.jid, result["url"])
  File "/home/pi/Desktop/Projeto3/yowCli/layer.py", line 265, in <lambda>
    successFn = lambda filePath, jid, url: self.doSendMedia(mediaType, filePath, url, jid, resultRequestUploadIqProtocolEntity.getIp(), caption)
  File "/home/pi/Desktop/Projeto3/yowCli/layer.py", line 251, in doSendMedia
    entity = VideoDownloadableMediaMessageProtocolEntity.fromFilePath(filePath, url, ip, to, caption = caption)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_video.py", line 134, in fromFilePath
    entity = DownloadableMediaMessageProtocolEntity.fromFilePath(path, url, DownloadableMediaMessageProtocolEntity.MEDIA_TYPE_VIDEO, ip, to, mimeType, preview)
AttributeError: type object 'DownloadableMediaMessageProtocolEntity' has no attribute 'fromFilePath'
ERROR:layer:Upload file /home/pi/Desktop/Projeto3/videos/video.avi to https://mmi478.whatsapp.net/u/o8DiDg86ruOU9kNCf3v6nf5es8sABTdMTAqVWA/AokDljlXhMDs2gjTHXPgQb3JqeBDAg66l_sHB26LmBBh for 5516993955824@s.whatsapp.net failed!

Please Help!
Thanks!

**Comment by Dargmuesli** [comment]
1. Remove your phone number from the previous post
2. Did you fix it? And if how?
