### ISSUE TITLE
Send Video Error yowsup

### ISSUE THREAD

**Issue by GabrielHenriqueGz** [tgalal/yowsup#1689]
ERROR:yowsup.common.optionalmodules:ffvideo import failed
ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer type object 'DownloadableMediaMessageProtocolEntity' has no attribute 'fromFilePath'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/mediauploader.py", line 138, in run
    self.successCallback(sourcePath, self.jid, result["url"])
  File "/home/pi/Desktop/Projeto3/yowCli/layer.py", line 265, in <lambda>
    successFn = lambda filePath, jid, url: self.doSendMedia(mediaType, filePath, url, jid, resultRequestUploadIqProtocolEntity.getIp(), caption)
  File "/home/pi/Desktop/Projeto3/yowCli/layer.py", line 251, in doSendMedia
    entity = VideoDownloadableMediaMessageProtocolEntity.fromFilePath(filePath, url, ip, to, caption = caption)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_video.py", line 134, in fromFilePath
    entity = DownloadableMediaMessageProtocolEntity.fromFilePath(path, url, DownloadableMediaMessageProtocolEntity.MEDIA_TYPE_VIDEO, ip, to, mimeType, preview)
AttributeError: type object 'DownloadableMediaMessageProtocolEntity' has no attribute 'fromFilePath'
ERROR:layer:Upload file /home/pi/Desktop/Projeto3/videos/video.avi to https://mmi478.whatsapp.net/u/o8DiDg86ruOU9kNCf3v6nf5es8sABTdMTAqVWA/AokDljlXhMDs2gjTHXPgQb3JqeBDAg66l_sHB26LmBBh for XXMYNUMBER@s.whatsapp.net failed!

Please Help!

**Comment by GabrielHenriqueGz** [comment]
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-y9gXBT/ffvideo/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-SMHZg9-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-y9gXBT/ffvideo
Storing debug log for failure in /root/.pip/pip.log

**Comment by jlguardi** [comment]
Remove from setup.py ffvideo dependency and try again.

**Comment by GabrielHenriqueGz** [comment]
How to make this ?
This: "error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1"  it happens when i try to install ffvideo package.
Sorry. I'm python beginner.

**Comment by Dargmuesli** [comment]
This is the same issues as #1662.
I got the same error message too. On my Raspberry Pi 2b (Jessie) I **cannot** `sudo pip install ffvideo` successfully. It outputs some lines saying

`ffvideo/ffvideo.c:[...]:[...]: error: 'struct AVStream' has no member named 'r_frame_rate'`

Somehow it has to do with both, yowsup and ffvideo itself. Did you find a solution? Or do you think if I get ffvideo installed it will work? Because nevertheless *DownloadableMediaMessageProtocolEntity* has no `.fromFilePath` ...

**Comment by Dargmuesli** [comment]
Ok, one hour later: I got it now. It is indeed **2 seperate issues**.

## First

**fromFilePath** was not updated with 0f181795bab2a65f3472159e74cbd07d908326f6 by @tgalal in `message_media_downloadable_audio.py` and `message_media_downloadable_video.py` accordingly. @tanquetav did so in pull request #1564.
I'll try to get an own fork of it running as the pr is open since 2 May 2k16 ...

## Second

**FFVideo's** newest version is currently `0.0.13` which is from *2013-02-24* so it's extremely incurrent. What worked for me was editing `FFVideo.c` and replacing all `r_frame_rate` with `avg_frame_rate`. Then it was no problem for me installing it via `sudo python setup.py install`! Though **yowsup** still tells me that there was an error importing FFVideo... I'll investigate.

For both problems I will add a reference to an easy fix tomorrow.

**Comment by Dargmuesli** [comment]
Here are the fixes:

## First

GitHub repository   [Dargmuesli/yowsup-mediafix](https://github.com/Dargmuesli/yowsup-mediafix).
Contains the original `yowsup source` + `builder support for audio and video upload`!

## Second

BitBucket repository [Dargmuesli/FFVideo](https://bitbucket.org/Dargmuesli/ffvideo).
Contains the original `FFVideo source` + `r_frame_rate-fix`!

You can download and install them as usual with `sudo python setup.py install`.

**Comment by Dargmuesli** [comment]
If - for some reason - **importlib**'s *import_module* does not work and you still get the same import error, change `yowsup/common/tools.py` to the following:

```
from ffvideo import VideoStream
```
```
class VideoTools:
    @staticmethod
    def getVideoProperties(videoFile):
        # with FFVideoOptionalModule() as imp:
        # VideoStream = imp("VideoStream")
        s = VideoStream(videoFile)
        return s.width, s.height, s.bitrate, s.duration #, s.codec_name

    @staticmethod
    def generatePreviewFromVideo(videoFile):
        #with FFVideoOptionalModule() as imp:
        #VideoStream = imp("VideoStream")
        fd, path = tempfile.mkstemp('.jpg')
        stream = VideoStream(videoFile)
        stream.get_frame_at_sec(0).image().save(path)
        preview = ImageTools.generatePreviewFromImage(path)
        os.remove(path)
        return preview
```

But note that captions for videos are currently not send.
