### ISSUE TITLE
Yowsup crash when try to decode Unicode string

### ISSUE THREAD

**Issue by minhlt9196** [tgalal/yowsup#1719]
Dear develop Team .
I got this problem with yowsup "UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 4: ordinal not in range(128)" when issued this command: "./yowsup-cli demos --config yowsup.conf -y"
I've try to update the newest version of yowsup but it won't work...
Could anybody help me resolve this bug ? Here is the traceback

Traceback (most recent call last):
  File "./yowsup-cli", line 368, in <module>
    if not parser.process():
  File "./yowsup-cli", line 268, in process
    self.startCmdline()
  File "./yowsup-cli", line 297, in startCmdline
    stack.start()
  File "./yowsup-master/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "./yowsup-master/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/local/python-2.7/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/local/python-2.7/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/local/python-2.7/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/local/python-2.7/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/python-2.7/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "./yowsup-master/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "./yowsup-master/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "./yowsup-master/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "./yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "./yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "./yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "./yowsup-master/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "./yowsup-master/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "./yowsup-master/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "./yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "./yowsup-master/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "./yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "./yowsup-master/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "./yowsup-master/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "./yowsup-master/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "./yowsup-master/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "./yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "./yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "./yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 86, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "./yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 129, in handlePreKeyWhisperMessage
    self.parseAndHandleMessageProto(pkMessageProtocolEntity, plaintext[:-padding])
  File "./yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 188, in parseAndHandleMessageProto
    self.handleConversationMessage(node, m.conversation)
  File "./yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 217, in handleConversationMessage
    self.toUpper(messageNode)
  File "./yowsup-master/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "./yowsup-master/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "./yowsup-master/yowsup/layers/__init__.py", line 125, in receive
    recv(node)
  File "./yowsup-master/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
    self.toUpper(entity)
  File "./yowsup-master/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "./yowsup-master/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "./yowsup-master/yowsup/demos/cli/layer.py", line 512, in onMessage
    MESSAGE_ID = message.getId()
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 4: ordinal not in range(128)

**Comment by sowerkoku** [comment]
[read here](https://github.com/tgalal/yowsup/issues/1646#issuecomment-229545988)
