### ISSUE TITLE
HTTPSConnection request behind proxy fails 

### ISSUE THREAD

**Issue by akeskimo** [tgalal/yowsup#1731]
I have recently installed Yowsup and I am trying to register to use the Whatsapp service on my work PC, but I cannot get pass the initial connection request (nor get a response from the server). I am on company network that has proxy, I have set the corresponding proxy server URLs in my environment variables.

For some reason, the Yowsup does not retrieve the http_proxy / https_proxy settings and the HttpProxy is not instantiated at all. Any help on this matter or advice on debugging on how to get through the initial connection request would be greatly appreciated.

I am using Python version 2.7.9.

C:\>python yowsup-cli registration -r sms -p 35840XXXXXX -C 358 -d
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.16.7 S40Version/14.26 Device/Nokia-302'}
DEBUG:yowsup.common.http.warequest:cc=358&in=40XXXXXXX&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6&network_radio_type=1&simnum=1&s
=&copiedrc=1&hasinrc=1&rcmatch=1&pid=6840&rchash=...
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=358&in=40XXXXXXX&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&mcc=000&mnc=000&method=sms&mistyped=6
&network_radio_type=1&simnum=1&s=&copiedrc=1&hasinrc=1&rcmatch=1&pid=6840&rchash=e...
Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 189, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup-cli", line 208, in handleRequestCode
    result = codeReq.send()
  File "D:\userdata\user\PycharmProjects\sanbox\Yowsup\yowsup\yowsup\registration\coderequest.py", line 62, in send
    res = super(WACodeRequest, self).send(parser)
  File "D:\userdata\user\PycharmProjects\sanbox\Yowsup\yowsup\yowsup\common\http\warequest.py", line 70, in send
    return self.sendGetRequest(parser)
  File "D:\userdata\user\PycharmProjects\sanbox\Yowsup\yowsup\yowsup\common\http\warequest.py", line 108, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET")
  File "D:\userdata\user\PycharmProjects\sanbox\Yowsup\yowsup\yowsup\common\http\warequest.py", line 163, in sendRequest
    conn.request(reqType, path, params, headers);
  File "C:\Localdata\Python2_7_8\Lib\httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "C:\Localdata\Python2_7_8\Lib\httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "C:\Localdata\Python2_7_8\Lib\httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "C:\Localdata\Python2_7_8\Lib\httplib.py", line 850, in _send_output
    self.send(msg)
  File "C:\Localdata\Python2_7_8\Lib\httplib.py", line 812, in send
    self.connect()
  File "C:\Localdata\Python2_7_8\Lib\httplib.py", line 1208, in connect
    HTTPConnection.connect(self)
  File "C:\Localdata\Python2_7_8\Lib\httplib.py", line 793, in connect
    self.timeout, self.source_address)
  File "C:\Localdata\Python2_7_8\Lib\socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection f
ailed because connected host has failed to respond

C:\>echo %http_proxy%
http://XXX.XXX.XXX.XXX:8080

C:\>echo %https_proxy%
http://XXX.XXX.XXX.XXX:8080

**Comment by DagoW** [comment]
Hi akeskimo,
from my own experience (as of Feb2017), the registration does not work via an http-proxy.
But once you have registered, via a direct connection, sending and receiving messages
works fine via the proxy.
I did not look at the code the see if this makes sense, so it would be nice if one of the
developers could confirm or correct.

BTW, I run yowsup on Linux, but I don't think this should matter.

**Comment by DagoW** [comment]
I just found that issue https://github.com/tgalal/yowsup/issues/912 mentions the same.
Maybe you can make sense of the code shown there.
