### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by yofux** [tgalal/yowsup#1733]
Hey everyone,

I installed yowsup today, everything went fine. I've received the SMS and got the password. Then I tried to send a message:

`yowsup-cli demos -d -s 491615578243 "hello" -l 4915188888836:b'646TWdHCaHLtXvQrlAK33WSLRHs=' `

and received this error:

yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/usr/lib/python3.4/site-packages/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python3.4/asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python3.4/asyncore.py", line 153, in poll
    read(obj)
  File "/usr/lib64/python3.4/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib64/python3.4/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python3.4/asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3.4/site-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/lib/python3.4/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/axolotl/layer_receive.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 125, in receive
    recv(node)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/auth/layer_authentication.py", line 81, in handleFailure
    raise AuthError(nodeEntity.getReason())
yowsup.layers.auth.autherror.AuthError: not-authorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/bin/yowsup-cli", line 324, in startSendClient
    stack.start()
  File "/usr/lib/python3.4/site-packages/yowsup/demos/sendclient/stack.py", line 33, in start
    print("Authentication Error: %s" % e.message)
AttributeError: 'AuthError' object has no attribute 'message'
foxey@linux-csqw:~> yowsup-cli demos -s -d 491615578243 "hello" -l 4915188888836:b'646TWdHCaHLtXvQrlAK33WSLRHs='    
usage: demos [-h] [-v] [-d] [--help-config] [-l phone:b64password | -c CONFIG]
             [-E {android,s40}] [-M] [-y] [-e] [-s phone message]
             [-S contacts]
demos: error: argument -s/--send: expected 2 arguments
foxey@linux-csqw:~> yowsup-cli demos -d -s 491602478243 "hello" -l 4915115788836:b'646EXdHAsHLtXvQrlAK33WSLRHs='    
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f87fcc7edd8>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f8800e493c8>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e4.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="4915115788836" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
§6ç¾Gge¼ºÕ
HEX3:b'1692fe18ba2e476765bcba1dd50da79536e7be87'
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
²(Ú6YK¶!°òÚ*£&ïMºßJÏ
                    ²Çb(. PËëà¥;È7²øÉìî
                                       æéN]j)ýV[7í~Ò
HEX3:b'b228da36594b0fb621b0f217da882a1ca3269c11ef4d8c81badf4acf0c90b2c78e62282e90a050cbebe08710a53bc837b2f8c9ecee8e0ce6e9174e5d6a848429fd565b37ed7ed2'
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/usr/lib/python3.4/site-packages/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python3.4/asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python3.4/asyncore.py", line 153, in poll
    read(obj)
  File "/usr/lib64/python3.4/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib64/python3.4/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python3.4/asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3.4/site-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/lib/python3.4/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/axolotl/layer_receive.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 125, in receive
    recv(node)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/auth/layer_authentication.py", line 81, in handleFailure
    raise AuthError(nodeEntity.getReason())
yowsup.layers.auth.autherror.AuthError: not-authorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/bin/yowsup-cli", line 324, in startSendClient
    stack.start()
  File "/usr/lib/python3.4/site-packages/yowsup/demos/sendclient/stack.py", line 33, in start
    print("Authentication Error: %s" % e.message)
AttributeError: 'AuthError' object has no attribute 'message'

Does that mean that I am already banned? 
Are those quotation marks in the password a problem for yowsup?

Thanks for your help!!!

**Comment by jlguardi** [comment]
Don't set the "b'" in the command line.

**Comment by yofux** [comment]
Sorry guys, its working now, what a silly mistake :-(

**Comment by althafas** [comment]
what was the fix ?
