### ISSUE TITLE
Error on sending simple message

### ISSUE THREAD

**Issue by Dinizzzka** [tgalal/yowsup#1774]
Hello. 
I registered via yowsup-cli, got a password from Whatsapp API and now I would like to send messages. I typed in terminal command
sudo yowsup-cli demos -l "my phone":"my whatsapp password"  -s "receiver's phone" "Hello, this is test message from watsapp cli!"

And got an error:

INFO:yowsup.layers.axolotl.layer_control:Axolotl layer is generating keys
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    **import**('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 324, in startSendClient
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/**init**.py", line 76, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init**.py", line 76, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init**.py", line 76, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init**.py", line 76, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init**.py", line 76, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init**.py", line 76, in toUpper
    self.**upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init**.py", line 189, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/layer_send.py", line 64, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/**init**.py", line 156, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/layer_base.py", line 65, in onSuccess
    sessionBuilder.processPreKeyBundle(preKeyBundle)
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.35-py2.7.egg/axolotl/sessionbuilder.py", line 166, in processPreKeyBundle
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 19, in getIdentityKeyPair
    return self.identityKeyStore.getIdentityKeyPair()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/store/sqlite/liteidentitykeystore.py", line 30, in getIdentityKeyPair
    publicKey, privateKey = result
TypeError: 'NoneType' object is not iterable

**Comment by jlguardi** [comment]
First start cli in command line mode: yowsup-cli demos -y -d ...
Login and try to get destination number info‎. Probably you are using an incorrect jid (you missed some digit) or the recipient isn't registered in whatsapp.

**Comment by hypertech** [comment]
Hi, @jlguardi.

So you can login to whatsapp with yowsup with no issues ?

**Comment by jlguardi** [comment]
@hypertech Yes, I use S40 env from master.
As you can see, Dinizzzka too. He has just a keys error.

**Comment by lambasoft** [comment]
I'm having similar issue.
I register a phone number successfully, obtain the login and password.

Then when I proceed to send a message using the client, I login first using /L then do a /message send.
As soon as I do this, a message is sent and received on my phone, but I get an error: 
```
DEBUG:yowsup.layers.logger.layer:rx:
<stream:error>
<system-shutdown>
</system-shutdown>
</stream:error>

Auth Error, reason Unhandled stream:error node:
<stream:error>
<system-shutdown>
</system-shutdown>
</stream:error>
```

and the api stops working on my number.

any help ?

**Comment by Dinizzzka** [comment]
Thanks for fast response. Unfortunately I still could not send simple message. I type the command:

sudo yowsup-cli demos -y -d -E s40 -l "my phone":"my whatsapp password"  -s "receiver phone" "Hello! Test message from watsapp cli"
[sudo] password for denis: 
DEBUG:yowsup.env.env:Current env changed to s40 
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f667a02b290>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f667a0899d0>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:

Also I'm confused that when I press Ctrl+C and exited from client I could not type anything in terminal. Please look at the attached screenshot.
![terminal_broken](https://cloud.githubusercontent.com/assets/22413965/18827139/e67ec30a-83d9-11e6-8674-b2a669038dcb.png)

Message was not sent. Please help me to solve the problem.

**Comment by rodrigolopezguerra** [comment]
Hi , from what i see , you are OFFLINE. You need to get ONLINE. (/L). Probably you're mixing up ONLINE/OFFLINE concept with AVAILABLE/UNAVAILABLE. After /L you can check the -y client in order to use the send message cmd. Hope it helps!

**Comment by sidnet03** [comment]
Type reset to get the commandline back after yowsup crashes
