### ISSUE TITLE
python3 venv - Exception: expecting STREAM_START in streamStart, instead got token: failure

### ISSUE THREAD

**Issue by peletiah** [tgalal/yowsup#1784]
yowsup2 does not appear to work under python3 at the moment:

I've created a fresh virtualenv:

```
python3 -m venv env_python3
cd env_python3
bin/pip install yowsup2
bin/yowsup-cli demos -d --login 4915XXXXXXXX:LvdlXXXXXXX+XXXXXX649a4= -s 43680XXXXXXX6 'Testasdfsdaf'
[..]
Exception: expecting STREAM_START in streamStart, instead got token: failure
```

Here's the full debug output:

```
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7fcdbcd76320>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7fcdbed2c828>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e10.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth user="4915XXXXXXXX" mechanism="WAUTH-2" passive="true">
¸gHÎiÂ\2ð¹ÿ FzW õla"ÿ·ê¹}·ø`[!âeò%ÿÐðõJ*
HEX3:b'd28c62ce69c25c9932f09db9ffa0467a1e57a0f56c1d6122ffb7eab97db7f8470d8e89ba6d8d87b867489260805b21e29565f2842503ec32e16fbcc2691220ff18d0f0f54a2a82'
</auth>

Traceback (most recent call last):
  File "bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "bin/yowsup-cli", line 272, in process
    self.startSendClient()
  File "bin/yowsup-cli", line 324, in startSendClient
    stack.start()
  File "/home/benke/env_python3/lib/python3.4/site-packages/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/home/benke/env_python3/lib/python3.4/site-packages/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.4/asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.4/asyncore.py", line 153, in poll
    read(obj)
  File "/usr/lib/python3.4/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.4/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.4/asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "/home/benke/env_python3/lib/python3.4/site-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/home/benke/env_python3/lib/python3.4/site-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/benke/env_python3/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/benke/env_python3/lib/python3.4/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/benke/env_python3/lib/python3.4/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/benke/env_python3/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/benke/env_python3/lib/python3.4/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/benke/env_python3/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/benke/env_python3/lib/python3.4/site-packages/yowsup/layers/coder/layer.py", line 33, in receive
    node = self.reader.getProtocolTreeNode(data)
  File "/home/benke/env_python3/lib/python3.4/site-packages/yowsup/layers/coder/decoder.py", line 15, in getProtocolTreeNode
    return self.streamStart(data)
  File "/home/benke/env_python3/lib/python3.4/site-packages/yowsup/layers/coder/decoder.py", line 46, in streamStart
    raise Exception("expecting STREAM_START in streamStart, instead got token: %s" % token)
Exception: expecting STREAM_START in streamStart, instead got token: failure
```

**Comment by ricardojlrufino** [comment]
Yes, it's working

See my comment:
https://github.com/tgalal/yowsup/issues/1613#issuecomment-251235093
