### ISSUE TITLE
sqlite3.OperationalError: attempt to write a readonly database

### ISSUE THREAD

**Issue by BetaUliansyah** [tgalal/yowsup#1794]
Hi,

i have installed yowsup in Ubuntu 16.04. But it has to be run by root to run. It was flawlessly run if started with root. But get error when I started the script with regular user.

`sudo yowsup-cli demos --yowsup --login phone:passwd`
works oke

`yowsup-cli demos --yowsup --login phone:passwd`
raised error:

```
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
Auth: Logged in!
[connected]:Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 268, in process
    self.startCmdline()
  File "yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/home/beta/wa/new/yowsup/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/home/beta/wa/new/yowsup/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/beta/wa/new/yowsup/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/home/beta/wa/new/yowsup/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/beta/wa/new/yowsup/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/beta/wa/new/yowsup/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/beta/wa/new/yowsup/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/beta/wa/new/yowsup/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/beta/wa/new/yowsup/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/beta/wa/new/yowsup/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/beta/wa/new/yowsup/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/beta/wa/new/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/beta/wa/new/yowsup/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/beta/wa/new/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/beta/wa/new/yowsup/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/beta/wa/new/yowsup/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/home/beta/wa/new/yowsup/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/beta/wa/new/yowsup/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/home/beta/wa/new/yowsup/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "/home/beta/wa/new/yowsup/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/beta/wa/new/yowsup/yowsup/layers/axolotl/layer_receive.py", line 88, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/home/beta/wa/new/yowsup/yowsup/layers/axolotl/layer_receive.py", line 139, in handleWhisperMessage
    plaintext = sessionCipher.decryptMsg(whisperMessage)
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.35-py2.7.egg/axolotl/sessioncipher.py", line 86, in decryptMsg
  File "/home/beta/wa/new/yowsup/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 55, in storeSession
    self.sessionStore.storeSession(recepientId, deviceId, sessionRecord)
  File "/home/beta/wa/new/yowsup/yowsup/layers/axolotl/store/sqlite/litesessionstore.py", line 35, in storeSession
    self.deleteSession(recipientId, deviceId)
  File "/home/beta/wa/new/yowsup/yowsup/layers/axolotl/store/sqlite/litesessionstore.py", line 53, in deleteSession
    self.dbConn.cursor().execute(q, (recipientId, deviceId))
sqlite3.OperationalError: attempt to write a readonly database


```

**Comment by jlguardi** [comment]
Change yowsup files owner and don't use sudo to start yowsup again:

'''
sudo ‎chown -R $USER:$USER $HOME/.yowsup
'''

**Comment by BetaUliansyah** [comment]
works fine, problem solved after following @jlguardi suggestion above. I'm closing the issue.
Thanks a lot!
