### ISSUE TITLE
Two Problems

### ISSUE THREAD

**Issue by AlkindiX** [tgalal/yowsup#1807]
## 1 - When I type `yowsup-cli demos -M -e -c yu.config` , it shows

```
Traceback (most recent call last):
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 746, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(code, namespace, namespace)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 270, in process
    self.startEcho()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 308, in startEcho
    stack.start()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/demos/echoclient/stack.py", line 21, in start
    self.stack.loop()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.5/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.5/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib/python3.5/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 125, in receive
    recv(node)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'

```
## 2- I typed in shell `yowsup-cli demos  -e -c yu.config` , when I tried to send message from my phone to yowsup number using E2E system. It will shows

```
Traceback (most recent call last):
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 746, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(code, namespace, namespace)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 270, in process
    self.startEcho()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 308, in startEcho
    stack.start()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/demos/echoclient/stack.py", line 21, in start
    self.stack.loop()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.5/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.5/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib/python3.5/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/axolotl/layer_receive.py", line 86, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/axolotl/layer_receive.py", line 129, in handlePreKeyWhisperMessage
    self.parseAndHandleMessageProto(pkMessageProtocolEntity, plaintext[:-padding])
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/yowsup2-2.5.0-py3.5.egg/yowsup/layers/axolotl/layer_receive.py", line 171, in parseAndHandleMessageProto
    m.ParseFromString(serializedData)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1093, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
```

and the same time. It shows

```
Traceback (most recent call last):
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1087, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/google/protobuf/internal/python_message.py", line 1109, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/home/mohammed/Django_Communication_system/CommunicationSystemEnv/lib/python3.5/site-packages/google/protobuf/internal/decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

```

Thanks

**Comment by AlkindiX** [comment]
I will try to make some investigations on this two damn issues

**Comment by jlguardi** [comment]
Use my master (due to protobuf errors in tgalal master) and use always encryption option.

**Comment by AlkindiX** [comment]
Sure

**Comment by chenwayne** [comment]
I met the same problem using tgalal's master, but his s40 version is updated. @jlguardi the s40 version is out dated in your master, show old_version when register. can you please help update to 2.16.9?

**Comment by jlguardi** [comment]
@chenwayne you are right, my master was out to date. Fixed!
