### ISSUE TITLE
[ERROR] TypeError: unorderable types: NoneType() >= str()

### ISSUE THREAD

**Issue by Armisius** [tgalal/yowsup#1844]
Hi i was trying to install this cutie and something happened I don't know what to do.
Any ideas?

EDIT: Im using python 3, and I've researched and it maybe it causing the problem of comparing types
```
Installed c:\users\erty\appdata\local\programs\python\python35-32\lib\site-packages\protobuf-3.1.0.post1-py3.5.egg
Searching for python-axolotl-curve25519
Reading https://pypi.python.org/simple/python-axolotl-curve25519/
Best match: python-axolotl-curve25519 0.1
Downloading https://pypi.python.org/packages/69/e0/9605cac4c83c12d0bef5c2e9992f0bcbce4fae9a252899d545ccb7dc8717/python-axolotl-curve25519-0.1.tar.gz#md5=f28d902df9044f0bf86a35a4bd2ec092
Processing python-axolotl-curve25519-0.1.tar.gz
Writing C:\Users\erty\AppData\Local\Temp\easy_install-2g2hmgak\python-axolotl-curve25519-0.1\setup.cfg
Running python-axolotl-curve25519-0.1\setup.py -q bdist_egg --dist-dir C:\Users\erty\AppData\Local\Temp\easy_install-2g2hmgak\python-axolotl-curve25519-0.1\egg-dist-tmp-izalcdnz
Traceback (most recent call last):
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
    yield saved
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 273, in run
    return func()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\erty\AppData\Local\Temp\easy_install-2g2hmgak\python-axolotl-curve25519-0.1\setup.py", line 27, in <module>
    tests_require=[],
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\install_lib.py", line 10, in run
    self.build()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\build_ext.py", line 49, in run
    _build_ext.run(self)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\command\build_ext.py", line 307, in run
    force=self.force)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\cygwinccompiler.py", line 282, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\cygwinccompiler.py", line 126, in __init__
    if self.ld_version >= "2.10.90":
TypeError: unorderable types: NoneType() >= str()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules'
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\install.py", line 117, in do_egg_install
    cmd.run()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\easy_install.py", line 391, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\easy_install.py", line 621, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\easy_install.py", line 672, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\easy_install.py", line 717, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pkg_resources\__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pkg_resources\__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pkg_resources\__init__.py", line 1104, in obtain
    return installer(requirement)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\easy_install.py", line 640, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\easy_install.py", line 670, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\easy_install.py", line 850, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\easy_install.py", line 1078, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\easy_install.py", line 1064, in run_setup
    run_setup(setup_script, args)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 246, in run_setup
    raise
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pkg_resources\_vendor\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
    yield saved
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
    yield
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 243, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 273, in run
    return func()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 242, in runner
    _execfile(setup_script, ns)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\erty\AppData\Local\Temp\easy_install-2g2hmgak\python-axolotl-curve25519-0.1\setup.py", line 27, in <module>
    tests_require=[],
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\install_lib.py", line 10, in run
    self.build()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\site-packages\setuptools\command\build_ext.py", line 49, in run
    _build_ext.run(self)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\command\build_ext.py", line 307, in run
    force=self.force)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\cygwinccompiler.py", line 282, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "C:\Users\erty\AppData\Local\Programs\Python\Python35-32\lib\distutils\cygwinccompiler.py", line 126, in __init__
    if self.ld_version >= "2.10.90":
TypeError: unorderable types: NoneType() >= str()

C:\Users\erty\Desktop\yowsup-master\yowsup-master>
```

**Comment by rafaelsilverioit** [comment]
It seems that the variable `ld_version` inside of `cygwinccompiler.py` is not being initialized, because of that, when a comparison is made on line 126 (```if self.ld_version >= "2.10.90"```) an error is thrown because you cannot compare a None with a str type.

The source code of cygwinccompiler has a method called get_versions, which:
> Try to find out the versions of gcc, ld and dllwrap. If not possible it returns None for it.

The easiest workaround is to use Python2.7, since in Python2.7 allows you to compare None with str.

More info: [Python3 - Ordering Comparisons](https://docs.python.org/release/3.0/whatsnew/3.0.html#ordering-comparisons)
