### ISSUE TITLE
TypeError: unsupported operand type(s) for &: 'str' and 'int'

### ISSUE THREAD

**Issue by IAmJulianAcosta** [tgalal/yowsup#1862]
Tried to login using cli

```
[offline]:/login 573456789012 password
INFO:yowsup.layers.axolotl.layer_control:Axolotl layer is generating keys
Auth: Logged in!
general: Disconnected: Requested
[connected]:

Auth: Logged in!
WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or KeyId for 57xxxxxxxxxx, going to send a retry
Notification: Notification

From: 57xxxxxxxx@s.whatsapp.net
Type: picture

[connected]:

Notification: Notification
From: 57xxxxxxxx@s.whatsapp.net
Type: picture

[connected]:
DUMP:

Snsak
['\n', '\x05', 'S', 'n', 's', 'a', 'k']
[10, 5, 83, 110, 115, 97, 107]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 1087, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 1109, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/usr/local/bin/yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.5/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.5/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib/python3.5/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 86, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 129, in handlePreKeyWhisperMessage
    self.parseAndHandleMessageProto(pkMessageProtocolEntity, plaintext[:-padding])
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 171, in parseAndHandleMessageProto
    m.ParseFromString(serializedData)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 1093, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
```

**Comment by jlguardi** [comment]
Replace string types by bytes in protobuf file.

**Comment by IAmJulianAcosta** [comment]
Thanks @jlguardi, I'm new to this, which protobuf file are you talking about?

Thanks

**Comment by gushome7** [comment]
@jlguardi could you explain? Thanks a lot!

**Comment by rafaelsilverioit** [comment]
@IAmJulianAcosta and @gushome7 I do believe it must be replaced on: [yowsup.layers.protocol_messages.proto.wa.proto](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_messages/proto/wa.proto)

**Comment by rafaelsilverioit** [comment]
@IAmJulianAcosta Have you tried this?

**Comment by tgalal** [comment]
fixed
