### ISSUE TITLE
From yowsup-cli I can send spanish chars (like á) but crashes if receive it.

### ISSUE THREAD

**Issue by gushome7** [tgalal/yowsup#1864]
If someone already solved it and can share how, I will very thank you very much!

Traceback:
DUMP:

Ñ
['\n', '\x02', 'Ñ']
[10, 2, 209]
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/google/protobuf/internal/python_message.py", line 1087, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/lib/python3.4/site-packages/google/protobuf/internal/python_message.py", line 1109, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/usr/lib/python3.4/site-packages/google/protobuf/internal/decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/usr/bin/yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/usr/lib/python3.4/site-packages/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/lib/python3.4/site-packages/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python3.4/asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python3.4/asyncore.py", line 153, in poll
    read(obj)
  File "/usr/lib64/python3.4/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib64/python3.4/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python3.4/asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3.4/site-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/lib/python3.4/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/axolotl/layer_receive.py", line 88, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/axolotl/layer_receive.py", line 144, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "/usr/lib/python3.4/site-packages/yowsup/layers/axolotl/layer_receive.py", line 171, in parseAndHandleMessageProto
    m.ParseFromString(serializedData)
  File "/usr/lib/python3.4/site-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/lib/python3.4/site-packages/google/protobuf/internal/python_message.py", line 1093, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

**Comment by rafaelsilverioit** [comment]
@gushome7 Replace string types by bytes in protobuf file. The file is: [/yowsup/layers/protocol_messages/proto/wa.proto](https://github.com/tgalal/yowsup/blob/master/yowsup/layers/protocol_messages/proto/wa.proto)

#1862

**Comment by gushome7** [comment]
@rafaelsilverioit Thanks a lot!

**Comment by gushome7** [comment]
Hi @rafaelsilverioit, after change strings for bytes and reinstall still crash but different:
    self.entity_callbacks[entityType](entity)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.5.0-py2.6.egg/yowsup/demos/cli/layer.py", line 512, in onMessage
    MESSAGE_ID = message.getId()
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 1: ordinal not in range(128)

Ideas? Thanks a lot

**Comment by gushome7** [comment]
Oh my god.... solved reading issues ;-) @rafaelsilverioit thanks a lot.

**Comment by rafaelsilverioit** [comment]
@gushome7 Can you close the issue, please?

**Comment by gushome7** [comment]
Solved reading https://github.com/tgalal/yowsup/issues/1646#issuecomment-229545988
