### ISSUE TITLE
yowsup-cli send image

### ISSUE THREAD

**Issue by wendeljardel** [tgalal/yowsup#1884]
How to send image file with yowsup cli?
I trying send image with yowsup cli.
> yowsup-cli demos --yowsup --config yowsup/whats.config
 
After connected I put this code

> /image send 55XXXXXXXXXX teste.jpg

Returned this

> [connected]:ERROR:yowsup.common.optionalmodules:PIL import failed
ERROR:yowsup.common.optionalmodules:PIL import failed
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1350, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 121, in receive
    if not self.processIqRegistry(node):
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 156, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/layer.py", line 70, in onRequestUploadSuccess
    self.toUpper(ResultRequestUploadIqProtocolEntity.fromProtocolTreeNode(resultNode))
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/interface/interface.py", line 77, in receive
    if not self.processIqRegistry(entity):
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/interface/interface.py", line 56, in processIqRegistry
    successClbk(entity, originalIq)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/demos/cli/layer.py", line 403, in <lambda>
    successFn = lambda successEntity, originalEntity: self.onRequestUploadResult(jid, mediaType, path, successEntity, originalEntity, caption)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/demos/cli/layer.py", line 556, in onRequestUploadResult
    resultRequestUploadIqProtocolEntity.getIp(), caption)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/demos/cli/layer.py", line 540, in doSendMedia
    entity = ImageDownloadableMediaMessageProtocolEntity.fromFilePath(filePath, url, ip, to, caption = caption)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_image.py", line 123, in fromFilePath
    return ImageDownloadableMediaMessageProtocolEntity.fromBuilder(builder)
  File "/Library/Python/2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_image.py", line 107, in fromBuilder
    assert dimensions, "Could not determine image dimensions"
AssertionError: Could not determine image dimensions

**Comment by DmitryPostolenko** [comment]
Hi,
Had the same issue, try:

pip install Pillow
apt-get install python-imaging

Worked for me

**Comment by danfsd** [comment]
Had the same problem, it has been solved with **Pillow** suggested by @DmitryPostolenko suggestion. But the still I'm unable to send images
```
Sent: **********-************@s.whatsapp.net, 100% p.net, 1% 
```

The image never arrived at the destination, anyone knows why?

**Comment by the-jojo-jj** [comment]
> Had the same problem, it has been solved with **Pillow** suggested by @DmitryPostolenko suggestion. But the still I'm unable to send images
> 
> ```
> Sent: **********-************@s.whatsapp.net, 100% p.net, 1% 
> ```
> 
> The image never arrived at the destination, anyone knows why?

hi @danfsd, Do you solve this?
Can you share your scripts?

**Comment by danfsd** [comment]
> > Had the same problem, it has been solved with **Pillow** suggested by @DmitryPostolenko suggestion. But the still I'm unable to send images
> > ```
> > Sent: **********-************@s.whatsapp.net, 100% p.net, 1% 
> > ```
> > 
> > 
> > The image never arrived at the destination, anyone knows why?
> 
> hi @danfsd, Do you solve this?
> Can you share your scripts?

Hey @the-jojo-jj, unfortunately no. I ended up switching to another library back at the day, but this other library also has stopped working.

**Comment by the-jojo-jj** [comment]
Ok, thanks
