### ISSUE TITLE
yowsup cli crash when i login

### ISSUE THREAD

**Issue by Jan2220** [tgalal/yowsup#1903]
Hey,
if i try to login at yoqsup cli the cli crashs with this error message: http://pastebin.com/raw/h44Q9wJK
Can somebody help?
few seconds before the crash, i changed the group picture in a group with the yoqsup client maybe the reason? tried to remove the picture but same error when i login :/ 
Hope somebody can help me :c

~Jan

**Comment by Domeax** [comment]
Use the send demo and send a message to the contact.

**Comment by Jan2220** [comment]
> Use the send demo and send a message to the contact.

How to get whatsapp group id without the real "interface"? 
now i get a new error:
```
root@vps:/yowsup# yowsup-cli demos -c /yowsup/config -y
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 290, in startCmdline
    from yowsup.demos import cli
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/demos/cli/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/stacks/yowstack.py", line 8, in <module>
    from yowsup.layers.protocol_messages           import YowMessagesProtocolLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_messages/__init__.py", line 1, in <module>
    from .layer import YowMessagesProtocolLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_messages/layer.py", line 2, in <module>
    from .protocolentities import TextMessageProtocolEntity
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_messages/protocolentities/__init__.py", line 1, in <module>
    from .message_text import TextMessageProtocolEntity
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 24
    def getBody(self):
      ^
IndentationError: expected an indented block
```

**Comment by Jan2220** [comment]
i´ve tried to reboot the system, let setup.py reinstall & rebuild... but nothing works...
