### ISSUE TITLE
Import error after successful registration

### ISSUE THREAD

**Issue by alarazr** [tgalal/yowsup#1911]
Hi, if I give the command
`yowsup-cli demos -c /home/razlr/yowsup/mydetails -s 44xxxxxxxxxx "testing"`

I get:

`Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 290, in startCmdline
    from yowsup.demos import cli
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/demos/cli/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/stacks/yowstack.py", line 10, in <module>
    from yowsup.layers.protocol_media              import YowMediaProtocolLayer
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/__init__.py", line 1, in <module>
    from .layer import YowMediaProtocolLayer 
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/layer.py", line 2, in <module>
    from .protocolentities import ImageDownloadableMediaMessageProtocolEntity
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/protocolentities/__init__.py", line 3, in <module>
    from .message_media_downloadable_image import ImageDownloadableMediaMessageProtocolEntity
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_image.py", line 4, in <module>
    from yowsup.layers.protocol_messages.proto.wa_pb2 import ImageMessage
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/protocol_messages/proto/wa_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: libprotobuf.so.12: cannot open shared object file: No such file or directory
`

I tried recompiling and I tried a number of the demos but I can't get the app to do anything without this message. Does anyone have a solution? I'm probably missing something obvious

Thanks

**Comment by jegue** [comment]
Same here! no Solution yet

**Comment by jegue** [comment]
I solved pip uninstall protobuf then pip install protobuf

**Comment by arthahir** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.2', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/yowsup/env/env.py", line 15, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python2.7/abc.py", line 87, in __new__
    cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
root@BBLPT0825:~/yowsup-2.5.2#


can u pls help on this.

also tried uninstaling pip and also installed it again ..

when i run yowsup-cli command im getting above error
