### ISSUE TITLE
google.protobuf.message.DecodeError: Truncated message. | AttributeError: 'NoneType' object has no attribute 'getData'

### ISSUE THREAD

**Issue by Nitrama** [tgalal/yowsup#1923]
Hello,
i send a message from my Phone to yowsup and i get this error.

```
F:\Python\Scripts>python yowsup-cli demos -c config.example -e -s 491XXXXXXX "Hello World"
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


WARNING:yowsup.layers.axolotl.layer_receive:Received a message that we've previously decrypted, goint to send the delivery receipt myself
DUMP:

Okay
['\n', '\x04', 'O', 'k', 'a', 'y']
[10, 4, 79, 107, 97, 121]
Traceback (most recent call last):
  File "F:\Python\lib\site-packages\google\protobuf\internal\python_message.py", line 1062, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "F:\Python\lib\site-packages\google\protobuf\internal\python_message.py", line 1084, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "F:\Python\lib\site-packages\google\protobuf\internal\decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "F:\Python\lib\site-packages\pkg_resources\__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "F:\Python\lib\site-packages\pkg_resources\__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "f:\python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\EGG-INFO\scripts\yowsup-cli", line 368, in <module>
    if not parser.process():
  File "f:\python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\EGG-INFO\scripts\yowsup-cli", line 270, in process
    self.startEcho()
  File "f:\python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\EGG-INFO\scripts\yowsup-cli", line 308, in startEcho
    stack.start()
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\demos\echoclient\stack.py", line 21, in start
    self.stack.loop()
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\stacks\yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "F:\Python\lib\asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "F:\Python\lib\asyncore.py", line 150, in poll
    read(obj)
  File "F:\Python\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "F:\Python\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "F:\Python\lib\asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\network\layer.py", line 102, in handle_read
    self.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\network\layer.py", line 110, in receive
    self.toUpper(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\stanzaregulator\layer.py", line 29, in receive
    self.processReceived()
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\stanzaregulator\layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\auth\layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\axolotl\layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\__init__.py", line 189, in receive
    s.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\axolotl\layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\axolotl\layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\axolotl\layer_receive.py", line 88, in handleEncMessage
    self.handleWhisperMessage(node)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\axolotl\layer_receive.py", line 144, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\axolotl\layer_receive.py", line 171, in parseAndHandleMessageProto
    m.ParseFromString(serializedData)
  File "F:\Python\lib\site-packages\google\protobuf\message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "F:\Python\lib\site-packages\google\protobuf\internal\python_message.py", line 1068, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
```

If I use "-M" comes the error

```
F:\Python\Scripts>python yowsup-cli demos -c config.example -M -e -s 4917XXXXX "Hallo Welt"
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "F:\Python\lib\site-packages\pkg_resources\__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "F:\Python\lib\site-packages\pkg_resources\__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "f:\python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\EGG-INFO\scripts\yowsup-cli", line 368, in <module>
    if not parser.process():
  File "f:\python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\EGG-INFO\scripts\yowsup-cli", line 270, in process
    self.startEcho()
  File "f:\python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\EGG-INFO\scripts\yowsup-cli", line 308, in startEcho
    stack.start()
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\demos\echoclient\stack.py", line 21, in start
    self.stack.loop()
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\stacks\yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "F:\Python\lib\asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "F:\Python\lib\asyncore.py", line 150, in poll
    read(obj)
  File "F:\Python\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "F:\Python\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "F:\Python\lib\asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\network\layer.py", line 102, in handle_read
    self.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\network\layer.py", line 110, in receive
    self.toUpper(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\stanzaregulator\layer.py", line 29, in receive
    self.processReceived()
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\stanzaregulator\layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\auth\layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\__init__.py", line 189, in receive
    s.receive(data)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\__init__.py", line 125, in receive
    recv(node)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\protocol_messages\layer.py", line 22, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "F:\Python\lib\site-packages\yowsup2-2.5.0-py3.5.egg\yowsup\layers\protocol_messages\protocolentities\message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'
```

Sorry for my bad English
I'm from Germany :-)

thanks

**Comment by jlguardi** [comment]
Try it with python 2.7 instead of 3.5.

-M flag cank't be used due to "all" incomming messages are encrypted and ‎yowsup doesn't know how to manage is axolotl is disabled.

**Comment by ashishradadia** [comment]
i have same issue  where i try only with 2.7 
after remove 3.4.3 python 
error got below 
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in startSendClient
    not self.args["unmoxie"])
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/demos/sendclient/stack.py", line 26, in __init__
    self.stack.setCredentials(credentials)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/stacks/yowstack.py", line 156, in setCredentials
    self.getLayerInterface(YowAuthenticationProtocolLayer).setCredentials(*credentials)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/auth/layer_interface_authentication.py", line 5, in setCredentials
    self._layer.setCredentials((phone, password))
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/auth/layer_authentication.py", line 46, in setCredentials
    self._credentials = self.__getCredentials(credentials)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/layers/auth/layer_authentication.py", line 41, in __getCredentials
    password = base64.b64decode(pb64)
  File "/usr/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
