### ISSUE TITLE
Protobuf: Desciptors directly called

### ISSUE THREAD

**Issue by Viporizer** [tgalal/yowsup#1945]
It seems to be impossible to send messages, echo or run the cli. All demo options end up with the same error:

DEBUG:yowsup.env.env:Current env changed to s40 
Traceback (most recent call last):
  File "/home/vipo/Documents/scripts/python/whatbot/venv/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/home/vipo/Documents/scripts/python/whatbot/venv/bin/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/home/vipo/Documents/scripts/python/whatbot/venv/bin/yowsup-cli", line 290, in startCmdline
    from yowsup.demos import cli
  File "/home/vipo/Documents/scripts/python/whatbot/venv/local/lib/python2.7/site-packages/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/home/vipo/Documents/scripts/python/whatbot/venv/local/lib/python2.7/site-packages/yowsup/demos/cli/stack.py", line 5, in <module>
    from yowsup.layers.axolotl.props import PROP_IDENTITY_AUTOTRUST
  File "/home/vipo/Documents/scripts/python/whatbot/venv/local/lib/python2.7/site-packages/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer_send import AxolotlSendLayer
  File "/home/vipo/Documents/scripts/python/whatbot/venv/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_send.py", line 6, in <module>
    from axolotl.sessioncipher import SessionCipher
  File "/home/vipo/Documents/scripts/python/whatbot/venv/local/lib/python2.7/site-packages/axolotl/sessioncipher.py", line 9, in <module>
    from .sessionbuilder import SessionBuilder
  File "/home/vipo/Documents/scripts/python/whatbot/venv/local/lib/python2.7/site-packages/axolotl/sessionbuilder.py", line 13, in <module>
    from .protocol.keyexchangemessage import KeyExchangeMessage
  File "/home/vipo/Documents/scripts/python/whatbot/venv/local/lib/python2.7/site-packages/axolotl/protocol/keyexchangemessage.py", line 5, in <module>
    from . import whisperprotos
  File "/home/vipo/Documents/scripts/python/whatbot/venv/local/lib/python2.7/site-packages/axolotl/protocol/whisperprotos.py", line 41, in <module>
    options=None),
  File "/home/vipo/Documents/scripts/python/whatbot/venv/local/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 494, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

I have tried this with Python 2.7 and 3.x, can anybody tell me how to solve this issue?

**Comment by Viporizer** [comment]
Nevermind. Missed that it required Protobuf to be version 3.0.0b3

**Comment by DagoW** [comment]
Thanks a lot for posting this anyway. I had run into the same error and only solved it after you told us  the right version.

Do you happen to know of other packages that need to be of a specific (older) version?
On a computer with python3, I still get uncaught exceptions for some messages and sometimes warnings like this:
`WARNING:axolotl.sessioncipher:'utf-8' codec can't decode byte 0x8a in position 36: invalid start byte`
