### ISSUE TITLE
yowsup stop working.

### ISSUE THREAD

**Issue by maruscya** [tgalal/yowsup#1949]
Dear All 

After months yowsup stop working. After some test this is the error : 

root@zbx1:~# ./yowsup-cli demos -c yowsup.cfg -s 3934833****** "test"
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Traceback (most recent call last):
  File "/app/zabbix/script/yowsup-master/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/app/zabbix/script/yowsup-master/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/app/zabbix/script/yowsup-master/yowsup-cli", line 323, in startSendClient
    not self.args["unmoxie"])
  File "/app/zabbix-server-3-0/script/yowsup-master/yowsup/demos/sendclient/stack.py", line 20, in __init__
    .pushDefaultLayers(encryptionEnabled)\
  File "/app/zabbix-server-3-0/script/yowsup-master/yowsup/stacks/yowstack.py", line 51, in pushDefaultLayers
    defaultLayers = YowStackBuilder.getDefaultLayers(axolotl)
  File "/app/zabbix-server-3-0/script/yowsup-master/yowsup/stacks/yowstack.py", line 73, in getDefaultLayers
    from yowsup.layers.axolotl import AxolotlSendLayer, AxolotlControlLayer, AxolotlReceivelayer
  File "/app/zabbix-server-3-0/script/yowsup-master/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer_send import AxolotlSendLayer
  File "/app/zabbix-server-3-0/script/yowsup-master/yowsup/layers/axolotl/layer_send.py", line 6, in <module>
    from axolotl.sessioncipher import SessionCipher
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessioncipher.py", line 9, in <module>
    from .sessionbuilder import SessionBuilder
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 13, in <module>
    from .protocol.keyexchangemessage import KeyExchangeMessage
  File "/usr/local/lib/python2.7/dist-packages/axolotl/protocol/keyexchangemessage.py", line 5, in <module>
    from . import whisperprotos
  File "/usr/local/lib/python2.7/dist-packages/axolotl/protocol/whisperprotos.py", line 41, in <module>
    options=None),
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 494, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

The OS is ubuntu 16.04 LTS. Do you have any idea about to solve this issue ?

Many thanks.

**Comment by DagoW** [comment]
Probably you upgraded Python. Apparently there is one specific version of
the protobuf package that works. Try:
`pip install protobuf==3.0.0b3`
or, without root premissions
`pip install protobuf==3.0.0b3 --user`
Ref: #1945

**Comment by maruscya** [comment]
Man ! 

You save my life, after the "pip install protobuf==3.0.0b3" everything works fine. 

Many thanks for your help.
