### ISSUE TITLE
Yowsup crashes when special chars are received

### ISSUE THREAD

**Issue by DennisGaida** [tgalal/yowsup#1951]
Yowsup crashes when special characters (e.g. "Üüüü") are received via WhatsApp - missing utf8 encoding seems to be the issue.

Trace:
```
Traceback (most recent call last):
  File "~/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "~/yowsup-cli", line 268, in process
    self.startCmdline()
  File "~/yowsup-cli", line 297, in startCmdline
    stack.start()
  File "~/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "~/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "~/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "~/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "~/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "~/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "~/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "~/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "~/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "~/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "~/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "~/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "~/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "~/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "~/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "~/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "~/yowsup/layers/axolotl/layer_receive.py", line 88, in handleEncMessage
    self.handleWhisperMessage(node)
  File "~/yowsup/layers/axolotl/layer_receive.py", line 144, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "~/yowsup/layers/axolotl/layer_receive.py", line 188, in parseAndHandleMessageProto
    self.handleConversationMessage(node, m.conversation)
  File "~/yowsup/layers/axolotl/layer_receive.py", line 217, in handleConversationMessage
    self.toUpper(messageNode)
  File "~/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "~/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "~/yowsup/layers/__init__.py", line 125, in receive
    recv(node)
  File "~/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
    self.toUpper(entity)
  File "~/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "~/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "~/yowsup/demos/cli/layer.py", line 512, in onMessage
    MESSAGE_ID = message.getId()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```

The problem can be resolved by adding
```
reload(sys)
sys.setdefaultencoding('utf8')
```
into line 7 in cli/layer.py

Using Python 2.7.9, but I suppose the default encoding should be UTF8 anyways so this doesn't look like a bad default?

**Comment by hypertech** [comment]
Hello, about encoding also, if i send messages in UTF8 encoding and without encription, i get this exception

> Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\yowsup\demos\cli\cli.py", line 155, in startInputThread
    wait = self.execCmd(cmd)
  File "C:\Python27\yowsup\demos\cli\cli.py", line 139, in execCmd
    return self.doExecCmd(lambda :targetFn(*args))
  File "C:\Python27\yowsup\demos\cli\cli.py", line 142, in doExecCmd
    return fn()
  File "C:\Python27\yowsup\demos\cli\cli.py", line 139, in <lambda>
    return self.doExecCmd(lambda :targetFn(*args))
  File "C:\Python27\yowsup\demos\cli\layer.py", line 373, in message_send
    self.toLower(outgoingMessage)
  File "C:\Python27\yowsup\layers\__init__.py", line 80, in toLower
    self.__lower.send(data)
  File "C:\Python27\yowsup\layers\__init__.py", line 193, in send
    s.send(data)
  File "C:\Python27\yowsup\layers\__init__.py", line 131, in send
    send(entity)
  File "C:\Python27\yowsup\layers\protocol_messages\layer.py", line 15, in sendM
essageEntity
    self.entityToLower(entity)
  File "C:\Python27\yowsup\layers\__init__.py", line 135, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "C:\Python27\yowsup\layers\__init__.py", line 80, in toLower
    self.__lower.send(data)
  File "C:\Python27\yowsup\layers\logger\layer.py", line 9, in send
    self.toLower(data)
  File "C:\Python27\yowsup\layers\__init__.py", line 80, in toLower
    self.__lower.send(data)
  File "C:\Python27\yowsup\layers\coder\layer.py", line 30, in send
    self.write(self.writer.protocolTreeNodeToBytes(data))
  File "C:\Python27\yowsup\layers\coder\layer.py", line 39, in write
    self.toLower(bytearray(i))
ValueError: byte must be in range(0, 256)

any idea how to fix it?

**Comment by sporteman** [comment]
Thanks @moontear  

```
reload(sys)
sys.setdefaultencoding('utf8')
```

It works 😄

**Comment by tgalal** [comment]
fixed
