### ISSUE TITLE
Registration UnicodeDecodeError

### ISSUE THREAD

**Issue by evertonrenne** [tgalal/yowsup#1961]
I ran a few test to register and activate a single number and everything goes well until I tried to do a new registration (with a new SIM card) and I am receiving UnicodeDecodeError.

Any idea what could be?

### env_s40:
`from .env import YowsupEnv
import hashlib
class S40YowsupEnv(YowsupEnv):
    _VERSION = "2.16.11"
    _OS_NAME= "S40"
    _OS_VERSION = "14.28"
    _DEVICE_NAME = "306"
    _MANUFACTURER = "Nokia"
    _TOKEN_STRING  = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1478194306452{phone}"
    _AXOLOTL = True

    def getVersion(self):
        return self.__class__._VERSION

    def getOSName(self):
        return self.__class__._OS_NAME

    def getOSVersion(self):
        return self.__class__._OS_VERSION

    def getDeviceName(self):
        return self.__class__._DEVICE_NAME

    def getManufacturer(self):
        return self.__class__._MANUFACTURER

    def isAxolotlEnabled(self):
        return self.__class__._AXOLOTL

    def getToken(self, phoneNumber):
        return hashlib.md5(self.__class__._TOKEN_STRING.format(phone = phoneNumber).encode()).hexdigest()

    def getUserAgent(self):
        return self.__class__._USERAGENT_STRING.format(
            WHATSAPP_VERSION = self.getVersion(),
            OS_NAME = self.getOSName() + "Version",
            OS_VERSION = self.getOSVersion(),
            DEVICE_NAME = self.getDeviceName(),
            MANUFACTURER = self.getManufacturer()
        )`

### my command line
**yowsup-cli registration --requestcode sms --phone 34XXXXXXXXX​ --cc 34 -d**
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
Traceback (most recent call last):
  File ".local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.0', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/home/user/.local/lib/python2.7/site-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/home/user/.local/lib/python2.7/site-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 189, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/home/user/.local/lib/python2.7/site-packages/yowsup2-2.5.0-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 206, in handleRequestCode
    method
  File "/home/user/.local/lib/python2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/registration/coderequest.py", line 41, in __init__
    self.addParam("token", YowsupEnv.getCurrent().getToken(p_in))
  File "/home/user/.local/lib/python2.7/site-packages/yowsup2-2.5.0-py2.7.egg/yowsup/env/env_s40.py", line 31, in getToken
    return hashlib.md5(self.__class__._TOKEN_STRING.format(phone = phoneNumber).encode()).hexdigest()
**UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 64: ordinal not in range(128)**

**Comment by evertonrenne** [comment]
Found the problem: somehow (i don`t know why) there is a char (<200b>) after last phone number. I checked few times with an editor to shown all special chars and this <200b> never appear before in my command line. When i tried to type char by char it works. 

So, i figured out was something in my command line. After change locale and try again, the problem was in copy/paste in console from a text editor. This char appear everytime at the end of phonenumber **yowsup-cli registration --requestcode sms --phone 34XXXXXXXXX<200b>​ --cc 34 -d**

I hope that this information help someone to not waste time with this kind of issue.
