### ISSUE TITLE
general: Login Failed, reason: not-authorized Auth Error, reason not-authorized

### ISSUE THREAD

**Issue by EiderDiaz** [tgalal/yowsup#1971]
@tgalal  I made it this far, and i wanna still use yowsup,
every time I tried to log in with different numbers in different raspberrys kick me with this:
![2017-03-16 6](https://cloud.githubusercontent.com/assets/17805140/24025422/7c7aef0e-0a77-11e7-816e-ae15a7342381.png)

any idea or any trick, I'm in trouble right here @tgalal 
thanks in advance ✋

**Comment by wongchungon** [comment]
same issue, installed and get blocked after few minutes. 
I guess they block the account after they detect third-party application.

**Comment by vityapro** [comment]
try use android_env on registration than s40 on login and sending message

**Comment by EiderDiaz** [comment]
@vityapro how? can you send me an example or some documentation about that?
thanks in advance 😄

**Comment by vityapro** [comment]
just look at wiki

**Comment by gauchoarg** [comment]
try with thiis:

https://github.com/colonyhq/yowsup

**Comment by barapa** [comment]
@gauchoarg I have tried using that alternate yowsup repo and I get errors still. If I don't include a country code in the number, I get 
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.6.0/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/var/pyenv/versions/3.6.0/bin/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/local/var/pyenv/versions/3.6.0/bin/yowsup-cli", line 324, in startSendClient
    stack.start()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_send.py", line 53, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 156, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_base.py", line 51, in onSuccess
    entity = ResultGetKeysIqProtocolEntity.fromProtocolTreeNode(resultNode)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 88, in fromProtocolTreeNode
    preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
AttributeError: 'NoneType' object has no attribute 'getChild'

If I do include a country code, I get
  File "/usr/local/var/pyenv/versions/3.6.0/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/var/pyenv/versions/3.6.0/bin/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/local/var/pyenv/versions/3.6.0/bin/yowsup-cli", line 324, in startSendClient
    stack.start()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 46, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 125, in receive
    recv(node)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/auth/layer_authentication.py", line 75, in handleSuccess
    self.toUpper(nodeEntity)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/demos/sendclient/layer.py", line 31, in onSuccess
    self.toLower(messageEntity)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 80, in toLower
    self.__lower.send(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 193, in send
    s.send(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 131, in send
    send(entity)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 135, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 80, in toLower
    self.__lower.send(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 193, in send
    s.send(data)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_send.py", line 48, in send
    self.processPlaintextNodeAndSend(node)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_send.py", line 84, in processPlaintextNodeAndSend
    self.sendToContact(node)
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_send.py", line 142, in sendToContact
    messageData = self.serializeToProtobuf(node).SerializeToString() + self.getPadding()
  File "/usr/local/var/pyenv/versions/3.6.0/lib/python3.6/site-packages/google/protobuf/message.py", line 197, in SerializeToString
    raise NotImplementedError
NotImplementedError

**Comment by barapa** [comment]
I've been using the colonyhq repo with python 2.7.12, and after just a few minutes started getting 

```
DEBUG:yowsup.layers.logger.layer:rx:
<failure>
<not-authorized>
</not-authorized>
</failure>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Authentication Error: not-authorized
```

**Comment by jlguardi** [comment]
You've been banned.

**Comment by lgveronese** [comment]
Any news @EiderDiaz ? 

I just did the same thing and got the same error.. I don't think I got banner.. I just registered right now.. can't login once..

**Comment by hongkit7890** [comment]
You have been banned.

Below is the response from whatsapp, and my account got unbanned after sending iphone screenshot copy of whatsapp for 2 weeks.

From support@support.whatsapp.com

Hi,
Thanks for your message.
Your WhatsApp account was banned because you violated our Terms of Service and were using an unauthorized application and/or unsupported device.
Please uninstall your application and install an authorized version on supported devices from:
www.whatsapp.com/download
Please note that we do not allow use of unofficial clients or jailbroken/rooted (including emulators), and unsupported devices.
To use WhatsApp on your computer, access our website from your computer’s browser. Then, open the app and scan the QR code using the WhatsApp app on your phone (look for WhatsApp Web menu under Settings). WhatsApp can only be installed on your computer if your operating system is Windows 8 (or newer) or Mac OSX 10.9 (or newer). If you are having issues installing WhatsApp on a supported operating system, turn off your anti-virus and try again.
For all other operating systems, you may use WhatsApp on your browser here
Your account will be permanently banned if you continue to violate our Terms of Service, and there will be no possibility of an appeal.

**Comment by djwesleyborges** [comment]
yowsup-cli demos --config whatsapp.txt --send 55XXXXXXXXXX "Teste"
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


**Authentication Error: not-authorized**

**Comment by coolnickname** [comment]
Please don't open old issues that have been closed, it's generally annoying.

And since I'm commenting now anyway, not-authorized can also mean your credentials are invalid.
