### ISSUE TITLE
'NoneType' object has no attribute 'getChild'

### ISSUE THREAD

**Issue by roigreenberg** [tgalal/yowsup#1985]
After I finished to make my bot do what I wanted(syncing messages between 2 groups) in a test environment(2 new group we opened for this) , we moved it to a "real" groups but when the bot tried to forword the message to the second group, we got the error in the title.
Moving back to test groups and it's works again. It seems like somthing special in the old groups.

I tried to look for an answer in old issues but failed to find somthing that works.

Traceback (most recent call last):
  File "run.py", line 33, in <module>
    stack.loop( timeout = 0.5, discrete = 0.5 )
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.5/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.5/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib/python3.5/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/axolotl/layer_send.py", line 64, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/__init__.py", line 161, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/axolotl/layer_base.py", line 51, in onSuccess
    entity = ResultGetKeysIqProtocolEntity.fromProtocolTreeNode(resultNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 88, in fromProtocolTreeNode
    preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
AttributeError: 'NoneType' object has no attribute 'getChild'

**Comment by roigreenberg** [comment]
@jlguardi , I tried to use your master, but it seems like it got to the loop but doing nothing.. any ideas?

**Comment by mikelog** [comment]
After, I've logged on via /yowsup-cli demo -y and sent some message. After got some messages with image contets, I can't sent anything =(
./yowsup-cli demos  --send 7923*****64 "Test message"  --config ./yowsup-cli.config
I'll get the same issue =(
  File "/usr/src/yowsup-master/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 88, in fromProtocolTreeNode
    preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
AttributeError: 'NoneType' object has no attribute 'getChild'

**Comment by jlguardi** [comment]
You are trying to send a message to an invalid jid. Try to get contact info of this number (without CC or add '+' before).

**Comment by roigreenberg** [comment]
I don't think that relevant in my case.
I send messages between groups. It was working on new group we opened but not in old group with lots of members.

**Comment by mikelog** [comment]
roigreenberg, I've reproduce my problem. I've got AttributeError: 'NoneType' object has no attribute 'getChild' when recepient isn't registered in watsapp. 
After registration complete of 7923*****64,  " yowsup-cli demos --send  " was executed successfully,
maybe one of contact isn't registered in your groups?

**Comment by roigreenberg** [comment]
We thought that maybe the issue, but the admin remove numbers that didn't see his messages..

Will it be possible to change the code to ignore such case?

I tried to do it in iq_keys_get_result.py but we just see "message should be here soon" or something like this..

**Comment by duzaq** [comment]
Dear sirs, there is some solution to this problem ?

**Comment by SpEcHiDe** [comment]
Hi. Please any solution to this problem?
