### ISSUE TITLE
Unable to send encrypted messaged to a broadcast

### ISSUE THREAD

**Issue by paulwollner** [tgalal/yowsup#1993]
Would firstly like to say that this is a great project.

When trying to send a message to a broadcast group, the message fails to send. It appears that when yowsup Axolotl layer sends it's request, an error of not-acceptable" code="406" is received.

If I send the message without encryption, it works. Any idea how I can get this resolved?

Debug is below:

/message broadcast 27827XXXXXX test
DEBUG:yowsup.layers.logger.layer:tx:
<iq to="s.whatsapp.net" xmlns="encrypt" type="get" id="2">
<key>
<user jid="1491570686376@broadcast">
</user>
</key>
</iq>

[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<iq type="error" from="s.whatsapp.net" id="2">
<error text="not-acceptable" code="406">
</error>
</iq>

Traceback (most recent call last):
  File "/usr/local/src/yowsup/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/src/yowsup/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/usr/local/src/yowsup/yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/usr/local/src/yowsup/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/src/yowsup/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python2.6/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.6/asyncore.py", line 151, in poll
    read(obj)
  File "/usr/lib64/python2.6/asyncore.py", line 82, in read
    obj.handle_error()
  File "/usr/lib64/python2.6/asyncore.py", line 78, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.6/asyncore.py", line 428, in handle_read_event
    self.handle_read()
  File "/usr/local/src/yowsup/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/src/yowsup/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/src/yowsup/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/src/yowsup/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/src/yowsup/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/src/yowsup/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/src/yowsup/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/src/yowsup/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/src/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/src/yowsup/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/src/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/src/yowsup/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/src/yowsup/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/src/yowsup/yowsup/layers/__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "/usr/local/src/yowsup/yowsup/layers/__init__.py", line 189, in receive
    s.receive(data)
  File "/usr/local/src/yowsup/yowsup/layers/axolotl/layer_send.py", line 65, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/local/src/yowsup/yowsup/layers/__init__.py", line 158, in processIqRegistry
    errorClbk(protocolTreeNode, originalIq)
  File "/usr/local/src/yowsup/yowsup/layers/axolotl/layer_base.py", line 81, in onError
    errorClbk(errorNode, getKeysEntity)
TypeError: <lambda>() takes no arguments (2 given)

**Comment by paulwollner** [comment]
The encryption still fails, but at least yosup does not crash anymore after changing the file: yowsup/layers/axolotl/layer_base.py line 81

From:
errorClbk(errorNode, getKeysEntity)
To 
errorClbk()

**Comment by bindu144** [comment]
@paulwollner any fix to send encrypted broadcast message?
