### ISSUE TITLE
Server crashes when receiving ptt audio

### ISSUE THREAD

**Issue by FabricioCabeca** [tgalal/yowsup#1995]
How reproducible: always
Version: 2.5.2
Python version: 2.7

This is the output from console (binary content omitted):

```
DEBUG:yowsup.layers.logger.layer:rx:
<message type="media" notify="John Doe" from="xxx@s.whatsapp.net" id="zzz" t="1491832775">
<enc type="msg" mediatype="ptt" v="2">
"binary content omitted"
HEX:330a210563b28a039513c875d9949d60457c1eec4c2a983991d40b2a0f58a374a0fcdf551002180222e0016f4d735de13df47704913b79fef9aade2911f9cae82718f4d549206c4e8a82b9107c80c70c9ff46cb24f323af9016b619c1ad5e58cad61555d84d16181e7f171eece49f752262caa76e54400c4480fe155e4a3a675850c7d33b5c13a7468350131cafaacfd73626bcd8e72fc3e6047b76539a6e0ef71e9f2fff723602d7b5929473a30b9360c70afb7614ca3f592ac41a2062bf64cbfce3fb6ed85dcd851357472701b6110dd635a70419bbeb0adc63c2811862d72b257d88715a0ed04c2fb901f82f23227fc0664191889dfe7657fe3754d74128b4a6fc7c30213e74a690faff3cb21f6258ffd08
</enc>
</message>

Traceback (most recent call last):
  File "run.py", line 28, in <module>
    stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib64/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib64/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 88, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 144, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 204, in parseAndHandleMessageProto
    raise ValueError("Unhandled")

```

**Comment by Domeax** [comment]
Audio messages aren't implemented (correctly) i think. But you can restart your program when it crashes. (See the issue where someone asked about it)

**Comment by psts** [comment]
Any workarounds for this?

**Comment by tgalal** [comment]
fixed
