### ISSUE TITLE
socket.error

### ISSUE THREAD

**Issue by felipe010203** [tgalal/yowsup#2023]
Until yesterday it worked correctly, and today it does not connect, any help please.

File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/argosbot/yowsup/yowsup/demos/readclient/Service2.py", line 55, in receive2
stack.loop(count=5)
File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.0-py2.7.egg/yowsup/stacks/yowstack.py", line 196, in loop
asyncore.loop(*args, **kwargs)
File "/usr/lib/python2.7/asyncore.py", line 220, in loop
poll_fun(timeout, map)
File "/usr/lib/python2.7/asyncore.py", line 156, in poll
read(obj)
File "/usr/lib/python2.7/asyncore.py", line 87, in read
obj.handle_error()
File "/usr/lib/python2.7/asyncore.py", line 83, in read
obj.handle_read_event()
File "/usr/lib/python2.7/asyncore.py", line 446, in handle_read_event
self.handle_connect_event()
File "/usr/lib/python2.7/asyncore.py", line 454, in handle_connect_event
raise socket.error(err, _strerror(err))
error: [Errno 110] Connection timed out

**Comment by munknex** [comment]
Same for me. Tried from different IPs and different numbers.

**Comment by munknex** [comment]
Even official WhatsApp client for iOS is not working now.

**Comment by felipe010203** [comment]
After whatsapp official stopped working on yesterday I present this error, any help please:

# **yowsup.layers.auth.autherror.AuthError**
AuthError: not-authorized

Traceback (most recent call last)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/yowsup/yowsup/demos/readclient/Service2.py", line 55, in receive2
stack.loop(count=5)
File "/usr/local/lib/python2.7/site-packages/yowsup/stacks/yowstack.py", line 196, in loop
asyncore.loop(*args, **kwargs)
File "/usr/local/lib/python2.7/asyncore.py", line 220, in loop
poll_fun(timeout, map)
File "/usr/local/lib/python2.7/asyncore.py", line 156, in poll
read(obj)
File "/usr/local/lib/python2.7/asyncore.py", line 87, in read
obj.handle_error()
File "/usr/local/lib/python2.7/asyncore.py", line 83, in read
obj.handle_read_event()
File "/usr/local/lib/python2.7/asyncore.py", line 449, in handle_read_event
self.handle_read()
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 102, in handle_read
self.receive(data)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 110, in receive
self.toUpper(data)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
self.__upper.receive(data)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
self.processReceived()
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
self.toUpper(oneMessageData)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
self.__upper.receive(data)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
self.toUpper(payload)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
self.__upper.receive(data)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
self.toUpper(node)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
self.__upper.receive(data)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
self.toUpper(data)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
self.__upper.receive(data)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
self.toUpper(protocolTreeNode)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
self.__upper.receive(data)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 189, in receive
s.receive(data)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 44, in receive
self.toUpper(protocolTreeNode)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 76, in toUpper
self.__upper.receive(data)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 189, in receive
s.receive(data)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 125, in receive
recv(node)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/auth/layer_authentication.py", line 81, in handleFailure
raise AuthError(nodeEntity.getReason())
AuthError: not-authorized

**Comment by felipe010203** [comment]
After whatsapp official stopped working on yesterday I present this error, any help please

**Comment by munknex** [comment]
WhatsApp always block numbers from time to time. You need to buy new ones ;)

**Comment by felipe010203** [comment]
The strange esque in the virtual machine with ubuntu: 16.04 if it works and in Docker comes that error being the same base image and the same code.
