### ISSUE TITLE
Message is not sending by broadcast method.

### ISSUE THREAD

**Issue by manojrao** [tgalal/yowsup#2043]
when send message by boadcast event then error below as:-
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_send.py", line 64, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 163, in processIqRegistry
    errorClbk(protocolTreeNode, originalIq)
  File "/usr/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_base.py", line 81, in onError
    errorClbk(errorNode, getKeysEntity)
TypeError: <lambda>() takes no arguments (2 given)

**Comment by AragurDEV** [comment]
As seen in the error, you passed 2 arguments to a function. But it takes none of these.
If you need assistance please pass your sourcecode to us.

**Comment by manojrao** [comment]
i did send message by yowsup cli command like as:-
/message broadcast 919785156562,919887613096 'hello'
error as:-
when send message by boadcast event then error below as:-
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_send.py", line 64, in receive
if not self.processIqRegistry(protocolTreeNode):
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/init.py", line 163, in processIqRegistry
errorClbk(protocolTreeNode, originalIq)
File "/usr/local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_base.py", line 81, in onError
errorClbk(errorNode, getKeysEntity)
TypeError: () takes no arguments (2 given)

**Comment by MilanPrasad** [comment]
I am trying this stilli am geting error 
python yowsup-cli demos --yowsup --config config -s 918080974213 "hello"
Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 268, in process
    self.startCmdline()
  File "yowsup-cli", line 290, in startCmdline
    from yowsup.demos import cli
  File "E:\Milan\whatsup 1\yowsup-master\yowsup\demos\cli\__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "E:\Milan\whatsup 1\yowsup-master\yowsup\demos\cli\stack.py", line 2, in <module>
    from .layer import YowsupCliLayer
  File "E:\Milan\whatsup 1\yowsup-master\yowsup\demos\cli\layer.py", line 562
    successFn, self.onUploadError, self.onUploadProgress, async=False)
                                                              ^
SyntaxError: invalid syntax
