### ISSUE TITLE
not working registration

### ISSUE THREAD

**Issue by darkane188** [tgalal/yowsup#2062]
python yowsup-cli registration --requestcode sms --phone 7762152192 --cc 7 --mcc 401 --mnc 01 -E android

INFO:yowsup.common.http.warequest:{"login":"7762152192","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 7762152192

**Comment by abhishekdeshkar** [comment]
Hi,
 Try this.

1) Replace env_android.py : https://github.com/colonyhq/yowsup/blob/master/yowsup/env/env_android.py
2) While registering, 
```
py yowsup-cli registration --requestcode sms --phone 919979559210 --cc 91 --mcc 404 --mnc 05 -E android
```
At the end ``` -E android ``` parameter.

**Comment by rodrigoorrego** [comment]
Hello! I'm new here but already a fan of yowsup! but I'm and also having some issues....

I can request a SMS code with these instructions.. thank you guys for that

but I cannot register... I'm still receiving "old version" error....

any ideas? since now, thanks for the attention! :)

--

yowsup-cli registration --register XXX-XXX --phone 5553XXXXXXXXX --cc 55 -E android
yowsup-cli v2.0.15
yowsup v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"login":"5553XXXXXXXX","status":"fail","reason":"old_version"}

status: fail
reason: old_version
login: 5553XXXXXXXX

**Comment by AlexanderUsselmann** [comment]
same same :)

**Comment by cristopher29** [comment]
same `yowsup-cli registration --requestcode` work but... `yowsup-cli registration --register XXXXXX` doesn't work.

**Comment by shubhamivane** [comment]
please any one help me I getting error during registration.
shubham@shubham-Vostro-2520:~/Desktop/yowsup-2.5.2$ yowsup-cli registration --requestcode sms --phone 919039546421 --cc 91 --mcc 405 --mnc 038
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "/home/shubham/.local/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/home/shubham/.local/bin/yowsup-cli", line 189, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/home/shubham/.local/bin/yowsup-cli", line 208, in handleRequestCode
    result = codeReq.send()
  File "/home/shubham/.local/lib/python3.5/site-packages/yowsup/registration/coderequest.py", line 62, in send
    res = super(WACodeRequest, self).send(parser)
  File "/home/shubham/.local/lib/python3.5/site-packages/yowsup/common/http/warequest.py", line 70, in send
    return self.sendGetRequest(parser)
  File "/home/shubham/.local/lib/python3.5/site-packages/yowsup/common/http/warequest.py", line 108, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET")
  File "/home/shubham/.local/lib/python3.5/site-packages/yowsup/common/http/warequest.py", line 164, in sendRequest
    conn.request(reqType, path, params, headers);
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1252, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

**Comment by rodrigoorrego** [comment]
if I use -E android i'm getting: old version

if I dont use i'm getting: temporarily unavailable

:(

**Comment by rodrigoorrego** [comment]
anyone has ideas? is yowsup still working?

**Comment by shubhamivane** [comment]
I tried it but nothing happend.

**Comment by rodrigoorrego** [comment]
weird... it worked in a new cellphone number I've bought here to test

but in the number I was using (and that was registered once before) it just didn't work (always "temporarily unavailable" error)
