### ISSUE TITLE
yowsup-cli request code command is not working

### ISSUE THREAD

**Issue by shubhamivane** [tgalal/yowsup#2068]
I am running this command behind the proxy server "python3 yowsup-cli registration --requestcode sms --phone 918860820272 --cc 91 --mcc 404 --mnc 11 -E android" and I am getting this,
`(tg) shubham@shubham-Vostro-2520:~/Desktop/tg/yowsup$ python3 yowsup-cli registration --requestcode sms --phone 918860820272 --cc 91 --mcc 404 --mnc 11 -E android
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 189, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup-cli", line 208, in handleRequestCode
    result = codeReq.send()
  File "/home/shubham/Desktop/tg/yowsup/yowsup/registration/coderequest.py", line 62, in send
    res = super(WACodeRequest, self).send(parser)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/common/http/warequest.py", line 70, in send
    return self.sendGetRequest(parser)
  File "/home/shubham/Desktop/tg/yowsup/yowsup/common/http/warequest.py", line 108, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET")
  File "/home/shubham/Desktop/tg/yowsup/yowsup/common/http/warequest.py", line 164, in sendRequest
    conn.request(reqType, path, params, headers);
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1252, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
`

**Comment by shubhamivane** [comment]
yowsup-cli does not work on proxy server.
