### ISSUE TITLE
can't download images

### ISSUE THREAD

**Issue by rodrigoorrego** [tgalal/yowsup#2086]
Hello! I'm still newbie in yowsup and can't find much help in the documentations... so, if someone had run with a problem similar to this, or has some ideas of what may be happening... I'm accepting any tips, help and ideas... thanks in advance! my problem is:

I'm trying to send a image from my cellphone to my run.py script and I'm having this error:

No handlers could be found for logger "yowsup.layers.protocol_media.mediadownloader"
Error download file

full log below:

--

Echoing image https://mmi296.whatsapp.net/d/VZ251nYwKNDZW13cV567GVklw24/AtxrYCnjDID1qtpSiksqZN_cz-cepZCBiFSmF4239naN.enc to 555381436776
Downloading https://mmi296.whatsapp.net/d/VZ251nYwKNDZW13cV567GVklw24/AtxrYCnjDID1qtpSiksqZN_cz-cepZCBiFSmF4239naN.enc
No handlers could be found for logger "yowsup.layers.protocol_media.mediadownloader"
Error download file
Hi Rodrigo Orrego, thank you for sending me your picture.

**Comment by rodrigoorrego** [comment]
and when I try to do the opposite way, that is send a image from the run.py script to my cellphone, I don't receive neither the image nor any message (error message or done message).. and the script continues running as if nothing happened (actually, nothing happened :P)

**Comment by rodrigoorrego** [comment]
and if I try to send the image through yousup-cli with the command:

echo -e "/L\n/image send 5553xxxxxxxx /vagrant_data/Yowsup_Atlas/yowsup-master/geb.jpg" | sudo ./yowsup-cli demos -y -d -c ../config-r &

I've got an error:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/vagrant_data/Yowsup_Atlas/yowsup-master/yowsup/demos/cli/cli.py", line                                                                                                                 153, in startInputThread
    cmd = self._queuedCmds.pop(0) if len(self._queuedCmds) else input(self.getPr                                                                                                                ompt()).strip()
EOFError: EOF when reading a line

and then a loop where nothing happens...

full log below:

--

yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to s40
DEBUG:yowsup.env.env:Current env changed to s40
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.Ax                                                                                                                olotlControlLayer object at 0x1988b90>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.                                                                                                                layer_receive.AxolotlReceivelayer object at 0x1988450>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer -                                                                                                                 Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification                                                                                                                 Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media La                                                                                                                yer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

DEBUG:yowsup.layers.network.layer:Connecting to e2.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="5553xxxxxxxx" mechanism="WAUTH-2">
(...)
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1495400567" expiration="444444444                                                                                                                4" props="15" t="1496050838">
▒▒▒▒▒AnE▒▒?%i▒▒X_▒
HEX:92daf4a9e793416e45f187d13f2569cafd585f90
</success>

DEBUG:yowsup.layers.protocol_iq.layer:starting ping thread.
[offline]:Auth: Logged in!
DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1496050838" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<receipt type="read" offline="0" from="555381436776@s.whatsapp.net" id="14960507                                                                                                                63-1" t="1496050764">
</receipt>

DEBUG:yowsup.layers.axolotl.layer_send:Axolotl layer does not have the message,                                                                                                                 bubbling it upwards
DEBUG:yowsup.layers.logger.layer:tx:
<ack to="555381436776@s.whatsapp.net" type="read" id="1496050763-1" class="recei                                                                                                                pt">
</ack>

DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<offline count="1">
</offline>
</ib>

DEBUG:yowsup.layers.logger.layer:tx:
<iq to="s.whatsapp.net" xmlns="w:m" type="set" id="1">
<media type="image" hash="wXtOst6e9AtI141aejo0jgIFQK2WSFAEiP5FLHS/zqY=" size="11                                                                                                                2517">
</media>
</iq>

DEBUG:yowsup.layers.logger.layer:tx:
<iq to="s.whatsapp.net" xmlns="w:m" type="set" id="1">
<media type="image" hash="wXtOst6e9AtI141aejo0jgIFQK2WSFAEiP5FLHS/zqY=" size="11                                                                                                                2517">
</media>
</iq>

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/vagrant_data/Yowsup_Atlas/yowsup-master/yowsup/demos/cli/cli.py", line                                                                                                                 153, in startInputThread
    cmd = self._queuedCmds.pop(0) if len(self._queuedCmds) else input(self.getPr                                                                                                                ompt()).strip()
EOFError: EOF when reading a line

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="s.whatsapp.net" id="1">
<duplicate mimetype="image/jpeg" filehash="wXtOst6e9AtI141aejo0jgIFQK2WSFAEiP5FL                                                                                                                HS/zqY=" url="https://mmi339.whatsapp.net/d/Ak4NtC4f89azEx-_t3C3hLQmy08VQdaUwHrw                                                                                                                Pzb6sIwF.jpg" height="800" width="800" type="image" size="112517">
</duplicate>
</iq>

DEBUG:yowsup.layers.logger.layer:tx:
<message to="5553981436776@s.whatsapp.net" type="media" id="1496050838-2">
<media mimetype="i" filehash="wXtOst6e9AtI141aejo0jgIFQK2WSFAEiP5FLHS/zqY=" enco                                                                                                                ding="raw" url="https://mmi339.whatsapp.net/d/Ak4NtC4f89azEx-_t3C3hLQmy08VQdaUwH                                                                                                                rwPzb6sIwF.jpg" height="800" width="800" file="geb.jpg" type="image" size="11251                                                                                                                7">
(...)
</media>
</message>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="s.whatsapp.net" id="1">
<duplicate mimetype="image/jpeg" filehash="wXtOst6e9AtI141aejo0jgIFQK2WSFAEiP5FL                                                                                                                HS/zqY=" url="https://mmi339.whatsapp.net/d/Ak4NtC4f89azEx-_t3C3hLQmy08VQdaUwHrw                                                                                                                Pzb6sIwF.jpg" height="800" width="800" type="image" size="112517">
</duplicate>
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<ack t="1496050839" from="5553981436776@s.whatsapp.net" class="message" id="1496                                                                                                                050838-2">
</ack>

[connected]:[connected]:Sent: 1496050838-2
[connected]:
DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w:p" type="get" id="3">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="5553xxxxxxxx@s.whatsapp.net" id="3" t="1496050888">
</iq>

Iq:
ID: 3
Type: result
from: 5553xxxxxxxx@s.whatsapp.net

DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="w:p" type="get" id="4">
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="result" from="5553xxxxxxxx@s.whatsapp.net" id="4" t="1496050938">
</iq>

Iq:
ID: 4
Type: result
from: 5553xxxxxxxx@s.whatsapp.net

(loop where nothing happens...)

**Comment by rodrigoorrego** [comment]
I'm lost :(

**Comment by prats69** [comment]
i am also not able to send images. I am sending using yowsup-cli demos.
 /L
/image send 9xxxxxxxxx /home/path/img.jpg [press enter]
it says Sent: {timestamp}

but the image never comes to my number.

Any help would be appreciated.

**Comment by avinashajith** [comment]
The image is sent but on the receiving number no image is received.

**Comment by hgc2002** [comment]
See [issue 2149](https://github.com/tgalal/yowsup/issues/2149)
It's not solved yet, but coming.
