### ISSUE TITLE
yowsup-cli demo run  connection refused

### ISSUE THREAD

**Issue by magdalia2016** [tgalal/yowsup#2100]
Before I run it but after few days I could not run yowsup-cli

File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 446, in handle_read_event
    self.handle_connect_event()
  File "/usr/lib/python2.7/asyncore.py", line 454, in handle_connect_event
    raise socket.error(err, _strerror(err))
socket.error: [Errno 111] Connection refused

**Comment by zilverback** [comment]
I have the same error


I 2020-06-15 12:30:34,337 yowsup.layers.network.layer - Connecting to e8.whatsapp.net:443
E 2020-06-15 12:30:39,867 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 446, in handle_read_event
    self.handle_connect_event()
  File "/usr/lib/python2.7/asyncore.py", line 454, in handle_connect_event
    raise socket.error(err, _strerror(err))
error: [Errno 111] Connection refused
