### ISSUE TITLE
registration Connection reset

### ISSUE THREAD

**Issue by ykguCoder** [tgalal/yowsup#2181]
It works a few days ago,
my command :
yowsup-cli registration --requestcode sms --phone ***** --cc ** --mcc *** --mnc ** -E android

and my env :
_MD5_CLASSES = "1naz8gL5pIYWbtaOZ3207g=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.17.16"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "armani"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"
    _AXOLOTL = True

the error :
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 189, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/bin/yowsup-cli", line 208, in handleRequestCode
    result = codeReq.send()
  File "/usr/local/lib/python2.7/site-packages/yowsup/registration/coderequest.py", line 53, in send
    result = request.send()
  File "/usr/local/lib/python2.7/site-packages/yowsup/registration/existsrequest.py", line 37, in send
    res = super(WAExistsRequest, self).send(parser)
  File "/usr/local/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 73, in send
    if isinstance(parser, ResponseParser):
  File "/usr/local/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 111, in sendGetRequest
    logger.error("Request not success, status was %s"%self.response.status)
  File "/usr/local/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 181, in sendRequest
    
  File "/usr/local/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/local/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/local/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/local/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/local/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
socket.error: [Errno 104] Connection reset by peer

who can help me~~~
Thanks so much

**Comment by coolnickname** [comment]
Try to repull Yowsup, that way your changes will be gone but you might fix it.On 2 Aug 2017 9:50 am, ykguCoder <notifications@github.com> wrote:It works a few days ago,
my command :
yowsup-cli registration --requestcode sms --phone ***** --cc ** --mcc *** --mnc ** -E android
and my env :
_MD5_CLASSES = "1naz8gL5pIYWbtaOZ3207g=="
_KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="
_VERSION = "2.17.16"
_OS_NAME = "Android"
_OS_VERSION = "4.3"
_DEVICE_NAME = "armani"
_MANUFACTURER = "Xiaomi"
_BUILD_VERSION = "JLS36C"
_AXOLOTL = True

the error :
Traceback (most recent call last):
File "/usr/bin/yowsup-cli", line 368, in 
if not parser.process():
File "/usr/bin/yowsup-cli", line 189, in process
self.handleRequestCode(self.args["requestcode"], config)
File "/usr/bin/yowsup-cli", line 208, in handleRequestCode
result = codeReq.send()
File "/usr/local/lib/python2.7/site-packages/yowsup/registration/coderequest.py", line 53, in send
result = request.send()
File "/usr/local/lib/python2.7/site-packages/yowsup/registration/existsrequest.py", line 37, in send
res = super(WAExistsRequest, self).send(parser)
File "/usr/local/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 73, in send
if isinstance(parser, ResponseParser):
File "/usr/local/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 111, in sendGetRequest
logger.error("Request not success, status was %s"%self.response.status)
File "/usr/local/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 181, in sendRequest
File "/usr/local/lib/python2.7/httplib.py", line 1001, in request
self._send_request(method, url, body, headers)
File "/usr/local/lib/python2.7/httplib.py", line 1035, in _send_request
self.endheaders(body)
File "/usr/local/lib/python2.7/httplib.py", line 997, in endheaders
self._send_output(message_body)
File "/usr/local/lib/python2.7/httplib.py", line 850, in _send_output
self.send(msg)
File "/usr/local/lib/python2.7/httplib.py", line 812, in send
self.connect()
File "/usr/local/lib/python2.7/httplib.py", line 1212, in connect
server_hostname=server_hostname)
File "/usr/local/lib/python2.7/ssl.py", line 350, in wrap_socket
_context=self)
File "/usr/local/lib/python2.7/ssl.py", line 566, in init
self.do_handshake()
File "/usr/local/lib/python2.7/ssl.py", line 788, in do_handshake
self._sslobj.do_handshake()
socket.error: [Errno 104] Connection reset by peer
who can help me~~~
Thanks so much
