### ISSUE TITLE
how to receive multimidia messgae?

### ISSUE THREAD

**Issue by manojrao** [tgalal/yowsup#2206]
hello everyone how to get a symily message. 
my error is Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    stack.start()
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/demos/echoclient/stack.py", line 21, in start
    self.stack.loop()
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/local/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/local/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/local/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 86, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 129, in handlePreKeyWhisperMessage
    self.parseAndHandleMessageProto(pkMessageProtocolEntity, plaintext[:-padding])
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 188, in parseAndHandleMessageProto
    self.handleConversationMessage(node, m.conversation)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 217, in handleConversationMessage
    self.toUpper(messageNode)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/protocol_messages/layer.py", line 21, in recvMessageStanza
    self.toUpper(entity) 
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/demos/echoclient/layer.py", line 85, in onMessage
    self.onTextMessage(messageProtocolEntity)
  File "/usr/local/lib/python2.7/site-packages/yowsup-master/yowsup/demos/echoclient/layer.py", line 99, in onTextMessage
    print messageProtocolEntity
UnicodeEncodeError: 'ascii' codec can't encode characters in position 118-121: ordinal not in range(128)

please guide me

**Comment by jegue** [comment]
reload(sys)
sys.setdefaultencoding('utf8')

on echoclient/layer.py

**Comment by tgalal** [comment]
fixed
