### ISSUE TITLE
Exception in thread Thread-1: ValueError: No closing quotation

### ISSUE THREAD

**Issue by fsarihan** [tgalal/yowsup#2218]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yowsup/yowsup/demos/cli/cli.py", line 154, in startInputThread
    wait = self.execCmd(cmd)
  File "/home/yowsup/yowsup/demos/cli/cli.py", line 115, in execCmd
    cmdInputDissect = [c for c in shlex.split(cmdInput) if c]
  File "/usr/local/lib/python3.6/shlex.py", line 305, in split
    return list(lex)
  File "/usr/local/lib/python3.6/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/usr/local/lib/python3.6/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/usr/local/lib/python3.6/shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
```

**Comment by tgalal** [comment]
exactly what it say, your input had no closing quotation
