### ISSUE TITLE
No reciver multimedia message

### ISSUE THREAD

**Issue by jeffersonsc** [tgalal/yowsup#2232]
Traceback (most recent call last):
  File "/home/help/anaconda3/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/home/help/anaconda3/bin/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/home/help/anaconda3/bin/yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/home/help/anaconda3/lib/python3.6/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/home/help/anaconda3/lib/python3.6/asyncore.py", line 150, in poll
    read(obj)
  File "/home/help/anaconda3/lib/python3.6/asyncore.py", line 87, in read
    obj.handle_error()
  File "/home/help/anaconda3/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/home/help/anaconda3/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 88, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 144, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "/home/help/anaconda3/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 204, in parseAndHandleMessageProto
    raise ValueError("Unhandled")
ValueError: Unhandled

**Comment by sealabr** [comment]
thats right...  this repo doesn't have implemetation for receiving encrypted media...

You might use some parts of https://github.com/jlguardi/yowsup
getExtension-method of common/tools.py

in folder layers/protocol_media/protocolentities/
message_media_downloadable.py
message_media_downloadable_image.py

I think this might help.

EDIT:
Or just see #1713
