### ISSUE TITLE
send Broadcast text massage

### ISSUE THREAD

**Issue by holgerschochwitz** [tgalal/yowsup#2250]
Hi,
in the past i changed the sendclient/layer,py:

            if ',' in phone: 
               jids = [Jid.normalize(number) for number in phone.split(',')]
	       messageEntity = BroadcastTextMessage(jids, message)
            else:
               messageEntity = TextMessageProtocolEntity(message, to = Jid.normalize(phone))

Now i get this error massages:

Traceback (most recent call last):
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup-cli", line 324, in startSendClient
    stack.start()
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib64/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib64/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/axolotl/layer_send.py", line 64, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/__init__.py", line 163, in processIqRegistry
    errorClbk(protocolTreeNode, originalIq)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/axolotl/layer_base.py", line 81, in onError
    errorClbk(errorNode, getKeysEntity)
TypeError: <lambda>() takes no arguments (2 given)

Thanks

**Comment by holgerschochwitz** [comment]
When i Change in file 'layers/Axolotl/layer_base.py' this:
errorClbk(errorNode, getKeysEntity)
to: errorClbk(errorNode . getKeysEntity)

than i get this error massage:

  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/__init__.py"ine 163, in processIqRegistry
    errorClbk(protocolTreeNode, originalIq)
  File "/var/www/vhosts/sg1948schochwitz.de/httpdocs/yowsup/yowsup/layers/axolotl/layease.py", line 81, in onError
    errorClbk(errorNode . getKeysEntity)
AttributeError: 'ProtocolTreeNode' object has no attribute 'getKeysEntity'

**Comment by ykguCoder** [comment]
hello,could you register success?

**Comment by holgerschochwitz** [comment]
Yes, the send function works without Problems.

**Comment by pabloruan0710** [comment]
I received this erro after try broadcast:

```
<iq type="error" from="s.whatsapp.net" id="2">
<error text="not-acceptable" code="406">
</error>
</iq>
```

**Comment by pabloruan0710** [comment]
+1

**Comment by xhijack** [comment]
have it solved?

**Comment by bindu144** [comment]
@pabloruan0710 @holgerschochwitz found any solution for this?
