### ISSUE TITLE
TypeError: Error when calling the metaclass bases

### ISSUE THREAD

**Issue by zarin-raim** [tgalal/yowsup#2259]
Hi, 
I'm getting this error while trying to register phone number
```
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.5.2', 'yowsup-cli')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/env/env.py", line 15, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib64/python2.7/abc.py", line 87, in __new__
    cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by ykguCoder** [comment]
the same problem

**Comment by alvarollmenezes** [comment]
same here

**Comment by plam4u** [comment]
same here

**Comment by thaihau** [comment]
dont use python2.7, change to use python3.X

```
sudo apt-get install python3-setuptools
sudo python3  setup.py install
```

**Comment by plam4u** [comment]
thanks @thaihau 
this solved the issue for me.

**Comment by JackLeo** [comment]
This is because of https://github.com/benjaminp/six/issues/210
Downgrading six is a temporary workaround

```
pip install six==1.10
```

**Comment by 83lipe** [comment]
same... not solve with python3 and not pip install six==1.10

**Comment by r0alt** [comment]
dont use python2.7, change to use python3.X

sudo apt-get install python3-setuptools
sudo apt-get install python3-pip         <-- dev-packages also needed
sudo python3  setup.py install

**Comment by yoko83** [comment]
Works with 2.7

**Comment by vlad2** [comment]
@JackLeo  using python 2.7 and six 1.10 solved the problem.

**Comment by jupitercl** [comment]
Solved Downgrading six
Thanks @JackLeo

**Comment by noahfx** [comment]
Hi 
I've submitted a PR that fixes the compatibility with six >= 1.11 https://github.com/tgalal/yowsup/pull/2379

**Comment by Gabedu2000** [comment]
@thaihau Thanks!

**Comment by jairoccjunior** [comment]
# yowsup-cli version
.....
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

this error is solved with #pip install six==1.10

but showed new error:

# yowsup-cli demos --yowsup --config config --debug
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/usr/bin/yowsup-cli", line 290, in startCmdline
    from yowsup.demos import cli
  File "/usr/lib/python2.6/site-packages/yowsup2-2.5.7-py2.6.egg/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/usr/lib/python2.6/site-packages/yowsup2-2.5.7-py2.6.egg/yowsup/demos/cli/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/usr/lib/python2.6/site-packages/yowsup2-2.5.7-py2.6.egg/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/usr/lib/python2.6/site-packages/yowsup2-2.5.7-py2.6.egg/yowsup/stacks/yowstack.py", line 10, in <module>
    from yowsup.layers.protocol_media              import YowMediaProtocolLayer
  File "/usr/lib/python2.6/site-packages/yowsup2-2.5.7-py2.6.egg/yowsup/layers/protocol_media/__init__.py", line 1, in <module>
    from .layer import YowMediaProtocolLayer 
  File "/usr/lib/python2.6/site-packages/yowsup2-2.5.7-py2.6.egg/yowsup/layers/protocol_media/layer.py", line 2, in <module>
    from .protocolentities import ImageDownloadableMediaMessageProtocolEntity
  File "/usr/lib/python2.6/site-packages/yowsup2-2.5.7-py2.6.egg/yowsup/layers/protocol_media/protocolentities/__init__.py", line 3, in <module>
    from .message_media_downloadable_image import ImageDownloadableMediaMessageProtocolEntity
  File "/usr/lib/python2.6/site-packages/yowsup2-2.5.7-py2.6.egg/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_image.py", line 4, in <module>
    from yowsup.layers.protocol_messages.proto.wa_pb2 import ImageMessage
  File "/usr/lib/python2.6/site-packages/yowsup2-2.5.7-py2.6.egg/yowsup/layers/protocol_messages/proto/wa_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
  File "/usr/lib/python2.6/site-packages/google/protobuf/symbol_database.py", line 62, in <module>
    from google.protobuf import message_factory
  File "/usr/lib/python2.6/site-packages/google/protobuf/message_factory.py", line 142
    file_by_name = {file_proto.name: file_proto for file_proto in file_protos}
                                                  ^
SyntaxError: invalid syntax

any idea, what could it be?

**Comment by rodrigolopezguerra** [comment]
@JackLeo thanks, that did it!
