### ISSUE TITLE
Echoclient crashes if an image is sent to it

### ISSUE THREAD

**Issue by manzari** [tgalal/yowsup#2260]
Hello, I am kinda new to Python and I got echoing text messages to work but when sending an image to [Echoclient](https://github.com/tgalal/yowsup/tree/master/yowsup/demos/echoclient), it crashes with below Traceback.
Can anything be done to fix described behaviour?

#### Traceback
```
Traceback (most recent call last):
  File "/home/user/yowsuptest/run.py", line 6, in <module>
    stack.start()
  File "/home/user/yowsuptest/stack.py", line 21, in start
    self.stack.loop()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.5/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.5/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib/python3.5/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 88, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 144, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 200, in parseAndHandleMessageProto
    self.handleImageMessage(node, m.image_message)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 237, in handleImageMessage
    self.toUpper(messageNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/protocol_media/layer.py", line 42, in recvMessageStanza
    self.toUpper(entity)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/home/user/yowsuptest/layer.py", line 13, in onMessage
    self.toLower(messageProtocolEntity.forward(messageProtocolEntity.getFrom()))
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 136, in send
    send(entity)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/protocol_media/layer.py", line 35, in sendMessageEntity
    self.entityToLower(entity)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 140, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_send.py", line 61, in send
    self.toLower(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_control.py", line 34, in send
    self.toLower(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/logger/layer.py", line 8, in send
    logger.debug("tx:\n%s" % ldata)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/structs/protocoltreenode.py", line 88, in __str__
    return self.toString()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/structs/protocoltreenode.py", line 80, in toString
    out += c.toString()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/structs/protocoltreenode.py", line 55, in toString
    out+= " "+key+'="'+val+'"'
TypeError: Can't convert 'bytes' object to str implicitly
Traceback (most recent call last):
  File "/home/user/yowsuptest/run.py", line 6, in <module>
    stack.start()
  File "/home/user/yowsuptest/stack.py", line 21, in start
    self.stack.loop()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.5/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.5/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib/python3.5/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 88, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 144, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 200, in parseAndHandleMessageProto
    self.handleImageMessage(node, m.image_message)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 237, in handleImageMessage
    self.toUpper(messageNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/protocol_media/layer.py", line 42, in recvMessageStanza
    self.toUpper(entity)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/home/user/yowsuptest/layer.py", line 13, in onMessage
    self.toLower(messageProtocolEntity.forward(messageProtocolEntity.getFrom()))
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 136, in send
    send(entity)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/protocol_media/layer.py", line 35, in sendMessageEntity
    self.entityToLower(entity)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 140, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_send.py", line 61, in send
    self.toLower(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_control.py", line 34, in send
    self.toLower(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/logger/layer.py", line 8, in send
    logger.debug("tx:\n%s" % ldata)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/structs/protocoltreenode.py", line 88, in __str__
    return self.toString()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/structs/protocoltreenode.py", line 80, in toString
    out += c.toString()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/structs/protocoltreenode.py", line 55, in toString
    out+= " "+key+'="'+val+'"'
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by syavcin** [comment]
protocoltreenode.py  line 55 Replace 

`out+= " "+str(key)+'="'+str(val)+'"'`

**Comment by tgalal** [comment]
fixed
