### ISSUE TITLE
Yowsup won't connect, error in iq_crypto.py, line 10, in toProtocolTreeNode : 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by arneman** [tgalal/yowsup#2265]
After getting yowsup to work a few hours ago, I made some updates to the system and now it wont work anymore.

I assume there's an issue with python3 (Python 3.4.2)?

```
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Yowsup Cli client
Type /help for available commands

[offline]:/seq
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/demos/cli/cli.py", line 154, in startInputThread
    wait = self.execCmd(cmd)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/demos/cli/cli.py", line 138, in execCmd
    return self.doExecCmd(lambda :targetFn(*args))
  File "/usr/local/lib/python3.4/dist-packages/yowsup/demos/cli/cli.py", line 141, in doExecCmd
    return fn()
  File "/usr/local/lib/python3.4/dist-packages/yowsup/demos/cli/cli.py", line 138, in <lambda>
    return self.doExecCmd(lambda :targetFn(*args))
  File "/usr/local/lib/python3.4/dist-packages/yowsup/demos/cli/layer.py", line 353, in seq
    self.toLower(crypto)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/__init__.py", line 136, in send
    send(entity)
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/protocol_iq/layer.py", line 36, in sendIq
    self.toLower(entity.toProtocolTreeNode())
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/protocol_iq/protocolentities/iq_crypto.py", line 10, in toProtocolTreeNode
    googleNode = ProtocolTreeNode("google", data = "fe5cf90c511fb899781bbed754577098e460d048312c8b36c11c91ca4b49ca34".decode('hex'))
AttributeError: 'str' object has no attribute 'decode'
```

```
pip3 list
chardet (2.3.0)
colorama (0.3.2)
gpiozero (1.4.0)
html5lib (0.999)
mcpi (0.1.1)
numpy (1.8.2)
pgzero (1.1)
picamera (1.13)
pifacecommon (4.2.1)
pifacedigitalio (3.1.0)
Pillow (2.6.1)
pip (9.0.1)
protobuf (3.4.0)
pycrypto (2.6.1)
pygame (1.9.2a0)
pyserial (2.6)
python-apt (0.9.3.12)
python-axolotl (0.1.39)
python-axolotl-curve25519 (0.1)
python-dateutil (2.6.1)
python-debian (0.1.27)
requests (2.4.3)
RPi.GPIO (0.6.3)
RTIMULib (7.2.1)
sense-hat (2.2.0)
setuptools (36.5.0)
six (1.11.0)
spidev (3.0)
urllib3 (1.9.1)
wheel (0.24.0)
yowsup2 (2.5.2)
```

**Comment by arneman** [comment]
change layers/protocol_iq/protocolentities/iq_crypto.py" line 11 from

`googleNode = ProtocolTreeNode("google", data = "fe5cf90c511fb899781bbed754577098e460d048312c8b36c11c91ca4b49ca34".decode('hex'))`

to

`googleNode = ProtocolTreeNode("google", data = "fe5cf90c511fb899781bbed754577098e460d048312c8b36c11c91ca4b49ca34")`

fixes the issue

**Comment by tgalal** [comment]
fixed
