### ISSUE TITLE
ValueError: Unkown ib node <ib from="s.whatsapp.net">

### ISSUE THREAD

**Issue by leoxzl** [tgalal/yowsup#2270]
yowsup-cli command can't to send, pls help! 

yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.layers.axolotl.layer_control:Axolotl layer is generating keys
Traceback (most recent call last):
  File "/root/anaconda3/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/root/anaconda3/bin/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/root/anaconda3/bin/yowsup-cli", line 324, in startSendClient
    stack.start()
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/root/anaconda3/lib/python3.6/asyncore.py", line 150, in poll
    read(obj)
  File "/root/anaconda3/lib/python3.6/asyncore.py", line 87, in read
    obj.handle_error()
  File "/root/anaconda3/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/root/anaconda3/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 52, in processReceived
    self.processReceived()
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/root/anaconda3/lib/python3.6/site-packages/yowsup/layers/protocol_ib/layer.py", line 27, in recvIb
    raise ValueError("Unkown ib node %s" % node)
ValueError: Unkown ib node <ib from="s.whatsapp.net">
<fbip>
52.57.240.222|443|1506402728|90000|true|false,52.3.243.37|443|1506402728|90000|true|false
HEX3:b'35322e35372e3234302e3232327c3434337c313530363430323732387c39303030307c747275657c66616c73652c35322e332e3234332e33377c3434337c313530363430323732387c39303030307c747275657c66616c7365'
</fbip>
</ib>

**Comment by neorai** [comment]
try different versions of python 2.6 or 3.5

**Comment by leoxzl** [comment]
@neorai, I have several vps running python 3.6,Has been no problem,These days began to appear this problem,I do not know why there is an error. help!

**Comment by mathslimin** [comment]
modify
yowsup/layers/protocol_ib/layer.py
change line 27 to
# raise ValueError("Unkown ib node %s" % node)
print("Unknow ib node %s"%node)

re run the program, it works!

**Comment by javad329** [comment]
Did you change "raise ValueError("Unkown ib node %s" % node)" to "print("Unknow ib node %s"%node)" ?
It didn't work for me.

**Comment by chbinghu** [comment]
Does anyone know how to solve this? change raise to print does not work.

**Comment by tgalal** [comment]
fca99c46ea11c570136f64e44e31cf9581ede296
