### ISSUE TITLE
Cannot start Yowsup with python3

### ISSUE THREAD

**Issue by drixbarsali** [tgalal/yowsup#2277]
I do not know what's missing. 
It only starts when I use python without 3. 
But it does not send media.

`root@lab:/yowsup# python3 yowsup-cli demos -y  -c /etc/yowsup/config.conf
Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 268, in process
    self.startCmdline()
  File "yowsup-cli", line 290, in startCmdline
    from yowsup.demos import cli
  File "/yowsup/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/yowsup/yowsup/demos/cli/stack.py", line 2, in <module>
    from .layer import YowsupCliLayer
  File "/yowsup/yowsup/demos/cli/layer.py", line 2, in <module>
    from yowsup.layers.interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/yowsup/yowsup/layers/interface/__init__.py", line 1, in <module>
    from .interface import YowInterfaceLayer, ProtocolEntityCallback
  File "/yowsup/yowsup/layers/interface/interface.py", line 5, in <module>
    from yowsup.layers.protocol_media.mediauploader import MediaUploader
  File "/yowsup/yowsup/layers/protocol_media/mediauploader.py", line 17, in <module>
    import md5
ImportError: No module named 'md5'
`

Thanks

**Comment by drixbarsali** [comment]
Solved with https://github.com/tgalal/yowsup/issues/1884#issuecomment-275150808
