### ISSUE TITLE
Image Error

### ISSUE THREAD

**Issue by syavcin** [tgalal/yowsup#2289]
Hi

I have a problem. 

 `python yowsup-cli demos --config whatsapp_config.txt --echo`

```
Echoing image b'https://mmg-fna.whatsapp.net/d/f/AjSACSmF0nmkWaKyGPiK8wlDWQ8PJHXwh9oRPDXmllI_.enc' to 905330413660
Traceback (most recent call last):
  File "yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.2', 'yowsup-cli')
  File "C:\Users\Cc\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "c:\users\cc\anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\EGG-INFO\scripts\yowsup-cli", line 368, in <module>
    if not parser.process():
  File "c:\users\cc\anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\EGG-INFO\scripts\yowsup-cli", line 270, in process
    self.startEcho()
  File "c:\users\cc\anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\EGG-INFO\scripts\yowsup-cli", line 308, in startEcho
    stack.start()
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\demos\echoclient\stack.py", line 21, in start
    self.stack.loop()
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\stacks\yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "C:\Users\Cc\Anaconda3\lib\asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "C:\Users\Cc\Anaconda3\lib\asyncore.py", line 150, in poll
    read(obj)
  File "C:\Users\Cc\Anaconda3\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Users\Cc\Anaconda3\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Users\Cc\Anaconda3\lib\asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\network\layer.py", line 102, in handle_read
    self.receive(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\network\layer.py", line 110, in receive
    self.toUpper(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\stanzaregulator\layer.py", line 29, in receive
    self.processReceived()
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\stanzaregulator\layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\auth\layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\axolotl\layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 194, in receive
    s.receive(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\axolotl\layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\axolotl\layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\axolotl\layer_receive.py", line 88, in handleEncMessage
    self.handleWhisperMessage(node)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\axolotl\layer_receive.py", line 144, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\axolotl\layer_receive.py", line 200, in parseAndHandleMessageProto
    self.handleImageMessage(node, m.image_message)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\axolotl\layer_receive.py", line 237, in handleImageMessage
    self.toUpper(messageNode)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 194, in receive
    s.receive(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 130, in receive
    recv(node)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\protocol_media\layer.py", line 42, in recvMessageStanza
    self.toUpper(entity)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\interface\interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\demos\echoclient\layer.py", line 13, in onMessage
    self.toLower(messageProtocolEntity.forward(messageProtocolEntity.getFrom()))
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 198, in send
    s.send(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 136, in send
    send(entity)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\protocol_media\layer.py", line 35, in sendMessageEntity
    self.entityToLower(entity)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 140, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 198, in send
    s.send(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\axolotl\layer_send.py", line 61, in send
    self.toLower(node)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\axolotl\layer_control.py", line 34, in send
    self.toLower(node)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\layers\logger\layer.py", line 8, in send
    logger.debug("tx:\n%s" % ldata)
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\structs\protocoltreenode.py", line 88, in __str__
    return self.toString()
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\structs\protocoltreenode.py", line 80, in toString
    out += c.toString()
  File "C:\Users\Cc\Anaconda3\lib\site-packages\yowsup2-2.5.2-py3.6.egg\yowsup\structs\protocoltreenode.py", line 55, in toString
    out+= " "+key+'="'+val+'"'
TypeError: must be str, not bytes

```

**Comment by PedroFcul** [comment]
that particular error is probably because key and val are bytes, switch that line to 
out+= " " + str(key) + "='"+str(val)+"'"

**Comment by syavcin** [comment]
thanx all right how is save in image ?
