### ISSUE TITLE
Convert virtual number from emulator to hash for yowsup

### ISSUE THREAD

**Issue by cyberp1983** [tgalal/yowsup#2309]
Need HELP. on the emulator in Whatsapp registered virtual number, it is very necessary to convert it into hagh for work with yowsup.

**Comment by cyberp1983** [comment]
$100

**Comment by bryanjhv** [comment]
I think he registered a number with WhatsApp on Android, running an emulator, and wants to extract its account password in the format Yowsup expects it to be, for use with `yowsup-cli` or via programming.

**Comment by cyberp1983** [comment]
right)

**Comment by bryanjhv** [comment]
You'll need ADB installed and the phone rooted (tip: if using Genymotion, bundles it, so you're ready to go). Then you need to extract two files: `key` and `me`. The first one contains your encrypted password, the other one contains your basic WhatsApp profile (a Jabber ID), which you need later.
```bash
adb pull /data/data/com.whatsapp/files/me me     # Extract profile
adb pull /data/data/com.whatsapp/files/key key   # Extract password
```

Then, you need to have Python 2 installed, then install following packages (I do it the `pip` way):
```bash
pip install pbkdf2 pycrypto javaobj
```

Finally, download this script (taken from [here](https://github.com/tgalal/yowsup/issues/234#issue-29683578)), and run it from the same directory as pulled files:
```python
from pbkdf2 import PBKDF2
from base64 import b64encode
from Crypto.Cipher import AES
from javaobj import JavaObjectUnmarshaller

sauce = '\xc2\x99\x1e\xc2\x9b\x1d\x0c\xc2\xb8\xc3\xb7\x55\x64\x58\xc2\x98\xc2\x92\x03\xc2\x8b\x45\xc2\x97\x3e\x78\xc3\x86\xc3\x95'

if __name__ == '__main__':
    # Info reading
    keybuf = JavaObjectUnmarshaller(open('key')).readObject()
    numtxt = JavaObjectUnmarshaller(open('me')).readObject().jabber_id
    keytxt = ''.join([chr(c) if c >= 0 else chr(c + 256) for c in keybuf])

    # Begin decoding
    iv = keytxt[6:22]
    salt = keytxt[2:6]
    enkey = keytxt[22:]
    fekey = PBKDF2(sauce + numtxt, salt, 16).read(16)
    crypt = AES.new(fekey, AES.MODE_OFB, iv)

    # Finalize it all
    key = crypt.decrypt(enkey + '1' * 12)[:20]  # Change 12 to less that works
    print 'The password is: %s' % b64encode(key)
```

That should print the password ready to be fed into Yowsup. 😄

**Comment by cyberp1983** [comment]
not workin :(
The password is: mC32F1Jn0RDR9imY8hy2m9k4pWY=

python C:\yowsup-master\yowsup-cli demos -l 79671101463:mC32F1Jn0RDR9imY8hy2m9k4pWY= -e
Authentication Error: not-authorized

**Comment by bryanjhv** [comment]
Try quoting the `-l` value, so it doesn't get scaped by any shell thing (I remember `=` has special meaning in `cmd`).

**Comment by bryanjhv** [comment]
Also, remember the phone number must go with the country code, so please append that.
(and, as a recommendation, hide your data from the comment, as many people can use it for bad)

**Comment by cyberp1983** [comment]
Method does not work( can Anyone help finish?

**Comment by bryanjhv** [comment]
Well, I used that method and worked. If it's not working, you're better off pasting the error here, so anyone can help.
By the way, I stored the auth details in a file to avoid problems with shell, like this:

```ini
cc=777                   # Country code
phone=777xxxxxxxxx       # Phone number with country code
password=xxxxxxxxxxxxx   # Raw b64 password you got
```

And invoked the CLI like this:

```bash
yowsup-cli -c config.txt -e
```

**Comment by coolnickname** [comment]
@bryanjhv Sorry to kinda hijack this thead, but I felt it was related enough.

The script you sent gives me this error: 
```Python
Traceback (most recent call last):
  File "Extract.py", line 22, in <module>
    key = crypt.decrypt(enkey + '1' * 8)[:20]  # Change 12 to less that works
  File "/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length
```
So the line throwing the exception is
```Python
key = crypt.decrypt(enkey + '1' * 8)[:20]  # Change 12 to less that works
```
And I did try to change 12 to lower values, but to no luck.

I have no idea what's even happening in this script so I can't debug it myself.

**Comment by bryanjhv** [comment]
@coolnickname That error is related to AES decription, saying that the parameter must have a multiple of 16 characters.
You should try decreasing 12 to a value, even 0, until it matches. (there's another way to calculate that automatically but I'm lazy to do that)

**Comment by jlguardi** [comment]
You could use:
```
refkey + '1'*(len(refkey)%16)
```

**Comment by bryanjhv** [comment]
No, S40 is still supported, but I have two phones, one Firefox OS (which uses [Loqui IM](https://github.com/loqui/im) with S40 env (It's kind of Yowsup fork), and just tried with the key I got from that device. Didn't tried with the Android one, really, and the version in this repository is too old. Hope someone can submit a PR for that, because I'm almost sure the flag `-E android` solves that weird `AuthError` with the right keys and version set.

**Comment by bryanjhv** [comment]
Seems like the proposed changes from https://github.com/tgalal/yowsup/pull/2340/files should do the trick, if someone can test. (and maybe S40->Android change isn't needed with that)

**Comment by coolnickname** [comment]
@bryanjhv I tested those changes with both S40 and Android environments but no luck.

**Comment by bryanjhv** [comment]
I remember that MD5 classes thing also take part in the process (for Android env), so you can search how to generate them, and if it works maybe also submit a PR. 😄

**Comment by bryanjhv** [comment]
I'll take a look at it. Maybe WhatsApp is screwing things again.

**Comment by coolnickname** [comment]
So I did a little testing and came out on this conclusion:
The passwords generated from this script look legit, but give a `not-authorized` error with no message body. I've tried to stop the Whatsapp process on my phone (By force stopping the app and by shutting down my phone).

However I'm not banned because if I use Yowsup to register a new password everything works fine.

**Comment by bryanjhv** [comment]
I realized that. There should be, however, a way to make it work. As I said, using LoquiIM, got the password from the device directly and it worked fine. I don't know if any case still using S40 env in real life works like that. Maybe we need to inspect some Android things that WhatsApp does in order to validate a password.

**Comment by cyberp1983** [comment]
I'm still ready to pay $ 100 for this task!!!

**Comment by lazyjohny500** [comment]
As @coolnickname said, The password I got look legit but give a not-authorized error :\

**Comment by lazyjohny500** [comment]
@bryanjhv Im not sure I understand what you said. The success is depend on the env I used?

**Comment by bryanjhv** [comment]
I meant: it looks like that if you register the number (i.e. get a password) from an Android device, then you'll need to force Yowsup to use Android env, even if S40 env works most of the time and still is the default. I may be wrong, but as I said, if I register my number on LoquiIM (uses a JavaScript port of Yowsup to work in FirefoxOS), and then use S40 env with Yowsup, then it works out of the box.

**Comment by SaadeMotion** [comment]
Maybe whatsapp changed something.... Not working here too. (Not using yowsup api)

**Comment by bryanjhv** [comment]
https://github.com/EliteAndroidApps/WhatsApp-Key-DB-Extractor

**Comment by netfiretec** [comment]
@bryanjhv That's not what I'm looking for.
I'm looking for a way to extract PW Hash (login password from whatsapp), extract from android.
