### ISSUE TITLE
TypeError: Error when calling the metaclass bases

### ISSUE THREAD

**Issue by MykeNogueira** [tgalal/yowsup#2325]
Been trying to set up yowsup-cli on Ubuntu 14.06 LTS, but haven't got past the registration so far. 
First I installed from the repositories using `sudo apt-get install yowsup-cli`. It started, but when trying to register, it gave a error saying that was a old version and did not complete the operation. Then I been trying again using the instructions on the project GitHub main page, as follows:

Installation

    Requires python2.6+, or python3.0 +
    Required python packages: python-dateutil,
    Required python packages for end-to-end encryption: protobuf, pycrypto, python-axolotl-curve25519
    Required python packages for yowsup-cli: argparse, readline (or pyreadline for windows), pillow (for sending images)

Install using setup.py to pull all python dependencies, or using pip:

pip install yowsup2

And then, when typing `yowsup-cli` on Terminal, I get this error:

`Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.2', 'yowsup-cli')
  File "/home/myke/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/myke/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/yowsup/env/env.py", line 15, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python2.7/abc.py", line 87, in __new__
    cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`

 Won't start and I haven't got a clue of where it went wrong

**Comment by r0alt** [comment]
install python3
install python3-pip
and:
pyhton3 setup.py install
hope it works ;)

**Comment by tgalal** [comment]
fixed
