### ISSUE TITLE
yowsup-cli getting crashed

### ISSUE THREAD

**Issue by sah-anshu** [tgalal/yowsup#2351]
Traceback (most recent call last):
  File "/home/anshu/.local/bin/yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2-py2.7.egg/yowsup/env/env.py", line 15, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python2.7/abc.py", line 87, in __new__
    cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by sah-anshu** [comment]
fixed while using python3

**Comment by manojkumarlinux** [comment]
sudo vi /usr/bin/yowsup-cli

change in the first line   #!/usr/bin/python ---> #!/usr/bin/python3

  1 #!/usr/bin/python3
  2 __version__ = "2.0.15"
  3 __author__ = "Tarek Galal"
  
sudo pip3 install yowsup 

Done. it working.
