### ISSUE TITLE
Can't request registration

### ISSUE THREAD

**Issue by Dylan-Graham** [tgalal/yowsup#2352]
Have updated six==1.11.0 as: python setup.py install wasn't working with my previous version

Traceback (most recent call last):
  File "yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/home/dylan/yowsup/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/home/dylan/yowsup/yowsup/env/env.py", line 15, in <module>
    class YowsupEnv(with_metaclass(YowsupEnvType, object)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/home/dylan/yowsup/yowsup/env/env.py", line 12, in __init__
    YowsupEnv.registerEnv(cls)
NameError: global name 'YowsupEnv' is not defined

**Comment by tgalal** [comment]
still issue after latest update?

**Comment by Dylan-Graham** [comment]
Hi,

I haven't tried since the update, will give it a go in the new year.

Hope this finds you well.
