### ISSUE TITLE
yowsup-cli errors

### ISSUE THREAD

**Issue by timodeoirish** [tgalal/yowsup#2354]
Hey World,

I installed Nagios today and wanted to add a notification method via Whatsapp.
I followed the instructions and got the following errors:
(in my env_Android.py file I entered Whatsapp Version 2.17.426 and the M5 hash sum)
(My yowsup version: 2.5.2 (march 2017))
How can I fix the issues below?

```
**_Afer running yowsup-cli_**
Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 156, in process
    YowsupEnv.setEnv(self.args["env"])
  File "/home/nagios/yowsup/yowsup/env/env.py", line 33, in setEnv
    cls.__CURR = cls.__ENVS[envName]()
TypeError: Can't instantiate abstract class AndroidYowsupEnv with abstract methods getDeviceName, getManufacturer, getOSName, getOSVersion, getToken, getVersion, isAxolotlEnabled
```

`Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.5.2', 'yowsup-cli')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/env/__init__.py", line 2, in <module>
    from .env_android import AndroidYowsupEnv
  File "/usr/lib/python2.7/site-packages/yowsup2-2.5.2-py2.7.egg/yowsup/env/env_android.py", line 20
    _MD5_CLASSES = "OyTf9XK7xoJkKIxLgY6/Lw=="
    ^
IndentationError: unexpected indent`

**Comment by edsondario** [comment]
Try you send messages by yowsup-cli (shell)?

**Comment by tgalal** [comment]
you messed up the file when you changed it.  update yowsup and try again
