### ISSUE TITLE
Traceback (most recent call last):   File "yowsup-cli", line 6, in <module>     from yowsup.env import YowsupEnv   File "/home/vagrant/Desktop/Telegram/yowsup/yowsup/env/__init__.py", line 1, in <module>     from .env import YowsupEnv   File "/home/vagrant/Desktop/Telegram/yowsup/yowsup/env/env.py", line 3, in <module>     from six import with_metaclass ImportError: No module named 'six'

### ISSUE THREAD

**Issue by pkmk123** [tgalal/yowsup#2363]
How to resolve the below issue.

Traceback (most recent call last):
  File "yowsup-cli", line 6, in <module>
    from yowsup.env import YowsupEnv
  File "/home/vagrant/Desktop/Telegram/yowsup/yowsup/env/__init__.py", line 1, in <module>
    from .env import YowsupEnv
  File "/home/vagrant/Desktop/Telegram/yowsup/yowsup/env/env.py", line 3, in <module>
    from six import with_metaclass
ImportError: No module named 'six'

**Comment by sealabr** [comment]
RUN.........pip install six

**Comment by tgalal** [comment]
fixed
