### ISSUE TITLE
Error starting yowsup

### ISSUE THREAD

**Issue by nicopastorello** [tgalal/yowsup#2366]
Error starting yowsup.

Ubuntu 16.04
Python 2.7.12 

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.2', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1518, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/yowsup-cli' not found in metadata at '/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.2.egg-info'

**Comment by dbsdenis** [comment]
https://iamjagjeetubhi.wordpress.com/2017/09/21/how-to-use-yowsup-the-python-whatsapp-library-in-ubuntu/

**Comment by nicopastorello** [comment]
Unfortunately continuous with the same problem @dbsdenis @

**Comment by tgalal** [comment]
doesn't look like installed properly. try update, and reopen if it's still an issue
