### ISSUE TITLE
/L in yowsup-cli demos --y giving error

### ISSUE THREAD

**Issue by dkiran** [tgalal/yowsup#2382]
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.5.2', 'yowsup-cli')
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1236, in run_script
    exec(compile(open(script_filename).read(), script_filename, 'exec'), namespace, namespace)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/EGG-INFO/scripts/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/EGG-INFO/scripts/yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.2/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.2/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python3.2/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.2/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.2/asyncore.py", line 444, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/layers/coder/layer.py", line 33, in receive
    node = self.reader.getProtocolTreeNode(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/layers/coder/decoder.py", line 16, in getProtocolTreeNode
    return self.nextTreeInternal(data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/layers/coder/decoder.py", line 243, in nextTreeInternal
    attribs = self.readAttributes(attribCount, data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/layers/coder/decoder.py", line 174, in readAttributes
    value = self.readString(self.readInt8(data), data)
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/layers/coder/decoder.py", line 201, in readString
    return "".join(map(chr, self.readPacked8(token, data)))
  File "/usr/local/lib/python3.2/dist-packages/yowsup2-2.5.2-py3.2.egg/yowsup/layers/coder/decoder.py", line 83, in readPacked8
    val = ord(binascii.unhexlify("0%s" % char))
TypeError: 'str' does not support the buffer interface

**Comment by dkiran** [comment]
can some one help me please.

**Comment by suvadipg** [comment]
Getting the same issue. kindly help

**Comment by tgalal** [comment]
this looks like a bug in a yowsup fork you use. Try python 3, or use this upstream version
