### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getChild'

### ISSUE THREAD

**Issue by phenriquec** [tgalal/yowsup#2426]
Hi, 

I need help solving this error while sending a message
I tried to look for an answer in old issues but failed to find somthing that works.

`[connected]:/contacts sync +5533991069239
DEBUG:yowsup.layers.logger.layer:tx:
<iq id="13" type="get" xmlns="urn:xmpp:whatsapp:sync">
<sync sid="131623310520000000" index="0" last="true" mode="full" context="interactive">
<user>
+5533991069239
HEX3:b'2b35353333393931303639323339'
</user>
</sync>
</iq>

[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<iq from="5511976446206@s.whatsapp.net" type="result" id="13">
<sync index="0" sid="131623310520000000" last="true" wait="454989" version="1517853852830994">
<in>
<user jid="553391069239@s.whatsapp.net" is_biz="false">
+5533991069239
HEX3:b'2b35353333393931303639323339'
</user>
</in>
</sync>
</iq>

Iq:
ID: 13
Type: result
from: 5511976446206@s.whatsapp.net
Wait: 454989
Version: 1517853852830994
In Numbers: +5533991069239
Out Numbers:
Invalid Numbers:

/message send 5533991069239 Oi
DEBUG:yowsup.layers.logger.layer:tx:
<iq id="15" type="get" xmlns="encrypt" to="s.whatsapp.net">
<key>
<user jid="5533991069239@s.whatsapp.net">
</user>
</key>
</iq>

[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<iq from="s.whatsapp.net" type="result" id="15">
<list>
<user jid="5533991069239@s.whatsapp.net">
<registration>
Ã§K

HEX3:b'e74b0a1e'
</registration>
<type>

HEX3:b'05'
</type>
<identity>
ÂlÃ»>Â |Ã                     Â|<
         Ã¸!Â»CcM;jÂ¢   Â¿^ÂJÂ   M
HEX3:b'826c16fb3ea07cc4f821bb43634d3b6a0fa2030910bf5e9e4a8d8c7c103c0b4d'
</identity>
<skey>
<id>
Â¾&!
HEX3:b'be2621'
</id>
<value>
ÃªÂÃ­
     QÃyÃ¦Ã¸Ã§ÂÃÂ
                 HEX3:b'ea89ed0b1b7351d679e6f8e78bd0149dbcaa27f8f727898b9f1266f36eac3442'
</value>
<signature>
Â²EÂÃÃ)"Â²&Â§Ã
!Â,ÃÂ´,Â8iÂlu|6|Â±Â§2-ÃWnnÃ
                           HEX3:b'1c7fb245ab7f16c8d4291d22b226a7db85219c2cd0b42c883869926c757c367cb1a7322dd3576e6e327fdda808622d9a7c19fd2ce30b7a31bb48c5d2a82ca709'
</signature>
</skey>
</user>
</list>
</iq>

Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/usr/bin/yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/usr/lib/python3.6/site-packages/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/lib/python3.6/site-packages/yowsup/stacks/yowstack.py", line 189, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python3.6/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python3.6/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib64/python3.6/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib64/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/lib/python3.6/site-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_send.py", line 64, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 161, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_base.py", line 51, in onSuccess
    entity = ResultGetKeysIqProtocolEntity.fromProtocolTreeNode(resultNode)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 88, in fromProtocolTreeNode
    preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
AttributeError: 'NoneType' object has no attribute 'getChild'

`
![error](https://user-images.githubusercontent.com/7809203/35860296-ae2406d0-0b2a-11e8-96ee-a65e75efb445.png)

**Comment by phenriquec** [comment]
solved the problem
tks

**Comment by theoneandonly-vector** [comment]
how you solved it?
