### ISSUE TITLE
send message results in reconnect

### ISSUE THREAD

**Issue by HeinzFo** [tgalal/yowsup#2433]
Hello

Update: Yowsup 2.5.2 works the issue occurs with version 2.5.7

When I send a message with yowsup then yowsup do an reconnect the message will not be send.
Until the the next message is yowsup online.

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/yowsup-master/yowsup/demos/cli/cli.py", line 154, in startInputThread
    wait = self.execCmd(cmd)
  File "/opt/yowsup-master/yowsup/demos/cli/cli.py", line 138, in execCmd
    return self.doExecCmd(lambda :targetFn(*args))
  File "/opt/yowsup-master/yowsup/demos/cli/cli.py", line 141, in doExecCmd
    return fn()
  File "/opt/yowsup-master/yowsup/demos/cli/cli.py", line 138, in <lambda>
    return self.doExecCmd(lambda :targetFn(*args))
  File "/opt/yowsup-master/yowsup/demos/cli/layer.py", line 372, in message_send
    self.toLower(outgoingMessage)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 136, in send
    send(entity)
  File "/opt/yowsup-master/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 140, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/opt/yowsup-master/yowsup/layers/axolotl/layer_send.py", line 48, in send
    self.processPlaintextNodeAndSend(node)
  File "/opt/yowsup-master/yowsup/layers/axolotl/layer_send.py", line 95, in processPlaintextNodeAndSend
    self.sendToContact(node)
  File "/opt/yowsup-master/yowsup/layers/axolotl/layer_send.py", line 155, in sendToContact
    ciphertext = cipher.encrypt(messageData)
  File "build/bdist.linux-armv6l/egg/axolotl/sessioncipher.py", line 69, in encrypt
    self.sessionStore.storeSession(self.recipientId, self.deviceId, sessionRecord)
  File "/opt/yowsup-master/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 55, in storeSession
    self.sessionStore.storeSession(recepientId, deviceId, sessionRecord)
  File "/opt/yowsup-master/yowsup/layers/axolotl/store/sqlite/litesessionstore.py", line 35, in storeSession
    self.deleteSession(recipientId, deviceId)
  File "/opt/yowsup-master/yowsup/layers/axolotl/store/sqlite/litesessionstore.py", line 53, in deleteSession
    self.dbConn.cursor().execute(q, (recipientId, deviceId))
OperationalError: database is locked`

Any idea?

Best regards
Heinz

**Comment by HeinzFo** [comment]
After reinstall axolotl an new problem occures

`Traceback (most recent call last):
File "/opt/yowsup-master/yowsup-cli", line 368, in <module>
  if not parser.process():
File "/opt/yowsup-master/yowsup-cli", line 272, in process
  self.startSendClient()
File "/opt/yowsup-master/yowsup-cli", line 323, in startSendClient
  not self.args["unmoxie"])
File "/opt/yowsup-master/yowsup/demos/sendclient/stack.py", line 20, in __init__
  .pushDefaultLayers(encryptionEnabled)\
File "/opt/yowsup-master/yowsup/stacks/yowstack.py", line 52, in pushDefaultLayers
  defaultLayers = YowStackBuilder.getDefaultLayers(axolotl)
File "/opt/yowsup-master/yowsup/stacks/yowstack.py", line 74, in getDefaultLayers
  from yowsup.layers.axolotl import AxolotlSendLayer, AxolotlControlLayer, AxolotlReceivelayer
File "/opt/yowsup-master/yowsup/layers/axolotl/__init__.py", line 1, in <module>
  from .layer_send import AxolotlSendLayer
File "/opt/yowsup-master/yowsup/layers/axolotl/layer_send.py", line 8, in <module>
  from axolotl.axolotladdress import AxolotlAddress
ImportError: No module named axolotladdress`

To slove this problem https://github.com/tgalal/yowsup/issues/500
`sudo pip uninstall python-axolotl
sudo pip install python-axolotl`

Now yowsup works fine again.

Regards
Heinz

**Comment by sulz47** [comment]
hey dude i m facing issue with yowsup..
whenever i try to send message command
it returns DLL error..
i m running yowsup on windows powershell
which OS u r using?

**Comment by HeinzFo** [comment]
Hardware is Raspberry Pi 3, OS is Raspian Stretch.

**Comment by tgalal** [comment]
outdated python-axoltol version
