### ISSUE TITLE
Registration: ValueError: You have to request code first

### ISSUE THREAD

**Issue by AlwaysLearn1ng** [tgalal/yowsup#2447]
I tiped the following command: yowsup-cli registration --register xxx-xxx --phone 49xxxxxxxxxxx --cc 49
yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.7', 'yowsup-cli')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.7-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.7-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 191, in process
    self.handleRegister(self.args["register"], config)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.7-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 215, in handleRegister
    req = WARegRequest(config["cc"], config["phone"], code)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.7-py3.5.egg/yowsup/registration/regrequest.py", line 35, in __init__
    raise ValueError("You have to request code first")
ValueError: You have to request code first

Can somebody explain me what i have to do? I already requestet a code and got it and used it for that command.

**Comment by cijo7** [comment]
Make sure that you have the id value stored in the user directory (on Linux: ~/.yowsup). If it is not present request this code again.
