### ISSUE TITLE
AttributeError: type object 'StopIteration' has no attribute 'co_names'

### ISSUE THREAD

**Issue by dnyati** [tgalal/yowsup#2469]
Faces below issue while installation of yowsup-master 

opying yowsup2.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying yowsup2.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules'
  File "c:\WhatsApp\WS\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\WhatsApp\WS\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "c:\WhatsApp\WS\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\WhatsApp\WS\lib\site-packages\setuptools\command\install.py", line 67
, in run
    self.do_egg_install()
  File "c:\WhatsApp\WS\lib\site-packages\setuptools\command\install.py", line 10
9, in do_egg_install
    self.run_command('bdist_egg')
  File "c:\WhatsApp\WS\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "c:\WhatsApp\WS\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\WhatsApp\WS\lib\site-packages\setuptools\command\bdist_egg.py", line
208, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "c:\WhatsApp\WS\lib\site-packages\setuptools\command\bdist_egg.py", line
244, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "c:\WhatsApp\WS\lib\site-packages\setuptools\command\bdist_egg.py", line
354, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "c:\WhatsApp\WS\lib\site-packages\setuptools\command\bdist_egg.py", line
394, in scan_module
    symbols = dict.fromkeys(iter_symbols(code))
  File "c:\WhatsApp\WS\lib\site-packages\setuptools\command\bdist_egg.py", line
413, in iter_symbols
    for name in code.co_names:
AttributeError: type object 'StopIteration' has no attribute 'co_names'

How can i remove this.

**Comment by mpenkov** [comment]
I had the same problem, and solved it by upgrading setuptools:

     python3.7 -m pip install --upgrade setuptools

Sorry for hijacking this thread, but it's the only thing google comes up with when searching for "AttributeError: type object 'StopIteration' has no attribute 'co_names'", so it could be of use to someone.
