### ISSUE TITLE
Doesn't work when trying to send a demo message... 

### ISSUE THREAD

**Issue by fabioneves** [tgalal/yowsup#2619]
Trying registering multiple times, tried python2 and python3, none of them work.

➜  ~ yowsup-cli version
yowsup-cli v2.0.15
Using yowsup v2.5.7

```
INFO:yowsup.layers.axolotl.layer_control:Axolotl layer is generating keys
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/local/bin/yowsup-cli", line 324, in startSendClient
    stack.start()
  File "/usr/local/lib/python3.6/dist-packages/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/usr/local/lib/python3.6/dist-packages/yowsup/stacks/yowstack.py", line 197, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.6/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.6/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib/python3.6/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/axolotl/layer_send.py", line 64, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 161, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/axolotl/layer_base.py", line 65, in onSuccess
    sessionBuilder.processPreKeyBundle(preKeyBundle)
  File "/usr/local/lib/python3.6/dist-packages/axolotl/sessionbuilder.py", line 166, in processPreKeyBundle
    .setOurIdentityKey(self.identityKeyStore.getIdentityKeyPair())\
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 19, in getIdentityKeyPair
    return self.identityKeyStore.getIdentityKeyPair()
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/axolotl/store/sqlite/liteidentitykeystore.py", line 30, in getIdentityKeyPair
    publicKey, privateKey = result
TypeError: 'NoneType' object is not iterable
```

**Comment by ruslanguns** [comment]
Did you figured to get this to work?
