### ISSUE TITLE
socket.error: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by mocart2** [tgalal/yowsup#2656]
when i try to send message:
**yowsup-cli demos -l  7934324324324:CVNVT4324edt4555t/Rxu00Qzc= -s "79123213331"  "hello"**
```
yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/local/bin/yowsup-cli", line 324, in startSendClient
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/demos/sendclient/stack.py", line 31, in start
    self.stack.loop()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 197, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 446, in handle_read_event
    self.handle_connect_event()
  File "/usr/lib/python2.7/asyncore.py", line 454, in handle_connect_event
    raise socket.error(err, _strerror(err))
socket.error: [Errno 110] Connection timed out
```

**Comment by lisabrauns** [comment]
see the issues [2655](https://github.com/tgalal/yowsup/issues/2655)

**Comment by tgalal** [comment]
@mocart2 issue still exists?
