### ISSUE TITLE
Can't register: UnsupportedAlgorithm: X25519 is not supported by this version of OpenSSL.

### ISSUE THREAD

**Issue by mocart2** [tgalal/yowsup#2658]
Can't register yowsup:
```
root@orangepiplus2e:~# yowsup-cli registration --requestcode sms --phone 79111111111 --cc 7 --mcc 250 --mnc 99 --env android
E 2019-04-23 11:11:09,006 yowsup.config.manager - Could not find a config for username=79111111111, paths checked: /root/.config/yowsup/79111111111/config:/root/.config/yowsup/79111111111/config.json:/root/.config/yowsup/791111111117/config.yo
yowsup-cli  v3.0.0
yowsup      v3.0.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 518, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 340, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/local/bin/yowsup-cli", line 351, in handleRequestCode
    codeReq = WACodeRequest(method, config)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/registration/coderequest.py", line 15, in __init__
    super(WACodeRequest,self).__init__(config)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/common/http/warequest.py", line 71, in __init__
    config.client_static_keypair = WATools.generateKeyPair()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/common/tools.py", line 70, in generateKeyPair
    return KeyPair.generate()
  File "/usr/local/lib/python2.7/dist-packages/consonance/structs/keypair.py", line 36, in generate
    keypair = X25519DH().generate_keypair()
  File "/usr/local/lib/python2.7/dist-packages/dissononce/dh/x25519/x25519.py", line 28, in generate_keypair
    private = x25519.X25519PrivateKey.generate()
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/asymmetric/x25519.py", line 42, in generate
    _Reasons.UNSUPPORTED_EXCHANGE_ALGORITHM
cryptography.exceptions.UnsupportedAlgorithm: X25519 is not supported by this version of OpenSSL.
```

**Comment by tgalal** [comment]
you need to update OpenSSL to 1.1.0+, see https://github.com/openssl/openssl/issues/309

**Comment by mocart2** [comment]
i removed old version and get version **openssl 1.1.1**
`wget --no-check-certificate https://www.openssl.org/source/openssl-1.1.1.tar.gz`
compile with:
`./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl shared zlib`
and make install , after configure links etc, and check version:
```
root@orangepiplus2e:~# openssl version -a
OpenSSL 1.1.1  11 Sep 2018
built on: Fri Apr 26 11:33:31 2019 UTC
platform: linux-armv4
options:  bn(64,32) rc4(char) des(long) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread  -march=armv7-a -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/ssl/lib/engines-1.1"
Seeding source: os-specific
```
and after it i try to register:
```
root@orangepiplus2e:~# yowsup-cli registration --requestcode sms --phone 71111111111 --cc 7 --mcc 250 --mnc 99 --env android
E 2019-04-26 21:57:35,927 yowsup.config.manager - Could not find a config for username=71111111111, paths checked: /root/.config/yowsup/71111111111/config:/root/.config/yowsup/71111111111/config.json:/root/.config/yowsup/71111111111/config.yo
yowsup-cli  v3.0.0
yowsup      v3.0.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 518, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 340, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/local/bin/yowsup-cli", line 351, in handleRequestCode
    codeReq = WACodeRequest(method, config)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/registration/coderequest.py", line 15, in __init__
    super(WACodeRequest,self).__init__(config)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/common/http/warequest.py", line 71, in __init__
    config.client_static_keypair = WATools.generateKeyPair()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/common/tools.py", line 70, in generateKeyPair
    return KeyPair.generate()
  File "/usr/local/lib/python2.7/dist-packages/consonance/structs/keypair.py", line 36, in generate
    keypair = X25519DH().generate_keypair()
  File "/usr/local/lib/python2.7/dist-packages/dissononce/dh/x25519/x25519.py", line 28, in generate_keypair
    private = x25519.X25519PrivateKey.generate()
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/asymmetric/x25519.py", line 42, in generate
    _Reasons.UNSUPPORTED_EXCHANGE_ALGORITHM
cryptography.exceptions.UnsupportedAlgorithm: X25519 is not supported by this version of OpenSSL.
```

where is my mistake?

**Comment by mocart2** [comment]
@tgalal i get latest pythone 2.7 and recompile it for using system openssl:
```
root@orangepiplus2e:~# python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.1.1b  26 Feb 2019
```
but problem is still exist:
```
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/asymmetric/x25519.py", line 42, in generate
    _Reasons.UNSUPPORTED_EXCHANGE_ALGORITHM
cryptography.exceptions.UnsupportedAlgorithm: X25519 is not supported by this version of OpenSSL.
```

**Comment by 1seven** [comment]
I had the same problem on gentoo. Solved it by rebuilding dev-python/cryptography
