### ISSUE TITLE
ImportError: cannot import name x25519

### ISSUE THREAD

**Issue by jowiemann** [tgalal/yowsup#2660]
Hello,
with the new Version I get the following error:
Traceback (most recent call last):
File "yowsup-cli", line 6, in 
from yowsup.config.manager import ConfigManager
File "/opt/fhem/yowsup-master/yowsup/config/manager.py", line 4, in 
from yowsup.config.v1.serialize import ConfigSerialize
File "/opt/fhem/yowsup-master/yowsup/config/v1/serialize.py", line 8, in 
from consonance.structs.keypair import KeyPair
File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.0-py2.7.egg/consonance/structs/keypair.py", line 4, in 
from dissononce.dh.x25519.x25519 import X25519DH
File "build/bdist.linux-armv6l/egg/dissononce/dh/x25519/x25519.py", line 1, in 
ImportError: cannot import name x25519
Environment: RPi, ARMv6-compatible processor rev 7 (v6l), Stretch
Thank you for your help

**Comment by tgalal** [comment]
which version of cryptography lib do you have? maybe an old one?

**Comment by tgalal** [comment]
Please update to cryptography 2.5+, reopen the issue if it doesn't solve it.

**Comment by FGarridoV** [comment]
Hello! I have the same problem of this invalid [issue](https://github.com/tgalal/yowsup/issues/2770).
I have the last version of cryptography (2.6.1)
what can be the solution?

So thanks,
Francisco

**Comment by tgalal** [comment]
make sure yowsup is using crypto 2.6.1 because most probably it isnt. set this all up in a virtualenv without access to system packages and see if it works

**Comment by leemgs** [comment]
I have the same issue. Anyone that solved this issue? Welcome to any hints to me. 

```bash
pi@raspberrypi:~/lgs$ sudo pip install yowsup2==3.2.3
pi@raspberrypi:~/lgs $ yowsup-cli
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 6, in <module>
    from yowsup.config.manager import ConfigManager
  File "/usr/local/lib/python2.7/dist-packages/yowsup/config/manager.py", line 4, in <module>
    from yowsup.config.v1.serialize import ConfigSerialize
  File "/usr/local/lib/python2.7/dist-packages/yowsup/config/v1/serialize.py", line 8, in <module>
    from consonance.structs.keypair import KeyPair
  File "/usr/local/lib/python2.7/dist-packages/consonance/structs/keypair.py", line 4, in <module>
    from dissononce.dh.x25519.x25519 import X25519DH
  File "build/bdist.linux-armv7l/egg/dissononce/dh/x25519/x25519.py", line 1, in <module>
ImportError: cannot import name x25519
```

**Comment by tgalal** [comment]
issue is closed, open a new issue describing your problem
