### ISSUE TITLE
Please help, trying register with yowsup v3

### ISSUE THREAD

**Issue by Sharissa90** [tgalal/yowsup#2661]
When I issuing this command:
`yowsup-cli registration -p --requestcode sms --config-phone xxxxxxxxxxxxx--config-cc xx`

i get error results

`yowsup-cli  v3.0.0
yowsup      v3.0.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 518, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 340, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/local/bin/yowsup-cli", line 351, in handleRequestCode
    codeReq = WACodeRequest(method, config)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/registration/coderequest.py", line 15, in __init__
    super(WACodeRequest,self).__init__(config)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/common/http/warequest.py", line 71, in __init__
    config.client_static_keypair = WATools.generateKeyPair()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/common/tools.py", line 70, in generateKeyPair
    return KeyPair.generate()
  File "/usr/local/lib/python3.5/dist-packages/consonance/structs/keypair.py", line 36, in generate
    keypair = X25519DH().generate_keypair()
  File "/usr/local/lib/python3.5/dist-packages/dissononce/dh/x25519/x25519.py", line 37, in generate_keypair
    encoding=serialization.Encoding.Raw,
  File "/usr/lib/python3.5/enum.py", line 274, in __getattr__
    raise AttributeError(name) from None
AttributeError: Raw
`

**Comment by tgalal** [comment]
which version of cryptography lib do you have? maybe an old one?

**Comment by BodduSatya** [comment]
i too have the same issue
i am using following cryptography 

Using /usr/lib/python3/dist-packages
Searching for cryptography==2.1.4
Best match: cryptography 2.1.4
Adding cryptography 2.1.4 to easy-install.pth file

**Comment by tgalal** [comment]
Please update to cryptography 2.5+, reopen the issue if it doesn't solve it.
