### ISSUE TITLE
no /login command

### ISSUE THREAD

**Issue by dfroger** [tgalal/yowsup#2662]
I'm using `yowsup-cli 3.0.0`:

    yowsup-cli demos --yowsup --config /path/to/config

There is no `/login` command, how do I provide the credentials? `/L` seems to take no arguments.

Thanks

**Comment by tgalal** [comment]
if you register using yowsup-cli you do not need to input credentials

**Comment by dfroger** [comment]
Note: I was reading https://github.com/tgalal/yowsup/wiki/Command-line-client


Seems there is now a `keypair`:

```
commit c4f0af02335d1cc224084299c633ed5789394863
Author: Tarek Galal <tare2.galal@gmail.com>
Date:   Mon Apr 22 19:57:17 2019 +0200

    [chore] apply multiple cleanups
    
    Replace "password" occurences with keypair
    Remove cli demo's login(username, password) method/command
    Remove obsolete Crypt layer
    Remove obsolete StanzaRegulator Layer
    Remove obsolete tests
```

**Comment by dfroger** [comment]
@tgalal ok, I registred with:

    yowsup-cli v2.0.15
    Using yowsup v2.5.7

do I need to register again?

When trying `/L`, I get:

```
[offline]:/L
I 2019-04-23 17:22:39,053 yowsup.layers.network.layer - Connecting to e12.whatsapp.net:443
I 2019-04-23 17:22:39,170 yowsup.axolotl.manager - Loaded 812 unsent prekeys
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/david/.pyenv/versions/3.6.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/david/.pyenv/versions/3.6.6/lib/python3.6/site-packages/yowsup/layers/noise/workers/handshake.py", line 36, in run
    self._protocol.start(self._stream, self._client_config, self._s, self._rs)
  File "/home/david/.pyenv/versions/3.6.6/lib/python3.6/site-packages/consonance/protocol.py", line 82, in start
    result = handshake.perform(client_config, stream, s, rs)
  File "/home/david/.pyenv/versions/3.6.6/lib/python3.6/site-packages/consonance/handshake.py", line 72, in perform
    PublicKey(s.public.data),
AttributeError: 'NoneType' object has no attribute 'public'
```

**Comment by tgalal** [comment]
yes you must register again

**Comment by dfroger** [comment]
@tgalal solved, thanks! Now, will try a send my first whatsapp message to a contact...
