### ISSUE TITLE
 No such prekeyRecord!

### ISSUE THREAD

**Issue by Sharissa90** [tgalal/yowsup#2672]
Hi, please assist me. I Success connecting yowsup to my group chat and when I tested sending image to yowsup, the script is error and when i tried to restart raise this problem.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/network/dispatcher/dispatcher_socket.py", line 42, in connectAndLoop
    self.connectionCallbacks.onRecvData(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/network/layer.py", line 82, in onRecvData
    self.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/network/layer.py", line 85, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/noise/layer.py", line 149, in receive
    self._flush_incoming_buffer()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/noise/layer.py", line 137, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_control.py", line 32, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 36, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 69, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 81, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 118, in handlePreKeyWhisperMessage
    enc.getVersion() == 2)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/axolotl/manager.py", line 164, in decrypt_pkmsg
    plaintext = self._get_session_cipher(senderid).decryptPkmsg(pkmsg)
  File "/usr/local/lib/python3.5/dist-packages/axolotl/sessioncipher.py", line 96, in decryptPkmsg
    unsignedPreKeyId = self.sessionBuilder.process(sessionRecord, ciphertext)
  File "/usr/local/lib/python3.5/dist-packages/axolotl/sessionbuilder.py", line 50, in process
    unsignedPreKeyId = self.processV3(sessionRecord, message)
  File "/usr/local/lib/python3.5/dist-packages/axolotl/sessionbuilder.py", line 121, in processV3
    parameters.setOurOneTimePreKey(self.preKeyStore.loadPreKey(message.getPreKeyId()).getKeyPair())
  File "/usr/local/lib/python3.5/dist-packages/yowsup/axolotl/store/sqlite/liteaxolotlstore.py", line 37, in loadPreKey
    return self.preKeyStore.loadPreKey(preKeyId)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/axolotl/store/sqlite/liteprekeystore.py", line 21, in loadPreKey
    raise Exception("No such prekeyRecord!")
Exception: No such prekeyRecord!
```
I have deleted axolotl.db  in ~/.config/yowsup folder but no luck..

**Comment by mrolinek** [comment]
Any progress? Or is there a fix already? I get the missing prekeys already on login.
