### ISSUE TITLE
Crash on receive unhandled message type

### ISSUE THREAD

**Issue by tgalal** [tgalal/yowsup#2677]
audio recording, video, and document seem to trigger that
```
Traceback (most recent call last):
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/network/dispatcher/dispatcher_socket.py", line 42, in connectAndLoop
    self.connectionCallbacks.onRecvData(data)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/network/layer.py", line 82, in onRecvData
    self.receive(data)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/network/layer.py", line 85, in receive
    self.toUpper(data)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/noise/layer.py", line 149, in receive
    self._flush_incoming_buffer()
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/noise/layer.py", line 137, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/axolotl/layer_control.py", line 32, in receive
    self.toUpper(protocolTreeNode)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 36, in receive
    self.onMessage(protocolTreeNode)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 69, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 81, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 121, in handlePreKeyWhisperMessage
    self.parseAndHandleMessageProto(pkMessageProtocolEntity, plaintext)
  File "/tmp/yoweenv/lib/python3.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 194, in parseAndHandleMessageProto
    raise ValueError("Unhandled")
ValueError: Unhandled

```

**Comment by Sharissa90** [comment]
@tgalal how we resolve this issue?

**Comment by jegue** [comment]
how about this

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/axolotl/groups/groupcipher.py", line 105, in getPlainText
    return plaintext.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 0: invalid continuation byte
on receving sticker

**Comment by Sharissa90** [comment]
when I send media file like emoticon, video and image, to yowsup 3.1.0 both private chat and group yowsup crash, please @tgalal fix this.. Thank you
