### ISSUE TITLE
Error when sending messages with command line client (demos)

### ISSUE THREAD

**Issue by jowiemann** [tgalal/yowsup#2678]
Yesterday I have revoced my WhatsApp Messages in Fhem. When sending message I see the following Errors:

yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/noise/workers/handshake.py", line 36, in run
    self._protocol.start(self._stream, self._client_config, self._s, self._rs)
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.0-py2.7.egg/consonance/protocol.py", line 87, in start
    self._machine.finish()
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 383, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 1047, in _process
    return trigger()
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 399, in _trigger
    return self._process(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 409, in _process
    if trans.execute(event_data):
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 266, in execute
    machine.callback(func, event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 1005, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.0-py2.7.egg/consonance/protocol.py", line 57, in _trigger_state_callback
    self._protocol_state_callbacks(self._machine.state)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/noise/layer.py", line 116, in _on_protocol_state_changed
    self._flush_incoming_buffer()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/noise/layer.py", line 137, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 32, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 36, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 69, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 85, in handleEncMessage
    self.handleSenderKeyMessage(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 145, in handleSenderKeyMessage
    data=enc.getData()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/axolotl/manager.py", line 209, in group_decrypt
    plaintext = group_cipher.decrypt(data)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/groups/groupcipher.py", line 65, in decrypt
    senderKey = self.getSenderKey(senderKeyState, senderKeyMessage.getIteration())
  File "/usr/local/lib/python2.7/dist-packages/axolotl/groups/groupcipher.py", line 83, in getSenderKey
    (senderChainKey.getIteration(), iteration))
DuplicateMessageException: Received message with old counter: 10, 9

the second error:
E 2019-04-24 14:14:09,107 yowsup.layers.network.dispatcher.dispatcher_socket - [Errno 9] Bad file descriptor
E 2019-04-24 14:14:09,111 yowsup.layers.network.dispatcher.dispatcher_socket - [Errno 9] Bad file descriptor
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/demos/cli/cli.py", line 154, in startInputThread
    wait = self.execCmd(cmd)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/demos/cli/cli.py", line 138, in execCmd
    return self.doExecCmd(lambda :targetFn(*args))
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/demos/cli/cli.py", line 141, in doExecCmd
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/demos/cli/cli.py", line 138, in <lambda>
    return self.doExecCmd(lambda :targetFn(*args))
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/demos/cli/layer.py", line 370, in message_send
    self.toLower(outgoingMessage)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/__init__.py", line 136, in send
    send(entity)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/__init__.py", line 140, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/axolotl/layer_send.py", line 39, in send
    self.processPlaintextNodeAndSend(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.0.0-py2.7.egg/yowsup/layers/axolotl/layer_send.py", line 85, in processPlaintextNodeAndSend
    elif self.manager.session_exists(recipient_id):
AttributeError: 'NoneType' object has no attribute 'session_exists'

**Comment by jowiemann** [comment]
Seems to be fixed with 3.2.0
