### ISSUE TITLE
Requirement.parse('cryptography>=2.5')

### ISSUE THREAD

**Issue by magnussolution** [tgalal/yowsup#2689]
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup==3.1.0', 'yowsup-cli')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 2.2.2 (/usr/lib/python2.7/site-packages/cryptography-2.2.2-py2.7-linux-x86_64.egg), Requirement.parse('cryptography>=2.5'), set(['dissononce']))

I try using Debian and Centos.

**Comment by tgalal** [comment]
something is wrong with how you installed, it's not a yowsup issue

**Comment by magnussolution** [comment]
I try on a new server with Debian and Centos, make the install according to your documentation. Have you any idea? remember I donate for you this year to help you find a solution.
