### ISSUE TITLE
Version 3.1.0: Error when pillow is installed

### ISSUE THREAD

**Issue by jowiemann** [tgalal/yowsup#2690]
[offline]:/L
I 2019-04-25 14:44:54,301 yowsup.layers.network.layer - Connecting to e15.whatsapp.net:443
I 2019-04-25 14:44:56,655 yowsup.axolotl.manager - Loaded 0 unsent prekeys
Auth: Logged in!
[connected]:W 2019-04-25 14:44:57,526 yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/noise/workers/handshake.py", line 36, in run
    self._protocol.start(self._stream, self._client_config, self._s, self._rs)
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.1-py2.7.egg/consonance/protocol.py", line 87, in start
    self._machine.finish()
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 383, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 1047, in _process
    return trigger()
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 399, in _trigger
    return self._process(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 409, in _process
    if trans.execute(event_data):
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 266, in execute
    machine.callback(func, event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions-0.6.9-py2.7.egg/transitions/core.py", line 1005, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.1-py2.7.egg/consonance/protocol.py", line 57, in _trigger_state_callback
    self._protocol_state_callbacks(self._machine.state)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/noise/layer.py", line 123, in _on_protocol_state_changed
    self._flush_incoming_buffer()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/noise/layer.py", line 144, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 32, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 31, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 63, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 75, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 112, in handlePreKeyWhisperMessage
    enc.getVersion() == 2)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/axolotl/manager.py", line 164, in decrypt_pkmsg
    plaintext = self._get_session_cipher(senderid).decryptPkmsg(pkmsg)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessioncipher.py", line 96, in decryptPkmsg
    unsignedPreKeyId = self.sessionBuilder.process(sessionRecord, ciphertext)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 50, in process
    unsignedPreKeyId = self.processV3(sessionRecord, message)
  File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 121, in processV3
    parameters.setOurOneTimePreKey(self.preKeyStore.loadPreKey(message.getPreKeyId()).getKeyPair())
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/axolotl/store/sqlite/liteaxolotlstore.py", line 37, in loadPreKey
    return self.preKeyStore.loadPreKey(preKeyId)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.1.0-py2.7.egg/yowsup/axolotl/store/sqlite/liteprekeystore.py", line 21, in loadPreKey
    raise Exception("No such prekeyRecord!")
Exception: No such prekeyRecord!

**Comment by stv0g** [comment]
Duplicate #2672

Please close this issue
