### ISSUE TITLE
cannot start after install

### ISSUE THREAD

**Issue by magnussolution** [tgalal/yowsup#2706]
I install normally in Centos 7.

when I try execute yowsup-cli I receive this error.

```
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup==3.1.0', 'yowsup-cli')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/yowsup-cli' not found in metadata at '/usr/lib/python2.7/site-packages/yowsup-3.1.0.dist-info'
```

**Comment by tgalal** [comment]
not an issue in yowsup
