### ISSUE TITLE
Try to implement Send Image but got  Error parsing message

### ISSUE THREAD

**Issue by bahtiarp** [tgalal/yowsup#2714]
[connected]:D 2019-05-04 22:40:27,430 yowsup.layers.logger.layer - rx:
<iq type="result" id="1" from="s.whatsapp.net">
<encr_media url="https://mmg.whatsapp.net/u/f/bcT9mce7zSaTtKknUpi9x1zNpFsABYgQ2SEntA/AuVEYaLp3KkxK6BHCL0fYc7_cqmOPDTMEmtTLqA1A3jx">
</encr_media>
</iq>

E 2019-05-04 22:40:27,430 yowsup.layers.network.dispatcher.dispatcher_socket - __init__() got an unexpected keyword argument 'asynchronous'
D 2019-05-04 22:40:27,430 yowsup.layers.network.layer - Disconnected
D 2019-05-04 22:40:27,466 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
D 2019-05-04 22:40:27,466 yowsup.layers.protocol_iq.layer - stopping ping thread
general: Disconnected: 
[connected]:
D 2019-05-04 22:40:27,888 yowsup.layers.protocol_iq.layer - YowPingThread-4 - ping thread stopped

[offline]:
[offline]:/L
.
.
D 2019-05-04 20:59:51,466 yowsup.config.manager - Loading config
D 2019-05-04 20:59:51,466 yowsup.layers.noise.layer - Performing handshake [username= 628129221xxxx, passive=False]
D 2019-05-04 20:59:51,466 yowsup.layers.noise.layer - Starting handshake worker
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/home/yowsup/yowsup/yowsup/layers/noise/workers/handshake.py", line 36, in run
    self._protocol.start(self._stream, self._client_config, self._s, self._rs)
  File "/usr/lib/python3.4/site-packages/consonance/protocol.py", line 82, in start
    result = handshake.perform(client_config, stream, s, rs)
  File "/usr/lib/python3.4/site-packages/consonance/handshake.py", line 80, in perform
    cipherstatepair = self._start_handshake_ik(stream, client_payload, dissononce_s, dissononce_rs)
  File "/usr/lib/python3.4/site-packages/consonance/handshake.py", line 182, in _start_handshake_ik
    incoming_handshakemessage.ParseFromString(stream.read_segment())
google.protobuf.message.DecodeError: Error parsing message

**Comment by BodduSatya** [comment]
https://github.com/tgalal/yowsup/issues/2686#issuecomment-489329479

**Comment by vlntdds** [comment]
Any news on that? 🤔

**Comment by ersinayaz** [comment]
is there any improvement? @tgalal

**Comment by ersinayaz** [comment]
hey @tgalal ,
is there any improvement?

**Comment by ciclanoio** [comment]
any news about send images ? 

Thanks
