### ISSUE TITLE
Error on identity change encrypt notification

### ISSUE THREAD

**Issue by test07662** [tgalal/yowsup#2716]
```
I 2019-05-05 07:19:09,473 yowsup.layers.network.layer - Connecting to e13.whatsapp.net:443
I 2019-05-05 07:19:11,434 yowsup.demos.sendclient.layer - Message sent

Yowsdown
[root@WAPP-centos-s-1vcpu-1gb-sgp1-01 bin]# yowsup-cli demos --config-phone xxxxxxxxxxxx -y
yowsup-cli  v3.2.0
yowsup      v3.2.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
I 2019-05-05 07:19:27,344 yowsup.layers.network.layer - Connecting to e11.whatsapp.net:443
Auth: Logged in!
[connected]:E 2019-05-05 07:19:28,188 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3.6/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 100, in onRecvData
    self.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 103, in receive
    self.toUpper(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 156, in receive
    self._flush_incoming_buffer()
  File "/usr/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 144, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_control.py", line 30, in receive
    self.onEncryptNotification(protocolTreeNode)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_control.py", line 35, in onEncryptNotification
    entity = EncryptNotification.fromProtocolTreeNode(protocolTreeNode)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/axolotl/protocolentities/notification_encrypt.py", line 31, in fromProtocolTreeNode
    entity.setProps(node.getChild("count")["value"])
TypeError: 'NoneType' object is not subscriptable

general: Disconnected: 
[connected]:
Error: Not connected
[offline]:
```

i update today and can send message but can`t receive message or connect to yowsup -L

**Comment by tgalal** [comment]
Please run with --debug and post output

**Comment by test07662** [comment]
`yowsup-cli demos --config-phone xxxxxxxxxxxxxxx -y --debug
D 2019-05-05 08:02:52,613 yowsup.config.manager - Detecting config for username=xxxxxxxxxxxxxxx, dir=/root/.config/yowsup/xxxxxxxxxxxxxxx/
D 2019-05-05 08:02:52,613 yowsup.config.manager - Trying /root/.config/yowsup/xxxxxxxxxxxxxxx/config.yo
D 2019-05-05 08:02:52,613 yowsup.config.manager - Trying /root/.config/yowsup/xxxxxxxxxxxxxxx/config.json
D 2019-05-05 08:02:52,614 yowsup.config.manager - load_path(path=/root/.config/yowsup/xxxxxxxxxxxxxxx/config.json)
D 2019-05-05 08:02:52,614 yowsup.config.manager - Detected config type: json
D 2019-05-05 08:02:52,614 yowsup.config.manager - Opening config for reading
D 2019-05-05 08:02:52,614 yowsup.config.manager - Loading config
D 2019-05-05 08:02:52,614 yowsup-cli - starting cmd
yowsup-cli  v3.2.0
yowsup      v3.2.0

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


D 2019-05-05 08:02:52,779 yowsup.stacks.yowstack - Initializing stack
D 2019-05-05 08:02:52,779 yowsup.stacks.yowstack - Constructed Network Layer
D 2019-05-05 08:02:52,780 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2019-05-05 08:02:52,780 yowsup.stacks.yowstack - Constructed Noise Layer
D 2019-05-05 08:02:52,780 yowsup.stacks.yowstack - Constructed Coder Layer
D 2019-05-05 08:02:52,781 yowsup.stacks.yowstack - Constructed Logger Layer
D 2019-05-05 08:02:52,781 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f47eb6daa58>
D 2019-05-05 08:02:52,781 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f47e9f5d7f0>
D 2019-05-05 08:02:52,781 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2019-05-05 08:02:52,785 yowsup.stacks.yowstack - Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
D 2019-05-05 08:02:56,445 yowsup.layers.network.layer - Created asyncore dispatcher
I 2019-05-05 08:02:56,445 yowsup.layers.network.layer - Connecting to e3.whatsapp.net:443
D 2019-05-05 08:02:56,445 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e3.whatsapp.net', 443))
D 2019-05-05 08:02:56,688 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2019-05-05 08:02:56,688 yowsup.layers.network.layer - Connected
D 2019-05-05 08:02:56,688 yowsup.axolotl.factory - get_manager(username=xxxxxxxxxxxxxxx)
D 2019-05-05 08:02:56,689 yowsup.axolotl.manager - Initialized AxolotlManager [username=xxxxxxxxxxxxxxx, db=/root/.config/yowsup/xxxxxxxxxxxxxxx/axolotl.db]
D 2019-05-05 08:02:56,689 yowsup.axolotl.manager - level_prekeys(force=False)
D 2019-05-05 08:02:56,695 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2019-05-05 08:02:56,695 yowsup.axolotl.manager - load_unsent_prekeys
D 2019-05-05 08:02:56,696 yowsup.axolotl.factory - get_manager(username=xxxxxxxxxxxxxxx)
D 2019-05-05 08:02:56,697 yowsup.axolotl.manager - Initialized AxolotlManager [username=xxxxxxxxxxxxxxx, db=/root/.config/yowsup/xxxxxxxxxxxxxxx/axolotl.db]
D 2019-05-05 08:02:56,697 yowsup.axolotl.factory - get_manager(username=xxxxxxxxxxxxxxx)
D 2019-05-05 08:02:56,697 yowsup.axolotl.manager - Initialized AxolotlManager [username=xxxxxxxxxxxxxxx, db=/root/.config/yowsup/xxxxxxxxxxxxxxx/axolotl.db]
D 2019-05-05 08:02:56,698 yowsup.layers.noise.layer - Received auth event
D 2019-05-05 08:02:56,698 yowsup.config.manager - Detecting config for username=xxxxxxxxxxxxxxx, dir=/root/.config/yowsup/xxxxxxxxxxxxxxx/
D 2019-05-05 08:02:56,698 yowsup.config.manager - Trying /root/.config/yowsup/xxxxxxxxxxxxxxx/config.yo
D 2019-05-05 08:02:56,698 yowsup.config.manager - Trying /root/.config/yowsup/xxxxxxxxxxxxxxx/config.json
D 2019-05-05 08:02:56,698 yowsup.config.manager - load_path(path=/root/.config/yowsup/xxxxxxxxxxxxxxx/config.json)
D 2019-05-05 08:02:56,698 yowsup.config.manager - Detected config type: json
D 2019-05-05 08:02:56,698 yowsup.config.manager - Opening config for reading
D 2019-05-05 08:02:56,699 yowsup.config.manager - Loading config
D 2019-05-05 08:02:56,699 yowsup.env.env - Env not set, setting it to android
D 2019-05-05 08:02:56,699 yowsup.env.env - Current env changed to android 
D 2019-05-05 08:02:56,699 yowsup.layers.noise.layer - Performing handshake [username= xxxxxxxxxxxxxxx, passive=False]
D 2019-05-05 08:02:56,699 yowsup.layers.noise.layer - Starting handshake worker
D 2019-05-05 08:02:57,813 yowsup.layers.logger.layer - rx:
<success t="1557043377" props="25" location="frc" creation="1556089671">
</success>

D 2019-05-05 08:02:57,813 yowsup.layers.protocol_iq.layer - starting ping thread.
Auth: Logged in!
[connected]:D 2019-05-05 08:02:57,843 yowsup.layers.logger.layer - rx:
<ib from="s.whatsapp.net">
<edge_routing>
<routing_info>

HEX3:b'08020805'
</routing_info>
<dns_domain>
fb
HEX3:b'6662'
</dns_domain>
</edge_routing>
</ib>

D 2019-05-05 08:02:57,843 yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now
D 2019-05-05 08:02:57,843 yowsup.layers.logger.layer - rx:
<ib from="s.whatsapp.net">
<dirty type="groups" timestamp="1557043377">
</dirty>
</ib>

D 2019-05-05 08:02:57,844 yowsup.layers.logger.layer - rx:
<ib from="s.whatsapp.net">
<fbip>
18.185.100.110|5222|1557043377|90000|false|false,3.90.32.201|5222|1557043377|90000|false|false,169.55.67.251|5222|1557043377|90000|false|false
HEX3:b'31382e3138352e3130302e3131307c353232327c313535373034333337377c39303030307c66616c73657c66616c73652c332e39302e33322e3230317c353232327c313535373034333337377c39303030307c66616c73657c66616c73652c3136392e35352e36372e3235317c353232327c313535373034333337377c39303030307c66616c73657c66616c7365'
</fbip>
</ib>

D 2019-05-05 08:02:57,844 yowsup.layers.protocol_ib.layer - ignoring fbip ib node for now
D 2019-05-05 08:02:57,872 yowsup.layers.logger.layer - rx:
<notification from="989190450015@s.whatsapp.net" type="encrypt" id="2405379295" offline="11" t="1556551321">
<identity>
</identity>
</notification>

E 2019-05-05 08:02:57,874 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3.6/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 100, in onRecvData
    self.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 103, in receive
    self.toUpper(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 156, in receive
    self._flush_incoming_buffer()
  File "/usr/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 144, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_control.py", line 30, in receive
    self.onEncryptNotification(protocolTreeNode)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_control.py", line 35, in onEncryptNotification
    entity = EncryptNotification.fromProtocolTreeNode(protocolTreeNode)
  File "/usr/lib/python3.6/site-packages/yowsup/layers/axolotl/protocolentities/notification_encrypt.py", line 31, in fromProtocolTreeNode
    entity.setProps(node.getChild("count")["value"])
TypeError: 'NoneType' object is not subscriptable

D 2019-05-05 08:02:57,874 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2019-05-05 08:02:57,874 yowsup.layers.network.layer - Disconnected
D 2019-05-05 08:02:57,903 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
D 2019-05-05 08:02:57,903 yowsup.layers.protocol_iq.layer - stopping ping thread
general: Disconnected: 
[connected]:
D 2019-05-05 08:02:58,815 yowsup.layers.protocol_iq.layer - YowPingThread-4 - ping thread stopped`

**Comment by kadrimanaj** [comment]
I have this problem

yowsup-cli demos -c config.txt -s 35569xxxxxxxxxx "hi"  --debug
D 2020-09-03 23:32:38,548 yowsup.config.manager - load(path_or_profile_name=config.txt, profile_only=False)
D 2020-09-03 23:32:38,548 yowsup.config.manager - _load_path(path=config.txt)
D 2020-09-03 23:32:38,548 yowsup.config.manager - Trying auto detect config type by parsing
D 2020-09-03 23:32:38,549 yowsup.config.manager - Trying to parse as keyval
D 2020-09-03 23:32:38,549 yowsup.config.manager - config.txt was not parseable as keyval, reason: list index out of range
D 2020-09-03 23:32:38,549 yowsup.config.manager - Trying to parse as json
D 2020-09-03 23:32:38,549 yowsup.config.manager - Successfully detected json as config type for config.txt
D 2020-09-03 23:32:38,549 yowsup.config.manager - Detected config type: json
D 2020-09-03 23:32:38,549 yowsup.config.manager - Opening config for reading
D 2020-09-03 23:32:38,549 yowsup.config.manager - Loading config
D 2020-09-03 23:32:38,550 yowsup.config.manager - load(path_or_profile_name=35569xxxxxxxxxx, profile_only=True)
D 2020-09-03 23:32:38,550 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2020-09-03 23:32:38,550 yowsup.config.manager - Detecting config for profile=35569xxxxxxxxxx, dir=/home/ubuntu/.config/yowsup/35569xxxxxxxxxx
D 2020-09-03 23:32:38,550 yowsup.config.manager - Trying /home/ubuntu/.config/yowsup/35569xxxxxxxxxx/config.yo
D 2020-09-03 23:32:38,550 yowsup.config.manager - Trying /home/ubuntu/.config/yowsup/35569xxxxxxxxxx/config.json
E 2020-09-03 23:32:38,550 yowsup.config.manager - Could not find a config for profile=35569xxxxxxxxxx, paths checked: /home/ubuntu/.config/yowsup/35569xxxxxxxxxx/co                                                                               nfig.yo:/home/ubuntu/.config/yowsup/35569xxxxxxxxxx/config.json
D 2020-09-03 23:32:38,550 yowsup.profile.profile - Constructed Profile(profile_name=35569xxxxxxxxxx)
yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.2
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v3.1
protobuf       v3.13.0


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


D 2020-09-03 23:32:38,643 yowsup.stacks.yowstack - Initializing stack
D 2020-09-03 23:32:38,643 yowsup.stacks.yowstack - Constructed Network Layer
D 2020-09-03 23:32:38,643 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2020-09-03 23:32:38,644 yowsup.stacks.yowstack - Constructed Noise Layer
D 2020-09-03 23:32:38,644 yowsup.stacks.yowstack - Constructed Coder Layer
D 2020-09-03 23:32:38,644 yowsup.stacks.yowstack - Constructed Logger Layer
D 2020-09-03 23:32:38,645 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7eff79287358>
D 2020-09-03 23:32:38,645 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7eff7a119f                                                                               28>
D 2020-09-03 23:32:38,645 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer -                                                                                Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2020-09-03 23:32:38,645 yowsup.stacks.yowstack - Constructed Interface Layer
D 2020-09-03 23:32:38,645 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=35569xxxxxxxxxx))
D 2020-09-03 23:32:38,645 yowsup.layers.network.layer - Created asyncore dispatcher
I 2020-09-03 23:32:38,646 yowsup.layers.network.layer - Connecting to e14.whatsapp.net:443
D 2020-09-03 23:32:38,646 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e14.whatsapp.net', 443))
D 2020-09-03 23:32:38,725 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2020-09-03 23:32:38,726 yowsup.layers.network.layer - Connected
D 2020-09-03 23:32:38,726 yowsup.axolotl.factory - get_manager(profile_name=35569xxxxxxxxxx, username=35569xxxxxxxxxx)
D 2020-09-03 23:32:38,727 yowsup.axolotl.manager - Initialized AxolotlManager [username=35569xxxxxxxxxx, db=/home/ubuntu/.config/yowsup/35569xxxxxxxxxx/axolotl.db]
D 2020-09-03 23:32:38,727 yowsup.axolotl.manager - level_prekeys(force=False)
D 2020-09-03 23:32:38,730 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2020-09-03 23:32:38,730 yowsup.axolotl.manager - load_unsent_prekeys
I 2020-09-03 23:32:38,733 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2020-09-03 23:32:38,733 yowsup.layers.noise.layer - Received auth event
D 2020-09-03 23:32:38,733 yowsup.env.env - Env not set, setting it to android
D 2020-09-03 23:32:38,733 yowsup.env.env - Current env changed to android
E 2020-09-03 23:32:38,734 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.6/asyncore.py", line 441, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.6/asyncore.py", line 429, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/network/layer.py", line 54, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/noise/layer.py", line 109, in on_auth
    locale_country="US"
  File "/home/ubuntu/.local/lib/python3.6/site-packages/consonance/config/useragent.py", line 58, in __init__
    app_version = AppVersionConfig(app_version)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/consonance/config/appversion.py", line 15, in __init__
    self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
ValueError: too many values to unpack (expected 3)

D 2020-09-03 23:32:38,736 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-09-03 23:32:38,736 yowsup.layers.network.layer - Disconnected
D 2020-09-03 23:32:38,736 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
