### ISSUE TITLE
Version 3.2.0: NotImplementedError: Unhandled stream:error node:

### ISSUE THREAD

**Issue by jowiemann** [tgalal/yowsup#2718]
Got the following error:
```
E 2019-05-05 14:46:00,423 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/opt/fhem/yowsup-master/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/opt/fhem/yowsup-master/yowsup/layers/network/layer.py", line 100, in onRecvData
    self.receive(data)
  File "/opt/fhem/yowsup-master/yowsup/layers/network/layer.py", line 103, in receive
    self.toUpper(data)
  File "/opt/fhem/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/fhem/yowsup-master/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/opt/fhem/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/fhem/yowsup-master/yowsup/layers/noise/layer.py", line 156, in receive
    self._flush_incoming_buffer()
  File "/opt/fhem/yowsup-master/yowsup/layers/noise/layer.py", line 144, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/opt/fhem/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/fhem/yowsup-master/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/opt/fhem/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/fhem/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/opt/fhem/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/fhem/yowsup-master/yowsup/layers/axolotl/layer_control.py", line 32, in receive
    self.toUpper(protocolTreeNode)
  File "/opt/fhem/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/fhem/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/opt/fhem/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 34, in receive
    self.toUpper(protocolTreeNode)
  File "/opt/fhem/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/fhem/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/opt/fhem/yowsup-master/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/opt/fhem/yowsup-master/yowsup/layers/auth/layer_authentication.py", line 72, in handleStreamError
    raise NotImplementedError("Unhandled stream:error node:\n%s" % node)
NotImplementedError: Unhandled stream:error node:
<stream:error>
<bad-mac>
</bad-mac>
</stream:error>
```

**Comment by tgalal** [comment]
Got the following error while doing what, just login? Sent a text message? Sent an image? Created a group? Is the error repeating? Any information about how to reproduce? Which yowsup version, which python version? Is this one of the yowsup-cli demos or an own client? Please attach relevant information, and a debug-enabled dump if this was yowsup-cli demo.

**Comment by jowiemann** [comment]
Sorry, no more infos available. It happens just while demo client is running. May be this error will reapear and I can get more informations.

**Comment by jowiemann** [comment]
Seems to be a single event
