### ISSUE TITLE
unhandled <stream:error> exception

### ISSUE THREAD

**Issue by kepeto** [tgalal/yowsup#272]
hi,

is there any ways how to catch the unhandled exception?

from example i use this simple method to start client

``` python
try:
  wa = WhatsappListenerClient()
  wa.login(login, password)
except Exception, e:
  print("Exception: %s") % str(e)
```

but i cannot catch this following error / exception, no onDisconnect event is trigered

``` xml
ReaderThread: Waiting, time to die: T-150 seconds
ReaderThread: Waiting, time to die: T-120 seconds
BinTreeNodeReader:     Incoming
BinTreeNodeReader:
<stream:error>
<ack>
</ack>
</stream:error>

Exception in thread Thread-682:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/Yowsup/connectionmanager.py", line 896, in run
    except FatalStreamErrorException, e:
NameError: global name 'FatalStreamErrorException' is not defined
```

**Comment by sattva1** [comment]
I've dealt it this way: #1535
