### ISSUE TITLE
'utf-8' codec can't decode byte 0x8d in position 1: invalid start byte

### ISSUE THREAD

**Issue by mrolinek** [tgalal/yowsup#2721]
I am running commit 97e91569 and it "almost" works. I was able to send and receive a couple of messages some direct, some group messages.

However, there still seems to be something unstable with decrypting the group messages. Now I am receiving the following error:

```
E 2019-05-06 09:55:13,034 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/python_axolotl-0.1.39-py3.6.egg/axolotl/groups/groupcipher.py", line 108, in getPlainText
    return plaintext.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 1: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/network/layer.py", line 100, in onRecvData
    self.receive(data)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/network/layer.py", line 103, in receive
    self.toUpper(data)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/noise/layer.py", line 156, in receive
    self._flush_incoming_buffer()
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/noise/layer.py", line 144, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/axolotl/layer_receive.py", line 31, in receive
    self.onMessage(protocolTreeNode)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/axolotl/layer_receive.py", line 63, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/axolotl/layer_receive.py", line 79, in handleEncMessage
    self.handleSenderKeyMessage(node)
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/layers/axolotl/layer_receive.py", line 145, in handleSenderKeyMessage
    data=enc.getData()
  File "/home/al/.local/lib/python3.6/site-packages/yowsup-3.2.0-py3.6.egg/yowsup/axolotl/manager.py", line 210, in group_decrypt
    plaintext = group_cipher.decrypt(data)
  File "/usr/local/lib/python3.6/dist-packages/python_axolotl-0.1.39-py3.6.egg/axolotl/groups/groupcipher.py", line 68, in decrypt
    plaintext = self.getPlainText(senderKey.getIv(), senderKey.getCipherKey(), senderKeyMessage.getCipherText())
  File "/usr/local/lib/python3.6/dist-packages/python_axolotl-0.1.39-py3.6.egg/axolotl/groups/groupcipher.py", line 113, in getPlainText
    raise InvalidMessageException(e)
axolotl.invalidmessageexception.InvalidMessageException: 'utf-8' codec can't decode byte 0x8d in position 1: invalid start byte
```

**Comment by Wedmal** [comment]
it?

> https://github.com/tgalal/yowsup/issues/1592

**Comment by mrolinek** [comment]
Hm... strangely, I am running Python3 so these encoding problems shouldn't happen. For the same reason, the fixes suggested in [#1592](https://github.com/tgalal/yowsup/issues/1592) don't even apply. Or am I missing something?

**Comment by tgalal** [comment]
It's a bug in python-axolotl, fixed by https://github.com/tgalal/python-axolotl/commit/d04105ac7c546b6df74ceb561c3b206f2f856be0 namely changed to `groupcipher.py`.
This might still need slight adjustments in yowsup though which will be in next release.

**Comment by bahtiarp** [comment]
For me it works after modify:

return plaintext.decode('unicode-escape')
