### ISSUE TITLE
Asyncore Error

### ISSUE THREAD

**Issue by devalexanderdaza** [tgalal/yowsup#2723]
Hi guys, I'm getting this error after yowsup-cli gets the config.json file that has the account settings.

Any idea what may be happening? I am using Python 3.6 in a MacOS High Sierra environment.

```ERROR:yowsup.layers.network.dispatcher.dispatcher_asyncore:Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 441, in handle_write_event
    self.handle_connect_event()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 429, in handle_connect_event
    self.handle_connect()
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 3 more times]
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/Users/alexanderdaza/Desktop/yowsapp-framework/venv/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 63, in on_auth
    assert type(local_static) is KeyPair
AssertionError
```

**Comment by tgalal** [comment]
what command did you run, which yowsup version, and run with `--debug` and include output. Additionally your config.json file with sensitive information (phone, identity, client_static_keypair) masked (not removed) would be useful.

**Comment by devalexanderdaza** [comment]
Hi @tgalal i get this error after following the next steps:

1. I installed yowsup in its most recent version today which is 3.2.3

2. I entered the wiki in the option to create a sample application that echoes everything that they send.

3. First, in the run.py file on lines 31, 32, and 33 you can not find the references PROP_DOMAIN, PROP_RESOURCE, and .getResource ()

4. I commented on these lines and launched again python run.py

5. I threw the error mentioned above, however I update it at this time:

`Alexanders-MacBook-Pro:yowsapp-framework alexanderdaza$ python run.py 
E 2019-05-08 09:47:17,953 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 441, in handle_write_event
    self.handle_connect_event()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncore.py", line 429, in handle_connect_event
    self.handle_connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/network/layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 3 more times]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/noise/layer.py", line 63, in on_auth
    assert type(local_static) is KeyPair
AssertionError

^CTraceback (most recent call last):
  File "run.py", line 37, in <module>
    stack.loop()  # this is the program mainloop
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/stacks/yowstack.py", line 188, in loop
    time.sleep(0.1)
KeyboardInterrupt
`

I really appreciate your help.

**Comment by AmitGamingKing** [comment]
facing the same error

**Comment by Neolysion** [comment]
Exact same problem for me. Running yowsup 3.2.3 on ubuntu. Here is my traceback with a bit of debug log before and after:

```
I 2019-05-23 18:51:16,699 yowsup.axolotl.manager - Loaded 812 unsent prekeys
2019-05-23 18:51:16,699 - yowsup.axolotl.manager - INFO - Loaded 812 unsent prekeys
D 2019-05-23 18:51:16,699 yowsup.layers.noise.layer - Received auth event
2019-05-23 18:51:16,699 - yowsup.layers.noise.layer - DEBUG - Received auth event
D 2019-05-23 18:51:16,699 yowsup.config.manager - Detecting config for username=41xxxxxxxxxx, dir=/home/Boro/.config/yowsup/41xxxxxxxxxx/
2019-05-23 18:51:16,699 - yowsup.config.manager - DEBUG - Detecting config for username=41xxxxxxxxxx, dir=/home/Boro/.config/yowsup/41xxxxxxxxxx/
D 2019-05-23 18:51:16,699 yowsup.config.manager - Trying /home/Boro/.config/yowsup/41xxxxxxxxxx/config.json
2019-05-23 18:51:16,699 - yowsup.config.manager - DEBUG - Trying /home/Boro/.config/yowsup/41xxxxxxxxxx/config.json
D 2019-05-23 18:51:16,699 yowsup.config.manager - load_path(path=/home/Boro/.config/yowsup/41xxxxxxxxxx/config.json)
2019-05-23 18:51:16,699 - yowsup.config.manager - DEBUG - load_path(path=/home/Boro/.config/yowsup/41xxxxxxxxxx/config.json)
D 2019-05-23 18:51:16,699 yowsup.config.manager - Detected config type: json
2019-05-23 18:51:16,699 - yowsup.config.manager - DEBUG - Detected config type: json
D 2019-05-23 18:51:16,699 yowsup.config.manager - Opening config for reading
2019-05-23 18:51:16,699 - yowsup.config.manager - DEBUG - Opening config for reading
D 2019-05-23 18:51:16,700 yowsup.config.manager - Loading config
2019-05-23 18:51:16,700 - yowsup.config.manager - DEBUG - Loading config
E 2019-05-23 18:51:16,701 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.5/asyncore.py", line 441, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.5/asyncore.py", line 429, in handle_connect_event
    self.handle_connect()
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/network/layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/noise/layer.py", line 63, in on_auth
    assert type(local_static) is KeyPair
AssertionError

2019-05-23 18:51:16,701 - yowsup.layers.network.dispatcher.dispatcher_asyncore - ERROR - Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.5/asyncore.py", line 441, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.5/asyncore.py", line 429, in handle_connect_event
    self.handle_connect()
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/network/layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/home/Boro/.local/lib/python3.5/site-packages/yowsup/layers/noise/layer.py", line 63, in on_auth
    assert type(local_static) is KeyPair
AssertionError

D 2019-05-23 18:51:16,701 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
2019-05-23 18:51:16,701 - yowsup.layers.network.dispatcher.dispatcher_asyncore - DEBUG - handle_close
D 2019-05-23 18:51:16,701 yowsup.layers.network.layer - Disconnected
2019-05-23 18:51:16,701 - yowsup.layers.network.layer - DEBUG - Disconnected

```

Also I wasn't quite sure about the "password" in the example app. I entered the "client_static_keypair" from the registration result, was that right? 
(it looks like yowsup took the config file from my profile folder for authentication anyway)

**Comment by Neolysion** [comment]
nvm I found the problem. the assert function was expecting a consonance keypair but I gave it the client_static_keypair (aka. password) as string.
converting the string into a keypair before setting the credentials prop works.

```
from consonance.structs.keypair import KeyPair
import base64

keypair = KeyPair.from_bytes(
     base64.b64decode("password")
)

CREDENTIALS = ("phone", keypair)
```

**Comment by ChinoGC** [comment]
I'm facing the same mistake, but in the demo.

**Comment by langioletto** [comment]
Hi @devalexanderdaza 

you can kindly post here your run.py

I have an old version that worked with yowsp 2 and I would like to adapt it with yowsup 3

Very thanks

**Comment by tsifra** [comment]
@langioletto you can get code from here https://github.com/tgalal/yowsup/wiki/Sample-Application I use layer.py I and run.py I with modification by @Neolysion

```
...
from consonance.structs.keypair import KeyPair
import base64

keypair = KeyPair.from_bytes(
     base64.b64decode("[value from ~/.config/yowsup/(phone number)/config.json - client_static_keypair]")
)

credentials = ("79032624557", keypair) # replace with your phone and password
...
```
