### ISSUE TITLE
Wrong wire type in tag. in protobuf

### ISSUE THREAD

**Issue by Sharissa90** [tgalal/yowsup#2729]
Suddenly we have this error
```Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/yowsup-3.2.3-py3.5.egg/yowsup/layers/noise/workers/handshake.py", line 36, in run
    self._protocol.start(self._stream, self._client_config, self._s, self._rs)
  File "/usr/local/lib/python3.5/dist-packages/consonance/protocol.py", line 82, in start
    result = handshake.perform(client_config, stream, s, rs)
  File "/usr/local/lib/python3.5/dist-packages/consonance/handshake.py", line 80, in perform
    cipherstatepair = self._start_handshake_ik(stream, client_payload, dissononce_s, dissononce_rs)
  File "/usr/local/lib/python3.5/dist-packages/consonance/handshake.py", line 182, in _start_handshake_ik
    incoming_handshakemessage.ParseFromString(stream.read_segment())
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/message.py", line 187, in ParseFromString
    return self.MergeFromString(serialized)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 1124, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/python_message.py", line 1176, in InternalParse
    buffer, new_pos, wire_type)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/internal/decoder.py", line 952, in _DecodeUnknownField
    raise _DecodeError('Wrong wire type in tag.')
google.protobuf.message.DecodeError: Wrong wire type in tag.
```

Name: protobuf
Version: 3.8.0rc1
Summary: Protocol Buffers

Name: yowsup
Version: 3.2.3
Summary: The WhatsApp lib

**Comment by tommyyama2020** [comment]
I have same issue here. Is this fixed? 
Any solution would be appreciated!

**Comment by vomov** [comment]
Exactly the same issue here, on a managed kafka cluster. Does anyone have any idea?
