### ISSUE TITLE
Unable to register 

### ISSUE THREAD

**Issue by febin-nucore** [tgalal/yowsup#2731]
yowsup-cli registration --requestcode sms --phone 916238903201 --cc 91 -E android

E 2019-05-08 13:15:15,093 yowsup.config.manager - Could not find a config for username=916238903201, paths checked: /home/febin/.config/yowsup/916238903201/config.yo:/home/febin/.config/yowsup/916238903201/config.json
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Traceback (most recent call last):
  File "/home/febin/.local/bin/yowsup-cli", line 679, in <module>
    if not parser.process():
  File "/home/febin/.local/bin/yowsup-cli", line 350, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/home/febin/.local/bin/yowsup-cli", line 361, in handleRequestCode
    codeReq = WACodeRequest(method, config)
  File "/home/febin/.local/lib/python3.7/site-packages/yowsup/registration/coderequest.py", line 15, in __init__
    super(WACodeRequest,self).__init__(config)
  File "/home/febin/.local/lib/python3.7/site-packages/yowsup/common/http/warequest.py", line 71, in __init__
    config.client_static_keypair = WATools.generateKeyPair()
  File "/home/febin/.local/lib/python3.7/site-packages/yowsup/common/tools.py", line 70, in generateKeyPair
    return KeyPair.generate()
  File "/home/febin/.local/lib/python3.7/site-packages/consonance/structs/keypair.py", line 36, in generate
    keypair = X25519DH().generate_keypair()
  File "/home/febin/.local/lib/python3.7/site-packages/dissononce/dh/x25519/x25519.py", line 37, in generate_keypair
    encoding=serialization.Encoding.Raw,
  File "/usr/lib/python3.7/enum.py", line 349, in __getattr__
    raise AttributeError(name) from None
AttributeError: Raw

**Comment by tgalal** [comment]
update cryptography to >=2.5
