### ISSUE TITLE
Problems sending messages with Unicode

### ISSUE THREAD

**Issue by dazzzl** [tgalal/yowsup#2732]
I have problems sending messages with Unicode (Emojis)

python 2.7

File "/opt/transwhat2/yowsup/axolotl/manager.py", line 150, in encrypt
    logger.debug("encrypt(recipientid=%s, message=%s)" % (recipient_id, message))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 2: ordinal not in range(128)

**Comment by tgalal** [comment]
yowsup version?

**Comment by dazzzl** [comment]
from yesterday ... 
commit 2fe65132257eb37c2dfbe82de7bd93a1707c276e

**Comment by tgalal** [comment]
ok please post more information, like full debug output and how are you sending the emoji

**Comment by dazzzl** [comment]
I looked for the important code lines:

'message = message.encode("utf-8")
messageEntity = TextMessageProtocolEntity(message, to = to)
self.stack.broadcastEvent(YowLayerEvent(YowsupAppLayer.TO_LOWER_EVENT,
                        entity = messageEntity))'

Output + Trace:
`019-05-08 18:58:36,169 DEBUG WhatsAppBackend: handleMessageSendRequest(user=xxx, buddy=xxx, message=<U+1F600> , xhtml=, ID=3b7c253a-cb13-4672-a685-2d96a7492ac6)
2019-05-08 18:58:36,169 INFO Session: Message sent from xxx to xxx <U+1F600>  (xhtml=)
2019-05-08 18:58:36,171 DEBUG yowsup.axolotl.manager: session_exists(xxx)?
2019-05-08 18:58:36,219 ERROR transwhat: Traceback (most recent call last):
  File "/opt/transwhat2/transwhat.py", line 75, in handleTransportData
    plugin.handleDataRead(data)
  File "/opt/transwhat2/Spectrum2/backend.py", line 423, in handleDataRead
    self.handleConvMessagePayload(wrapper.payload)
  File "/opt/transwhat2/Spectrum2/backend.py", line 277, in handleConvMessagePayload
    self.handleMessageSendRequest(payload.userName, payload.buddyName, payload.message, payload.xhtml, payload.id)
  File "/opt/transwhat2/whatsappbackend.py", line 73, in handleMessageSendRequest
    self.sessions[user].sendMessageToWA(buddy, message, ID, xhtml)
  File "/opt/transwhat2/session.py", line 731, in sendMessageToWA
    waId = self.sendTextMessage(sender + '@s.whatsapp.net', message)
  File "/opt/transwhat2/yowsupwrapper.py", line 172, in sendTextMessage
    self.sendEntity(messageEntity)
  File "/opt/transwhat2/yowsupwrapper.py", line 701, in sendEntity
    entity = entity
  File "/opt/transwhat2/yowsup/stacks/yowstack.py", line 175, in broadcastEvent
    if not self.__stackInstances[-1].onEvent(yowLayerEvent):
  File "/opt/transwhat2/yowsupwrapper.py", line 734, in onEvent
    self.toLower(layerEvent.getArg('entity'))
  File "/opt/transwhat2/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/opt/transwhat2/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/opt/transwhat2/yowsup/layers/__init__.py", line 136, in send
    send(entity)
  File "/opt/transwhat2/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/opt/transwhat2/yowsup/layers/__init__.py", line 140, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/opt/transwhat2/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/opt/transwhat2/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/opt/transwhat2/yowsup/layers/axolotl/layer_send.py", line 37, in send
    self.processPlaintextNodeAndSend(node)
  File "/opt/transwhat2/yowsup/layers/axolotl/layer_send.py", line 71, in processPlaintextNodeAndSend
    self.sendToContact(node)
  File "/opt/transwhat2/yowsup/layers/axolotl/layer_send.py", line 112, in sendToContact
    messageData
  File "/opt/transwhat2/yowsup/axolotl/manager.py", line 150, in encrypt
    logger.debug("encrypt(recipientid=%s, message=%s)" % (recipient_id, message))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 2: ordinal not in range(128)

2019-05-08 18:59:12,249 DEBUG yowsup.layers.protocol_iq.layer: ping queue size: 1
`

Hope this helps

**Comment by dazzzl** [comment]
It is only the debug output. By remove the debug output, the message will be sent correctly.

**Comment by tgalal** [comment]
I'm not able to reproduce, but I also see no advantage of including the message content in that specific log line so I'll just remove it. Please close the issue if 749ac64a0f72109fc3cc94447a8433056b28b5e2 fixed the problem.

**Comment by dazzzl** [comment]
Ok, it is working. Thanks!
