### ISSUE TITLE
after login

### ISSUE THREAD

**Issue by monica-delcastillo** [tgalal/yowsup#2750]
Hi. Thanks for this fantastic project. I known recently and it will resolve my life.

I install, register new number and make the first login. All work ok. But, every exist a BUT

After prekey show it

`Storing prekey 167/812 
I 2019-05-14 07:33:25,424 yowsup.axolotl.manager - Loaded 812 unsent prekeys

Auth: Logged in!
[connected]:
[connected]:
[connected]:
W 2019-05-14 07:33:25,941 yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now
[connected]:W 2019-05-14 07:33:25,942 yowsup.layers.protocol_ib.layer - ignoring attestation ib node for now
E 2019-05-14 07:33:26,628 yowsup.layers.network.dispatcher.dispatcher_socket - [Errno 9] Bad file descriptor
I 2019-05-14 07:33:26,725 yowsup.layers.network.layer - Connecting to e7.whatsapp.net:443
I 2019-05-14 07:33:26,770 yowsup.axolotl.manager - Loaded 0 unsent prekeys
Auth: Logged in!
W 2019-05-14 07:33:27,063 yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now
E 2019-05-14 07:33:27,144 yowsup.layers.network.dispatcher.dispatcher_socket - No such prekeyRecord!
general: Disconnected: `

If I try relogin I see

`[offline]:/L
I 2019-05-14 07:33:33,483 yowsup.layers.network.layer - Connecting to e7.whatsapp.net:443
[offline]:I 2019-05-14 07:33:33,529 yowsup.axolotl.manager - Loaded 0 unsent prekeys
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/yowsup-3.1.0-py2.7.egg/yowsup/layers/noise/workers/handshake.py", line 36, in run
    self._protocol.start(self._stream, self._client_config, self._s, self._rs)
  File "/usr/lib/python2.7/site-packages/consonance-0.1.1-py2.7.egg/consonance/protocol.py", line 82, in start
    result = handshake.perform(client_config, stream, s, rs)
  File "/usr/lib/python2.7/site-packages/consonance-0.1.1-py2.7.egg/consonance/handshake.py", line 80, in perform
    cipherstatepair = self._start_handshake_ik(stream, client_payload, dissononce_s, dissononce_rs)
  File "/usr/lib/python2.7/site-packages/consonance-0.1.1-py2.7.egg/consonance/handshake.py", line 182, in _start_handshake_ik
    incoming_handshakemessage.ParseFromString(stream.read_segment())
  File "/usr/lib/python2.7/site-packages/protobuf-3.6.0-py2.7.egg/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/lib/python2.7/site-packages/protobuf-3.6.0-py2.7.egg/google/protobuf/internal/python_message.py", line 1086, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
DecodeError: Unexpected end-group tag.`

thanks

**Comment by monica-delcastillo** [comment]
I update and it was fixed. Sorry, i not seen the last commit
