### ISSUE TITLE
can't connect to whatsapp - Exception("Sent keys were not accepted")

### ISSUE THREAD

**Issue by NicoSoftware** [tgalal/yowsup#2762]
when connecting with yowsup-cli demos I get the following error:
```
==================
Type /help for available commands

[offline]:/L
I 2019-05-19 16:33:02,095 yowsup.layers.network.layer - Connecting to e10.whatsapp.net:443
I 2019-05-19 16:33:02,226 yowsup.axolotl.manager - Generating 812 prekeys
I 2019-05-19 16:33:03,814 yowsup.axolotl.manager - Storing 812 prekeys
I 2019-05-19 16:33:12,781 yowsup.axolotl.manager - Loaded 812 unsent prekeys
Auth: Logged in!
[connected]:E 2019-05-19 16:33:14,195 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/network/layer.py", line 100, in onRecvData
    self.receive(data)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/network/layer.py", line 103, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/noise/layer.py", line 156, in receive
    self._flush_incoming_buffer()
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/noise/layer.py", line 144, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/axolotl/layer_control.py", line 28, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 163, in processIqRegistry
    errorClbk(protocolTreeNode, originalIq)
  File "/usr/local/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/axolotl/layer_control.py", line 118, in onSentKeysError
    raise Exception("Sent keys were not accepted")
Exception: Sent keys were not accepted

general: Disconnected:
[connected]:

```
![image](https://user-images.githubusercontent.com/35654361/57983700-5f3aab00-7a55-11e9-9214-4ea25ede4fe8.png)

Thanks in advantage!

**Comment by NicoSoftware** [comment]
Can't get any config information too:
```
![image](https://user-images.githubusercontent.com/35654361/57985503-2f959e00-7a69-11e9-8b33-c0cbc2372579.png)
```

**Comment by tgalal** [comment]
Please don't include information/comments irrelevant to the issue. See my [comment here](https://github.com/tgalal/yowsup/issues/2791#issuecomment-498660334) regarding the same issue. Closing this one as it doesn't have enough information.
