### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'axolotl_manager'

### ISSUE THREAD

**Issue by danya3** [tgalal/yowsup#2773]
Hello, I have some problem with echo client. After starting the application, I get this error
```E 2019-05-24 18:17:06,876 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncore.py", line 440, in handle_write_event
    self.handle_connect_event()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncore.py", line 428, in handle_connect_event
    self.handle_connect()
  File "/Users/localadmin/Documents/WhatsApp_V3/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/Users/localadmin/Documents/WhatsApp_V3/yowsup/layers/network/layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/Users/localadmin/Documents/WhatsApp_V3/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/Users/localadmin/Documents/WhatsApp_V3/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/Users/localadmin/Documents/WhatsApp_V3/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/Users/localadmin/Documents/WhatsApp_V3/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/Users/localadmin/Documents/WhatsApp_V3/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/Users/localadmin/Documents/WhatsApp_V3/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/Users/localadmin/Documents/WhatsApp_V3/yowsup/layers/axolotl/layer_base.py", line 38, in on_connected
    self._manager = profile.axolotl_manager
AttributeError: 'NoneType' object has no attribute 'axolotl_manager'`



My **run.py**
`from layer import EchoLayer
from yowsup.layers                             import YowParallelLayer
from yowsup.layers.auth                        import YowAuthenticationProtocolLayer
from yowsup.layers.protocol_messages           import YowMessagesProtocolLayer
from yowsup.layers.protocol_receipts           import YowReceiptProtocolLayer
from yowsup.layers.protocol_acks               import YowAckProtocolLayer
from yowsup.layers.network                     import YowNetworkLayer
from yowsup.common import YowConstants
from yowsup.layers import YowLayerEvent
from yowsup.stacks import YowStack, YOWSUP_CORE_LAYERS
from yowsup.layers.axolotl                     import AxolotlControlLayer, AxolotlSendLayer, AxolotlReceivelayer


CREDENTIALS = ("**********", False) 

if __name__==  "__main__":
    layers = (
        EchoLayer,
        YowParallelLayer([YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer,
                          YowAckProtocolLayer]),
        AxolotlControlLayer,
        YowParallelLayer((AxolotlSendLayer, AxolotlReceivelayer)),
    ) + YOWSUP_CORE_LAYERS

    stack = YowStack(layers)
    stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, CREDENTIALS)         
    stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])    
    #stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
    #stack.setProp(YowCoderLayer.PROP_RESOURCE, YowsupEnv.getCurrent().getResource())          

    stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))   

    stack.loop() `

My **layer.py**

`
from yowsup.layers.interface                           import YowInterfaceLayer, ProtocolEntityCallback

class EchoLayer(YowInterfaceLayer):

    @ProtocolEntityCallback("message")
    def onMessage(self, messageProtocolEntity):
        if messageProtocolEntity.getType() == 'text':
            phone = messageProtocolEntity.getFrom(False)
            message = messageProtocolEntity.conversation
            print(phone + ' ' + message)
        elif messageProtocolEntity.getType() == 'media':
            self.onMediaMessage(messageProtocolEntity)

        self.toLower(messageProtocolEntity.forward(messageProtocolEntity.getFrom()))
        self.toLower(messageProtocolEntity.ack())
        self.toLower(messageProtocolEntity.ack(True))


    @ProtocolEntityCallback("receipt")
    def onReceipt(self, entity):
        self.toLower(entity.ack())

    def onMediaMessage(self, messageProtocolEntity):
        if messageProtocolEntity.media_type == "image":
            print("Echoing image %s to %s" % (messageProtocolEntity.url, messageProtocolEntity.getFrom(False)))

        elif messageProtocolEntity.media_type == "location":
            print("Echoing location (%s, %s) to %s" % (messageProtocolEntity.getLatitude(), messageProtocolEntity.getLongitude(), messageProtocolEntity.getFrom(False)))

        elif messageProtocolEntity.media_type == "contact":
            print("Echoing contact (%s, %s) to %s" % (messageProtocolEntity.getName(), messageProtocolEntity.getCardData(), messageProtocolEntity.getFrom(False)))
```

**Comment by tgalal** [comment]
Samples are outdated I need to fix that. In the mean time check the [Echo client's stack](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/echoclient/stack.py) in demos.
