### ISSUE TITLE
I can't log in, the error: assert type(local_static) is KeyPair AssertionError

### ISSUE THREAD

**Issue by ChinoGC** [tgalal/yowsup#2775]
Hello. Im getting this error after launching the demo.
IN:
`root@raspberrypi:/home/pi/yowsup# yowsup-cli demos --yowsup --config config`
OUT:
```
I 2019-05-25 12:47:53,623 yowsup.profile.profile - Constructed Profile(profile_name=593XXXXXXXXX)
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Yowsup Cli client
==================
Type /help for available commands

[offline]:
```

And when I try to connect with `/L` i'm getting the next error:

```
[offline]:/L
I 2019-05-25 12:49:44,133 yowsup.layers.network.layer - Connecting to e11.whatsapp.net:443
I 2019-05-25 12:49:44,627 yowsup.axolotl.manager - Loaded 812 unsent prekeys
E 2019-05-25 12:49:44,631 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python2.7/asyncore.py", line 467, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python2.7/asyncore.py", line 455, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer.py", line 68, in on_auth
    assert type(local_static) is KeyPair
AssertionError

general: Disconnected: 
[offline]:
```

My config file, located in `/home/pi/yowsup`, is:
```
## Actual config starts below ##
  cc=593
  phone=593XXXXXXXXX
```
Help me please.

**Comment by ChinoGC** [comment]
I'm working with a Raspberry Pi

**Comment by tgalal** [comment]
your config is missing data obtained during registration, try register first

**Comment by ChinoGC** [comment]
I have already registered. My info is:

```
root@raspberrypi:/home/pi/yowsup# python yowsup-cli registration --register 124-958 --phone 593xxxxxxxxx --cc 593
I 2019-05-25 11:08:21,711 yowsup.profile.profile - Constructed Profile(profile_name=593xxxxxxxxx)
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


W 2019-05-25 11:08:21,969 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
I 2019-05-25 11:08:21,970 yowsup.profile.profile - Constructed Profile(profile_name=593978690745)
I 2019-05-25 11:08:23,759 yowsup.common.http.warequest - {"status":"ok","login":"593978690745","type":"existing","edge_routing_info":"CAUIAg==","chat_dns_domain":"fb","security_code_set":false}

{
    "_version_": 1,
    "cc": "593",
    "client_static_keypair": "oEPkQyxd5lA7w/dOxi5NdOaqdIv8ErPTOQO7SSc1EW1nPnl4OSw63lMpLwk2hCESrIIT7tBHepP6CbbXU9ShQg==",
    "expid": "xxxxxxxxxxxxxxxxxxxx==",
    "fdid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=",
    "login": "593xxxxxxxxx",
    "mcc": "740",
    "mnc": "03",
    "phone": "593xxxxxxxxx",
    "sim_mcc": "xxx",
    "sim_mnc": "xxx"
}
status: ok
edge_routing_info: CAUIAg==
login: 593xxxxxxxxx
type: existing

```
What other data is missing in my config?

**Comment by ChinoGC** [comment]
I have already registered. My info is:

```
root@raspberrypi:/home/pi/yowsup# python yowsup-cli registration --register 124-958 --phone 593xxxxxxxxx --cc 593
I 2019-05-25 11:08:21,711 yowsup.profile.profile - Constructed Profile(profile_name=593xxxxxxxxx)
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


W 2019-05-25 11:08:21,969 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
I 2019-05-25 11:08:21,970 yowsup.profile.profile - Constructed Profile(profile_name=593xxxxxxxxx)
I 2019-05-25 11:08:23,759 yowsup.common.http.warequest - {"status":"ok","login":"593xxxxxxxxx","type":"existing","edge_routing_info":"CAUIAg==","chat_dns_domain":"fb","security_code_set":false}

{
    "_version_": 1,
    "cc": "593",
    "client_static_keypair": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==",
    "expid": "xxxxxxxxxxxxxxxxxxxx==",
    "fdid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=",
    "login": "593xxxxxxxxx",
    "mcc": "740",
    "mnc": "03",
    "phone": "593xxxxxxxxx",
    "sim_mcc": "xxx",
    "sim_mnc": "xxx"
}
status: ok
edge_routing_info: CAUIAg==
login: 593xxxxxxxxx
type: existing

```
What other data is missing in my config?

**Comment by ChinoGC** [comment]
At the time of registration, the configuration file was not generated in `~/.yowsup/blabla`. So I used the optional configuration option `-c path`, in case that someone have the same mistake in the future.
