### ISSUE TITLE
ValueError: config.id is not set.

### ISSUE THREAD

**Issue by akak92** [tgalal/yowsup#2784]
Hello, I'm trying to finish the registration process (I've already have the XXX-XXX code) but im getting this message when a execute: **_python yowsup-cli registration --register xxx-xxx --phone 54xxxxxxxxxx --cc 54_**

```
pi@raspberrypi:~/yowsup $ python yowsup-cli registration --register xxx-xxx --phone 54xxxxxxxxxx --cc 54

W 2019-06-01 03:22:51,337 yowsup.config.v1.config - Setting a password in Config is deprecated and not used anymore. client_static_keypair is used instead
yowsup-cli  v3.2.0
yowsup      v3.2.3


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

W 2019-06-01 03:22:51,589 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
Traceback (most recent call last):
  File "yowsup-cli", line 713, in <module>
    if not parser.process():
  File "yowsup-cli", line 390, in process
    self.handleRegister(self.args["register"], config)
  File "yowsup-cli", line 419, in handleRegister
    req = WARegRequest(config, code)
  File "/home/pi/yowsup/yowsup/registration/regrequest.py", line 38, in __init__
    raise ValueError("config.id is not set.")
ValueError: config.id is not set.

```

What I'm doing wrong?
Thanks!

**Comment by tgalal** [comment]
> What I'm doing wrong?

1- you did not follow the bug report template
2- you are not using a released version, but code from master branch, which is fine, but please indicate the which commit hash this is.

Closing for lack of information.
