### ISSUE TITLE
ImportError: No module named handshake_failed_exception

### ISSUE THREAD

**Issue by ghersonn** [tgalal/yowsup#2799]
python yowsup-cli demos -c config -s 51xxxxxxxxx "hello"

**when I execute the following command I get the following error:**

Traceback (most recent call last):
  File "yowsup-cli", line 722, in <module>
    if not parser.process():
  File "yowsup-cli", line 610, in process
    self.startSendClient()
  File "yowsup-cli", line 649, in startSendClient
    from yowsup.demos import sendclient
  File "/home/gizquierdo/Escritorio/yowsup-master/yowsup/demos/sendclient/__init__.py", line 1, in <module>
    from .stack import YowsupSendStack
  File "/home/gizquierdo/Escritorio/yowsup-master/yowsup/demos/sendclient/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/home/gizquierdo/Escritorio/yowsup-master/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/home/gizquierdo/Escritorio/yowsup-master/yowsup/stacks/yowstack.py", line 4, in <module>
    from yowsup.layers.noise.layer import YowNoiseLayer
  File "/home/gizquierdo/Escritorio/yowsup-master/yowsup/layers/noise/layer.py", line 1, in <module>
    from yowsup.layers.noise.workers.handshake import WANoiseProtocolHandshakeWorker
  File "/home/gizquierdo/Escritorio/yowsup-master/yowsup/layers/noise/workers/handshake.py", line 3, in <module>
    from consonance.exceptions.handshake_failed_exception import HandshakeFailedException
ImportError: No module named handshake_failed_exception

**Comment by tgalal** [comment]
please follow the bug report template. closing for lack of information.

**Comment by cesarnvf** [comment]
Tengo el mismo error:
raceback (most recent call last):
  File "./yowsup-cli", line 722, in <module>
    if not parser.process():
  File "./yowsup-cli", line 610, in process
    self.startSendClient()
  File "./yowsup-cli", line 649, in startSendClient
    from yowsup.demos import sendclient
  File "/home/cesarnvf/Desarrollo/yowsup/yowsup/demos/sendclient/__init__.py", line 1, in <module>
    from .stack import YowsupSendStack
  File "/home/cesarnvf/Desarrollo/yowsup/yowsup/demos/sendclient/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/home/cesarnvf/Desarrollo/yowsup/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/home/cesarnvf/Desarrollo/yowsup/yowsup/stacks/yowstack.py", line 4, in <module>
    from yowsup.layers.noise.layer import YowNoiseLayer
  File "/home/cesarnvf/Desarrollo/yowsup/yowsup/layers/noise/layer.py", line 1, in <module>
    from yowsup.layers.noise.workers.handshake import WANoiseProtocolHandshakeWorker
  File "/home/cesarnvf/Desarrollo/yowsup/yowsup/layers/noise/workers/handshake.py", line 3, in <module>
    from consonance.exceptions.handshake_failed_exception import HandshakeFailedException
ImportError: No module named handshake_failed_exception

Se pudo resolver, gracias, Saludos.
