### ISSUE TITLE
yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):

### ISSUE THREAD

**Issue by HeinzFo** [tgalal/yowsup#2805]
Hello

I get this Error 3-5 times every Day.
10min. after this error yowsup reconnect and keep working.
Preferably, this happens between 22:00 and 6:00 EST and sometimes also during the day.

> E 2019-06-11 13:42:04,459 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/opt/yowsup-master/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/opt/yowsup-master/yowsup/layers/network/layer.py", line 107, in onRecvData
    self.receive(data)
  File "/opt/yowsup-master/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/opt/yowsup-master/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/opt/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 32, in receive
    self.onMessage(protocolTreeNode)
  File "/opt/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 48, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/opt/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 62, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/opt/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 126, in handleWhisperMessage
    self.toUpper(node)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/opt/yowsup-master/yowsup/layers/protocol_messages/layer.py", line 36, in recvMessageStanza
    message.conversation, MessageMetaAttributes.from_message_protocoltreenode(node)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/opt/yowsup-master/yowsup/demos/cli/layer.py", line 504, in onMessage
    self.output(output, tag = None, prompt = not self.sendReceipts)
  File "/opt/yowsup-master/yowsup/demos/cli/cli.py", line 180, in output
    print(message)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 74: ordinal not in range(128)

**YOWSUP:**
yowsup-cli v3.2.0
using:
  consonance v0.1.3-1
  protobuf v3.6.0
  cryptography v2.6.1
  yowsup v3.2.3
  dissononce v0.34.3
  python-axolotl v0.2.2

**PYTHON:**
Python Version 2.7.13

**OS on Rasperry PI3:**
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by NelsonGaldeman** [comment]
It has to do with a latin char: "ü"
Try to send yourself a message with that char and check if that breaks the code.

**Comment by HeinzFo** [comment]
I send the **ü** or the word **über** and none error occurs, the message will send correctly to my Android smart phone.

**Comment by tgalal** [comment]
Logs contain "yowsup-master", can you please specify the commit hash?

**Comment by HeinzFo** [comment]
Please help me, what is the commit hash?

**Comment by tgalal** [comment]
in that case I'll have to ask you to install a released yowsup version and not use directly from the repo. I'll also close the issue because of the missing information. Do open a new issue if you encounter the problem on a released version, or if you are able to attach a commit hash to the information.

**Comment by HeinzFo** [comment]
missing information commit hash 69c5211

**Comment by hoppel118** [comment]
Hi guys,

I see the same error in my logfile. I am using latest master: 

commit hash: 2adc067

https://github.com/tgalal/yowsup/commit/2adc067f306d9e7d8b634f66e96c52d80a42e1ff#diff-3fba23d9ae6f523490711ace804aa8c2

```
2019.11.04 23:19:29 3: WhatsApp: reConnect
2019.11.04 23:19:29 3: WhatsApp: sending /disconnect
2019.11.04 23:19:29 3: WhatsApp: Disconnected
2019.11.04 23:19:29 2: WhatsApp: setting $HOME to /opt/fhem
2019.11.04 23:19:29 2: WhatsApp: starting yoswup-cli: python3 /opt/yowsup-master/yowsup-cli demos --config-phone 49482230805 --yowsup
2019.11.04 23:19:29 3: WhatsApp: sending /L
2019.11.04 23:19:29 3: WhatsApp: sending /presence available
I 2019-11-04 23:19:29,555 yowsup.layers.network.layer - Connecting to e12.whatsapp.net:443
E 2019-11-05 00:17:58,783 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/opt/yowsup-master/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/opt/yowsup-master/yowsup/layers/network/layer.py", line 107, in onRecvData
    self.receive(data)
  File "/opt/yowsup-master/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/opt/yowsup-master/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/opt/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/opt/yowsup-master/yowsup/layers/auth/layer_authentication.py", line 67, in handleStreamError
    raise NotImplementedError("Unhandled stream:error node:\n%s" % node)
NotImplementedError: Unhandled stream:error node:
<stream:error code="503" />

2019.11.05 00:27:58 3: WhatsApp: reConnect
2019.11.05 00:27:58 3: WhatsApp: sending /disconnect
2019.11.05 00:27:58 3: WhatsApp: Disconnected
2019.11.05 00:27:58 2: WhatsApp: setting $HOME to /opt/fhem
2019.11.05 00:27:58 2: WhatsApp: starting yoswup-cli: python3 /opt/yowsup-master/yowsup-cli demos --config-phone 49482230805 --yowsup
2019.11.05 00:27:59 3: WhatsApp: sending /L
2019.11.05 00:27:59 3: WhatsApp: sending /presence available
I 2019-11-05 00:27:59,202 yowsup.layers.network.layer - Connecting to e4.whatsapp.net:443
2019.11.05 01:55:46 3: CUL_HM set DG_SZ_Thermostat_Clima desired-temp 17
E 2019-11-05 02:59:41,021 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/opt/yowsup-master/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/opt/yowsup-master/yowsup/layers/network/layer.py", line 107, in onRecvData
    self.receive(data)
  File "/opt/yowsup-master/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/opt/yowsup-master/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/opt/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/opt/yowsup-master/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/opt/yowsup-master/yowsup/layers/auth/layer_authentication.py", line 67, in handleStreamError
    raise NotImplementedError("Unhandled stream:error node:\n%s" % node)
NotImplementedError: Unhandled stream:error node:
<stream:error code="503" />

2019.11.05 03:09:41 3: WhatsApp: reConnect
2019.11.05 03:09:41 3: WhatsApp: sending /disconnect
2019.11.05 03:09:41 3: WhatsApp: Disconnected
2019.11.05 03:09:41 2: WhatsApp: setting $HOME to /opt/fhem
2019.11.05 03:09:41 2: WhatsApp: starting yoswup-cli: python3 /opt/yowsup-master/yowsup-cli demos --config-phone 49482230805 --yowsup
2019.11.05 03:09:41 3: WhatsApp: sending /L
2019.11.05 03:09:41 3: WhatsApp: sending /presence available
I 2019-11-05 03:09:41,378 yowsup.layers.network.layer - Connecting to e2.whatsapp.net:443
```

Do you need any further information?

Regards Hoppel
