### ISSUE TITLE
Send Image don't work

### ISSUE THREAD

**Issue by bitmurder** [tgalal/yowsup#2809]
**Describe the bug**
When i use the command
/image send 51YYYYYYYYY "/root/multimedia.png" "como estas"
give a error
File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/protocol_media/mediauploader.py", line 18, in __init__
    WARequest.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

**Debug output**
```
D 2019-06-11 22:52:37,126 yowsup.config.manager - load(path_or_profile_name=51XXXXXXXX, profile_only=False)
D 2019-06-11 22:52:37,126 yowsup.config.manager - _load_path(path=51XXXXXXXX)
D 2019-06-11 22:52:37,127 yowsup.config.manager - _load_path couldn't find the path: 51XXXXXXXX
D 2019-06-11 22:52:37,127 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2019-06-11 22:52:37,127 yowsup.config.manager - Detecting config for profile=51XXXXXXXX, dir=/root/.config/yowsup/51XXXXXXXX
D 2019-06-11 22:52:37,127 yowsup.config.manager - Trying /root/.config/yowsup/51XXXXXXXX/config.json
D 2019-06-11 22:52:37,127 yowsup.config.manager - _load_path(path=/root/.config/yowsup/51XXXXXXXX/config.json)
D 2019-06-11 22:52:37,127 yowsup.config.manager - Detected config type: json
D 2019-06-11 22:52:37,127 yowsup.config.manager - Opening config for reading
D 2019-06-11 22:52:37,127 yowsup.config.manager - Loading config
D 2019-06-11 22:52:37,127 yowsup.profile.profile - Constructed Profile(profile_name=51XXXXXXXX)
D 2019-06-11 22:52:37,127 yowsup-cli - starting cmd

yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.6.1
protobuf       v3.8.0rc1


D 2019-06-11 22:52:37,207 yowsup.stacks.yowstack - Initializing stack
D 2019-06-11 22:52:37,207 yowsup.stacks.yowstack - Constructed Network Layer
D 2019-06-11 22:52:37,208 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2019-06-11 22:52:37,211 yowsup.stacks.yowstack - Constructed Noise Layer
D 2019-06-11 22:52:37,211 yowsup.stacks.yowstack - Constructed Coder Layer
D 2019-06-11 22:52:37,211 yowsup.stacks.yowstack - Constructed Logger Layer
D 2019-06-11 22:52:37,211 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f92721ec690>
D 2019-06-11 22:52:37,211 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f92721d01d0>
D 2019-06-11 22:52:37,211 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2019-06-11 22:52:37,213 yowsup.stacks.yowstack - Constructed CLI Interface Layer
D 2019-06-11 22:52:37,213 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=51XXXXXXXX))
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
D 2019-06-11 22:52:40,095 yowsup.layers.network.layer - Created asyncore dispatcher
I 2019-06-11 22:52:40,095 yowsup.layers.network.layer - Connecting to e1.whatsapp.net:443
D 2019-06-11 22:52:40,095 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e1.whatsapp.net', 443))
D 2019-06-11 22:52:40,389 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2019-06-11 22:52:40,389 yowsup.layers.network.layer - Connected
D 2019-06-11 22:52:40,389 yowsup.axolotl.factory - get_manager(profile_name=51XXXXXXXX, username=51XXXXXXXX)
D 2019-06-11 22:52:40,391 yowsup.axolotl.manager - Initialized AxolotlManager [username=51XXXXXXXX, db=/root/.config/yowsup/51XXXXXXXX/axolotl.db]
D 2019-06-11 22:52:40,391 yowsup.axolotl.manager - level_prekeys(force=False)
D 2019-06-11 22:52:40,443 yowsup.axolotl.manager - len(pending_prekeys) = 805
D 2019-06-11 22:52:40,443 yowsup.axolotl.manager - load_unsent_prekeys
D 2019-06-11 22:52:40,444 yowsup.layers.noise.layer - Received auth event
D 2019-06-11 22:52:40,444 yowsup.env.env - Env not set, setting it to android
D 2019-06-11 22:52:40,444 yowsup.env.env - Current env changed to android 
D 2019-06-11 22:52:40,444 yowsup.layers.noise.layer - Performing handshake [username= 51XXXXXXXX, passive=False]
D 2019-06-11 22:52:40,444 yowsup.layers.noise.layer - Starting handshake worker
D 2019-06-11 22:52:41,306 yowsup.profile.profile - write_config for 51XXXXXXXX
D 2019-06-11 22:52:41,307 yowsup.common.tools - writeProfileData(profile_name=51XXXXXXXX, name=config.json, val=[omitted])
D 2019-06-11 22:52:41,307 yowsup.common.tools - Writing /root/.config/yowsup/51XXXXXXXX/config.json
D 2019-06-11 22:52:41,308 yowsup.layers.logger.layer - rx:
<success location="atn" creation="1556000338" t="1560311599" props="25" />
D 2019-06-11 22:52:41,308 yowsup.layers.protocol_iq.layer - starting ping thread.
Auth: Logged in!
D 2019-06-11 22:52:41,309 yowsup.layers.logger.layer - rx:
<ib from="s.whatsapp.net">
  <edge_routing>
    <routing_info>
      0x08050802
    </routing_info>
    <dns_domain>
      0x6662
    </dns_domain>
  </edge_routing>
</ib>
D 2019-06-11 22:52:41,309 yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now
D 2019-06-11 22:52:41,309 yowsup.layers.logger.layer - rx:
<ib from="s.whatsapp.net">
  <dirty timestamp="1560311599" type="groups" />
</ib>
D 2019-06-11 22:52:41,309 yowsup.layers.logger.layer - rx:
<ib from="s.whatsapp.net">
  <offline count="0" />
</ib>
[connected]:/image send 51YYYYYYYYY "/root/multimedia.png" "como estas"
D 2019-06-11 22:52:44,289 yowsup.layers.logger.layer - tx:
<iq to="s.whatsapp.net" xmlns="w:m" type="set" id="1">
  <encr_media type="image" hash="jVoHvfHL4tNbgJe2AW0slWc/jdFT1ARKee5GPq+kVNs=" size="381790" />
</iq>
[connected]:D 2019-06-11 22:52:45,035 yowsup.layers.logger.layer - rx:
<iq type="result" from="s.whatsapp.net" id="1">
  <encr_media url="https://mmg.whatsapp.net/u/f/y1XRpilKwaZSKpWXD_ZRkl0AdzIABYsYWtVMqw/AhLSoTvJx_7Ux_VADBkontfnFePFu2jr3Hf1W7zkedP3" />
</iq>
E 2019-06-11 22:52:45,036 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib64/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/layer.py", line 107, in onRecvData
    self.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 126, in receive
    if not self.processIqRegistry(node):
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 161, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/protocol_media/layer.py", line 78, in onRequestUploadSuccess
    self.toUpper(ResultRequestUploadIqProtocolEntity.fromProtocolTreeNode(resultNode))
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/interface/interface.py", line 77, in receive
    if not self.processIqRegistry(entity):
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/interface/interface.py", line 56, in processIqRegistry
    successClbk(entity, originalIq)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/demos/cli/layer.py", line 380, in <lambda>
    successFn = lambda successEntity, originalEntity: self.onRequestUploadResult(jid, mediaType, path, successEntity, originalEntity, caption)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/demos/cli/layer.py", line 553, in onRequestUploadResult
    successFn, self.onUploadError, self.onUploadProgress, asynchronous=False)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/protocol_media/mediauploader.py", line 18, in __init__
    WARequest.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

D 2019-06-11 22:52:45,036 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2019-06-11 22:52:45,036 yowsup.layers.network.layer - Disconnected
D 2019-06-11 22:52:45,056 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
D 2019-06-11 22:52:45,056 yowsup.layers.protocol_iq.layer - stopping ping thread
general: Disconnected: 
[connected]:
D 2019-06-11 22:52:45,313 yowsup.layers.protocol_iq.layer - YowPingThread-4 - ping thread stopped```

**Config file**

{
    "__version__": 1,
    "cc": "51",
    "client_static_keypair": "xxxx==",
    "edge_routing_info": "xxxxx==",
    "expid": "xxxxx==",
    "fdid": "xxxxxxxxx",
    "id": "xxxxxxxx=",
    "mcc": "716",
    "mnc": "06",
    "phone": "51XXXXXXXX",
    "pushname": "TestWS",
    "server_static_public": "XXXXXX=",
    "sim_mcc": "000",
    "sim_mnc": "000"
}

**Versions**

yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.6.1
protobuf       v3.8.0rc1

**To Reproduce**

**Expected behavior**

**OS (please complete the following information):**
Centos 7 
**Additional context**

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/issues?q=send+image+is%3Aopen
