### ISSUE TITLE
ValueError: Invalid padding bytes.

### ISSUE THREAD

**Issue by samwikiv** [tgalal/yowsup#2813]
yowsup-cli v3.2.0
Using yowsup v3.2.3

I got this error:

```
E 2019-06-16 13:08:32,430 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/user/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/home/user/yowsup/layers/network/layer.py", line 107, in onRecvData
    self.receive(data)
  File "/home/user/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/user/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/user/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/home/user/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/user/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/home/user/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/home/user/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/user/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/home/user/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/user/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/user/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/user/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/home/user/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/user/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/user/yowsup/layers/axolotl/layer_receive.py", line 32, in receive
    self.onMessage(protocolTreeNode)
  File "/home/user/yowsup/layers/axolotl/layer_receive.py", line 48, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/user/yowsup/layers/axolotl/layer_receive.py", line 60, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/home/user/yowsup/layers/axolotl/layer_receive.py", line 103, in handlePreKeyWhisperMessage
    enc.getVersion() == 2)
  File "/home/user/yowsup/axolotl/manager.py", line 169, in decrypt_pkmsg
    plaintext = self._get_session_cipher(senderid).decryptPkmsg(pkmsg)
  File "build/bdist.linux-x86_64/egg/axolotl/sessioncipher.py", line 86, in decryptPkmsg
    plaintext = self.decryptWithSessionRecord(sessionRecord, ciphertext.getWhisperMessage())
  File "build/bdist.linux-x86_64/egg/axolotl/sessioncipher.py", line 106, in decryptWithSessionRecord
    plaintext = self.decryptWithSessionState(sessionState, cipherText)
  File "build/bdist.linux-x86_64/egg/axolotl/sessioncipher.py", line 144, in decryptWithSessionState
    plaintext = self.getPlaintext(messageVersion, messageKeys, ciphertextMessage.getBody())
  File "build/bdist.linux-x86_64/egg/axolotl/sessioncipher.py", line 198, in getPlaintext
    return cipher.decrypt(cipherText)
  File "build/bdist.linux-x86_64/egg/axolotl/sessioncipher.py", line 226, in decrypt
    return unpadder.update(decrypted) + unpadder.finalize()
  File "/home/whats/.local/lib/python2.7/site-packages/cryptography/hazmat/primitives/padding.py", line 144, in finalize
    lib.Cryptography_check_pkcs7_padding)
  File "/home/whats/.local/lib/python2.7/site-packages/cryptography/hazmat/primitives/padding.py", line 89, in _byte_unpadding_check
    raise ValueError("Invalid padding bytes.")
ValueError: Invalid padding bytes.

```

**Comment by tgalal** [comment]
please follow the bug report template. closing for lack of information.
