### ISSUE TITLE
ValueError: Invalid padding bytes

### ISSUE THREAD

**Issue by tgalal** [tgalal/yowsup#2816]
**Describe the bug**

Ran cli demo, error occurred immediately after login

**Debug output**
```
 D 2019-06-16 17:12:00,668 yowsup.layers.logger.layer - rx:
<message from="xxxxxxxxxx-xxxxxxxxxx@g.us" type="text" id="1559289592-1" participant="xxxxxxxxxx@s.whatsapp.net" offline="0" t="1559289581" notify="yowsup">
  <enc type="skmsg" v="2">
    0x3308c8f2cd5c10011a601e57974acd61ce0b2f9b2b1f0904909c43fe80d56262482ab4d586b5ae3d5d5684dcb9983eebcb6238fc82d664b624d89cf6ede322efee3b104a9f7a1bf8349f331b0d120a74a0f0a6add2bbd9a1257f438f405177abeaaee8542f467387e19c0520c7c86d76345f4d7f600dccecb1d24a6fa762fdea89680986241729d08335860ade907bfca6bdbf74d3b6786552050b011b8129a4d07bc75c69a259868c08
  </enc>
</message>
D 2019-06-16 17:12:00,668 yowsup.axolotl.manager - group_decrypt(groupid=xxxxxxxxxx-xxxxxxxxxx@g.us, participantid=xxxxxxxxxx, data=[omitted])
D 2019-06-16 17:12:00,668 yowsup.axolotl.manager - get_group_cipher(groupid=xxxxxxxxxx-xxxxxxxxxx@g.us, username=xxxxxxxxxx)

[xxxxxxxxxx/xxxxxxxxxx-xxxxxxxxxx@g.us(31-05-2019 09:59)]:[1559289592-1]	 ok?
D 2019-06-16 17:12:00,688 yowsup.layers.logger.layer - tx:
<receipt id="1559289592-1" type="read" participant="xxxxxxxxxx@s.whatsapp.net" to="xxxxxxxxxx-xxxxxxxxxx@g.us" />
Message 1559289592-1: Sent delivered receipt and Read
[connected]:
D 2019-06-16 17:12:00,690 yowsup.layers.logger.layer - rx:
<message from="xxxxxxxxxx-xxxxxxxxxx@g.us" type="text" id="1559289614-2" participant="xxxxxxxxxx@s.whatsapp.net" offline="0" t="1559289604" notify="yowsup">
  <enc type="pkmsg" v="2">
    0x3308bab9f60712210515066e924db52d4f63424e7b2feb718150ec25637a814ccb3806b9e84d7870221a2105119988fe1a896784c6b04ef2d4e0cdb724d49cd766e10e517c59fe2228bfd00022c301330a210582f5ad5767f2138b9fc9570d8c8aa780a1c39884582e643de65d435f1faaf32b10001800229001859a301cc74d2b924ce350860a4ec1ea532a43bccbd17effb334204f696bc843e659e9b1dd8f8044263d88fc8a8a68263e50cc64be10d4ebda4a89adc702819ba8930a1bec9531575e40c277365bb8fe534b7ee0fd218e8bca7259e089865e4402816e2f55da3bdd468485b81f74c73dd784d0bd1473e74bd3ae3379ea1cf9551878eb859d507e12b236a054139651f6de11f2c9336177ec28fdf8a7fd033000
  </enc>
  <enc type="skmsg" v="2">
    0x33089da09ada0410001aa00136a38473daa0b34475e021fcbeaa0074d3142ff8f2987d407d7292cc837d965bb3f5b2fd5474e8c1c40415ade5c31bcd5a4b15ff5fa50f86d99b03b04f637fe191939b90616264b0ee5f100d749bcf587207cf32a9a8a94d1af82ec879ebebdfdca76cf3e507d30ef9f2d94e3c1123a1eb662515a6251738f74cd06e75d7af7cc4fb8b996a279a441b279424557cc966b8cd6e0ab54ac6755aa978d7ca3cfd6961343338bfe075fed868dbdb8c4945733e27008eca4751d4293b49b1b56504f2486610b5ffea419cd07bd529720ee7aec7622027c7736c3f8dfbb272d469998f
  </enc>
</message>
D 2019-06-16 17:12:00,690 yowsup.axolotl.manager - decrypt_pkmsg(senderid=xxxxxxxxxx, data=(omitted), unpad=True)
D 2019-06-16 17:12:00,690 yowsup.axolotl.manager - get_session_cipher(recipientid=xxxxxxxxxx)
W 2019-06-16 17:12:00,691 yowsup.layers.axolotl.layer_receive - Autotrusting identity for xxxxxxxxxx
D 2019-06-16 17:12:00,691 yowsup.axolotl.manager - trust_identity(recipientid=xxxxxxxxxx, identitykey=[omitted])
D 2019-06-16 17:12:00,726 yowsup.axolotl.manager - decrypt_pkmsg(senderid=xxxxxxxxxx, data=(omitted), unpad=True)
D 2019-06-16 17:12:00,726 yowsup.axolotl.manager - get_session_cipher(recipientid=xxxxxxxxxx)
E 2019-06-16 17:12:00,775 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/home/tarek/projects/yowsup/yowsup/layers/axolotl/layer_receive.py", line 60, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/home/tarek/projects/yowsup/yowsup/layers/axolotl/layer_receive.py", line 103, in handlePreKeyWhisperMessage
    enc.getVersion() == 2)
  File "/home/tarek/projects/yowsup/yowsup/axolotl/manager.py", line 169, in decrypt_pkmsg
    plaintext = self._get_session_cipher(senderid).decryptPkmsg(pkmsg)
  File "/home/tarek/projects/yowsup/venv/lib/python3.7/site-packages/axolotl/sessioncipher.py", line 85, in decryptPkmsg
    unsignedPreKeyId = self.sessionBuilder.process(sessionRecord, ciphertext)
  File "/home/tarek/projects/yowsup/venv/lib/python3.7/site-packages/axolotl/sessionbuilder.py", line 42, in process
    raise UntrustedIdentityException(self.recipientId, theirIdentityKey)
axolotl.untrustedidentityexception.UntrustedIdentityException: ('xxxxxxxxxx', <axolotl.identitykey.IdentityKey object at 0x7f2392b13978>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python3.7/asyncore.py", line 422, in handle_read_event
    self.handle_read()
  File "/home/tarek/projects/yowsup/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/home/tarek/projects/yowsup/yowsup/layers/network/layer.py", line 107, in onRecvData
    self.receive(data)
  File "/home/tarek/projects/yowsup/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/tarek/projects/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/tarek/projects/yowsup/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/home/tarek/projects/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/tarek/projects/yowsup/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/home/tarek/projects/yowsup/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/home/tarek/projects/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/tarek/projects/yowsup/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/home/tarek/projects/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/tarek/projects/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/tarek/projects/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/tarek/projects/yowsup/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/home/tarek/projects/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/tarek/projects/yowsup/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/tarek/projects/yowsup/yowsup/layers/axolotl/layer_receive.py", line 32, in receive
    self.onMessage(protocolTreeNode)
  File "/home/tarek/projects/yowsup/yowsup/layers/axolotl/layer_receive.py", line 48, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/tarek/projects/yowsup/yowsup/layers/axolotl/layer_receive.py", line 95, in handleEncMessage
    return self.handleEncMessage(node)
  File "/home/tarek/projects/yowsup/yowsup/layers/axolotl/layer_receive.py", line 60, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/home/tarek/projects/yowsup/yowsup/layers/axolotl/layer_receive.py", line 103, in handlePreKeyWhisperMessage
    enc.getVersion() == 2)
  File "/home/tarek/projects/yowsup/yowsup/axolotl/manager.py", line 169, in decrypt_pkmsg
    plaintext = self._get_session_cipher(senderid).decryptPkmsg(pkmsg)
  File "/home/tarek/projects/yowsup/venv/lib/python3.7/site-packages/axolotl/sessioncipher.py", line 86, in decryptPkmsg
    plaintext = self.decryptWithSessionRecord(sessionRecord, ciphertext.getWhisperMessage())
  File "/home/tarek/projects/yowsup/venv/lib/python3.7/site-packages/axolotl/sessioncipher.py", line 106, in decryptWithSessionRecord
    plaintext = self.decryptWithSessionState(sessionState, cipherText)
  File "/home/tarek/projects/yowsup/venv/lib/python3.7/site-packages/axolotl/sessioncipher.py", line 144, in decryptWithSessionState
    plaintext = self.getPlaintext(messageVersion, messageKeys, ciphertextMessage.getBody())
  File "/home/tarek/projects/yowsup/venv/lib/python3.7/site-packages/axolotl/sessioncipher.py", line 198, in getPlaintext
    return cipher.decrypt(cipherText)
  File "/home/tarek/projects/yowsup/venv/lib/python3.7/site-packages/axolotl/sessioncipher.py", line 224, in decrypt
    return unpadder.update(decrypted) + unpadder.finalize()
  File "/home/tarek/projects/yowsup/venv/lib/python3.7/site-packages/cryptography/hazmat/primitives/padding.py", line 144, in finalize
    lib.Cryptography_check_pkcs7_padding)
  File "/home/tarek/projects/yowsup/venv/lib/python3.7/site-packages/cryptography/hazmat/primitives/padding.py", line 89, in _byte_unpadding_check
    raise ValueError("Invalid padding bytes.")
ValueError: Invalid padding bytes.

D 2019-06-16 17:12:00,775 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2019-06-16 17:12:00,776 yowsup.layers.network.layer - Disconnected
D 2019-06-16 17:12:00,858 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
D 2019-06-16 17:12:00,859 yowsup.layers.protocol_iq.layer - stopping ping thread

```

**Versions**
```
yowsup-cli v3.2.0
using:
  yowsup v3.2.3
  consonance v0.1.3-1
  dissononce v0.34.3
  python-axolotl v0.2.1
  cryptography v2.5
  protobuf v3.7.1
```

Commit hash: 7f336c7c300ffe00e04be339f029ff23679fa1c1

**To Reproduce**

```
yowsup-cli demos --config configfile -yd
[offline]: /L
```

**OS (please complete the following information):**
Linux

**Additional context**
Several incoming messages were being processes

**Comment by zablah** [comment]
I Have same error on :
```
yowsup-cli v3.2.0
using:
  consonance v0.1.3-1
  protobuf v3.6.0
  cryptography v2.7
  yowsup v3.2.3
  dissononce v0.34.3
  python-axolotl v0.2.2

```

but when I remove `axolotl.db` the error is gone
