### ISSUE TITLE
Yowsup-cli demos: I can send message but "echo" demo is not working

### ISSUE THREAD

**Issue by bottasergio** [tgalal/yowsup#2817]
yowsup-cli  v3.2.0
yowsup      v3.2.3

I can send message using:

` yowsup-cli demos -c config.json -s 5nnnnnnnnnn "texto"`

But when I run 

`yowsup-cli demos -c config.json -e`

I get This error:

`
I 2019-06-17 08:08:03,317 yowsup.layers.network.layer - Connecting to e7.whatsapp.net:443
E 2019-06-17 08:08:04,113 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 100, in onRecvData
    self.receive(data)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 103, in receive
    self.toUpper(data)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/noise/layer.py", line 156, in receive
    self._flush_incoming_buffer()
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/noise/layer.py", line 144, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 31, in receive
    self.onMessage(protocolTreeNode)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 63, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 75, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 120, in handlePreKeyWhisperMessage
    self.toUpper(node)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/protocol_messages/layer.py", line 23, in recvMessageStanza
    self.toUpper(TextMessageProtocolEntity.fromProtocolTreeNode(node))
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/demos/echoclient/layer.py", line 11, in onMessage
    self.onMediaMessage(messageProtocolEntity)
  File "/home/sergio/.local/lib/python2.7/site-packages/yowsup/demos/echoclient/layer.py", line 28, in onMediaMessage
    if messageProtocolEntity.media_type == "image":
AttributeError: 'TextMessageProtocolEntity' object has no attribute 'media_type'
`

**Comment by NelsonGaldeman** [comment]
Add -d param so you get full debug log
