### ISSUE TITLE
ImportError: cannot import name x25519 while building v3.1.0

### ISSUE THREAD

**Issue by leemgs** [tgalal/yowsup#2822]
I have got the "**ImportError: cannot import name x25519**" issue while building v3.1.0 on Rasbian Stretch of Raspberry Pi3 board. Anyone that solved this issue? Welcome to any hints to me.
```
pi@raspberrypi:~/lgs$ sudo pip install yowsup2==3.2.3
pi@raspberrypi:~/lgs $ yowsup-cli
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 6, in <module>
    from yowsup.config.manager import ConfigManager
  File "/usr/local/lib/python2.7/dist-packages/yowsup/config/manager.py", line 4, in <module>
    from yowsup.config.v1.serialize import ConfigSerialize
  File "/usr/local/lib/python2.7/dist-packages/yowsup/config/v1/serialize.py", line 8, in <module>
    from consonance.structs.keypair import KeyPair
  File "/usr/local/lib/python2.7/dist-packages/consonance/structs/keypair.py", line 4, in <module>
    from dissononce.dh.x25519.x25519 import X25519DH
  File "build/bdist.linux-armv7l/egg/dissononce/dh/x25519/x25519.py", line 1, in <module>
ImportError: cannot import name x25519
```

**Comment by tgalal** [comment]
please follow the bug report template. closing for lack of information.

**Comment by leemgs** [comment]
Here is my recipe. Note that the yoswup v 3.1.0 requires Cryptography 2.6.1+.

```
# Remove the python-cryptography 1.7.1 version from the Raspbian OS.
$ sudo pip list | grep crypto
$ sudo apt purge python-cryptography
$ sudo apt purge python3-cryptography

# Create a Python-cryptographty 2.6.1 version and perform the installation.
$ git clone https://github.com/pyca/cryptography.git
$ git checkout -b 2.6.1 2.6.1
$ sudo pip installs the password.
```

Then, install the yowsup package.

```
$ sudo pip install yowsup2==3.2.3
$ pip freeze | grep cryptography

```
