### ISSUE TITLE
Error when receiving replied message

### ISSUE THREAD

**Issue by tonistiawan** [tgalal/yowsup#2825]
Hi,

I feel this yowsup tool is very useful.
I have successfully created a shell daemon to receive messages
and automatically saved to the MySQL database

But when the message is received, "reply", then the yowsup will
issued an error message as follows:

**Error message**
-=-=-=-=-=-=-=-=-=-=-
Echo to mysql client
-=-=-=-=-=-=-=-=-=-=-
org.openwhatsapp.yowsup.event.network.connect
I 2019-06-23 16:10:43,105 yowsup.layers.network.layer - Connecting to e11.whatsapp.net:443
org.openwhatsapp.yowsup.event.network.connected
Connected

E 2019-06-23 16:11:47,474 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/sources/yowsup/yowsup/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/sources/yowsup/yowsup/yowsup/layers/network/layer.py", line 107, in onRecvData
    self.receive(data)
  File "/sources/yowsup/yowsup/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/sources/yowsup/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/sources/yowsup/yowsup/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/sources/yowsup/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/sources/yowsup/yowsup/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/sources/yowsup/yowsup/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/sources/yowsup/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/sources/yowsup/yowsup/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/sources/yowsup/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/sources/yowsup/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/sources/yowsup/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/sources/yowsup/yowsup/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/sources/yowsup/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/sources/yowsup/yowsup/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/sources/yowsup/yowsup/yowsup/layers/axolotl/layer_receive.py", line 32, in receive
    self.onMessage(protocolTreeNode)
  File "/sources/yowsup/yowsup/yowsup/layers/axolotl/layer_receive.py", line 48, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/sources/yowsup/yowsup/yowsup/layers/axolotl/layer_receive.py", line 62, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/sources/yowsup/yowsup/yowsup/layers/axolotl/layer_receive.py", line 126, in handleWhisperMessage
    self.toUpper(node)
  File "/sources/yowsup/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/sources/yowsup/yowsup/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/sources/yowsup/yowsup/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/sources/yowsup/yowsup/yowsup/layers/protocol_messages/layer.py", line 43, in recvMessageStanza
    MessageMetaAttributes.from_message_protocoltreenode(node)
  File "/sources/yowsup/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/sources/yowsup/yowsup/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/sources/yowsup/yowsup/yowsup/demos/echo2mysql/layer.py", line 13, in onMessage
    self.onTextMessage(messageProtocolEntity)
  File "/sources/yowsup/yowsup/yowsup/demos/echo2mysql/layer.py", line 42, in onTextMessage
    nilai=(messageProtocolEntity.getBody(), messageProtocolEntity.getFrom(False), messageProtocolEntity.getId())
AttributeError: 'ExtendedTextMessageProtocolEntity' object has no attribute 'getBody'

selesai

And also have found difficulty to send image. I have search solution
but seems it is a bugs from yowsup. Hopefully can be fix soon.

**Versions**
yowsup-cli  v3.2.0
yowsup      v3.2.3

**OS :**
Linux Mint 19 Tara

**Comment by tgalal** [comment]
it's `messageProtocolEntity.text` for ExtendedTextMessageProtocolEntity

**Comment by ShitalBorganve** [comment]
Hello, did this issue fixed ? i am still getting same error, below is the code i am using and debug message output also pasted  
For the code of line  _message    = messageProtocolEntity.getBody().lower()_  
I some times get below error.

  self.__upper.receive(data)
  File "/home/pi/My_VEs/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/home/pi/myraspiwhatsappbot/layer.py", line 62, in onMessage
    self.onTextMessage(messageProtocolEntity) #Send the answer
  File "/home/pi/myraspiwhatsappbot/layer.py", line 88, in onTextMessage
    message    = messageProtocolEntity.text().lower()
AttributeError: 'TextMessageProtocolEntity' object has no attribute 'text'


I also tried using code line _message    = messageProtocolEntity.text().lower()_
And i got the below error

 self.__upper.receive(data)
  File "/home/pi/My_VEs/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/home/pi/myraspiwhatsappbot/layer.py", line 62, in onMessage
    self.onTextMessage(messageProtocolEntity) #Send the answer
  File "/home/pi/myraspiwhatsappbot/layer.py", line 88, in onTextMessage
    message    = messageProtocolEntity.text().lower()
AttributeError: 'TextMessageProtocolEntity' object has no attribute 'text'

Any points how i can use this line?
