### ISSUE TITLE
Refresh Sample Application Page

### ISSUE THREAD

**Issue by analistamarcioprado** [tgalal/yowsup#2826]
@alcal Congratulations on the initiative, is it possible for you to refresh the application sample page? @alcal Congratulations on the initiative, is it possible for you to refresh the application sample page? I saw on another issue that this page is outdated (https://github.com/tgalal/yowsup/wiki/Sample-Application).

I for example am using the following versions:
yowsup-cli v3.2.0
using:
   consonance v0.1.3-1
   protobuf v3.8.0
   cryptography v2.7
   yowsup v3.2.3
   dissononce v0.34.3
   python-axolotl v0.2.2

When I try to run run.py from the page (https://github.com/tgalal/yowsup/wiki/Sample-Application) the following error is returned:

root@whatsapp:~/robo# python run.py
Traceback (most recent call last):
File "run.py", line 31, in 
stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
AttributeError: type object 'YowCoderLayer' has no attribute 'PROP_DOMAIN'

Thanks in advance.

**Comment by NelsonGaldeman** [comment]
Check the issue #2800

**Comment by analistamarcioprado** [comment]
Thanks @NelsonGaldeman however the issue was not clear to me.

I use the example echoclient only change the parameter profile? Do I need run.py?

**Comment by acidbotmaker** [comment]
> root@whatsapp:~/robo# python run.py
> Traceback (most recent call last):
> File "run.py", line 31, in
> stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
> AttributeError: type object 'YowCoderLayer' has no attribute 'PROP_DOMAIN'
Hi @analistamarcioprado ,
I just had a similar issue, Yowstack as no method `setProfile`.
Turns out I installed yowsup2 from pip3 which was giving me a hell of a time.

Hope, this helps you out.
