### ISSUE TITLE
Asyncore handle_read_event [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by Sougotsu** [tgalal/yowsup#2835]
Hi, good job with this excelent whatsapp client.

I'm developing a software to connect different numbers, everything is working in differents threads for each number. I mean, I instance a stack for each number, and connect the self._stack.getLayerInterface(YowNetworkLayer).connect() in each thread. and everything is working good, sending and receving messages, all at the same time.

But!! Unexpectedly sometimes I got the next error:

`2019-07-04 02:27:34.879 yowsup.layers.network.dispatcher.dispatcher_asyncore ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/home/whatsapp-api/venv/lib/python3.6/site-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 47, in handle_read
    data = self.recv(1024)
  File "/usr/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
BlockingIOError: [Errno 11] Resource temporarily unavailable`

And with the thread I got that error, I lose the whatsapp connection for that number, preventing me from receiving and sending messages through that number.  But the others connected numbers still working with no issues.

Btw, the onStateDisconnected callback is never called on my layer, so I dont know how I lose the connection in order to reconnect again.

`@EventCallback(YowNetworkLayer.EVENT_STATE_DISCONNECTED)
    def onStateDisconnected(self, layerEvent):
        log.error("Disconnected: %s" % layerEvent.getArg("reason"))
        log.info("Trying to reconnect %s" % self.customer.phone)
        time.sleep(randint(5, 15))
        self.getStack().broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))`

Thanks in advance!

**Comment by alonefox** [comment]
Duplicate of #2829

**Comment by Sougotsu** [comment]
> Duplicate of #2829

I read that thread too, but its different because in my case everything is working normal, and sometimes, unexpectedly  I get that error, and not registering or doing those other stuff you were talking in that thread. here, the phone number are registered fine, connected fine, sending and receving message fine. 

The main process start a thread to create the stack, attach the layer and connect to whatsapp servers for each phone number I'm listening (3 of them right now). 

So when I get that error I was talking about, I get it for ONE of those 3, and not same in each time I get the error, and when I get it, that specific number of that thread doesnt can receive and send message any more until I restart it. The other threads keep working normally

**Comment by Ozdemir-B** [comment]
Have you find any solutions?
