### ISSUE TITLE
Error Registration AttributeError:Raw

### ISSUE THREAD

**Issue by tausday** [tgalal/yowsup#2836]
Hello,

i get this error when i start the registration:
I hope somebody can help me
Command  
python3 yowsup-cli registration  --config-phone 49XXXXXXXXX -R 123456 --config-cc 49

yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

W 2019-07-14 02:16:20,064 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
Traceback (most recent call last):
  File "yowsup-cli", line 722, in <module>
    if not parser.process():
  File "yowsup-cli", line 389, in process
    self.handleRegister(self.args["register"], config)
  File "yowsup-cli", line 418, in handleRegister
    req = WARegRequest(config, code)
  File "/opt/yowsup-master/yowsup/registration/regrequest.py", line 35, in __init__
    super(WARegRequest,self).__init__(config)
  File "/opt/yowsup-master/yowsup/common/http/warequest.py", line 79, in __init__
    config.client_static_keypair = WATools.generateKeyPair()
  File "/opt/yowsup-master/yowsup/common/tools.py", line 70, in generateKeyPair
    return KeyPair.generate()
  File "/usr/local/lib/python3.6/dist-packages/consonance-0.1.3.post1-py3.6.egg/consonance/structs/keypair.py", line 36, in generate
    keypair = X25519DH().generate_keypair()
  File "/usr/local/lib/python3.6/dist-packages/dissononce-0.34.3-py3.6.egg/dissononce/dh/x25519/x25519.py", line 37, in generate_keypair
    encoding=serialization.Encoding.Raw,
  File "/usr/lib/python3.6/enum.py", line 326, in __getattr__
    raise AttributeError(name) from None
AttributeError: Raw

**Comment by tgalal** [comment]
please follow the bug report template. closing for lack of information.
