### ISSUE TITLE
How to solve group message issue

### ISSUE THREAD

**Issue by ciclanoio** [tgalal/yowsup#2838]
**Describe the bug**
Receive message from group:

I 2019-07-17 15:45:39,460 yowsup.layers.network.layer - Connecting to e11.whatsapp.net:443
E 2019-07-17 15:45:39,996 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/layer.py", line 102, in onRecvData
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/layer.py", line 105, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer.py", line 172, in receive
    self._flush_incoming_buffer()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer.py", line 160, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 32, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 48, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 64, in handleEncMessage
    self.handleSenderKeyMessage(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 136, in handleSenderKeyMessage
    data=enc.getData()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/axolotl/manager.py", line 217, in group_decrypt
    plaintext = group_cipher.decrypt(data)
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.2.2-py2.7.egg/axolotl/groups/groupcipher.py", line 63, in decrypt
    raise InvalidMessageException(e)
**InvalidMessageException: No keys for: 47046226**

I try remove group, send ack from message but locked here in this step.

Send message is ok.

**Comment by tgalal** [comment]
please follow the bug report template. closing for lack of information.
