### ISSUE TITLE
Seems like a permissions issue

### ISSUE THREAD

**Issue by jacobghattas** [tgalal/yowsup#2839]
I am runnig Nagios and trying to get Yowsup workng with it.
When I run the command as root:
/usr/local/nagios/libexec/yowsup-cli demos -c /usr/local/nagios/libexec/yowsup-cli.config -s XXXXXXXXXX "PROBLEM"

I get the message with no problems...

But when I run it as the nagios user I get an error:
I 2019-07-18 21:42:33,939 yowsup.layers.network.layer - Connecting to e6.whatsapp.net:443
E 2019-07-18 21:42:34,865 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib64/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/layer.py", line 107, in onRecvData
    self.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/axolotl/layer_receive.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/auth/layer_authentication.py", line 55, in handleSuccess
    self.toUpper(nodeEntity)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/demos/sendclient/layer.py", line 31, in onSuccess
    self.toLower(messageEntity)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 136, in send
    send(entity)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/protocol_messages/layer.py", line 24, in sendMessageEntity
    self.entityToLower(entity)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 140, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/axolotl/layer_send.py", line 39, in send
    self.processPlaintextNodeAndSend(node)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/axolotl/layer_send.py", line 107, in processPlaintextNodeAndSend
    self.sendToContact(node)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/axolotl/layer_send.py", line 152, in sendToContact
    messageData
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/axolotl/manager.py", line 163, in encrypt
    return cipher.encrypt(message + self._generate_random_padding())
  File "build/bdist.linux-x86_64/egg/axolotl/sessioncipher.py", line 59, in encrypt
    self.sessionStore.storeSession(self.recipientId, self.deviceId, sessionRecord)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/axolotl/store/sqlite/liteaxolotlstore.py", line 58, in storeSession
    self.sessionStore.storeSession(recepientId, deviceId, sessionRecord)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/axolotl/store/sqlite/litesessionstore.py", line 35, in storeSession
    self.deleteSession(recipientId, deviceId)
  File "/usr/lib/python2.7/site-packages/yowsup-3.2.3-py2.7.egg/yowsup/axolotl/store/sqlite/litesessionstore.py", line 53, in deleteSession
    self.dbConn.cursor().execute(q, (recipientId, deviceId))
OperationalError: unable to open database file

Your help is appreciated...
10xs
Jacob

**Comment by jacobghattas** [comment]
FIXED :)
