### ISSUE TITLE
Registration FAIL

### ISSUE THREAD

**Issue by carjr** [tgalal/yowsup#2841]
When creating another server, I have difficulty registering number,
I am using the following versions:
yowsupcli v3.2.0
yowsup v3.2.3

I've tried registration through these ways:
*********************************************************************
yowsup-cli registration --requestcode sms --phone 5517981249463 --cc 55

with the above method I get this error:

E 2019-07-27 09:48:17,100 yowsup.config.manager - Could not find a config for username=5517981249463, paths checked: /root/.config/yowsup/5517981249463/config.json:/root/.config/yowsup/5517981249463/config.yo
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 679, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 350, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/bin/yowsup-cli", line 362, in handleRequestCode
    result = codeReq.send(encrypt=self._encrypt, preview=self._preview)
  File "/usr/lib/python2.7/site-packages/yowsup/registration/coderequest.py", line 46, in send
    res = super(WACodeRequest, self).send(parser, encrypt=encrypt, preview=preview)
  File "/usr/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 133, in send
    return self.sendGetRequest(parser, encrypt, preview=preview)
  File "/usr/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 205, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET", preview=preview)
  File "/usr/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 294, in sendRequest
    conn.request(reqType, path, params, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1041, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1075, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 881, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 843, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1260, in connect
    server_hostname=sni_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 348, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 609, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 831, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] unknown error (_ssl.c:618)

*********************************************************************
*********************************************************************

yowsup-cli registration --requestcode sms --config zap.config

zap.config:
cc = 55
phone = 5517981249463

with the above method I get this error:

E 2019-07-27 09:51:00,953 yowsup.config.manager - Could not find a config for username=5517981249463, paths checked: /root/.config/yowsup/5517981249463/config.json:/root/.config/yowsup/5517981249463/config.yo
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 679, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 350, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/bin/yowsup-cli", line 362, in handleRequestCode
    result = codeReq.send(encrypt=self._encrypt, preview=self._preview)
  File "/usr/lib/python2.7/site-packages/yowsup/registration/coderequest.py", line 46, in send
    res = super(WACodeRequest, self).send(parser, encrypt=encrypt, preview=preview)
  File "/usr/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 133, in send
    return self.sendGetRequest(parser, encrypt, preview=preview)
  File "/usr/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 205, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET", preview=preview)
  File "/usr/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 294, in sendRequest
    conn.request(reqType, path, params, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1041, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1075, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 881, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 843, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1260, in connect
    server_hostname=sni_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 348, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 609, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 831, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] unknown error (_ssl.c:618)

*********************************************************************
*********************************************************************

yowsup-cli registration --requestcode sms --config-phone 5517981249463 --config-cc 55 --debug

when running debug I get the following error:

D 2019-07-27 09:53:02,675 yowsup.config.manager - Detecting config for username=5517981249463, dir=/root/.config/yowsup/5517981249463/
D 2019-07-27 09:53:02,675 yowsup.config.manager - Trying /root/.config/yowsup/5517981249463/config.json
D 2019-07-27 09:53:02,675 yowsup.config.manager - Trying /root/.config/yowsup/5517981249463/config.yo
E 2019-07-27 09:53:02,675 yowsup.config.manager - Could not find a config for username=5517981249463, paths checked: /root/.config/yowsup/5517981249463/config.json:/root/.config/yowsup/5517981249463/config.yo
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

D 2019-07-27 09:53:02,752 yowsup.axolotl.factory - get_manager(username=5517981249463)
D 2019-07-27 09:53:02,753 yowsup.axolotl.manager - Initialized AxolotlManager [username=5517981249463, db=/root/.config/yowsup/5517981249463/axolotl.db]
D 2019-07-27 09:53:02,754 yowsup.axolotl.manager - load_latest_signed_prekey
D 2019-07-27 09:53:02,755 yowsup.env.env - Env not set, setting it to android
D 2019-07-27 09:53:02,755 yowsup.env.env - Current env changed to android
D 2019-07-27 09:53:02,755 yowsup.common.http.warequest - send(parser=None, encrypt=True, preview=False)
D 2019-07-27 09:53:02,755 yowsup.common.http.warequest - sendGetRequest(parser=None, encrypt_params=True, preview=False)
D 2019-07-27 09:53:02,755 yowsup.common.http.warequest - Encrypting parameters
D 2019-07-27 09:53:02,756 yowsup.common.http.warequest - pre-encrypt (encoded) parameters =
cc=55&in=17981249463&lg=en&lc=GB&mistyped=6&authkey=dSi0b2HuJenoYiatqGUl%2dItiyaoxHTc%5fyPLJZM9BWwc&e_regid=N0gnfw&e_keytype=BQ&e_ident=ziqvtkOY2QLmGuT2yf5UDC7sLDHl2yWmF73Sp3Fv4Tk&e_skey_id=AAAA&e_skey_val=%5fMal3xoJjJdj9ZCAoeewTIXo5xp9MxkKhQWQH42t9W0&e_skey_sig=WwbBdM6N9V8%2dlOtyfhk%5fxskS7Ilff8W8Mq9S6PUw5XAUlNa1fVOiivR4pTbwy509guRbAOwXoV44qkXBesJeiQ&fdid=0caddbca%2d7d59%2d4c21%2d8723%2d89f6ccce35e2&expid=cWRjp2txQyCtoKvvFJN1fA&network_radio_type=1&simnum=1&hasinrc=1&pid=3133&rc=0&mcc=000&mnc=000&sim_mcc=000&sim_mnc=000&method=sms&reason=&token=u7%2bm6jJr5T5yCsPtCEom2e9ROAk%3d&hasav=1&id=B%88%ee%1fR%7e%f8%c7%1e%06%d8GV%cah%f6e%bbIT
D 2019-07-27 09:53:02,757 yowsup.common.http.warequest - sendRequest(host=v.whatsapp.net, port=443, path=/v2/code, headers={'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.19.51 Android/8.0.0 Device/samsung-star2lte'}, params=[('ENC', '1D6Gg9qC6qHSaCGLPCiA6AJ3/6R6dAo/83TeTAhAEmsE62xvSIoDU/ZmCTSm8dDHciwtjOlcjNQ2v8VVIdFngYByPz0bfyxzi308lfeWWoVJ/P+IJjSArMExeF+STfRlEzkmSSgj4ULa9Ed/AXhRUYxOrJWuf6jSQHSZjTOQ/sYSg68P3fyteC893+NMRi3yXwBBIF4Qojdm0mCaohCKYht8ZiYgJXSi6QGh9AhU3zae+/GHXd3Htu64HP951wvNtUuGuWyJ3sngssyasGBsUcdSy9HTS+uufkwPqiCenvS7bcMyKpX4ny5FeWRCYKXXnElHLATuCqh2WMuhR2zOEU4S+8sjv2ulFU7BeIAU0R5vWfYx3WhO/GwqAiW3xt9PjFKYQMzt8IekqQtF7Q4HAJBEJkfsA840NOBCp6St0BqOlgs+EnLGf0oVFl+5laG8ze0Z+ZNBqoLNJOhQvSu+onRcqFQ78PcgOVjv4uDDjoVe0iJN/GuW10rjIwB+/3U9aha36xm05gsKBOrLjLxUwuD1rPx8tAo/D5BEw+uge6wso18Q/IGJ0q/oIojBrYPF+/bHsyM8kLAs6lm5Qxc0y6Bvcpge4KWk2F+AIAcTEFVTWt+feyBHv920YzIQMfv6pCjTbwbqJg2ebduE+g+Aa42RF1KetKbcpslJwruqmJMiliQPjjo38wZaBTBU+Wkf3Hxv7uYb3IgZVn+rCuv4VsGLA9wxZZfsI3CRC+4k4IfLHcG6OgPAYEFnTGR5jCqvIb+eDM/gs7SIREO3w1s2tz6YTKuLUgtSqheelwptwuSDEjH+uKpVdMRmA+DjTmkuvzHZi8jyoMmq7jjR+UfnPy2++8HpGUFIjMTeDrdPymR93l8IeFkNisQ0ISncJvyd/aHx3akgMNVSOkvl9j5Xdg==')], reqType=GET, preview=False)
D 2019-07-27 09:53:02,758 yowsup.common.http.warequest - Opening connection to v.whatsapp.net
D 2019-07-27 09:53:02,764 yowsup.common.http.warequest - Sending GET request to /v2/code?ENC=1D6Gg9qC6qHSaCGLPCiA6AJ3%2f6R6dAo%2f83TeTAhAEmsE62xvSIoDU%2fZmCTSm8dDHciwtjOlcjNQ2v8VVIdFngYByPz0bfyxzi308lfeWWoVJ%2fP%2bIJjSArMExeF%2bSTfRlEzkmSSgj4ULa9Ed%2fAXhRUYxOrJWuf6jSQHSZjTOQ%2fsYSg68P3fyteC893%2bNMRi3yXwBBIF4Qojdm0mCaohCKYht8ZiYgJXSi6QGh9AhU3zae%2b%2fGHXd3Htu64HP951wvNtUuGuWyJ3sngssyasGBsUcdSy9HTS%2buufkwPqiCenvS7bcMyKpX4ny5FeWRCYKXXnElHLATuCqh2WMuhR2zOEU4S%2b8sjv2ulFU7BeIAU0R5vWfYx3WhO%2fGwqAiW3xt9PjFKYQMzt8IekqQtF7Q4HAJBEJkfsA840NOBCp6St0BqOlgs%2bEnLGf0oVFl%2b5laG8ze0Z%2bZNBqoLNJOhQvSu%2bonRcqFQ78PcgOVjv4uDDjoVe0iJN%2fGuW10rjIwB%2b%2f3U9aha36xm05gsKBOrLjLxUwuD1rPx8tAo%2fD5BEw%2buge6wso18Q%2fIGJ0q%2foIojBrYPF%2b%2fbHsyM8kLAs6lm5Qxc0y6Bvcpge4KWk2F%2bAIAcTEFVTWt%2bfeyBHv920YzIQMfv6pCjTbwbqJg2ebduE%2bg%2bAa42RF1KetKbcpslJwruqmJMiliQPjjo38wZaBTBU%2bWkf3Hxv7uYb3IgZVn%2brCuv4VsGLA9wxZZfsI3CRC%2b4k4IfLHcG6OgPAYEFnTGR5jCqvIb%2beDM%2fgs7SIREO3w1s2tz6YTKuLUgtSqheelwptwuSDEjH%2buKpVdMRmA%2bDjTmkuvzHZi8jyoMmq7jjR%2bUfnPy2%2b%2b8HpGUFIjMTeDrdPymR93l8IeFkNisQ0ISncJvyd%2faHx3akgMNVSOkvl9j5Xdg%3d%3d
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 679, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 350, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/bin/yowsup-cli", line 362, in handleRequestCode
    result = codeReq.send(encrypt=self._encrypt, preview=self._preview)
  File "/usr/lib/python2.7/site-packages/yowsup/registration/coderequest.py", line 46, in send
    res = super(WACodeRequest, self).send(parser, encrypt=encrypt, preview=preview)
  File "/usr/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 133, in send
    return self.sendGetRequest(parser, encrypt, preview=preview)
  File "/usr/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 205, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET", preview=preview)
  File "/usr/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 294, in sendRequest
    conn.request(reqType, path, params, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1041, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1075, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 881, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 843, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1260, in connect
    server_hostname=sni_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 348, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 609, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 831, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] unknown error (_ssl.c:618)

and on my other previous machine (VM) I ran the registry without problem, but it was blocked, and then I started doing another and now this error does not come out

**Comment by bryanjhv** [comment]
Looks like there's no `ca-certificates` in your server.
Apart from that, the README clealy states that you should NOT try to register a number via Yowsup because it will be instantly banned from WhatsApp, I guess a fix is on its way.

**Comment by carjr** [comment]
Strange, because my other yowsup had done less than 7 days ago and was working, I tried to do another and it happened, I'll wait then.

**Comment by carjr** [comment]
I did the following test, registered a number on the normal phone, it worked, used a few days, and then tried to register on yowsup, he gives the error, but does not block the number, just does not register.

**Comment by carjr** [comment]
I was able to register a number and use yowsup normally!

**Comment by bryanjhv** [comment]
Would be a more helpful comment if you tell others how did you register it (using Yowsup or a smartphone?).
Also, if you solved your *issue*, then it'd be of help if you close this. That way the maintainer will have less work reviewing issues for something he's not being paid.

**Comment by carjr** [comment]
Did you read my previous comments?

But I will add a few things, I registered the number for the first time on a smartphone I stayed a few days with it, tried to register on yowsup was not, I formatted my VM, and changed the ip of my internet, and tried to register directly on yowsup and succeeded , but it is very unstable, I can not be "online", but I can send message, check numbers.

forgive for the mistakes, use translator.

**Comment by carjr** [comment]
I also don't know if it worked by luck, or something I did that I didn't do the other times, I will reformat the VM and try to redo the process to a new number and describe the steps I took.

**Comment by ShiSHcat** [comment]
What do you mean for VM? Yowsup is on it?

**Comment by carjr** [comment]
VM = VMware, yes!
