### ISSUE TITLE
'contact_array' Not supported

### ISSUE THREAD

**Issue by paco020295** [tgalal/yowsup#2851]
**Describe the bug**

When sendingmany contacts to the bot i receive  error "Not supported". I made some modifications to be able to, at least, print what im receiving. I can see the information of the contacts together with gibberish text. I think this is called a byte_array.

**Debug output**

```
D 2019-08-13 09:27:35,944 yowsup.layers.logger.layer - rx:
<message from="xxxxxxxxxx@s.whatsapp.net" type="media" id="90EF225B12ACC2F4DA2AB2A5BAD47551" t="1565699255" notify="xxxxxxxxxx">
  <enc v="2" type="msg" mediatype="contact_array">
    0x330a21050e2b1dc030fce89e3c84ce25e404f546949d64f9bdd00e84badf311340134b111003180022d002db2c4f5eeeb50b465e8cba265b9aa20d04ba7775b4c36aa8648043c48c0acc1c38e9bf46eae3a2922a232e2c8767ea1a4c3608d6bbf7dd4b78595d5d01413e0df2bf0763c238758f8a9dcf1f127b13bf7eafffd44952c05d28a1ae21422f4358ab22940a45b22a8a00218988ac7d2370ac4f6084792f7b55c062c5d03cdacbca00c1e72d219b4bceecd823170e1530a8131c8a8dc9d362737c43e0ebd224483312597fe0c2cef5478509239e3631f455948d9fe209ea17927e7cc0e54e7ca6b3a79e97c3da81c458a2125e25617934e4c14d378285d4c199916cd5b7c6092e578086c6c1d059741c9154c886d3f7dfd37372a8c61ad4e22106f3d610340e826669fc5d5069dfe6d50cf297005aff622d2b107859f60ac8b71f9df6575f13e3bcbdb8e9cd67ca4cf48519d66719d088ee99f34430ef15f8462c7181bcaf42fd1babdafcc9f304065e5df31d27b700e9c520c4a099e7a17bf3
  </enc>
</message>
D 2019-08-13 09:27:35,946 yowsup.axolotl.manager - decrypt_msg(senderid=xxxxxxxxxx, data=[omitted], unpad=True)
D 2019-08-13 09:27:35,947 yowsup.axolotl.manager - get_session_cipher(recipientid=xxxxxxxxxxx)
b'j\xc0\x02\n\n2 contacts\x12\x92\x01\n\tAa martin\x82\x01\x83\x01BEGIN:VCARD\nVERSION:3.0\nN:martin;Aa;;;\nFN:Aa martin\nitem1.TEL;waid=xxxxxxxxxxxx:xxxxxxxxxxxxxxnitem1.X-ABLabel:Other\nEND:VCARD\x12\x9c\x01\n\x0cAgus (Cande)\x82\x01\x8a\x01BEGIN:VCARD\nVERSION:3.0\nN:(Cande);Agus;;;\nFN:Agus (Cande)\nitem1.TEL;waid=xxxxxxxxxxxx:+xxxxxxxxxxxxxxxxxx\nitem1.X-ABLabel:Mobile\nEND:VCARD\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c'
D 2019-08-13 09:27:36,137 yowsup.layers.logger.layer - tx:
<receipt id="90EF225B12ACC2F4DA2AB2A5BAD47551" to="xxxxxxxxxxxxxxx@s.whatsapp.net" />
D 2019-08-13 09:27:36,142 yowsup.layers.logger.layer - tx:
<receipt id="90EF225B12ACC2F4DA2AB2A5BAD47551" type="read" to="xxxxxxxxxxxxxx@s.whatsapp.net" />
I 2019-08-13 09:27:36,150 yowsup.demos.common.sink_worker - Processing contact_array
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/Proyectos/yowsapp-framework/libs/yowsup/yowsup/demos/common/sink_worker.py", line 131, in run
    filename = media_message_protocolentity.display_name
  File "/home/pi/Proyectos/yowsapp-framework/libs/yowsup/yowsup/layers/protocol_media/protocolentities/message_media_contact.py", line 20, in display_name
    return self.media_specific_attributes.display_name
AttributeError: 'NoneType' object has no attribute 'display_name'

```

**Versions**
yowsup-cli v3.2.0
  yowsup v3.2.3
  consonance v0.1.3
  dissononce v0.34.3
  python-axolotl v0.2.3
  cryptography v2.7
  protobuf v3.9.0

**To Reproduce**

Just send many contacts together while running mediasink demo, for example. 

**Expected behavior**
Message "Type not supported"

**OS (please complete the following information):**
Raspbian

**Comment by bryanjhv** [comment]
I guess you at least know how to use `@ProtocolEntityCallback`, that way you shouldn't be modifying library code.
The "gibberish" text you see are the protocol responses, and they are byte literals.
Then, what code are you using that reproduces the problem you're facing? That way someone could help.

**Comment by paco020295** [comment]
> I guess you at least know how to use `@ProtocolEntityCallback`, that way you shouldn't be modifying library code.
> The "gibberish" text you see are the protocol responses, and they are byte literals.
> Then, what code are you using that reproduces the problem you're facing? That way someone could help.

Thank you very much for your reply. I will learn more about ProtocolEntityCallback
Mediasink demo can be used to reproduce the error. Just need to send many contacts all at once. Attach>Contacts>"Select more than one contact">Send
Send it to bot and you will receive this message. "Not supported"

**Comment by paco020295** [comment]
What arguments do i have to pass to be able to use "decrypt_msg" from Axolotl/manager.py? I need to get the information from plaintext to  my layer.py. This would help me a lot

**Comment by bryanjhv** [comment]
Usually you don't want to mess things up with axolotl, because that's the layer which handles cryptography. Also, you know that's not the problem by looking at the kind-of-plaintext you got in your first post:

```python
b'j\xc0\x02\n\n2 contacts\x12\x92\x01\n\tAa martin\x82\x01\x83\x01BEGIN:VCARD\nVERSION:3.0\nN:martin;Aa;;;\nFN:Aa martin\nitem1.TEL;waid=xxxxxxxxxxxx:xxxxxxxxxxxxxxnitem1.X-ABLabel:Other\nEND:VCARD\x12\x9c\x01\n\x0cAgus (Cande)\x82\x01\x8a\x01BEGIN:VCARD\nVERSION:3.0\nN:(Cande);Agus;;;\nFN:Agus (Cande)\nitem1.TEL;waid=xxxxxxxxxxxx:+xxxxxxxxxxxxxxxxxx\nitem1.X-ABLabel:Mobile\nEND:VCARD\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c\x0c'
```

Also, if you look at mediasink demo, it does `sys.exit(1)` on unsupported media type.

**Comment by paco020295** [comment]
For this comment, ignore what i wrote before.

How can i get the plaintext of any message in a layer in yowsup?
Imagine im running echoclient, how can i add plaintext in layer.py?

I tried adding this lines to layer.py of echoclient:
        encMessageProtocolEntity = EncryptedMessageProtocolEntity
        enc = encMessageProtocolEntity.getEnc(EncProtocolEntity.TYPE_MSG)
        plaintext = self.manager.decrypt_msg(encMessageProtocolEntity.getAuthor(False), enc.getData(),
                                             enc.getVersion() == 2)

But i don't think i can use them like that. How can i use it in my layer?

**Comment by bryanjhv** [comment]
I guess there are some good Python courses on the web.
