### ISSUE TITLE
assert type(local_static) is KeyPair AssertionError

### ISSUE THREAD

**Issue by apepenkov** [tgalal/yowsup#2852]
**Describe the bug**
I get an 
 assert type(local_static) is KeyPair
AssertionError

**Debug output**

```
E 2019-08-19 21:14:32,802 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "C:\Users\apepenkov\AppData\Local\Programs\Python\Python37-32\lib\asyncore.py", line 91, in write
    obj.handle_write_event()
  File "C:\Users\apepenkov\AppData\Local\Programs\Python\Python37-32\lib\asyncore.py", line 440, in handle_write_event
    self.handle_connect_event()
  File "C:\Users\apepenkov\AppData\Local\Programs\Python\Python37-32\lib\asyncore.py", line 428, in handle_connect_event
    self.handle_connect()
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\network\dispatcher\dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\network\layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 3 more times]
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\auth\layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "C:\projects\fiverr\egores\venv\lib\site-packages\yowsup\layers\noise\layer.py", line 63, in on_auth
    assert type(local_static) is KeyPair
AssertionError
```

**Versions**

yowsup-cli  v3.2.0
yowsup      v3.2.3

**OS (please complete the following information):**
Win 10 x64

run.py:
```
from yowsup.stacks import YowStackBuilder
from layer import EchoLayer
# from yowsup.layers.auth import AuthError
from yowsup.layers import YowLayerEvent
from yowsup.layers.network import YowNetworkLayer
from yowsup.env import YowsupEnv

credentials = ("7********",
               "mAPxNZjOkzhGFXAKxJz8***********************mgJPlLcVXGBwlj8TwRB1Tw==")  # replace with your phone and password

if __name__ == "__main__":
    stackBuilder = YowStackBuilder()

    stack = stackBuilder \
        .pushDefaultLayers() \
        .push(EchoLayer) \
        .build()

    stack.setCredentials(credentials)
    stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))  # sending the connect signal
    stack.loop()  # this is the program mainloop
```

**Comment by apepenkov** [comment]
keypair = KeyPair.from_bytes solved my problem


```
from yowsup.stacks import YowStackBuilder
from layer import EchoLayer
# from yowsup.layers.auth import AuthError
from yowsup.layers import YowLayerEvent
from yowsup.layers.network import YowNetworkLayer
from yowsup.env import YowsupEnv
from consonance.structs.keypair import KeyPair
import base64
keypair = KeyPair.from_bytes(
     base64.b64decode("mAPxNZjOkzhGFXAKxJz8tKrQ1y8kRE7vxasDuAqfgUg7GPALwDMrGqymLfLtrmt9mgJPlLcVXGBwlj8TwRB1Tw==")
)

credentials = ("7********",
               keypair)  # replace with your phone and password

if __name__ == "__main__":
    stackBuilder = YowStackBuilder()

    stack = stackBuilder \
        .pushDefaultLayers() \
        .push(EchoLayer) \
        .build()

    stack.setCredentials(credentials)
    stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))  # sending the connect signal
    stack.loop()  # this is the program mainloop
```
