### ISSUE TITLE
why the connection breaks (error code="503")

### ISSUE THREAD

**Issue by turkeyhakan** [tgalal/yowsup#2855]
**Excuse me. My English is not very good**

**I'm only doing online and offline tracking, but the connection is broken for no reason. I wonder what the problem might be?**
```
D 2019-08-22 03:52:08,950 yowsup.layers.protocol_iq.layer - ping queue size: 1
D 2019-08-22 03:52:09,216 yowsup.layers.logger.layer - tx:
<iq id="44" type="get" xmlns="w:p" />
D 2019-08-22 03:52:09,903 yowsup.layers.logger.layer - rx:
<iq from="90xxxxxx752@s.whatsapp.net" type="result" id="44" t="1566435129" />
Iq:
ID: 44
Type: result
from: 90xxxxxx752@s.whatsapp.net

D 2019-08-22 03:53:02,528 yowsup.layers.protocol_iq.layer - ping queue size: 1
D 2019-08-22 03:53:02,825 yowsup.layers.logger.layer - tx:
<iq id="45" type="get" xmlns="w:p" />
D 2019-08-22 03:53:03,247 yowsup.layers.logger.layer - rx:
<iq from="90xxxxxx752@s.whatsapp.net" type="result" id="45" t="1566435183" />
Iq:
ID: 45
Type: result
from: 90xxxxxx752@s.whatsapp.net

2019-08-22 03:53:30,028 yowsup.layers.logger.layer - rx:
<stream:error code="503" />
E 2019-08-22 03:53:30,606 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\asyncore.py", line 422, in handle_read_event
    self.handle_read()
  File "E:\Hakan\yowsup\layers\network\dispatcher\dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "E:\Hakan\yowsup\layers\network\layer.py", line 107, in onRecvData
    self.receive(data)
  File "E:\Hakan\yowsup\layers\network\layer.py", line 110, in receive
    self.toUpper(data)
  File "E:\Hakan\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "E:\Hakan\yowsup\layers\noise\layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "E:\Hakan\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "E:\Hakan\yowsup\layers\noise\layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "E:\Hakan\yowsup\layers\noise\layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "E:\Hakan\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "E:\Hakan\yowsup\layers\coder\layer.py", line 21, in receive
    self.toUpper(node)
  File "E:\Hakan\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "E:\Hakan\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "E:\Hakan\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "E:\Hakan\yowsup\layers\axolotl\layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "E:\Hakan\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "E:\Hakan\yowsup\layers\__init__.py", line 194, in receive
    s.receive(data)
  File "E:\Hakan\yowsup\layers\axolotl\layer_receive.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "E:\Hakan\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "E:\Hakan\yowsup\layers\__init__.py", line 194, in receive
    s.receive(data)
  File "E:\Hakan\yowsup\layers\__init__.py", line 130, in receive
    recv(node)
  File "E:\Hakan\yowsup\layers\auth\layer_authentication.py", line 67, in handleStreamError
    raise NotImplementedError("Unhandled stream:error node:\n%s" % node)
NotImplementedError: Unhandled stream:error node:
<stream:error code="503" />

D 2019-08-22 03:53:30,919 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2019-08-22 03:53:31,122 yowsup.layers.network.layer - Disconnected
D 2019-08-22 03:53:31,231 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
D 2019-08-22 03:53:31,419 yowsup.layers.protocol_iq.layer - stopping ping thread
D 2019-08-22 03:53:31,591 yowsup.layers.protocol_iq.layer - YowPingThread-4 - ping thread stopped

**When I try to login again, I get this error.**

[offline]:/L
D 2019-08-22 05:07:50,144 yowsup.layers.network.layer - Created asyncore dispatcher
I 2019-08-22 05:07:50,144 yowsup.layers.network.layer - Connecting to e3.whatsapp.net:443
D 2019-08-22 05:07:50,144 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e3.whatsapp.net', 443))
D 2019-08-22 05:07:50,316 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2019-08-22 05:07:50,332 yowsup.layers.network.layer - Connected
D 2019-08-22 05:07:50,332 yowsup.axolotl.manager - level_prekeys(force=False)
D 2019-08-22 05:07:50,347 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2019-08-22 05:07:50,394 yowsup.axolotl.manager - load_unsent_prekeys
D 2019-08-22 05:07:50,550 yowsup.layers.noise.layer - Received auth event
D 2019-08-22 05:07:50,597 yowsup.layers.noise.layer - Performing handshake [username= 90xxxxxx752 , passive=False]
D 2019-08-22 05:07:50,894 yowsup.layers.noise.layer - Starting handshake worker
E 2019-08-22 05:07:51,113 consonance.handshake - Error parsing message
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\consonance\handshake.py", line 84, in perform
    cipherstatepair = self._start_handshake_ik(stream, client_payload, dissononce_s, dissononce_rs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\consonance\handshake.py", line 192, in _start_handshake_ik
    incoming_handshakemessage.ParseFromString(stream.read_segment())
google.protobuf.message.DecodeError: Error parsing message
D 2019-08-22 05:07:51,269 yowsup.layers.logger.layer - rx:
<failure reason="Error parsing message" />

general: Login Failed, reason: Error parsing message
D 2019-08-22 05:07:51,285 yowsup.layers.network.dispatcher.dispatcher_asyncore - disconnect
D 2019-08-22 05:07:51,285 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2019-08-22 05:07:51,285 yowsup.layers.network.layer - Disconnected
E 2019-08-22 05:07:51,285 yowsup.layers.noise.layer - An error occurred during handshake, try login again.
[offline]:general: Disconnected: Authentication Failure
[offline]:
D 2019-08-22 03:18:57,687 yowsup.layers.protocol_iq.layer - ping queue size: 1

**Ctrl+C**
**I'm logging out and logging in again when I say I'm logging in smoothly.**
**But after 2-3 hours, I get the same error.**

E:\Hakan>python yowsup-cli demos --yowsup --config 90xxxxxx752 --debug
D 2019-08-22 05:13:47,986 yowsup.config.manager - load(path_or_profile_name=90xxxxxx752 , profile_only=False)
D 2019-08-22 05:13:48,174 yowsup.config.manager - _load_path(path=90xxxxxx752 )
D 2019-08-22 05:13:48,346 yowsup.config.manager - _load_path couldn't find the path: 90xxxxxx752 
D 2019-08-22 05:13:48,549 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2019-08-22 05:13:48,549 yowsup.config.manager - Detecting config for profile=90xxxxxx752 , dir=C:\Users\Administrator\AppData\Local\yowsup\yowsup\90xxxxxx752 
D 2019-08-22 05:13:48,549 yowsup.config.manager - Trying C:\Users\Administrator\AppData\Local\yowsup\yowsup\90xxxxxx752 \config.yo
D 2019-08-22 05:13:48,549 yowsup.config.manager - Trying C:\Users\Administrator\AppData\Local\yowsup\yowsup\90xxxxxx752 \config.json
D 2019-08-22 05:13:48,549 yowsup.config.manager - _load_path(path=C:\Users\Administrator\AppData\Local\yowsup\yowsup\90xxxxxx752 \config.json)
D 2019-08-22 05:13:48,549 yowsup.config.manager - Detected config type: json
D 2019-08-22 05:13:48,549 yowsup.config.manager - Opening config for reading
D 2019-08-22 05:13:48,549 yowsup.config.manager - Loading config
D 2019-08-22 05:13:48,549 yowsup.profile.profile - Constructed Profile(profile_name=90xxxxxx752 )
D 2019-08-22 05:13:48,564 yowsup-cli - starting cmd
yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.7
protobuf       v3.9.1


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

D 2019-08-22 05:13:54,736 yowsup.stacks.yowstack - Initializing stack
D 2019-08-22 05:13:54,877 yowsup.stacks.yowstack - Constructed Network Layer
D 2019-08-22 05:13:54,955 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2019-08-22 05:13:55,142 yowsup.stacks.yowstack - Constructed Noise Layer
D 2019-08-22 05:13:55,142 yowsup.stacks.yowstack - Constructed Coder Layer
D 2019-08-22 05:13:55,142 yowsup.stacks.yowstack - Constructed Logger Layer
D 2019-08-22 05:13:55,142 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x0000023C9687B860>
D 2019-08-22 05:13:55,158 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x0000023C95888978>
D 2019-08-22 05:13:55,174 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Med
ia Layer - Privacy Layer - Profiles Layer
D 2019-08-22 05:13:55,174 yowsup.stacks.yowstack - Constructed CLI Interface Layer
D 2019-08-22 05:13:55,189 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=90xxxxxx752 ))
Yowsup Cli client

Type /help for available commands

[offline]: /L
D 2019-08-22 05:14:08,611 yowsup.layers.network.layer - Created asyncore dispatcher
I 2019-08-22 05:14:08,611 yowsup.layers.network.layer - Connecting to e1.whatsapp.net:443
D 2019-08-22 05:14:08,611 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e1.whatsapp.net', 443))
D 2019-08-22 05:14:08,892 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2019-08-22 05:14:08,986 yowsup.layers.network.layer - Connected
D 2019-08-22 05:14:09,199 yowsup.axolotl.factory - get_manager(profile_name=90xxxxxx752 , username=90xxxxxx752 )
D 2019-08-22 05:14:09,205 yowsup.axolotl.manager - Initialized AxolotlManager [username=90xxxxxx752 , db=C:\Users\Administrator\AppData\Local\yowsup\yowsup\90xxxxxx752 \axolotl.db]
D 2019-08-22 05:14:09,205 yowsup.axolotl.manager - level_prekeys(force=False)
D 2019-08-22 05:14:09,220 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2019-08-22 05:14:09,236 yowsup.axolotl.manager - load_unsent_prekeys
D 2019-08-22 05:14:09,267 yowsup.layers.noise.layer - Received auth event
D 2019-08-22 05:14:09,377 yowsup.env.env - Env not set, setting it to android
D 2019-08-22 05:14:09,392 yowsup.env.env - Current env changed to android
D 2019-08-22 05:14:09,408 yowsup.layers.noise.layer - Performing handshake [username= 90xxxxxx752 , passive=False]
D 2019-08-22 05:14:09,580 yowsup.layers.noise.layer - Starting handshake worker
D 2019-08-22 05:14:10,689 yowsup.layers.logger.layer - rx:
<success t="1566440050" props="25" location="atn" creation="1566169933" />
D 2019-08-22 05:14:10,720 yowsup.layers.protocol_iq.layer - starting ping thread.

D 2019-08-22 05:14:14,470 yowsup.layers.logger.layer - rx:
<ib from="s.whatsapp.net">
  <edge_routing>
    <routing_info>
      0x08050802
    </routing_info>
    <dns_domain>
      0x6662
    </dns_domain>
  </edge_routing>
</ib>
D 2019-08-22 05:14:14,470 yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now
D 2019-08-22 05:14:14,470 yowsup.layers.logger.layer - rx:
<ib from="s.whatsapp.net">
  <dirty type="groups" timestamp="1566440050" />
</ib>
D 2019-08-22 05:14:14,470 yowsup.layers.logger.layer - rx:
<ib from="s.whatsapp.net">
  <offline count="0" />
</ib>
[connected]:
```

**Comment by apepenkov** [comment]
Works now. I had  the same issue

**Comment by turkeyhakan** [comment]
yes the problem is improved

**Comment by turkeyhakan** [comment]
problem persists

**Comment by tgalal** [comment]
please follow the bug report template. closing for lack of information.

**Comment by devops35** [comment]
@turkeyhakan did you solve the problem? I have the same problem. Can you help me?
