### ISSUE TITLE
problems in the registration

### ISSUE THREAD

**Issue by JoeHardSal** [tgalal/yowsup#2858]
I have problems with my registration

My command:
./yowsup-cli registration --requestcode sms --phone 51965394505 --cc 51 --mcc 716 --mnc 10

Myserver-ubuntu# ./yowsup-cli registration --requestcode sms --phone 51965394505 --cc 51 --mcc 716 --mnc 10

E 2019-08-26 15:21:20,225 yowsup.config.manager - Could not find a config for profile=51965394505, paths checked: 51965394505:/home/waldoyo/.config/yowsup/51965394505/config.json:/home/waldoyo/.config/yowsup/51965394505/config.yo
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

W 2019-08-26 15:21:20,280 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
Traceback (most recent call last):
  File "./yowsup-cli", line 722, in <module>
    if not parser.process():
  File "./yowsup-cli", line 387, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "./yowsup-cli", line 398, in handleRequestCode
    codeReq = WACodeRequest(method, config)
  File "/home/waldoyo/yowsup/yowsup/registration/coderequest.py", line 15, in __init__
    super(WACodeRequest,self).__init__(config)
  File "/home/waldoyo/yowsup/yowsup/common/http/warequest.py", line 79, in __init__
    config.client_static_keypair = WATools.generateKeyPair()
  File "/home/waldoyo/yowsup/yowsup/common/tools.py", line 70, in generateKeyPair
    return KeyPair.generate()
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.3.post1-py2.7.egg/consonance/structs/keypair.py", line 36, in generate
    keypair = X25519DH().generate_keypair()
  File "build/bdist.linux-x86_64/egg/dissononce/dh/x25519/x25519.py", line 28, in generate_keypair
  File "/usr/local/lib/python2.7/dist-packages/cryptography-2.7-py2.7-linux-x86_64.egg/cryptography/hazmat/primitives/asymmetric/x25519.py", line 42, in generate
    _Reasons.UNSUPPORTED_EXCHANGE_ALGORITHM
**cryptography.exceptions.UnsupportedAlgorithm: X25519 is not supported by this version of OpenSSL.**
myserver-ubuntuyowsup# 

Please Help

**Comment by tgalal** [comment]
not a yowsup issue

**Comment by tgalal** [comment]
#2658
