### ISSUE TITLE
Is not the openssl version

### ISSUE THREAD

**Issue by JoeHardSal** [tgalal/yowsup#2859]
good evening

I check my server and my openssl version is ok
I think is this log the problem

PowerEdge-R300:~/yowsup# **./yowsup-cli registration --requestcode sms --phone 51965394505 --cc 51 --mcc 716 --mnc 10**
E 2019-08-26 16:09:18,094 yowsup.config.manager - Could not find a config for profile=51965394505, paths checked: 51965394505:/home/waldoyo/.config/yowsup/51965394505/config.json:/home/waldoyo/.config/yowsup/51965394505/config.yo
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

W 2019-08-26 16:09:18,376 yowsup.common.http.warequest - **Passing Config to WARequest is deprecated, pass a YowProfile instead**
Traceback (most recent call last):
  File "./yowsup-cli", line 722, in <module>
    if not parser.process():
  File "./yowsup-cli", line 387, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "./yowsup-cli", line 398, in handleRequestCode
    codeReq = WACodeRequest(method, config)
  File "/home/waldoyo/yowsup/yowsup/registration/coderequest.py", line 15, in __init__
    super(WACodeRequest,self).__init__(config)
  File "/home/waldoyo/yowsup/yowsup/common/http/warequest.py", line 79, in __init__
    config.client_static_keypair = WATools.generateKeyPair()
  File "/home/waldoyo/yowsup/yowsup/common/tools.py", line 70, in generateKeyPair
    return KeyPair.generate()
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.3.post1-py2.7.egg/consonance/structs/keypair.py", line 36, in generate
    keypair = X25519DH().generate_keypair()
  File "build/bdist.linux-x86_64/egg/dissononce/dh/x25519/x25519.py", line 28, in generate_keypair
  File "/usr/local/lib/python2.7/dist-packages/cryptography-2.7-py2.7-linux-x86_64.egg/cryptography/hazmat/primitives/asymmetric/x25519.py", line 42, in generate
    _Reasons.UNSUPPORTED_EXCHANGE_ALGORITHM
cryptography.exceptions.UnsupportedAlgorithm: X25519 is not supported by this version of OpenSSL.

root@waldoyo-PowerEdge-R300:~/yowsup# openssl version
OpenSSL 1.1.1b  26 Feb 2019
PowerEdge-R300:~/yowsup# 

Please , your help

Thanks

**Comment by tgalal** [comment]
https://www.google.com/search?q=X25519+is+not+supported+by+this+version+of+OpenSSL

**Comment by antoniovalenzuela** [comment]
RPI3 (Raspbian Buster) 
Solved

wget https://www.openssl.org/source/openssl-${OPENSSL_VER}.tar.gz
tar xf openssl-${OPENSSL_VER}.tar.gz
./config zlib shared no-ssl3
make -j4
make install

export LDFLAGS="-L/usr/local/lib/"
export LD_LIBRARY_PATH="/usr/local/lib/"
export CPPFLAGS="-I/usr/local/include -I/usr/local/include/openssl"

wget https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz
tar xzf Python-2.7.11.tgz
./configure --prefix=/usr/local/
make
make altinstall
