### ISSUE TITLE
broadcastEvent Error

### ISSUE THREAD

**Issue by AlejandroBlackburn** [tgalal/yowsup#2879]
Hi, when I execute yowsup and use self.stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT)) I get the following error:

```
ERROR:yowsup.layers.network.dispatcher.dispatcher_asyncore:Traceback (most recent call last):
  File "F:\Python\lib\asyncore.py", line 91, in write
    obj.handle_write_event()
  File "F:\Python\lib\asyncore.py", line 441, in handle_write_event
    self.handle_connect_event()
  File "F:\Python\lib\asyncore.py", line 429, in handle_connect_event
    self.handle_connect()
  File "F:\Python\lib\site-packages\yowsup\layers\network\dispatcher\dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "F:\Python\lib\site-packages\yowsup\layers\network\layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "F:\Python\lib\site-packages\yowsup\layers\auth\layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "F:\Python\lib\site-packages\yowsup\layers\__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "F:\Python\lib\site-packages\yowsup\layers\noise\layer.py", line 58, in on_auth
    config = self._config_manager.load(self._username)  # type: yowsup.config.v1.config.Config
  File "F:\Python\lib\site-packages\yowsup\config\manager.py", line 53, in load
    return self.load_path(fpath)
  File "F:\Python\lib\site-packages\yowsup\config\manager.py", line 87, in load_path
    return self.load_data(datadict)
  File "F:\Python\lib\site-packages\yowsup\config\manager.py", line 95, in load_data
    return ConfigSerialize(Config).deserialize(datadict)
  File "F:\Python\lib\site-packages\yowsup\config\base\serialize.py", line 26, in deserialize
    data = transform.reverse(data)
  File "F:\Python\lib\site-packages\yowsup\config\transforms\config_dict.py", line 27, in reverse
    return self._cls(**data)
TypeError: __init__() got an unexpected keyword argument 'login'
```

What is wrong? I search in all Google but I don't find anything

**Comment by tgalal** [comment]
please follow the bug report template. closing for lack of information.
