### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by ayzakh** [tgalal/yowsup#2886]
How can i store profile data in another path?

python version: 3.6.8
yowsup version: current, using git clone

OS: linux, ubuntu 18

config:
{
    "__version__": 1,
    "cc": "7",
    "client_static_keypair": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", // masked
    "edge_routing_info": "CAIICA==",
    "expid": "tzgHxItESwui/9EBp+PyGQ==",
    "fdid": "bf788f8c-a465-4958-9f72-639b3caa27df",
    "id": "5U9lkN2HO6BIEg4E2CZ5cP1xVDA=",
    "login": "79243641073",
    "mcc": "250",
    "mnc": "02",
    "phone": "79243641073",
    "server_static_public": "LKFtqKAASnxIgl89fmUjtpxpL8WVkwPZLMk3ybT3ggI=",
    "sim_mcc": "000",
    "sim_mnc": "000"
}

input:
trying to set profile from different folder /home/aysen/.config/7xxxxxxxx/config.json (not $HOME/.config/yowsup/7xxxxxxx)

output:
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
E 2019-10-10 01:11:36,617 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.6/asyncore.py", line 441, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.6/asyncore.py", line 429, in handle_connect_event
    self.handle_connect()
  File "/home/aysen/.local/lib/python3.6/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/home/aysen/.local/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 54, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/home/aysen/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/aysen/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/aysen/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/home/aysen/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/home/aysen/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/home/aysen/.local/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_control.py", line 56, in on_connected
    super(AxolotlControlLayer, self).on_connected(yowLayerEvent)
  File "/home/aysen/.local/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_base.py", line 37, in on_connected
    self._manager = profile.axolotl_manager
  File "/home/aysen/.local/lib/python3.6/site-packages/yowsup/profile/profile.py", line 50, in axolotl_manager
    self._axolotl_manager = self._load_axolotl_manager()
  File "/home/aysen/.local/lib/python3.6/site-packages/yowsup/profile/profile.py", line 34, in _load_axolotl_manager
    return AxolotlManagerFactory().get_manager(self._profile_name, self.username)
  File "/home/aysen/.local/lib/python3.6/site-packages/yowsup/axolotl/factory.py", line 15, in get_manager
    store = LiteAxolotlStore(dbpath)
  File "/home/aysen/.local/lib/python3.6/site-packages/yowsup/axolotl/store/sqlite/liteaxolotlstore.py", line 12, in __init__
    conn = sqlite3.connect(db, check_same_thread=False)
sqlite3.OperationalError: unable to open database file

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/blob/master/yowsup/common/tools.py#L96

This method returns storage path for a given `profile_name`, change that.
