### ISSUE TITLE
No module named handshake_failed_exception

### ISSUE THREAD

**Issue by holgerschochwitz** [tgalal/yowsup#2888]
Hallo
i get an error after start this:
/opt/yowsup-master/yowsup-cli demos --config-phone 4934609253781 --yowsup

Traceback (most recent call last):
  File "/opt/yowsup-master/yowsup-cli", line 722, in <module>
    if not parser.process():
  File "/opt/yowsup-master/yowsup-cli", line 606, in process
    self.startCmdline()
  File "/opt/yowsup-master/yowsup-cli", line 627, in startCmdline
    from yowsup.demos import cli
  File "/opt/yowsup-master/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/opt/yowsup-master/yowsup/demos/cli/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/opt/yowsup-master/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/opt/yowsup-master/yowsup/stacks/yowstack.py", line 4, in <module>
    from yowsup.layers.noise.layer import YowNoiseLayer
  File "/opt/yowsup-master/yowsup/layers/noise/layer.py", line 1, in <module>
    from yowsup.layers.noise.workers.handshake import WANoiseProtocolHandshakeWorker
  File "/opt/yowsup-master/yowsup/layers/noise/workers/handshake.py", line 3, in <module>
    from consonance.exceptions.handshake_failed_exception import HandshakeFailedException
ImportError: No module named handshake_failed_exception

Thanks

**Comment by holgerschochwitz** [comment]
I have delete Import HandshakeFailedException and now i get a Connection

next i got this message

UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 113: ordinal not in range(128)
 and this resolve the Problem in the layer.py

import sys
reload(sys)
sys.setdefaultencoding('utf8')

It is possible to implement this or is this not correct?

**Comment by paco020295** [comment]
I think i had this problem a few days ago

I replaced the folders that were casing errors. For example, the first error was 
handshake_failed_exception. That module is supposed to be inside consonance. So i replaced consonance from dist-packages in python folder with https://github.com/tgalal/consonance/tree/master/consonance

I think it's going to give you different errors. Just replace them with the correct repositories from tgalal.

Hope this is clear and hope it helps

**Comment by myckhel** [comment]
`pip install consonance --force` saved me from the errors
