### ISSUE TITLE
WARequest.__init_ in connected profile

### ISSUE THREAD

**Issue by syberi** [tgalal/yowsup#2891]
Hi ,   profile connected text messages go and come,  i try sending image 

what am I doing wrong? :
mediaUploader = MediaUploader(self.demoContactJid, self.getOwnJid(), self.filePath,
                                      resultRequestUploadIqProtocolEntity.getUrl(),
                                      resultRequestUploadIqProtocolEntity.getResumeOffset(),
                                      self.onUploadSuccess, self.onUploadError, self.onUploadProgress, asynchronous=False)
         
         mediaUploader.start()
but have error :

E 2019-10-25 16:22:42,853 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/network/layer.py", line 107, in onRecvData
    self.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/axolotl/layer_receive.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 126, in receive
    if not self.processIqRegistry(node):
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 161, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/protocol_media/layer.py", line 78, in onRequestUploadSuccess
    self.toUpper(ResultRequestUploadIqProtocolEntity.fromProtocolTreeNode(resultNode))
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/interface/interface.py", line 77, in receive
    if not self.processIqRegistry(entity):
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/interface/interface.py", line 56, in processIqRegistry
    successClbk(entity, originalIq)
  File "/home/novikov/user/yowsup-master/yowsup/demos/echoclient/layer.py", line 146, in onRequestUploadResult
    self.onUploadSuccess, self.onUploadError, self.onUploadProgress, asynchronous=False)
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/protocol_media/mediauploader.py", line 18, in __init__
    WARequest.__init__(self)
TypeError: __init__() missing 1 required positional argument: 'config_or_profile'

**Comment by syberi** [comment]
[https://github.com/tgalal/yowsup/issues/2724#issuecomment-494359606](2724#issuecomment-494359606 )- the same problem was here, it is not fixed yet?

**Comment by syberi** [comment]
Guys, somebody knows as to send media ? help with sample code please.

**Comment by dogexan** [comment]
Hi, I have exactly the same problem. Anybody got a solution yet? Thanks
