### ISSUE TITLE
"Sent keys were not accepted" under Ubuntu Linux

### ISSUE THREAD

**Issue by frankmuc** [tgalal/yowsup#2892]
I know that there are some issues regarding this error but they seem to refer to Windows and I can't fix it.

I build a yowsup installation directly from GIT under Ubuntu Linux and was able to register a phone number (received the code via phone) but when logging in, it throws the error "Sent keys were not accepted".

How can I fix that?

[offline]:/L
I 2019-11-02 19:47:06,870 yowsup.layers.network.layer - Connecting to e13.whatsapp.net:443
I 2019-11-02 19:47:07,125 yowsup.axolotl.manager - Loaded 812 unsent prekeys
Auth: Logged in!
[connected]:E 2019-11-02 19:47:08,869 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/layer.py", line 107, in onRecvData
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 28, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 163, in processIqRegistry
    errorClbk(protocolTreeNode, originalIq)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 118, in onSentKeysError
    raise Exception("Sent keys were not accepted")
Exception: Sent keys were not accepted

general: Disconnected: 
[connected]:

**Comment by OVERSKY2003** [comment]
I also had the same issue today. How to solve it?

**Comment by frankmuc** [comment]
I am no longer using yowsup. Isn't this project dead anyway? It can't be used any longer as far as I know...

**Comment by frankmuc** [comment]
I am closing this issue since the affected system does no longer exist after three years, so it's no longer relevant.

**Comment by huoxing007** [comment]
> I also had the same issue today. How to solve it?

https://github.com/tgalal/yowsup/issues/3182
