### ISSUE TITLE
Crash loading YowProfile

### ISSUE THREAD

**Issue by fabi321** [tgalal/yowsup#2897]
```
E 2019-11-13 15:31:56,852 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.7/asyncore.py", line 440, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.7/asyncore.py", line 428, in handle_connect_event
    self.handle_connect()
  File "/yowsup-3.2.4-py3.7.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/yowsup-3.2.4-py3.7.egg/yowsup/layers/network/layer.py", line 54, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/yowsup-3.2.4-py3.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/yowsup-3.2.4-py3.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/yowsup-3.2.4-py3.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/yowsup-3.2.4-py3.7.egg/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/yowsup-3.2.4-py3.7.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/yowsup-3.2.4-py3.7.egg/yowsup/layers/axolotl/layer_control.py", line 56, in on_connected
    super(AxolotlControlLayer, self).on_connected(yowLayerEvent)
  File "/yowsup-3.2.4-py3.7.egg/yowsup/layers/axolotl/layer_base.py", line 37, in on_connected
    self._manager = profile.axolotl_manager
  File "/yowsup-3.2.4-py3.7.egg/yowsup/profile/profile.py", line 50, in axolotl_manager
    self._axolotl_manager = self._load_axolotl_manager()
  File "/yowsup-3.2.4-py3.7.egg/yowsup/profile/profile.py", line 34, in _load_axolotl_manager
    return AxolotlManagerFactory().get_manager(self._profile_name, self.username)
  File "/yowsup-3.2.4-py3.7.egg/yowsup/profile/profile.py", line 55, in username
    config = self.config
  File "/yowsup-3.2.4-py3.7.egg/yowsup/profile/profile.py", line 44, in config
    self._config = self._load_config()
  File "/yowsup-3.2.4-py3.7.egg/yowsup/profile/profile.py", line 30, in _load_config
    return self._config_manager.load(self._profile_name)
  File "/yowsup-3.2.4-py3.7.egg/yowsup/config/manager.py", line 46, in load
    config = self._load_path(path_or_profile_name)
  File "/yowsup-3.2.4-py3.7.egg/yowsup/config/manager.py", line 92, in _load_path
    if os.path.isfile(path):
  File "/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not Config
```

That's bechause in /yowsup-3.2.4-py3.7.egg/yowsup/profile/profile.py:
```
    def _load_config(self):
        # type: () -> Config
        logger.debug("load_config for %s" % self._profile_name)
        return self._config_manager.load(self._profile_name)
```
in my mind, it should be
`        return self._config_manager.load(self._profile_name, profile_only=True)`

**Comment by fabi321** [comment]
By the way, I found my error. I was trying to set a Config as YowProfile
