### ISSUE TITLE
ModuleNotFoundError: No module named "consonance"

### ISSUE THREAD

**Issue by scruzy** [tgalal/yowsup#2902]
I am trying to  run the last command 

yowsup-cli demos --yowsup --config config.json

It get an error:

Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 6, in <module>
    from yowsup.config.manager import ConfigManager
  File "/usr/lib/python3/dist-packages/yowsup/config/manager.py", line 4, in <module>
    from yowsup.config.v1.serialize import ConfigSerialize
  File "/usr/lib/python3/dist-packages/yowsup/config/v1/serialize.py", line 8, in <module>
    from consonance.structs.keypair import KeyPair
ModuleNotFoundError: No module named 'consonance'

How can I go on from this?

**Comment by Ser1aL** [comment]
Getting the same error.
