### ISSUE TITLE
Logged in!, but invalid token error. 

### ISSUE THREAD

**Issue by nightcoder22** [tgalal/yowsup#2923]
Hi all, I am able to get log in but facing this value error: Invalid token. Anyone have any idea about this? How to solve?

I followed a solution given by @iacup in #2922

`Logged in!
W 2020-01-27 17:05:10,429 yowsup.layers.protocol_notifications.layer - Unsupported notification type: psa
E 2020-01-27 17:05:10,431 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 100, in onRecvData
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 103, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/noise/layer.py", line 156, in receive
    self._flush_incoming_buffer()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/noise/layer.py", line 144, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 34, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_notifications/layer.py", line 43, in recvNotification
    self.toLower(ack.toProtocolTreeNode())
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer_send.py", line 39, in send
    self.toLower(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/axolotl/layer_control.py", line 22, in send
    self.toLower(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/logger/layer.py", line 9, in send
    self.toLower(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/layer.py", line 16, in send
    self.write(self.writer.protocolTreeNodeToBytes(data))
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/encoder.py", line 8, in protocolTreeNodeToBytes
    self.writeInternal(node, outBytes)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/encoder.py", line 23, in writeInternal
    self.writeAttributes(node.attributes, data);
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/encoder.py", line 39, in writeAttributes
    self.writeString(value, data, True);
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/encoder.py", line 122, in writeString
    self.writeToken(index, data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/encoder.py", line 113, in writeToken
    raise ValueError("Invalid token: %s" % token)
ValueError: Invalid token: 292

Disconnected:
Disconnected: due to handshake error.
`

**Comment by batuhanrn** [comment]
how you solved this issue

**Comment by fajarnurprasetyo** [comment]
@nightcoder22  how do you solve this error?
