### ISSUE TITLE
When I use yowsup-cli registration,feedback tips Network is unreachable

### ISSUE THREAD

**Issue by Dabai1021** [tgalal/yowsup#2931]
**Describe the bug**
When I use yowsup-cli registration,feedback tips Network is unreachable

**Debug output**

yowsup-cli registration --requestcode sms --config-phone 49XXXXXXXX --config-cc 49
E 2020-02-04 16:01:09,439 yowsup.config.manager - Could not find a config for username=49XXXXXXXX, paths checked: /home/python/.config/yowsup/49XXXXXXXX/config.json:/home/python/.config/yowsup/49XXXXXXXX/config.yo
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Traceback (most recent call last):
  File "/home/python/.virtualenvs/MyInfoHouse01/bin/yowsup-cli", line 679, in <module>
    if not parser.process():
  File "/home/python/.virtualenvs/MyInfoHouse01/bin/yowsup-cli", line 350, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/home/python/.virtualenvs/MyInfoHouse01/bin/yowsup-cli", line 362, in handleRequestCode
    result = codeReq.send(encrypt=self._encrypt, preview=self._preview)
  File "/home/python/.virtualenvs/MyInfoHouse01/lib/python3.5/site-packages/yowsup/registration/coderequest.py", line 46, in send
    res = super(WACodeRequest, self).send(parser, encrypt=encrypt, preview=preview)
  File "/home/python/.virtualenvs/MyInfoHouse01/lib/python3.5/site-packages/yowsup/common/http/warequest.py", line 133, in send
    return self.sendGetRequest(parser, encrypt, preview=preview)
  File "/home/python/.virtualenvs/MyInfoHouse01/lib/python3.5/site-packages/yowsup/common/http/warequest.py", line 205, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET", preview=preview)
  File "/home/python/.virtualenvs/MyInfoHouse01/lib/python3.5/site-packages/yowsup/common/http/warequest.py", line 294, in sendRequest
    conn.request(reqType, path, params, headers)
  File "/usr/lib/python3.5/http/client.py", line 1122, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1167, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1118, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 944, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 887, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1268, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 859, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

**Comment by everaldoscabral** [comment]
Use python 3.6.

**Comment by ciclanoio** [comment]
the same here in python 3.6

**Comment by ciclanoio** [comment]
I use python 3.6 and the network problems appear, all request to new SMS and register is very slow now.

I don't know what's happening

**Comment by jsandonas89** [comment]
They know if the yowsup library is currently working, because I try to register to send me the verification code, but I get an error.

**Comment by gmistick** [comment]
It is working, what is the error you are getting? 

1. Maybe you are not able to access the whatsapp registration servers due to firewalling? Make sure you are not blocked.

ping v.whatsapp.net - see if you get response
curl https://v.whatsapp.net/v2/register --> what is the response you are getting?

**Comment by jongositem** [comment]
my response 
{"status":"fail","reason":"missing_param","param":"in"}
