### ISSUE TITLE
 It does not allow me to register yowsup-cli

### ISSUE THREAD

**Issue by jsandonas89** [tgalal/yowsup#2935]
Good,

I try to register with the following command line, indicated on the git page,
yowsup-cli registration --requestcode sms --config-phone 51XXXXXXXX --config-cc 51 --config-mcc 716 --config-mnc 17

and it shows me the following message:

usage: registration [-h] [-v] [-d] [--help-config] [-c CONFIG]
                    [-E {android, s40}] [-m MCC] [-n MNC] [-p PHONE] [-C CC]
                    [-r (sms | voice) | -R code]
registration: error: unrecognized arguments: --config-phone 51XXXXXXXX --config-cc 51 --config-mcc 716 --config-mnc 17

could you help me

**Comment by gmistick** [comment]
try the following:
yowsup-cli registration -r sms --config-phone 51XXXXXXXX --config-cc 51 --config-mcc 716 --config-mnc 17

**Comment by jsandonas89** [comment]
root@SSPEZABBIX:/# yowsup-cli registration --register 738500 --config-phone 519891626XX --config-cc 51
yowsup-cli  v3.2.0
yowsup      v3.2.3


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


W 2020-02-26 21:15:49,573 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
I 2020-02-26 21:15:50,140 yowsup.common.http.warequest - {"login":"519891626XX","status":"fail","reason":"missing"}

{
    "__version__": 1,
    "cc": "51",
    "client_static_keypair": "sJvgiMNuxpxrooW+ZXMbkUri7GZWd7hXqXAyCBW4UWH8s0zx7DKHQvEpDlwi7BYngRv6Uro/XjBgMTfIdRW5VA==",
    "expid": "zUOiFWTNSKOjBSGec2W0KQ==",
    "fdid": "740a38b2-fc20-42ce-90e9-68922200678c",
    "id": "TyEnjFGAhvFYRB6z0rS/FxfoKDE=",
    "login": "519891626XX",
    "mcc": "716",
    "mnc": "17",
    "phone": "519891626XX",
    "sim_mcc": "000",
    "sim_mnc": "000"
}
status: fail
login: 519891626XX
root@SSPEZABBIX:/#

could you help me

**Comment by GM12Tick** [comment]
I wrote down the command and you ignore it.
Please use the command i sent you

**Comment by safciplak** [comment]
how can fix it? 
yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead

**Comment by iskeltan** [comment]
> root@SSPEZABBIX:/# yowsup-cli registration --register 738500 --config-phone 519891626XX --config-cc 51 yowsup-cli v3.2.0 yowsup v3.2.3
> 
> Copyright (c) 2012-2019 Tarek Galal http://www.openwhatsapp.org
> 
> This software is provided free of charge. Copying and redistribution is encouraged.
> 
> If you appreciate this software and you would like to support future development please consider donating: http://openwhatsapp.org/yowsup/donate
> 
> W 2020-02-26 21:15:49,573 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead I 2020-02-26 21:15:50,140 yowsup.common.http.warequest - {"login":"519891626XX","status":"fail","reason":"missing"}
> 
> { "**version**": 1, "cc": "51", "client_static_keypair": "sJvgiMNuxpxrooW+ZXMbkUri7GZWd7hXqXAyCBW4UWH8s0zx7DKHQvEpDlwi7BYngRv6Uro/XjBgMTfIdRW5VA==", "expid": "zUOiFWTNSKOjBSGec2W0KQ==", "fdid": "740a38b2-fc20-42ce-90e9-68922200678c", "id": "TyEnjFGAhvFYRB6z0rS/FxfoKDE=", "login": "519891626XX", "mcc": "716", "mnc": "17", "phone": "519891626XX", "sim_mcc": "000", "sim_mnc": "000" } status: fail login: 519891626XX root@SSPEZABBIX:/#
> 
> could you help me

same here

**Comment by ghost** [comment]
linux@nagios:~$ yowsup-cli registration -R 499-702 --config-phone 917xxxxxxx
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


I 2023-03-20 16:28:08,680 yowsup.common.http.warequest - b'{"autoconf_type":1,"lid":"18696126881998","login":"9170xxxxxxx","security_code_set":false,"status":"ok","type":"existing"}\n'
{
    "__version__": 1,
    "cc": "91",
    "client_static_keypair": "wOOu57uLPqLQ8VrNEU8SRwVN7cs8yk7FA0fL8li6+l/3u2hZZuex5VaiVR55wvflKEgz4ziVzFxDUOBSYHJLaQ==",
    "expid": "Q65iEGyWQKaACEXLmAGE2A==",
    "fdid": "26ecdec5-02f9-4174-86e6-8e16c3a78113",
    "id": "lrHhRBpmUKMpi5QXHfUUrgkMZR4=",
    "mcc": "405",
    "mnc": "19",
    "phone": "9170xxxxxxxx",
    "sim_mcc": "000",
    "sim_mnc": "000"
}
Traceback (most recent call last):
  File "/home/linux/.local/bin/yowsup-cli", line 679, in <module>
    if not parser.process():
  File "/home/linux/.local/bin/yowsup-cli", line 352, in process
    self.handleRegister(self.args["register"], config)
  File "/home/linux/.local/bin/yowsup-cli", line 384, in handleRegister
    self._config.edge_routing_info = base64.b64decode(result["edge_routing_info"])
  File "/usr/lib/python3.10/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/lib/python3.10/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

any help
