### ISSUE TITLE
Can't trigger event send from state handshake

### ISSUE THREAD

**Issue by weechatfly** [tgalal/yowsup#2939]
when I use yowsup-cli demos -y start commands, /message send xxxx xxxx, I got the exception:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "F:\software\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "F:\software\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\demos\cli\cli.py", line 160, in startInputThread
    wait = self.execCmd(cmd)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\demos\cli\cli.py", line 141, in execCmd
    return self.doExecCmd(lambda :targetFn(*args))
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\demos\cli\cli.py", line 144, in doExecCmd
    return fn()
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\demos\cli\cli.py", line 141, in <lambda>
    return self.doExecCmd(lambda :targetFn(*args))
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\demos\cli\layer.py", line 103, in presence_name
    self.toLower(entity)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\__init__.py", line 198, in send
    s.send(data)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\__init__.py", line 136, in send
    send(entity)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\protocol_presence\layer.py", line 16, in sendPresence
    self.entityToLower(entity)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\__init__.py", line 140, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\__init__.py", line 198, in send
    s.send(data)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\axolotl\layer_send.py", line 45, in send
    self.toLower(node)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\axolotl\layer_control.py", line 22, in send
    self.toLower(node)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\logger\layer.py", line 9, in send
    self.toLower(data)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\coder\layer.py", line 16, in send
    self.write(self.writer.protocolTreeNodeToBytes(data))
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\coder\layer.py", line 25, in write
    self.toLower(bytearray(i))
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "F:\software\Python\Python37-32\lib\site-packages\yowsup\layers\noise\layer.py", line 164, in send
    self._wa_noiseprotocol.send(data)
  File "F:\software\Python\Python37-32\lib\site-packages\consonance\protocol.py", line 107, in send
    self._machine.send()
  File "F:\software\Python\Python37-32\lib\site-packages\transitions\core.py", line 383, in trigger
    return self.machine._process(func)
  File "F:\software\Python\Python37-32\lib\site-packages\transitions\core.py", line 1047, in _process
    return trigger()
  File "F:\software\Python\Python37-32\lib\site-packages\transitions\core.py", line 397, in _trigger
    raise MachineError(msg)
transitions.core.MachineError: "Can't trigger event send from state handshake!"

W 2020-02-20 16:10:39,648 yowsup.layers.axolotl.layer_receive - Invalid KeyId for 917259306441, going to send a retry

**Comment by rajatpathak** [comment]
Yes, even I am facing same issue from yesterday!

**Comment by rajatpathak** [comment]
@tgalal any luck bro?

**Comment by Johnprogg** [comment]
@iacup Can you help ?

**Comment by Johnprogg** [comment]
It's Working Now, Thanks.

**Comment by weechatfly** [comment]
@Johnprogg Do you have the same problem? How did you solve it?

**Comment by Johnprogg** [comment]
@weechatfly no my issue was online/offline status issue, After using New Registration and IP it's working now.

```
/L 
/presence available
/presence subscribe
```
