### ISSUE TITLE
error on /L 

### ISSUE THREAD

**Issue by ram-sh** [tgalal/yowsup#2954]
First and foremost - **huge thanks for this project!!!**

I have successfully got a registration reply after the SMS arrival and saved a config.json file (replaced some data with 'XXXXXXXXXX'):
`{
    "__version__": 1,
    "cc": "1",
    "client_static_keypair": "XXXXXXXXXXe2fH0iDRRI+3urYR060JB1y/G1OTwYLyNLMgtAk/M0hEHxmw9jZ2bd16Ns6w+o3KTdhdA==",
    "expid": "XXXXXXXXXXuuB8yjz88L4A==",
    "fdid": XXXXXXXXXXd2d-4110-9413-2b2d5396d8fc",
    "id": "XXXXXXXXXXLWTnIPT1VTZJo0MkVaxQ=",
    "login": "XXXXXXXXXX612",
    "mcc": "222",
    "mnc": "46",
    "phone": "XXXXXXXXXX612",
    "sim_mcc": "000",
    "sim_mnc": "000"
}`

when trying to login I get the following error when using Python 2.7.16:

```
python yowsup-cli demos --yowsup --config config.json 
yowsup-cli  v3.2.0
yowsup      v3.2.3


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
I 2020-03-13 23:19:03,315 yowsup.layers.network.layer - Connecting to e2.whatsapp.net:443
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/yowsup/yowsup/demos/cli/layer.py", line 430, in <lambda>
    threading.Thread(target=lambda: self.getLayerInterface(YowNetworkLayer).connect()).start()
  File "/home/pi/yowsup/yowsup/layers/network/layer_interface.py", line 4, in connect
    self._layer.createConnection()
  File "/home/pi/yowsup/yowsup/layers/network/layer.py", line 92, in createConnection
    self._dispatcher.connect(endpoint)
  File "/home/pi/yowsup/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 27, in connect
    asyncore.dispatcher_with_send.connect(self, host)
  File "/usr/lib/python2.7/asyncore.py", line 356, in connect
    raise socket.error(err, errorcode[err])
error: [Errno 101] ENETUNREACH
```

and when using python3 3.7.3:
```
python3 yowsup-cli demos --yowsup --config config.json 
Traceback (most recent call last):
  File "yowsup-cli", line 6, in <module>
    from yowsup.config.manager import ConfigManager
  File "/home/pi/yowsup/yowsup/config/manager.py", line 4, in <module>
    from yowsup.config.v1.serialize import ConfigSerialize
  File "/home/pi/yowsup/yowsup/config/v1/serialize.py", line 8, in <module>
    from consonance.structs.keypair import KeyPair
ModuleNotFoundError: No module named 'consonance'
```

Many thanks in advance!!
Best,
RS

**Comment by ram-sh** [comment]
managed to fix the problem after many struggles (different linux device) but now have a new one :)

will try to understand that before posting another issue.
