### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'config'

### ISSUE THREAD

**Issue by titipc** [tgalal/yowsup#2958]
I am new to yowsup and after being able to resolve old_version and update protocol to v3, 
i got registered and  following error message:
AttributeError: 'NoneType' object has no attribute 'config'

**Debug output**
C:\Users\tiberio>yowsup-cli demos -d --yowsup --config-phone 558xxxxxxx99
D 2020-03-26 00:24:49,470 yowsup.config.manager - Detecting config for username=558xxxxxxx99, dir=C:\Users\tiberio\AppData\Local\yowsup\yowsup\558xxxxxxx99/
D 2020-03-26 00:24:49,470 yowsup.config.manager - Trying C:\Users\tiberio\AppData\Local\yowsup\yowsup\558xxxxxxx99/config.json
D 2020-03-26 00:24:49,470 yowsup.config.manager - load_path(path=C:\Users\tiberio\AppData\Local\yowsup\yowsup\558xxxxxxx99/config.json)
D 2020-03-26 00:24:49,470 yowsup.config.manager - Detected config type: json
D 2020-03-26 00:24:49,470 yowsup.config.manager - Opening config for reading
D 2020-03-26 00:24:49,471 yowsup.config.manager - Loading config
D 2020-03-26 00:24:49,471 yowsup-cli - starting cmd
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

D 2020-03-26 00:24:49,640 yowsup.stacks.yowstack - Initializing stack
D 2020-03-26 00:24:49,641 yowsup.stacks.yowstack - Constructed Network Layer
D 2020-03-26 00:24:49,641 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2020-03-26 00:24:49,642 yowsup.stacks.yowstack - Constructed Noise Layer
D 2020-03-26 00:24:49,642 yowsup.stacks.yowstack - Constructed Coder Layer
D 2020-03-26 00:24:49,644 yowsup.stacks.yowstack - Constructed Logger Layer
D 2020-03-26 00:24:49,644 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x03928150>
D 2020-03-26 00:24:49,645 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x038F7C30>
D 2020-03-26 00:24:49,645 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - I
q Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2020-03-26 00:24:49,648 yowsup.stacks.yowstack - Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
D 2020-03-26 00:24:54,025 yowsup.layers.network.layer - Created asyncore dispatcher
I 2020-03-26 00:24:54,025 yowsup.layers.network.layer - Connecting to e10.whatsapp.net:443
D 2020-03-26 00:24:54,025 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e10.whatsapp.net', 443))
D 2020-03-26 00:24:54,180 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2020-03-26 00:24:54,190 yowsup.layers.network.layer - Connected
D 2020-03-26 00:24:54,190 yowsup.axolotl.factory - get_manager(username=558xxxxxxx99)
D 2020-03-26 00:24:54,194 yowsup.axolotl.manager - Initialized AxolotlManager [username=558xxxxxxx99, db=C:\Users\tiberio\AppData\Local\yowsup\yowsup\558598212
1586\axolotl.db]
D 2020-03-26 00:24:54,194 yowsup.axolotl.manager - level_prekeys(force=False)
D 2020-03-26 00:24:54,204 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2020-03-26 00:24:54,210 yowsup.axolotl.manager - load_unsent_prekeys
I 2020-03-26 00:24:54,220 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2020-03-26 00:24:54,220 yowsup.axolotl.factory - get_manager(username=558xxxxxxx99)
D 2020-03-26 00:24:54,224 yowsup.axolotl.manager - Initialized AxolotlManager [username=558xxxxxxx99, db=C:\Users\tiberio\AppData\Local\yowsup\yowsup\558598212
1586\axolotl.db]
D 2020-03-26 00:24:54,224 yowsup.axolotl.factory - get_manager(username=558xxxxxxx99)
D 2020-03-26 00:24:54,224 yowsup.axolotl.manager - Initialized AxolotlManager [username=558xxxxxxx99, db=C:\Users\tiberio\AppData\Local\yowsup\yowsup\558598212
1586\axolotl.db]
D 2020-03-26 00:24:54,230 yowsup.layers.noise.layer - Received auth event
D 2020-03-26 00:24:54,230 yowsup.layers.noise.layer - None
E 2020-03-26 00:24:54,230 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "C:\Python27\lib\asyncore.py", line 91, in write
    obj.handle_write_event()
  File "C:\Python27\lib\asyncore.py", line 467, in handle_write_event
    self.handle_connect_event()
  File "C:\Python27\lib\asyncore.py", line 455, in handle_connect_event
    self.handle_connect()
  File "C:\Python27\lib\site-packages\yowsup\layers\network\dispatcher\dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "C:\Python27\lib\site-packages\yowsup\layers\network\layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "C:\Python27\lib\site-packages\yowsup\layers\auth\layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "C:\Python27\lib\site-packages\yowsup\layers\__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "C:\Python27\lib\site-packages\yowsup\layers\noise\layer.py", line 62, in on_auth
    config = self._profile.config  # type: yowsup.config.v1.config.Config
AttributeError: 'NoneType' object has no attribute 'config'

D 2020-03-26 00:24:54,244 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-03-26 00:24:54,244 yowsup.layers.network.layer - Disconnected
D 2020-03-26 00:24:54,255 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
general: Disconnected:

**Config file**

{
    "__version__": 1,
    "cc": "55",
    "client_static_keypair": "4C6????????????????????????????????????? RND8rCR+nhukjtMZfv3byZsog/HNmaN9EGWCfQ==",
    "expid": "qHjK???????????==",
    "fdid": "201d5861-????-4???-85a3-19??????",
    "id": "ffjBXXykW/F?????????=",
    "mcc": "724",
    "mnc": "10",
    "phone": "558???????99",
    "sim_mcc": "000",
    "sim_mnc": "000"
}

**Versions**
Python 2.7.17

**Comment by titipc** [comment]
Resolved using python3.6
