### ISSUE TITLE
How to send media via yowsup-cli?

### ISSUE THREAD

**Issue by Whomakes** [tgalal/yowsup#2959]
How to send media(image, audio) via yowsup-cli?
yowsup-cli v3.2.0
using:
  yowsup v3.2.3
  consonance v0.1.3-1
  dissononce v0.34.3
  python-axolotl v0.2.3
  cryptography v2.8
  protobuf v3.11.3

i try:
/image send 79037642305 /home/envy/Dropbox/whatsapp/venv/bin/rand_img_000.jpg
/image send 79037642305 ./rand_img_000.jpg

**Debug output**

/image send 79037642305 /home/envy/Dropbox/whatsapp/venv/bin/rand_img_000.jpg
[connected]:E 2020-03-29 13:00:39,706 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 107, in onRecvData
    self.receive(data)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 126, in receive
    if not self.processIqRegistry(node):
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 161, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/protocol_media/layer.py", line 78, in onRequestUploadSuccess
    self.toUpper(ResultRequestUploadIqProtocolEntity.fromProtocolTreeNode(resultNode))
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/interface/interface.py", line 77, in receive
    if not self.processIqRegistry(entity):
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/interface/interface.py", line 56, in processIqRegistry
    successClbk(entity, originalIq)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/demos/cli/layer.py", line 380, in <lambda>
    successFn = lambda successEntity, originalEntity: self.onRequestUploadResult(jid, mediaType, path, successEntity, originalEntity, caption)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/demos/cli/layer.py", line 553, in onRequestUploadResult
    successFn, self.onUploadError, self.onUploadProgress, asynchronous=False)
  File "/home/envy/Dropbox/whatsapp/venv/lib/python3.6/site-packages/yowsup/layers/protocol_media/mediauploader.py", line 18, in __init__
    WARequest.__init__(self)
TypeError: __init__() missing 1 required positional argument: 'config_or_profile'

**Comment by ugurgungezerler** [comment]
not related to the your problem but do you register number successfully?

**Comment by Whomakes** [comment]
yes29.03.2020, 19:28, "ugurgungezerler" <notifications@github.com>:
not related to the your problem but do you register number successfully?

**Comment by Whomakes** [comment]
Anyone can hlp me? if need can pay

**Comment by DeLuca92** [comment]
I need send image too.
Have a demo for this?
I'm thing dev a script to send msg and image together.
LIke read a CSV file and send for this numbers and send images.

**Comment by Whomakes** [comment]
Developers consider it beneath their dignity to answer the question. The last response to this topic was a year ago, before the update. I'm not sure this function works at all. What is written in the instructions for the cli is outdated.

**Comment by DeLuca92** [comment]
Yes.
I try make a simple script to send msg, but is Very difficult :/.
I know have on cli,but I would like create my script

**Comment by Whomakes** [comment]
> Yes.
> I try make a simple script to send msg, but is Very difficult :/.
> I know have on cli,but I would like create my script

i can send text msg, i can reg numbers, but i cant send media

**Comment by DeLuca92** [comment]
But u use cli or create your script?

**Comment by Whomakes** [comment]
both ways

**Comment by DeLuca92** [comment]
Can u send me your script?
Layer and Stack, pls?
I tried use the EchoClient in Demo folder, but dont works.
I'm reading about how send img, but don't have much information :/
@tgalal can u help us?
