### ISSUE TITLE
method "profile_setPicture" don't work

### ISSUE THREAD

**Issue by Marcorele** [tgalal/yowsup#296]
Hi,

since few days, "profile_setPicture" don't work.

No error messages returned but the profile picture stay the same.

Anyone have the same problem?
##

**Comment by ivanbaldo** [comment]
With current Legacy branch code I get this:

BinTreeNodeWriter:	Outgoing
Traceback (most recent call last):
  File "asdf.py", line 469, in <module>
    asdf.YMethodsI.call("profile_setPicture", ('/tmp/asdf.jpg',))
  File "/Yowsup/Interfaces/Interface.py", line 235, in call
    return callback(*params)
  File "/Yowsup/connectionmanager.py", line 694, in sendSetProfilePicture
    return self.sendSetPicture(self.jid, filepath)
  File "/Yowsup/connectionmanager.py", line 710, in sendSetPicture
    self._writeNode(iqNode)
  File "/Yowsup/connectionmanager.py", line 216, in _writeNode
    self.out.write(node)
  File "/Yowsup/ConnectionIO/bintreenode.py", line 293, in write
    self._d("\n%s"%node.toString());
  File "/Yowsup/ConnectionIO/protocoltreenode.py", line 48, in toString
    out+=c.toString(depth + 4);
  File "/Yowsup/ConnectionIO/protocoltreenode.py", line 44, in toString
    out += (" " * (depth + 4)) + self.data.encode("hex") + "\n"
AttributeError: 'bytearray' object has no attribute 'encode'

I changed the bytearray() to str() at line 700 in /Yowsup/connectionmanager.py and it fixes the exception which sends this:
BinTreeNodeWriter:	Outgoing
BinTreeNodeWriter:	
<iq to="xxxxxx@s.whatsapp.net" xmlns="w:profile:picture" type="set" id="set_picture_1">
    <picture type="image">
hexdatahexdatahexdata...
    </picture>
</iq>

And then we get this from WhatsApp server:
BinTreeNodeReader:	Incoming
BinTreeNodeReader:	
<iq type="error" from="xxxxxxx@s.whatsapp.net" id="set_picture_1">
    <error text="not-acceptable" code="406">
    </error>
</iq>

Anyone has a patch readily available?
Thanks.
