### ISSUE TITLE
No Login works

### ISSUE THREAD

**Issue by christopherbentley** [tgalal/yowsup#2977]
[offline]:/L
D 2020-04-22 14:27:11,591 yowsup.layers.network.layer - Created asyncore dispatcher
I 2020-04-22 14:27:11,592 yowsup.layers.network.layer - Connecting to e11.whatsapp.net:443
D 2020-04-22 14:27:11,592 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e11.whatsapp.net', 443))
D 2020-04-22 14:27:11,729 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2020-04-22 14:27:11,730 yowsup.layers.network.layer - Connected
D 2020-04-22 14:27:11,730 yowsup.axolotl.factory - get_manager(username=None)
E 2020-04-22 14:27:11,744 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.7/asyncore.py", line 440, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.7/asyncore.py", line 428, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python3.7/dist-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/usr/local/lib/python3.7/dist-packages/yowsup/layers/network/layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python3.7/dist-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.7/dist-packages/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.7/dist-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup/layers/axolotl/layer_control.py", line 56, in on_connected
    super(AxolotlControlLayer, self).on_connected(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup/layers/axolotl/layer_base.py", line 38, in on_connected
    self.getProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS)[0]
  File "/usr/local/lib/python3.7/dist-packages/yowsup/axolotl/factory.py", line 14, in get_manager
    dbpath = StorageTools.constructPath(username, self.DB)
  File "/usr/local/lib/python3.7/dist-packages/yowsup/common/tools.py", line 89, in constructPath
    path = os.path.join(*path)
  File "/usr/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

D 2020-04-22 14:27:11,744 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-04-22 14:27:11,744 yowsup.layers.network.layer - Disconnected
D 2020-04-22 14:27:11,761 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
general: Disconnected:

**Comment by iamcarlosmunoz** [comment]
Hello friend, I also had that problem, the problem is the credentials of your cell number, now it must contain:
cc, phone and client_static_keypair 

You must also clone the library, since the security policies changed and this user already did
[link](https://github.com/tgalal/yowsup/pull/2924)
