### ISSUE TITLE
Random error:   error: [Errno 111] Connection refused  

### ISSUE THREAD

**Issue by JoelSaldanaMontoya** [tgalal/yowsup#2992]
I am presenting this error frequently and randomly.

Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
I 2020-06-15 08:35:08,539 yowsup.layers.network.layer - Connecting to e2.whatsapp.net:443
E 2020-06-15 08:35:08,675 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 446, in handle_read_event
    self.handle_connect_event()
  File "/usr/lib/python2.7/asyncore.py", line 454, in handle_connect_event
    raise socket.error(err, _strerror(err))
error: [Errno 111] Connection refused

general: Disconnected: 
[offline]:

it is happening randomly with all the whatsapp servers eX.whatsapp.net, registered at: /yowsup/common/constants.py

Please, does the same happen to someone?

**Comment by simenca** [comment]
same issue here

**Comment by JoelSaldanaMontoya** [comment]
> I forced all WSP hosts to one IP 34.194.255.230
> All queue messages were sent.
> 
> I don't understand why it happens with some servers

I'm going to test your solution, I imagine that due to the volume of messages to a single server they could block us.
You let me know if you notice any changes.

Thank you.

**Comment by antoniovalenzuela** [comment]
Few messages (40) are sent from a bash every 10 seconds.

**Comment by antoniovalenzuela** [comment]
34.192.181.12
34.193.38.112
34.194.71.217

 Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.7/asyncore.py", line 419, in handle_read_event
    self.handle_connect_event()
  File "/usr/lib/python3.7/asyncore.py", line 427, in handle_connect_event
    raise OSError(err, _strerror(err))

**Comment by JoelSaldanaMontoya** [comment]
> 34.192.181.12
> 34.193.38.112
> 34.194.71.217
> 
> Traceback (most recent call last):
> File "/usr/lib/python3.7/asyncore.py", line 83, in read
> obj.handle_read_event()
> File "/usr/lib/python3.7/asyncore.py", line 419, in handle_read_event
> self.handle_connect_event()
> File "/usr/lib/python3.7/asyncore.py", line 427, in handle_connect_event
> raise OSError(err, _strerror(err))

Antonio, can you share a traceroute from your server to the IP 34.193.38.112 ?

**Comment by antoniovalenzuela** [comment]
Connectivity problem
Last hop:
**25**  52.93.28.166 (52.93.28.166)  240.341 ms * 52.93.28.138 (52.93.28.138)  127.406 ms

Three ISP testing (two local and one international)

Telnet :443 Connection refused
34.192.181.12
34.193.38.112
34.194.71.217

34.194.255.230 OK!

Joel, estás en facebook?

**Comment by antoniovalenzuela** [comment]
I will use the addresses updated in June 2019

I tried randomly and I have login

https://developers.facebook.com/docs/whatsapp/guides/network-requirements/?locale=es_ES

**Comment by JoelSaldanaMontoya** [comment]
Almost 7 days ago there was an update on the routing information for segment 34.192.0.0/12 on Amazon. There  the WhatsApp servers are.
The time coincides with the beginning of the problem. I believe that it may be asymmetric traffic in international providers by spreading this segment of amazon.

**Comment by CyberSinister** [comment]
Soo. Sorry, kind of a noob. There's no fix yet, right?

**Comment by antoniovalenzuela** [comment]
> Soo. Sorry, kind of a noob. There's no fix yet, right?

Select and test other IP addresses. In my case I made a custom list

https://developers.facebook.com/docs/whatsapp/guides/network-requirements/?locale=es_ES

**Comment by fanishe** [comment]
> Select and test other IP addresses. In my case I made a custom list

Please help us. What should I do with this list of addresses?
I'm noob too :)

**Comment by antoniovalenzuela** [comment]
I share the selected IPs.  Sending works pretty fast.

**Table hosts linux**
157.240.28.55   e1.whatsapp.net e15.whatsapp.net
34.194.255.230  e2.whatsapp.net e16.whatsapp.net
31.13.66.51     e3.whatsapp.net
31.13.71.50     e4.whatsapp.net
31.13.72.48     e5.whatsapp.net
31.13.79.54     e6.whatsapp.net
31.13.85.49     e7.whatsapp.net
31.13.65.50     e8.whatsapp.net
31.13.87.48     e9.whatsapp.net
108.168.254.65  e10.whatsapp.net
31.13.66.51     e11.whatsapp.net
31.13.70.50     e12.whatsapp.net
31.13.83.51     e13.whatsapp.net
31.13.92.48     e14.whatsapp.net

Or modify the hosts on file /yowsup/common/constants.py

**Comment by myckhel** [comment]
**Getting this error on e12**
[offline]:I 2020-06-16 17:32:30,895 yowsup.layers.network.layer - Connecting to e12.whatsapp.net:443
I 2020-06-16 17:32:31,607 yowsup.axolotl.manager - Loaded 812 unsent prekeys
E 2020-06-16 17:32:31,656 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncore.py", line 440, in handle_write_event
    self.handle_connect_event()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncore.py", line 428, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/network/layer.py", line 54, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/noise/layer.py", line 109, in on_auth
    locale_country="US"
  File "/usr/local/lib/python3.7/site-packages/consonance-0.1.3.post1-py3.7.egg/consonance/config/useragent.py", line 58, in __init__
    app_version = AppVersionConfig(app_version)
  File "/usr/local/lib/python3.7/site-packages/consonance-0.1.3.post1-py3.7.egg/consonance/config/appversion.py", line 15, in __init__
    self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
ValueError: too many values to unpack (expected 3)

general: Disconnected: 
[offline]:

**Getting connection refused on other domains**

**Comment by antoniovalenzuela** [comment]
@myckhel  you used fixed hosts?

**Comment by reddington000** [comment]
@antoniovalenzuela Can it depend on our server location whether it can work ? Have you ever look at which servers are used for our phones, maybe we can sniff https requests.

**Comment by myckhel** [comment]
> @myckhel you used fixed hosts?

yes

i commented all hosts except e12 from `/yowsup/common/constants.py`
since i discovered only that host did work for me.

**Comment by antoniovalenzuela** [comment]
> @antoniovalenzuela Can it depend on our server location whether it can work ? Have you ever look at which servers are used for our phones, maybe we can sniff https requests.

It is possible, they should have segmented accesses

Flow from Xiaomi Cel
![image](https://user-images.githubusercontent.com/28113584/84827696-d6dd5f80-aff2-11ea-9e84-670c59f62c1e.png)

e8 = 157.240.204.61
![image](https://user-images.githubusercontent.com/28113584/84827844-11df9300-aff3-11ea-9ff3-09d9cfd6978e.png)

**Comment by reddington000** [comment]
Which program is it ? Can you track your phone HTTPS activity ?

**Comment by antoniovalenzuela** [comment]
> Which program is it ? Can you track your phone HTTPS activity ?

**Ntopng** 
Hotspot network ----tun0-----> raspberry with ntopng -----eth0-----> Internet

Or wireshark sharing adhoc WiFi network

**Comment by Johnprogg** [comment]
Anyone can Provide Detailed Solution for this ?

**Comment by fanishe** [comment]
> Or modify the hosts on file /yowsup/common/constants.py

Should I install again, after changing this file

**Comment by fanishe** [comment]
> Anyone can Provide Detailed Solution for this ?

- You should copy [this text](https://github.com/tgalal/yowsup/issues/2992#issuecomment-644864909)
- to the end of your /etc/hosts


- if Whatsapp will decide to change its IP adresses, you'll go to [that link](https://developers.facebook.com/docs/whatsapp/guides/network-requirements/?locale=es_ES) and copy other 16 ip adresses and test them

enjoy

somebody change in yowsup file `/yowsup/common/constants.py` but I don't know how to change it correct

**Comment by myckhel** [comment]
> > Or modify the hosts on file /yowsup/common/constants.py
> 
> Should I install again, after changing this file

You have to run the install again after changing the file.

**Comment by Johnprogg** [comment]
> > Anyone can Provide Detailed Solution for this ?
> 
> * You should copy [this text](https://github.com/tgalal/yowsup/issues/2992#issuecomment-644864909)
> * to the end of your /etc/hosts
> * if Whatsapp will decide to change its IP adresses, you'll go to [that link](https://developers.facebook.com/docs/whatsapp/guides/network-requirements/?locale=es_ES) and copy other 16 ip adresses and test them
> 
> enjoy
> 
> somebody change in yowsup file `/yowsup/common/constants.py` but I don't know how to change it correct

Thank You Sir

**Comment by Johnprogg** [comment]
> > Anyone can Provide Detailed Solution for this ?
> 
> * You should copy [this text](https://github.com/tgalal/yowsup/issues/2992#issuecomment-644864909)
> * to the end of your /etc/hosts
> * if Whatsapp will decide to change its IP adresses, you'll go to [that link](https://developers.facebook.com/docs/whatsapp/guides/network-requirements/?locale=es_ES) and copy other 16 ip adresses and test them
> 
> enjoy
> 
> somebody change in yowsup file `/yowsup/common/constants.py` but I don't know how to change it correct

Sir is this the right way to add IP's in Constants.py ?
("e1.whatsapp.net e15.whatsapp.net", 157.240.28.55), 
        ("e2.whatsapp.net e16.whatsapp.net" ,34.194.255.230),
        ("e3.whatsapp.net", 31.13.66.51), 
        ("e4.whatsapp.net", 31.13.71.50), 
        ("e5.whatsapp.net", 31.13.72.48), 
        ("e6.whatsapp.net", 31.13.79.54), 
        ("e7.whatsapp.net", 31.13.85.49), 
        ("e8.whatsapp.net", 31.13.65.50), 
        ("e9.whatsapp.net", 31.13.87.48), 
        ("65 e10.whatsapp.net", 108.168.254),
        ("e11.whatsapp.net", 31.13.66.51), 
        ("e12.whatsapp.net", 31.13.70.50), 
        ("e13.whatsapp.net", 31.13.83.51), 
        ("e14.whatsapp.net", 31.13.92.48), 
and whats the end of  /etc/hosts that you are referring to @fanishe  ?

**Comment by Johnprogg** [comment]
Getting this error does i am pasting IP's in the Wrong Way ?


[offline]:/L
I 2020-06-18 05:15:35,310 yowsup.layers.network.layer - Connecting to 65 e10.whatsapp.net:108.168.254
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/demos/cli/layer.py", line 430, in <lambda>
    threading.Thread(target=lambda: self.getLayerInterface(YowNetworkLayer).connect()).start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/layer_interface.py", line 4, in connect
    self._layer.createConnection()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/layer.py", line 92, in createConnection
    self._dispatcher.connect(endpoint)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 27, in connect
    asyncore.dispatcher_with_send.connect(self, host)
  File "/usr/lib/python2.7/asyncore.py", line 347, in connect
    err = self.socket.connect_ex(address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: an integer is required

Please help @fanishe and @antoniovalenzuela

**Comment by fanishe** [comment]
@Johnprogg look at my `/etc/hosts`

![hosts](https://user-images.githubusercontent.com/41025164/84987802-8b899500-b149-11ea-9fc2-ad2dc5782361.png)

I just copy/paste this text
```
157.240.28.55 e1.whatsapp.net e15.whatsapp.net
34.194.255.230 e2.whatsapp.net e16.whatsapp.net
31.13.66.51 e3.whatsapp.net
31.13.71.50 e4.whatsapp.net
31.13.72.48 e5.whatsapp.net
31.13.79.54 e6.whatsapp.net
31.13.85.49 e7.whatsapp.net
31.13.65.50 e8.whatsapp.net
31.13.87.48 e9.whatsapp.net
108.168.254.65 e10.whatsapp.net
31.13.66.51 e11.whatsapp.net
31.13.70.50 e12.whatsapp.net
31.13.83.51 e13.whatsapp.net
31.13.92.48 e14.whatsapp.net
```

**Comment by Johnprogg** [comment]
Hey @fanishe I am Running it in Ubuntu, Btwn does any one knows how to change IP’s in Constants.py correctly?

**Comment by antoniovalenzuela** [comment]
> Connecting to 65 e10.whatsapp.net:108.168.254

Port: 108.168.254 (is 443)

you modified the file constants.py? (I don't recommend changing that file, there are the hosts with port 443)

If you have problems I can help you with a remote connection.

**Comment by reddington000** [comment]
Have you ever tried with a new version of WhatsApp? For example, version 2.20.193.7 . I tried and it never connected, it may explain why we can not connect e type servers. Whatsapp could change something about connection.

**Comment by CyberSinister** [comment]
> Have you ever tried with a new version of WhatsApp? For example, version 2.20.193.7 . I tried and it never connected, it may explain why we can not connect e type servers. Whatsapp could change something about connection.

Oh shit. I think that's why I wasn't connecting. I'm using the latest version of WhatsApp. Download it from the official site and updated the version and hash.

**Comment by myckhel** [comment]
> Hey @fanishe I am Running it in Ubuntu, Btwn does any one knows how to change IP’s in Constants.py correctly?

for me i solved the connection refused issue by following @fanishe instruction

i ran `sudo nano /etc/hosts` and pasted
`57.240.28.55 e1.whatsapp.net e15.whatsapp.net
34.194.255.230 e2.whatsapp.net e16.whatsapp.net
31.13.66.51 e3.whatsapp.net
31.13.71.50 e4.whatsapp.net
31.13.72.48 e5.whatsapp.net
31.13.79.54 e6.whatsapp.net
31.13.85.49 e7.whatsapp.net
31.13.65.50 e8.whatsapp.net
31.13.87.48 e9.whatsapp.net
108.168.254.65 e10.whatsapp.net
31.13.66.51 e11.whatsapp.net
31.13.70.50 e12.whatsapp.net
31.13.83.51 e13.whatsapp.net
31.13.92.48 e14.whatsapp.ne`
at the bottom
saved and quit

and the connections worked fine.

**Comment by fevzican** [comment]
> Have you ever tried with a new version of WhatsApp? For example, version 2.20.193.7 . I tried and it never connected, it may explain why we can not connect e type servers. Whatsapp could change something about connection.

There is fourth digit in version so cosonance library can not handle it, It was set 3 version code part. I fixed it with adding fourth part of Version Code on consonance.

**Comment by ads1230** [comment]
> > Have you ever tried with a new version of WhatsApp? For example, version 2.20.193.7 . I tried and it never connected, it may explain why we can not connect e type servers. Whatsapp could change something about connection.
> 
> There is fourth digit in version so cosonance library can not handle it, It was set 3 version code part. I fixed it with adding fourth part of Version Code on consonance.

Do you have the changes needed?

**Comment by whatsnum** [comment]
I think the number im using for the demo has been blocked
was getting `403` error when tried to login
and when i tried to request code
i got:
  `{"status":"fail","reason":"blocked","login":"xxxxxxxxx"}`

Who else got same problem.

**Comment by myckhel** [comment]
I think the number im using for the demo has been blocked
was getting `403` error when tried to login
and when i tried to request code
i got:
`{"status":"fail","reason":"blocked","login":"xxxxxxxxx"}`

Who else got same problem.

**Comment by antoniovalenzuela** [comment]
> I think the number im using for the demo has been blocked
> was getting `403` error when tried to login
> and when i tried to request code
> i got:
> `{"status":"fail","reason":"blocked","login":"xxxxxxxxx"}`
> 
> Who else got same problem.

Try to activate WhatsApp from a phone and send the debug when the block information appears. The debug is received by android@support.whatsapp.com (they respond and enable it)

Justify the reasons (changing cell phones for example)

**Comment by LuKks** [comment]
`/yowsup/common/constants.py`
```python
class YowConstants:
    DOMAIN       = "s.whatsapp.net"
    ENDPOINTS     = (
        ("157.240.28.55", 443),
        #("34.194.255.230", 443),
        ("31.13.66.51", 443),
        ("31.13.71.50", 443),
        ("31.13.72.48", 443),
        ("31.13.79.54", 443),
        ("31.13.85.49", 443),
        ("31.13.65.50", 443),
        ("31.13.87.48", 443),
        ("108.168.254.65", 443),
        ("31.13.66.51", 443),
        ("31.13.70.50", 443),
        ("31.13.83.51", 443),
        ("31.13.92.48", 443),
        ("157.240.28.55", 443),
        #("34.194.255.230", 443),
        )

    WHATSAPP_SERVER = "s.whatsapp.net"
    WHATSAPP_GROUP_SERVER = "g.us"

    YOWSUP = "yowsup"

    PREVIEW_WIDTH = 64
    PREVIEW_HEIGHT = 64

```

![image](https://user-images.githubusercontent.com/12686176/85389476-d7f41c80-b51d-11ea-8b67-c0e6e117f1b2.png)

I also have updated the env android to the latest version and the `_MD5_CLASSES`.

**Comment by pyweb-wa** [comment]
what about registration? I still have temporarily unavailable

**Comment by com2it** [comment]
> ValueError: too many values to unpack (expected 3)
Have exactly the same error as  myckhel .  Applied everything as LuKks described in his post. (So MD5 was already updates, this was neccassary to request the sms cod,  but when logging in I always get the "ValueError" ?? Does anyone knows how to solve this ?

**Comment by darobles** [comment]
> > Have you ever tried with a new version of WhatsApp? For example, version 2.20.193.7 . I tried and it never connected, it may explain why we can not connect e type servers. Whatsapp could change something about connection.
> 
> There is fourth digit in version so cosonance library can not handle it, It was set 3 version code part. I fixed it with adding fourth part of Version Code on consonance.

I'm facing the same problem, what file did you modified?

**Comment by Johnprogg** [comment]
@fevzican Hey, Which file have your modified to add 4 Digit Version Code?

**Comment by fevzican** [comment]
Okay guys, I will post an Pull Request for new versions.

**Comment by LuKks** [comment]
I did it 3 weeks ago: https://github.com/LuKks/consonance/commit/5fa738102bd6658b38cedcea9a1d0a591e0409a6

**Comment by LuKks** [comment]
Obviously you have to use that repo, replacing like this:

`setup.py`
```python
deps = ['consonance', 'argparse', 'python-axolotl==0.2.2', 'six==1.10', 'appdirs', 'protobuf>=3.6.0']

setup(
    ...,
    dependency_links=[
        'git+https://github.com/LuKks/consonance.git#egg=consonance-0.1.4'
    ],
    ...,
)
```

`tox.ini`
```
consonance==0.1.4
```

Also in the README but it's not strictly need it.

If you really need it I can make a pull request.
