### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by dm-s** [tgalal/yowsup#2996]
when i try to execute this command: "yowsup-cli demos -c /root/.config/yowsup/7950xxxxx24/config.json -s 79xxxxxx389 "test"".
I receive this errors:

yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

I 2020-07-03 07:32:17,676 yowsup.layers.network.layer - Connecting to e10.whatsapp.net:443
I 2020-07-03 07:32:17,787 yowsup.axolotl.manager - Loaded 812 unsent prekeys
E 2020-07-03 07:32:17,789 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.7/asyncore.py", line 440, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.7/asyncore.py", line 428, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/network/layer.py", line 54, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/noise/layer.py", line 109, in on_auth
    locale_country="US"
  File "/usr/local/lib/python3.7/dist-packages/consonance-0.1.3.post1-py3.7.egg/consonance/config/useragent.py", line 58, in __init__
    app_version = AppVersionConfig(app_version)
  File "/usr/local/lib/python3.7/dist-packages/consonance-0.1.3.post1-py3.7.egg/consonance/config/appversion.py", line 15, in __init__
    self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
ValueError: too many values to unpack (expected 3)

Can you kindly help me to solve this. I really cant find out what i'm doing wrong

**Comment by AIMVOIP** [comment]
Hi, I have the same problem.

**Comment by lauriolasw** [comment]
**Same here...**

[offline]:**/L**
I 2020-07-06 12:29:46,363 yowsup.layers.network.layer - Connecting to e5.whatsapp.net:443
I 2020-07-06 12:29:46,674 yowsup.axolotl.manager - Loaded 812 unsent prekeys
E 2020-07-06 12:29:46,681 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python2.7/asyncore.py", line 467, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python2.7/asyncore.py", line 455, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/layer.py", line 54, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer.py", line 109, in on_auth
    locale_country="US"
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.3.post1-py2.7.egg/consonance/config/useragent.py", line 58, in __init__
    app_version = AppVersionConfig(app_version)
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.3.post1-py2.7.egg/consonance/config/appversion.py", line 15, in __init__
    self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
ValueError: too many values to unpack

**ValueError: too many values to unpack**
general: Disconnected:
[offline]:

**Comment by odanielspm** [comment]
I have the same problem, can someone help please?

**Comment by ramyasha-mss** [comment]
Hello, I'm also facing the same issues after installation.  Everything works successfully but upon trying to go online I face that error.  I'm using Ubuntu 18.04.  My environment is here:

yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.9.2
protobuf       v3.12.2

I'm using Python 3.6.9

**Comment by dm-s** [comment]
just solve this problem. Yowsup will work only on this conditions: 
requires:
- python>=2.7,<=3.7
- consonance==0.1.3-1
- python-axolotl==0.2.2
- protobuf>=3.6.0
- six==1.10

i'm used python3 and pip3. if some libraries are newer, you should remove them by "pip3 uninstall" and install proper version. for example: "pip3 install consonance==0.1.3-1 "

also you should patch some files, like in this commit https://github.com/tgalal/yowsup/pull/2924/files

and use newer MD5 and version. 
you should change _VERSION and _MD5_CLASSES  in env/env_android.py to the latest.
on 11.07.2020 they are:
_VERSION = "2.20.134"
_MD5_CLASSES = "PzuZ7EJNcuXEealGEJT6+g=="

**Comment by ramyasha-mss** [comment]
>     * python-axolotl==0.2.2

Hello, I've tried the steps you've mentioned and I might be missing something.  Instead of doing a git pull I simply cloned the repo again to get the latest files.  My environment is also pip3 & python3.  All the steps worked including the registration however when we try to go online, it crashes with the same mentioned error:

E 2020-07-13 08:44:35,656 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.6/asyncore.py", line 441, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.6/asyncore.py", line 429, in handle_connect_event
    self.handle_connect()
  File "/home/ramyasha/projects/yowsup/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/home/ramyasha/projects/yowsup/yowsup/layers/network/layer.py", line 54, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/home/ramyasha/projects/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/ramyasha/projects/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/ramyasha/projects/yowsup/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 3 more times]
  File "/home/ramyasha/projects/yowsup/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/home/ramyasha/projects/yowsup/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/home/ramyasha/projects/yowsup/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/home/ramyasha/projects/yowsup/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/home/ramyasha/projects/yowsup/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/home/ramyasha/projects/yowsup/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/ramyasha/projects/yowsup/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/ramyasha/projects/yowsup/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/home/ramyasha/projects/yowsup/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/home/ramyasha/projects/yowsup/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/home/ramyasha/projects/yowsup/yowsup/layers/noise/layer.py", line 109, in on_auth
    locale_country="US"
  File "/usr/local/lib/python3.6/dist-packages/consonance-0.1.3.post1-py3.6.egg/consonance/config/useragent.py", line 58, in __init__
    app_version = AppVersionConfig(app_version)
  File "/usr/local/lib/python3.6/dist-packages/consonance-0.1.3.post1-py3.6.egg/consonance/config/appversion.py", line 15, in __init__
    self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
ValueError: too many values to unpack (expected 3)

D 2020-07-13 08:44:35,656 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-07-13 08:44:35,656 yowsup.layers.network.layer - Disconnected
D 2020-07-13 08:44:35,672 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
general: Disconnected:

**Comment by dm-s** [comment]
> general: Disconnected:

Check your files, if there are those changes, which are in this pull request. If you have differencies, you should change you files to work yowsup properly. I fixed files manually, in nano.

**Comment by dm-s** [comment]
I'm also cloned repo, but changes, which mentioned in pull request, are absent.

**Comment by ramyasha-mss** [comment]
Can you please mention which files were changed manually? I'm honestly a newbie.  I've got no idea how to do a pull request to copy over my current cloned folders.

**Comment by ramyasha-mss** [comment]
Is there any place I can get the latest release with all the fixes just via a git clone? I'm more of an Infrastructure guy trying to relay our monitoring system via Whatsapp.  This was the only solution I could find that seemed feasible and easy to understand.

**Comment by dm-s** [comment]
> which files were changed manually

Open the link what was mentioned earlier, and you will see which files are changed. you also will see what changed in this files

> Is there any place I can get the latest release

 No Country for Old Men:) No, there is no place, where everything worked out of box. but you can do this place yourself


>  to relay our monitoring system via Whatsapp

Very bad idea. Why? Case developers of whatsapp are homosexyalists (in a bad meaning of the word). they can ban your phone number easily. just google

**Comment by ramyasha-mss** [comment]
Good Evening and thank you for the advice.  I've made some progress, the following environment requirements

yowsup-cli     v3.2.0
yowsup         v3.2.3
consonance     v0.1.3-1
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v2.5
protobuf       v3.0.0

The error regarding ValueError: too many values to unpack has disappeared.  Now I'm simply getting a general disconnect error:

[offline]:/L
D 2020-07-13 20:52:56,188 yowsup.layers.network.layer - Created asyncore dispatcher
I 2020-07-13 20:52:56,188 yowsup.layers.network.layer - Connecting to e7.whatsapp.net:443
D 2020-07-13 20:52:56,188 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e7.whatsapp.net', 443))
D 2020-07-13 20:52:56,398 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2020-07-13 20:52:56,398 yowsup.layers.network.layer - Connected
D 2020-07-13 20:52:56,399 yowsup.axolotl.factory - get_manager(profile_name=XXXXXX05885, username=XXXXXX005885)
D 2020-07-13 20:52:56,400 yowsup.axolotl.manager - Initialized AxolotlManager [username=962778005885, db=/root/.config/yowsup/962778005885/axolotl.db]
D 2020-07-13 20:52:56,400 yowsup.axolotl.manager - level_prekeys(force=False)
D 2020-07-13 20:52:56,406 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2020-07-13 20:52:56,406 yowsup.axolotl.manager - load_unsent_prekeys
I 2020-07-13 20:52:56,410 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2020-07-13 20:52:56,410 yowsup.layers.noise.layer - Received auth event
D 2020-07-13 20:52:56,410 yowsup.env.env - Env not set, setting it to android
D 2020-07-13 20:52:56,410 yowsup.env.env - Current env changed to android 
D 2020-07-13 20:52:56,410 yowsup.layers.noise.layer - Performing handshake [username= 962778005885, passive=True]
D 2020-07-13 20:52:56,411 yowsup.layers.noise.layer - Starting handshake worker
D 2020-07-13 20:52:56,782 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-07-13 20:52:56,783 yowsup.layers.network.layer - Disconnected
D 2020-07-13 20:52:56,796 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
general: Disconnected:

**Comment by dm-s** [comment]
> 
> 
> Good Evening and thank you for the advice. I've made some progress, the following environment requirements

Its very good! If you don't know how to apply patch (general disconnect is because of this) you can download this archive and extract into yowsup git folder with replacement of files. 

https://sf.urlk.org/f/1a0ca91bc7ba45339742/?dl=1

**Comment by ramyasha-mss** [comment]
Dear, thank you so much for the support.  I applied the files and ran the test again, the result is here:

D 2020-07-14 09:32:41,103 yowsup.stacks.yowstack - Initializing stack
D 2020-07-14 09:32:41,104 yowsup.stacks.yowstack - Constructed Network Layer
D 2020-07-14 09:32:41,104 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2020-07-14 09:32:41,105 yowsup.stacks.yowstack - Constructed Noise Layer
D 2020-07-14 09:32:41,105 yowsup.stacks.yowstack - Constructed Coder Layer
D 2020-07-14 09:32:41,105 yowsup.stacks.yowstack - Constructed Logger Layer
D 2020-07-14 09:32:41,105 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f9f8cd81210>
D 2020-07-14 09:32:41,105 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f9f8d990110>
D 2020-07-14 09:32:41,105 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2020-07-14 09:32:41,106 yowsup.stacks.yowstack - Constructed Interface Layer
D 2020-07-14 09:32:41,106 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=9627XXXXXXX))
D 2020-07-14 09:32:41,106 yowsup.layers.network.layer - Created asyncore dispatcher
I 2020-07-14 09:32:41,106 yowsup.layers.network.layer - Connecting to e3.whatsapp.net:443
D 2020-07-14 09:32:41,106 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e3.whatsapp.net', 443))
D 2020-07-14 09:32:41,263 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2020-07-14 09:32:41,264 yowsup.layers.network.layer - Connected
D 2020-07-14 09:32:41,264 yowsup.axolotl.factory - get_manager(profile_name=96277XXXXXX, username=9627XXXXXXX)
D 2020-07-14 09:32:41,265 yowsup.axolotl.manager - Initialized AxolotlManager [username=962778005885, db=/root/.config/yowsup/962778005885/axolotl.db]
D 2020-07-14 09:32:41,265 yowsup.axolotl.manager - level_prekeys(force=False)
D 2020-07-14 09:32:41,268 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2020-07-14 09:32:41,268 yowsup.axolotl.manager - load_unsent_prekeys
I 2020-07-14 09:32:41,270 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2020-07-14 09:32:41,270 yowsup.layers.noise.layer - Received auth event
D 2020-07-14 09:32:41,270 yowsup.env.env - Env not set, setting it to android
D 2020-07-14 09:32:41,270 yowsup.env.env - Current env changed to android 
D 2020-07-14 09:32:41,271 yowsup.layers.noise.layer - Performing handshake [username= 962778005885, passive=True]
D 2020-07-14 09:32:41,271 yowsup.layers.noise.layer - Starting handshake worker
D 2020-07-14 09:32:41,608 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-07-14 09:32:41,609 yowsup.layers.network.layer - Disconnected
D 2020-07-14 09:32:41,609 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

**Comment by dm-s** [comment]
Try to register you number again. I don't know whats going wrong

**Comment by dm-s** [comment]
> Dear, thank you so much

I'm stupid. I give you wrong files. wait, i give you another patch

**Comment by ramyasha-mss** [comment]
Dear, tried the link though nothing to download.  It spins and then times out.

**Comment by dm-s** [comment]
> 
> 
> Dear, tried the link though nothing to download. It spins and then times out.

check you connection. everything good

**Comment by ramyasha-mss** [comment]
Dear. connection is fine.  Downloaded from multiple sources all morning.  Might be our company firewall.  will disconnect and try from hot spot.

**Comment by ramyasha-mss** [comment]
We are almost there.  We've made progress.  Here's the latest error message.  Thank you again so much for your support.

90>
D 2020-07-15 08:15:39,890 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f8fdd1da110>
D 2020-07-15 08:15:39,890 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2020-07-15 08:15:39,891 yowsup.stacks.yowstack - Constructed Interface Layer
D 2020-07-15 08:15:39,891 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=96277XXXXXXX))
D 2020-07-15 08:15:39,891 yowsup.layers.network.layer - Created asyncore dispatcher
I 2020-07-15 08:15:39,891 yowsup.layers.network.layer - Connecting to e9.whatsapp.net:443
D 2020-07-15 08:15:39,891 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e9.whatsapp.net', 443))
D 2020-07-15 08:15:40,098 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2020-07-15 08:15:40,098 yowsup.layers.network.layer - Connected
D 2020-07-15 08:15:40,099 yowsup.axolotl.factory - get_manager(profile_name=96277XXXXXX, username=96277XXXXXXX)
D 2020-07-15 08:15:40,100 yowsup.axolotl.manager - Initialized AxolotlManager [username=962778005885, db=/root/.config/yowsup/96277XXXXXXX/axolotl.db]
D 2020-07-15 08:15:40,100 yowsup.axolotl.manager - level_prekeys(force=False)
D 2020-07-15 08:15:40,103 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2020-07-15 08:15:40,103 yowsup.axolotl.manager - load_unsent_prekeys
I 2020-07-15 08:15:40,106 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2020-07-15 08:15:40,106 yowsup.layers.noise.layer - Received auth event
D 2020-07-15 08:15:40,106 yowsup.env.env - Env not set, setting it to android
D 2020-07-15 08:15:40,106 yowsup.env.env - Current env changed to android 
D 2020-07-15 08:15:40,106 yowsup.layers.noise.layer - Performing handshake [username= 962778005885, passive=True]
D 2020-07-15 08:15:40,106 yowsup.layers.noise.layer - Starting handshake worker
D 2020-07-15 08:15:40,471 yowsup.profile.profile - write_config for 96277XXXXXX
D 2020-07-15 08:15:40,471 yowsup.common.tools - writeProfileData(profile_name=96277XXXXXX, name=config.json, val=[omitted])
D 2020-07-15 08:15:40,471 yowsup.common.tools - Writing /root/.config/yowsup/9627XXXXXX/config.json
D 2020-07-15 08:15:43,848 yowsup.layers.logger.layer - rx:
<failure reason="401" location="atn" />
D 2020-07-15 08:15:43,849 yowsup.layers.network.dispatcher.dispatcher_asyncore - disconnect
D 2020-07-15 08:15:43,849 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-07-15 08:15:43,849 yowsup.layers.network.layer - Disconnected
D 2020-07-15 08:15:43,849 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

**Comment by ramyasha-mss** [comment]
Dear, we've made progress however now facing a new error:

D 2020-07-15 10:15:56,676 yowsup.profile.profile - write_config for 962778005885
D 2020-07-15 10:15:56,677 yowsup.common.tools - writeProfileData(profile_name=962778005885, name=config.json, val=[omitted])
D 2020-07-15 10:15:56,677 yowsup.common.tools - Writing /root/.config/yowsup/962778005885/config.json
D 2020-07-15 10:15:59,676 yowsup.layers.logger.layer - rx:
<failure reason="401" location="nao" />

**Comment by ramyasha-mss** [comment]
Strange enough, when I modified the file /env/env_android and edited the listed values below to these:

    _MD5_CLASSES = "REEvhQbSptYJoQEVnvKo4Q=="
    _VERSION = "2.20.194.17"

I got the error again:

  File "/home/ramyasha/projects/yowsup/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/home/ramyasha/projects/yowsup/yowsup/layers/noise/layer.py", line 109, in on_auth
    locale_country="US"
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.3.post1-py2.7.egg/consonance/config/useragent.py", line 58, in __init__
    app_version = AppVersionConfig(app_version)
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.3.post1-py2.7.egg/consonance/config/appversion.py", line 15, in __init__
    self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
ValueError: too many values to unpack

D 2020-07-15 11:24:25,304 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-07-15 11:24:25,304 yowsup.layers.network.layer - Disconnected
D 2020-07-15 11:24:25,305 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

**Comment by ramyasha-mss** [comment]
Here was my problem at the end.  Instead of:

_MD5_CLASSES = "REEvhQbSptYJoQEVnvKo4Q=="
_VERSION = "2.20.194.17"

It had to be:

_MD5_CLASSES = "REEvhQbSptYJoQEVnvKo4Q=="
_VERSION = "2.20.194"

The version had too many values.  Once I made the edit, everything worked like a charm.  Thanks so much for all your support.  I'm cloning and doing a backup of this VM as a final setup for us.

**Comment by dm-s** [comment]
> 
> 
> Here was my problem at the end. Instead of:
> 
> _MD5_CLASSES = "REEXXXXXXXXXXXXXxXXXX"
> _VERSION = "2.20.194.17"
> 
> It had to be:
> 
> _MD5_CLASSES = "REEXXXXXXXXXXXXXXXXXXX"
> _VERSION = "2.20.194"
> 
> The version had too many values. Once I made the edit, everything worked like a charm. Thanks so much for all your support. I'm cloning and doing a backup of this VM as a final setup for us.

Oh, I'm so happy that everything end good

**Comment by ramyasha-mss** [comment]
Yes, I owe you a huge debt of gratitude so thank you again.  Now I'm experimenting with html tags and adding colors by using this library here, https://github.com/prashnts/hues .  It would be nice to be able to add a "Click Here" and reference a link in the message.  As well as add colors to specific types of messages starting with Info, Warning, or Critical.  It's our job to protect customers from hackers and cybersecurity issues are big.  The more we can keep customers informed and alert the better it is for them and everyone around.

**Comment by wens32** [comment]
> > Cher, merci beaucoup
> 
> Je suis stupide. Je vous donne de mauvais fichiers. attendez, je vous donne un autre patch
> 
> https://sf.urlk.org/f/1a0ca91bc7ba45339742/?dl=1
> 
> il s'agit d'un patch, qui inclut tous les nouveaux fichiers de commit. Devrait marcher. Essayer.
> 
> et installez ceci en utilisant pip:
> 
> * argparse [yowsup-cli]
> * readline [yowsup-cli]
> * oreiller [envoyer des images]
> * tqdm [démo mediasink]
> * demande [démo mediasink]

l'envoi d'image marche pour toi?

**Comment by grunkle-stan** [comment]
> 
> 
> Here was my problem at the end. Instead of:
> 
> _MD5_CLASSES = "REEXXXXXXXXXXXXXxXXXX"
> _VERSION = "2.20.194.17"
> 
> It had to be:
> 
> _MD5_CLASSES = "REEXXXXXXXXXXXXXXXXXXX"
> _VERSION = "2.20.194"
> 
> The version had too many values. Once I made the edit, everything worked like a charm. Thanks so much for all your support. I'm cloning and doing a backup of this VM as a final setup for us.

Many thanks for the solution!

**Comment by huffiewuffie** [comment]
Hi all, sorry for digging up this old thread but I'm still experiencing "ValueError: too many values to unpack (expected 3)".
Dependencies are as follow:
protobuf==3.19.1
appdirs==1.4.4
six==1.10.0
python-axolotl==0.2.2
argparse==1.4.0
consonance==0.1.3.post1
cryptography==3.2.1

I did a python setup.py build; python setup.py install instead of using pip. (Python 3.6.8 on Centos 8)

Any ideas? Thanks.

**Comment by huffiewuffie** [comment]
Upon closer look, managed to resolve the issue. Whatsapp is now expecting 3 dots and 4 values, so I've tweaked consonance/config/appversion.py to cater for this change. Now the error is gone.

**Comment by marlos7** [comment]
There is a project that I tested here in nodejs that is very good! i think yowsup has been discontinued
https://github.com/jonalan7/Hydra-bot
