### ISSUE TITLE
Cannot send  messsge

### ISSUE THREAD

**Issue by M3dS0** [tgalal/yowsup#2998]
Hi,

I've registered and configured the yowsup and this part is working but when I try to send message, the program stuck in this state:
++++++++++++++++++++++++++++
I 2020-07-13 17:14:38,513 yowsup.layers.network.layer - Connecting to e2.whatsapp.net:443
I 2020-07-13 17:14:38,755 yowsup.axolotl.manager - Loaded 812 unsent prekeys
++++++++++++++++++++++++++++

After that I tried --debug, --log-dissononce and --log-consonance
At the end result is :
D 2020-07-13 17:16:49,366 dissononce.processing.impl.handshakestate - MixHash(prologue)
I 2020-07-13 17:16:49,367 dissononce.processing.impl.handshakestate - WriteMessage(payload, message_buffer)
D 2020-07-13 17:16:49,367 dissononce.processing.impl.handshakestate -     Processing token 'e'
D 2020-07-13 17:16:49,367 dissononce.processing.impl.handshakestate -         e=GENERATE_KEYPAIR()
D 2020-07-13 17:16:49,367 dissononce.processing.impl.handshakestate -         message_buffer.append(e.public_key)
D 2020-07-13 17:16:49,368 dissononce.processing.impl.handshakestate -         MixHash(e.public_key)
D 2020-07-13 17:16:49,368 dissononce.processing.impl.handshakestate -     buffer.append(EncryptAndHash(payload))
E 2020-07-13 16:51:28,629 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncore.py", line 422, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.7/site-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 47, in handle_read
    data = self.recv(1024)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncore.py", line 373, in recv
    data = self.socket.recv(buffer_size)
TimeoutError: [Errno 60] Operation timed out

D 2020-07-13 16:51:28,629 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-07-13 16:51:28,629 yowsup.layers.network.layer - Disconnected
D 2020-07-13 16:51:28,630 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

**Comment by M3dS0** [comment]
fixed with:
https://github.com/tgalal/yowsup/pull/2924
