### ISSUE TITLE
Login - Invalid token: 292

### ISSUE THREAD

**Issue by fajarnurprasetyo** [tgalal/yowsup#3000]
[offline]:/L
I 2020-08-10 18:26:13,015 yowsup.layers.network.layer - Connecting to e9.whatsapp.net:443
Auth: Logged in!
[connected]:W 2020-08-10 18:26:14,398 yowsup.layers.axolotl.layer_receive - InvalidMessage or KeyId for 628988378097, going to send a retry
W 2020-08-10 18:26:14,411 yowsup.layers.axolotl.layer_receive - InvalidMessage or KeyId for 628988378097, going to send a retry
W 2020-08-10 18:26:14,421 yowsup.layers.axolotl.layer_receive - InvalidMessage or KeyId for 628988378097, going to send a retry
W 2020-08-10 18:26:14,747 yowsup.layers.protocol_notifications.layer - Unsupported notification type: psa
E 2020-08-10 18:26:14,753 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/data/data/com.termux/files/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 100, in onRecvData
    self.receive(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 103, in receive
    self.toUpper(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/noise/layer.py", line 156, in receive
    self._flush_incoming_buffer()
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/noise/layer.py", line 144, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_receive.py", line 34, in receive
    self.toUpper(protocolTreeNode)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/protocol_notifications/layer.py", line 43, in recvNotification
    self.toLower(ack.toProtocolTreeNode())
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_send.py", line 39, in send
    self.toLower(node)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/axolotl/layer_control.py", line 22, in send
    self.toLower(node)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/logger/layer.py", line 9, in send
    self.toLower(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/coder/layer.py", line 16, in send
    self.write(self.writer.protocolTreeNodeToBytes(data))
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/coder/encoder.py", line 8, in protocolTreeNodeToBytes
    self.writeInternal(node, outBytes)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/coder/encoder.py", line 23, in writeInternal
    self.writeAttributes(node.attributes, data);
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/coder/encoder.py", line 39, in writeAttributes
    self.writeString(value, data, True);
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/coder/encoder.py", line 122, in writeString
    self.writeToken(index, data)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/yowsup/layers/coder/encoder.py", line 113, in writeToken
    raise ValueError("Invalid token: %s" % token)
ValueError: Invalid token: 292

general: Disconnected:
[connected]:

[offline]:

**Comment by fajarnurprasetyo** [comment]
@iacup
