### ISSUE TITLE
AttributeError: 'YowStack' object has no attribute 'setProfile'

### ISSUE THREAD

**Issue by neo3** [tgalal/yowsup#3001]
**Describe the bug**

Failed to try to pass my login number.

**Debug output**

Switch on debug logging and include output along with the error or problem you see. If you are using yowsup-cli, this can be enabled by passing ```---debug```.

Please include any output as code blocks for proper formatting. For example:
```
pi@afccasa:~ $ python /home/pi/afccasa/run.py
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/afccasa/run.py", line 36, in YowThread
    stack.setProfile("14195046403")
AttributeError: 'YowStack' object has no attribute 'setProfile'
```

**Config file**

{
    "__version__": 1,
    "cc": "1",
    "client_static_keypair": "kKOghgbAj0DeGgoCN6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==",
    "edge_routing_info": "CAIxxx==",
    "expid": "KmfAG0ivSxxxxxxxxxxxxx==",
    "fdid": "c213xxxx-14xx-43xx-b0xx-ae0408xxxxxx",
    "id": "ZOdG4wNwVz9Tk2Zdxxxxxxxxxxxx",
    "login": "1419xxxxxxx",
    "mcc": "000",
    "mnc": "000",
    "phone": "1419xxxxxxx",
    "server_static_public": "LKFtqKAASnxIgl89fmxxxxxxxxxxxxxxxxxxxxxxxxxx=",
    "sim_mcc": "000",
    "sim_mnc": "000"
}

**Versions**

yowsup-cli  v3.2.0
yowsup       v3.2.3

**To Reproduce**

python /home/pi/afccasa/run.py

from yowsup.stacks                             import YowStackBuilder
from yowsup.common                             import YowConstants
from yowsup.layers                             import YowLayerEvent
from layer                                     import EchoLayer
from yowsup.layers.coder                       import YowCoderLayer
from yowsup.layers.network                     import YowNetworkLayer
from yowsup.env                                import YowsupEnv

from server                                    import make_app
from sys                                       import argv

import threading, time
import tornado.ioloop, tornado.web

#Uncomment to log
#import logging
#logging.basicConfig(level=logging.DEBUG)

port = 8888

if __name__==  "__main__":

    messages = dict()

    stackBuilder = YowStackBuilder()
    stack = stackBuilder\
	.pushDefaultLayers()\
	.push(EchoLayer)\
	.build()

    stack.setProp("messages", messages)

    app = make_app(stack, messages)

    def YowThread():
        stack.setProfile("1419xxxxxxx")
        stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))          #sending the connect signal
        stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])           #whatsapp server address
        stack.loop(timeout = 0.5, discrete = 0.5 )                                        #this is the program mainloop

    def TornadoThread():
        app.listen(port)
        tornado.ioloop.IOLoop.current().start()

    AppThread = threading.Thread( target=TornadoThread )
    AppThread.daemon = False
    AppThread.start()

    WaThread = threading.Thread( target=YowThread )
    WaThread.daemon = True
    WaThread.start()

**Expected behavior**
Start the bot with the my phone number.

**OS (please complete the following information):**
Raspbian Stretch

**Additional context**
After installing the latest Yowsup packages, I can't start my bot anymore, it shows the error informed on the title. The yowsup-cli still works normally, I can send and receive messages.

Can someone please share a complete run.py file?

**Comment by hossinasaadi** [comment]
try use :
`pip2.7 install  yowsup`
and
`pip2 install  yowsup`

then use python2 or python2.7 like:
```
python2 run.py
python2.7 run.py
```
