### ISSUE TITLE
Problems to Login - ValueError

### ISSUE THREAD

**Issue by Ralphie12** [tgalal/yowsup#3019]
Hello,
I've tried to connect with yowsup on a Raspberry PI to whatsapp. After I get the verification Number and I connect to Whatsapp I tried: 
sudo yowsup-cli demos --yowsup -c 491........
and then
/L
after this following Errors are sign:

yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
I 2020-10-28 13:40:13,757 yowsup.layers.network.layer - Connecting to e10.whatsapp.net:443
I 2020-10-28 13:40:14,124 yowsup.axolotl.manager - Loaded 812 unsent prekeys
E 2020-10-28 13:40:14,131 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.7/asyncore.py", line 440, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.7/asyncore.py", line 428, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/network/layer.py", line 54, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.7/dist-packages/yowsup-3.2.3-py3.7.egg/yowsup/layers/noise/layer.py", line 109, in on_auth
    locale_country="US"
  File "/usr/local/lib/python3.7/dist-packages/consonance-0.1.3.post1-py3.7.egg/consonance/config/useragent.py", line 58, in __init__
    app_version = AppVersionConfig(app_version)
  File "/usr/local/lib/python3.7/dist-packages/consonance-0.1.3.post1-py3.7.egg/consonance/config/appversion.py", line 15, in __init__
    self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
ValueError: too many values to unpack (expected 3)

general: Disconnected: 

I tried the Tutorial in the Thread #2996 
I doesn't work.
Can anyone Help me with this Problem?
Thanks and best regards!

**Comment by catmater** [comment]
Confirm this problem. 
root of this - version WhatsApp now have 3 dots in digit and 4 values!
i'm talking about  _VERSION = "2.20.202**.19**" instead  _VERSION = "2.20.202" in env_android.py.
If change this for 3 values (VERSION = "2.20.202") - error is gone, but token now are incorrect (bad token error in login)!
Please fix it...

**Comment by Ralphie12** [comment]
Dear catmater,
THX for the fast Answer.
I've got version 2.20.198 in env_android.py in _VERSION.
I've got the same Problem.
Have I rebuilt (python3 setup.py --install) after take this Chamge?
Thank's a Lot

**Comment by Ralphie12** [comment]
I've rebuilt it and everthing goes!
THX a LOT

**Comment by catmater** [comment]
And you can send message ? 
i can't, no messages sending:
D 2020-11-01 13:26:11,605 yowsup.axolotl.manager - Initialized AxolotlManager [username=7xxxxxxxxxx, db=/root/.config/yowsup/7xxxxxxxxxx/axolotl.db]
D 2020-11-01 13:26:11,606 yowsup.axolotl.manager - level_prekeys(force=False)
D 2020-11-01 13:26:11,609 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2020-11-01 13:26:11,609 yowsup.axolotl.manager - load_unsent_prekeys
I 2020-11-01 13:26:11,610 yowsup.axolotl.manager - Loaded 812 unsent prekeys
D 2020-11-01 13:26:11,611 yowsup.layers.noise.layer - Received auth event
D 2020-11-01 13:26:11,611 yowsup.layers.noise.layer - Performing handshake [username= 7xxxxxxxxxx, passive=True]
D 2020-11-01 13:26:11,611 yowsup.layers.noise.layer - Starting handshake worker
**D 2020-11-01 13:26:12,010 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2020-11-01 13:26:12,010 yowsup.layers.network.layer - Disconnected
D 2020-11-01 13:26:12,011 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False**

**Comment by blackconcerto** [comment]
> And you can send message ?
> i can't, no messages sending:
> D 2020-11-01 13:26:11,605 yowsup.axolotl.manager - Initialized AxolotlManager [username=7xxxxxxxxxx, db=/root/.config/yowsup/7xxxxxxxxxx/axolotl.db]
> D 2020-11-01 13:26:11,606 yowsup.axolotl.manager - level_prekeys(force=False)
> D 2020-11-01 13:26:11,609 yowsup.axolotl.manager - len(pending_prekeys) = 812
> D 2020-11-01 13:26:11,609 yowsup.axolotl.manager - load_unsent_prekeys
> I 2020-11-01 13:26:11,610 yowsup.axolotl.manager - Loaded 812 unsent prekeys
> D 2020-11-01 13:26:11,611 yowsup.layers.noise.layer - Received auth event
> D 2020-11-01 13:26:11,611 yowsup.layers.noise.layer - Performing handshake [username= 7xxxxxxxxxx, passive=True]
> D 2020-11-01 13:26:11,611 yowsup.layers.noise.layer - Starting handshake worker
> **D 2020-11-01 13:26:12,010 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close D 2020-11-01 13:26:12,010 yowsup.layers.network.layer - Disconnected D 2020-11-01 13:26:12,011 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False**

same result, can not send message although i have modified the constant.py with the ips.

**Comment by endroemily** [comment]
> And you can send message ?
> i can't, no messages sending:
> D 2020-11-01 13:26:11,605 yowsup.axolotl.manager - Initialized AxolotlManager [username=7xxxxxxxxxx, db=/root/.config/yowsup/7xxxxxxxxxx/axolotl.db]
> D 2020-11-01 13:26:11,606 yowsup.axolotl.manager - level_prekeys(force=False)
> D 2020-11-01 13:26:11,609 yowsup.axolotl.manager - len(pending_prekeys) = 812
> D 2020-11-01 13:26:11,609 yowsup.axolotl.manager - load_unsent_prekeys
> I 2020-11-01 13:26:11,610 yowsup.axolotl.manager - Loaded 812 unsent prekeys
> D 2020-11-01 13:26:11,611 yowsup.layers.noise.layer - Received auth event
> D 2020-11-01 13:26:11,611 yowsup.layers.noise.layer - Performing handshake [username= 7xxxxxxxxxx, passive=True]
> D 2020-11-01 13:26:11,611 yowsup.layers.noise.layer - Starting handshake worker
> **D 2020-11-01 13:26:12,010 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close D 2020-11-01 13:26:12,010 yowsup.layers.network.layer - Disconnected D 2020-11-01 13:26:12,011 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False**

@catmater @blackconcerto did you fix this?
