### ISSUE TITLE
I can't Login with the phone number!

### ISSUE THREAD

**Issue by kos5c23123** [tgalal/yowsup#3020]
I can registration about my phone, but I can't send a message and log in.

it is my error message:
```
[offline]:/L
I 2020-11-04 19:17:01,448 yowsup.layers.network.layer - Connecting to e13.whatsapp.net:443
I 2020-11-04 19:17:01,806 yowsup.axolotl.manager - Loaded 812 unsent prekeys
E 2020-11-04 19:17:01,807 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/Users/user/.platformio/python3/lib/python3.8/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/Users/user/.platformio/python3/lib/python3.8/asyncore.py", line 438, in handle_write_event
    self.handle_connect_event()
  File "/Users/user/.platformio/python3/lib/python3.8/asyncore.py", line 426, in handle_connect_event
    self.handle_connect()
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/network/layer.py", line 54, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 3 more times]
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/auth/layer_authentication.py", line 33, in on_connected
    self.broadcastEvent(
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/noise/layer.py", line 98, in on_auth
    useragent=UserAgentConfig(
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/consonance-0.1.3.post1-py3.8.egg/consonance/config/useragent.py", line 58, in __init__
    app_version = AppVersionConfig(app_version)
  File "/Users/user/.platformio/penv/lib/python3.8/site-packages/consonance-0.1.3.post1-py3.8.egg/consonance/config/appversion.py", line 15, in __init__
    self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
ValueError: too many values to unpack (expected 3)

general: Disconnected:
```

**Comment by alfikr** [comment]
> I can registration about my phone, but I can't send a message and log in.
> 
> it is my error message:
> 
> ```
> [offline]:/L
> I 2020-11-04 19:17:01,448 yowsup.layers.network.layer - Connecting to e13.whatsapp.net:443
> I 2020-11-04 19:17:01,806 yowsup.axolotl.manager - Loaded 812 unsent prekeys
> E 2020-11-04 19:17:01,807 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
>   File "/Users/user/.platformio/python3/lib/python3.8/asyncore.py", line 91, in write
>     obj.handle_write_event()
>   File "/Users/user/.platformio/python3/lib/python3.8/asyncore.py", line 438, in handle_write_event
>     self.handle_connect_event()
>   File "/Users/user/.platformio/python3/lib/python3.8/asyncore.py", line 426, in handle_connect_event
>     self.handle_connect()
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
>     self.connectionCallbacks.onConnected()
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/network/layer.py", line 54, in onConnected
>     self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 94, in emitEvent
>     self.__upper.emitEvent(yowLayerEvent)
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 94, in emitEvent
>     self.__upper.emitEvent(yowLayerEvent)
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 94, in emitEvent
>     self.__upper.emitEvent(yowLayerEvent)
>   [Previous line repeated 3 more times]
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 88, in emitEvent
>     if self.__upper and not self.__upper.onEvent(yowLayerEvent):
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 212, in onEvent
>     stopEvent = stopEvent or s.onEvent(yowLayerEvent)
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 109, in onEvent
>     return self.event_callbacks[eventName](yowLayerEvent)
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/auth/layer_authentication.py", line 33, in on_connected
>     self.broadcastEvent(
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
>     self.broadcastEvent(yowLayerEvent)
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
>     self.__lower.broadcastEvent(yowLayerEvent)
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
>     self.__lower.broadcastEvent(yowLayerEvent)
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
>     self.__lower.broadcastEvent(yowLayerEvent)
>   [Previous line repeated 1 more time]
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 98, in broadcastEvent
>     if self.__lower and not self.__lower.onEvent(yowLayerEvent):
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 109, in onEvent
>     return self.event_callbacks[eventName](yowLayerEvent)
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/noise/layer.py", line 98, in on_auth
>     useragent=UserAgentConfig(
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/consonance-0.1.3.post1-py3.8.egg/consonance/config/useragent.py", line 58, in __init__
>     app_version = AppVersionConfig(app_version)
>   File "/Users/user/.platformio/penv/lib/python3.8/site-packages/consonance-0.1.3.post1-py3.8.egg/consonance/config/appversion.py", line 15, in __init__
>     self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
> ValueError: too many values to unpack (expected 3)
> 
> general: Disconnected:
> ```

i have this problem too. any suggestion ?

**Comment by ben221199** [comment]
Your error `ValueError: too many values to unpack (expected 3)` says the code expects 3 values.
However, if you are looking to your `env_android.y`, the value of `_VERSION` will likely contain a version number with 4 parts. Remove the last part and it will likely work.
