### ISSUE TITLE
General disconnect problem

### ISSUE THREAD

**Issue by devops35** [tgalal/yowsup#3038]
There has been a problem with the connection for a few hours. I am getting a general disconnected error. How can I solve this problem?

**Comment by ironbat1** [comment]
Same here all numbers got banned in last few hours. Any Solutions yet ?

**Comment by endroemily** [comment]
Same issue here. numbers not banned, we can't connect to whatsapp with yowsup

**Comment by endroemily** [comment]
This has happened before: 
#2924
i hope someone can fix, i'm trying

**Comment by emrecanozkok** [comment]
![image](https://user-images.githubusercontent.com/8539564/103590088-0192f500-4efe-11eb-80d7-e440ef6cd2b6.png)

**Comment by kylonrizoki** [comment]
i am trying and waiting

**Comment by lauriolasw** [comment]
Hello, same problem here

**Comment by lauriolasw** [comment]
My number is not banned, I tried to go back in WA and register was fine,  but then back to Yowsup result still "general: Disconnected" at login

**Comment by toobadsosad** [comment]
mine just stuck on 

2021-01-05 08:51:16,975 yowsup.layers.network.layer - Connecting to e7.whatsapp.net:443
2021-01-05 08:51:16,975 yowsup.layers.network.layer - Connecting to e6.whatsapp.net:443

ping not ok.. internet ok

**Comment by mamsak** [comment]
I have updated my private yowsup and it works like a charm.
Just contact with me at mowsan7 [at] gmail.com

**Comment by Whomakes** [comment]
> Я обновил свой личный yowsup, и он работает как шарм.
> Просто свяжитесь со мной по адресу mowsan7 [at] gmail.com



> mowsan7

I already wrote to you

**Comment by rk77a** [comment]
> I have updated my private yowsup and it works like a charm.
> Just contact with me at mowsan7 [at] gmail.com

I have also wrote to you

**Comment by dongbuze** [comment]
> > Я обновил свой личный yowsup, и он работает как шарм.
> > Просто свяжитесь со мной по адресу mowsan7 [at] gmail.com
> 
> > mowsan7
> 
> I already wrote to you

I have also wrote to you

**Comment by dongbuze** [comment]
> I have updated my private yowsup and it works like a charm.
> Just contact with me at mowsan7 [at] gmail.com
I have also wrote to you

**Comment by bahtiarp** [comment]
> I have updated my private yowsup and it works like a charm.
> Just contact with me at mowsan7 [at] gmail.com

I have wrote.
thanks.

**Comment by bahtiarp** [comment]
![image](https://user-images.githubusercontent.com/3410804/103610898-b60b3600-4f53-11eb-8fbd-6f7ffd6b9abc.png)

yowsup/layers/noise/layer.py

works!

**Comment by ironbat1** [comment]
that worked for me bahtiarp thanks!

**Comment by toobadsosad** [comment]
solution works.. thanks bahtiarp

**Comment by endroemily** [comment]
> ![image](https://user-images.githubusercontent.com/3410804/103610898-b60b3600-4f53-11eb-8fbd-6f7ffd6b9abc.png)
> 
> yowsup/layers/noise/layer.py
> 
> works!

thanks works for me

**Comment by bizzu** [comment]
> ![image](https://user-images.githubusercontent.com/3410804/103610898-b60b3600-4f53-11eb-8fbd-6f7ffd6b9abc.png)
> 
> yowsup/layers/noise/layer.py
> 
> works!

Thanks bahtiarp for the fix, working well here also !
If you don't mind, how have you been able to identify the issue ?

**Comment by bahtiarp** [comment]
> > ![image](https://user-images.githubusercontent.com/3410804/103610898-b60b3600-4f53-11eb-8fbd-6f7ffd6b9abc.png)
> > yowsup/layers/noise/layer.py
> > works!
> 
> Thanks bahtiarp for the fix, working well here also !
> If you don't mind, how have you been able to identify the issue ?

same pattern with: https://github.com/tgalal/yowsup/issues/2922

**Comment by tomaskutaj** [comment]
Should we also update the token dictionary? Do you know how to update those?

**Comment by bizzu** [comment]
> Should we also update the token dictionary? Do you know how to update those?

That is what I am wondering too.
the commit from iacup solving #2922 (which is #2924), included numerous other changes, so it would be interesting to know the process of checking possible changes on  the token dictionary as well as the bytes of test_decode function. Unfortunately I have no idea on it...

**Comment by ironbat1** [comment]
Yes, I am so concerned about it too,
"same pattern with: #2922"

so how would iacup found out these solution, he once mentioned that he reversed engineered WhatsApp APK to find out protocol,
Does anyone have any idea how can we manage to do such a job ?


> > Should we also update the token dictionary? Do you know how to update those?
> 
> That is what I am wondering too.
> the commit from iacup solving #2922 (which is #2924), included numerous other changes, so it would be interesting to know the process of checking possible changes on the token dictionary as well as the bytes of test_decode function. Unfortunately I have no idea on it...

**Comment by ersinayaz** [comment]
> Yes, I am so concerned about it too,
> "same pattern with: #2922"
> 
> so how would iacup found out these solution, he once mentioned that he reversed engineered WhatsApp APK to find out protocol,
> Does anyone have any idea how can we manage to do such a job ?
> 
> > > Should we also update the token dictionary? Do you know how to update those?
> > 
> > 
> > That is what I am wondering too.
> > the commit from iacup solving #2922 (which is #2924), included numerous other changes, so it would be interesting to know the process of checking possible changes on the token dictionary as well as the bytes of test_decode function. Unfortunately I have no idea on it...

possible with **kaios**.

**Comment by ben221199** [comment]
So, we are already in WhatsApp Protocol 4.0?

**Comment by mthushara** [comment]
Thank you very much "bahtiarp" for sharing the fix.
It saved us a lot.

Wish you good luck !

Thushara

**Comment by the-jojo-jj** [comment]
> > > ![image](https://user-images.githubusercontent.com/3410804/103610898-b60b3600-4f53-11eb-8fbd-6f7ffd6b9abc.png)
> > > yowsup/layers/noise/layer.py
> > > works!
> > 
> > 
> > Thanks bahtiarp for the fix, working well here also !
> > If you don't mind, how have you been able to identify the issue ?
> 
> same pattern with: #2922

it works for me too, thanks bahtiarp!!!!

**Comment by antoniovalenzuela** [comment]
I can connect, but I am not receiving group messages.

/message send xxxxxxxxxxx-1591065550 test
Sent: 1610031918-14

There is the sending ID, but the messages do not reach the group.

Do this also happen to someone else?

**Comment by DaveFH** [comment]
> ![image](https://user-images.githubusercontent.com/3410804/103610898-b60b3600-4f53-11eb-8fbd-6f7ffd6b9abc.png)
> 
> yowsup/layers/noise/layer.py
> 
> works!

Also works for me & my yowsup....

**Comment by ironbat1** [comment]
I am having difficulties after registering the number,
on my first login I faced this error,

"<failure reason="403" location="atn" />
general: Login Failed, reason: 403"

And number get blocked,

I think it is happened last year and iacup/yowsup#2 commit solved it,
So do you know what could be the reason behind that also ?

**Comment by MrNadimi** [comment]
@bahtiarp Not worked for me 
Code:
`class YowNoiseLayer(YowLayer):
    DEFAULT_PUSHNAME = "yowsup"
    #Edited by mr Mrnadimi
    #HEADER = b'WA\x02\x01'
    HEADER = b'WA\x04\x00'
    EDGE_HEADER = b'ED\x00\x01'
    EVENT_HANDSHAKE_FAILED = "org.whatsapp.yowsup.layer.noise.event.handshake_failed"

    def __init__(self):
        super(YowNoiseLayer, self).__init__()
        self._wa_noiseprotocol = WANoiseProtocol(
            #2, 1, protocol_state_callbacks=self._on_protocol_state_changed
            #Edited by mrnadimi
            4, 0, protocol_state_callbacks=self._on_protocol_state_changed
        )  # type: WANoiseProtocol

        self._handshake_worker = None
        self._stream = BlockingQueueSegmentedStream()  # type: BlockingQueueSegmentedStream
        self._read_buffer = bytearray()
        self._flush_lock = threading.Lock()
        self._incoming_segments_queue = Queue.Queue()
        self._profile = None
        self._rs = None
 `

Error:
`[offline]:/L
I 2021-01-24 07:15:14,809 yowsup.layers.network.layer - Connecting to e12.whatsapp.net:443
I 2021-01-24 07:15:15,194 yowsup.axolotl.manager - Loaded 812 unsent prekeys
E 2021-01-24 07:15:15,194 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.8/asyncore.py", line 438, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.8/asyncore.py", line 426, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/network/layer.py", line 54, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/auth/layer_authentication.py", line 33, in on_connected
    self.broadcastEvent(
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.8/dist-packages/yowsup-3.2.3-py3.8.egg/yowsup/layers/noise/layer.py", line 102, in on_auth
    useragent=UserAgentConfig(
  File "/usr/local/lib/python3.8/dist-packages/consonance-0.1.3.post1-py3.8.egg/consonance/config/useragent.py", line 58, in __init__
    app_version = AppVersionConfig(app_version)
  File "/usr/local/lib/python3.8/dist-packages/consonance-0.1.3.post1-py3.8.egg/consonance/config/appversion.py", line 15, in __init__
    self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
ValueError: too many values to unpack (expected 3)

general: Disconnected: 
[offline]:
[offline]:
`

**Comment by MrNadimi** [comment]
@bahtiarp Not worked for me
Code:
![Screenshot from 2021-01-24 07-27-53](https://user-images.githubusercontent.com/57061923/105623947-c5282a00-5e15-11eb-892c-aa6ea989c980.png)

Console error:
![Screenshot from 2021-01-24 07-28-14](https://user-images.githubusercontent.com/57061923/105623955-d2ddaf80-5e15-11eb-98ce-484428bfdffe.png)

**Comment by ben221199** [comment]
@MrNadimi In your `env_android.py`, go to version and remove the last version part. So instead of `1.2.3.4`, you only need `1.2.3`.

**Comment by pizdjuk** [comment]
Tried all fixes, but cannot register a number....

**Comment by pizdjuk** [comment]
sorry. Works now. Only needed to apply small python script from other issue to detect MD5 summ

**Comment by kaisar945** [comment]
> ![image](https://user-images.githubusercontent.com/3410804/103610898-b60b3600-4f53-11eb-8fbd-6f7ffd6b9abc.png)
> 
> yowsup/layers/noise/layer.py
> 
> works!

very good, this is magic !

**Comment by sjoerdj** [comment]
Version 5 (5.0, 5.2) on the noise layer is mentioned as the solution to issue #3185, so I updated yowsup/layers/noise/layer.py as follows:

![image](https://user-images.githubusercontent.com/47718586/208474924-0839dbe4-823a-4c49-9590-d1024deea56f.png)

I did also the [decoder.py update](https://github.com/bizzu/yowsup/commit/a02d85c5412c61306628544958728d06974b749b) to deal with token 247.

Now I experience two different errors, depending on which phone number I use:
- Phone number 1: failure reason="401" location="frc"
- Phone number 2: Exception("Sent keys were not accepted")

Does someone have a clue what is going on here?

**Comment by RabbitCreed** [comment]
> Version 5 (5.0, 5.2) on the noise layer is mentioned as the solution to issue #3185, so I updated yowsup/layers/noise/layer.py as follows:
> 
> ![image](https://user-images.githubusercontent.com/47718586/208474924-0839dbe4-823a-4c49-9590-d1024deea56f.png)
> 
> Unfortunately, it did not do the trick. What else do I need to do to make it work?


Same problems，same modifications，but it not work. Are there any other that need to be modified? Thanks for a lot.
 @bahtiarp

**Comment by sjoerdj** [comment]
What eventually worked for me:

1. Updating yowsup/layers/noise/layer.py as follows:

![image](https://user-images.githubusercontent.com/47718586/208474924-0839dbe4-823a-4c49-9590-d1024deea56f.png)

2. [Updating /yowsup/layers/coder/decoder.py and /yowsup/layers/coder/encoder.py](https://github.com/tgalal/yowsup/issues/3090#issuecomment-924989153) to deal with token 247.

3. Re-registering my phone number
