### ISSUE TITLE
onConnected     self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))

### ISSUE THREAD

**Issue by kasru** [tgalal/yowsup#3049]
After registration.
call yowsup-cli demos -y --config myphone
and have error:
```
$ yowsup-cli demos -y --config myphone
/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/dissononce/dh/x25519/x25519.py:1: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography.hazmat.primitives.asymmetric import x25519
W 2021-02-08 14:03:14,580 yowsup.config.manager - load_path couldn't find the path: myphone
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
I 2021-02-08 14:03:16,589 yowsup.layers.network.layer - Connecting to e15.whatsapp.net:443
I 2021-02-08 14:03:16,736 yowsup.axolotl.manager - Loaded 812 unsent prekeys
E 2021-02-08 14:03:16,743 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.5/asyncore.py", line 441, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.5/asyncore.py", line 429, in handle_connect_event
    self.handle_connect()
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/network/layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/yowsup/layers/noise/layer.py", line 95, in on_auth
    locale_country="US"
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/consonance/config/useragent.py", line 58, in __init__
    app_version = AppVersionConfig(app_version)
  File "/home/kas/work/telegram_bridge/venv/lib/python3.5/site-packages/consonance/config/appversion.py", line 15, in __init__
    self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
ValueError: too many values to unpack (expected 3)

general: Disconnected: 
[offline]:
```

**Comment by ben221199** [comment]
Please all stop making duplicate issues that are already solved => https://github.com/tgalal/yowsup/issues/2996#issuecomment-658744919

**Comment by softmaxchile** [comment]
You must modify the File: /yowsup/env/env_android.py and replace with:

_MD5_CLASSES = "johGawnfJx5vOGIePP3qKw =="
_VERSION = "2.21.3" 

and sudo python3 setup.py install

**Comment by kasru** [comment]
```
_MD5_CLASSES = "johGawnfJx5vOGIePP3qKw =="
_VERSION = "2.21.3"
```
Where get manual for getting values that variables?

**Comment by softmaxchile** [comment]
In this link there is information: https://github.com/tgalal/yowsup/issues/2996#issuecomment-658744919
