### ISSUE TITLE
 Unsupported ib node: <ib receipt="type">

### ISSUE THREAD

**Issue by Asatecore** [tgalal/yowsup#3073]
Hello,

./yowsup-cli demos -c /home/centos/.config/yowsup/XXXXXXXXXXXX/ -s XXYYYYYYYYYY "test"
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

I 2021-05-19 18:16:58,618 yowsup.layers.network.layer - Connecting to e16.whatsapp.net:443
I 2021-05-19 18:16:58,651 yowsup.axolotl.manager - Loaded 812 unsent prekeys
W 2021-05-19 18:16:58,883 yowsup.layers.protocol_ib.layer - Unsupported ib node: <ib receipt="type">
  <gcm>
    <deny>
      0x0805080c
    </deny>
  </gcm>
</ib>
E 2021-05-19 18:16:58,885 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/home/centos/yowsup-master/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/home/centos/yowsup-master/yowsup/layers/network/layer.py", line 107, in onRecvData
    self.receive(data)
  File "/home/centos/yowsup-master/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/home/centos/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/centos/yowsup-master/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/home/centos/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/centos/yowsup-master/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/home/centos/yowsup-master/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/home/centos/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/centos/yowsup-master/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/home/centos/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/centos/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/centos/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/centos/yowsup-master/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/home/centos/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/centos/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/centos/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/home/centos/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/centos/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/centos/yowsup-master/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/home/centos/yowsup-master/yowsup/layers/protocol_ib/layer.py", line 25, in recvIb
    self.toUpper(DirtyIbProtocolEntity.fromProtocolTreeNode(node))
  File "/home/centos/yowsup-master/yowsup/layers/protocol_ib/protocolentities/dirty_ib.py", line 37, in fromProtocolTreeNode
    entity.setProps(dirtyChild["timestamp"], dirtyChild["type"])
  File "/home/centos/yowsup-master/yowsup/layers/protocol_ib/protocolentities/dirty_ib.py", line 15, in setProps
    self.timestamp = int(timestamp)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Regards,

**Comment by Asatecore** [comment]
I follow this thread #2713 , but nothing happens

**Comment by tgalal** [comment]
Fixed.
