### ISSUE TITLE
old_version error registration requet sms

### ISSUE THREAD

**Issue by Jnavarro1314** [tgalal/yowsup#3077]
**Describe the bug**

I have tried to register but it always marks old_version
I already changed the version of env_android.py and the problem still continues

**Debug output**

status: fail
reason: old_version
Login: 52xxxxxxxxxx

env_android.py

_MD5_CLASSES = "/QhoCBMppKpKQumhTC8kcQ=="
_VERSION = "2.19.244"

**Comment by mprataps** [comment]
After change you need to again setup build and install

python setup.py build

python setup.py install

**Comment by Jnavarro1314** [comment]
the same error still appears

status: fail
reason: old_version
Login: 52xxxxxxxxxx

**Comment by Josue-g28** [comment]
I have the same problem, could you solve it?

**Comment by Jnavarro1314** [comment]
I have been able to fix the registry problem by changing the version of /home/pi/yowsup/yowsup/env/env_android.py
_MD5_CLASSES = "/ QhoCBMppKpKQumhTC8kcQ =="
  _VERSION = "2.19.244"

but now when using / L I get another error

pi@raspberry:~/yowsup $ yowsup-cli demos --yowsup --config config
yowsup-cli  v3.2.0
yowsup      v3.2.3


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
I 2021-05-31 11:53:12,027 yowsup.layers.network.layer - Connecting to e15.whatsapp.net:443
I 2021-05-31 11:53:12,117 yowsup.axolotl.manager - Loaded 812 unsent prekeys
E 2021-05-31 11:53:12,118 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python2.7/asyncore.py", line 467, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python2.7/asyncore.py", line 455, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/network/layer.py", line 54, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup-3.2.3-py2.7.egg/yowsup/layers/noise/layer.py", line 109, in on_auth
    locale_country="US"
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.3.post1-py2.7.egg/consonance/config/useragent.py", line 58, in __init__
    app_version = AppVersionConfig(app_version)
  File "/usr/local/lib/python2.7/dist-packages/consonance-0.1.3.post1-py2.7.egg/consonance/config/appversion.py", line 15, in __init__
    self._primary, self._secondary, self._tertiary = map(lambda v:int(v), dissected)
ValueError: too many values to unpack

general: Disconnected: 
[offline]:
[offline]:

**Comment by phpjoker** [comment]
Use:
`_MD5_CLASSES = "FNU4RbThIt/2TmAQraquEA==;"`
`_VERSION = "2.21.8.18"`

**Comment by phpjoker** [comment]
_VERSION = "2.21.8"

**Comment by AleksB27** [comment]
> _VERSION = "2.21.8"

status: b'fail'
reason: b'bad_token'

**Comment by halper03** [comment]
> > Use:
> > `_MD5_CLASSES = "FNU4RbThIt/2TmAQraquEA==;"`
> > `_VERSION = "2.21.8.18"`
> 
> same mistake

Same mistake.

**Comment by alirezadigi** [comment]
> Use:
> `_MD5_CLASSES = "FNU4RbThIt/2TmAQraquEA==;"`
> `_VERSION = "2.21.8.18"`

It worked!Thanks!
How did you find them?
Could you please explain?

**Comment by gbrunmayr** [comment]
> > Use:
> > `_MD5_CLASSES = "FNU4RbThIt/2TmAQraquEA==;"`
> > `_VERSION = "2.21.8.18"`
> 
> It worked!Thanks! How did you find them? Could you please explain?

Hi,
you can download the most recent WhatsApp.apk from https://www.whatsapp.com/android
Then install pyaxmlparser

pip install pyaxmlparser

With dexMD5.py you should get the recent Version ID and the regarding MD5 Class:
 
python dexMD5.py WhatsApp.apk

Version: 2.21.24.16
ClassesDex: zX+KrpW5CBQf1YB5GeEUag==

**Comment by tgalal** [comment]
Fixed.
