### ISSUE TITLE
AttributeError: Raw on registration 

### ISSUE THREAD

**Issue by emezeta** [tgalal/yowsup#3079]
This is ubuntu bionic 18.04 runing both python2.7 
yowsup-cli  v3.2.0
yowsup      v3.2.3

my installation steps:
```
$ git clone git@github.com:tgalal/yowsup.git
$ cd yowsup
$ su -c python setup.py install
```
install ends with no errors

my envs:

```
$ export CONFIG_PHONE='598xxxxxxxx'
$ export CONFIG_CC='598'
$ export CONFIG_MCC='471'
$ export CONFIG_MNC='01'
```

my yow commands

```
$ yowsup-cli config -d --config-phone $CONFIG_PHONE --config-cc $CONFIG_CC --config-mcc $CONFIG_MCC --config-mnc $CONFIG_MNC

D 2021-06-03 17:17:06,460 yowsup.config.manager - Detecting config for username=598xxxxxxxx, dir=/home/dosmilun/.config/yowsup/598xxxxxxxx/
D 2021-06-03 17:17:06,460 yowsup.config.manager - Trying /home/dosmilun/.config/yowsup/598xxxxxxxx/config.json
D 2021-06-03 17:17:06,461 yowsup.config.manager - Trying /home/dosmilun/.config/yowsup/598xxxxxxxx/config.yo
D 2021-06-03 17:17:06,461 yowsup.config.manager - load_path(path=/home/dosmilun/.config/yowsup/598xxxxxxxx/config.yo)
D 2021-06-03 17:17:06,461 yowsup.config.manager - Detected config type: keyval
D 2021-06-03 17:17:06,461 yowsup.config.manager - Opening config for reading
D 2021-06-03 17:17:06,461 yowsup.config.manager - Loading config
```

no erros here.

and then

```                        
$ yowsup-cli registration -r sms -d --config-phone $CONFIG_PHONE --config-cc $CONFIG_CC --config-mcc $CONFIG_MCC --config-mnc $CONFIG_MNC 

D 2021-06-03 17:22:16,611 yowsup.config.manager - Detecting config for username=598xxxxxxxx, dir=/home/dosmilun/.config/yowsup/598xxxxxxxx/
D 2021-06-03 17:22:16,611 yowsup.config.manager - Trying /home/dosmilun/.config/yowsup/598xxxxxxxx/config.json
D 2021-06-03 17:22:16,611 yowsup.config.manager - Trying /home/dosmilun/.config/yowsup/598xxxxxxxx/config.yo
D 2021-06-03 17:22:16,611 yowsup.config.manager - load_path(path=/home/dosmilun/.config/yowsup/598xxxxxxxx/config.yo)
D 2021-06-03 17:22:16,611 yowsup.config.manager - Detected config type: keyval
D 2021-06-03 17:22:16,611 yowsup.config.manager - Opening config for reading
D 2021-06-03 17:22:16,611 yowsup.config.manager - Loading config
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


D 2021-06-03 17:22:16,673 yowsup.axolotl.factory - get_manager(username=598xxxxxxxx)
D 2021-06-03 17:22:16,673 yowsup.axolotl.manager - Initialized AxolotlManager [username=598xxxxxxxx, db=/home/dosmilun/.config/yowsup/598xxxxxxxx/axolotl.db]
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 679, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 350, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/local/bin/yowsup-cli", line 361, in handleRequestCode
    codeReq = WACodeRequest(method, config)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/registration/coderequest.py", line 15, in __init__
    super(WACodeRequest,self).__init__(config)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/common/http/warequest.py", line 71, in __init__
    config.client_static_keypair = WATools.generateKeyPair()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/common/tools.py", line 70, in generateKeyPair
    return KeyPair.generate()
  File "/usr/local/lib/python2.7/dist-packages/consonance/structs/keypair.py", line 36, in generate
    keypair = X25519DH().generate_keypair()
  File "build/bdist.linux-x86_64/egg/dissononce/dh/x25519/x25519.py", line 37, in generate_keypair
  File "/usr/lib/python2.7/dist-packages/enum/__init__.py", line 390, in __getattr__
    raise AttributeError(name)
AttributeError: Raw
```

I'm obviously doing something wrong but I don't know what it is

**Comment by tgalal** [comment]
Please try with python3+ and re-open if the issue persists.
