### ISSUE TITLE
Trying to install it on CentOS

### ISSUE THREAD

**Issue by DangerD1024** [tgalal/yowsup#3091]
I have CentOS 7 on X64 server.
```
pip3 install yowsup
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting yowsup
  Using cached https://files.pythonhosted.org/packages/f2/ad/6348a2eb3abacee64164f8f45bfde8941db11d0ffd37558f8638ed293910/yowsup-3.2.3-py3-none-any.whl
Collecting argparse (from yowsup)
  Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting appdirs (from yowsup)
  Using cached https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl
Collecting six==1.10 (from yowsup)
  Using cached https://files.pythonhosted.org/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl
Collecting protobuf>=3.6.0 (from yowsup)
  Using cached https://files.pythonhosted.org/packages/53/4e/e2db88d0bb0bda6a879eea62fddbaf813719ce3770d458bc5580512d9c95/protobuf-3.17.3-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
Collecting python-axolotl==0.2.2 (from yowsup)
  Using cached https://files.pythonhosted.org/packages/47/21/01946b935bc2c05a1b59b2a4747a63841cfc4b797452e94799d7a0305807/python_axolotl-0.2.2-py3-none-any.whl
Collecting consonance==0.1.2 (from yowsup)
  Using cached https://files.pythonhosted.org/packages/da/27/5ffff77320cf947da7d7b90959bc0a5ef08bddb8eb27bc057204f7f9db06/consonance-0.1.2-py3-none-any.whl
Requirement already satisfied: python-axolotl-curve25519>=0.4.1 in /usr/local/lib64/python3.6/site-packages/python_axolotl_curve25519-0.4.1-py3.6-linux-x86_64.egg (from python-axolotl==0.2.2->yowsup)
Collecting cryptography (from python-axolotl==0.2.2->yowsup)
  Using cached https://files.pythonhosted.org/packages/cc/98/8a258ab4787e6f835d350639792527d2eb7946ff9fc0caca9c3f4cf5dcfe/cryptography-3.4.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5u7dcupx/cryptography/setup.py", line 152, in <module>
        rust_extensions=rust_extensions,
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 457, in __init__
        for k, v in attrs.items()
      File "/usr/lib64/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 831, in finalize_options
        ep(self)
      File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 852, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-5u7dcupx/cryptography/.eggs/cffi-1.14.6-py3.6-linux-x86_64.egg/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-build-5u7dcupx/cryptography/.eggs/cffi-1.14.6-py3.6-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-build-5u7dcupx/cryptography/.eggs/cffi-1.14.6-py3.6-linux-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/_cffi_src/build_openssl.py", line 119, in <module>
        extra_link_args=extra_link_args(compiler_type()),
      File "/tmp/pip-build-5u7dcupx/cryptography/src/_cffi_src/utils.py", line 59, in build_ffi_for_binding
        extra_link_args=extra_link_args,
      File "/tmp/pip-build-5u7dcupx/cryptography/src/_cffi_src/utils.py", line 73, in build_ffi
        ffi = FFI()
      File "/tmp/pip-build-5u7dcupx/cryptography/.eggs/cffi-1.14.6-py3.6-linux-x86_64.egg/cffi/api.py", line 48, in __init__
        import _cffi_backend as backend
    ImportError: /tmp/pip-build-5u7dcupx/cryptography/.eggs/cffi-1.14.6-py3.6-linux-x86_64.egg/_cffi_backend.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

        =============================DEBUG ASSISTANCE=============================
        If you are seeing a compilation error please try the following steps to
        successfully install cryptography:
        1) Upgrade to the latest pip and try again. This will fix errors for most
           users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        2) Read https://cryptography.io/en/latest/installation.html for specific
           instructions for your platform.
        3) Check our frequently asked questions for more information:
           https://cryptography.io/en/latest/faq.html
        4) Ensure you have a recent Rust toolchain installed:
           https://cryptography.io/en/latest/installation.html#rust
        5) If you are experiencing issues with Rust for *this release only* you may
           set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
        =============================DEBUG ASSISTANCE=============================


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5u7dcupx/cryptography/
```
I need to make bot that will create groups and add few contacts to it and read/send messages to that group, are that possible via cli? I need to integrate it somehow to website (php)

**Comment by huffiewuffie** [comment]
Have you tried as what the debug message suggested?
=============================DEBUG ASSISTANCE=============================
        1) Upgrade to the latest pip and try again. This will fix errors for most
           users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        2) Read https://cryptography.io/en/latest/installation.html for specific
           instructions for your platform.
        3) Check our frequently asked questions for more information:
           https://cryptography.io/en/latest/faq.html
        4) Ensure you have a recent Rust toolchain installed:
           https://cryptography.io/en/latest/installation.html#rust
        5) If you are experiencing issues with Rust for *this release only* you may
           set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.

**Comment by tgalal** [comment]
For consultancy related to your own application please refer to the [README](https://github.com/tgalal/yowsup).
