### ISSUE TITLE
General problem. Login and subscribe issue

### ISSUE THREAD

**Issue by jackRowscal** [tgalal/yowsup#3093]
Hello. Is there a general problem in Yowsup? 
I think the protocol has changed.
'/presence subcribe' not working
Is everyone the same?

`[connected]:E 2021-09-18 22:39:42,167 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/home/yowsup/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/home/yowsup/yowsup/layers/network/layer.py", line 109, in onRecvData
    self.receive(data)
  File "/home/yowsup/yowsup/layers/network/layer.py", line 112, in receive
    self.toUpper(data)
  File "/home/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/yowsup/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/home/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/yowsup/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/home/yowsup/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/home/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/yowsup/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/home/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/yowsup/yowsup/layers/axolotl/layer_control.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/home/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/yowsup/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/yowsup/yowsup/layers/axolotl/layer_receive.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/home/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/yowsup/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/yowsup/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/home/yowsup/yowsup/layers/auth/layer_authentication.py", line 67, in handleStreamError
    raise NotImplementedError("Unhandled stream:error node:\n%s" % node)
NotImplementedError: Unhandled stream:error node:
<stream:error code="503" />`

**Comment by jackRowscal** [comment]
There is no general problem. The problem is caused by numbers.

**Comment by halper03** [comment]
Hello, @jackRowscal
i am having this problem too.
I tested many numbers.
all the same.

Can you help?
Thank you
