### ISSUE TITLE
First Login Bans Phone Number

### ISSUE THREAD

**Issue by ironbat1** [tgalal/yowsup#3095]
After successful registration, on the first login to a new phone number, I see a new error like the one on the below,
Then on the second trial, I see that number is already get banned,

is there anyone who knows why this is happening, 
I used to face this issue but it is happening more often than before,

Thanks in advance,

------------------------------------------------------------------------------------------------------------

D 2021-09-22 13:10:34,410 yowsup.layers.logger.layer - rx:
<stream:error code="precise_rx_timestamps_mask" />
E 2021-09-22 13:10:34,502 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/root/yowsup/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/root/yowsup/yowsup/layers/network/layer.py", line 107, in onRecvData
    self.receive(data)
  File "/root/yowsup/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/root/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/root/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/root/yowsup/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/root/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/root/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/root/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup/yowsup/layers/axolotl/layer_control.py", line 32, in receive
    self.toUpper(protocolTreeNode)
  File "/root/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/root/yowsup/yowsup/layers/axolotl/layer_receive.py", line 35, in receive
    self.toUpper(protocolTreeNode)
  File "/root/yowsup/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/root/yowsup/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/root/yowsup/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/root/yowsup/yowsup/layers/auth/layer_authentication.py", line 67, in handleStreamError
    raise NotImplementedError("Unhandled stream:error node:\n%s" % node)
NotImplementedError: Unhandled stream:error node:
<stream:error code="precise_rx_timestamps_mask" />

**Comment by gughovh** [comment]
Hi @ironbat1, did you solve the problem?

**Comment by ironbat1** [comment]
Hi @gughovh , No I didn't,
 I am not sure what really happened but It occurs less often right now.

**Comment by gughovh** [comment]
I still have this error ...
What version of WhatsApp and Noise protocol do you use?
