### ISSUE TITLE
Invalid padding bytes

### ISSUE THREAD

**Issue by Whomakes** [tgalal/yowsup#3096]
Does anyone know how to solve this problem?

yowsup v3.2.3
  consonance v0.1.3-1
  dissononce v0.34.3
  python-axolotl v0.2.3
  cryptography v3.4.7
  protobuf v4.0.0rc2

Location: vll
Creation: 1631894303
Props: 26
t: 1632404341

Auth: Logged in!
[connected]:E 2021-09-24 02:38:40,060 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.6/asyncore.py", line 427, in handle_read_event
    self.handle_read()
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 52, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 111, in onRecvData
    self.receive(data)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 114, in receive
    self.toUpper(data)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 181, in receive
    self._flush_incoming_buffer()
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 169, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_control.py", line 37, in receive
    self.toUpper(protocolTreeNode)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 39, in receive
    self.onMessage(protocolTreeNode)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 55, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 69, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 126, in handleWhisperMessage
    enc.getVersion() == 2)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/yowsup/axolotl/manager.py", line 190, in decrypt_msg
    plaintext = self._get_session_cipher(senderid).decryptMsg(msg)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/axolotl/sessioncipher.py", line 74, in decryptMsg
    plaintext = self.decryptWithSessionRecord(sessionRecord, ciphertext)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/axolotl/sessioncipher.py", line 106, in decryptWithSessionRecord
    plaintext = self.decryptWithSessionState(sessionState, cipherText)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/axolotl/sessioncipher.py", line 144, in decryptWithSessionState
    plaintext = self.getPlaintext(messageVersion, messageKeys, ciphertextMessage.getBody())
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/axolotl/sessioncipher.py", line 198, in getPlaintext
    return cipher.decrypt(cipherText)
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/axolotl/sessioncipher.py", line 223, in decrypt
    return unpadder.update(decrypted) + unpadder.finalize()
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/cryptography/hazmat/primitives/padding.py", line 157, in finalize
    self._buffer, self.block_size, lib.Cryptography_check_pkcs7_padding
  File "/home/asus/Dropbox/whatsapp/venv_asus/lib/python3.6/site-packages/cryptography/hazmat/primitives/padding.py", line 98, in _byte_unpadding_check
    raise ValueError("Invalid padding bytes.")
ValueError: Invalid padding bytes.

**Comment by emrecanozkok** [comment]
did you try to get rooted phone config.json to log in in your local ?.

**Comment by Whomakes** [comment]
No, its in yowsup registered number

**Comment by phpjoker** [comment]
if not valid:
        return buffer_
        #raise ValueError("Invalid padding bytes.")
