### ISSUE TITLE
yowsup.common.http.warequest - b'{"login":"505xxxxxxxx","param":"backup_token","reason":"bad_param","status":"fail"}\

### ISSUE THREAD

**Issue by ronaldoats** [tgalal/yowsup#3120]
./yowsup-cli  registration --requestcode sms --config-phone 505xxxxxxxx --config-cc 505 --config-mcc 710 --config-mnc 30 --debug
D 2022-02-11 13:32:03,667 yowsup.config.manager - load(path_or_profile_name=505xxxxxxxx, profile_only=False)
D 2022-02-11 13:32:03,667 yowsup.config.manager - _load_path(path=505xxxxxxxx)
D 2022-02-11 13:32:03,667 yowsup.config.manager - _load_path couldn't find the path: 505xxxxxxxx
D 2022-02-11 13:32:03,667 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2022-02-11 13:32:03,667 yowsup.config.manager - Detecting config for profile=505xxxxxxxx, dir=/Users/xxxxxxxx/Library/Application Support/yowsup/505xxxxxxxx
D 2022-02-11 13:32:03,667 yowsup.config.manager - Trying /Users/xxxxxxxx/Library/Application Support/yowsup/505xxxxxxxx/config.yo
D 2022-02-11 13:32:03,667 yowsup.config.manager - Trying /Users/xxxxxxxx/Library/Application Support/yowsup/505xxxxxxxx/config.json
E 2022-02-11 13:32:03,667 yowsup.config.manager - Could not find a config for profile=505xxxxxxxx, paths checked: 505xxxxxxxx:/Users/xxxxxxxx/Library/Application Support/yowsup/505xxxxxxxx/config.yo:/Users/xxxxxxxx/Library/Application Support/yowsup/505xxxxxxxx/config.json
D 2022-02-11 13:32:03,667 yowsup.profile.profile - Constructed Profile(profile_name=505xxxxxxxx)
yowsup-cli     v3.2.1
yowsup         v3.3.0
consonance     v0.1.5
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v36.0.1
protobuf       v4.0.0rc2

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

W 2022-02-11 13:32:03,736 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
D 2022-02-11 13:32:03,736 yowsup.profile.profile - Constructed Profile(profile_name=505xxxxxxxx)
D 2022-02-11 13:32:03,736 yowsup.axolotl.factory - get_manager(profile_name=505xxxxxxxx, username=505xxxxxxxx)
D 2022-02-11 13:32:03,739 yowsup.axolotl.manager - Initialized AxolotlManager [username=505xxxxxxxx, db=/Users/xxxxxxxx/Library/Application Support/yowsup/505xxxxxxxx/axolotl.db]
D 2022-02-11 13:32:03,739 yowsup.axolotl.manager - load_latest_signed_prekey
D 2022-02-11 13:32:03,740 yowsup.env.env - Env not set, setting it to android
D 2022-02-11 13:32:03,740 yowsup.env.env - Current env changed to android
D 2022-02-11 13:32:03,740 yowsup.common.http.warequest - send(parser=None, encrypt=True, preview=False)
D 2022-02-11 13:32:03,740 yowsup.common.http.warequest - sendGetRequest(parser=None, encrypt_params=True, preview=False)
D 2022-02-11 13:32:03,740 yowsup.common.http.warequest - Encrypting parameters
D 2022-02-11 13:32:03,740 yowsup.common.http.warequest - pre-encrypt (encoded) parameters =
cc=505&in=xxxxxxxx&lg=en&lc=GB&mistyped=6&authkey=coYeBz1e709MPWpsJdeO3EBucOVcbcypi4aSEYsn0Sw&e_regid=PRd0hQ&e_keytype=BQ&e_ident=Am%5f%2d%5f%2dCSAtxkDYkqaOaCvm3TnJ2eh3ThBcqiyT8culc&e_skey_id=AAAA&e_skey_val=2cMEZFHKNw6NGBs%5foTvvYxb%5fUXW9kp52WVcfDSrZSRY&e_skey_sig=R2WtCiTdy%2dBksBB23HSOGDgcgRHMXJiu%2dWCCq6J0vsZUqLhAqdZcZ5yIwp1bc86ikmsJfGC5vZV0VPUMby2xAQ&fdid=0eb57f54%2dbeb8%2d4617%2d93e5%2d31e0dff9759e&expid=h94imeb2Rcm6q6YkQCkloQ&network_radio_type=1&simnum=1&hasinrc=1&pid=5052&rc=0&mcc=710&mnc=030&sim_mcc=000&sim_mnc=000&method=sms&reason=&token=AgYBJ89gPSWy9TPhd4tJ62tOH%2fU%3d&hasav=1&id=%04%11%d0Fi%23u%a7%d6%a2RL%ca%05F%a6%a9%b3%25%e5
D 2022-02-11 13:32:03,741 yowsup.common.http.warequest - sendRequest(host=v.whatsapp.net, port=443, path=/v2/code, headers={'User-Agent': 'WhatsApp/2.21.21 Android/8.0.0 Device/samsung-star2lte', 'Accept': 'text/json'}, params=[('ENC', b'XvFyK5kogMCaMn29h5c1lev6VG1ErQLksyOw6NKNuHcIJUjwv/HfVc3iM3ONx1ifeLlKiJfaAO6Qb4dOTzSPtCKVFBGVUpHs2+pqZqBSrhQRqPKcwty409SU8kG7JWKNZNsPfhpnZ8oGFT0h3kHWXhvUvrW+J18skcCTQSAICnx7kO1XriiAoW0mitV/6+NswGa+bm2Weobh5IJDQy6vMOsW2ivajtYuMeF9agUazNaLOkhBc3zgSIKNa3xHLvLvADQ8Q0snO0AhU6i7LjGXcfAvFfCrCq/IkuXrcqGk7cgypWgUoU3ygV8xGUoLAiTuBxzlcKbv7SxMlAHuD9hlS2XEwlwUUi1pXAuneGD0DVgiRcs/E89K4Jx3w2n/iT+drcPfvmZTXY1yxGRnQ6wa7xHjCkyfd3qLtumHiiomwvprK2pYmakjCEkpdykUc2wAQFYLxdelPshsMLH96dqr2VSk1OODDJtYjdNC72NeYkT0qEgYlpFUNuLwHS0ShIAdvgmy6H0rsrTALzQY6vEV/PNIXZdSI5b0LPP6jDDXEeGWLflt0WnXpc2HsZIfokpnlWrEUGb7ckNf20qY90nkba/+TtYeNljrecQW708MrjMH11MLYzThmpVz9Kmgn73xKqYvSlAo7+REyo+wFBpYsyeDUU402WDWcXhKHBubQ2N0wOVW1bVaYBK6+q1/iAZmhfG97VJHdBEBsyAwLPrmjjyWFODaC0ZF358fXz0PY+RHus8fLLMIvo0RMoBGME0PtUjxXJjrAe3TJoDLN9TN1EAlBzmzGvdLY8NlNQmPPeCkcLvxpVBCgkEx3AdyO+qdbHlCV+3cx7C+Jx/5fGjLqfTK3xyOX8E9V6dTTiPb/BYjKJefpE2Lgmfx+dvY252dYexMjQ6HpI1yZep8iScNiwhoN9VKSHFc')], reqType=GET, preview=False)
D 2022-02-11 13:32:03,741 yowsup.common.http.warequest - Opening connection to v.whatsapp.net
D 2022-02-11 13:32:03,748 yowsup.common.http.warequest - Sending GET request to /v2/code?ENC=XvFyK5kogMCaMn29h5c1lev6VG1ErQLksyOw6NKNuHcIJUjwv%2fHfVc3iM3ONx1ifeLlKiJfaAO6Qb4dOTzSPtCKVFBGVUpHs2%2bpqZqBSrhQRqPKcwty409SU8kG7JWKNZNsPfhpnZ8oGFT0h3kHWXhvUvrW%2bJ18skcCTQSAICnx7kO1XriiAoW0mitV%2f6%2bNswGa%2bbm2Weobh5IJDQy6vMOsW2ivajtYuMeF9agUazNaLOkhBc3zgSIKNa3xHLvLvADQ8Q0snO0AhU6i7LjGXcfAvFfCrCq%2fIkuXrcqGk7cgypWgUoU3ygV8xGUoLAiTuBxzlcKbv7SxMlAHuD9hlS2XEwlwUUi1pXAuneGD0DVgiRcs%2fE89K4Jx3w2n%2fiT%2bdrcPfvmZTXY1yxGRnQ6wa7xHjCkyfd3qLtumHiiomwvprK2pYmakjCEkpdykUc2wAQFYLxdelPshsMLH96dqr2VSk1OODDJtYjdNC72NeYkT0qEgYlpFUNuLwHS0ShIAdvgmy6H0rsrTALzQY6vEV%2fPNIXZdSI5b0LPP6jDDXEeGWLflt0WnXpc2HsZIfokpnlWrEUGb7ckNf20qY90nkba%2f%2bTtYeNljrecQW708MrjMH11MLYzThmpVz9Kmgn73xKqYvSlAo7%2bREyo%2bwFBpYsyeDUU402WDWcXhKHBubQ2N0wOVW1bVaYBK6%2bq1%2fiAZmhfG97VJHdBEBsyAwLPrmjjyWFODaC0ZF358fXz0PY%2bRHus8fLLMIvo0RMoBGME0PtUjxXJjrAe3TJoDLN9TN1EAlBzmzGvdLY8NlNQmPPeCkcLvxpVBCgkEx3AdyO%2bqdbHlCV%2b3cx7C%2bJx%2f5fGjLqfTK3xyOX8E9V6dTTiPb%2fBYjKJefpE2Lgmfx%2bdvY252dYexMjQ6HpI1yZep8iScNiwhoN9VKSHFc
I 2022-02-11 13:32:04,139 yowsup.common.http.warequest - b'{"login":"505xxxxxxxx","param":"backup_token","reason":"bad_param","status":"fail"}\n'
status: b'fail'
reason: b'bad_param'
param: b'backup_token'
login: b'505xxxxxxxx'

**Comment by gpcortes** [comment]
I'm having the same error

**Comment by ronaldoats** [comment]
it seems that whatsapp is identifying unofficial clients and does not allow them to work

**Comment by M-Mortaz** [comment]
same here

**Comment by M-Mortaz** [comment]
same here

**Comment by ElieTabet** [comment]
Same

**Comment by aavestan** [comment]
same here

**Comment by lianyu6569** [comment]
same here, Does anyone know what is the reason for this error?Is it necessary to modify the generation function of the token?

**Comment by lianyu6569** [comment]
look here "https://github.com/tgalal/yowsup/pull/3127/files" 
Change the android device into an ios device and modify it step by step according to the modification in the file.Then you can register an account

**Comment by mrjoebudi** [comment]
> look here "https://github.com/tgalal/yowsup/pull/3127/files" Change the android device into an ios device and modify it step by step according to the modification in the file.Then you can register an account

that's right !!!! success for me, thank's

**Comment by pietpit** [comment]
Hello,
thank you so much for the files, i modified the files and create a new file for the ios.
Then i register an account, it works well, so far so good...

But when i will send an message to my mobilphone, i get the following issue and it doesn`t work...

```
Traceback (most recent call last):
  File "yowsup-cli", line 722, in <module>
    if not parser.process():
  File "yowsup-cli", line 610, in process
    self.startSendClient()
  File "yowsup-cli", line 649, in startSendClient
    from yowsup.demos import sendclient
  File "/opt/yowsup-master/yowsup/demos/sendclient/__init__.py", line 1, in <module>
    from .stack import YowsupSendStack
  File "/opt/yowsup-master/yowsup/demos/sendclient/stack.py", line 1, in <module>
    from yowsup.stacks import  YowStackBuilder
  File "/opt/yowsup-master/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/opt/yowsup-master/yowsup/stacks/yowstack.py", line 4, in <module>
    from yowsup.layers.noise.layer import YowNoiseLayer
  File "/opt/yowsup-master/yowsup/layers/noise/layer.py", line 1, in <module>
    from yowsup.layers.noise.workers.handshake import WANoiseProtocolHandshakeWorker
  File "/opt/yowsup-master/yowsup/layers/noise/workers/handshake.py", line 1, in <module>
    from consonance.protocol import WANoiseProtocol
  File "/usr/local/lib/python3.5/dist-packages/consonance-0.1.5-py3.5.egg/consonance/protocol.py", line 2, in <module>
    from .handshake import WAHandshake
  File "/usr/local/lib/python3.5/dist-packages/consonance-0.1.5-py3.5.egg/consonance/handshake.py", line 22, in <module>
    from .proto import wa20_pb2
  File "/usr/local/lib/python3.5/dist-packages/consonance-0.1.5-py3.5.egg/consonance/proto/wa20_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```
who can help me...
Greetings
Pit

**Comment by leonardocxavier** [comment]
Some error: 
root@Natalia:/yowsup# python3 yowsup-cli registration -r sms -c /etc/ac/wp.conf -E android -d
D 2022-06-23 13:08:50,418 yowsup.env.env - Current env changed to android
D 2022-06-23 13:08:50,420 yowsup.config.manager - load(path_or_profile_name=/etc/ac/wp.conf, profile_only=False)
D 2022-06-23 13:08:50,420 yowsup.config.manager - _load_path(path=/etc/ac/wp.conf)
D 2022-06-23 13:08:50,421 yowsup.config.manager - Trying auto detect config type by parsing
D 2022-06-23 13:08:50,422 yowsup.config.manager - Trying to parse as keyval
D 2022-06-23 13:08:50,422 yowsup.config.manager - Successfully detected keyval as config type for /etc/ac/wp.conf
D 2022-06-23 13:08:50,422 yowsup.config.manager - Detected config type: keyval
D 2022-06-23 13:08:50,423 yowsup.config.manager - Opening config for reading
D 2022-06-23 13:08:50,423 yowsup.config.manager - Loading config
D 2022-06-23 13:08:50,424 yowsup.config.manager - load(path_or_profile_name=5581xxxxxxxx, profile_only=True)
D 2022-06-23 13:08:50,424 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2022-06-23 13:08:50,424 yowsup.config.manager - Detecting config for profile=5581xxxxxxxx, dir=/root/.config/yowsup/558185674444
D 2022-06-23 13:08:50,425 yowsup.config.manager - Trying /root/.config/yowsup/5581xxxxxxxx/config.yo
D 2022-06-23 13:08:50,425 yowsup.config.manager - Trying /root/.config/yowsup/5581xxxxxxxx/config.json
E 2022-06-23 13:08:50,425 yowsup.config.manager - Could not find a config for profile=5581xxxxxxxx, paths checked: /root/.config/yowsup/558185674444/config.yo:/root/.config/yowsup/5581xxxxxxxx/config.json
D 2022-06-23 13:08:50,425 yowsup.profile.profile - Constructed Profile(profile_name=5581xxxxxxxx)
yowsup-cli     v3.2.1
yowsup         v3.3.0
consonance     v0.1.5
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v37.0.2
protobuf       v3.20.0


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


W 2022-06-23 13:08:50,927 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
D 2022-06-23 13:08:50,928 yowsup.profile.profile - Constructed Profile(profile_name=5581xxxxxxxx)
D 2022-06-23 13:08:50,928 yowsup.axolotl.factory - get_manager(profile_name=558185674444, username=5581xxxxxxxx)
D 2022-06-23 13:08:50,954 yowsup.axolotl.manager - Initialized AxolotlManager [username=5581xxxxxxxx, db=/root/.config/yowsup/5581xxxxxxxx/axolotl.db]
D 2022-06-23 13:08:51,001 yowsup.axolotl.manager - load_latest_signed_prekey
D 2022-06-23 13:08:51,006 yowsup.common.http.warequest - send(parser=None, encrypt=True, preview=False)
D 2022-06-23 13:08:51,006 yowsup.common.http.warequest - sendGetRequest(parser=None, encrypt_params=True, preview=False)
D 2022-06-23 13:08:51,007 yowsup.common.http.warequest - Encrypting parameters
D 2022-06-23 13:08:51,010 yowsup.common.http.warequest - pre-encrypt (encoded) parameters =
cc=55&in=5581xxxxxxxx&lg=en&lc=GB&mistyped=6&authkey=vXim%5fkHn9lzz%2d40AbC%2dTHK4j8YPRS1NRgpo0Uwhwqnc&e_regid=F54b7g&e_keytype=BQ&e_ident=LBIWJmnXFov7pbbVoDjmirbvqxerWkSiIcHhEQENXT8&e_skey_id=AAAA&e_skey_val=gVOehAoLyooZvOG%2d%2d1PMUkaKxlTGIniFiq7ETZcSzio&e_skey_sig=CYiJTnP4kjsQ1Sg%2dUAFwPPPvuS4asFB5ZQkwLibFYTU7NGb1G4%5fetvwi%5f3sR%2dAlMpzHJ2LQ6GaCTX6bFahp7Aw&fdid=93ca39e3%2d24d6%2d46a4%2db71a%2da162f0ea0f70&expid=4e0P%2daMpTdWEuF2%5fYoQMmQ&network_radio_type=1&simnum=1&hasinrc=1&pid=9795&rc=0&mcc=000&mnc=000&sim_mcc=000&sim_mnc=000&method=sms&reason=&token=2b9uaF%2bC3lVdOJWqrEVAjlzCgdI%3d&hasav=1&id=ni%e8%86u%9eE%f0e%c6%22%d6%86%f5%a8%a9%f2%91%fb%1e
D 2022-06-23 13:08:51,017 yowsup.common.http.warequest - sendRequest(host=v.whatsapp.net, port=443, path=/v2/code, headers={'User-Agent': 'WhatsApp/2.22.13.75 Android/8.0.0 Device/samsung-star2lte', 'Accept': 'text/json'}, params=[('ENC', b'BCJmqDCGWPZd6E88tUmFt3KS0tSi+YEMWVcecWhrahe69KflDRp3VLo3sdvQVv0pdDBCF9bRHAe6LOUVOKC/3F4xO3xAsmBtbghgO7qp2bcbK25Cx0ybV7/u4k6tooYOmgIb+JIZZz6qMKN0ckvjYezyfufXEWotSC4kY3mCX3t7CEt/SWIZk4Vll5aGFHVikuCz+mU1y4WRo3yUJU9Xl6wgwCR9ed54AQPLu0TDjPsZhsuVxq3lzEXMzVppsh4J2vHkQPb0QSdF9YRWo06+dbhIjIxi41kW3VU6xZf08C8fZy2I36EL22pdVWgVMmK9HrIiNQ8Cn4Rs9ENuLMLLFQ+Nv4yjrrUWbyqDmWbHJzqJi8PkKAZL8NFVDA/KsqGXFdQKuTV3enkm0AhIxDWW0pacKiepUg93p1IwvD7pMZHWJI6xzu4QHxR2UipAKNVEbCgEWMKq0VJmF2vRZ4i4rt1bgpdmuOlHX4qXzi9c829nI8pUbKkuOA3squLhw/u9pCDpCzXHMZ1OMGqzp68RX//kJNh2bFX6UhcOMTaR3le2c1BDjQCAo+p+xrvm/GHuBtcDD8gbOSan6PZ52HKL4CLvkLSBelUEZOJzDynimxmxA5DpULmQowH6sq7LgnEnUbzpCJSGqXLh642QdRHqPAkmpnAJ3ILIFOabh5fBae/JsuOwK2T8hZbklo2tIcJxbwHmDuyOp80UyyWrbwzeuSAGt/LbFmR9Sgn/0SgdZPBG6yd3kENAJJNdS8p/RH1E1LuN8NwTtzoivYSOBqCxudG2b+P7afNYBXz55XYAfg7SZfVCzKTA6ewHQU2zcDIeOXAGrzXbYSXA48JqLIZ43UcxSffgyyqrvORy4nyZnd5n4SueQD8vXTsmrgZ7DmNyMfJyncc/bEDvr6c+gJ0p5pb3ulmIt0APaLbQkTHQiM24')], reqType=GET, preview=False)
D 2022-06-23 13:08:51,020 yowsup.common.http.warequest - Opening connection to v.whatsapp.net
D 2022-06-23 13:08:51,049 yowsup.common.http.warequest - Sending GET request to /v2/code?ENC=BCJmqDCGWPZd6E88tUmFt3KS0tSi%2bYEMWVcecWhrahe69KflDRp3VLo3sdvQVv0pdDBCF9bRHAe6LOUVOKC%2f3F4xO3xAsmBtbghgO7qp2bcbK25Cx0ybV7%2fu4k6tooYOmgIb%2bJIZZz6qMKN0ckvjYezyfufXEWotSC4kY3mCX3t7CEt%2fSWIZk4Vll5aGFHVikuCz%2bmU1y4WRo3yUJU9Xl6wgwCR9ed54AQPLu0TDjPsZhsuVxq3lzEXMzVppsh4J2vHkQPb0QSdF9YRWo06%2bdbhIjIxi41kW3VU6xZf08C8fZy2I36EL22pdVWgVMmK9HrIiNQ8Cn4Rs9ENuLMLLFQ%2bNv4yjrrUWbyqDmWbHJzqJi8PkKAZL8NFVDA%2fKsqGXFdQKuTV3enkm0AhIxDWW0pacKiepUg93p1IwvD7pMZHWJI6xzu4QHxR2UipAKNVEbCgEWMKq0VJmF2vRZ4i4rt1bgpdmuOlHX4qXzi9c829nI8pUbKkuOA3squLhw%2fu9pCDpCzXHMZ1OMGqzp68RX%2f%2fkJNh2bFX6UhcOMTaR3le2c1BDjQCAo%2bp%2bxrvm%2fGHuBtcDD8gbOSan6PZ52HKL4CLvkLSBelUEZOJzDynimxmxA5DpULmQowH6sq7LgnEnUbzpCJSGqXLh642QdRHqPAkmpnAJ3ILIFOabh5fBae%2fJsuOwK2T8hZbklo2tIcJxbwHmDuyOp80UyyWrbwzeuSAGt%2fLbFmR9Sgn%2f0SgdZPBG6yd3kENAJJNdS8p%2fRH1E1LuN8NwTtzoivYSOBqCxudG2652bP7afNYBXz55XYAfg7SZfVCzKTA6ewHQU2zcDIeOXAGrzXbYSXA48JqLIZ43UcxSffgyyqrvORy4nyZnd5n4SueQD8vXTsmrgZ7DmNyMfJyncc%2fbEDvr6c%2bgJ0p5pb3ulmIt0APaLbQkTHQiM24
I 2022-06-23 13:08:51,593 yowsup.common.http.warequest - b'{"login":"5581xxxxxxxx","param":"backup_token","reason":"bad_param","status":"fail"}\n'
status: b'fail'
reason: b'bad_param'
param: b'backup_token'
login: b'5581xxxxxxxx'

**Comment by marlos7** [comment]
There is a project that I tested here in nodejs that is very good! i think yowsup has been discontinued
https://github.com/jonalan7/Hydra-bot
