### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'config'

### ISSUE THREAD

**Issue by abadiops** [tgalal/yowsup#3133]
When trying to send a message using yowsup, the following error appears: Centos7 operating system with python updated from version 2.7 to 3.6

Activation already generated config.jason file in root. Some of the colleagues would have a solution?

yowsup.layers.network.layer - Connecting to e14.whatsapp.net:443
yowsup.axolotl.manager - Loaded 812 unsent prekeys
yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
File "/usr/lib64/python3.6/asyncore.py", line 91, in write
obj.handle_write_event()
File "/usr/lib64/python3.6/asyncore.py", line 441, in handle_write_event
self.handle_connect_event()
File "/usr/lib64/python3.6/asyncore.py", line 429, in handle_connect_event
self.handle_connect()
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect self.connectionCallbacks.onConnected()
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 53, in onConnected
self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 94, in emitEvent emitEvent(yowLayerEvent)
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 94, in emitEvent .emitEvent(yowLayerEvent)
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 94, in emitEvent er.emitEvent(yowLayerEvent)
[Previous line repeated 3 more times]
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 88, in emitEvent if self.__upper and not self.__upper.onEvent(yowLayerEvent):
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 212, in onEvent stopEvent = stopEvent or s.onEvent(yowLayerEvent)
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 109, in onEvent return self.event_callbacks[eventName](https://github.com/tgalal/yowsup/issues/yowLayerEvent)
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected passive=self.getProp(self.PROP_PASSIVE, False)
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 202, in subBroadcastEvent
self.broadcastEvent(yowLayerEvent)
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 103, in broadcastEvent
self.__lower.broadcastEvent(yowLayerEvent)
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 103, in broadcastEvent
self.__lower.broadcastEvent(yowLayerEvent)
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 103, in broadcastEvent
self.__lower.broadcastEvent(yowLayerEvent)
[Previous line repeated 1 more time]
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 98, in broadcastEvent
if self.__lower and not self.__lower.onEvent(yowLayerEvent):
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 109, in onEvent
return self.event_callbacks[eventName](https://github.com/tgalal/yowsup/issues/yowLayerEvent)
File "/usr/local/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 61, in on_auth
config = self._profile.config # type: yowsup.config.v1.config.Config
AttributeError: 'NoneType' object has no attribute 'config'

yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
yowsup.layers.network.layer - Disconnected
yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False

**Comment by mrjoebudi** [comment]
Type /help for available commands

[offline]:/L
I 2022-04-16 07:59:47,567 yowsup.layers.network.layer - Connecting to e7.whatsapp.net:443
I 2022-04-16 07:59:47,677 yowsup.axolotl.manager - Generating 812 prekeys, current max_prekey_id=0
I 2022-04-16 07:59:47,850 yowsup.axolotl.manager - Storing 812 prekeys
I 2022-04-16 07:59:56,428 yowsup.axolotl.manager - Loaded 812 unsent prekeys
Auth: Logged in!
[connected]:/message send 6281xxxxxxx7 "disini lho"
[connected]:Sent: 1650070823-2
[connected]:

[6281xxxxxxx7@s.whatsapp.net(16-04-2022 08:00)]:[1FFBD53DF8D74D2ADAF171730800001C]       Iya saya tau
Message 1FFBD53DF8D74D2ADAF171730800001C: Sent delivered receipt and Read
[connected]:

[6281xxxxxxx7@s.whatsapp.net(16-04-2022 08:00)]:[25CCEB9E75C90FB21206878C446FDF2F]       Muah
Message 25CCEB9E75C90FB21206878C446FDF2F: Sent delivered receipt and Read
[connected]:

[6281xxxxxxx7@s.whatsapp.net(16-04-2022 08:00)]:[0736C1E75C278365AD78E2948890F201]       Dimana ya
Message 0736C1E75C278365AD78E2948890F201: Sent delivered receipt and Read
[connected]:


still nurmal for me,

**Comment by mrjoebudi** [comment]
> When trying to send a message using yowsup, the following error appears: Centos7 operating system with python updated from version 2.7 to 3.6
> 
> Activation already generated config.jason file in root. Some of the colleagues would have a solution?
> 
> yowsup.layers.network.layer - Connecting to e14.whatsapp.net:443 yowsup.axolotl.manager - Loaded 812 unsent prekeys yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last): File "/usr/lib64/python3.6/asyncore.py", line 91, in write obj.handle_write_event() File "/usr/lib64/python3.6/asyncore.py", line 441, in handle_write_event self.handle_connect_event() File "/usr/lib64/python3.6/asyncore.py", line 429, in handle_connect_event self.handle_connect() File "/usr/local/lib/python3.6/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect self.connectionCallbacks.onConnected() File "/usr/local/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 53, in onConnected self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED)) File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 94, in emitEvent emitEvent(yowLayerEvent) File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 94, in emitEvent .emitEvent(yowLayerEvent) File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 94, in emitEvent er.emitEvent(yowLayerEvent) [Previous line repeated 3 more times] File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 88, in emitEvent if self.__upper and not self.__upper.onEvent(yowLayerEvent): File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 212, in onEvent stopEvent = stopEvent or s.onEvent(yowLayerEvent) File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 109, in onEvent return self.event_callbacks[eventName](https://github.com/tgalal/yowsup/issues/yowLayerEvent) File "/usr/local/lib/python3.6/site-packages/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected passive=self.getProp(self.PROP_PASSIVE, False) File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 202, in subBroadcastEvent self.broadcastEvent(yowLayerEvent) File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 103, in broadcastEvent self.__lower.broadcastEvent(yowLayerEvent) File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 103, in broadcastEvent self.__lower.broadcastEvent(yowLayerEvent) File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 103, in broadcastEvent self.__lower.broadcastEvent(yowLayerEvent) [Previous line repeated 1 more time] File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 98, in broadcastEvent if self.__lower and not self.__lower.onEvent(yowLayerEvent): File "/usr/local/lib/python3.6/site-packages/yowsup/layers/init.py", line 109, in onEvent return self.event_callbacks[eventName](https://github.com/tgalal/yowsup/issues/yowLayerEvent) File "/usr/local/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 61, in on_auth config = self._profile.config # type: yowsup.config.v1.config.Config AttributeError: 'NoneType' object has no attribute 'config'
> 
> yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close yowsup.layers.network.layer - Disconnected yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False


**if error , No Attribute Config,** 

Have you successfully registered?
put the config file in the root directory where the yowsup folder is,

{
    "__version__": 1,
    "cc": "62",
    "client_static_keypair": "8xxxxxxxxxxxxxxxxxlerGiGXnUxxxxxxkdBpTw==",
    "expid": "pQG9KZxxxxxxxxxxMHw==",
    "fdid": "41e6xxxxxxxxxx4a31bf8f",
    "id": "VgG6hVXZxxxxxxxxxqHnLEwhcc=",
    "login": "62xxxxxxxxxx1770",
    "mcc": "510",
    "mnc": "01",
    "phone": "62xxxxxxxxxx1770",
    "sim_mcc": "000",
    "sim_mnc": "000"
}

you can try again, this yowsup lib still nurmaly work !!!
