### ISSUE TITLE
Connection Error 10060 during Installing spaCy medium model

### ISSUE THREAD

**Issue by MEHEhsani** [tgalal/yowsup#3135]
Hi 
I couldn't install a medium or large Spacy model via anaconda,
my OS is win10:
I entered this command:
`(base) C:\>python -m spacy download en_core_web_md` 

and the operation stop by this error:
`Traceback (most recent call last):
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "e:\Users\resea\anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "e:\Users\resea\anaconda3\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "e:\Users\resea\anaconda3\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\Users\resea\anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "e:\Users\resea\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "e:\Users\resea\anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "e:\Users\resea\anaconda3\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "e:\Users\resea\anaconda3\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\Users\resea\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\Users\resea\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "e:\Users\resea\anaconda3\lib\site-packages\spacy\__main__.py", line 4, in <module>
    setup_cli()
  File "e:\Users\resea\anaconda3\lib\site-packages\spacy\cli\_util.py", line 71, in setup_cli
    command(prog_name=COMMAND)
  File "e:\Users\resea\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "e:\Users\resea\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "e:\Users\resea\anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "e:\Users\resea\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "e:\Users\resea\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "e:\Users\resea\anaconda3\lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "e:\Users\resea\anaconda3\lib\site-packages\spacy\cli\download.py", line 35, in download_cli
    download(model, direct, sdist, *ctx.args)
  File "e:\Users\resea\anaconda3\lib\site-packages\spacy\cli\download.py", line 67, in download
    compatibility = get_compatibility()
  File "e:\Users\resea\anaconda3\lib\site-packages\spacy\cli\download.py", line 78, in get_compatibility
    r = requests.get(about.__compatibility__)
  File "e:\Users\resea\anaconda3\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "e:\Users\resea\anaconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "e:\Users\resea\anaconda3\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "e:\Users\resea\anaconda3\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "e:\Users\resea\anaconda3\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))`

**Comment by heeplr** [comment]
This doesn't look like a yowsup issue. It's rather related to spacy or anaconda.
