### ISSUE TITLE
error al registrar

### ISSUE THREAD

**Issue by ibanana** [tgalal/yowsup#3141]
root@ns305455:/opt/yowsup# yowsup-cli registration --requestcode sms -p 34xxxxx555 -C x4 -m xx4 -n x2
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 189, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/bin/yowsup-cli", line 198, in handleRequestCode
    from yowsup.registration import WACodeRequest
  File "/usr/lib/python3/dist-packages/yowsup/registration/__init__.py", line 1, in <module>
    from .coderequest import WACodeRequest
  File "/usr/lib/python3/dist-packages/yowsup/registration/coderequest.py", line 3, in <module>
    from yowsup.common.tools import StorageTools, WATools
  File "/usr/lib/python3/dist-packages/yowsup/common/tools.py", line 3, in <module>
    from dateutil import tz
ModuleNotFoundError: No module named 'dateutil'

Requirement already up-to-date: python-dateutil in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: six>=1.5 in /usr/local/lib/python2.7/dist-packages (from python-dateutil)

**Comment by RafOSS-br** [comment]
Run setup.py
