### ISSUE TITLE
Unsupported ib node:

### ISSUE THREAD

**Issue by nekko211** [tgalal/yowsup#3162]

**Comment by nekko211** [comment]
Hello everyone, I tried to run yowsup from different Linux distros, but it always gives the same error "NameError: name 'version' is not defined" and refers to this line in the file "yowsup/layers/noise/layer.py" "app_version= version.str", it seems to me that the problem is in the content of the "env" directory headers, I may be wrong, here is the command line output:
yowsup-cli demos --config-phone 44********** -y -d -E android
D 2022-09-03 10:33:04,341 yowsup.env.env - Current env changed to android 
D 2022-09-03 10:33:04,341 yowsup.config.manager - load(path_or_profile_name=44**********, profile_only=False)
D 2022-09-03 10:33:04,341 yowsup.config.manager - _load_path(path=44**********)
D 2022-09-03 10:33:04,341 yowsup.config.manager - _load_path couldn't find the path: 44**********
D 2022-09-03 10:33:04,341 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2022-09-03 10:33:04,341 yowsup.config.manager - Detecting config for profile=44**********, dir=/home/jak/.config/yowsup/44**********
D 2022-09-03 10:33:04,341 yowsup.config.manager - Trying /home/jak/.config/yowsup/44**********/config.yo
D 2022-09-03 10:33:04,341 yowsup.config.manager - Trying /home/jak/.config/yowsup/44**********/config.json
D 2022-09-03 10:33:04,341 yowsup.config.manager - _load_path(path=/home/jak/.config/yowsup/44**********/config.json)
D 2022-09-03 10:33:04,341 yowsup.config.manager - Detected config type: json
D 2022-09-03 10:33:04,341 yowsup.config.manager - Opening config for reading
D 2022-09-03 10:33:04,341 yowsup.config.manager - Loading config
D 2022-09-03 10:33:04,341 yowsup.profile.profile - Constructed Profile(profile_name=44**********)
D 2022-09-03 10:33:04,341 yowsup-cli - starting cmd
yowsup-cli     v3.2.1
yowsup         v3.3.0
consonance     v0.1.5
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v3.4.7
protobuf       v3.14.0


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


D 2022-09-03 10:33:04,426 yowsup.stacks.yowstack - Initializing stack
D 2022-09-03 10:33:04,426 yowsup.stacks.yowstack - Constructed Network Layer
D 2022-09-03 10:33:04,426 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2022-09-03 10:33:04,427 yowsup.stacks.yowstack - Constructed Noise Layer
D 2022-09-03 10:33:04,427 yowsup.stacks.yowstack - Constructed Coder Layer
D 2022-09-03 10:33:04,427 yowsup.stacks.yowstack - Constructed Logger Layer
D 2022-09-03 10:33:04,428 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f36dee97d00>
D 2022-09-03 10:33:04,428 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f36df628dc0>
D 2022-09-03 10:33:04,428 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2022-09-03 10:33:04,431 yowsup.stacks.yowstack - Constructed CLI Interface Layer
D 2022-09-03 10:33:04,431 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=44**********))
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
D 2022-09-03 10:33:08,039 yowsup.layers.network.layer - Created asyncore dispatcher
I 2022-09-03 10:33:08,040 yowsup.layers.network.layer - Connecting to e3.whatsapp.net:443
D 2022-09-03 10:33:08,040 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e3.whatsapp.net', 443))
D 2022-09-03 10:33:08,981 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2022-09-03 10:33:08,981 yowsup.layers.network.layer - Connected
D 2022-09-03 10:33:08,982 yowsup.axolotl.factory - get_manager(profile_name=44**********, username=44**********)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
yowsup-cli demos --config-phone 44********** -y -d -E ios
D 2022-09-03 10:52:41,163 yowsup.env.env - Current env changed to ios 
D 2022-09-03 10:52:41,163 yowsup.config.manager - load(path_or_profile_name=44**********, profile_only=False)
D 2022-09-03 10:52:41,163 yowsup.config.manager - _load_path(path=44**********)
D 2022-09-03 10:52:41,163 yowsup.config.manager - _load_path couldn't find the path: 44**********
D 2022-09-03 10:52:41,163 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2022-09-03 10:52:41,163 yowsup.config.manager - Detecting config for profile=44**********, dir=/home/jak/.config/yowsup/44**********
D 2022-09-03 10:52:41,163 yowsup.config.manager - Trying /home/jak/.config/yowsup/44**********/config.yo
D 2022-09-03 10:52:41,163 yowsup.config.manager - Trying /home/jak/.config/yowsup/44**********/config.json
D 2022-09-03 10:52:41,163 yowsup.config.manager - _load_path(path=/home/jak/.config/yowsup/44**********/config.json)
D 2022-09-03 10:52:41,163 yowsup.config.manager - Detected config type: json
D 2022-09-03 10:52:41,163 yowsup.config.manager - Opening config for reading
D 2022-09-03 10:52:41,163 yowsup.config.manager - Loading config
D 2022-09-03 10:52:41,163 yowsup.profile.profile - Constructed Profile(profile_name=44**********)
D 2022-09-03 10:52:41,164 yowsup-cli - starting cmd
yowsup-cli     v3.2.1
yowsup         v3.3.0
consonance     v0.1.5
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v3.4.7
protobuf       v3.14.0


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


D 2022-09-03 10:52:41,248 yowsup.stacks.yowstack - Initializing stack
D 2022-09-03 10:52:41,248 yowsup.stacks.yowstack - Constructed Network Layer
D 2022-09-03 10:52:41,249 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2022-09-03 10:52:41,249 yowsup.stacks.yowstack - Constructed Noise Layer
D 2022-09-03 10:52:41,249 yowsup.stacks.yowstack - Constructed Coder Layer
D 2022-09-03 10:52:41,249 yowsup.stacks.yowstack - Constructed Logger Layer
D 2022-09-03 10:52:41,250 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f8ae9673d00>
D 2022-09-03 10:52:41,250 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f8ae9e10dc0>
D 2022-09-03 10:52:41,250 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2022-09-03 10:52:41,253 yowsup.stacks.yowstack - Constructed CLI Interface Layer
D 2022-09-03 10:52:41,253 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=44**********))
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
D 2022-09-03 10:52:46,084 yowsup.layers.network.layer - Created asyncore dispatcher
I 2022-09-03 10:52:46,084 yowsup.layers.network.layer - Connecting to e2.whatsapp.net:443
D 2022-09-03 10:52:46,084 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e2.whatsapp.net', 443))
D 2022-09-03 10:52:46,212 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2022-09-03 10:52:46,212 yowsup.layers.network.layer - Connected
D 2022-09-03 10:52:46,213 yowsup.axolotl.factory - get_manager(profile_name=44**********, username=44**********)
D 2022-09-03 10:52:46,213 yowsup.axolotl.manager - Initialized AxolotlManager [username=44**********, db=/home/jak/.config/yowsup/44**********/axolotl.db]
D 2022-09-03 10:52:46,213 yowsup.axolotl.manager - level_prekeys(force=False)
D 2022-09-03 10:52:46,239 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2022-09-03 10:52:46,239 yowsup.axolotl.manager - load_unsent_prekeys
D 2022-09-03 10:52:46,239 yowsup.layers.noise.layer - Received auth event
D 2022-09-03 10:52:46,239 yowsup.env.env - Env not set, setting it to android
D 2022-09-03 10:52:46,239 yowsup.env.env - Current env changed to android 
E 2022-09-03 10:52:46,240 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib64/python3.10/asyncore.py", line 98, in write
    obj.handle_write_event()
  File "/usr/lib64/python3.10/asyncore.py", line 445, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib64/python3.10/asyncore.py", line 433, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/network/layer.py", line 54, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/auth/layer_authentication.py", line 33, in on_connected
    self.broadcastEvent(
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/noise/layer.py", line 101, in on_auth
    app_version=version.str,
NameError: name 'version' is not defined

D 2022-09-03 10:52:46,240 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2022-09-03 10:52:46,240 yowsup.layers.network.layer - Disconnected
D 2022-09-03 10:52:46,262 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
general: Disconnected: 
[offline]:
[offline]:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
yowsup-cli demos --config-phone 44********** -y -d 
D 2022-09-03 10:54:40,960 yowsup.config.manager - load(path_or_profile_name=44**********, profile_only=False)
D 2022-09-03 10:54:40,960 yowsup.config.manager - _load_path(path=44**********)
D 2022-09-03 10:54:40,960 yowsup.config.manager - _load_path couldn't find the path: 44**********
D 2022-09-03 10:54:40,960 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2022-09-03 10:54:40,960 yowsup.config.manager - Detecting config for profile=44**********, dir=/home/jak/.config/yowsup/44**********
D 2022-09-03 10:54:40,960 yowsup.config.manager - Trying /home/jak/.config/yowsup/44**********/config.yo
D 2022-09-03 10:54:40,960 yowsup.config.manager - Trying /home/jak/.config/yowsup/44**********/config.json
D 2022-09-03 10:54:40,960 yowsup.config.manager - _load_path(path=/home/jak/.config/yowsup/44**********/config.json)
D 2022-09-03 10:54:40,961 yowsup.config.manager - Detected config type: json
D 2022-09-03 10:54:40,961 yowsup.config.manager - Opening config for reading
D 2022-09-03 10:54:40,961 yowsup.config.manager - Loading config
D 2022-09-03 10:54:40,961 yowsup.profile.profile - Constructed Profile(profile_name=44**********)
D 2022-09-03 10:54:40,961 yowsup-cli - starting cmd
yowsup-cli     v3.2.1
yowsup         v3.3.0
consonance     v0.1.5
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v3.4.7
protobuf       v3.14.0


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


D 2022-09-03 10:54:41,046 yowsup.stacks.yowstack - Initializing stack
D 2022-09-03 10:54:41,046 yowsup.stacks.yowstack - Constructed Network Layer
D 2022-09-03 10:54:41,046 yowsup.stacks.yowstack - Constructed Noise Segments Layer
D 2022-09-03 10:54:41,047 yowsup.stacks.yowstack - Constructed Noise Layer
D 2022-09-03 10:54:41,047 yowsup.stacks.yowstack - Constructed Coder Layer
D 2022-09-03 10:54:41,047 yowsup.stacks.yowstack - Constructed Logger Layer
D 2022-09-03 10:54:41,047 yowsup.stacks.yowstack - Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7f8a130d3d00>
D 2022-09-03 10:54:41,047 yowsup.stacks.yowstack - Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7f8a13870dc0>
D 2022-09-03 10:54:41,047 yowsup.stacks.yowstack - Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Contact Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
D 2022-09-03 10:54:41,051 yowsup.stacks.yowstack - Constructed CLI Interface Layer
D 2022-09-03 10:54:41,051 yowsup.stacks.yowstack - setProfile(YowProfile(profile_name=44**********))
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
D 2022-09-03 10:54:45,555 yowsup.layers.network.layer - Created asyncore dispatcher
I 2022-09-03 10:54:45,555 yowsup.layers.network.layer - Connecting to e6.whatsapp.net:443
D 2022-09-03 10:54:45,555 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e6.whatsapp.net', 443))
D 2022-09-03 10:54:45,744 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2022-09-03 10:54:45,744 yowsup.layers.network.layer - Connected
D 2022-09-03 10:54:45,744 yowsup.axolotl.factory - get_manager(profile_name=44**********, username=44**********)
D 2022-09-03 10:54:45,744 yowsup.axolotl.manager - Initialized AxolotlManager [username=44**********, db=/home/jak/.config/yowsup/44**********/axolotl.db]
D 2022-09-03 10:54:45,745 yowsup.axolotl.manager - level_prekeys(force=False)
D 2022-09-03 10:54:45,770 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2022-09-03 10:54:45,770 yowsup.axolotl.manager - load_unsent_prekeys
D 2022-09-03 10:54:45,770 yowsup.layers.noise.layer - Received auth event
D 2022-09-03 10:54:45,770 yowsup.env.env - Env not set, setting it to android
D 2022-09-03 10:54:45,771 yowsup.env.env - Current env changed to android 
E 2022-09-03 10:54:45,771 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib64/python3.10/asyncore.py", line 98, in write
    obj.handle_write_event()
  File "/usr/lib64/python3.10/asyncore.py", line 445, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib64/python3.10/asyncore.py", line 433, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/network/layer.py", line 54, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/auth/layer_authentication.py", line 33, in on_connected
    self.broadcastEvent(
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.10/site-packages/yowsup/layers/noise/layer.py", line 101, in on_auth
    app_version=version.str,
NameError: name 'version' is not defined

D 2022-09-03 10:54:45,771 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2022-09-03 10:54:45,772 yowsup.layers.network.layer - Disconnected
D 2022-09-03 10:54:45,866 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
general: Disconnected: 
[offline]:
[offline]:
