### ISSUE TITLE
Demo problem

### ISSUE THREAD

**Issue by limelect** [tgalal/yowsup#3165]
I use your demo run.py and layer.py
i put my phone and password CREDENTIALS =
I get an error
  create_key=_descriptor._internal_create_key,

Traceback (most recent call last):
  File "G:\1\Delphi\Whatsapp\yowsup-master\Demo\run.py", line 9, in <module>
    from yowsup.stacks import YowStack
  File "C:\Python\Python36-32\lib\site-packages\yowsup-3.3.0-py3.6.egg\yowsup\stacks\__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "C:\Python\Python36-32\lib\site-packages\yowsup-3.3.0-py3.6.egg\yowsup\stacks\yowstack.py", line 4, in <module>
    from yowsup.layers.noise.layer import YowNoiseLayer
  File "C:\Python\Python36-32\lib\site-packages\yowsup-3.3.0-py3.6.egg\yowsup\layers\noise\layer.py", line 1, in <module>
    from yowsup.layers.noise.workers.handshake import WANoiseProtocolHandshakeWorker
  File "C:\Python\Python36-32\lib\site-packages\yowsup-3.3.0-py3.6.egg\yowsup\layers\noise\workers\handshake.py", line 1, in <module>
    from consonance.protocol import WANoiseProtocol
  File "C:\Python\Python36-32\lib\site-packages\consonance-0.1.5-py3.6.egg\consonance\protocol.py", line 2, in <module>
    from .handshake import WAHandshake
  File "C:\Python\Python36-32\lib\site-packages\consonance-0.1.5-py3.6.egg\consonance\handshake.py", line 22, in <module>
    from .proto import wa20_pb2
  File "C:\Python\Python36-32\lib\site-packages\consonance-0.1.5-py3.6.egg\consonance\proto\wa20_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

**Comment by rohitmali123** [comment]
pip install --upgrade protobuf

upgrade it

**Comment by MySoulisBeer** [comment]
The demo example uses (phone, password) combination, but app says it is deprecated. Can anyone provide some simple demo of working code?
