### ISSUE TITLE
old_version

### ISSUE THREAD

**Issue by antonio199205** [tgalal/yowsup#3172]
W 2022-10-21 23:43:01,999 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
I 2022-10-21 23:43:02,288 yowsup.common.http.warequest - b'{"login":"55629xxxxxx","reason":"old_version","status":"fail"}\n'
status: b'fail'
reason: b'old_version'
login: b'55629xxxxxx'

**Comment by antonio199205** [comment]
I switched to ios but I get this error

Traceback (most recent call last):
  File "c:\Users\Anton\AppData\Local\Programs\Python\Python310\Scripts\yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup==3.3.0', 'yowsup-cli')
  File "c:\Users\Anton\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "c:\Users\Anton\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "c:\users\anton\appdata\local\programs\python\python310\lib\site-packages\yowsup-3.3.0-py3.10.egg\EGG-INFO\scripts\yowsup-cli", line 5, in <module>
    from yowsup.env import YowsupEnv
  File "c:\Users\Anton\AppData\Local\Programs\Python\Python310\lib\site-packages\yowsup-3.3.0-py3.10.egg\yowsup\env\__init__.py", line 2, in <module>
    from .env_ios import iOsYowsupEnv
ModuleNotFoundError: No module named 'yowsup.env.env_ios'

**Comment by dyahav3** [comment]
Same thing here

**Comment by antonio199205** [comment]
I managed to make it work, I updated the whatsapp constants, I just don't know how to send a message

**Comment by antonio199205** [comment]
![image](https://user-images.githubusercontent.com/111067121/197554550-f6262ac6-8c23-4e3c-8f3e-a2e89b93c36b.png)

![image](https://user-images.githubusercontent.com/111067121/197555914-87a5d388-5f4d-4ab0-82c6-161afda9d24f.png)

**Comment by madduck** [comment]
@antonio199205 could you please tell us what constants you updated? Maybe this library is unmaintained and needs a fork?

**Comment by antonio199205** [comment]
_MD5_CLASSES = "jJYkDZJ+SGfBMvlEeGKmSw=="
     _VERSION = "2.22.19.76"

**Comment by madduck** [comment]
Thanks. This should be merged into #3156

**Comment by madduck** [comment]
@antonio199205 could you please also share how you derived those new data?

**Comment by madduck** [comment]
Using those constants successfully got my burner phone registered. However, trying to use the demo client, I cannot seem to get connected:

```
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
I 2022-10-24 17:16:00,540 yowsup.layers.network.layer - Connecting to e3.whatsapp.net:443
I 2022-10-24 17:16:00,558 yowsup.axolotl.manager - Generating 812 prekeys, current max_prekey_id=0
I 2022-10-24 17:16:00,816 yowsup.axolotl.manager - Storing 812 prekeys
I 2022-10-24 17:16:06,647 yowsup.axolotl.manager - Loaded 812 unsent prekeys
general: Disconnected: 
[offline]:/ping

Error: Not connected
```

**Comment by antonio199205** [comment]
I have a developer friend who makes desktop software I got it from him I'll see if there's anything more up to date
https://www.youtube.com/channel/UCi6ejEXJgiVYHTH5c14TBpg

**Comment by antonio199205** [comment]
8Fz9R1yOYocVWtGWahVYBw==
2.22.21.83

try with this one
[madduck](https://github.com/madduck)

**Comment by antonio199205** [comment]
if it works let me know

**Comment by madduck** [comment]
It worked for me with

```
_MD5_CLASSES = "jJYkDZJ+SGfBMvlEeGKmSw=="
_VERSION = "2.22.19.76"
```

after I replaced all endpoints in `constants.py` with `g.whatsapp.net`, as suggested here: https://github.com/tgalal/yowsup/issues/3157#issuecomment-1193663427

It also works with the values you suggested above (2.22.21.83)

**Comment by antonio199205** [comment]
ok, whenever i need constant whatsapp i have something else how do i send a message to a number

**Comment by madduck** [comment]
You can use the demo client to send a message, or write some Python. It's documented on the Wiki.

**Comment by dazzzl** [comment]
@madduck 
It does not work for me... I got  `<failure reason="401" location="atn">`

What have you modified except the modification above? 

BTW r.whatsapp.net does not work... should be g.whatsapp.net?

Thanks!

**Comment by madduck** [comment]
yeah @dazzzl, g.... editing.

**Comment by kushagra9967** [comment]
@madduck @antonio199205 can we send images using yowsup . I am not able to send any media . Can u please help me ?

**Comment by antonio199205** [comment]
[kushagra9967](https://github.com/kushagra9967) I don't know how it works, I don't even know how to send a simple text message, but I have developers to work on this project, if anyone has the code developer's contact and wants to let me know, I have a good proposal for him to update the code

**Comment by kushagra9967** [comment]
@antonio199205 : i have messaged you on telegram

**Comment by antonio199205** [comment]
[kushagra9967](https://github.com/kushagra9967) https://t.me/sac_store24h

**Comment by kushagra9967** [comment]
@antonio199205 : i have already messaged. Please Check

**Comment by antonio199205** [comment]
xvHJS7OwkFzSCemQ0VX8cg==
2.22.22.80

**Comment by antonio199205** [comment]
2.22.23.84
Qc0kUxteJdDJSpeLPeHMKQ==

**Comment by FkyMouse** [comment]
Version: 2.22.23.85
ClassesDex: YgGFYlBVxzteZp1oO+v28w==

But it still does not work
what can do with it. cant make a registration
`status: b'fail'
reason: b'old_version'
login: b'7904XXXXXXX'`

**Comment by ChowSings** [comment]
change the file **/env/env_android.py**
_MD5_CLASSES = "fJdJ2pZOVbYYjN+D8g8mUQ=="
_VERSION = "2.22.24.76"
Tool: [dexMD5.py](https://github.com/mgp25/classesMD5-64/blob/master/dexMD5.py)

**Comment by marcossilva37** [comment]
> change the file **/env/env_android.py** _MD5_CLASSES = "fJdJ2pZOVbYYjN+D8g8mUQ==" _VERSION = "2.22.24.76" Tool: [dexMD5.py](https://github.com/mgp25/classesMD5-64/blob/master/dexMD5.py)

is working for you?

i tried the newest, but does not work

Version: 2.22.24.79
ClassesDex: aB7TRBP7/nT6KypPakIupw==

![image](https://user-images.githubusercontent.com/16008933/209158975-b403f2fa-6bc2-4eb4-bd94-6c038f3a7596.png)

**Comment by li894882182** [comment]
> 

me too , do you resolved it ?

**Comment by theunf** [comment]
> change the file **/env/env_android.py** _MD5_CLASSES = "fJdJ2pZOVbYYjN+D8g8mUQ==" _VERSION = "2.22.24.76" Tool: [dexMD5.py](https://github.com/mgp25/classesMD5-64/blob/master/dexMD5.py)

BTW, if I do these changes the error changes to : 

W 2023-04-22 11:09:06,500 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
I 2023-04-22 11:09:07,600 yowsup.common.http.warequest - b'{"email_otp_wait":65,"flash_type":1,"length":6,"login":"XXXXXXXXX","method":"sms","notify_after":86400,"retry_after":125,"sms_wait":125,"status":"sent","voice_wait":125,"wa_old_wait":65}\n'
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 679, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 350, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/local/bin/yowsup-cli", line 369, in handleRequestCode
    self._config_manager.save(self._config)
TypeError: save() missing 1 required positional argument: 'config'
