### ISSUE TITLE
"Sent keys were not accepted" issue

### ISSUE THREAD

**Issue by OVERSKY2003** [tgalal/yowsup#3178]
The error is as below, How to fix it?

2022-11-02 19:49:55,244 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/network/dispatcher/asyncore_new.py", line 88, in read
    obj.handle_read_event()
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/network/dispatcher/asyncore_new.py", line 447, in handle_read_event
    self.handle_read()
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 67, in handle_read
    self.connectionCallbacks.onRecvData(data)
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/network/layer.py", line 107, in onRecvData
    self.receive(data)
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/noise/layer.py", line 209, in receive
    self._flush_incoming_buffer()
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/noise/layer.py", line 197, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/axolotl/layer_control.py", line 29, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/__init__.py", line 163, in processIqRegistry
    errorClbk(protocolTreeNode, originalIq)
  File "/yowsup-3.3.0-py3.8.egg/yowsup/layers/axolotl/layer_control.py", line 121, in onSentKeysError
    raise Exception("Sent keys were not accepted")
Exception: Sent keys were not accepted

**Comment by clarithromycine** [comment]
try to rerun about 8 times
then exception disappear

**Comment by ORMiK0** [comment]
same issue too. Cant upload keys, then cant send messages. Any idea?

**Comment by Rodrigosolari** [comment]
From what I could see, it was connecting to other servers, I had it running connected to chat.cdn.whatsapp.net, or g.whatsapp.net, but now I can't find anything, any help?

**Comment by brewkon** [comment]
i hava the same probleam, who can help me?
When uploading the prekeys, the server returns an error, which is not acceptable. Seems related to gcm push

**Comment by glitchhunt3r** [comment]
hello @brewkon , have you ever been able to find a solution to this?
