### ISSUE TITLE
"Old version" error for Android version - 2.23.5.78?

### ISSUE THREAD

**Issue by Meirasulin** [tgalal/yowsup#3196]
**When I return the WhatsApp verification code when logging in I get the following error message
Does anyone know how to solve this???
It seems that the issue is with the "edge_routing_info" field in the response from the server, which is returning 'NoneType' instead of a bytes-like object or an ASCII string. This is causing a TypeError to be raised when trying to decode it using the base64 library.**
_[Using Kali Linux on VMWARE
Distributor ID: Kali
Description: Kali GNU/Linux Rolling
Release: 2022.4
Python version: Python 3.10.9]_

```
yowsup-cli registration --register 9****4 --config-phone 97********41 --config-cc ***
yowsup-cli  v3.2.0
yowsup      v3.2.3
Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org
This software is provided free of charge. Copying and redistribution is
encouraged.
If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate
I 2023-01-16 16:10:30,788 yowsup.common.http.warequest - b'{"autoconf_type":1,"lid":"279924745199757","login":"972******41","security_code_set":false,"status":"ok","type":"existing"}\n'
{    "__version__": 1,
    "cc": "972",
    "client_static_keypair": "yOXCdgcysa/J33FMUaxqQiOB5hy09RoK5SKj0a357F5A9duLeFoY6jofwfkPwN7SOPCjp3gA9GJlDsupwlkYNw==",
    "expid": "otCUMgMfTByHzDRfUtsWEg==",
    "fdid": "5da6df4e-8fdf-49d2-b61d-d02fa959d150",
    "id": "HieIi9riBSIJBNyYbjmLOZND0MI=",
    "mcc": "4*5",
    "mnc": "08",
    "phone": "97*****041",
    "sim_mcc": "000",
    "sim_mnc": "000"}
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 679, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 352, in process
    self.handleRegister(self.args["register"], config)
  File "/usr/local/bin/yowsup-cli", line 384, in handleRegister
    self._config.edge_routing_info = base64.b64decode(result["edge_routing_info"])
  File "/usr/lib/python3.10/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/lib/python3.10/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
```

**Comment by Rodrigosolari** [comment]
trata de poner "-d" al final para visualizar el debug, aun que pienso... que no actualizaste y estas usando el env de android

try to put "-d" at the end to display the debug, although I think ... you did not update and you are using the android env

**Comment by Meirasulin** [comment]
I updated my env_android file to version 2.23.5.78 and still I can't send sms to register
The reason "old version"
Has anyone encountered this? What is the pron for it?

**Comment by Meirasulin** [comment]
```
yowsup-cli registration --requestcode sms --config-phone 9----------1 --config-cc 9-- --config-mcc 4-- --config-mnc 0- -d
D 2023-03-18 18:16:11,038 yowsup.config.manager - Detecting config for username=9----------1, dir=/root/.config/yowsup/9----------1/
D 2023-03-18 18:16:11,038 yowsup.config.manager - Trying /root/.config/yowsup/9------------1/config.yo
D 2023-03-18 18:16:11,039 yowsup.config.manager - Trying /root/.config/yowsup/9------------1/config.json
D 2023-03-18 18:16:11,039 yowsup.config.manager - load_path(path=/root/.config/yowsup/9------------1/config.json)
D 2023-03-18 18:16:11,039 yowsup.config.manager - Detected config type: json
D 2023-03-18 18:16:11,039 yowsup.config.manager - Opening config for reading
D 2023-03-18 18:16:11,040 yowsup.config.manager - Loading config
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


D 2023-03-18 18:16:11,409 yowsup.axolotl.factory - get_manager(username=9-------------1)
D 2023-03-18 18:16:11,414 yowsup.axolotl.manager - Initialized AxolotlManager [username=9-----------1, db=/root/.config/yowsup/9--------1/axolotl.db]
D 2023-03-18 18:16:11,414 yowsup.axolotl.manager - load_latest_signed_prekey
D 2023-03-18 18:16:11,417 yowsup.env.env - Env not set, setting it to android
D 2023-03-18 18:16:11,417 yowsup.env.env - Current env changed to android 
D 2023-03-18 18:16:11,418 yowsup.axolotl.factory - get_manager(username=9----------1)
D 2023-03-18 18:16:11,418 yowsup.axolotl.manager - Initialized AxolotlManager [username=9---------1, db=/root/.config/yowsup/972587877041/axolotl.db]
D 2023-03-18 18:16:11,418 yowsup.axolotl.manager - load_latest_signed_prekey
D 2023-03-18 18:16:11,418 yowsup.common.http.warequest - send(parser=None, encrypt=True, preview=False)
D 2023-03-18 18:16:11,418 yowsup.common.http.warequest - sendGetRequest(parser=None, encrypt_params=True, preview=False)
D 2023-03-18 18:16:11,418 yowsup.common.http.warequest - Encrypting parameters
D 2023-03-18 18:16:11,419 yowsup.common.http.warequest - pre-encrypt (encoded) parameters = 
cc=9--&in=5-------1&lg=en&lc=GB&mistyped=6&authkey=QPXbi3haGOo6H8H5D8De0jjwo6d4APRiZQ7LqcJZGDc&e_regid=Ts0XXw&e_keytype=BQ&e_ident=GBam6SdiGXCNv%5fqSdfToFvjT%5ff%2dsYrWVOm%2dB6jI2PwU&e_skey_id=AAAA&e_skey_val=dsX%2dHBcUSBbP%5fUgcmB7pApmgTYQxD4dbFBoN4EmhXQM&e_skey_sig=eHvNMZvDJJM%2dlgeP4A7ycLdHsvOlokmHvPJLe%5fqXEOKhUtqqfkAnEkomechjTtSl2ZWf%5fKm6fQR4XT8TqAXADw&fdid=5da6df4e%2d8fdf%2d49d2%2db61d%2dd02fa959d150&expid=otCUMgMfTByHzDRfUtsWEg&network_radio_type=1&simnum=1&hasinrc=1&pid=387&rc=0&id=%1e%27%88%8b%da%e2%05%22%09%04%dc%98n9%8b9%93C%d0%c2&token=l2%2bB8hIcfFakws51cVNZon30HGo%3d
D 2023-03-18 18:16:11,421 yowsup.common.http.warequest - sendRequest(host=v.whatsapp.net, port=443, path=/v2/exist, headers={'User-Agent': 'WhatsApp/2.19.51 Android/8.0.0 Device/samsung-star2lte', 'Accept': 'text/json'}, params=[('ENC', b'GOOjZbTebAKFj/kQI9lpphT8Pk+n1ZBqN/VWsBxarx0BNbISh8cMdq9CUTuWSFuV0mM6G3exD6QIS7N9OHRr3e/o5AOSpPnru3u4BMpGAGZ9/WGk0oQjd0zCzGrHJzYKe2imErhXOiQ5rhrX9rm+p8MbGt7Nay68RbYEhnMjU5HWkMaG3bQfBRKE2hwICNK2jP4p4U43Wf1RrJQumuy1c/9QlXZaQP80kvEi+7ZSq2d0BFsjGPj17lXHK6XJG834T7byGasP3o6Tb3BBfiq2lnagVgBO69ethFwj39yUH70SrLdUnn3hFrvSZI3x9SHhdQLfOX2ImnKeXrGL/Nt5oo/lLpBY4733gSsekrgaQLhBiJN7hvhgVI4ULsGHfPJ0Pf0OVAmQhqNhP9sTe4G7+Qr1DaRsfUrgI3bSTPxwdgisJK1gU5cKG6NSThDbqCNlCE6vEKH8zHXFb7goazNYYik/i2DUMfM+O8Uc46/MkMyyBMrEdCR6ZkAEYbd2ytwD8GARST/7HBD/qTrlL78OJxog6P/7jSgiBuwD957+qmDYYTZ9xtCCbidJh9J5MqkmiJOsVb+BSEpZ0EFFN5/YlIGNPWbjmSehqyrTC+ytmch/ZvUT3cQecsHv3yqVsN8T6zgO+Q4cy9mbQgGcqW7tUXeKvzVELTet61H7WTxXnwiWXixcg5IgDg3GJ1m+pESJ9WOuP6fuTSg=')], reqType=GET, preview=False)
D 2023-03-18 18:16:11,422 yowsup.common.http.warequest - Opening connection to v.whatsapp.net
D 2023-03-18 18:16:11,457 yowsup.common.http.warequest - Sending GET request to /v2/exist?ENC=GOOjZbTebAKFj%2fkQI9lpphT8Pk%2bn1ZBqN%2fVWsBxarx0BNbISh8cMdq9CUTuWSFuV0mM6G3exD6QIS7N9OHRr3e%2fo5AOSpPnru3u4BMpGAGZ9%2fWGk0oQjdf9QlXZaQP80kvEi%2b7ZSq2dZJNIPBw2%2bM351sfrRXX0BFsjGPj17lXHK6XJG834T7byGasP3o6Tb3BBfiq2lnagVgBO69ethFwj39yUH70SrLdUnn3hFrvSZI3x9SHhdQLfOX2ImnKeXrGL%2fNt5oo%2flLpBY4733gSsekrgaQLhBiJN7hvhgVI4ULsGHfPJ0Pf0OVAmQhqNhP9sTe4G7%2bQr1DaRsfUrgI3bSTPxwdgisJK1gU5cKG6NSThDbqCNlCE6vEKH8zHXFb7goazNwEfos3Li9E3La3ci9q9PYYik%2fi2DgGcRbCNViIMTN5YKzBIQcoQksyVL8EwPeOo0%2fOx%2bbeAsC52PlV8OyGXPvImw9fMI0iXIOfVlLaU6lWiuxkQPl71%2fd7zGmxqZqW7tUXeKvzVELTet61H7WTxXnwiWXixcg5IgDg3GJ1m%2bpESJ9WOuP6fuTSg%3d
I 2023-03-18 18:16:11,885 yowsup.common.http.warequest - b'{"login":"9----------1","reason":"old_version","status":"fail"}\n'
D 2023-03-18 18:16:11,886 yowsup.common.http.warequest - send(parser=None, encrypt=True, preview=False)
D 2023-03-18 18:16:11,887 yowsup.common.http.warequest - sendGetRequest(parser=None, encrypt_params=True, preview=False)
D 2023-03-18 18:16:11,887 yowsup.common.http.warequest - Encrypting parameters
D 2023-03-18 18:16:11,888 yowsup.common.http.warequest - pre-encrypt (encoded) parameters = 
cc=9---&in=5-------1&lg=en&lc=GB&mistyped=6&authkey=QPXbi3haGOo6H8H5D8De0jjwo6d4APRiZQ7LqcJZGDc&e_regid=Ts0XXw&e_keytype=BQ&e_ident=GBam6SdiGXCNv%5fqSdN4EmhXQM&e_skey_sig=eHvNMZvDJJM%2dlgeP4A7ycLdHsvOlokmHvPJLe%5fqXEOKhUtqqfkAnEkomechjTtSl2Eg&network_radio_type=1&simnum=1&hasinrc=1&pid=4288&rc=0&id=%1e%27%88%8b%da%e2%05%22%09%04%dc%98n9%8b9%93C%d0%c2&mcc=425&mnc=008&sim_mcc=000&sim_mnc=000&method=sms&reason=&token=l2%2bB8hIcfFakws51cVNZon30HGo%3d&hasav=1
D 2023-03-18 18:16:11,888 yowsup.common.http.warequest - sendRequest(host=v.whatsapp.net, port=443, path=/v2/code, headers={'User-Agent': 'WhatsApp/2.19.51 Android/8.0.0 Device/samsung-star2lte', 'Accept': 'text/json'}, params=[('ENC', b'Ms9qYref+vTSr+xZjXTu2jy/tTWD87f7im1voL8mGXh7PJMg9zRe/0WkaSYpvacSNqy0dDmQe2nPDaE+gMQ9nGykh+P+Zf41eZFmYtbQuhkkha4HpW+V1zxAQOHbpFphHEEfNhgAtF4KB92XbGYfRaTZQiLF1J/HQ4QDOO7R/8jFm+J7y5OeLs3P8FFTyEguLD7d9mANkva3ppb7oDX4tHEvgPpDIvFDFBJ9QpSFeIB7pHdm/cJvFxIQjbrAR3Cy95EPyweHBC+zyGlebr/5alg+XOcj8d8lQnH8hijWGNcBgk/ebb0EolfS7y4e2wJak8pdFjypM/5X3K/pQ91Y+rHbC6bw==')], reqType=GET, preview=False)
D 2023-03-18 18:16:11,889 yowsup.common.http.warequest - Opening connection to v.whatsapp.net
D 2023-03-18 18:16:11,917 yowsup.common.http.warequest - Sending GET request to /v2/code?ENC=Ms9qYref%2bvTSr%2bxZjXTu2jy%2ftTWD87f7im1voL82s3P8FFTyEguLD7d9mANkva3ppb7oDX4tHEvgPpDIvFDFBJ9QpSFeIB7pHdm%2fcJvFxIQjbrAR3Cy95EPyweHBC%2bzyGlebr%2f5alg%2bXOcj8d8lQnH8hijWGNcBgk%2febb0EolfS7y4e2wJak8pdFjypM%2f5X3K%2fpQ91Y%2brHbC6bw%3d%3d
I 2023-03-18 18:16:12,271 yowsup.common.http.warequest - b'{"login":"9--------41","reason":"old_version","status":"fail"}\n'
status: b'fail'
reason: b'old_version'
login: b'9---------1
```

**Comment by ghost** [comment]
> **When I return the WhatsApp verification code when logging in I get the following error message Does anyone know how to solve this??? It seems that the issue is with the "edge_routing_info" field in the response from the server, which is returning 'NoneType' instead of a bytes-like object or an ASCII string. This is causing a TypeError to be raised when trying to decode it using the base64 library.** _[Using Kali Linux on VMWARE Distributor ID: Kali Description: Kali GNU/Linux Rolling Release: 2022.4 Python version: Python 3.10.9]_
> 
> ```
> yowsup-cli registration --register 9****4 --config-phone 97********41 --config-cc ***
> yowsup-cli  v3.2.0
> yowsup      v3.2.3
> Copyright (c) 2012-2019 Tarek Galal
> http://www.openwhatsapp.org
> This software is provided free of charge. Copying and redistribution is
> encouraged.
> If you appreciate this software and you would like to support future
> development please consider donating:
> http://openwhatsapp.org/yowsup/donate
> I 2023-01-16 16:10:30,788 yowsup.common.http.warequest - b'{"autoconf_type":1,"lid":"279924745199757","login":"972******41","security_code_set":false,"status":"ok","type":"existing"}\n'
> {    "__version__": 1,
>     "cc": "972",
>     "client_static_keypair": "yOXCdgcysa/J33FMUaxqQiOB5hy09RoK5SKj0a357F5A9duLeFoY6jofwfkPwN7SOPCjp3gA9GJlDsupwlkYNw==",
>     "expid": "otCUMgMfTByHzDRfUtsWEg==",
>     "fdid": "5da6df4e-8fdf-49d2-b61d-d02fa959d150",
>     "id": "HieIi9riBSIJBNyYbjmLOZND0MI=",
>     "mcc": "4*5",
>     "mnc": "08",
>     "phone": "97*****041",
>     "sim_mcc": "000",
>     "sim_mnc": "000"}
> Traceback (most recent call last):
>   File "/usr/local/bin/yowsup-cli", line 679, in <module>
>     if not parser.process():
>   File "/usr/local/bin/yowsup-cli", line 352, in process
>     self.handleRegister(self.args["register"], config)
>   File "/usr/local/bin/yowsup-cli", line 384, in handleRegister
>     self._config.edge_routing_info = base64.b64decode(result["edge_routing_info"])
>   File "/usr/lib/python3.10/base64.py", line 80, in b64decode
>     s = _bytes_from_decode_data(s)
>   File "/usr/lib/python3.10/base64.py", line 45, in _bytes_from_decode_data
>     raise TypeError("argument should be a bytes-like object or ASCII "
> TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
> ```

any solution ?

**Comment by aliaksandrprus** [comment]
current version for noise protocol 5.3
    HEADER = b'WA\x05\x03'

https://github.com/tgalal/yowsup/blob/master/yowsup/layers/noise/layer.py#L32
https://github.com/tgalal/yowsup/blob/master/yowsup/layers/noise/layer.py#L39

these updates also affect token dictionaries and something else

https://github.com/tgalal/yowsup/blob/master/yowsup/layers/coder/tokendictionary.py

**Comment by aadog** [comment]
https://t.me/wslastver2024
I also have a new version，And update in real-time

**Comment by ben221199** [comment]
@aadog Yo mate, stop. This is just spamming everywhere.
