### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by miloira** [tgalal/yowsup#3240]
```
python cli.py registration --requestcode voice --config-phone 8613297169182 --config-cc 86 --config-mcc 460 --config-mnc 01 -d 
D 2023-10-16 11:25:54,949 yowsup.config.manager - load(path_or_profile_name=8613297169182, profile_only=False)
D 2023-10-16 11:25:54,949 yowsup.config.manager - _load_path(path=8613297169182)
D 2023-10-16 11:25:54,950 yowsup.config.manager - _load_path couldn't find the path: 8613297169182
D 2023-10-16 11:25:54,950 yowsup.config.manager - path_or_profile_name is not a path, using it as profile name
D 2023-10-16 11:25:54,953 yowsup.config.manager - Detecting config for profile=8613297169182, dir=C:\Users\69012\AppData\Local\yowsup\yowsup\8613297169182
D 2023-10-16 11:25:54,953 yowsup.config.manager - Trying C:\Users\69012\AppData\Local\yowsup\yowsup\8613297169182\config.yo
D 2023-10-16 11:25:54,953 yowsup.config.manager - Trying C:\Users\69012\AppData\Local\yowsup\yowsup\8613297169182\config.json
E 2023-10-16 11:25:54,953 yowsup.config.manager - Could not find a config for profile=8613297169182, paths checked: 8613297169182:C:\Users\69012\AppData\Local\yowsup\yowsup\8613297169182\config.yo:C:\Users\69012\AppData\Local\yowsup\yowsup\8613297169182\config.json
D 2023-10-16 11:25:54,953 yowsup.profile.profile - Constructed Profile(profile_name=8613297169182)
yowsup-cli     v3.2.1
yowsup         v3.3.0
consonance     v0.1.5
dissononce     v0.34.3
python-axolotl v0.2.2
cryptography   v41.0.4
protobuf       v3.20.2


Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


W 2023-10-16 11:25:55,000 yowsup.common.http.warequest - Passing Config to WARequest is deprecated, pass a YowProfile instead
D 2023-10-16 11:25:55,001 yowsup.profile.profile - Constructed Profile(profile_name=8613297169182)
D 2023-10-16 11:25:55,001 yowsup.axolotl.factory - get_manager(profile_name=8613297169182, username=8613297169182)
D 2023-10-16 11:25:55,024 yowsup.axolotl.manager - Initialized AxolotlManager [username=8613297169182, db=C:\Users\69012\AppData\Local\yowsup\yowsup\8613297169182\axolotl.db]
D 2023-10-16 11:25:55,025 yowsup.axolotl.manager - load_latest_signed_prekey
D 2023-10-16 11:25:55,026 yowsup.axolotl.manager - generate_signed_prekey
D 2023-10-16 11:25:55,026 yowsup.axolotl.manager - load_latest_signed_prekey
D 2023-10-16 11:25:55,030 yowsup.env.env - Env not set, setting it to android
D 2023-10-16 11:25:55,030 yowsup.env.env - Current env changed to android
D 2023-10-16 11:25:55,030 yowsup.common.http.warequest - send(parser=None, encrypt=True, preview=False)
D 2023-10-16 11:25:55,030 yowsup.common.http.warequest - sendGetRequest(parser=None, encrypt_params=True, preview=False)
D 2023-10-16 11:25:55,030 yowsup.common.http.warequest - Encrypting parameters
D 2023-10-16 11:25:55,031 yowsup.common.http.warequest - pre-encrypt (encoded) parameters =
cc=86&in=13297169182&lg=en&lc=GB&mistyped=6&authkey=rGYAMamPNhS6NhbhoV%2dyzeKeSMFZ2K9i9aJ8I%5fx%5fEnk&e_regid=SN4uTQ&e_keytype=BQ&e_ident=tvLTEMzAPTtwEQz1nDiJIwClCf%2ddvFJ8r8qURf3FVjU&
e_skey_id=AAAA&e_skey_val=tcCP9%5fjZ%5fCJYE7jQNTfJ6ljk9If%5fJYD7FsAu48SM%2dlY&e_skey_sig=oP%2dgrf55xkWZog7dvOjwCzItqnewZlOtSbOWWfEcG4cyPLKag9BcDpB%5f6nWMVlZsXpolt%2dTEZ1ZUSdypAoKugw&fd
id=8fe2c1f6%2da806%2d4c18%2d850d%2dfc1c7e188b2b&expid=Hf2xFmiSTdGMpx0VWa%2dAnQ&network_radio_type=1&simnum=1&hasinrc=1&pid=5878&rc=0&mcc=460&mnc=001&sim_mcc=000&sim_mnc=000&method=voice&reason=&token=oYUf8VIiDSgPPz0%2fDLbO4d4qqpg%3d&hasav=1&id=%2cBOLA%a7%e6%0c9%9eo%b5%b3%18R%e0w%1d%3d%e4
D 2023-10-16 11:25:55,032 yowsup.common.http.warequest - sendRequest(host=v.whatsapp.net, port=443, path=/v2/code, headers={'User-Agent': 'WhatsApp/2.21.21.18 Android/8.0.0 Device/sams
ung-star2lte', 'Accept': 'text/json'}, params=[('ENC', b'fL/mCqg2im6YuVewLk+JeCC0xHR+MnSRJBFQKD9D5yt8thpyGYzrNSH0Eqn2lgPiUg8AytJevO+UXB2Bib2RJO7RqQ0SCGVTO+2pNUTprdwfX6ylFIloVh6BK2932aa
50lvYEk0FHIPahBkNkfZ9ljmeDjO2/+WUvcJ0xrfolaAAag+2QtyXAsiOQ9l5f9VO+aG3dg26gs2WCJZJLu6Ey3s/sthJU62xXI3W4kORv4mB/yVfVni6aC8pVjGjaWGe+wsHDTLEgXWIlZ6DBEl/EfXr2v85mHJMLQYMR5o/GX+k7LlFugwTvYQ
sylv5tXY0pStpvb2NP3HCqtKJXWs3HUZeTu0u9F6BGVQaTeFwEpW6PNLgh3i1fg3eWhJZf8bDYRARyMRwwBm4+deZEELfQ7YaDYJQpZsgdgBrIRQwjq6NfVny1KtSzSiS5CIKNxTFhaRlf7267cMtkTKfO0a64OZXLkJhUJVKEjtfrRhg5ObkNVB
qJDkCQeqjlvntZj1zxTn4PEE71L0uFvl2TLaxhSyj2Y9VSCGBOSje37Zdm3NhW59JhJqXy7U4ArUVmURPPzbQfT7Tk3uiei39rx+AxUmntWLW8BY127bnTYdw4DPgexDcQWiM98rsltm4gN7Ko1PBBuo+fgy7sSiO5mJ7FueLtGzHXJaJckCvJ2C
wfFEUceSo/oEx/MG6adF6xWQdPNBGNTPUUKceP04wVis1Hvv0ZaodJE4+gubAbhFTcDnr4DdW7Q5muI+FqyC4iRMhjIaf0G2qag6KrcV2uE1Jbpj0N+KbNTBmVYlD6j+ra7Z56zHWCy8JBevSB9Yh6ZFcoag65ck24GeuACHtQsDUiJ6EGYmE1oiTS7PhABCVz2rV+UiDvXT+WohWfm4RpZljs2dCugr9PNK5tODUd9g2SX3l9feR5vj+IWAPR65ZEKc=')], reqType=GET, preview=False)
D 2023-10-16 11:25:55,034 yowsup.common.http.warequest - Opening connection to v.whatsapp.net
D 2023-10-16 11:25:55,119 yowsup.common.http.warequest - Sending GET request to /v2/code?ENC=fL%2fmCqg2im6YuVewLk%2bJeCC0xHR%2bMnSRJBFQKD9D5yt8thpyGYzrNSH0Eqn2lgPiUg8AytJevO%2bUXB2Bib2
RJO7RqQ0SCGVTO%2b2pNUTprdwfX6ylFIloVh6BK2932aa50lvYEk0FHIPahBkNkfZ9ljmeDjO2%2f%2bWUvcJ0xrfolaAAag%2b2QtyXAsiOQ9l5f9VO%2baG3dg26gs2WCJZJLu6Ey3s%2fsthJU62xXI3W4kORv4mB%2fyVfVni6aC8pVjGja
WGe%2bwsHDTLEgXWIlZ6DBEl%2fEfXr2v85mHJMLQYMR5o%2fGX%2bk7LlFugwTvYQsylv5tXY0pStpvb2NP3HCqtKJXWs3HUZeTu0u9F6BGVQaTeFwEpW6PNLgh3i1fg3eWhJZf8bDYRARyMRwwBm4%2bdeZEELfQ7YaDYJQpZsgdgBrIRQwjq6
NfVny1KtSzSiS5CIKNxTFhaRlf7267cMtkTKfO0a64OZXLkJhUJVKEjtfrRhg5ObkNVBqJDkCQeqjlvntZj1zxTn4PEE71L0uFvl2TLaxhSyj2Y9VSCGBOSje37Zdm3NhW59JhJqXy7U4ArUVmURPPzbQfT7Tk3uiei39rx%2bAxUmntWLW8BY12
7bnTYdw4DPgexDcQWiM98rsltm4gN7Ko1PBBuo%2bfgy7sSiO5mJ7FueLtGzHXJaJckCvJ2CwfFEUceSo%2foEx%2fMG6adF6xWQdPNBGNTPUUKceP04wVis1Hvv0ZaodJE4%2bgubAbhFTcDnr4DdW7Q5muI%2bFqyC4iRMhjIaf0G2qag6KrcV2uE1Jbpj0N%2bKbNTBmVYlD6j%2bra7Z56zHWCy8JBevSB9Yh6ZFcoag65ck24GeuACHtQsDUiJ6EGYmE1oiTS7PhABCVz2rV%2bUiDvXT%2bWohWfm4RpZljs2dCugr9PNK5tODUd9g2SX3l9feR5vj%2bIWAPR65ZEKc%3d
Traceback (most recent call last):
  File "C:\Users\69012\Desktop\jst\whatsup\cli.py", line 722, in <module>
    if not parser.process():
  File "C:\Users\69012\Desktop\jst\whatsup\cli.py", line 387, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "C:\Users\69012\Desktop\jst\whatsup\cli.py", line 399, in handleRequestCode
    result = codeReq.send(encrypt=self._encrypt, preview=self._preview)
  File "C:\Users\69012\AppData\Local\Programs\Python\Python310\lib\site-packages\yowsup-3.3.0-py3.10.egg\yowsup\registration\coderequest.py", line 46, in send
    res = super(WACodeRequest, self).send(parser, encrypt=encrypt, preview=preview)
  File "C:\Users\69012\AppData\Local\Programs\Python\Python310\lib\site-packages\yowsup-3.3.0-py3.10.egg\yowsup\common\http\warequest.py", line 141, in send
    return self.sendGetRequest(parser, encrypt, preview=preview)
  File "C:\Users\69012\AppData\Local\Programs\Python\Python310\lib\site-packages\yowsup-3.3.0-py3.10.egg\yowsup\common\http\warequest.py", line 213, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET", preview=preview)
  File "C:\Users\69012\AppData\Local\Programs\Python\Python310\lib\site-packages\yowsup-3.3.0-py3.10.egg\yowsup\common\http\warequest.py", line 302, in sendRequest
    conn.request(reqType, path, params, headers)
  File "C:\Users\69012\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\69012\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\69012\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\69012\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\69012\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\69012\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1447, in connect
    super().connect()
  File "C:\Users\69012\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 941, in connect
    self.sock = self._create_connection(
  File "C:\Users\69012\AppData\Local\Programs\Python\Python310\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\Users\69012\AppData\Local\Programs\Python\Python310\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
```

**Comment by miloira** [comment]
C:\Users\69012>ping v.whatsapp.net

正在 Ping v.whatsapp.net [69.63.178.13] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

69.63.178.13 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

**Comment by Rodrigosolari** [comment]
use VPN, or proxy

**Comment by miloira** [comment]
> use VPN, or proxy

thanks for your help,I sovled this problem by using proxy.

**Comment by miloira** [comment]
But there are new problems.
D 2023-10-16 17:11:48,047 yowsup.common.http.warequest - Opening connection to v.whatsapp.net
D 2023-10-16 17:11:48,117 yowsup.common.http.warequest - Sending GET request to /v2/code?ENC=1sQhmvs1qO4l4BG5AgEF%2bQpMk8p%2bSZEClIJIIqK7HHGq9VF4S6n9ipfSFQ%2ff9%2fMP0to4grH1ML3z%2fvYDa
P2sM7T2q%2fbDSLdzH4hal8vRJ7SN7QsLlL8zQQpqUV67xlI7%2bq%2bpT1o4mzoMf1YoI6YTy7ieylqtZUtPjDYR0PYT7v6lBPWSquFNurmJs6ARJIbj2ypLVXmE%2f%2bewTpDoRq3q2Fo%2fdXMllPAd7nf8cGMqVCQ7f27h%2by%2b4%2f7p
kS1RhOAzDqIHiHqp3O6hIpCgFW9vaPcIMFeExSmishSdxXu1O0qY13QkdPLuZO7u2MZIt%2fVqenQFLDTVv479%2fDs5wrnL%2fwFRI29wcFrhjCenuFy4bT%2bDbo3OQEfoRKz6ddrAZYhlnqhqST2He43FOPv2GSYlCH6ni%2f7KXux%2fMofZ
dUMND3yCnQwBurMdnjWRj6jY79hHf9wUbxZskXRM1JwfLCQMBOuueEdjJrCVnIXDDthI2bMLQFQOB3apNhLplvzJ3Z9%2fqHvOaPKL%2fmNxafayme8lDGgNygd%2fff5djPhskMpM%2bCB0Hh1IDTl7Mt7oekLfBW4DGS%2fW%2fP%2bEsdwAkG
IWl03%2fhAVrxwcwcvPGaz84O8TJtk3CzIydavP4gr5TnT7EwY0e0ycPpYBhK%2b6ISV3fSEUnc8qJAdu7Crip8ET29OnFYfYPUYW3zsP2wxMjem4bAYuVkKj2p9qwcbGe27RmCV2CebISXBPx45gsZwhhei1lEetvCvPLCWeAP22f9d%2fIlwCK
6H88FAek7qlOXoN%2fQylbmIgyp%2bt8cA5laEtp%2bQaMEVoaj0w%2fh127wvztM9KIG9ZD8Ykrg6ikm3TO%2brXyZIOxGIZBD9hfyLmunMAIFr43ZEOLnhAiSDu99BrOn2ZUWU%2bRzbbodA9kOSLTvQ%2fuYLie6GfT0vIgzgvA%2b2mQRUOrtxr6mCg%3d%3d
I 2023-10-16 17:11:48,756 yowsup.common.http.warequest - b'{"login":"8613297169182","reason":"old_version","status":"fail"}\n'
status: b'fail'
reason: b'old_version'
login: b'8613297169182'

**Comment by Rodrigosolari** [comment]
update env_android yowsup/env/env_android.py

    _MD5_CLASSES = 'BUEwqjsx9OXwzmq9sTA4bw=='
    _VERSION = "2.23.18.71" # 2.20.206.24

**Comment by miloira** [comment]
god,too much problems.
2023-10-16 17:28:10,508 yowsup.common.http.warequest - b'{"email_otp_wait":0,"flash_type":1,"login":"8613297169182","reason":"no_routes","retry_after":3600,"sms_wait":0,"status":"fail","voice_wait":0,"wa_old_wait":0}\n'
status: b'fail'
reason: b'no_routes'
retry_after: 3600
login: b'8613297169182'
sms_wait: 0
voice_wait: 0

**Comment by Rodrigosolari** [comment]
I'm left there, I don't have a solution for the env, I'm sure the metrics are sending an error, the env is used to register it android, but no one wants to share it

**Comment by miloira** [comment]
@Rodrigosolari thank you again,I solved these problems.

**Comment by miloira** [comment]
now this output like
I 2023-10-16 17:35:05,781 yowsup.common.http.warequest - b'{"login":"8613697169182","reason":"code_checkpoint","status":"fail"}\n'
status: b'fail'
reason: b'code_checkpoint'
login: b'8613697169182'

**Comment by wanxings** [comment]
> 现在这个输出就像 我 2023-10-16 17:35:05,781 yowsup.common.http.warequest - b'{"login":"8613697169182","re​​ason":"code_checkpoint","status":"fail"} \n' 状态：b'失败' 原因：b'code_checkpoint' 登录：b'8613697169182'
There is a branch for processing graphical verification codes. Someone has answered the search question.

**Comment by Whomakes** [comment]
> @Rodrigosolari thank you again,I solved these problems.

please tell me how you solved the problem!

**Comment by Rodrigosolari** [comment]
Telegram ID @dodysol

**Comment by RobLinux** [comment]
Just re-ask the code with "method" = "captcha". In the answer you'll get "image_blob" as PNG containing the code. enjoy

**Comment by RobLinux** [comment]
https://github.com/WhiskeySockets/Baileys/issues/277

**Comment by RobLinux** [comment]
https://github.com/WhiskeySockets/Baileys/issues/364

**Comment by Teyae** [comment]
> > use VPN, or proxy
> 
> thanks for your help,I sovled this problem by using proxy.

Hi, can you share how you proxy it?
