### ISSUE TITLE
''module' object has no attribute 'logger'

### ISSUE THREAD

**Issue by arternauta** [tgalal/yowsup#407]
I tried to use yowsup-cli and I get this error
AttributeError: 'module' object has no attribute 'logger'

I don't know how to start with 2.0 version

**Comment by ThomasRgbg** [comment]
I had a similar issue. When just using pip install pyreadline, it installed 2.0 (Distro is raspbian), then I got
```
 python yowsup-cli demos -y 
Traceback (most recent call last):
  File "yowsup-cli", line 304, in <module>
    if not parser.process():
  File "yowsup-cli", line 223, in process
    self.startCmdline()
  File "yowsup-cli", line 243, in startCmdline
    from yowsup.demos import cli
  File "/home/pi/fanti/yowsup.git/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/home/pi/fanti/yowsup.git/yowsup/demos/cli/stack.py", line 3, in <module>
    from .layer import YowsupCliLayer
  File "/home/pi/fanti/yowsup.git/yowsup/demos/cli/layer.py", line 1, in <module>
    from .cli import Cli, clicmd
  File "/home/pi/fanti/yowsup.git/yowsup/demos/cli/cli.py", line 9, in <module>
    import pyreadline as readline
  File "/usr/local/lib/python2.7/dist-packages/pyreadline-2.0-py2.7.egg/pyreadline/__init__.py", line 11, in <module>
    from . import unicode_helper, logger, clipboard, lineeditor, modes, console
  File "/usr/local/lib/python2.7/dist-packages/pyreadline-2.0-py2.7.egg/pyreadline/modes/__init__.py", line 3, in <module>
    from . import emacs, notemacs, vi
  File "/usr/local/lib/python2.7/dist-packages/pyreadline-2.0-py2.7.egg/pyreadline/modes/emacs.py", line 11, in <module>
    import pyreadline.logger as logger
AttributeError: 'module' object has no attribute 'logger'
```
However, when I used pip install pyreadline==1.7.1 as mentioned above, it worked. 

I agree its a distro thing, but still strange....

**Comment by Liyaguan** [comment]
> In case it's related to pyreadline, Can you install python readline pkg and post whether everything worked ? `pip install readline` if you use pip

i have installed pyreadline,but,it didn't work
