### ISSUE TITLE
Reconnect does not work

### ISSUE THREAD

**Issue by ThomasRgbg** [tgalal/yowsup#417]
Hi Tarek, 

as followup of #402, I tried 

```python
if event.getName() == YowNetworkLayer.EVENT_STATE_DISCONNECTED:
    print("Got EVENT_STATE_DISCONNECTED")
    time.sleep(10)
    print("Issueing EVENT_STATE_CONNECT")
    self.getStack().broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))        

```

But then I get

```
Got EVENT_STATE_DISCONNECTED
Issueing EVENT_STATE_CONNECT
onEvent: Unknown Event: org.openwhatsapp.yowsup.event.network.connect
Traceback (most recent call last):
  File "./whatsapp_user.py", line 52, in <module>
    stack.loop(timeout=2, count=1) #this is the program mainloop
  File "/usr/local/lib/python2.7/dist-packages/yowsup-2.0.1-py2.7.egg/yowsup/stacks/yowstack.py", line 44, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 220, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
select.error: (9, 'Bad file descriptor')
```

**Comment by relima** [comment]
from time to time I get to this error.. It seems to be the same.

_server.py_	[ERROR][2016-01-03 11:50:02,405] Authentication Error: Unhandled stream:error node:
<stream:error>
<xml-not-well-formed>
</xml-not-well-formed>
</stream:error>
Traceback (most recent call last):
  File "server.py", line 37, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "/home/mestre/bot/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/mestre/bot/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/home/mestre/bot/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/home/mestre/bot/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/mestre/bot/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/mestre/bot/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/home/mestre/bot/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/mestre/bot/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/mestre/bot/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/mestre/bot/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/mestre/bot/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/mestre/bot/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/mestre/bot/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/mestre/bot/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/mestre/bot/yowsup/layers/axolotl/layer.py", line 126, in receive
    self.toUpper(protocolTreeNode)
  File "/home/mestre/bot/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/home/mestre/bot/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/home/mestre/bot/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/home/mestre/bot/yowsup/layers/auth/layer_authentication.py", line 89, in handleStreamError
    raise AuthError("Unhandled stream:error node:\n%s" % node)
AuthError: Unhandled stream:error node:
<stream:error>
<xml-not-well-formed>
</xml-not-well-formed>
</stream:error>

_server.py_	[INFO][2016-01-03 11:50:06,361] Restarting..
_server.py_	[INFO][2016-01-03 11:50:06,943] 

_server.py_	[INFO][2016-01-03 11:50:07,055] #####################################
_server.py_	[INFO][2016-01-03 11:50:07,056] Server started. Number: 55xxxxxxxxxxx
_server.py_	[INFO][2016-01-03 11:50:07,056] #####################################
_server.py_	[ERROR][2016-01-03 11:50:07,056] Unexpected Exception: 
Traceback (most recent call last):
  File "server.py", line 37, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "/home/mestre/bot/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
error: (9, 'Bad file descriptor')
_server.py_	[INFO][2016-01-03 11:50:07,232] Restarting..
_server.py_	[INFO][2016-01-03 11:50:07,325] 

_server.py_	[INFO][2016-01-03 11:50:07,325] #####################################
_server.py_	[INFO][2016-01-03 11:50:07,325] Server started. Number: 55xxxxxxxxxxx
_server.py_	[INFO][2016-01-03 11:50:07,325] #####################################
_server.py_	[ERROR][2016-01-03 11:50:07,326] Unexpected Exception: 
Traceback (most recent call last):
  File "server.py", line 37, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "/home/mestre/bot/yowsup/stacks/yowstack.py", line 187, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
error: (9, 'Bad file descriptor')
_server.py_	[INFO][2016-01-03 11:50:07,326] Restarting..
_server.py_	[INFO][2016-01-03 11:50:07,505]

**Comment by CreatorSky** [comment]
Modify /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py and set the default of use_poll from False to True:

Line 207:

`def loop(timeout=30.0, use_poll=False, map=None, count=None):`

to

`def loop(timeout=30.0, use_poll=True, map=None, count=None):`

and that solved my issue .
Best of luck.
