### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by pickfire** [tgalal/yowsup#459]
I had register and setup the config. When I run ```$ yowsup-cli demos --yowsup --config config```:
```
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
Auth: Logged in!
[connected]:Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.0.53', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 296, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 234, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 257, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/stacks/yowstack.py", line 41, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/network/layer.py", line 46, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/network/layer.py", line 53, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/__init__.py", line 52, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/__init__.py", line 52, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/__init__.py", line 52, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/__init__.py", line 52, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/__init__.py", line 52, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/__init__.py", line 124, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/__init__.py", line 86, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/protocol_notifications/layer.py", line 24, in recvNotification
    self.raiseErrorForNode(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/yowsup/layers/__init__.py", line 102, in raiseErrorForNode
    raise ValueError("Unimplemented notification type %s " % node)
ValueError: Unimplemented notification type <notification retry="4" from="60122548620@s.whatsapp.net" t="1416228220" offline="4" type="picture" id="1839516731" notify="Nabil Yunos">
<delete jid="60122548620@s.whatsapp.net">
</delete>
</notification>
```

**Comment by rlimosenero** [comment]
Hi, 
I get this error. Please help

run this:
/L

  File "C:\Python26\lib\asyncore.py", line 141, in poll
    read(obj)
  File "C:\Python26\lib\asyncore.py", line 78, in read
    obj.handle_error()
  File "C:\Python26\lib\asyncore.py", line 74, in read
    obj.handle_read_event()
  File "C:\Python26\lib\asyncore.py", line 413, in handle_read_event
    self.handle_read()
  File "C:\yowsup-master\yowsup\layers\network\layer.py", line 47, in handle_read
    self.receive(data)
  File "C:\yowsup-master\yowsup\layers\network\layer.py", line 54, in receive
    self.toUpper(data)
  File "C:\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\yowsup-master\yowsup\layers\stanzaregulator\layer.py", line 28, in receive
    self.processReceived()
  File "C:\yowsup-master\yowsup\layers\stanzaregulator\layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "C:\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\yowsup-master\yowsup\layers\auth\layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "C:\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\yowsup-master\yowsup\layers\coder\layer.py", line 33, in receive
    node = self.reader.getProtocolTreeNode(data)
  File "C:\yowsup-master\yowsup\layers\coder\decoder.py", line 13, in getProtocolTreeNode
    return self.streamStart(data)
  File "C:\yowsup-master\yowsup\layers\coder\decoder.py", line 29, in streamStart
    size = self.readListSize(tag, data)
  File "C:\yowsup-master\yowsup\layers\coder\decoder.py", line 95, in readListSize
    raise Exception("invalid list size in readListSize: token " + str(token))
Exception: invalid list size in readListSize: token -8

C:\yowsup-master>

**Comment by tgalal** [comment]
Fixed

**Comment by amarent** [comment]
Hi, I get this error
Please help!!!

[offline]:/L
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.7', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 268, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 297, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/demos/cli/stack.py", line 26, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/stacks/yowstack.py", line 189, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 162, in poll
    write(obj)
  File "/usr/lib/python2.7/asyncore.py", line 95, in write
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python2.7/asyncore.py", line 467, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python2.7/asyncore.py", line 455, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/network/layer.py", line 82, in handle_connect
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 65, in onConnected
    if self.isInitState():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/axolotl/layer_control.py", line 47, in isInitState
    return self.store == None or self.state == self.__class__._STATE_INIT
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/axolotl/layer_base.py", line 37, in store
    self.__class__._DB
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.5.7-py2.7.egg/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 10, in __init__
    conn = sqlite3.connect(db, check_same_thread=False)
sqlite3.OperationalError: unable to open database file

**Comment by jpf198** [comment]
@amarent did you solve that error as im gettgin the same thing?

"sqlite3.OperationalError: unable to open database file"

**Comment by outrageousaman** [comment]
i am also getting same error
