### ISSUE TITLE
registration error

### ISSUE THREAD

**Issue by DhirManish** [tgalal/yowsup#497]
aftre running this command 
---------------------------
python yowsup-cli registration --debug --mcc 404 --mnc 14 --phone 9198******** -C 91 --id 000000000000000 -r sms
--------------------------- i got this
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/manishdhir/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "yowsup-cli", line 6, in <module>
    from yowsup.demos import cli, echoclient, sendclient
  File "/home/manishdhir/Data/yyy/yowsup/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/home/manishdhir/Data/yyy/yowsup/yowsup/demos/cli/stack.py", line 2, in <module>
    from yowsup.layers.axolotl import YowAxolotlLayer
  File "/home/manishdhir/Data/yyy/yowsup/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/home/manishdhir/Data/yyy/yowsup/yowsup/layers/axolotl/layer.py", line 3, in <module>
    from axolotl.util.keyhelper import KeyHelper
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.1-py2.7.egg/axolotl/util/keyhelper.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.1-py2.7.egg/axolotl/identitykeypair.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.1-py2.7.egg/axolotl/state/storageprotos.py", line 9, in <module>
ImportError: cannot import name symbol_database
manishdhir@manishdhir-HP-d530-SFF-DG058A:~/Data/yyy/yowsup$ python yowsup-cli 
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/manishdhir/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "yowsup-cli", line 6, in <module>
    from yowsup.demos import cli, echoclient, sendclient
  File "/home/manishdhir/Data/yyy/yowsup/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/home/manishdhir/Data/yyy/yowsup/yowsup/demos/cli/stack.py", line 2, in <module>
    from yowsup.layers.axolotl import YowAxolotlLayer
  File "/home/manishdhir/Data/yyy/yowsup/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/home/manishdhir/Data/yyy/yowsup/yowsup/layers/axolotl/layer.py", line 3, in <module>
    from axolotl.util.keyhelper import KeyHelper
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.1-py2.7.egg/axolotl/util/keyhelper.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.1-py2.7.egg/axolotl/identitykeypair.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.1-py2.7.egg/axolotl/state/storageprotos.py", line 9, in <module>
ImportError: cannot import name symbol_database

**Comment by GrumpyOldDog** [comment]
chmod g-wx,o-wx ~/.python-eggs

**Comment by tgalal** [comment]
@DhirManish still a problem ?

**Comment by DhirManish** [comment]
no, its been solved

**Comment by maruen** [comment]
@DhirManish  How did you solved? I still having the same problem here.
Appreciate any help, thanks

**Comment by widnyana** [comment]
@maruen symbol_database is part of protobuf. did you have that module on your machine? [ref](https://github.com/google/protobuf/blob/master/python/google/protobuf/symbol_database.py)

**Comment by maruen** [comment]
@widnyana Yes, I have it here, as you can see in pyton console after running this:
>>> from google import protobuf
>>> print(protobuf.__version__)
3.0.0-alpha-1
>>> 

Do you have any ideas on whats going on?

**Comment by maruen** [comment]
@widnyana  also in stack trace of the error I see this:
 File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/state/storageprotos.py", line 9, in <module>

and this path does not exist when I checked. I think it's related to not having this file at that location.
but I don't know how to fix it.

**Comment by widnyana** [comment]
@maruen if that so, take a look [here](https://github.com/tgalal/python-axolotl)

**Comment by maruen** [comment]
@widnyana  I think we had a progress.
afeter cloning the repository you passed me and installing it the error changed a litle bit to that.:

 File "build/bdist.linux-x86_64/egg/axolotl/state/storageprotos.py", line 9, in <module>
ImportError: cannot import name symbol_database

the path changed, but also, the path above still does not exists.
Any other clue?

**Comment by maruen** [comment]
@widnyana 
all the stack trace is:

yowsup-cli demos -c config  -s 5511984388499  "heyy"
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.2.78', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1649, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 304, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 227, in process
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 265, in startSendClient
    
  File "build/bdist.linux-x86_64/egg/yowsup/demos/sendclient/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/demos/sendclient/stack.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 22, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/axolotl/util/keyhelper.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/axolotl/identitykeypair.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/axolotl/state/storageprotos.py", line 9, in <module>

**Comment by maruen** [comment]
@widnyana 
and for what I checked, I have the directory below installed: 
/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.79.egg-info/

and not the directory that mentions on stack trace:
/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg

**Comment by widnyana** [comment]
@maruen sorry man, I have no idea.
