### ISSUE TITLE
Always get the same error "ImportError: No module named axolotl.state.prekeybundle" when i ask for the message confirmation

### ISSUE THREAD

**Issue by dudufcb** [tgalal/yowsup#500]
eduardo-poo@HP-Compaq-6200-Pro-MT-PC:~/yowsup-master$ sudo ./yowsup-cli --requestcode sms --config whatsapp_config.txt
Traceback (most recent call last):
  File "./yowsup-cli", line 6, in <module>
    from yowsup.demos import cli, echoclient, sendclient
  File "/home/eduardo-poo/yowsup-master/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/home/eduardo-poo/yowsup-master/yowsup/demos/cli/stack.py", line 2, in <module>
    from yowsup.layers.axolotl import YowAxolotlLayer
  File "/home/eduardo-poo/yowsup-master/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/home/eduardo-poo/yowsup-master/yowsup/layers/axolotl/layer.py", line 2, in <module>
    from .protocolentities import SetKeysIqProtocolEntity
  File "/home/eduardo-poo/yowsup-master/yowsup/layers/axolotl/protocolentities/__init__.py", line 3, in <module>
    from .iq_keys_get_result import ResultGetKeysIqProtocolEntity
  File "/home/eduardo-poo/yowsup-master/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 3, in <module>
    from axolotl.state.prekeybundle import PreKeyBundle
ImportError: No module named axolotl.state.prekeybundle

**Comment by tgalal** [comment]
did you run the installation again after latest updates ?

**Comment by aesedepece** [comment]
sudo pip install python-axolotl

**Comment by dudufcb** [comment]
How can i do the update? i've installed it yesterday, then i tried to install with: sudo pip install python-axolotl with no sucess. thanks

**Comment by tgalal** [comment]
Logs please

**Comment by micha137** [comment]
Had the same problem, needed to install python-dev package, then "pip install python-axolotl" worked fine.

**Comment by tgalal** [comment]
@dudufcb  reopen if the suggested solution doesn't solve the problem.

**Comment by clarityworld** [comment]
Same Problem  :(

**Comment by cutec-chris** [comment]
sudo apt-get install python-pip python-dev build-essential 
sudo pip install --upgrade pip 
sudo pip install python-axolotl

works for me

**Comment by mutindaz** [comment]
@cutec-chris solution works pretty good

**Comment by rdiasfreitas** [comment]
Hi
do not use version 0.1.16...
the correct version of python-axolotl to be used with yowsup is 0.1.15.

**Comment by RaulCer** [comment]
Hi,
reinstall python-axolotl.

sudo pip uninstall python-axolotl
sudo pip install python-axolotl
