### ISSUE TITLE
ImportError: No module named _sqlite3

### ISSUE THREAD

**Issue by abdawoud** [tgalal/yowsup#511]
Dear All,

Thank you for your effort...

I am trying to use yowsup. I followed the guidelines carefully and installed all packages. 

Python version: 2.7.8

When I try to send a message or issue any command with yowsup-cli I receive: 

>>>>>>>>>>>>>

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.0.53', 'yowsup-cli')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 696, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1621, in run_script
  File "/usr/local/lib/python2.7/site-packages/yowsup2-2.0.53-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 6, in <module>
    
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/stack.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 4, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 6, in <module>
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3

>>>>>>>>>>>>>

I installed SQLite 3.7.9 and I still get the same error! 

What could be the problem?

Thanks

**Comment by tgalal** [comment]
check if python is compiled with sqlite support?

**Comment by abdawoud** [comment]
OK I will check how to do that. However, I appreciate if you tell me how.

Thanks
