### ISSUE TITLE
Yowsup 2.0 sample app does not run

### ISSUE THREAD

**Issue by tfvtfv** [tgalal/yowsup#513]
Executing run.py /layer.py sample applications from here
https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Sample-app

causes errors:

1.) Traceback (most recent call last):
  File "run.py", line 26, in <module>
AttributeError: class YowConstants has no attribute 'RESOURCE'

If you comment that line, assuming that RESOURCE is not necessary, you get another one:
2.)  Traceback (most recent call last):
  File "C:\Program Files (x86)\Wing IDE 101 5.0\src\debug\tserver\_sandbox.py", line 30, in <module>
  File "c:\Python27\lib\site-packages\yowsup2-2.0.53-py2.7.egg\yowsup\stacks\yowstack.py", line 57, in loop
  File "c:\Python27\Lib\asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "c:\Python27\Lib\asyncore.py", line 162, in poll
    write(obj)
  File "c:\Python27\Lib\asyncore.py", line 95, in write
    obj.handle_error()
  File "c:\Python27\Lib\asyncore.py", line 95, in write
    obj.handle_write_event()
  File "c:\Python27\Lib\asyncore.py", line 467, in handle_write_event
    self.handle_connect_event()
  File "c:\Python27\Lib\asyncore.py", line 455, in handle_connect_event
    self.handle_connect()
  File "c:\Python27\lib\site-packages\yowsup2-2.0.53-py2.7.egg\yowsup\layers\network\layer.py", line 33, in handle_connect
  File "c:\Python27\lib\site-packages\yowsup2-2.0.53-py2.7.egg\yowsup\layers\__init__.py", line 69, in emitEvent
  File "c:\Python27\lib\site-packages\yowsup2-2.0.53-py2.7.egg\yowsup\layers\__init__.py", line 69, in emitEvent
  File "c:\Python27\lib\site-packages\yowsup2-2.0.53-py2.7.egg\yowsup\layers\__init__.py", line 63, in emitEvent
  File "c:\Python27\lib\site-packages\yowsup2-2.0.53-py2.7.egg\yowsup\layers\coder\layer.py", line 23, in onEvent
  File "c:\Python27\lib\site-packages\yowsup2-2.0.53-py2.7.egg\yowsup\layers\coder\encoder.py", line 21, in getStreamStartBytes
  File "c:\Python27\lib\site-packages\yowsup2-2.0.53-py2.7.egg\yowsup\layers\coder\encoder.py", line 53, in writeAttributes
  File "c:\Python27\lib\site-packages\yowsup2-2.0.53-py2.7.egg\yowsup\layers\coder\encoder.py", line 123, in writeString
AttributeError: 'NoneType' object has no attribute 'index'

Sorry, I am a newbie and this is above my paygrade.

**Comment by addodelgrossi** [comment]
Using:

```
from yowsup import env
stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())
```

**Comment by tgalal** [comment]
@tfvtfv sorry sample app in wiki needed to be updated, I fixed it using @addodelgrossi suggestion. Thanks!

**Comment by tfvtfv** [comment]
Thanks for your quick help!

Thomas
Am 07.01.2015 um 08:39 schrieb Tarek:

**Comment by tfvtfv** [comment]
Thanks for your quick help!

Thomas

Am 07.01.2015 um 03:32 schrieb Addo:
