### ISSUE TITLE
Register Error

### ISSUE THREAD

**Issue by clarityworld** [tgalal/yowsup#527]
02:02 ~ $ python yowsup/yowsup-cli registration -r  sms --phone 4912345678 --cc 49 --mcc 123 --mnc 456
 
Traceback (most recent call last):
  File "yowsup/yowsup-cli", line 301, in <module>
    if not parser.process():
  File "yowsup/yowsup-cli", line 158, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup/yowsup-cli", line 175, in handleRequestCode
    result = codeReq.send()
  File "/home/clarityworld/yowsup/yowsup/registration/coderequest.py", line 52, in send
    res = super(WACodeRequest, self).send(parser)
  File "/home/clarityworld/yowsup/yowsup/common/http/warequest.py", line 67, in send
    return self.sendGetRequest(parser)
  File "/home/clarityworld/yowsup/yowsup/common/http/warequest.py", line 105, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET")
  File "/home/clarityworld/yowsup/yowsup/common/http/warequest.py", line 161, in sendRequest
    conn.request(reqType, path, params, headers);
  File "/usr/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
02:04 ~ $

**Comment by tgalal** [comment]
It's a connection problem. Have you tried again?

**Comment by clarityworld** [comment]
Yes many times

**Comment by tgalal** [comment]
Are you behind a proxy or something?

**Comment by clarityworld** [comment]
Well maybe the problem is that I use
www,pythonanywhere.com  ? Don't know about proxy :3

**Comment by karthikb351** [comment]
I'm facing the same issue.

```
File "build/bdist.macosx-10.10-x86_64/egg/yowsup/registration/coderequest.py", line 52, in send
  File "build/bdist.macosx-10.10-x86_64/egg/yowsup/common/http/warequest.py", line 67, in send
  File "build/bdist.macosx-10.10-x86_64/egg/yowsup/common/http/warequest.py", line 105, in sendGetRequest
  File "build/bdist.macosx-10.10-x86_64/egg/yowsup/common/http/warequest.py", line 161, in sendRequest
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

Seems to be an SSL error.

```
karthikbalakrishnan$ openssl s_client -connect c.whatsapp.net:443 -prexit
CONNECTED(00000003)
32809:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:/SourceCache/OpenSSL098/OpenSSL098-52/src/ssl/s23_lib.c:182:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 130 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
```

**Comment by clarityworld** [comment]
Changed from OS fixed it.

**Comment by amankharb** [comment]
Can someone tell me how this issue is fixed ?
