### ISSUE TITLE
Iq of type error is not implemented

### ISSUE THREAD

**Issue by dedmen** [tgalal/yowsup#536]
/contacts sync 49*,49*,49*,49*,49* (Censored none is my number)
[connected]:DEBUG:yowsup.layers.logger.layer:tx:
<iq xmlns="urn:xmpp:whatsapp:sync" type="get" id="1420990542-0">
<sync index="0" last="true" mode="full" context="interactive" sid="1.30654677424e+17">
<user>
49*</user>
<user>
49*</user>
<user>
49*</user>
<user>
49*</user>
<user>
49*</user>
</sync>
</iq>

DEBUG:yowsup.layers.logger.layer:rx:
<iq type="error" from="49*myNumber*@s.whatsapp.net" id="1420990542-0">
<error text="feature-not-implemented" code="501" backoff="3600">
</error>
</iq>

Traceback (most recent call last):
  File "/root/whatsappp/yowsup-cli", line 287, in <module>
    if not parser.process():
  File "/root/whatsappp/yowsup-cli", line 231, in process
    self.startCmdline()
  File "/root/whatsappp/yowsup-cli", line 253, in startCmdline
    stack.start()
  File "/root/whatsappp/yowsup/demos/cli/stack.py", line 27, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/root/whatsappp/yowsup/stacks/yowstack.py", line 41, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/root/whatsappp/yowsup/layers/network/layer.py", line 46, in handle_read
    self.receive(data)
  File "/root/whatsappp/yowsup/layers/network/layer.py", line 52, in receive
    self.toUpper(data)
  File "/root/whatsappp/yowsup/layers/__init__.py", line 52, in toUpper
    self.__upper.receive(data)
  File "/root/whatsappp/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/root/whatsappp/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/root/whatsappp/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/root/whatsappp/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/root/whatsappp/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/root/whatsappp/yowsup/layers/__init__.py", line 52, in toUpper
    self.__upper.receive(data)
  File "/root/whatsappp/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/root/whatsappp/yowsup/layers/__init__.py", line 52, in toUpper
    self.__upper.receive(data)
  File "/root/whatsappp/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/root/whatsappp/yowsup/layers/__init__.py", line 52, in toUpper
    self.__upper.receive(data)
  File "/root/whatsappp/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/root/whatsappp/yowsup/layers/__init__.py", line 52, in toUpper
    self.__upper.receive(data)
  File "/root/whatsappp/yowsup/layers/__init__.py", line 124, in receive
    s.receive(data)
  File "/root/whatsappp/yowsup/layers/__init__.py", line 86, in receive
    recv(node)
  File "/root/whatsappp/yowsup/layers/protocol_iq/layer.py", line 23, in recvIq
    self.toUpper(ErrorIqProtocolEntity.fromProtocolTreeNode(node))
  File "/root/whatsappp/yowsup/layers/protocol_iq/protocolentities/iq_error.py", line 30, in fromProtocolTreeNode
    entity = IqProtocolEntity.fromProtocolTreeNode(node)
  File "/root/whatsappp/yowsup/layers/protocol_iq/protocolentities/iq.py", line 63, in fromProtocolTreeNode
    node.getAttributeValue("from")
  File "/root/whatsappp/yowsup/layers/protocol_iq/protocolentities/iq.py", line 14, in __init__
    assert _type in self.__class__.TYPES, "Iq of type %s is not implemented, can accept only (%s)" % (_type," | ".join(self.__class__.TYPES))
AssertionError: Iq of type error is not implemented, can accept only (set | get | result)

**Comment by tgalal** [comment]
This is fixed as of 91ebdd349da221c82e36e0124b543231c9970a85, you need to update yowsup I guess
