### ISSUE TITLE
After work for some hour, then "Authentication Error: not-authorized" appear

### ISSUE THREAD

**Issue by salmanmumtaz** [tgalal/yowsup#537]
Hi Friends, after my yowsup running well for a 5 or 7 hour, then appear some error message when I try to send message using this command
$yowsup-cli demos -c conf.txt --send 9876543212345 "hellow"

the error messages is :
/usr/local/lib/python2.6/dist-packages/yowsup2-2.2.15-py2.6.egg/yowsup/demos/sendclient/stack.py:60: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
Authentication Error: not-authorized

When I try to register again using previous successful command (the same command I used to register), then this error appears :

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.2.15', 'yowsup-cli')
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 448, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1173, in run_script
    exec script_code in namespace, namespace
  File "/usr/local/lib/python2.6/dist-packages/yowsup2-2.2.15-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 304, in <module>

  File "/usr/local/lib/python2.6/dist-packages/yowsup2-2.2.15-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 156, in process

  File "/usr/local/lib/python2.6/dist-packages/yowsup2-2.2.15-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 174, in handleRequestCode

  File "build/bdist.linux-i686/egg/yowsup/registration/coderequest.py", line 44, in send
  File "build/bdist.linux-i686/egg/yowsup/registration/existsrequest.py", line 15, in __init__
  File "build/bdist.linux-i686/egg/yowsup/env/env_android.py", line 55, in getToken
TypeError: update() argument 1 must be string or read-only buffer, not bytearray

How to fix this?

**Comment by tgalal** [comment]
Is it fixed? Because python2.6 support was broken and should be fixed now

**Comment by salmanmumtaz** [comment]
Alhamdulillah it fixed.. Sorry it just because my fault in broadcast messages to many number simultaneously, then my number was temporarily blockage by whatsapp. 

Wrong case closed.
