### ISSUE TITLE
yowsup start error

### ISSUE THREAD

**Issue by daniel0916** [tgalal/yowsup#575]
Hello,

i can't start yowsup. Error:
daniel@daniel-notebook ~/Schreibtisch/WhatsApp-API/yowsup $ yowsup-cli demos --yowsup
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.2.15', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 696, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1621, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 304, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 223, in process
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 243, in startCmdline
    
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/stack.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/axolotl/util/keyhelper.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/axolotl/identitykeypair.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/axolotl/state/storageprotos.py", line 9, in <module>
ImportError: cannot import name symbol_database

**Comment by daniel0916** [comment]
I fixed it with installing a newer version of protobuf.
