### ISSUE TITLE
Uploading image failed (encoder jpeg not available)

### ISSUE THREAD

**Issue by onahoe** [tgalal/yowsup#577]
After running the following command in the cmd client, i got the error down below:
/image send 4917******** /home/pi/whatsapp/yowsup-master/yowsup/demos/WhatsApp/example2.jpg

ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer encoder jpeg not available
Traceback (most recent call last):
  File "/home/pi/yowsup-master/yowsup/layers/protocol_media/mediauploader.py", line 137, in run
    self.successCallback(sourcePath, self.jid, result["url"])
  File "/home/pi/yowsup-master/yowsup/demos/cli/layer.py", line 422, in onUploadSuccess
    self.doSendImage(filePath, url, jid)
  File "/home/pi/yowsup-master/yowsup/demos/cli/layer.py", line 401, in doSendImage
    entity = ImageDownloadableMediaMessageProtocolEntity.fromFilePath(filePath, url, ip, to)
  File "/home/pi/yowsup-master/yowsup/layers/protocol_media/protocolentities/message_media_downloadable_image.py", line 80, in fromFilePath
    preview = ImageTools.generatePreviewFromImage(path)
  File "/home/pi/yowsup-master/yowsup/common/tools.py", line 131, in generatePreviewFromImage
    if ImageTools.scaleImage(image, fileObj, "JPEG", YowConstants.PREVIEW_WIDTH, YowConstants.PREVIEW_HEIGHT):
  File "/home/pi/yowsup-master/yowsup/common/tools.py", line 110, in scaleImage
    im.save(outfile, imageFormat)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1682, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python2.7/dist-packages/PIL/JpegImagePlugin.py", line 696, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0)+im.size, 0, rawmode)], bufsize)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 488, in _save
    e = Image._getencoder(im.mode, e, a, im.encoderconfig)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 434, in _getencoder
    raise IOError("encoder %s not available" % encoder_name)
IOError: encoder jpeg not available
ERROR:yowsup.demos.cli.layer:Upload file /home/pi/whatsapp/yowsup-master/yowsup/demos/WhatsApp/example2.jpg to https://mmi624.whatsapp.net/u/-tDSXBnkXr5SZ8Zr_bk1cXRNU-kABQ1rBfmswA/ApSiPC1Zg52ADJgpp8V9abavZKOWU8P_urVyxip8SMfh for 491*********@s.whatsapp.net failed!

**Comment by douglasfsti** [comment]
- IOError: decoder jpeg not available
    http://stackoverflow.com/questions/8915296/python-image-library-fails-with-message-decoder-jpeg-not-available-pil
    http://pillow.readthedocs.org/en/latest/installation.html
```
sudo apt-get install libtiff4-dev libjpeg8-dev zlib1g-dev \
                     libfreetype6-dev liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev python-tk
sudo pip install -I pillow
```
