### ISSUE TITLE
yowsup-cli error from "/groups list" if list is empty.

### ISSUE THREAD

**Issue by danieldaboul** [tgalal/yowsup#580]
With
yowsup-cli v2.0.9
Using yowsup v2.2.15

"/groups list" in yowsup-cli works fine if the username belongs to a group
but gives me an error if the username does not belong to any group.
Transscript below:

[connected]:
/ping
[connected]:Iq:
ID: 3
Type: result
from: s.whatsapp.net

/groups list
[connected]:Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.2.15', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 487, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1344, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 304, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 223, in process
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 249, in startCmdline
    
  File "build/bdist.linux-i686/egg/yowsup/demos/cli/stack.py", line 42, in start
  File "build/bdist.linux-i686/egg/yowsup/stacks/yowstack.py", line 49, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-i686/egg/yowsup/layers/network/layer.py", line 48, in handle_read
  File "build/bdist.linux-i686/egg/yowsup/layers/network/layer.py", line 55, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 56, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 56, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 56, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 56, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 56, in toUpper
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 161, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 98, in receive
  File "build/bdist.linux-i686/egg/yowsup/layers/__init__.py", line 133, in processIqRegistry
  File "build/bdist.linux-i686/egg/yowsup/layers/protocol_groups/layer.py", line 61, in onListGroupsResult
  File "build/bdist.linux-i686/egg/yowsup/layers/protocol_groups/protocolentities/iq_result_groups_list.py", line 60, in fromProtocolTreeNode
  File "build/bdist.linux-i686/egg/yowsup/layers/protocol_groups/protocolentities/iq_result_groups_list.py", line 30, in setProps
AssertionError: groupList must be a list of Group instances

**Comment by msshapira** [comment]
fixed in my  PR  https://github.com/tgalal/yowsup/pull/569

**Comment by danieldaboul** [comment]
Thank you. I will try your code :-)

**Comment by danieldaboul** [comment]
The fix by msshapira works fine for me. I assume, I should leave this issue open until there's a fix in the trunk.
If not, feel free to close it.

**Comment by tgalal** [comment]
merged #569
