### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by bbtimx** [tgalal/yowsup#587]
C:\Python27>python yowsup-cli demos -l 49xxxxxxxxxxx8:C10vXxxxxx4ZO7/x
qtxxxxxxWOrvk= -s 49xxxxxxx9-1xxxxxxxxxx2 "Test"
Traceback (most recent call last):
  File "c:\Python27\yowsup-cli", line 304, in <module>
    if not parser.process():
  File "c:\Python27\yowsup-cli", line 227, in process
    self.startSendClient()
  File "c:\Python27\yowsup-cli", line 265, in startSendClient
    from yowsup.demos import sendclient
  File "c:\Python27\yowsup\demos\sendclient\__init__.py", line 1, in <module>
    from .stack import YowsupSendStack
  File "c:\Python27\yowsup\demos\sendclient\stack.py", line 12, in <module>
    from yowsup.layers.axolotl                     import YowAxolotlLayer
  File "c:\Python27\yowsup\layers\axolotl\__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "c:\Python27\yowsup\layers\axolotl\layer.py", line 2, in <module>
    from .protocolentities import SetKeysIqProtocolEntity
  File "c:\Python27\yowsup\layers\axolotl\protocolentities\__init__.py", line 3,
 in <module>
    from .iq_keys_get_result import ResultGetKeysIqProtocolEntity
  File "c:\Python27\yowsup\layers\axolotl\protocolentities\iq_keys_get_result.py
", line 4, in <module>
    from axolotl.identitykey import IdentityKey
  File "build/bdist.linux-x86_64/egg/axolotl/identitykey.py", line 1, in <module
>
  File "build/bdist.linux-x86_64/egg/axolotl/ecc/curve.py", line 1, in <module>
  File "build\bdist.win32\egg\axolotl_curve25519.py", line 7, in <module>
  File "build\bdist.win32\egg\axolotl_curve25519.py", line 6, in __bootstrap__
ImportError: DLL load failed: The specified module could not be found.

Can anyone help fix this issue?

OS: Win Server 2012 R2 x64
PIP installed
ez_setup installed
mingw installed
pycrypt installed
yowsup2 installed

**Comment by lcmeyer37** [comment]
I understand, I followed the installation section but I'm finding some errors when trying to run demos -s, -y for example. It says the same last message: DLL load failed.


c:\Python26\Scripts>python yowsup-cli demos -h
usage: demos [-h] [-v] [-d] [--help-config] [-l phone:b64password] [-c CONFIG]
             [-m] [-y] [-e] [-s phone message]

Run a yowsup demo

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         Print version info and exit
  -d, --debug           Show debug messages
  --help-config         Prints a config file sample

Configuration options for demos:
  -l phone:b64password, --login phone:b64password
                        WhatsApp login credentials, in the format
                        phonenumber:password, where password is base64
                        encoded.
  -c CONFIG, --config CONFIG
                        Path to config file containing authentication info.
                        For more info about config format use --help-config
  -m, --moxie           Enable experimental support for the new WhatsApp
                        encryption

Command line interface demo:
  -y, --yowsup          Start the Yowsup command line client

Echo client demo:
  -e, --echo            Start the Yowsup Echo client

Send client demo:
  -s phone message, --send phone message
                        Send a message to specified phone number, wait for
                        server receipt and exit

c:\Python26\Scripts>python yowsup-cli demos -e
Traceback (most recent call last):
  File "yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.2.78', 'yowsup-cli')
  File "build\bdist.win32\egg\pkg_resources\__init__.py", line 698, in run_scrip
t
  File "build\bdist.win32\egg\pkg_resources\__init__.py", line 1616, in run_scri
pt
  File "c:\python26\lib\site-packages\yowsup2-2.2.78-py2.6.egg\EGG-INFO\scripts\
yowsup-cli", line 304, in <module>
    if not parser.process():
  File "c:\python26\lib\site-packages\yowsup2-2.2.78-py2.6.egg\EGG-INFO\scripts\
yowsup-cli", line 225, in process
    self.startEcho()
  File "c:\python26\lib\site-packages\yowsup2-2.2.78-py2.6.egg\EGG-INFO\scripts\
yowsup-cli", line 252, in startEcho
    from yowsup.demos import echoclient
  File "C:\Python26\lib\site-packages\yowsup2-2.2.78-py2.6.egg\yowsup\demos\echo
client\__init__.py", line 1, in <module>
    from .stack import YowsupEchoStack
  File "C:\Python26\lib\site-packages\yowsup2-2.2.78-py2.6.egg\yowsup\demos\echo
client\stack.py", line 1, in <module>
    from yowsup.stacks import YowStack
  File "C:\Python26\lib\site-packages\yowsup2-2.2.78-py2.6.egg\yowsup\stacks\__i
nit__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "C:\Python26\lib\site-packages\yowsup2-2.2.78-py2.6.egg\yowsup\stacks\yow
stack.py", line 21, in <module>
    from yowsup.layers.axolotl import YowAxolotlLayer
  File "C:\Python26\lib\site-packages\yowsup2-2.2.78-py2.6.egg\yowsup\layers\axo
lotl\__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "C:\Python26\lib\site-packages\yowsup2-2.2.78-py2.6.egg\yowsup\layers\axo
lotl\layer.py", line 14, in <module>
    from axolotl.sessioncipher import SessionCipher
  File "build\bdist.win32\egg\axolotl\sessioncipher.py", line 2, in <module>
  File "c:\users\radio\appdata\local\temp\easy_install-w1nvtn\pycrypto-2.6-py2.6
-win32.egg.tmp\Crypto\Cipher\AES.py", line 50, in <module>
  File "c:\users\radio\appdata\local\temp\easy_install-w1nvtn\pycrypto-2.6-py2.6
-win32.egg.tmp\Crypto\Cipher\_AES.py", line 7, in <module>
  File "c:\users\radio\appdata\local\temp\easy_install-w1nvtn\pycrypto-2.6-py2.6
-win32.egg.tmp\Crypto\Cipher\_AES.py", line 6, in __bootstrap__
ImportError: DLL load failed: NÒo foi possÝvel encontrar o m¾dulo especificado.

c:\Python26\Scripts>
