### ISSUE TITLE
EchoClient does not work with encryption

### ISSUE THREAD

**Issue by jlguardi** [tgalal/yowsup#591]
I was trying to add encryption to my app but if I add YowAxolotlLayer to the stack as described in [EchoClient](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/echoclient/stack.py#L24) I get this exception:
```
DEBUG:yowsup.layers.logger.layer:rx:
<iq type="error" from="s.whatsapp.net" id="1">
<error text="not-authorized" code="401">
</error>
</iq>

Traceback (most recent call last):
  File "./yowsup-cli", line 304, in <module>
    if not parser.process():
  File "./yowsup-cli", line 225, in process
    self.startEcho()
  File "./yowsup-cli", line 259, in startEcho
    stack.start()
  File "./yowsup/demos/echoclient/stack.py", line 51, in start
    self.stack.loop()
  File "./yowsup/stacks/yowstack.py", line 57, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "./yowsup/layers/network/layer.py", line 48, in handle_read
    self.receive(data)
  File "./yowsup/layers/network/layer.py", line 55, in receive
    self.toUpper(data)
  File "./yowsup/layers/__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "./yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "./yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "./yowsup/layers/__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "./yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "./yowsup/layers/__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "./yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "./yowsup/layers/__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "./yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "./yowsup/layers/__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "./yowsup/layers/axolotl/layer.py", line 97, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "./yowsup/layers/__init__.py", line 135, in processIqRegistry
    errorClbk(protocolTreeNode, originalIq)
  File "./yowsup/layers/axolotl/layer.py", line 245, in onSentKeysError
    raise Exception("Sent keys were not accepted")
Exception: Sent keys were not accepted
```

I have fixed this issue with this patch:
```
diff --git a/yowsup/demos/echoclient/stack.py b/yowsup/demos/echoclient/stack.py
index 82d5e00..ffef6ef 100644
--- a/yowsup/demos/echoclient/stack.py
+++ b/yowsup/demos/echoclient/stack.py
@@ -17,7 +17,6 @@ from yowsup import env
 class YowsupEchoStack(object):
     def __init__(self, credentials, encryptionEnabled = False):
         if encryptionEnabled:
-            env.CURRENT_ENV = env.S40YowsupEnv()
             layers = (
                 EchoLayer,
                 (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer, YowMediaProtocolLayer)
@@ -29,6 +28,7 @@ class YowsupEchoStack(object):
                 YowNetworkLayer
             )
         else:
+            env.CURRENT_ENV = env.S40YowsupEnv()
             layers = (
                 EchoLayer,
                 (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer, YowMediaProtocolLayer)
```

**Comment by tgalal** [comment]
oops my bad, thanks for the tip!
