### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getData' 

### ISSUE THREAD

**Issue by overallduka** [tgalal/yowsup#595]
Im try run a sample echo client but, i put the run.py file inside echoclient  path, when i execute sudo `python run.py`  run ok waiting for message, when receive some message receive this error:

error after `python run.py`  and receive some message
```
No handlers could be found for logger "yowsup.stacks.yowstack"
Traceback (most recent call last):
  File "run.py", line 31, in <module>
    stack.loop() #this is the program mainloop
  File "build/bdist.macosx-10.9-intel/egg/yowsup/stacks/yowstack.py", line 170, in loop
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/network/layer.py", line 48, in handle_read
    messageProtocolEntity.getCaption(),
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/network/layer.py", line 55, in receive
    self.toLower(outImage)
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/__init__.py", line 56, in toUpper

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    receipt = OutgoingReceiptProtocolEntity(messageProtocolEntity.getId(), messageProtocolEntity.getFrom())
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    messageProtocolEntity.getCaption(),
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/__init__.py", line 56, in toUpper

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/__init__.py", line 56, in toUpper

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/coder/layer.py", line 35, in receive

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/__init__.py", line 56, in toUpper

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/logger/layer.py", line 14, in receive
    print('issso ehehhhh')
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/__init__.py", line 56, in toUpper

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/__init__.py", line 161, in receive

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/__init__.py", line 102, in receive

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    self.onMediaMessage(messageProtocolEntity)
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
AttributeError: 'NoneType' object has no attribute 'getData'`
```
run.py
``` 
from layer import EchoLayer
from yowsup.layers.auth                        import YowAuthenticationProtocolLayer
from yowsup.layers.protocol_messages           import YowMessagesProtocolLayer
from yowsup.layers.protocol_receipts           import YowReceiptProtocolLayer
from yowsup.layers.protocol_acks               import YowAckProtocolLayer
from yowsup.layers.network                     import YowNetworkLayer
from yowsup.layers.coder                       import YowCoderLayer
from yowsup.stacks import YowStack
from yowsup.common import YowConstants
from yowsup.layers import YowLayerEvent
from yowsup.stacks import YowStack, YOWSUP_CORE_LAYERS
from yowsup import env


CREDENTIALS = ("number", "pass") # replace with your phone and password

if __name__==  "__main__":
    layers = (
        EchoLayer,
        (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer)
    ) + YOWSUP_CORE_LAYERS

    stack = YowStack(layers)
    stack.setProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS, CREDENTIALS)         #setting credentials
    stack.setProp(YowNetworkLayer.PROP_ENDPOINT, YowConstants.ENDPOINTS[0])    #whatsapp server address
    stack.setProp(YowCoderLayer.PROP_DOMAIN, YowConstants.DOMAIN)
    stack.setProp(YowCoderLayer.PROP_RESOURCE, env.CURRENT_ENV.getResource())          #info about us as WhatsApp client

    stack.broadcastEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECT))   #sending the connect signal

    stack.loop() #this is the program main loop`
```
I found this related issue: https://github.com/tgalal/yowsup/issues/588  and check my stack.py file and he have  the `YowAxolotlLayer,` line.

**Comment by tgalal** [comment]
you pasted this:
```
layers = (
EchoLayer,
(YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer)
) + YOWSUP_CORE_LAYERS
```
Where is YowAxolotlLayer in that ?

Also you don't need to run with 'sudo'

**Comment by overallduka** [comment]
Thanks, i add the YowAxolotlLayer, now get this error:

Also added the debug

```
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Axolotl Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="my_number" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

Traceback (most recent call last):
  File "run.py", line 34, in <module>
    stack.loop() #this is the program mainloop
  File "build/bdist.macosx-10.9-intel/egg/yowsup/stacks/yowstack.py", line 170, in loop
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/network/layer.py", line 48, in handle_read
    messageProtocolEntity.getCaption(),
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/network/layer.py", line 55, in receive
    self.toLower(outImage)
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/__init__.py", line 56, in toUpper

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    receipt = OutgoingReceiptProtocolEntity(messageProtocolEntity.getId(), messageProtocolEntity.getFrom())
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    print("Echoing image %s to %s" % (messageProtocolEntity.url, messageProtocolEntity.getFrom(False)))
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    messageProtocolEntity.getCaption(),
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/__init__.py", line 56, in toUpper

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/__init__.py", line 56, in toUpper

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/coder/layer.py", line 35, in receive

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/__init__.py", line 56, in toUpper

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/logger/layer.py", line 14, in receive
    print('issso ehehhhh')
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/__init__.py", line 56, in toUpper

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/__init__.py", line 161, in receive

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/axolotl/layer.py", line 104, in receive

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/__init__.py", line 56, in toUpper

  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/interface/interface.py", line 68, in receive
  File "build/bdist.macosx-10.9-intel/egg/yowsup/layers/interface/interface.py", line 36, in processIqRegistry
AttributeError: 'ProtocolTreeNode' object has no attribute 'getTag'
```

**Comment by tgalal** [comment]
It needs to be added before the Protocol layers, so something like:
```
layers = (
EchoLayer,
(YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer),
YowAxolotlLayer
)  + YOWSUP_CORE_LAYERS

**Comment by overallduka** [comment]
Sorry my noob error, now getting other: `Exception: No such signedprekeyrecord! 0`

**Comment by overallduka** [comment]
still have the error

**Comment by tgalal** [comment]
Something screwed up encryption database consistency, not sure on yowsup side, whatsapp's contact side, or whatsapp's server side. Anyways, keep logging in till you stop receiving that crashing message  (around 5 times?), then send 1 message to this contact, this should fix receiving future messages from that contact

**Comment by overallduka** [comment]
Works now, one day after i logged via `yowsup-cli` and start chat, after i run the `echo client` and works, thanks much, excellent work.
