### ISSUE TITLE
Command line client did not start

### ISSUE THREAD

**Issue by mcl024** [tgalal/yowsup#621]
Hey together,

after successful registration with yowsup-cli i have a new problem. I can not start the command line client:

matthias@matthias-desktop:~/yowsup$ yowsup-cli demos --yowsup
/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py:1180: UserWarning: /home/matthias/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.2.15', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 652, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 1580, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 304, in <module>

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 223, in process

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 243, in startCmdline

  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/**init**.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/stack.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/**init**.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 21, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/**init**.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/axolotl/util/keyhelper.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/axolotl/identitykeypair.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/axolotl/state/storageprotos.py", line 9, in <module>
ImportError: cannot import name symbol_database
matthias@matthias-desktop:~/yowsup$ 
##

**Comment by mcl024** [comment]
This is the version of protobuf

matthias@matthias-desktop:~/yowsup$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from google import protobuf
>>> print(protobuf.__version__)
3.0.0-alpha-1
>>>

**Comment by eternautaCAT** [comment]
Try $yowsup-cli demos -y -c YOUCONFIGFILE.config

**Comment by mcl024** [comment]
Always the same!!

matthias@matthias-desktop:~/yowsup$ yowsup-cli demos -y -c config
/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py:1180: UserWarning: /home/matthias/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.2.15', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 652, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1580, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 304, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 223, in process
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 243, in startCmdline
    
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/stack.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 21, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/axolotl/util/keyhelper.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/axolotl/identitykeypair.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/axolotl/state/storageprotos.py", line 9, in <module>
ImportError: cannot import name symbol_database
matthias@matthias-desktop:~/yowsup$

**Comment by valentinmari** [comment]
Please @tgalal explain me why the axolotl label. I'm very intrigued.
