### ISSUE TITLE
Suddenly stopped request sms 

### ISSUE THREAD

**Issue by nishant-firefly** [tgalal/yowsup#644]
For me everything was working fine, I already configured one number for whatsapp . 
Suddenly started getting error. 

$ python yowsup-cli registration --requestcode sms --phone 91********** --cc 91 --mcc 1
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600}

status: fail
retry_after: 3600
reason: no_routes

I even tried after 3600 seconds got the same error. 

I tried the sms from my mobile and than when I tried to get password. 

$ python yowsup-cli registration --register 676480 --phone 91********* --cc 91
Traceback (most recent call last):
  File "yowsup-cli", line 307, in <module>
    if not parser.process():
  File "yowsup-cli", line 159, in process
    self.handleRegister(self.args["register"], config)
  File "yowsup-cli", line 181, in handleRegister
    req = WARegRequest(config["cc"], config["phone"], code)
  File "/home/ubuntu/valuation/bm/yowsup/yowsup/registration/regrequest.py", line 33, in __init__
    raise ValueError("You have to request code first")
ValueError: You have to request code first

**Comment by tgalal** [comment]
Please reopen if is still issue

**Comment by EmersonHenriique** [comment]
i need help
LOG : 
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4.48', 'yowsup-cli')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 724, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1657, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 160, in process

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 182, in handleRegister

  File "build/bdist.linux-x86_64/egg/yowsup/registration/regrequest.py", line 33, in __init__
ValueError: You have to request code first

**Comment by jlguardi** [comment]
You need to send sms before from the same computer and don't remove identity file generated in the .yowsup dir.

**Comment by EmersonHenriique** [comment]
yowsup-cli registration --requestcode sms --phone 5518991XXXXX --cc 55 --mcc 123 --mnc 456
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"no_routes","retry_after":3600,"sms_wait":3600,"voice_wait":3600}

status: fail
retry_after: 3600
reason: no_routes
