### ISSUE TITLE
Error a while after connect

### ISSUE THREAD

**Issue by Pedro-H-Fialho** [tgalal/yowsup#672]
Around 40 seconds after I connect (/L) , I'm receiving an error on yowsup-cli. 
It doesn't matter whether I've send or received any messages during this period. This error occurs after 0-70 seconds after I connect.

[root@server1 ~]# yowsup-cli demos -y -l number:pass
# Yowsup Cli client

Type /help for available commands

Auth: Logged in!
[connected]:
[connected]:Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.2.78', 'yowsup-cli')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.2.78-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 304, in <module>
    if not parser.process():
  File "/usr/lib/python2.6/site-packages/yowsup2-2.2.78-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 223, in process
    self.startCmdline()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.2.78-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 249, in startCmdline
    stack.start()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.2.78-py2.6.egg/yowsup/demos/cli/stack.py", line 28, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.2.78-py2.6.egg/yowsup/stacks/yowstack.py", line 162, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib64/python2.6/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.6/asyncore.py", line 151, in poll
    read(obj)
  File "/usr/lib64/python2.6/asyncore.py", line 82, in read
    obj.handle_error()
  File "/usr/lib64/python2.6/asyncore.py", line 78, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.6/asyncore.py", line 428, in handle_read_event
    self.handle_read()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.2.78-py2.6.egg/yowsup/layers/network/layer.py", line 48, in handle_read
    self.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.2.78-py2.6.egg/yowsup/layers/network/layer.py", line 55, in receive
    self.toUpper(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.2.78-py2.6.egg/yowsup/layers/**init**.py", line 55, in toUpper
    self.**upper.receive(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.2.78-py2.6.egg/yowsup/layers/stanzaregulator/layer.py", line 30, in receive
    self.toLower(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.2.78-py2.6.egg/yowsup/layers/__init**.py", line 59, in toLower
    self.__lower.send(data)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.2.78-py2.6.egg/yowsup/layers/network/layer.py", line 52, in send
    self.initiate_send()
  File "/usr/lib64/python2.6/asyncore.py", line 516, in initiate_send
    num_sent = dispatcher.send(self, self.out_buffer[:512])
  File "/usr/lib64/python2.6/asyncore.py", line 360, in send
    result = self.socket.send(data)
  File "/usr/lib64/python2.6/socket.py", line 167, in _dummy
    raise error(EBADF, 'Bad file descriptor')
socket.error: [Errno 9] Bad file descriptor
##

**Comment by XaKaX** [comment]
I'm still getting this error, and couldn't fix it myself.
Is anybody else getting it?

**Comment by igormsg** [comment]
i got this error too. 

it started after i reset my sms code from my iphone and then get the password (using iBrowser) from it to try to use both devices (iphone and yowsup) at the same time!

does anyone can help?

**Comment by 0xTryCatch** [comment]
You can't login with yowsup and device at the same time. It will disconnect you and change your password.

**Comment by igormsg** [comment]
now im using another whatsapp number (no simultaneous devices) and still getting this error

**Comment by igormsg** [comment]
anyone?

**Comment by XaKaX** [comment]
I still have the same problem, and it's not related to any device..
40 seconds after I connect I do get the same error.

I didn't connect for around 15 days, and today I tried it again. Same error.

**Comment by osiloke** [comment]
I have this same problem. In my case, i modified the cli example to read commands off a redis queue. It works on my mac but when i run it in my openvz container using the same python and requirements versions i get an error EBADF. I can only assume that this is related to the os unless someone has any other explanation

**Comment by osiloke** [comment]
I think i've figured this out. Yowsup needs some time to setup (on some os,cpu,mem config...). If i set my program to sleep for 2 seconds `time.sleep(2)` everything works.

**Comment by de666** [comment]
Same problem here...

```
[offline]:/L
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/yowsup/demos/cli/cli.py", line 151, in startInputThread
    wait = self.execCmd(cmd)
  File "/usr/lib/python3.4/site-packages/yowsup/demos/cli/cli.py", line 135, in execCmd
    return self.doExecCmd(lambda :targetFn(*args))
  File "/usr/lib/python3.4/site-packages/yowsup/demos/cli/cli.py", line 138, in doExecCmd
    return fn()
  File "/usr/lib/python3.4/site-packages/yowsup/demos/cli/cli.py", line 135, in <lambda>
    return self.doExecCmd(lambda :targetFn(*args))
  File "/usr/lib/python3.4/site-packages/yowsup/demos/cli/layer.py", line 305, in L
    return self.login(*self.getProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS))
  File "/usr/lib/python3.4/site-packages/yowsup/demos/cli/layer.py", line 315, in login
    self.broadcastEvent(connectEvent)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 77, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 77, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 77, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 77, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 77, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/lib/python3.4/site-packages/yowsup/layers/__init__.py", line 72, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/usr/lib/python3.4/site-packages/yowsup/layers/network/layer.py", line 27, in onEvent
    self.connect(self.getProp(self.__class__.PROP_ENDPOINT))
  File "/usr/lib/python3.4/asyncore.py", line 348, in connect
    raise OSError(err, errorcode[err])
OSError: [Errno 9] EBADF
```
Any news about this?

**Comment by krmboya** [comment]
Getting this error too after updating to latest version.

Could it be that it affects only specific versions of python, I'm on python 2.6 like the OP I see python 3.4 above. 

Also this: https://github.com/tgalal/yowsup/issues/769 suggests an issue that seems to be broken in python 2.6

**Comment by eugenebann** [comment]
I too am getting this error, putting the loop in a try / except doesn't work. My suspicion is that it has something to do with ```OutgoingAckProtocolEntity```. If I can't find a solution, I will try supervise and just restart on ```socket.error: [Errno 9] Bad file descriptor```.
