### ISSUE TITLE
'ImportError: No module named 'axolotl_curve25519' on Windows using Python 3

### ISSUE THREAD

**Issue by ishan-marikar** [tgalal/yowsup#674]
I can't seem to get yowsup to run on my windows system. I'm using virtualenv with python version 3.4.2. 

Pip shows that I have the following modules installed:
- argparse (1.1)
- pillow (2.7.0)
- pip (1.5.6)
- pyreadline (2.0)
- python-axolotl (0.1.6)
- python-dateutil (2.4.1)
- setuptools (3.6)
- six (1.9.0)
- yowsup2 (2.2.78)

I use yowsup mainly to experiment with ideas.

Error Message:
       Traceback (most recent call last):
    File "yowsup-cli", line 304, in <module>
    if not parser.process():
     File "yowsup-cli", line 223, in process
    self.startCmdline()
      File "yowsup-cli", line 243, in startCmdline
    from yowsup.demos import cli
      File "E:\Projects\yowsup2\yowsup\demos\cli\__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
      File "E:\Projects\yowsup2\yowsup\demos\cli\stack.py", line 1, in <module>
    from yowsup.stacks import YowStack, YowStackBuilder
      File "E:\Projects\yowsup2\yowsup\stacks\__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
      File "E:\Projects\yowsup2\yowsup\stacks\yowstack.py", line 21, in <module>
    from yowsup.layers.axolotl import YowAxolotlLayer
      File "E:\Projects\yowsup2\yowsup\layers\axolotl\__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
      File "E:\Projects\yowsup2\yowsup\layers\axolotl\layer.py", line 2, in <module>
    from .protocolentities import SetKeysIqProtocolEntity
      File "E:\Projects\yowsup2\yowsup\layers\axolotl\protocolentities\__init__.py", line 3, in <module>
    from .iq_keys_get_result import ResultGetKeysIqProtocolEntity
      File "E:\Projects\yowsup2\yowsup\layers\axolotl\protocolentities\iq_keys_get_result.py", line 4, in <module>
    from axolotl.identitykey import IdentityKey
      File "E:\Projects\yowsup-playground\playground\lib\site-packages\python_axolotl-0.1.6-py3.4.egg\axolotl\identitykey.py", line 1, in <module>
      File "E:\Projects\yowsup-playground\playground\lib\site-packages\python_axolotl-0.1.6-py3.4.egg\axolotl\ecc\curve.py", line 1, in <module>
    ImportError: No module named 'axolotl_curve25519'

**Comment by blackjack4494** [comment]
Have a look here:
https://github.com/tgalal/python-axolotl-curve25519

**Comment by Walderi** [comment]
Same error and this link dont`n help

**Comment by Goldbricker** [comment]
I get the same error in mine running in Windows XP with Python 2.7. I noticed during the installation using python setup.py install I see the following error at the end:

Installed d:\python27\lib\site-packages\yowsup2-2.2.78-py2.7.egg
Processing dependencies for yowsup2==2.2.78
Searching for python-axolotl-curve25519
Reading https://pypi.python.org/simple/python-axolotl-curve25519/
Best match: python-axolotl-curve25519 0.1
Downloading https://pypi.python.org/packages/source/p/python-axolotl-curve25519/
python-axolotl-curve25519-0.1.tar.gz#md5=f28d902df9044f0bf86a35a4bd2ec092
Processing python-axolotl-curve25519-0.1.tar.gz
Writing d:\temp\easy_install-js1p0w\python-axolotl-curve25519-0.1\setup.cfg
Running python-axolotl-curve25519-0.1\setup.py -q bdist_egg --dist-dir d:\temp\e
asy_install-js1p0w\python-axolotl-curve25519-0.1\egg-dist-tmp-gcgce4
gcc: error: unrecognized command line option '-mno-cygwin'
error: Setup script exited with error: command 'gcc' failed with exit status 1

Do you guys see the same error?

**Comment by Goldbricker** [comment]
To be clear for blackjack4494 I ran the steps in his link:
1. Installed mingw, add it to the path (I set the path to the mingw bin folder) 
2. Created the distutils.cfg file
3. Ran mingw-get.exe install gcc which completed successfully
4. Installed zlib - do you just need the dll installed on the machine?

I then re-ran the python setup.py install again but I still get the same error.

**Comment by moughamir** [comment]
fix it by installing **[tgalal/python-axolotl-curve25519](https://github.com/tgalal/python-axolotl-curve25519)**.

**Comment by pinoverclock** [comment]
Got the same error as ishan-marikar runing on Arch Linux with python3.4
As moughamir said i installed tgalal/python-axolotl-curve25519 but now it's failing with this error:
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 304, in <module>
    if not parser.process():
  File "/usr/bin/yowsup-cli", line 223, in process
    self.startCmdline()
  File "/usr/bin/yowsup-cli", line 243, in startCmdline
    from yowsup.demos import cli
  File "/usr/lib/python3.4/site-packages/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/usr/lib/python3.4/site-packages/yowsup/demos/cli/stack.py", line 1, in <module>
    from yowsup.stacks import YowStack, YowStackBuilder
  File "/usr/lib/python3.4/site-packages/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/usr/lib/python3.4/site-packages/yowsup/stacks/yowstack.py", line 22, in <module>
    from yowsup.layers.axolotl import YowAxolotlLayer
  File "/usr/lib/python3.4/site-packages/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/usr/lib/python3.4/site-packages/yowsup/layers/axolotl/layer.py", line 3, in <module>
    from axolotl.util.keyhelper import KeyHelper
  File "/usr/lib/python3.4/site-packages/axolotl/util/keyhelper.py", line 3, in <module>
    from ..identitykeypair import IdentityKeyPair
  File "/usr/lib/python3.4/site-packages/axolotl/identitykeypair.py", line 1, in <module>
    from .state.storageprotos import IdentityKeyPairStructure
  File "/usr/lib/python3.4/site-packages/axolotl/state/storageprotos.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named 'google'

Any hints?

**Comment by axpence** [comment]
try:
`aptitude install python-dev`

**Comment by joAQUINCE** [comment]
I have been struggling with this issue for a full day. I grabbed the tgalal/python-axolotl-curve25519 package but the "No module named 'axolotl_curve25519'" continues to appear.

I had to install the "six" module recently and that went pretty smoothly. However, it looks like command prompt is having issues interpreting the "-" signs on the tgalal/python-axolotl-curve25519 package name. 
Does anyone have any suggestions?

**Comment by Madhanaa** [comment]
I'm also facing the same issue. 
    C:\MinGW\bin\gcc.exe -shared -s build\temp.win32-3.5\Release\curve25519module.o build\temp.win32-3.5\Release\curve\curve25519-donna.o build\temp.win32-3.5\Release\curve\ed25519\fe_0.o build\temp.win32-3.5\Release\curve\ed25519\fe_1.o build\temp.win32-3.5\Release\curve\ed25519\fe_add.o build\temp.win32-3.5\Release\curve\ed25519\fe_cmov.o build\temp.win32-3.5\Release\curve\ed25519\fe_copy.o build\temp.win32-3.5\Release\curve\ed25519\fe_frombytes.o build\temp.win32-3.5\Release\curve\ed25519\fe_invert.o build\temp.win32-3.5\Release\curve\ed25519\fe_isnegative.o build\temp.win32-3.5\Release\curve\ed25519\fe_isnonzero.o build\temp.win32-3.5\Release\curve\ed25519\fe_mul.o build\temp.win32-3.5\Release\curve\ed25519\fe_neg.o build\temp.win32-3.5\Release\curve\ed25519\fe_pow22523.o build\temp.win32-3.5\Release\curve\ed25519\fe_sq.o build\temp.win32-3.5\Release\curve\ed25519\fe_sq2.o build\temp.win32-3.5\Release\curve\ed25519\fe_sub.o build\temp.win32-3.5\Release\curve\ed25519\fe_tobytes.o build\temp.win32-3.5\Release\curve\ed25519\ge_add.o build\temp.win32-3.5\Release\curve\ed25519\ge_double_scalarmult.o build\temp.win32-3.5\Release\curve\ed25519\ge_frombytes.o build\temp.win32-3.5\Release\curve\ed25519\ge_madd.o build\temp.win32-3.5\Release\curve\ed25519\ge_msub.o build\temp.win32-3.5\Release\curve\ed25519\ge_p1p1_to_p2.o build\temp.win32-3.5\Release\curve\ed25519\ge_p1p1_to_p3.o build\temp.win32-3.5\Release\curve\ed25519\ge_p2_0.o build\temp.win32-3.5\Release\curve\ed25519\ge_p2_dbl.o build\temp.win32-3.5\Release\curve\ed25519\ge_p3_0.o build\temp.win32-3.5\Release\curve\ed25519\ge_p3_dbl.o build\temp.win32-3.5\Release\curve\ed25519\ge_p3_tobytes.o build\temp.win32-3.5\Release\curve\ed25519\ge_p3_to_cached.o build\temp.win32-3.5\Release\curve\ed25519\ge_p3_to_p2.o build\temp.win32-3.5\Release\curve\ed25519\ge_precomp_0.o build\temp.win32-3.5\Release\curve\ed25519\ge_scalarmult_base.o build\temp.win32-3.5\Release\curve\ed25519\ge_sub.o build\temp.win32-3.5\Release\curve\ed25519\ge_tobytes.o build\temp.win32-3.5\Release\curve\ed25519\open.o build\temp.win32-3.5\Release\curve\ed25519\sc_muladd.o build\temp.win32-3.5\Release\curve\ed25519\sc_reduce.o build\temp.win32-3.5\Release\curve\ed25519\sign.o build\temp.win32-3.5\Release\curve\ed25519\additions\compare.o build\temp.win32-3.5\Release\curve\ed25519\additions\curve_sigs.o build\temp.win32-3.5\Release\curve\ed25519\additions\sign_modified.o build\temp.win32-3.5\Release\curve\ed25519\additions\zeroize.o build\temp.win32-3.5\Release\curve\ed25519\nacl_sha512\blocks.o build\temp.win32-3.5\Release\curve\ed25519\nacl_sha512\hash.o build\temp.win32-3.5\Release\axolotl_curve25519.cp35-win32.def -Ld:\madhanaa\python\libs -Ld:\madhanaa\python\PCbuild\win32 -lpython35 -lmsvcr90 -o build\lib.win32-3.5\axolotl_curve25519.cp35-win32.pyd
    C:\MinGW\bin\..\lib\gcc\mingw32\3.4.5\..\..\..\..\mingw32\bin\ld.exe: build\temp.win32-3.5\Release\axolotl_curve25519.cp35-win32.def:1: syntax error
    C:\MinGW\bin\..\lib\gcc\mingw32\3.4.5\..\..\..\..\mingw32\bin\ld.exe:build\temp.win32-3.5\Release\axolotl_curve25519.cp35-win32.def: file format not recognized; treating as linker script
    C:\MinGW\bin\..\lib\gcc\mingw32\3.4.5\..\..\..\..\mingw32\bin\ld.exe:build\temp.win32-3.5\Release\axolotl_curve25519.cp35-win32.def:1: syntax error
    collect2: ld returned 1 exit status
    error: command 'C:\\MinGW\\bin\\gcc.exe' failed with exit status 1

    ----------------------------------------
Command "d:\madhanaa\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\TOSHIBA\\AppData\\Local\\Temp\\pip-build-llomt8sb\\python-axolotl-curve25519\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\TOSHIBA\AppData\Local\Temp\pip-1k_mnjcw-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\TOSHIBA\AppData\Local\Temp\pip-build-llomt8sb\python-axolotl-curve25519

Please help me out to get python-axolotl-curve25519

**Comment by joAQUINCE** [comment]
Hey Madhanna, I just solved my problem. Here are the steps I took (This assumes that you already installed mingw and added its bin to PATH):

- I downloaded Python 2.7(32 Bit). Was running 3.5(32 Bits) previously

- Go to System Settings and Change PATH (for both the User and System Variable under Environment Variables) to the installation folder for Python 2.7.

- I downloaded a fresh yowsup zip from "https://github.com/tgalal/yowsup" using the "DOWNLOAD ZIP" option on the top-right corner.

- I unzipped the zip file (my zip filename was yowsup-master, not like it matters but should help you ensure you are downloading the same pack). HERE, UNZIP RIGHT IN YOUR C:\Python27 FOLDER. I am talking your setup.py file (from Yowsup) along with all other folders and files from the yowsup package will reside in the same directory as your python.exe from the Python27 installation.

- I ran the "python setup.py install" command from the C:\Python27 directory and got a "chmod error" which is discussed by tgalal in the main yowsup page ("https://github.com/tgalal/yowsup"). So, to solve this, I went into the Scripts folder (C:\Python27\Scripts) and ran "python pip.exe install pycrypto" which installed the problematic module independently of yowsup. 

- I ran "python setup.py install" command from the C:\Python27 directory again and everthing installed smoothly this time around.

- I ran * "python yowsup-cli demos --config yowsup_config.txt --send thistextistthephonenumberincludingcountrycode "this text is the message, must be in quotes if space is included" * from the C:\Python27 directory and bang the text went right through. I would highlight that **yowsup_config.txt** is just a text file containing the lines below, saved in the C:\Python27 directory (note that instructions for the registration script -to obtain your password- are given at https://github.com/tgalal/yowsup/wiki/yowsup-cli):



############# Yowsup Configuration Sample ###########
#
# ====================
# The file contains info about your WhatsApp account. This is used during registration and login.
# You can define or override all fields in the command line args as well.
#
# Country code. See http://www.ipipi.com/help/telephone-country-codes.htm. This is now required.
cc=thisiscountrycode
#
# Your full phone number including the country code you defined in 'cc', without preceding '+' or '00'
phone=insertphonenumberincludingcc
#
# You obtain this password when you register using Yowsup.
password=insertpasswordyougetwhenyouruntheregistrationscript
#######################################################

**Comment by Madhanaa** [comment]
Hello,

Thanks for the info. I again tried the steps which you mentioned. This time
i didn't face any error while doing python setup.py install. It went well.
Please find the attached txt file for the log.
I registered a phone number and got password. When i tried to run python
yowsup-cli demos --config yowsup_config.txt --send 91XXXXXXXXXX "Message",
i'm getting the following error.

Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 231, in process
    self.startSendClient()
  File "yowsup-cli", line 279, in startSendClient
    not self.args["unmoxie"])
  File "D:\Madhanaa\Python\yowsup\demos\sendclient\stack.py", line 24, in
__init__
    from yowsup.layers.axolotl                     import YowAxolotlLayer
  File "D:\Madhanaa\Python\yowsup\layers\axolotl\__init__.py", line 1, in
<module>
    from .layer import YowAxolotlLayer
  File "D:\Madhanaa\Python\yowsup\layers\axolotl\layer.py", line 2, in
<module>
    from .protocolentities import SetKeysIqProtocolEntity
  File
"D:\Madhanaa\Python\yowsup\layers\axolotl\protocolentities\__init__.py",
line 3, in <module>
    from .iq_keys_get_result import ResultGetKeysIqProtocolEntity
  File
"D:\Madhanaa\Python\yowsup\layers\axolotl\protocolentities\iq_keys_get_result.py",
line 4, in <module>
    from axolotl.identitykey import IdentityKey
  File
"D:\Madhanaa\Python\lib\site-packages\python_axolotl-0.1.7-py3.5.egg\axolotl\identitykey.py",
line 1, in <module>
  File
"D:\Madhanaa\Python\lib\site-packages\python_axolotl-0.1.7-py3.5.egg\axolotl\ecc\curve.py",
line 1, in <module>
ImportError: No module named 'axolotl_curve25519'

I tried installing axolotl_curve25519. I was not able to do it. I got
struck at this point only. Please help me out.

Please find the log for installing axolotl_curve25519.

D:\Madhanaa\Python>easy_install python-axolotl-curve25519
Searching for python-axolotl-curve25519
Reading https://pypi.python.org/simple/python-axolotl-curve25519/
Best match: python-axolotl-curve25519 0.1
Downloading
https://pypi.python.org/packages/source/p/python-axolotl-curve25519/python-axolotl-curve25519-0.1.tar.gz#md5=f28d902df9044f0bf86a35a4bd2ec092
Processing python-axolotl-curve25519-0.1.tar.gz
Writing
C:\Users\TOSHIBA\AppData\Local\Temp\easy_install-mheh4ebk\python-axolotl-curve25519-0.1\setup.cfg
Running python-axolotl-curve25519-0.1\setup.py -q bdist_egg --dist-dir
C:\Users\TOSHIBA\AppData\Local\Temp\easy_install-mheh4ebk\python-axolotl-curve25519-0.1\egg-dist-tmp-opd3fdeh
In file included from D:/Madhanaa/Python/include/Python.h:65,
                 from curve25519module.c:3:
D:/Madhanaa/Python/include/pytime.h:113: warning: "struct timeval" declared
inside parameter list
D:/Madhanaa/Python/include/pytime.h:113: warning: its scope is only this
definition or declaration, which is probably not what you want
D:/Madhanaa/Python/include/pytime.h:118: warning: "struct timeval" declared
inside parameter list
curve25519module.c:159: warning: initialization makes integer from pointer
without a cast
curve25519module.c:176:7: warning: no newline at end of file
curve/ed25519/additions\curve_sigs.c: In function `curve25519_keygen':
curve/ed25519/additions\curve_sigs.c:10: warning: unused variable `ed_y'
curve/ed25519/additions\zeroize.c: In function `zeroize':
curve/ed25519/additions\zeroize.c:6: warning: unused variable `retval'
C:\MinGW\bin\..\lib\gcc\mingw32\3.4.5\..\..\..\..\mingw32\bin\ld.exe:
build\temp.win32-3.5\Release\axolotl_curve25519.cp35-win32.def:1: syntax
error
C:\MinGW\bin\..\lib\gcc\mingw32\3.4.5\..\..\..\..\mingw32\bin\ld.exe:build\temp.win32-3.5\Release\axolotl_curve25519.cp35-win32.def:
file format not recognized; treating as linker script
C:\MinGW\bin\..\lib\gcc\mingw32\3.4.5\..\..\..\..\mingw32\bin\ld.exe:build\temp.win32-3.5\Release\axolotl_curve25519.cp35-win32.def:1:
syntax error
collect2: ld returned 1 exit status
error: Setup script exited with error: command 'C:\\MinGW\\bin\\gcc.exe'
failed with exit status 1

Regards,
Madhanaa S R

**Comment by joAQUINCE** [comment]
What version of Python are you running again? Did you remove the previous Python installation directory from PATH?

**Comment by Madhanaa** [comment]
Thank you. I was using Python 3. I changed it to Python 2.7 and it worked.
I'm able to send message to a whatsapp contact.

Regards,
Madhanaa S R

**Comment by Madhanaa** [comment]
Hello,

I'm trying to do the same setup at my office. Firewall restriction is
there. When i tried to do python setup.py install from C:\Python27, i'm
getting the below error. 407 Proxy Authorization Required -- Some packages
may not be found!

Searching for python-axolotl-curve25519
Reading https://pypi.python.org/simple/python-axolotl-curve25519/
Download error on https://pypi.python.org/simple/python-axolotl-curve25519/:
Tun
nel connection failed: 407 Proxy Authorization Required -- Some packages
may not
 be found!
Couldn't find index page for 'python-axolotl-curve25519' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: Tunnel connection
failed: 407
 Proxy Authorization Required -- Some packages may not be found!
No local packages or download links found for python-axolotl-curve25519
error: Could not find suitable distribution for
Requirement.parse('python-axolot
l-curve25519')

Could you please help me in resoving the tunnel connection issue.

Regards,
Madhanaa S R

On Mon, Jan 25, 2016 at 11:01 PM, madhanaa s.r. <madhanaarajendran@gmail.com
> wrote:

> Thank you. I was using Python 3. I changed it to Python 2.7 and it worked.
> I'm able to send message to a whatsapp contact.
>
> Regards,
> Madhanaa S R
>
> On Mon, Jan 25, 2016 at 5:36 PM, joAQUINCE <notifications@github.com>
> wrote:
>
>> What version of Python are you running again? Did you remove the previous
>> Python installation directory from PATH?
>>
>>

**Comment by Madhanaa** [comment]
Hello,

Could you please tell me the steps to send image/video messages and also
group messages using yowsup.

Thanks in advance.

Regards,
Madhanaa S R

On Wed, Jan 27, 2016 at 12:08 PM, madhanaa s.r. <madhanaarajendran@gmail.com
> wrote:

> Hello,
>
> I'm trying to do the same setup at my office. Firewall restriction is
> there. When i tried to do python setup.py install from C:\Python27, i'm
> getting the below error. 407 Proxy Authorization Required -- Some packages
> may not be found!
>
> Searching for python-axolotl-curve25519
> Reading https://pypi.python.org/simple/python-axolotl-curve25519/
> Download error on
> https://pypi.python.org/simple/python-axolotl-curve25519/: Tun
> nel connection failed: 407 Proxy Authorization Required -- Some packages
> may not
>  be found!
> Couldn't find index page for 'python-axolotl-curve25519' (maybe
> misspelled?)
> Scanning index of all packages (this may take a while)
> Reading https://pypi.python.org/simple/
> Download error on https://pypi.python.org/simple/: Tunnel connection
> failed: 407
>  Proxy Authorization Required -- Some packages may not be found!
> No local packages or download links found for python-axolotl-curve25519
> error: Could not find suitable distribution for
> Requirement.parse('python-axolot
> l-curve25519')
>
> Could you please help me in resoving the tunnel connection issue.
>
> Regards,
> Madhanaa S R
>
> On Mon, Jan 25, 2016 at 11:01 PM, madhanaa s.r. <

**Comment by Vishal9650** [comment]
During run python setup.install geeting gcc error

ython-axolotl-curve25519-0.1.tar.gz#md5=f28d902df9044f0bf86a35a4bd2ec092
rocessing python-axolotl-curve25519-0.1.tar.gz
unning python-axolotl-curve25519-0.1\setup.py -q bdist_egg --dist-dir c:\users
ishalg2\appdata\local\temp\easy_install-deww0t\python-axolotl-curve25519-0.1\e
-dist-tmp-e21mni
urve25519module.c: In function 'calculateSignature':
urve25519module.c:50: warning: pointer targets in passing argument 1 of 'curve
519_sign' differ in signedness
urve25519module.c:50: warning: pointer targets in passing argument 2 of 'curve
519_sign' differ in signedness
urve25519module.c:50: warning: pointer targets in passing argument 3 of 'curve
519_sign' differ in signedness
urve25519module.c:50: warning: pointer targets in passing argument 5 of 'curve
519_sign' differ in signedness
urve25519module.c: In function 'verifySignature':
urve25519module.c:76: warning: pointer targets in passing argument 1 of 'curve
519_verify' differ in signedness
urve25519module.c:76: warning: pointer targets in passing argument 2 of 'curve
519_verify' differ in signedness
urve25519module.c:76: warning: pointer targets in passing argument 3 of 'curve
519_verify' differ in signedness
urve/ed25519/additions\curve_sigs.c: In function 'curve25519_keygen':
urve/ed25519/additions\curve_sigs.c:10: warning: unused variable 'ed_y'
urve/ed25519/additions\zeroize.c: In function 'zeroize':
urve/ed25519/additions\zeroize.c:6: warning: unused variable 'retval'
uild\temp.win32-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x5f)
undefined reference to `_imp__PyExc_ValueError'
uild\temp.win32-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x84)
undefined reference to `_imp__PyExc_ValueError'
uild\temp.win32-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x104
 undefined reference to `_imp__PyExc_ValueError'
uild\temp.win32-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x175
 undefined reference to `_imp__PyExc_ValueError'
uild\temp.win32-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x1f4
 undefined reference to `_imp__PyExc_ValueError'
uild\temp.win32-2.7\Release\curve25519module.o:curve25519module.c:(.text+0x219
 more undefined references to `_imp__PyExc_ValueError' follow
ollect2: ld returned 1 exit status
rror: Setup script exited with error: command 'gcc' failed with exit status 1

:\Python27>

**Comment by hmrasi** [comment]
I haven't installed minGW GCC at the time of registering . now i'm getting the error 

NoModuleFoundError : Axolotl-curve25519 module not found.

is it necessary to install minGW? any steps ?
@tgalal
