### ISSUE TITLE
Yosup printing iq to="s.whatsapp.net" xmlns="encrypt" type="get" in a loop

### ISSUE THREAD

**Issue by anuraguniyal** [tgalal/yowsup#700]
When I tried to send a message yowsup goes into some infinite loop and started printing messages like
```
<iq to="s.whatsapp.net" xmlns="encrypt" type="get" id="4">
<key>
<user jid="xxx@s.whatsapp.net">
</user>
</key>
</iq>
```

Good thing is it was not sending or recieving these on network as I disconnected my network at that point, but what would trigger this?

```
<success status="active" kind="free" creation="1427930481" expiration="1459466481" props="4" t="1428109742">
Gһ&65????.?Qt???8
HEX:471cd2bb2636353f8bcbde2eeb511e749ab58938
</success>

2015-04-03 18:09:02,288 DEBUG: rx:
<ib from="s.whatsapp.net">
<offline count="0">
</offline>
</ib>

2015-04-03 18:10:15,143 DEBUG: tx:
<iq to="s.whatsapp.net" xmlns="encrypt" type="get" id="4">
<key>
<user jid="xxx@s.whatsapp.net">
</user>
</key>
</iq>

2015-04-03 18:10:15,276 DEBUG: rx:
<iq type="result" from="s.whatsapp.net" id="4">
<list>
<user jid="xxx@s.whatsapp.net">
<registration>
|?gP
HEX:7ccd6750
</registration>
<type>

HEX:05
</type>
<identity>
{??????k?3?c)Ҫ???RջU?=&>
HEX:7bccfe9f10d7eceea66be01d33f26329d2aa82ea178f52d5bb55ec3d0126063e
</identity>
<skey>
<id>

HEX:000000
</id>
<value>
֎}T??T?
(?i-?'o?$)?=???b.t
HEX:1cd68e1e7d54b5c00654960a2801bb692d9527026f8f2429fa3d9be6c9622e74
</value>
<signature>
????;F?,xs???h??o??C;4֩??A
HEX:527600f728718f12a3f3156619dac673a5cd328626e0e675801d34d6a9a6ec410d3c26f9f68646b32c7873bee21eba6885fa6fdd10a9433b0dd5f8efcb193b07
</signature>
</skey>
<key>
<id>
??<
HEX:82b13c
</id>
<value>
?9?K?????)3+Β,h?EpaW?-??neh
HEX:f139f3bc014b899e88b3d229332bce922c016807e545706157e62df5d06e6568
</value>
</key>
</user>
</list>
</iq>

2015-04-03 18:10:15,292 DEBUG: tx:
<iq to="s.whatsapp.net" xmlns="encrypt" type="get" id="5">
<key>
<user jid="xxx@s.whatsapp.net">
</user>
</key>
</iq>

...
...
long long list
...
...

2015-04-03 18:10:58,489 DEBUG: tx:
<iq to="s.whatsapp.net" xmlns="encrypt" type="get" id="41937">
<key>
<user jid="xxx@s.whatsapp.net">
</user>
</key>
</iq>

2015-04-03 18:10:58,491 DEBUG: tx:
<iq to="s.whatsapp.net" xmlns="encrypt" type="get" id="41938">
<key>
<user jid="xxx@s.whatsapp.net">
</user>
</key>
</iq>

Traceback (most recent call last):
 File "yowsup_server/run.py", line 90, in <module>
    stack.loop()
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/stacks/yowstack.py", line 170, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/local/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/local/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/lib/python2.7/asyncore.py", line 444, in handle_read_event
    self.handle_read()
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 48, in handle_read
    self.receive(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 55, in receive
    self.toUpper(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 97, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 132, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 265, in onGetKeysResult
    self.processPendingMessages(jid)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 129, in processPendingMessages
    self.handlePlaintextNode(messageNode)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/axolotl/layer.py", line 146, in handlePlaintextNode
    self._sendIq(entity, self.onGetKeysResult, self.onGetKeysError)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 122, in _sendIq
    self.toLower(iqEntity.toProtocolTreeNode())
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toLower
    self.__lower.send(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/logger/layer.py", line 9, in send
    self.toLower(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toLower
    self.__lower.send(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/coder/layer.py", line 30, in send
    self.write(self.writer.protocolTreeNodeToBytes(data))
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/coder/layer.py", line 39, in write
    self.toLower(bytearray(i))
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toLower
    self.__lower.send(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/auth/layer_crypt.py", line 46, in send
    self.toLower(bytearray(data))
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toLower
    self.__lower.send(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/stanzaregulator/layer.py", line 23, in send
    self.toLower(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/__init__.py", line 59, in toLower
    self.__lower.send(data)
  File "/mnt/hgfs/auniyal/src/yowsup_heroku/venv/lib/python2.7/site-packages/yowsup/layers/network/layer.py", line 51, in send
    self.out_buffer = self.out_buffer + data
KeyboardInterrupt
```

**Comment by jlguardi** [comment]
I think this is an expected result. You are getting encryption Keys on first boot. It spends long time (1 minute) and stores keys in local data base. 
Try to run yowsup-cli with encryption for firts time and wait until all keys are downloaded. This app has console output indicating current state.

**Comment by tgalal** [comment]
@jlguardi is right. If e2e encryption is enabled (with --moxie switch), after first login yowsup will generate 200 keys that will be used in creating the encrypted sessions, sends them all to whatsapp, then stores them in a local database. This could take around a minute depending on your network speed (for sending) and the device specs in general (for storing them).

**Comment by anuraguniyal** [comment]
but if you see last tx, it is ```<iq to="s.whatsapp.net" xmlns="encrypt" type="get" id="41938">``` see the id=41938 and they all were sequential, why so many txs?

**Comment by CODeRUS** [comment]
you have 41938 contacts for example

**Comment by anuraguniyal** [comment]
I don't have that many contacts :)  and it did not stop at that number, it was going like that for minutes  and I had to kill it.

**Comment by tgalal** [comment]
Is it possible that on login with this number you are receiving many messages, for example you have not used this number for a while and many people sent you a lot of message in the mean time (4000+ in this case), and now you login and supposed to receive them all? Because  I think that's  a possible scenario which could cause a lot of those:
```
<iq to="s.whatsapp.net" xmlns="encrypt" type="get" id="4">
<key>
<user jid="xxx@s.whatsapp.net">
</user>
</key>
</iq>
```
and is definitely a bug.

**Comment by CODeRUS** [comment]
40,000+

**Comment by tgalal** [comment]
oh right 40000+, receiving all those many message is very unlikely too :/ While what I explained is still a bug, it's probably a different thing here, it does seems it gets stuck in a loop. @anuraguniyal What does your stack look like ?

**Comment by anuraguniyal** [comment]
This is my stack
```
def connect_whatsapp(phone, password, encryption, reply_url):
    layers = (
        ServerLayer,
        (YowAuthenticationProtocolLayer, YowMessagesProtocolLayer, YowReceiptProtocolLayer, YowAckProtocolLayer, YowMediaProtocolLayer),
    )

    if encryption:
        logging.info("Adding encryption layer")
        layers = layers + (YowAxolotlLayer,)
    else:
        env.CURRENT_ENV = env.S40YowsupEnv()
```

My ServerLayer is just a simple Echo type layer
```
class ServerLayer(YowInterfaceLayer):
```

btw I am not able to replicate this, my stack is working fine now. So only way to debug and fix this would be to review code and see how would this happen.
