### ISSUE TITLE
OSError WinError 10038

### ISSUE THREAD

**Issue by lcmeyer37** [tgalal/yowsup#705]
Hi people, I don't know why, but my program runs fine until randomly I get this error below:

Traceback (most recent call last):
  File "run.py", line 31, in <module>
    stack.loop() #this is the program mainloop
  File "C:\Python34\lib\site-packages\yowsup\stacks\yowstack.py", line 170, in l
oop
    asyncore.loop(*args, **kwargs)
  File "C:\Python34\lib\asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "C:\Python34\lib\asyncore.py", line 153, in poll
    read(obj)
  File "C:\Python34\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Python34\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python34\lib\asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "C:\Python34\lib\site-packages\yowsup\layers\network\layer.py", line 48,
in handle_read
    self.receive(data)
  File "C:\Python34\lib\site-packages\yowsup\layers\network\layer.py", line 55,
in receive
    self.toUpper(data)
  File "C:\Python34\lib\site-packages\yowsup\layers\__init__.py", line 55, in to
Upper
    self.__upper.receive(data)
  File "C:\Python34\lib\site-packages\yowsup\layers\stanzaregulator\layer.py", l
ine 30, in receive
    self.toLower(data)
  File "C:\Python34\lib\site-packages\yowsup\layers\__init__.py", line 59, in to
Lower
    self.__lower.send(data)
  File "C:\Python34\lib\site-packages\yowsup\layers\network\layer.py", line 52,
in send
    self.initiate_send()
  File "C:\Python34\lib\asyncore.py", line 536, in initiate_send
    num_sent = dispatcher.send(self, self.out_buffer[:65536])
  File "C:\Python34\lib\asyncore.py", line 366, in send
    result = self.socket.send(data)
OSError: [WinError 10038] An operation was attempted on something that is not a
socket

Any ideas? I run it on Python 3.4.3 - Windows 7. Also, I found that this same error occurs with the sample app Echo client. So, I'm not sure if the problem is specifically with my script.

**Comment by WilixLead** [comment]
I have similar problem on Windows 8.1 x64, Python 3.4.
For additional check I disable windows firewall and what I have:
I start my script (copy of echoclient from yowsup), scripts wait something and after some time I get:
>
Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
  File "G:\Cloud\wProjects\whatsapp_clicker\spmBot\__init__.py", line 4, in <module>
    yo.start()
  File "G:\Cloud\wProjects\whatsapp_clicker\spmBot\stack.py", line 51, in start
    self.stack.loop()
  File "C:\Python34\lib\site-packages\yowsup2-2.2.78-py3.4.egg\yowsup\stacks\yowstack.py", line 170, in loop
  File "C:\Python34\lib\asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "C:\Python34\lib\asyncore.py", line 153, in poll
    read(obj)
  File "C:\Python34\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Python34\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python34\lib\asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "C:\Python34\lib\site-packages\yowsup2-2.2.78-py3.4.egg\yowsup\layers\network\layer.py", line 48, in handle_read
    to = messageProtocolEntity.getFrom(), preview = messageProtocolEntity.getPreview())
  File "C:\Python34\lib\site-packages\yowsup2-2.2.78-py3.4.egg\yowsup\layers\network\layer.py", line 55, in receive
    
  File "C:\Python34\lib\site-packages\yowsup2-2.2.78-py3.4.egg\yowsup\layers\__init__.py", line 55, in toUpper
  File "C:\Python34\lib\site-packages\yowsup2-2.2.78-py3.4.egg\yowsup\layers\stanzaregulator\layer.py", line 30, in receive
    messageProtocolEntity.getBody(),
  File "C:\Python34\lib\site-packages\yowsup2-2.2.78-py3.4.egg\yowsup\layers\__init__.py", line 59, in toLower
  File "C:\Python34\lib\site-packages\yowsup2-2.2.78-py3.4.egg\yowsup\layers\network\layer.py", line 52, in send
    #send receipt otherwise we keep receiving the same message over and over
  File "C:\Python34\lib\asyncore.py", line 536, in initiate_send
    num_sent = dispatcher.send(self, self.out_buffer[:65536])
  File "C:\Python34\lib\asyncore.py", line 366, in send
    result = self.socket.send(data)
OSError: [WinError 10038] An operation was attempted on something that is not a socket

after that I go to yowsup-cli own echo client and run it like:
yowsup-cli demos -l NNNNN:MYENCPASS -e
scripts run and wait something (I thing while some socket operations will be done, or may be wait while socket will be opened)
and I get equal message:

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tupl
e is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
  File "./yowsup-cli", line 304, in <module>
    if not parser.process():
  File "./yowsup-cli", line 225, in process
    self.startEcho()
  File "./yowsup-cli", line 259, in startEcho
    stack.start()
  File "G:\Cloud\wProjects\whatsapp_clicker\yowsup\yowsup\demos\echoclient\stack.py", line 51, in start
    self.stack.loop()
  File "G:\Cloud\wProjects\whatsapp_clicker\yowsup\yowsup\stacks\yowstack.py", line 170, in loop
    asyncore.loop(*args, **kwargs)
  File "c:\Python34\lib\asyncore.py", line 208, in loop poll_fun(timeout, map)
  File "c:\Python34\lib\asyncore.py", line 153, in poll read(obj)
  File "c:\Python34\lib\asyncore.py", line 87, in read obj.handle_error()
  File "c:\Python34\lib\asyncore.py", line 83, in read obj.handle_read_event()
  File "c:\Python34\lib\asyncore.py", line 442, in handle_read_event self.handle_read()
  File "G:\Cloud\wProjects\whatsapp_clicker\yowsup\yowsup\layers\network\layer.py", line 48, in handle_read self.receive(data)
  File "G:\Cloud\wProjects\whatsapp_clicker\yowsup\yowsup\layers\network\layer.py", line 55, in receive
    self.toUpper(data)
  File "G:\Cloud\wProjects\whatsapp_clicker\yowsup\yowsup\layers\__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "G:\Cloud\wProjects\whatsapp_clicker\yowsup\yowsup\layers\stanzaregulator\layer.py", line 30, in receive self.toLower(data)
  File "G:\Cloud\wProjects\whatsapp_clicker\yowsup\yowsup\layers\__init__.py", line 59, in toLower
    self.__lower.send(data)
  File "G:\Cloud\wProjects\whatsapp_clicker\yowsup\yowsup\layers\network\layer.py", line 52, in send self.initiate_send()
  File "c:\Python34\lib\asyncore.py", line 536, in initiate_send num_sent = dispatcher.send(self, self.out_buffer[:65536])
  File "c:\Python34\lib\asyncore.py", line 366, in send result = self.socket.send(data)
OSError: [WinError 10038] An operation was attempted on something that is not a socket

If I try use yowsup-cli send message function, message was sent successful, without any errors
yowsup-cli demos -l NNNNN:MYENCPASS -s nomber "Hello"
