### ISSUE TITLE
SSL CERTIFICATE_VERIFY_FAILED (Windows - Python 3.4)

### ISSUE THREAD

**Issue by fasfelipe** [tgalal/yowsup#706]
Hi folks,

I'm having SSL problem on **"Registration"** and **"Register"** using yowsup-cli. I'm using windows with Python 3.4 and last week it was working fine, and I could register the number without any problem.
I seek for this SSL problem and found this problem on linux with a older version of python, but without a good solution. Any one know what should be this problem and what could I do to solve it? Any hint what cause this problem?

He is the call I am using.
```
python yowsup-cli registration --requestcode sms --phone 5511XXXXXXXXX --cc 55 --mcc 724 --mnc 13
 ```

Throw this out:
```
Traceback (most recent call last):
  File "yowsup-cli", line 304, in <module>
    if not parser.process():
  File "yowsup-cli", line 158, in process
    self.handleRegister(self.args["register"], config)
  File "yowsup-cli", line 181, in handleRegister
    result = req.send()
  File "C:\Users\Felipe\Documents\Python\WhatsApp\yowsup-master\yowsup\common\http\warequest.py", line 67, in send
    return self.sendGetRequest(parser)
  File "C:\Users\Felipe\Documents\Python\WhatsApp\yowsup-master\yowsup\common\http\warequest.py", line 105, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET")
  File "C:\Users\Felipe\Documents\Python\WhatsApp\yowsup-master\yowsup\common\http\warequest.py", line 161, in sendRequest
    conn.request(reqType, path, params, headers);
  File "C:\Python34\lib\http\client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1126, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 922, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 857, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 1231, in connect
    server_hostname=server_hostname)
  File "C:\Python34\lib\ssl.py", line 365, in wrap_socket
    _context=self)
  File "C:\Python34\lib\ssl.py", line 583, in __init__
    self.do_handshake()
  File "C:\Python34\lib\ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

Thanks all.

**Comment by army007** [comment]
Having the same problem in windows, python 3.4.3, yowsup-cli v2.0.9 and yowsup v2.2.78.

**Comment by patchido** [comment]
im having the same issue, can;t make it work, have any of you found any solution yet?

**Comment by fasfelipe** [comment]
Not yet. Anyone could solve this?

Enviado do meu iPhone

**Comment by Codehimn** [comment]
FIxed:
Change warequest.py to =

import urllib,  sys, os, logging
import ssl, socket
import hashlib
from .waresponseparser import ResponseParser
from yowsup.env import S40YowsupEnv
CURRENT_ENV = S40YowsupEnv()

if sys.version_info < (3, 0):
    import httplib
    from urllib import urlencode
else:
    from http import client as httplib
    from urllib.parse import urlencode

logger = logging.getLogger(__name__)


class WARequest(object):

    OK = 200

    def __init__(self):

        self.pvars = []
        self.port = 443
        self.type = "GET"
        self.parser = None
        self.params = []
        self.headers = {}

        self.sent = False
        self.response = None



    def setParsableVariables(self, pvars):
        self.pvars = pvars

    def onResponse(self, name, value):
        if name == "status":
            self.status = value
        elif name == "result":
            self.result = value

    def addParam(self,name,value):
        self.params.append((name,value))

    def removeParam(self, name):
        for i in range(0, len(self.params)):
            if self.params[i][0] == name:
                del self.params[i]


    def addHeaderField(self, name, value):
        self.headers[name] = value

    def clearParams(self):
        self.params = []

    def getUserAgent(self):
        return CURRENT_ENV.getUserAgent()

    def send(self, parser = None):

        if self.type == "POST":
            return self.sendPostRequest(parser)

        return self.sendGetRequest(parser)

    def setParser(self, parser):
        if isinstance(parser, ResponseParser):
            self.parser = parser
        else:
            logger.error("Invalid parser")

    def getConnectionParameters(self):

        if not self.url:
            return "", "", self.port

        try:
            url = self.url.split("://", 1)
            url = url[0] if len(url) == 1 else url[1]

            host, path = url.split('/', 1)
        except ValueError:
            host = url
            path = ""

        path = "/" + path

        return host, self.port, path

    def sendGetRequest(self, parser = None):
        self.response = None
        params =  self.params#[param.items()[0] for param in self.params];

        parser = parser or self.parser or ResponseParser()

        headers = dict(list({"User-Agent":self.getUserAgent(),
                "Accept": parser.getMeta()
            }.items()) + list(self.headers.items()));

        host,port,path = self.getConnectionParameters()

        self.response = WARequest.sendRequest(host, port, path, headers, params, "GET")

        if not self.response.status == WARequest.OK:
            logger.error("Request not success, status was %s"%self.response.status)
            return {}

        data = self.response.read()
        logger.info(data)

        self.sent = True
        return parser.parse(data.decode(), self.pvars)

    def sendPostRequest(self, parser = None):
        self.response = None
        params =  self.params #[param.items()[0] for param in self.params];

        parser = parser or self.parser or ResponseParser()

        headers = dict(list({"User-Agent":self.getUserAgent(),
                "Accept": parser.getMeta(),
                "Content-Type":"application/x-www-form-urlencoded"
            }.items()) + list(self.headers.items()))

        host,port,path = self.getConnectionParameters()
        self.response = WARequest.sendRequest(host, port, path, headers, params, "POST")


        if not self.response.status == WARequest.OK:
            logger.error("Request not success, status was %s" % self.response.status)
            return {}

        data = self.response.read()

        logger.info(data)

        self.sent = True
        return parser.parse(data.decode(), self.pvars)


    @staticmethod
    def sendRequest(host, port, path, headers, params, reqType="GET"):

        params = urlencode(params)


        path = path + "?"+ params if reqType == "GET" and params else path

        if len(headers):
            logger.debug(headers)
        if len(params):
            logger.debug(params)

        logger.debug("Opening connection to %s" % host);
        conn = httplib.HTTPSConnection(host ,port) if port == 443 else httplib.HTTPConnection(host ,port)

        logger.debug("Sending %s request to %s" % (reqType, path))


        sock = socket.create_connection((conn.host, conn.port), conn.timeout, conn.source_address)
        conn.sock = ssl.wrap_socket(sock, conn.key_file, conn.cert_file, ssl_version=ssl.PROTOCOL_TLSv1)

        conn.request(reqType, path, params, headers);

        response = conn.getresponse()
        return response

**Comment by alexisjk** [comment]
Not working for me this solution,is it  working for anyone?

**Comment by soutrick** [comment]
Thanks @Codehimn . Faced the same issue and your solution worked for me.

**Comment by Kaemmelot** [comment]
Thanks @Codehimn, works great!

The Important part is the
import ssl, socket
at the top and these 2 lines:
sock = socket.create_connection((conn.host, conn.port), conn.timeout, conn.source_address)
    conn.sock = ssl.wrap_socket(sock, conn.key_file, conn.cert_file, ssl_version=ssl.PROTOCOL_TLSv1)

**Comment by kraiz** [comment]
This fix work fine for me, too. (py3.4 @ debian 8)

**Comment by gaeldb** [comment]
Seen again with python3.4 on macOS. Install with pip3.

Was corrected by editing in common/http/warequest.py:

`if sys.version_info < (3, 0):
    import httplib
    from urllib import quote as urllib_quote

else:
    import ssl
    ssl._create_default_https_context = ssl._create_unverified_context

    from http import client as httplib
    from urllib.parse import quote as urllib_quote`
