### ISSUE TITLE
Not being able to login to yowsup-cli with a specific account?

### ISSUE THREAD

**Issue by lcmeyer37** [tgalal/yowsup#710]
Hi people, I'm trying to login to yowsup-cli with a specific account, that was working before. But, I get the following on my Terminal:

mier@ubuntu:~$ yowsup-cli demos -l number:password -y -d
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - Groups Iq Layer - Media Layer - Privacy Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:/login number password
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="number" mechanism="WAUTH-2">
��b������^�I,}�>R�������Z�.�"
u��;_03K��
HEX:90e262f4cefe860fc3118b5ef4492c7dc83e0e52e7f2ebe3f1d6ca5a8a122ec722ea0a75c3e63b5f30334b9ba80406
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
Ț\�)�D�
HEX:26f0d22aecb30df0a00dc89a5ca21d29d24404a4
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
��jR������"b�k�,�+�~��������|LK{�)�x6��$
HEX:d4d26a52989714fa9d1daddc2262aa6b8b2c15e22bdf7e9f178caaf5a5b18cf11c177c4c144b7bb529ea7836e99624
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1425666911" expiration="1457202911" props="4" t="1428842419">
a3U�M/?|R8(C�
HEX:6133559b4def8f912f3f7c52380406284300ce08
</success>

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 304, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 223, in process
    self.startCmdline()
  File "/usr/local/bin/yowsup-cli", line 249, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/demos/cli/stack.py", line 28, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/stacks/yowstack.py", line 162, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 48, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/network/layer.py", line 55, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 160, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/__init__.py", line 101, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/auth/layer_authentication.py", line 55, in handleSuccess
    if(node.data != None): StorageTools.writeNonce(self.credentials[0],node.data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup/common/tools.py", line 70, in writeNonce
    with open(os.path.join(path, "nonce"), 'wb') as idFile:
IOError: [Errno 13] Permission denied: '/home/mier/.yowsup/number/nonce'
mier@ubuntu:~$ 

IOError: [Errno 13] Permission denied. Do you know why? I don't get this when I use another number I have. There it works just fine.

Thanks,

Lucas Meyer.

**Comment by dedmen** [comment]
Do you have write permission to the file '/home/mier/.yowsup/number/nonce' ?

**Comment by lcmeyer37** [comment]
But, I don't know why i have to do something else more, like asking for permission for a file or something for just this one account that I have, and not for another number that I use for testing.

**Comment by dedmen** [comment]
I cant replicate that bug and im also using two different numbers on the
same machine so its probably not a bug in yowsup. Are you running yowsup
twice with both numbers at the same time? Or maybe only one number has to
save the nonce and fails on permissions. But i wouldnt know why the other
number doesnt have to save it... That would be a yowsup bug then.

**Comment by gschanuel** [comment]
I'm having the same error, but I'm running it via a php page
``` 
<?php
   $output=shell_exec("whoami");
   echo "<pre>$output</pre>";
   $output=shell_exec('yowsup-cli demos -d -c /etc/yowsup.conf --send MyNumber "test123 i asda"  2>&1; echo $?' );
   echo "<pre>$output</pre>";
?> 
```

I get this:
```
apache
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.layers.network.layer:HttpProxy initialize: ('192.168.3.42', 3128)
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:HttpProxy connect: c2.whatsapp.net:443
DEBUG:yowsup.layers.network.layer:HttpProxy handle connect
DEBUG:yowsup.layers.network.layer:HttpProxy connected
DEBUG:yowsup.layers.logger.layer:tx:











Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 5, in 
    pkg_resources.run_script('yowsup2==2.3.123', 'yowsup-cli')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 321, in 
    if not parser.process():
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 229, in process
    self.startSendClient()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 278, in startSendClient
    stack.start()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/demos/sendclient/stack.py", line 58, in start
    self.stack.loop()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/stacks/yowstack.py", line 175, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python2.6/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.6/asyncore.py", line 151, in poll
    read(obj)
  File "/usr/lib64/python2.6/asyncore.py", line 82, in read
    obj.handle_error()
  File "/usr/lib64/python2.6/asyncore.py", line 78, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.6/asyncore.py", line 428, in handle_read_event
    self.handle_read()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/network/layer.py", line 68, in handle_read
    data = self.proxyHandler.recv(self, readSize)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/common/http/httpproxy.py", line 93, in recv
    self.onConnect()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/network/layer.py", line 30, in onConnect
    self.handle_connect()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/network/layer.py", line 55, in handle_connect
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/__init__.py", line 68, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/__init__.py", line 68, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/__init__.py", line 68, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/__init__.py", line 68, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/__init__.py", line 62, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/__init__.py", line 178, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/auth/layer_authentication.py", line 39, in onEvent
    self.login()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/auth/layer_authentication.py", line 49, in login
    self._sendAuth()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/auth/layer_authentication.py", line 88, in _sendAuth
    nonce = StorageTools.getNonce(self.credentials[0])
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/common/tools.py", line 75, in getNonce
    path = StorageTools.getStorageForPhone(phone)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/common/tools.py", line 49, in getStorageForPhone
    return StorageTools.constructPath(phone + '/')
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/common/tools.py", line 44, in constructPath
    os.makedirs(os.path.dirname(fullPath))
  File "/usr/lib64/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.6/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/root/.yowsup'
1
```

You can see apache is running as user **apache**, so why is yowsup trying to write in /root/.yowsup?
