### ISSUE TITLE
New user in group error?

### ISSUE THREAD

**Issue by 4lloyd** [tgalal/yowsup#713]
```
Auth: Logged in!
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.0.53', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 320, in <module>

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 242, in process

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.0.53-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 267, in startCmdline

  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/stack.py", line 42, in start
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 49, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 47, in handle_read
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 54, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 56, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 56, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 56, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 56, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 56, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 114, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 56, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 138, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 100, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_notifications/layer.py", line 32, in recvNotification
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 116, in raiseErrorForNode
ValueError: Unimplemented notification type <notification retry="2" participant="CCTELNR1@s.whatsapp.net" t="1234567890" from="CCTELNR1-1234567890@g.us" offline="2" type="w:gp2" id="1234567890" notify="Test">
<add>
<participant jid="CCTELNR2@s.whatsapp.net">
</participant>
</add>
</notification>
```

Got the error above when logging in with yowsup-cli.
CCTELNR1 = the phone numer which has added the user to the group.
CCTELNR2 = the phone number which was added to the group.

**Comment by 4lloyd** [comment]
Solved in: #522
