### ISSUE TITLE
SSL ERROR Windows Python 3.4

### ISSUE THREAD

**Issue by alucardsl** [tgalal/yowsup#721]
Traceback (most recent call last):
  File "yowsup-cli", line 304, in <module>
    if not parser.process():
  File "yowsup-cli", line 156, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup-cli", line 174, in handleRequestCode
    result = codeReq.send()
  File "C:\Python33\yowsup\registration\coderequest.py", line 46, in send
    res = super(WACodeRequest, self).send(parser)
  File "C:\Python33\yowsup\common\http\warequest.py", line 73, in send
    return self.sendGetRequest(parser)
  File "C:\Python33\yowsup\common\http\warequest.py", line 111, in sendGetReques
t
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GE
T")
  File "C:\Python33\yowsup\common\http\warequest.py", line 167, in sendRequest
    conn.request(reqType, path, params, headers);
  File "C:\Python33\lib\http\client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "C:\Python33\lib\http\client.py", line 1126, in _send_request
    self.endheaders(body)
  File "C:\Python33\lib\http\client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "C:\Python33\lib\http\client.py", line 922, in _send_output
    self.send(msg)
  File "C:\Python33\lib\http\client.py", line 857, in send
    self.connect()
  File "C:\Python33\lib\http\client.py", line 1231, in connect
    server_hostname=server_hostname)
  File "C:\Python33\lib\ssl.py", line 365, in wrap_socket
    _context=self)
  File "C:\Python33\lib\ssl.py", line 583, in __init__
    self.do_handshake()
  File "C:\Python33\lib\ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c
:600)

**Comment by alexisjk** [comment]
I am having same issue

**Comment by bkoroglu** [comment]
I am facing the same problem with Python 3.4.

**Comment by bkoroglu** [comment]
According to your Python version, change the file, common\http\warequest.py ,as follows:
if sys.version_info > (3, 3):
   import ssl
   ssl._create_default_https_context = ssl._create_unverified_context

**Comment by AlexAlexandroff** [comment]
didnt help

**Comment by ivoneijr** [comment]
I am having same issue
