### ISSUE TITLE
Installing last Version

### ISSUE THREAD

**Issue by alexisjk** [tgalal/yowsup#724]
Hi All!
Last week i downloaded this great Api ,and i cant make it work.
I am Running Windows 7 ,Pyhton version 3.4.
After running :    
C:\Users\alexis\Desktop\yowsup-master>python yowsup-cli registration --requ
estcode sms --phone 541568469888 --cc 54 --mcc 722 --mnc 034

I am getting the follow output:   

Traceback (most recent call last):
  File "yowsup-cli", line 304, in <module>
    if not parser.process():
  File "yowsup-cli", line 156, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup-cli", line 165, in handleRequestCode
    from yowsup.registration import WACodeRequest
  File "C:\Users\alexis\Desktop\yowsup-master\yowsup\registration\__init__.
py", line 1, in <module>
    from .coderequest import WACodeRequest
  File "C:\Users\alexis\Desktop\yowsup-master\yowsup\registration\codereque
st.py", line 4, in <module>
    from yowsup.common.tools import StorageTools, WATools
  File "C:\Users\alexis\Desktop\yowsup-master\yowsup\common\tools.py", line
 2, in <module>
    from dateutil import tz
  File "build\bdist.win32\egg\dateutil\tz.py", line 16, in <module>
ImportError: No module named six

I even installed the module SIX to solve last error,but it keep getting the same issues.
I know it s installed well because if i run :  

C:\Users\alexis\Desktop\yowsup-master>pip install six --upgrade
I get : 
Requirement already up-to-date: six in c:\python34\lib\site-packages

Any help to finally make this api work i would be great for me!
Thanks in advance!

**Comment by alexisjk** [comment]
I dont have this error anymore:
ImportError: No module named six
But i am having :  
ImportError: No module named 'dateutil'

When i run "pip install dateutil"
I get : 
 Could not find a version that satisfies the requirement date util
 No matching distribution found for dateutil

**Comment by alexisjk** [comment]
Finally,after read some document ,i executed : 
pip install yousp2
Every went great,except i have this error at the end :  

 error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

After that,i tried again :  
C:\Users\alexis\Desktop\yowsup-master>python yowsup-cli registration --requ
estcode sms --phone 541568469888 --cc 54 --mcc 722 --mnc 034

And i get a very different output : 

Traceback (most recent call last):
  File "yowsup-cli", line 304, in <module>
    if not parser.process():
  File "yowsup-cli", line 156, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup-cli", line 174, in handleRequestCode
    result = codeReq.send()
  File "C:\Users\alexis\Desktop\yowsup-master\yowsup\registration\codereque
st.py", line 46, in send
    res = super(WACodeRequest, self).send(parser)
  File "C:\Users\alexis\Desktop\yowsup-master\yowsup\common\http\warequest.
py", line 73, in send
    return self.sendGetRequest(parser)
  File "C:\Users\alexis\Desktop\yowsup-master\yowsup\common\http\warequest.
py", line 111, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GE
T")
  File "C:\Users\alexis\Desktop\yowsup-master\yowsup\common\http\warequest.
py", line 167, in sendRequest
    conn.request(reqType, path, params, headers);
  File "C:\Python34\lib\http\client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1126, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 922, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 857, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 1231, in connect
    server_hostname=server_hostname)
  File "C:\Python34\lib\ssl.py", line 365, in wrap_socket
    _context=self)
  File "C:\Python34\lib\ssl.py", line 583, in __init__
    self.do_handshake()
  File "C:\Python34\lib\ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c
:600)


Thanks in advance again!

**Comment by alexisjk** [comment]
I fixed this ,adding import ssl into coderequest.py
