### ISSUE TITLE
Yowsup Registration Error? SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by lcmeyer37** [tgalal/yowsup#743]
Hello people,
I'm getting SSL: CERTIFICATE_VERIFY_FAILED when trying to do a new registration in yowsup:

c:\Python34\Scripts>python yowsup-cli registration --mcc 724 --mnc 01 --phone 55
1194xxxxxxx --cc 55 --requestcode sms
Traceback (most recent call last):
  File "yowsup-cli", line 304, in <module>
    if not parser.process():
  File "yowsup-cli", line 156, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup-cli", line 174, in handleRequestCode
    result = codeReq.send()
  File "C:\Python34\lib\site-packages\yowsup\registration\coderequest.py", line
46, in send
    res = super(WACodeRequest, self).send(parser)
  File "C:\Python34\lib\site-packages\yowsup\common\http\warequest.py", line 67,
 in send
    return self.sendGetRequest(parser)
  File "C:\Python34\lib\site-packages\yowsup\common\http\warequest.py", line 105
, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GE
T")
  File "C:\Python34\lib\site-packages\yowsup\common\http\warequest.py", line 161
, in sendRequest
    conn.request(reqType, path, params, headers);
  File "C:\Python34\lib\http\client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1126, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 922, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 857, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 1231, in connect
    server_hostname=server_hostname)
  File "C:\Python34\lib\ssl.py", line 365, in wrap_socket
    _context=self)
  File "C:\Python34\lib\ssl.py", line 583, in __init__
    self.do_handshake()
  File "C:\Python34\lib\ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c
:600)

Do you know what could that be?

Thank you,

**Comment by lcmeyer37** [comment]
After trying to do the registration using linux python 2.something, I got this message, it appears that yowsup2 now is no more compatible with WhatsApp

mier@ubuntu:/usr/local/bin$ python yowsup-cli registration --mcc 724 --mnc 01 --cc 55 --phone 551199xxxxxxx --requestcode sms
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

I hope I am wrong! Haha

**Comment by tgalal** [comment]
4fcca47110ffd56fbae53e116ae6f52afa7b7095 fixes this

**Comment by lcmeyer37** [comment]
Yep, it doesn't fix the SSL.

**Comment by vamshise** [comment]
Hi,

I have completed installing all the supported modules and yowsup.

While invoking the registration from yowsup-cli I have also encountered this same issue.

Is everyone blocked due to this while using yowsup or is this only applicable for python 3.4?

It means no one on this world is able to invoke yowsup now? 

Please provide your answer.

Thanks
Vamshi
