### ISSUE TITLE
'DescriptorPool' object has no attribute 'AddFileDescriptor' Error when launching yowsup cli client

### ISSUE THREAD

**Issue by chenshuiluke** [tgalal/yowsup#744]
Whenever I try to start the yowsup cli client:
$ yowsup-cli demos -y -c ~/yowsup

I get the following:

Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.2.78', 'yowsup-cli')
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 729, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1649, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.4/site-packages/yowsup2-2.2.78-py3.4.egg/EGG-INFO/scripts/yowsup-cli", line 304, in <module>
  File "/usr/lib/python3.4/site-packages/yowsup2-2.2.78-py3.4.egg/EGG-INFO/scripts/yowsup-cli", line 223, in process
  File "/usr/lib/python3.4/site-packages/yowsup2-2.2.78-py3.4.egg/EGG-INFO/scripts/yowsup-cli", line 243, in startCmdline
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/site-packages/yowsup2-2.2.78-py3.4.egg/yowsup/demos/cli/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/site-packages/yowsup2-2.2.78-py3.4.egg/yowsup/demos/cli/stack.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/site-packages/yowsup2-2.2.78-py3.4.egg/yowsup/stacks/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/site-packages/yowsup2-2.2.78-py3.4.egg/yowsup/stacks/yowstack.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/site-packages/yowsup2-2.2.78-py3.4.egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/lib/python3.4/site-packages/yowsup2-2.2.78-py3.4.egg/yowsup/layers/axolotl/layer.py", line 3, in <module>
  File "/usr/lib/python3.4/site-packages/axolotl/util/keyhelper.py", line 3, in <module>
    from ..identitykeypair import IdentityKeyPair
  File "/usr/lib/python3.4/site-packages/axolotl/identitykeypair.py", line 1, in <module>
    from .state.storageprotos import IdentityKeyPairStructure
  File "/usr/lib/python3.4/site-packages/axolotl/state/storageprotos.py", line 23, in <module>
    _sym_db.RegisterFileDescriptor(DESCRIPTOR)
  File "/usr/lib/python3.4/site-packages/google/protobuf/symbol_database.py", line 121, in RegisterFileDescriptor
    self.pool.AddFileDescriptor(file_descriptor)
AttributeError: 'DescriptorPool' object has no attribute 'AddFileDescriptor'

I examined a few previous issues in this repo and I saw something about protobuf being incompatible with python 3, so I got the python 3 version, which you can see when I try to install it again: 

pip install python3-protobuf
Requirement already satisfied (use --upgrade to upgrade): python3-protobuf in /usr/lib/python3.4/site-packages
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python3.4/site-packages (from python3-protobuf)

I'm not sure if this can be helpful, but Im running Arch Linux. Any help would be appreciated :)

**Comment by tgalal** [comment]
Can you try this and post result?
> pip install -Iv protobuf==3.0.0-alpha-1

**Comment by chenshuiluke** [comment]
My thanks...that seems to have done the trick.
