### ISSUE TITLE
Command line interface demo /L not working since latest commits

### ISSUE THREAD

**Issue by casperklein** [tgalal/yowsup#763]
I think some commit from May 2, 2015 broke the CLI demo. Before it worked perfect.

How to reproduce:

1. start yowsup-cli with ```-y```
2. enter ```/L```

```
foo:/$ python /new/yowsup/yowsup-cli demos -c /new/yowsup.config -y

Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
Auth: Logged in!
[connected]:Traceback (most recent call last):
  File "/new/yowsup/yowsup-cli", line 304, in <module>
    if not parser.process():
  File "/new/yowsup/yowsup-cli", line 223, in process
    self.startCmdline()
  File "/new/yowsup/yowsup-cli", line 249, in startCmdline
    stack.start()
  File "/new/yowsup/yowsup/demos/cli/stack.py", line 28, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/new/yowsup/yowsup/stacks/yowstack.py", line 166, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/new/yowsup/yowsup/layers/network/layer.py", line 48, in handle_read
    self.receive(data)
  File "/new/yowsup/yowsup/layers/network/layer.py", line 55, in receive
    self.toUpper(data)
  File "/new/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/new/yowsup/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/new/yowsup/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/new/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/new/yowsup/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/new/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/new/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/new/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/new/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/new/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/new/yowsup/yowsup/layers/__init__.py", line 160, in receive
    s.receive(data)
  File "/new/yowsup/yowsup/layers/__init__.py", line 101, in receive
    recv(node)
  File "/new/yowsup/yowsup/layers/protocol_receipts/layer.py", line 17, in recvReceiptNode
    self.toUpper(IncomingReceiptProtocolEntity.fromProtocolTreeNode(node))
  File "/new/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/new/yowsup/yowsup/layers/interface/interface.py", line 71, in receive
    self.callbacks[entityType](entity)
  File "/new/yowsup/yowsup/demos/cli/layer.py", line 346, in onReceipt
    ack = OutgoingAckProtocolEntity(entity.getId(), "receipt", "delivery")
TypeError: __init__() takes exactly 5 arguments (4 given)
```

**Comment by tgalal** [comment]
Thanks for reporting!
