### ISSUE TITLE
Authentication Error: not-authorized

### ISSUE THREAD

**Issue by abdawoud** [tgalal/yowsup#765]
Hello,

I am encountering this issue 
"Authentication Error: not-authorized"
for all of my accounts. I am sure they are not blocked and password is correct as I logged in with them in pidgin plugin and sent a message successfully.

I just want to know is this a common problem or the problem is in my yowsup?

I used one of the accounts two days ago and it logged in and sent successfully.

Thanks
##

**Comment by mutindaz** [comment]
I am having the same issue. Started some hours ago.

**Comment by casperklein** [comment]
Use the latest version of yowsup. Its already fixed: https://github.com/tgalal/yowsup/commit/6345f77b56e474f0eb6143b1363a789254da9ccd

**Comment by mutindaz** [comment]
Thanks @casperklein. Its working now ...

**Comment by rainonwednesday** [comment]
Hi, I'm having a similar issue. When I try to send a message using the command:

> yowsup-cli demos --config config --send NUMBER "MESSAGE"

I first get the following traceback:

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.2.78', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 304, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 227, in process
    self.startSendClient()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 274, in startSendClient
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/yowsup/demos/sendclient/stack.py", line 58, in start
    self.stack.loop()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/yowsup/stacks/yowstack.py", line 170, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/yowsup/layers/network/layer.py", line 48, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/yowsup/layers/network/layer.py", line 55, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/yowsup/layers/coder/layer.py", line 33, in receive
    node = self.reader.getProtocolTreeNode(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/yowsup/layers/coder/decoder.py", line 13, in getProtocolTreeNode
    return self.streamStart(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.78-py2.7.egg/yowsup/layers/coder/decoder.py", line 36, in streamStart
    raise Exception("expecting STREAM_START in streamStart, instead got token: %s" % token)
Exception: expecting STREAM_START in streamStart, instead got token: failure

When I retry with the same command again, I'm not getting the traceback, but instead I keep getting the "Authentication Error: not-authorized" error

However, when I send a message from within the command line client:

> yowsup-cli demos --config config --yowsup
> /L
>/message send NUMBER MESSAGE

it works...

Any ideas on what's going on and how I  can solve this? Thanks in advance!

**Comment by tgalal** [comment]
Can you add --debug as command argument and post output ?

**Comment by sbhayana26** [comment]
$python run.py send 91xxxxxxxxxx Hello --debug
91xxxxxxxxxx Hello
No handlers could be found for logger "yowsup.stacks.yowstack"
--------------------
Authentication error not-authorized
