### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by jacoboliveira** [tgalal/yowsup#766]
Hello my friends, I'm problem when trying to run the following command:
python setup.py install

I know this has been said but I can not find any solution.
The following error:
-----------------------------------------
Traceback (most recent call last):
  File "yowsup-cli", line 304, in <module>
    if not parser.process():
  File "yowsup-cli", line 156, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "yowsup-cli", line 174, in handleRequestCode
    result = codeReq.send()
  File "c:\Repository\yowsup-2.0\trunk\yowsup\registration\coderequest.py", line
 46, in send
    res = super(WACodeRequest, self).send(parser)
  File "c:\Repository\yowsup-2.0\trunk\yowsup\common\http\warequest.py", line 74
, in send
    return self.sendGetRequest(parser)
  File "c:\Repository\yowsup-2.0\trunk\yowsup\common\http\warequest.py", line 11
2, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GE
T")
  File "c:\Repository\yowsup-2.0\trunk\yowsup\common\http\warequest.py", line 16
8, in sendRequest
    conn.request(reqType, path, params, headers);
  File "C:\Python34\lib\http\client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1126, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 922, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 857, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 1231, in connect
    server_hostname=server_hostname)
  File "C:\Python34\lib\ssl.py", line 365, in wrap_socket
    _context=self)
  File "C:\Python34\lib\ssl.py", line 583, in __init__
    self.do_handshake()
  File "C:\Python34\lib\ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c
:600)

Thanks Advance!!!

**Comment by tgalal** [comment]
duplicate #706 #721 #568 #677

**Comment by jacoboliveira** [comment]
thanks a lot!!!

**Comment by AlexAlexandroff** [comment]
Gentlemen, any news on this?
thanks!
