### ISSUE TITLE
Error in sending the 'Ack': TypeError: __init__() takes exactly 5 arguments (4 given)

### ISSUE THREAD

**Issue by idigevian** [tgalal/yowsup#774]
After i cloned the repo and did "python setup.py install", the client and my code sprung back to life today.

However, it seems it is now failing in sending the Ack. I can confirm it was running fine previously.

=============================================================
    @ProtocolEntityCallback("receipt")
    def onReceipt(self, entity):
        ack = OutgoingAckProtocolEntity(entity.getId(), "receipt", "delivery")
        self.toLower(ack)
=============================================================

The entire stack trace
=============================================================
Traceback (most recent call last):
  File "/Users/idigevian/Documents/workspace/primality/WhatsappG/com/run.py", line 31, in <module>
    stack.loop() #this is the program mainloop
  File "build/bdist.macosx-10.6-intel/egg/yowsup/stacks/yowstack.py", line 174, in loop
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 214, in loop
    poll_fun(timeout, map)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 155, in poll
    read(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/network/layer.py", line 73, in handle_read
    
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/network/layer.py", line 80, in receive
    
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/__init__.py", line 55, in toUpper
    
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    print finalMsg
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/__init__.py", line 55, in toUpper
    
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/__init__.py", line 55, in toUpper
    
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/coder/layer.py", line 35, in receive
    ack = OutgoingAckProtocolEntity(entity.getId(), "receipt", "delivery")
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/__init__.py", line 55, in toUpper
    
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/logger/layer.py", line 14, in receive
    receipt = OutgoingReceiptProtocolEntity(messageProtocolEntity.getId(), messageProtocolEntity.getFrom())
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/__init__.py", line 55, in toUpper
    
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/__init__.py", line 160, in receive
    
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/__init__.py", line 101, in receive
    
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/protocol_receipts/layer.py", line 17, in recvReceiptNode
    
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/__init__.py", line 55, in toUpper
    
  File "build/bdist.macosx-10.6-intel/egg/yowsup/layers/interface/interface.py", line 71, in receive
  File "/Users/idigevian/Documents/workspace/primality/WhatsappG/com/layer.py", line 35, in onReceipt
    ack = OutgoingAckProtocolEntity(entity.getId(), "receipt", "delivery")
TypeError: __init__() takes exactly 5 arguments (4 given)
=============================================================

**Comment by tgalal** [comment]
Please see my reply in #770

**Comment by idigevian** [comment]
Cool. Thank you! I think so if the sample app document can be updated as well then that will be great!

Cheers!

**Comment by tgalal** [comment]
@idigevian yup, updated the sample app
