### ISSUE TITLE
Yowsup media send

### ISSUE THREAD

**Issue by Narendra-Kumar** [tgalal/yowsup#789]
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 232, in process
    self.startMediaClient()
  File "yowsup-cli", line 294, in startMediaClient
    stack.start()
  File "C:\Python27\yowsup-master\yowsup\demos\mediaclient\stack.py", line 36, in start
    self.stack.loop()
  File "C:\Python27\yowsup-master\yowsup\stacks\yowstack.py", line 173, in loop
    asyncore.loop(*args, **kwargs)
  File "C:\Python27\lib\asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "C:\Python27\lib\asyncore.py", line 156, in poll
    read(obj)
  File "C:\Python27\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\yowsup-master\yowsup\layers\network\layer.py", line 48, in handle_read
    self.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\network\layer.py", line 55, in receive
    self.toUpper(data)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\stanzaregulator\layer.py", line 28, in receive
    self.processReceived()
  File "C:\Python27\yowsup-master\yowsup\layers\stanzaregulator\layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\auth\layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 161, in receive
    s.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 102, in receive
    recv(node)
  File "C:\Python27\yowsup-master\yowsup\layers\auth\layer_authentication.py", line 55, in handleSuccess
    self.toUpper(nodeEntity)
  File "C:\Python27\yowsup-master\yowsup\layers\__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "C:\Python27\yowsup-master\yowsup\layers\interface\interface.py", line 71, in receive
    self.callbacks[entityType](entity)
  File "C:\Python27\yowsup-master\yowsup\demos\mediaclient\layer.py", line 30, in onSuccess
    self.main()
  File "C:\Python27\yowsup-master\yowsup\demos\mediaclient\layer.py", line 98, in main
    self.MEDIA_TYPE = MediaDiscover.getMediaType(path)
  File "C:\Python27\yowsup-master\yowsup\common\tools.py", line 190, in getMediaType
    mediaType = MediaDiscover.fromMimeType(path)
  File "C:\Python27\yowsup-master\yowsup\common\tools.py", line 162, in fromMimeType
    mimeType = magic.from_file(path, mime=True)
  File "build\bdist.win32\egg\magic.py", line 135, in from_file
  File "build\bdist.win32\egg\magic.py", line 123, in _get_magic_type
  File "build\bdist.win32\egg\magic.py", line 59, in __init__
WindowsError: exception: access violation writing 0x00000002
Exception AttributeError: "Magic instance has no attribute 'cookie'" in <bound method Magic.__del__ of <magic.Magic instance at 0x02E51C38>> ignored

getting above error..
Please advice.

**Comment by tgalal** [comment]
It's not really a yowsup issue, trying googling for it.
