### ISSUE TITLE
error while media upload

### ISSUE THREAD

**Issue by chetanunadkat90** [tgalal/yowsup#795]
Error occured at transfer [Errno 32] Broken pipe
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_media/mediauploader.py", line 97, in run
    ssl_sock.write(stream[:buf])
  File "/usr/lib/python2.7/ssl.py", line 272, in write
    return self._sslobj.write(data)
error: [Errno 32] Broken pipe

**Comment by tgalal** [comment]
still facing the problem ?

**Comment by daemonserj** [comment]
I stuck on exactly same problem:

ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer [Errno 32] Broken pipe
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_media/mediauploader.py", line 97, in run
    ssl_sock.write(stream[:buf])
  File "/usr/lib/python2.7/ssl.py", line 172, in write
    return self._sslobj.write(data)
error: [Errno 32] Broken pipe



Yowsup cloned from git at 17 Mar, all things set up as in CLI app.

git log:
commit a59ac410c057e8042c528e9f73e9f3eaada6e79e
Merge: 4007ee5 f64e6f4
Author: Tarek Galal <tare2.galal@gmail.com>
Date:   Mon Dec 14 08:02:54 2015 +0100

    Merge branch 'release/2.4.48'
