### ISSUE TITLE
Running CentOS 6.6 w. Python 2.6.6 produces errors

### ISSUE THREAD

**Issue by ReSpawN** [tgalal/yowsup#838]
Installed via 2.6.6 worked fine, but after the registration (I got the code) I'm getting loads of errors.
I also tried installing Phyton 2.7, which worked fine, but I am getting nowhere running it as 2.7 atm.

# yowsup-cli demos --yowsup --config config

```
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 6, in <module>
    pkg_resources.run_script('yowsup2==2.3.84', 'yowsup-cli')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 304, in <module>
    if not parser.process():
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 223, in process
    self.startCmdline()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 243, in startCmdline
    from yowsup.demos import cli
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/yowsup/demos/cli/__init__.py", line 1, in <module>
    from .stack import YowsupCliStack
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/yowsup/demos/cli/stack.py", line 1, in <module>
    from yowsup.stacks import YowStack, YowStackBuilder
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/yowsup/stacks/yowstack.py", line 22, in <module>
    from yowsup.layers.axolotl import YowAxolotlLayer
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/yowsup/layers/axolotl/layer.py", line 14, in <module>
    from axolotl.sessioncipher import SessionCipher
  File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/sessioncipher.py", line 3, in <module>
    from Crypto.Util import Counter
ImportError: cannot import name Counter
```
##

**Comment by leo-b** [comment]
_python-axolotl_ needs _pycrypto>=2.6_.

You may install `python-crypto2.6-2.6.1-2` from EPEL parallel to `python-crypto-2.0.1-22.el6` from Centos. However you will have to adapt your binaries, e.g. yowsup-cli to prefer that version:

```
__requires__ = [ 'pycrypto>=2.6' ]
import pkg_resources
```

Alternatively you might try ``python-crypto-2.6.1-1.el6.rfx`` from DAG.
