### ISSUE TITLE
Im getting these errors on a regular basis

### ISSUE THREAD

**Issue by IamC8** [tgalal/yowsup#839]
I have an echo client running which throws the following errors every so often:

Exception in thread YowPingThread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/root/Dropbox/myCloud/yowsup-master/yowsup/layers/protocol_iq/layer.py", line 86, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'sleep'

Where should I look?
Regards

**Comment by jodersus** [comment]
+1

Same problem. I've noticed it happens when Whatsapp closes the connection, typically after not receiving a receipt from a notification.

Is it possible to tell the application to re-connect (say after 30 secs) when Whatsapp disconnects? I tried the simplest code but got an infinite loop...

Thanks
