### ISSUE TITLE
help!!!!! please

### ISSUE THREAD

**Issue by Loxurkrift** [tgalal/yowsup#862]
how  can I fix this?
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Traceback (most recent call last):
  File "run.py", line 39, in <module>
    stack.loop()
  File "/home/pi/yowsup/yowsup/stacks/yowstack.py", line 175, in loop
    asyncore.loop(_args, *_kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/pi/yowsup/yowsup/layers/network/layer.py", line 72, in handle_read
    self.receive(data)
  File "/home/pi/yowsup/yowsup/layers/network/layer.py", line 79, in receive
    self.toUpper(data)
  File "/home/pi/yowsup/yowsup/layers/**init**.py", line 55, in toUpper
    self.**upper.receive(data)
  File "/home/pi/yowsup/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/pi/yowsup/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/pi/yowsup/yowsup/layers/__init**.py", line 55, in toUpper
    self.**upper.receive(data)
  File "/home/pi/yowsup/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/pi/yowsup/yowsup/layers/__init**.py", line 55, in toUpper
    self.**upper.receive(data)
  File "/home/pi/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/pi/yowsup/yowsup/layers/__init**.py", line 55, in toUpper
    self.**upper.receive(data)
  File "/home/pi/yowsup/yowsup/layers/__init**.py", line 160, in receive
    s.receive(data)
  File "/home/pi/yowsup/yowsup/layers/**init**.py", line 101, in receive
    recv(node)
  File "/home/pi/yowsup/yowsup/layers/auth/layer_authentication.py", line 67, in handleFailure
    raise AuthError(nodeEntity.getReason())
yowsup.layers.auth.autherror.AuthError: not-authorized
##

**Comment by mgp25** [comment]
Why so many '!!!' cool down, your password is wrong or your number is blocked

**Comment by lingjip** [comment]
I register the number in order to get the password . And others my number is blocked ?
I can't understand it .
Create a room on https://gitter.im/ for convenient communication.
Below is more try.
------------------------------------------------------------------------------------------------------------------
yowsup-cli registration --cc 86 -r sms -m 460 -n 00 -p 8613824364216 -d
DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.82 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=86&in=13824364216&id=%1Dp%21%CB%994P%B3%D9%02%2AG%5E%87%5Ci%9A%0E%E7%9D&lg=en&lc=GB&token=FCLLC6Rpwq2F4G3VIwy4qjIj6HI%3D
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/exist?cc=86&in=13824364216&id=%1Dp%21%CB%994P%B3%D9%02%2AG%5E%87%5Ci%9A%0E%E7%9D&lg=en&lc=GB&token=FCLLC6Rpwq2F4G3VIwy4qjIj6HI%3D
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"incorrect","sms_length":6,"voice_length":6}

DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.82 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=86&in=13824364216&lc=GB&lg=en&sim_mcc=460&sim_mnc=000&method=sms&token=a614babd98bce8aedadbf4d12d8b79c3&id=s%95%D3%AA%5C%F1%3F%22%FA%14%5B%23c%D9%08%1A%5C%DD%29%3D
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=86&in=13824364216&lc=GB&lg=en&sim_mcc=460&sim_mnc=000&method=sms&token=a614babd98bce8aedadbf4d12d8b79c3&id=s%95%D3%AA%5C%F1%3F%22%FA%14%5B%23c%D9%08%1A%5C%DD%29%3D
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"too_many_guesses","retry_after":64742}

status: fail
retry_after: 64742
reason: too_many_guesses



lingjip
 
From: mgp25
Date: 2015-06-10 17:33
To: tgalal/yowsup
Subject: Re: [yowsup] help!!!!! please (#862)
Why so many '!!!' cool down, your password is wrong or your number is blocked

**Comment by mgp25** [comment]
@lingjip Too many wrong code guesses, wait 64742 seconds

**Comment by Loxurkrift** [comment]
tanks, but now...
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
Traceback (most recent call last):
  File "run.py", line 39, in <module>
    stack.loop()
  File "/home/pi/yowsup/yowsup/stacks/yowstack.py", line 175, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/pi/yowsup/yowsup/layers/network/layer.py", line 72, in handle_read
    self.receive(data)
  File "/home/pi/yowsup/yowsup/layers/network/layer.py", line 79, in receive
    self.toUpper(data)
  File "/home/pi/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/pi/yowsup/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/pi/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/pi/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/pi/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup/yowsup/layers/__init__.py", line 160, in receive
    s.receive(data)
  File "/home/pi/yowsup/yowsup/layers/__init__.py", line 101, in receive
    recv(node)
  File "/home/pi/yowsup/yowsup/layers/protocol_receipts/layer.py", line 17, in recvReceiptNode
    self.toUpper(IncomingReceiptProtocolEntity.fromProtocolTreeNode(node))
  File "/home/pi/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/pi/yowsup/yowsup/layers/interface/interface.py", line 71, in receive
    self.callbacks[entityType](entity)
  File "/home/pi/yowsup/layer.py", line 20, in onReceipt
    ack = OutgoingAckProtocolEntity(entity.getId(), "receipt", "delivery")
TypeError: __init__() takes exactly 5 arguments (4 given)

**Comment by Loxurkrift** [comment]
Hello, already solved the problem, but now disconnects from the server, what can I do?
it takes 2 miuntes for going disconnected sorry for bad english

**Comment by alvariux** [comment]
How did you solve it? I'm having the same issue

**Comment by Loxurkrift** [comment]
you havo to add this entity.getFrom())
example:

class EchoLayer(YowInterfaceLayer):

    @ProtocolEntityCallback("message")
    def onMessage(self, messageProtocolEntity):
        #send receipt otherwise we keep receiving the same message over and over

        if True:
            receipt = OutgoingReceiptProtocolEntity(messageProtocolEntity.getId(), messageProtocolEntity.getFrom(), 'read', messageProtocolEntity.getParticipant())

            outgoingMessageProtocolEntity = TextMessageProtocolEntity(
                messageProtocolEntity.getBody(),
                to = messageProtocolEntity.getFrom())

            self.toLower(receipt)
            self.toLower(outgoingMessageProtocolEntity)

    @ProtocolEntityCallback("receipt")
    def onReceipt(self, entity):
        ack = OutgoingAckProtocolEntity(entity.getId(), "receipt", "delivery", entity.getFrom())
        self.toLower(ack)
