### ISSUE TITLE
Problem with proxy

### ISSUE THREAD

**Issue by koldooteo** [tgalal/yowsup#868]
Hello to everybody. I´m trying to regstrate my cel number, but yowsup-cli is not using the environment http_proxy/https_proxy.
I have redhat 6. I tried it with python 2.7, 3.4 and 2.6 and its the same.

The environment haves username/password in it. I use this variable with curl or other http clients and it works. If I don put v.whatsapp.net on the hosts gives an exception and if i put it gives other error. I also executed a sniffer to see if I connect to the proxy on that moment, but I don´t see traffic on it.

Please any help will be appreciated

The error:

DEBUG:yowsup.common.http.warequest:{'Accept': 'text/json', 'User-Agent': 'WhatsApp/2.12.82 S40Version/14.26 Device/Nokia302'}
DEBUG:yowsup.common.http.warequest:cc=34&in=622000000&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&method=sms&token=6bcXXXXXXXX46db5fd5XX&id=t%C4%11%05-%D7Y%AA%E8%13%ED%1B%24%17%A5%B1%E6%82%B2K
DEBUG:yowsup.common.http.warequest:Opening connection to v.whatsapp.net
DEBUG:yowsup.common.http.warequest:Sending GET request to /v2/code?cc=34&in=62XXXXXX&lc=GB&lg=en&sim_mcc=000&sim_mnc=000&method=sms&token=6bc9f50682323e146db5fd53434a94&id=t%C4%11%02-%D7Y%AA%E8%92%ED%1B%24%17%A5%B1%E6%82%B2K
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.3.84', 'yowsup-cli')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 304, in <module>
    if not parser.process():
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 156, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 174, in handleRequestCode
    result = codeReq.send()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/yowsup/registration/coderequest.py", line 46, in send
    res = super(WACodeRequest, self).send(parser)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/yowsup/common/http/warequest.py", line 73, in send
    return self.sendGetRequest(parser)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/yowsup/common/http/warequest.py", line 111, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET")
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.84-py2.6.egg/yowsup/common/http/warequest.py", line 167, in sendRequest
    conn.request(reqType, path, params, headers);
  File "/usr/lib64/python2.6/httplib.py", line 914, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.6/httplib.py", line 951, in _send_request
    self.endheaders()
  File "/usr/lib64/python2.6/httplib.py", line 908, in endheaders
    self._send_output()
  File "/usr/lib64/python2.6/httplib.py", line 780, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.6/httplib.py", line 739, in send
    self.connect()
  File "/usr/lib64/python2.6/httplib.py", line 1112, in connect
    sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/usr/lib64/python2.6/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

**Comment by Rustem** [comment]
Looks like your ENV not well configured
