### ISSUE TITLE
Send Message Error under python 3.4.3

### ISSUE THREAD

**Issue by budiw0219** [tgalal/yowsup#878]
I'm on windows 8. I got success during registration of my phone. But always got error to try sending message.

D:\Yowsup\yowsup-master>python yowsup-cli registration --register xxxx --phone 62xxxxxxxxx --cc 62

kind: b'free'
pw: b'Dxxxxxxxxxxxxxxxxxxxxxxxxxxx='
price_expiration: 1437269860
login: b'62xxxxxxxxxxxx'
cost: b'9500.00'
type: b'new'
status: b'ok'
expiration: 1465886066
currency: b'IDR'
price: b'Rp9500'

when I try to login or send message, I alway got error like this:
python yowsup-cli demos --config yowsup.config --send 62xxxxxxxx "Hello world"

Traceback (most recent call last):
  File "yowsup-cli", line 321, in <module>
    if not parser.process():
  File "yowsup-cli", line 229, in process
    self.startSendClient()
  File "yowsup-cli", line 269, in startSendClient
    from yowsup.demos import sendclient
  File "D:\Yowsup\yowsup-master\yowsup\demos\sendclient\__init__.py", line 1, in \<module>
    from .stack import YowsupSendStack
  File "D:\Yowsup\yowsup-master\yowsup\demos\sendclient\stack.py", line 1, in \<module>
    from yowsup.stacks import YowStack
  File "D:\Yowsup\yowsup-master\yowsup\stacks\__init__.py", line 1, in \<module>
    from .yowstack import YowStack, YowStackBuilder
  File "D:\Yowsup\yowsup-master\yowsup\stacks\yowstack.py", line 22, in \<module>
    from yowsup.layers.axolotl import YowAxolotlLayer
  File "D:\Yowsup\yowsup-master\yowsup\layers\axolotl\__init__.py", line 1, in \<module>
    from .layer import YowAxolotlLayer
  File "D:\Yowsup\yowsup-master\yowsup\layers\axolotl\layer.py", line 3, in \<module>
    from axolotl.util.keyhelper import KeyHelper
  File "\<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "\<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "\<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "\<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\python_axolotl-0.1.7-py3.4.egg\axolotl\util\keyhelper.py", line 3, in \<module>
  File "\<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "\<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "\<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "\<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\python_axolotl-0.1.7-py3.4.egg\axolotl\ide
ntitykeypair.py", line 1, in <module>
  File "\<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "\<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "\<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "\<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\python_axolotl-0.1.7-py3.4.egg\axolotl\sta
te\storageprotos.py", line 8, in <module>
  File "C:\Python34\lib\site-packages\google\protobuf\reflection.py", line 68, in \<module>
    from google.protobuf.internal import python_message
  File "C:\Python34\lib\sitepackages\google\protobuf\internal\python_message.py", line 848
    except struct.error, e:
                       ^
SyntaxError: invalid syntax

For reference:
D:\Yowsup\yowsup-master>python yowsup-cli demos --version
yowsup-cli v2.0.9
Using yowsup v2.3.84

my yowsup.config:
cc=62 
phone=62xxxxxxxxxx
id=
password=Dxxxxxxxxxxxxxxxxxxxxxxxxxxx=

Can somebody give me some adviseto fix this error messages. Thank you.

Best regards
budiw

**Comment by tgalal** [comment]
> pip install -Iv protobuf==3.0.0-alpha-1

**Comment by budiw0219** [comment]
Thank you for your respond.
I got another error from pip install -Iv protobuf==3.0.0-alpha-1
C:\>pip install -Iv protobuf==3.0.0-alpha-1
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\pip.exe\__main__.py", line 5, in <module>
  File "C:\Python34\lib\site-packages\pip\__init__.py", line 13, in <module>
    from pip.commands import commands, get_summaries, get_similar_commands
  File "C:\Python34\lib\site-packages\pip\commands\__init__.py", line 6, in <mod
ule>
    from pip.commands.bundle import BundleCommand
  File "C:\Python34\lib\site-packages\pip\commands\bundle.py", line 6, in <modul
e>
    from pip.commands.install import InstallCommand
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 5, in <modu
le>
    from pip.req import InstallRequirement, RequirementSet, parse_requirements
  File "C:\Python34\lib\site-packages\pip\req\__init__.py", line 3, in <module>
    from .req_install import InstallRequirement
  File "C:\Python34\lib\site-packages\pip\req\req_install.py", line 30, in <modu
le>
    from pip.utils import (
  File "C:\Python34\lib\site-packages\pip\utils\__init__.py", line 87, in <modul
e>
    def rmtree(dir, ignore_errors=False):
  File "C:\Python34\lib\site-packages\pip\_vendor\retrying.py", line 47, in wrap

    @six.wraps(f)
AttributeError: 'module' object has no attribute 'wraps'
