### ISSUE TITLE
yowsup-cli error to send

### ISSUE THREAD

**Issue by gustavosms** [tgalal/yowsup#882]
root@server:/usr/local/yowsup/yowsup-master# yowsup-cli demos -c /usr/local/yowsup/yowsup-master/TIMpo.config -s 55999999999 "test"
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.3.84', 'yowsup-cli')
  File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 735, in run_script
  File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 1659, in run_script
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.84-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 321, in <module>

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.84-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 229, in process

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.84-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 269, in startSendClient

  File "build/bdist.linux-i686/egg/yowsup/demos/sendclient/__init__.py", line 1, in <module>
  File "build/bdist.linux-i686/egg/yowsup/demos/sendclient/stack.py", line 1, in <module>
  File "build/bdist.linux-i686/egg/yowsup/stacks/__init__.py", line 1, in <module>
  File "build/bdist.linux-i686/egg/yowsup/stacks/yowstack.py", line 22, in <module>
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/layer.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/util/keyhelper.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/identitykeypair.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/state/storageprotos.py", line 9, in <module>
ImportError: cannot import name symbol_database

**Comment by gustavosms** [comment]
Any help?

**Comment by tgalal** [comment]
> pip install -Iv protobuf==3.0.0-alpha-1

**Comment by gustavosms** [comment]
The command:
pip install -Iv protobuf==3.0.0-alpha-1
result with: Successfully installed protobuf-3.0.0a1 setuptools-17.1.1

But still not working:
root@server:~# yowsup-cli demos -c /usr/local/yowsup/yowsup-master/TIMpo.config -s 5598999999999 "test"
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.3.84', 'yowsup-cli')
  File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 735, in run_script
  File "build/bdist.linux-i686/egg/pkg_resources/__init__.py", line 1659, in run_script
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.84-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 321, in <module>

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.84-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 229, in process

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.84-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 269, in startSendClient

  File "build/bdist.linux-i686/egg/yowsup/demos/sendclient/__init__.py", line 1, in <module>
  File "build/bdist.linux-i686/egg/yowsup/demos/sendclient/stack.py", line 1, in <module>
  File "build/bdist.linux-i686/egg/yowsup/stacks/__init__.py", line 1, in <module>
  File "build/bdist.linux-i686/egg/yowsup/stacks/yowstack.py", line 22, in <module>
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
  File "build/bdist.linux-i686/egg/yowsup/layers/axolotl/layer.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/util/keyhelper.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/identitykeypair.py", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/state/storageprotos.py", line 9, in <module>
ImportError: cannot import name symbol_database
root@server:~#

Versions:
Python 2.7.3 (default, Mar 14 2014, 11:57:14)
[GCC 4.7.2] on linux2
Debian 7.8

**Comment by gustavosms** [comment]
closed, but still same problem??
please help
