### ISSUE TITLE
ERROR: profile setPicture

### ISSUE THREAD

**Issue by kernelpanic2015** [tgalal/yowsup#897]
/profile setPicture logo.jpg
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/yowsup/yowsup/demos/cli/cli.py", line 151, in startInputThread
    wait = self.execCmd(cmd)
  File "/usr/local/yowsup/yowsup/demos/cli/cli.py", line 135, in execCmd
    return self.doExecCmd(lambda :targetFn(*args))
  File "/usr/local/yowsup/yowsup/demos/cli/cli.py", line 138, in doExecCmd
    return fn()
  File "/usr/local/yowsup/yowsup/demos/cli/cli.py", line 135, in <lambda>
    return self.doExecCmd(lambda :targetFn(*args))
  File "/usr/local/yowsup/yowsup/demos/cli/layer.py", line 223, in profile_setPicture
    pictureData = src.resize((640, 640)).tobytes("jpeg", "RGB")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 550, in tobytes
    e = _getencoder(self.mode, encoder_name, args)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 406, in _getencoder
    return encoder(mode, *args + extra)
SystemError: unknown raw mode

**Comment by jlguardi** [comment]
Replace tobytes by tostring. It is a problem with PiL version.

**Comment by kernelpanic2015** [comment]
I found 2 ways to resolve this.
1- uninstall pillow (#pip uninstall pillow) -> install python2.7-dev (#apt-get install python2.7-dev) -> re-install pillow (#pip install pillow)
2- the problem show to convert jpg files, so I use only gif files and work.
Thank you.
