### ISSUE TITLE
Error on registration (twilio virtual number)

### ISSUE THREAD

**Issue by gplaza** [tgalal/yowsup#916]
Hello,

i have a french number from twilio.
i have used this command :

yowsup-cli registration --requestcode sms --phone 336XXXXXXXXX --cc 33 --mcc 208 --mnc 22
The first time the message was (success) "sent", but i don't have the sms in twilio console log

In my second try i have a bug :

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 321, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 156, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/local/bin/yowsup-cli", line 174, in handleRequestCode
    result = codeReq.send()
  File "/usr/local/lib/python2.6/dist-packages/yowsup/registration/coderequest.py", line 38, in send
    request = WAExistsRequest(self.cc, self.p_in, self.__id)
  File "/usr/local/lib/python2.6/dist-packages/yowsup/registration/existsrequest.py", line 15, in __init__
    self.addParam("token", CURRENT_ENV.getToken(p_in))
  File "/usr/local/lib/python2.6/dist-packages/yowsup/env/env_android.py", line 55, in getToken
    subHash.update(ipad + data)
TypeError: update() argument 1 must be string or read-only buffer, not bytearray

imposible to try another registration always the same traceback :(
Why ?

**Comment by get2joao** [comment]
Please delete the .yowsup folder from user home directory and try again..

Thanks,

**Comment by tgalal** [comment]
latest changes in develop branch should fix this problem, please try and post feedback

**Comment by gplaza** [comment]
Both solution, fix the issue :) thx guys !!
note : Twilio virtual french number seem not worked with SMS of WhatAPP (GLOBAL SMS DISABLED)
