### ISSUE TITLE
"OSError: [Errno 13] Permission denied" from apache shell_exec 

### ISSUE THREAD

**Issue by gschanuel** [tgalal/yowsup#920]
I'm this error running yowsup via shell_exec in a php page
Apache/2.2.15 
PHP/5.3.3
CentOS 6.6
Python 2.6.6

```
<?php
   $output=shell_exec("whoami");
   echo "<pre>$output</pre>";
   $output=shell_exec('http_proxy=192.168.3.42:3128 yowsup-cli demos -d -c /etc/yowsup.conf --send 5541XXXXXXXX "test123 i asda"  2>&1; echo $?' );
   echo "<pre>$output</pre>";
?> 
```

I get this:

```
apache
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.layers.network.layer:HttpProxy initialize: ('192.168.3.42', 3128)
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:HttpProxy connect: c2.whatsapp.net:443
DEBUG:yowsup.layers.network.layer:HttpProxy handle connect
DEBUG:yowsup.layers.network.layer:HttpProxy connected
DEBUG:yowsup.layers.logger.layer:tx:











Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 5, in 
    pkg_resources.run_script('yowsup2==2.3.123', 'yowsup-cli')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 321, in 
    if not parser.process():
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 229, in process
    self.startSendClient()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 278, in startSendClient
    stack.start()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/demos/sendclient/stack.py", line 58, in start
    self.stack.loop()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/stacks/yowstack.py", line 175, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python2.6/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.6/asyncore.py", line 151, in poll
    read(obj)
  File "/usr/lib64/python2.6/asyncore.py", line 82, in read
    obj.handle_error()
  File "/usr/lib64/python2.6/asyncore.py", line 78, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.6/asyncore.py", line 428, in handle_read_event
    self.handle_read()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/network/layer.py", line 68, in handle_read
    data = self.proxyHandler.recv(self, readSize)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/common/http/httpproxy.py", line 93, in recv
    self.onConnect()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/network/layer.py", line 30, in onConnect
    self.handle_connect()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/network/layer.py", line 55, in handle_connect
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/__init__.py", line 68, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/__init__.py", line 68, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/__init__.py", line 68, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/__init__.py", line 68, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/__init__.py", line 62, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/__init__.py", line 178, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/auth/layer_authentication.py", line 39, in onEvent
    self.login()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/auth/layer_authentication.py", line 49, in login
    self._sendAuth()
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/layers/auth/layer_authentication.py", line 88, in _sendAuth
    nonce = StorageTools.getNonce(self.credentials[0])
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/common/tools.py", line 75, in getNonce
    path = StorageTools.getStorageForPhone(phone)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/common/tools.py", line 49, in getStorageForPhone
    return StorageTools.constructPath(phone + '/')
  File "/usr/lib/python2.6/site-packages/yowsup2-2.3.123-py2.6.egg/yowsup/common/tools.py", line 44, in constructPath
    os.makedirs(os.path.dirname(fullPath))
  File "/usr/lib64/python2.6/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib64/python2.6/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/root/.yowsup'
1
```

You can see apache is running as user **apache**, so why is yowsup trying to write in /root/.yowsup?
##

**Comment by gschanuel** [comment]
Also, when I run it from bash as *apache* user it runs fine
```
-bash-4.1$ http_proxy=http://192.168.3.42:3128  php /var/www/html/teste.php 
<pre>apache
</pre><pre>DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.layers.network.layer:HttpProxy initialize: ('192.168.3.42', 3128)
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:HttpProxy connect: c2.whatsapp.net:443
DEBUG:yowsup.layers.network.layer:HttpProxy handle connect
DEBUG:yowsup.layers.network.layer:HttpProxy connected
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="5541YYYYYYYY" mechanism="WAUTH-2">
�3�5�en�@MZ���d������k����1���2�}�Q|�;cLF
HEX:da33bd35fc656eff40024d5a871fc8f164eaf0abc0ebd16b91e5feb53104b81ee710ca32e57d91517c8b3b634c46
</auth>

DEBUG:yowsup.layers.network.layer:HttpProxy handle read: HTTP/1.1 200 Connection established
Connection: close


DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
�$1▒�
     ���c飋���▒�݋
HEX:dd24311aac0c84d8ec63e9a38bbf83ef1aefdd8b
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
�+�7�}��nz㪟 
             �}[�,�D���\���OA����e�t    �
HEX:a92bec7f3717a47d9efc6e7a0fe3aa9f200bad7d5bdb2c068644a6b0a37f5cc5c101dc4f41bb9792c965a77409b5
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1435766682" expiration="1467302682" props="4" t="1436323841">
<�v
   3>g`�'�      >�^�V��^
HEX:3cd3760c333e67609427f5093eea5eef5697bd5e
</success>

DEBUG:yowsup.layers.logger.layer:tx:
<message to="5541YYYYYYYY@s.whatsapp.net" type="text" id="1436323789-1">
<body>
teste123 i asda
HEX:746573746531323320692061736461
</body>
</message>

DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1435766682" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<ack t="1436323841" from="5541XXXXXXXX@s.whatsapp.net" id="1436323789-1" class="message">
</ack>

INFO:yowsup.demos.sendclient.layer:Message sent

Yowsdown
0
```

**Comment by prasselpikachu** [comment]
This has to do with daemons and where they're executed.

However, as you're using PHP anyway, you might want to consider using [Chat-API](https://github.com/WHAnonymous/Chat-API)

**Comment by coi6644** [comment]
@gschanuel: I solve this problem running at the same line of yowsup-cli these commands
shell_exec("export UID=`id`;export HOME=`getent passwd \$UID|cut -d: -f6`; export PYTHON_EGG_CACHE=\$HOME/.python-eggs; <YOWSUPCLI COMMAND HERE>");
yowsup-cli create some directory/files at the user's home dir (.yowsup and .python-eggs), so you need apropriate permissions. I hope it works for you.

**Comment by tablaz** [comment]
Configure the file "constants.py" accordingly to point to a directory with write access permission for user  (otherwise it was trying to write over /root/.yowsup)

PATH_STORAGE = "/xxxx/.yowsup"
