### ISSUE TITLE
Bild verschicken....

### ISSUE THREAD

**Issue by s00rb** [tgalal/yowsup#932]
ich machs mal auf deutsch :)
ich habe alle python pakete usw gefühlte 100 mal installiert. einen zweiten raspberry komplett neu aufgesetzt. immer wieder wie gleiche fehlermeldung beim verschicken eines bildes..

2015.07.15 22:50:56 3: WhatsApp: sending /image send 4916########0/opt/fhem/mama.jpg
2015.07.15 22:50:56 4: WhatsApp: parse: [connected]:
2015.07.15 22:50:57 4: WhatsApp: parse: mama.jpg => 4916########0@s.whatsapp.net, 3% 
mama.jpg => 4916########0@s.whatsapp.net, 6% 
mama.jpg => 4916########0@s.whatsapp.net, 10% 
mama.jpg => 4916########0@s.whatsapp.net, 13% 
mama.jpg => 4916########0@s.whatsapp.net, 17% 
mama.jpg => 4916########0@s.whatsapp.net, 20% 
mama.jpg => 4916########0@s.whatsapp.net, 24% 
mama.jpg => 4916########0@s.whatsapp.net, 27% 
mama.jpg => 4916########0@s.whatsapp.net, 31% 
mama.jpg => 4916########0@s.whatsapp.net, 34% 
mama.jpg => 4916########0@s.whatsapp.net, 37% 
mama.jpg => 4916########0@s.whatsapp.net, 41% 
mama.jpg => 4916########0@s.whatsapp.net, 44% 
mama.jpg => 4916########0@s.whatsapp.net, 48% 
mama.jpg => 4916########0@s.whatsapp.net, 51% 
mama.jpg => 4916########0@s.whatsapp.net, 55% 
mama.jpg => 4916########0@s.whatsapp.net, 58% 
mama.jpg => 4916########0@s.whatsapp.net, 62% 
mama.jpg => 4916########0@s.whatsapp.net, 65% 
mama.jpg => 4916########0@s.whatsapp.net, 68% 
mama.jpg => 4916########0@s.whatsapp.net, 72% 
mama.jpg => 4916########0@s.whatsapp.net, 75% 
mama.jpg => 4916########0@s.whatsapp.net, 79% 
mama.jpg => 4916########0@s.whatsapp.net, 82% 
2015.07.15 22:50:57 4: WhatsApp: parse: mama.jpg => 4916########0@s.whatsapp.net, 86% 
mama.jpg => 4916########0@s.whatsapp.net, 89% 
mama.jpg => 4916########0@s.whatsapp.net, 93% 
mama.jpg => 4916########0@s.whatsapp.net, 96% 
mama.jpg => 4916########0@s.whatsapp.net, 99% 
ERROR:yowsup.layers.protocol_media.mediauploader:uploadUrl: https://mmi601.whatsapp.net/u/_DJk7kO53lXU0z4EvQNKQJ-4VAIABRrwHIMz_A/Au23sBAuWaimJGra_6IeS7umJiDLPR2A-toIefLwY7TX, result of uploading media has no url
Traceback (most recent call last):
  File "/opt/yowsup-master/yowsup/stacks/yowstack.py", line 170, in loop
    callback = self.__class__.__detachedQueue.get(False) #doesn't block
  File "/usr/lib/python2.7/Queue.py", line 165, in get
    raise Empty
Empty
ERROR:yowsup.demos.cli.layer:Upload file /opt/fhem/1.jpg to https://mmi601.whatsapp.net/u/_DJk7kO53lXU0z4EvQNKQJ-4VAIABRrwHIMz_A/Au23sBAuWaimJGra_6IeS7umJiDLPR2A-toIefLwY7TX for 4916########0@s.whatsapp.net failed!
2015.07.15 22:50:58 4: WhatsApp: parse: mama.jpg => 4916########0@s.whatsapp.net, 100%

**Comment by prasselpikachu** [comment]
Ich buddel das hier mal aus. Ich hab noch keine Ahnung von Bildern, allerdings empfehl ich dir, das ganze noch mal auf Englisch zu posten, da dann alle helfen können ;)

**Comment by s00rb** [comment]
Huhu. 
Danke für die Antwort. 
Ich probiere mein Glück mal auf Englisch. 
Mal gucken ob mich dann noch wer versteht :)

Lieben Gruß 
Mario

**Comment by brunmayr** [comment]
Hallo Mario

Konntest du das Problem lösen? Steh vor dem selben Thema- hab schon alle möglichen Requirements nachinstalliert, pillow aktualisiert, yowsup mehrfach neu installiert- hat leider alles nix gebracht.

OS: Debian GNU/Linux 7

pip list
chardet (2.0.1)
Warning: cannot find svn location for distribute===0.6.24dev-r0
distribute (0.6.24dev-r0)
enum34 (1.0.4)
fpconst (0.7.2)
idna (2.0)
ipaddress (1.0.15)
Pillow (3.0.0)
pip (7.1.2)
protobuf (2.6.1)
pyasn1 (0.1.9)
pycparser (2.14)
pycrypto (2.6.1)
python-apt (0.8.8.2)
python-axolotl (0.1.7)
python-axolotl-curve25519 (0.1)
python-dateutil (1.5)
python-debian (0.1.21)
python-debianbts (1.11)
reportbug (6.4.4)
setuptools (0.6rc11)
six (1.10.0)
SOAPpy (0.12.0)

Danke und LG
Georg
