### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by rami-dabain** [tgalal/yowsup#941]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "models/yowsup/stacks/yowstack.py", line 175, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 446, in handle_read_event
    self.handle_connect_event()
  File "/usr/lib/python2.7/asyncore.py", line 454, in handle_connect_event
    raise socket.error(err, _strerror(err))
error: [Errno 110] Connection timed out

**Comment by aesedepece** [comment]
Same here from two different IPs, even after applying last changes from master.

**Comment by maggnetz** [comment]
same here

**Comment by jlguardi** [comment]
Same here from 4 IP of different countries and for more than 20 numbers.

**Comment by jlguardi** [comment]
Working again. Thanks!
