### ISSUE TITLE
 except struct.error, e:  SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by gjain0** [tgalal/yowsup#943]
``` shell
gaurav@gaurav:~/$ yowsup-cli registration --requestcode sms --phone 91995****74 --cc 91 --mcc 404 --mnc 10
gaurav@gaurav:~/$ yowsup-cli registration --register <6digit number received> --phone 91995****74 --cc 91
```

After getting password, I hit the command

``` shell
gaurav@gaurav:~/$ yowsup-cli demos --login 91995****74:lfslWzWDLpu9aSEUek5u4iVuroM= --send 91813*****75 "Test message"
```

And I got this error

```
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 321, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 229, in process
    self.startSendClient()
  File "/usr/local/bin/yowsup-cli", line 269, in startSendClient
    from yowsup.demos import sendclient
  File "/usr/local/lib/python3.4/dist-packages/yowsup/demos/sendclient/__init__.py", line 1, in <module>
    from .stack import YowsupSendStack
  File "/usr/local/lib/python3.4/dist-packages/yowsup/demos/sendclient/stack.py", line 1, in <module>
    from yowsup.stacks import YowStack
  File "/usr/local/lib/python3.4/dist-packages/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/usr/local/lib/python3.4/dist-packages/yowsup/stacks/yowstack.py", line 22, in <module>
    from yowsup.layers.axolotl import YowAxolotlLayer
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer import YowAxolotlLayer
  File "/usr/local/lib/python3.4/dist-packages/yowsup/layers/axolotl/layer.py", line 3, in <module>
    from axolotl.util.keyhelper import KeyHelper
  File "/usr/local/lib/python3.4/dist-packages/axolotl/util/keyhelper.py", line 3, in <module>
    from ..identitykeypair import IdentityKeyPair
  File "/usr/local/lib/python3.4/dist-packages/axolotl/identitykeypair.py", line 1, in <module>
    from .state.storageprotos import IdentityKeyPairStructure
  File "/usr/local/lib/python3.4/dist-packages/axolotl/state/storageprotos.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/reflection.py", line 68, in <module>
    from google.protobuf.internal import python_message
  File "/usr/local/lib/python3.4/dist-packages/google/protobuf/internal/python_message.py", line 848
    except struct.error, e:
                       ^
SyntaxError: invalid syntax
```
##

**Comment by rami-dabain** [comment]
looks like google package is not for python3

**Comment by ComFreek** [comment]
See #871
