### ISSUE TITLE
Error in yowsup-cli since latest update.

### ISSUE THREAD

**Issue by Agandir** [tgalal/yowsup#947]
Hey.

After the latest update, i installed yowsup on a new server, but i get this error when i perform the quick login "/L"

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/cli.py", line 152, in startInputThread
    wait = self.execCmd(cmd)
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/cli.py", line 136, in execCmd
    return self.doExecCmd(lambda :targetFn(*args))
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/cli.py", line 139, in doExecCmd
    return fn()
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/cli.py", line 136, in <lambda>
    return self.doExecCmd(lambda :targetFn(*args))
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/layer.py", line 404, in L
    return self.login(*self.getProp(YowAuthenticationProtocolLayer.PROP_CREDENTIALS))
  File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/layer.py", line 414, in login
    self.broadcastEvent(connectEvent)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 72, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 178, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_authentication.py", line 41, in onEvent
    self.credentials = self.__getCredentials()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_authentication.py", line 34, in __getCredentials
    password = base64.b64decode(pb64)
  File "/usr/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

And i have no idea honestly on what to do, so please, give me some help ;)

**Comment by rami-dabain** [comment]
wrong password

**Comment by tgalal** [comment]
your password is missing '=' at the end

**Comment by Agandir** [comment]
thanks.  Usually for the wrong password i ever get this error message and that's why i opened the issue:

general: Login Failed, reason: not-authorized
Auth Error, reason not-authorized

But now i noticed that you are correct, was simply a copy/paste mistake missing the "="

Regards
