### ISSUE TITLE
Exception: No such signedprekeyrecord! 

### ISSUE THREAD

**Issue by devilankur18** [tgalal/yowsup#961]
Usecase: Register a number from whatsapp and thats number seems to be working fine. Now move it to other computer/server. The sqlite db which have the keys is empty on the new server. Also there are some pending messages in the queue to be received.

I am new to the project, I did some debugging, what I found is there is no existing keys in the sqlite. And when running the echo client, the messages are received and they are processed before the key persistKeys function is called inside axolotl layer. 

So when message is received, there is no key in the db to decode it against. So it just fails there.

      DEBUG:yowsup.layers.logger.layer:rx:
      <ib from="s.whatsapp.net">
      <offline count="0">
      </offline>
      </ib>

      DEBUG:yowsup.layers.logger.layer:rx:
      <message type="text" notify="Ankur Agarwal" from="919452xxxxxx@s.whatsapp.net" id="1437837352-183" t="1437868209">
      <enc type="pkmsg" v="1">
      6m��K<�g��W�:��!���)����z_�ez����7����4-Q�    "B3
      !Q\uDW��7�2J���R�r=/��BqF�z
                                 "�q
                                    {�F��{��wuC>�V���w(�i0
      HEX:3308b1dae905122105327b5974928aee2a663a650d0d366d8b914b3cf3829967c4c757843a0fa3b20e1a2105b3e5e3298ccff003e47a5fb9657a93a6f7cd371db8b1f389ed342d51bd1509092242330a2105515c75440557031dfcc737f1324a8f8ed052ec82720f3d2fe918b1427146f57a100b18002210e6710b7bc146b1ae7bd5f7771675433eee561995e9a2c37728d9693000
      </enc>
      </message>

      > /root/yowsup/yowsup/layers/axolotl/store/sqlite/litesignedprekeystore.py(17)loadSignedPreKey()
      -> cursor = self.dbConn.cursor()
      (Pdb) DEBUG:yowsup.layers.protocol_iq.layer:ping queue size: 1
      DEBUG:yowsup.layers.logger.layer:tx:
      <iq xmlns="w:p" type="get" id="1">
      </iq>

      c
      Traceback (most recent call last):
        File "./yowsup-cli", line 327, in <module>
          if not parser.process():
        File "./yowsup-cli", line 233, in process
          self.startEcho()
        File "./yowsup-cli", line 269, in startEcho
          stack.start()
        File "/root/yowsup/yowsup/demos/echoclient/stack.py", line 52, in start
          self.stack.loop()
        File "/root/yowsup/yowsup/stacks/yowstack.py", line 175, in loop
          asyncore.loop(*args, **kwargs)
        File "/usr/lib/python2.7/asyncore.py", line 216, in loop
          poll_fun(timeout, map)
        File "/usr/lib/python2.7/asyncore.py", line 156, in poll
          read(obj)
        File "/usr/lib/python2.7/asyncore.py", line 87, in read
          obj.handle_error()
        File "/usr/lib/python2.7/asyncore.py", line 83, in read
          obj.handle_read_event()
        File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
          self.handle_read()
        File "/root/yowsup/yowsup/layers/network/layer.py", line 73, in handle_read
          self.receive(data)
        File "/root/yowsup/yowsup/layers/network/layer.py", line 80, in receive
          self.toUpper(data)
        File "/root/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
          self.__upper.receive(data)
        File "/root/yowsup/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
          self.processReceived()
        File "/root/yowsup/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
          self.toUpper(oneMessageData)
        File "/root/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
          self.__upper.receive(data)
        File "/root/yowsup/yowsup/layers/auth/layer_crypt.py", line 63, in receive
          self.toUpper(payload)
        File "/root/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
          self.__upper.receive(data)
        File "/root/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
          self.toUpper(node)
        File "/root/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
          self.__upper.receive(data)
        File "/root/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
          self.toUpper(data)
        File "/root/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
          self.__upper.receive(data)
        File "/root/yowsup/yowsup/layers/axolotl/layer.py", line 102, in receive
          self.onMessage(protocolTreeNode)
        File "/root/yowsup/yowsup/layers/axolotl/layer.py", line 120, in onMessage
          self.handleEncMessage(protocolTreeNode)
        File "/root/yowsup/yowsup/layers/axolotl/layer.py", line 175, in handleEncMessage
          self.handlePreKeyWhisperMessage(node)
        File "/root/yowsup/yowsup/layers/axolotl/layer.py", line 186, in handlePreKeyWhisperMessage
          plaintext = sessionCipher.decryptPkmsg(preKeyWhisperMessage)
        File "/var/app/local/lib/python2.7/site-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessioncipher.py", line 91, in decryptPkmsg
        File "/var/app/local/lib/python2.7/site-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessionbuilder.py", line 43, in process
        File "/var/app/local/lib/python2.7/site-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessionbuilder.py", line 104, in processV3
        File "/root/yowsup/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 65, in loadSignedPreKey
          return self.signedPreKeyStore.loadSignedPreKey(signedPreKeyId)
        File "/root/yowsup/yowsup/layers/axolotl/store/sqlite/litesignedprekeystore.py", line 17, in loadSignedPreKey
          cursor = self.dbConn.cursor()
      Exception: No such signedprekeyrecord! 0

**Comment by tgalal** [comment]
Please try code from develop branch

**Comment by devilankur18** [comment]
@tgalal The errors are gone, It seems to have worked but still need to restart echo command multiple times before echo client started echoing back.
