### ISSUE TITLE
Truncated string

### ISSUE THREAD

**Issue by Adinan** [tgalal/yowsup#966]
HI,

I am trying to run, an echo client based in [example](https://github.com/tgalal/yowsup/wiki/Yowsup-2.0-Sample-app).

But, i get the follow error when run ```python run.py```

--

```
No handlers could be found for logger "yowsup.stacks.yowstack"
Traceback (most recent call last):
  File "run.py", line 38, in <module>
    stack.loop() #this is the program mainloop
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 175, in loop
  File "/usr/local/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/local/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/local/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/local/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 73, in handle_read

  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 80, in receive

  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive

  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived

  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive

  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
    if True:
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 99, in receive

  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 117, in onMessage

  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 172, in handleEncMessage

  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 183, in handlePreKeyWhisperMessage

  File "/usr/local/lib/python2.7/site-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessioncipher.py", line 91, in decryptPkmsg
  File "/usr/local/lib/python2.7/site-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessionbuilder.py", line 43, in process
  File "/usr/local/lib/python2.7/site-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessionbuilder.py", line 104, in processV3
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 65, in loadSignedPreKey
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/store/sqlite/litesignedprekeystore.py", line 23, in loadSignedPreKey
  File "/usr/local/lib/python2.7/site-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/state/signedprekeyrecord.py", line 8, in __init__
  File "build/bdist.linux-x86_64/egg/google/protobuf/message.py", line 186, in ParseFromString
  File "build/bdist.linux-x86_64/egg/google/protobuf/internal/python_message.py", line 859, in MergeFromString
  File "build/bdist.linux-x86_64/egg/google/protobuf/internal/python_message.py", line 892, in InternalParse
  File "build/bdist.linux-x86_64/egg/google/protobuf/internal/decoder.py", line 556, in DecodeField
google.protobuf.message.DecodeError: Truncated string.
```
--

The only thing I found closest that, it was the #619.
But, even running in other python version, for example python2.7, the error persist.

Someone can help me?
Thanks

**Comment by kotorigadaisuki** [comment]
I'm experimenting the same, and with different versions of python too. Also tried installing different versions of protobuf, but it doesn't get fixed. The problems appears specifically when I try to send a message.
