### ISSUE TITLE
yowsup-cli: 'NoneType' object has no attribute 'getData'

### ISSUE THREAD

**Issue by hsaratoga** [tgalal/yowsup#970]
Hi!, this is the what i did:

-apt-get update && apt-get dist-upgrade -y
-wget https://github.com/tgalal/yowsup/archive/v2.3.183.tar.gz
-tar ....
-python setup.py install

#yowsup-cli demos --yowsup --login 34610xxxxxx:LI/jS2ZLxxxxxxxxxxxxxxxxxxxxxxx

Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
Auth: Logged in!
[connected]:Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.3.183', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 327, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 259, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/demos/cli/stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/stacks/yowstack.py", line 167, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/network/layer.py", line 73, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/network/layer.py", line 80, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/__init__.py", line 160, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/__init__.py", line 101, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'
root@.....:/home/pi/yowsup-master# 

thanks!

**Comment by tgalal** [comment]
can you please add --debug to the command and post output?

```yowsup-cli demos --yowsup --login 34610xxxxxx:LI/jS2ZLxxxxxxxxxxxxxxxxxxxxxxx --debug```

**Comment by hsaratoga** [comment]
Yes, of course! thanks!!! 

root@raspberry:~# yowsup-cli demos --yowsup --debug --login 346105xxxxxx:LI/jS2Zxxxxxxxxxxxxxxxxxx
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
DEBUG:yowsup.layers.network.layer:Connecting to e15.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="34610550000" mechanism="WAUTH-2">
��3#'��8U���48Cj;���R3�ltl�[$W�)\��]�X�
HEX:c8f033231927aabf3855a604f8853438436a133bb5fd861e5233c16c746c97035b2457fc295c98ed5dcb58d6d80
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
�@��lp��d1k��El
HEX:1ef18e1d08ab40dff46c70838b64316bbcc945xxxxx
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
و���~��5k�2�뇆{������a�r ��@�1�`9�/J
HEX:d98814dee8e77eb4ac13356b148132a0eb87867b14198c99b3ead9cd61009d7220e2e9408c31cd603913b5xxxxx
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1437670465" expiration="1469206465" props="4" t="1438164772">
���`��KC�˂N��z�U
HEX:b0d00100851060b5e54b4385cb824eba867adxxxxx
</success>

DEBUG:yowsup.layers.protocol_iq.layer:starting ping thread.
Auth: Logged in!
[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1437672460" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<message from="34636459xxx@s.whatsapp.net" notify="Rosario" offline="0" type="text" id="1437730589-380" t="1437744030">
<enc type="pkmsg" v="1">
���!|Tv|r���>kk�*'����&�T��V-��o4!z���|)���m{C|/s.�+�O�+h�d��s."B3
!f2�pz'.y���J:��%����� �sĸ.1ˀs"}�Xi"|n`�-���H�A�,�(�0
HEX:3308c8e9a0071221057c54761e7c72f8a0873e6b6bed2a27c7fbe410fa261c8a549cde562da5e16f341a21057a88b4fc7c1f29b0f5fd6d7b437c2f732ee62bc94f0208822b68e764be99732e2242330a21056632f5707a272e79ecf1834a3aefb625b2e5f4cbf00120bb73c4b82e31cb80731002180022107d1bf6586922147c056e60aa2d9b0688c348d641992c15c128d81xxxxxxx
</enc>
</message>

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.3.183', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 327, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 259, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/demos/cli/stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/stacks/yowstack.py", line 167, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/network/layer.py", line 73, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/network/layer.py", line 80, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/__init__.py", line 160, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/__init__.py", line 101, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'
root@raspberry:~#

**Comment by hsaratoga** [comment]
i'm sorry, i'm a newbee. I paste de code in pastebin: http://pastebin.com/hzKNtx3U

**Comment by tgalal** [comment]
thanks, just add --moxie to your command and it should fix it

**Comment by hsaratoga** [comment]
when i add --moxie command i have another problem.   I pasted in : http://pastebin.com/8TEsR2qj

thanks a lot!

**Comment by tgalal** [comment]
please install yowsup from develop branch, it fixes this problem:
https://github.com/tgalal/yowsup/archive/develop.zip

**Comment by hsaratoga** [comment]
Perfect!!! Thanks a lot!!! great work!!  :-)

**Comment by blaksoft** [comment]
yowsup-cli demos -e -c /etc/zapzap.cfg -M
Traceback (most recent call last):
  File "/usr/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.4', 'yowsup-cli')
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1674, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 323, in <module>

  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 229, in process

  File "/usr/lib/python2.6/site-packages/yowsup2-2.4-py2.6.egg/EGG-INFO/scripts/yowsup-cli", line 265, in startEcho

  File "build/bdist.linux-x86_64/egg/yowsup/demos/echoclient/stack.py", line 48, in start
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 195, in loop
  File "/usr/lib64/python2.6/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.6/asyncore.py", line 151, in poll
    read(obj)
  File "/usr/lib64/python2.6/asyncore.py", line 82, in read
    obj.handle_error()
  File "/usr/lib64/python2.6/asyncore.py", line 78, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.6/asyncore.py", line 428, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 86, in handle_read
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 94, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 169, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 105, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
AttributeError: 'NoneType' object has no attribute 'getData'
