### ISSUE TITLE
Axolotl: DuplicateMessageException

### ISSUE THREAD

**Issue by geversoncarvalho** [tgalal/yowsup#978]
Hello guys,

In the last days we have experienced some problems that forced us to use Axolotl, but it was working until today's afternoon. We are using the develop branch as it is the most updated version.

What is happening when running any custom application or even the yowsup-cli is:

./yowsup-cli demos -l 55XXXXXXX:XXXXXXXXXXXX= -e --moxie

Traceback (most recent call last):
  File "./yowsup-cli", line 327, in <module>
    if not parser.process():
  File "./yowsup-cli", line 233, in process
    self.startEcho()
  File "./yowsup-cli", line 269, in startEcho
    stack.start()
  File "/home/geverson.carvalho.dev/yowsup/yowsup/demos/echoclient/stack.py", line 49, in start
    self.stack.loop()
  File "/home/geverson.carvalho.dev/yowsup/yowsup/stacks/yowstack.py", line 175, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/network/layer.py", line 73, in handle_read
    self.receive(data)
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/network/layer.py", line 80, in receive
    self.toUpper(data)
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/axolotl/layer.py", line 103, in receive
    self.onMessage(protocolTreeNode)
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/axolotl/layer.py", line 125, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/axolotl/layer.py", line 210, in handleEncMessage
    self.handleWhisperMessage(node)
  File "/home/geverson.carvalho.dev/yowsup/yowsup/layers/axolotl/layer.py", line 254, in handleWhisperMessage
    plaintext = sessionCipher.decryptMsg(whisperMessage)
  File "/storage/projetos/proj/venv/lib/python2.7/site-packages/axolotl/sessioncipher.py", line 74, in decryptMsg
    plaintext = self.decryptWithSessionRecord(sessionRecord, ciphertext)
  File "/storage/projetos/proj/venv/lib/python2.7/site-packages/axolotl/sessioncipher.py", line 111, in decryptWithSessionRecord
    plaintext = self.decryptWithSessionState(sessionState, cipherText)
  File "/storage/projetos/proj/venv/lib/python2.7/site-packages/axolotl/sessioncipher.py", line 145, in decryptWithSessionState
    chainKey, counter)
  File "/storage/projetos/proj/venv/lib/python2.7/site-packages/axolotl/sessioncipher.py", line 182, in getOrCreateMessageKeys
    "with old counter: %s, %s" % (chainKey.getIndex(), counter))
axolotl.duplicatemessagexception.DuplicateMessageException: Received message with old counter: 2, 1

Is Whatsapp changing its encode/encryption?

**Comment by devilankur18** [comment]
+1

**Comment by devilankur18** [comment]
@tgalal To reproduce this, receive a message but dont sent the receipt and break the connection.

Now on again connect/reconnect, the same message is receive as no receipt is sent, causing duplicates key exception.

**Comment by devilankur18** [comment]
Temporary Solution

Delete the db, in the ~/.yowsup/<phonenumber>/axolotl.db and connect again.
