### ISSUE TITLE
yowsup-cli: AttributeError (for direct text message, group messages are fine)

### ISSUE THREAD

**Issue by rainonwednesday** [tgalal/yowsup#984]
Hi,

When running the yowsup command line client and being logged in, my yowsup registered account can receive group messages, however when sending a text message directly to the yowsup registered account (so no group message), yowsup-cli gives the following error:

note: if I log in and out a bunch of time, the error goes away, but returns as soon as i try sending a direct text again...

Any idea what's going on? Or am I doing something wrong?

```
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:DEBUG:yowsup.layers.network.layer:Connecting to e5.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="XXXXXXXXXXX" mechanism="WAUTH-2">
▒R▒TH_▒s▒^p$ڝ3P▒▒x▒▒0@▒]3}▒▒▒▒fZ▒▒n
HEX:b65207e49554485fc173e1a65e7024da9d1a335085a37883f5023001400103f35d337d8793a4cb665a9b1d826e
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1429558546" expiration="1461094546" props="4" t="1438779576">
▒T▒ӣ+▒l▒8X▒▒▒
HEX:805416ea9dd3a32b34167ff06c12d43858f4c7fe
</success>

DEBUG:yowsup.layers.protocol_iq.layer:starting ping thread.
Auth: Logged in!
[connected]:DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1438098369" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<message retry="4" from="XXXXXXXXXXXX@s.whatsapp.net" t="1438777358" offline="4" type="text" id="1438763456-35" notify="XXX">
<enc type="pkmsg" v="1">
▒F▒#!▒e{▒▒Q)ٱӜ▒w(▒▒&R!▒Q_▒k▒▒a]"B3
q6.▒▒@▒e▒▒▒s▒ƅ7p▒r▒;    "▒E5@▒▒▒▒▒▒S▒▒V▒▒% (▒Ã`0▒▒
HEX:3308cae6e7071221058ab9df48b9ee2e93c1c5bcedb326295e4f437b93f31938c53b72a60dee46e4231a2105cc657b85b85129d9b1d39ce577142891fd265221c1515fa66bee1de061151e5d2242330a2105a81ea989e3220d71362e04a4b440b7659bb0a37312b9c685377001e41e72cf3b100918002210f5bf90453540fe15b917f584ff83ef5305c2c856a7e7252028d3c3836030a5d103
</enc>
</message>

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.3.185', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 327, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 259, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/demos/cli/stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/stacks/yowstack.py", line 167, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/network/layer.py", line 73, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/network/layer.py", line 80, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 160, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 101, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'
```

**Comment by tgalal** [comment]
add --moxie as a command line argument
