### ISSUE TITLE
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead

### ISSUE THREAD

**Issue by kw005** [tgalal/yowsup#985]
Hi, I just installed the latest version and got the folling erro when running "./yowsup-cli demos -c conf -e": Also the fix (commenting out "def _construct(self):") dows not help (see that error respone bwlow please).

# ./yowsup-cli demos -c conf -e
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
  File "./yowsup-cli", line 327, in <module>
    if not parser.process():
  File "./yowsup-cli", line 233, in process
    self.startEcho()
  File "./yowsup-cli", line 269, in startEcho
    stack.start()
  File "/home/y3/yowsup/yowsup/demos/echoclient/stack.py", line 49, in start
    self.stack.loop()
  File "/home/y3/yowsup/yowsup/stacks/yowstack.py", line 175, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib64/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib64/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/home/y3/yowsup/yowsup/layers/network/layer.py", line 73, in handle_read
    self.receive(data)
  File "/home/y3/yowsup/yowsup/layers/network/layer.py", line 80, in receive
    self.toUpper(data)
  File "/home/y3/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/y3/yowsup/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/home/y3/yowsup/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/home/y3/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/y3/yowsup/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/home/y3/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/y3/yowsup/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/home/y3/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/y3/yowsup/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/y3/yowsup/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/home/y3/yowsup/yowsup/layers/__init__.py", line 160, in receive
    s.receive(data)
  File "/home/y3/yowsup/yowsup/layers/__init__.py", line 101, in receive
    recv(node)
  File "/home/y3/yowsup/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
    entity = TextMessageProtocolEntity.fromProtocolTreeNode(node)
  File "/home/y3/yowsup/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
    entity.setBody(node.getChild("body").getData())
AttributeError: 'NoneType' object has no attribute 'getData'

---------------
commenting out "def _construct(self) in ..//yowsup/stacks/yowstack.py return that error:

# ./yowsup-cli demos -c conf -e
Traceback (most recent call last):
  File "./yowsup-cli", line 327, in <module>
    if not parser.process():
  File "./yowsup-cli", line 233, in process
    self.startEcho()
  File "./yowsup-cli", line 262, in startEcho
    from yowsup.demos import echoclient
  File "/home/y3/yowsup/yowsup/demos/echoclient/__init__.py", line 1, in <module>
    from .stack import YowsupEchoStack
  File "/home/y3/yowsup/yowsup/demos/echoclient/stack.py", line 1, in <module>
    from yowsup.stacks import YowStack
  File "/home/y3/yowsup/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/home/y3/yowsup/yowsup/stacks/yowstack.py", line 203
    def getLayer(self, layerIndex):
    ^
IndentationError: unexpected indent

**Comment by tgalal** [comment]
uncomment what you've commented and add --moxie as an argument:

./yowsup-cli demos -c conf -e --moxie

**Comment by kw005** [comment]
Hi,

I still get this error:

# ./yowsup-cli demos -c conf -e --moxie
WARNING:yowsup-cli:--moxie/-m is deprecated and will be removed soon as e2e encryption is now almost mandatory.
Traceback (most recent call last):
  File "./yowsup-cli", line 327, in <module>
    if not parser.process():
  File "./yowsup-cli", line 233, in process
    self.startEcho()
  File "./yowsup-cli", line 262, in startEcho
    from yowsup.demos import echoclient
  File "/home/y3/yowsup/yowsup/demos/echoclient/__init__.py", line 1, in <module>
    from .stack import YowsupEchoStack
  File "/home/y3/yowsup/yowsup/demos/echoclient/stack.py", line 1, in <module>
    from yowsup.stacks import YowStack
  File "/home/y3/yowsup/yowsup/stacks/__init__.py", line 1, in <module>
    from .yowstack import YowStack, YowStackBuilder
  File "/home/y3/yowsup/yowsup/stacks/yowstack.py", line 204
    def getLayer(self, layerIndex):
    ^
IndentationError: unexpected indent

**Comment by tgalal** [comment]
uncomment what you've commented out,  restore the file exactly as you installed it in first place

**Comment by kw005** [comment]
Ah, Ok. That workds fine. Thanks a ton !!!!

However, when I am sending a message from my cell phone to the Linux server, I get immediately the same message back on my cell phone which I sent...? How can I just catch the messages users are sending to me?

**Comment by tgalal** [comment]
read the docs

**Comment by kw005** [comment]
I did.I don't see the feature. Can you please help me out shortly?

**Comment by kw005** [comment]
Looking at your docs at
    https://github.com/tgalal/yowsup/wiki/%5BLegacy%5D-yowsup-cli
would provide -l listing to messages
Looking at 
   https://github.com/tgalal/yowsup/wiki/yowsup-cli-2.0
does not. What seems to be right. This is quite confusing. I still do not see the possibility just to listing to new messages.

**Comment by naveen1988** [comment]
I have installed yowsup in my linux server, I have registered my number using "python yowsup-cli registration --requestcode sms --phone 91xxxxxxxxxx --cc 91 --mcc 404 --mnc 45" command and i got a reply with password. I updated config file with new password. But still i am unable to send message using command line interface "yowsup-cli demos --config config.txt --send 91xxxxxxxxxx "Hello world"".
I am getting the following output 

WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
Traceback (most recent call last):
  File "yowsup-cli", line 323, in <module>
    if not parser.process():
  File "yowsup-cli", line 231, in process
    self.startSendClient()
  File "yowsup-cli", line 280, in startSendClient
    stack.start()
  File "/yowsup-2.4/yowsup/demos/sendclient/stack.py", line 54, in start
    self.stack.loop()
  File "/yowsup-2.4/yowsup/stacks/yowstack.py", line 195, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.6/asyncore.py", line 210, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.6/asyncore.py", line 151, in poll
    read(obj)
  File "/usr/lib/python2.6/asyncore.py", line 82, in read
    obj.handle_error()
  File "/usr/lib/python2.6/asyncore.py", line 78, in read
    obj.handle_read_event()
  File "/usr/lib/python2.6/asyncore.py", line 428, in handle_read_event
    self.handle_read()
  File "/yowsup-2.4/yowsup/layers/network/layer.py", line 86, in handle_read
    self.receive(data)
  File "/yowsup-2.4/yowsup/layers/network/layer.py", line 94, in receive
    self.toUpper(data)
  File "/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/yowsup-2.4/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/yowsup-2.4/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/yowsup-2.4/yowsup/layers/stanzaregulator/layer.py", line 51, in processReceived
    self.processReceived()
  File "/yowsup-2.4/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/yowsup-2.4/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/yowsup-2.4/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/yowsup-2.4/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/yowsup-2.4/yowsup/layers/axolotl/layer.py", line 126, in receive
    self.toUpper(protocolTreeNode)
  File "/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/yowsup-2.4/yowsup/layers/__init__.py", line 169, in receive
    s.receive(data)
  File "/yowsup-2.4/yowsup/layers/__init__.py", line 105, in receive
    recv(node)
  File "/yowsup-2.4/yowsup/layers/auth/layer_authentication.py", line 71, in handleSuccess
    self.toUpper(nodeEntity)
  File "/yowsup-2.4/yowsup/layers/__init__.py", line 59, in toUpper
    self.__upper.receive(data)
  File "/yowsup-2.4/yowsup/layers/interface/interface.py", line 98, in receive
    self.callbacks[entityType](entity)
  File "/yowsup-2.4/yowsup/demos/sendclient/layer.py", line 35, in onSuccess
    self.toLower(messageEntity)
  File "/yowsup-2.4/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/yowsup-2.4/yowsup/layers/__init__.py", line 173, in send
    s.send(data)
  File "/yowsup-2.4/yowsup/layers/__init__.py", line 111, in send
    send(entity)
  File "/yowsup-2.4/yowsup/layers/protocol_messages/layer.py", line 15, in sendMessageEntity
    self.entityToLower(entity)
  File "/yowsup-2.4/yowsup/layers/__init__.py", line 115, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/yowsup-2.4/yowsup/layers/__init__.py", line 63, in toLower
    self.__lower.send(data)
  File "/yowsup-2.4/yowsup/layers/axolotl/layer.py", line 107, in send
    self.handlePlaintextNode(node)
  File "/yowsup-2.4/yowsup/layers/axolotl/layer.py", line 190, in handlePlaintextNode
    ciphertext = sessionCipher.encrypt(plaintext)
  File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/sessioncipher.py", line 38, in encrypt
    sessionRecord   = self.sessionStore.loadSession(self.recipientId, self.deviceId)
  File "/yowsup-2.4/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 47, in loadSession
    return self.sessionStore.loadSession(recepientId, deviceId)
  File "/yowsup-2.4/yowsup/layers/axolotl/store/sqlite/litesessionstore.py", line 20, in loadSession
    return SessionRecord(serialized=result[0])
  File "/usr/lib/python2.6/site-packages/python_axolotl-0.1.7-py2.6.egg/axolotl/state/sessionrecord.py", line 16, in __init__
    record.ParseFromString(serialized)
  File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/message.py", line 186, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/internal/python_message.py", line 859, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/internal/python_message.py", line 892, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/lib/python2.6/site-packages/protobuf-3.0.0_alpha_1-py2.6.egg/google/protobuf/internal/decoder.py", line 652, in DecodeField
    raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

Please anyone help me how to fix it. Thanks in advance
