### ISSUE TITLE
Message recieved and bugged

### ISSUE THREAD

**Issue by LorenzoSip** [tgalal/yowsup#991]
[offline]:/L
Auth: Logged in!
[connected]:Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.3.185', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 327, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 259, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/demos/cli/stack.py", line 25, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/stacks/yowstack.py", line 167, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/network/layer.py", line 73, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/network/layer.py", line 80, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 55, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 160, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 101, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/protocol_notifications/layer.py", line 41, in recvNotification
    self.raiseErrorForNode(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/yowsup/layers/__init__.py", line 117, in raiseErrorForNode
    raise ValueError("Unimplemented notification type %s " % node)
ValueError: Unimplemented notification type <notification retry="1" from="s.whatsapp.net" t="1439145578" offline="1" type="encrypt" id="3255026529">
<count value="0">
</count>
</notification>

**Comment by tgalal** [comment]
Add --moxie as a command line arg

**Comment by LorenzoSip** [comment]
What did you mean?

**Comment by tgalal** [comment]
yowsup-cli demos --yowsup --moxie [rest of args]

**Comment by LorenzoSip** [comment]
thnx! (close)

**Comment by arevindh** [comment]
An error message is showing as its will be depreciated . Is there any permnent fix for it ?
Sorry for i am a noob to this ..

**Comment by tgalal** [comment]
next release will have encryption opt-out instead of opt-in, which will fix this problem, unless one explicitly chooses to see it :)
